### ISSUE TITLE
could you add rtmp or rtsp sever in this project

### ISSUE THREAD

**Issue by cudnn** [pedroSG94/rtmp-rtsp-stream-client-java#1]
could you add rtmp or rtsp sever in this project !

**Comment by cudnn** [comment]
could you add rtmp or rtsp server in this project ! or  add a simple streamer server

**Comment by pedroSG94** [comment]
At the moment I have no plan to add a server in this project. However you have free options for RTMP server for test with red5 media server:  http://red5.org/.
I use VLC app for capture stream from server in mobile or desktop.

**Comment by cudnn** [comment]
Thank you ,only p2p streamer is ok
