### ISSUE TITLE
Can't play rtsp 

### ISSUE THREAD

**Issue by uldara1** [pedroSG94/rtmp-rtsp-stream-client-java#10]
hi could you tell me how to stream from rtsp link. i use with vlc it work ok

rtsp://mpv.cdn3.bigCDN.com:554/bigCDN/_definst_/mp4:bigbuckbunnyiphone_400.mp4

**Comment by pedroSG94** [comment]
Maybe i dont understand the question but, this library is for stream to a media server not for play a stream.
So this is a rtsp **Client** not player.
If you want a player you can use native MediaPlayer:
[https://developer.android.com/reference/android/media/MediaPlayer.html](url)
Anyway you can use a trial version of wowza if you want test this library. Use readme for example code.

**Comment by uldara1** [comment]
thank you for your reply, i had try with Mediaplayer but it not smooth ,sometime it can play and sometime can't play , it's shown can't play this file.  anyways thank you :)

**Comment by pedroSG94** [comment]
You can try with this:
https://github.com/mrmaffen/vlc-android-sdk
