### ISSUE TITLE
How to overlay image or text in rtmp live camera 

### ISSUE THREAD

**Issue by PongPloy2016** [pedroSG94/rtmp-rtsp-stream-client-java#1001]
How to use Overlay text and images live stream Flutter when Live Streaming in camera or icon  appears stretched
in pic exmaple

example : https://medium.com/flutter/how-its-made-i-o-photo-booth-3b8355d35883 for example web

![image](https://user-images.githubusercontent.com/8625469/144719490-8ac6df1e-2d31-4b10-b134-937138c7b1c9.png)

i want create for mobile app in example Here Please help  
![image](https://user-images.githubusercontent.com/8625469/144719583-2e6cfb59-2876-4dd8-b305-bd8aa049b855.png)

**Comment by pedroSG94** [comment]
Hello,
To avoid text or icons stretched you must set resolution depend of original text or icon size.
You can do it like in this issue:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/990#issuecomment-979862317
In this case the originalWidth and originalHeight is the bitmap getWidth and getHeight methods.
For text I found that you can't get bitmap size of the text so I recommend you use Image filters only and produce the text bitmap manually with the methods used in text filter:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/utils/gl/TextStreamObject.java#L62

**Comment by PongPloy2016** [comment]
ok bro thank you good. exmaple ^_^
