### ISSUE TITLE
Failed to publish to RTSP server after leaving the screen still for a few second

### ISSUE THREAD

**Issue by lchy12345** [pedroSG94/rtmp-rtsp-stream-client-java#1006]
Hi pedroSG94,

I am using DisplayService and RtspSender. I am capturing my phone screen and publish it as a RTSP stream to a RTSP server. I found that if I do not move the phone screen for a few second, there will be log "RtspSender: Skipping iteration, frame null" and then it stops publishing to the server. Do you have any idea on how can I still publish the screen even it is not moving?

Thank you so much.

**Comment by pedroSG94** [comment]
Hello,

Maybe this is related with your case:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/960
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/63

**Comment by lchy12345** [comment]
thx. #960 resolved my problem.
