### ISSUE TITLE
After muting mic and then unmuting again isAudioMuted() always returns false

### ISSUE THREAD

**Issue by MTayyabSarfraz** [pedroSG94/rtmp-rtsp-stream-client-java#1012]
@pedroSG94 here is my method of  muting/unmuting mic.

but there seems to be issue when I mute the mic by this code and then try to unmute again the method **`rtmpCamera1.isAudioMuted()`** is returning false ,even though the I've enabled the mic as you can see the code bellow.

` private void micController() {
        if (rtmpCamera1 != null) {
       
            if (rtmpCamera1.isAudioMuted()) {
                rtmpCamera1.enableAudio();
                ivMic.setImageDrawable(getResources().getDrawable(R.drawable.ic_svg_mic_on));
            } 
            else {
                rtmpCamera1.disableAudio();
                ivMic.setImageDrawable(getResources().getDrawable(R.drawable.ic_svg_mic_off));
            }
        }
    }`

**Comment by pedroSG94** [comment]
Hello,

It is fixed now:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/c957d9f3626068ae88409a8a926c301d43860e17

The error was only if you call is before prepareAudio method

**Comment by MTayyabSarfraz** [comment]
@pedroSG94 thanks bro.... will you merge it to master or should I close this issue myself?

**Comment by pedroSG94** [comment]
It is already on master. Issue closed
