### ISSUE TITLE
How to switch off BaseRtpSocket logs?

### ISSUE THREAD

**Issue by ArqinT** [pedroSG94/rtmp-rtsp-stream-client-java#1013]
Hi!

Can I switch off log messages like this:
`2021-12-17 12:01:23.632 945-1069/ru.universesoft.acs I/BaseRtpSocket: wrote packet: Video, size: 44, port: 60096`

**Comment by ArqinT** [comment]
Found myself. Thx!

**Comment by ArqinT** [comment]
Trying to set rtspServerCamera.setLogs(false) - but logs spamming

**Comment by pedroSG94** [comment]
Fixed here:
https://github.com/pedroSG94/RTSP-Server/commit/029657130d96eca6c14345f8df0a95877f0e2fa1
Please, next time open the issue in RTSP-Server if you are using it or let me know that you are using it to avoid confusion.

**Comment by ArqinT** [comment]
Ok. Thx. Waiting for release with this bagfix
