### ISSUE TITLE
Support for AES encryption

### ISSUE THREAD

**Issue by egrgdam** [pedroSG94/rtmp-rtsp-stream-client-java#102]
Thanks for great lib!

It would be great to have support for AES encryption, meaning encrypting video/audio chunks with AES 128, 256.

There is a simple lib for that which may be used: https://github.com/scottyab/AESCrypt-Android

Best

**Comment by pedroSG94** [comment]
You can send stream with tls socket that encrypt your stream. Anyway I have not a server to test this feature so I can't implement it for now.
If you know some sever that support it, share it, and I will have a look

**Comment by egrgdam** [comment]
Thanks for the reply.

you are correct about server side. I'll check if I can create some custom module for Wowza stream engine...
