### ISSUE TITLE
CameraBase: Cannot startPreview after prepareVideo

### ISSUE THREAD

**Issue by kow08absty** [pedroSG94/rtmp-rtsp-stream-client-java#1020]
Hi, thanks for the useful API.
I have a question about your API.

Is it possible to specify the fps when `startPreview()`?
OR, can I exec `startPreview()` after `prepareVideo()`?

I cannot get preview screen after `prepareVideo()`.
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/916d3a7f1bb9bd6e8868cbcdb0ebf611e3d5d7ae/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L270
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/916d3a7f1bb9bd6e8868cbcdb0ebf611e3d5d7ae/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera2Base.java#L310
I guess these lines should be `onPreview = false;`. I got all source code, modified it, compile and works fine.
Are there any other issues after applying this mod?

## Tested Envs

Android Studio: Arctic Fox | 2020.3.1 Patch 4 Build #AI-203.7717.56.2031.7935034, built on November 21, 2021
Runtime version: 11.0.10+0-b96-7249189 amd64
Phone: ASUS X018D Android 9 (Pie)
RTMP Server: Ubuntu 20.04 nginx

Thanks a lot ;)

**Comment by pedroSG94** [comment]
Hello,

I did a commit for it:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/e50f33fc27f56e5947b9b097f04047946b98816e
Now you can call startPreview with fps parameter. You only need update library version to 2.1.5

**Comment by kow08absty** [comment]
Thank you for your commit. I got it.

I created this issue because the Surface is displayed differently when `startPreview()` and after `startStreaming()`, and cannot execute `startPreview()` after `prepareVideo()`.
I get version 2.1.5, these problems are gone...

What happen?

For now, it's working as expected. I want to keep using this library. Thank you!
