### ISSUE TITLE
Cannot Import SrsFlvMuxer

### ISSUE THREAD

**Issue by publioelon** [pedroSG94/rtmp-rtsp-stream-client-java#1021]
Hello, i am trying to use this library to stream videos so I downloaded the libraries manually (encoder, rtmp, rtplibrary, rtsp). The problem is that i am trying to declare the parameter` private SrsFlvMuxer srsFlvMuxer; `However the library cannot be found to be automatically imported inside the code. Is there anything I need to do to import it?  From what I was looking the library that imports it is this one: `import net.ossrs.rtmp.SrsFlvMuxer;`  But there isn't any of that in library that I downloaded

**Comment by pedroSG94** [comment]
Hello,

RTMP module was totally refactored and migrated to kotlin in library version 2.0.3 so SrsFlvMuxer is not available anymore.
SrsFlvMuxer was replaced to RtmpClient class. You can see an example here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtmp/RtmpCamera1.java

As you can see it is really similar to SrsFlvMuxer.
