### ISSUE TITLE
Error configure stream, RTSP/1.0 500 Internal Server Error

### ISSUE THREAD

**Issue by jp1017** [pedroSG94/rtmp-rtsp-stream-client-java#103]
```
[ (RtspActivity.java:353)#onConnectionFailedRtsp ] Error configure stream, RTSP/1.0 500 Internal Server Error
Server: EasyDarwin/7.3 (Build/17.0325; Platform/Win32; Release/EasyDarwin; State/Development; )
Cseq: 2
Session: null
```

**Comment by pedroSG94** [comment]
Yes, I know it easydarwin server doesn't support RTSP command used in this library to connect. I need develop a specific connection for it. The command is announce or record, I dont remember good.

**Comment by jp1017** [comment]
Hope for that. Thank you!

**Comment by pedroSG94** [comment]
EasyDarwin is now working on version 1.2.8:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/3204f723a1393bc164c59f45954ef7a13b58d5a6

**Comment by jp1017** [comment]
@pedroSG94 Thank you. `announce` is ok, but `SETUP` return 500 still.

**Comment by pedroSG94** [comment]
EasyDarwin server is working for me. I tested with the official server from here:
https://github.com/EasyDarwin/EasyDarwin
I use Ubuntu 16.04. Steps:
- Compile in x64 using: ./Buildt x64.
- Execute server with: sudo ./easydarwin -c ../WinNTSupport/easydarwin.xml -d
- Stream to endpoint: rtsp://ip:554/live/pedro
Only work with TCP protocol.

**Comment by jp1017** [comment]
Yours: OPTIONS rtsp://192.168.178.28:554/live/pedro RTSP/1.0

I compile server successful but I can't to set the ip, 

How to set the ip and the path: /live/pedro

**Comment by pedroSG94** [comment]
you only need see the ip of your pc where you installed easydarwin server, in my case is 192.168.178.28 (local ip server).
Linux command: ifconfig
```
Direc. inet:192.168.178.28
```
"live" is the default application name of easydarwin and "pedro" is a random stream name that I used. You can change it.

**Comment by jp1017** [comment]
121.40.50.44 is worked from: https://github.com/EasyDarwin/EasyDarwin/blob/master/EasyDarwin_Cloud_Windows.md

so, the error comes from my real server?

**Comment by pedroSG94** [comment]
I don't know. :(
Try compare application configurations (I don't know how to do it, but you should have any file with that).

**Comment by jp1017** [comment]
Another one responsible for the server, so we'll check it tomorrow, thank you for your great job.

**Comment by jp1017** [comment]
DNS results in the problem. When the Client use ip to connect, it succeed.

**Comment by felipebutcher** [comment]
Hi there! maybe this helps... this happened to me with some cameras that don't allow multiple connections. I had another computer using the rtsp stream and getting this exact error message. Closing the connection on the other computer solved.
