### ISSUE TITLE
Excuse me, does the streaming address have to have a port number？

### ISSUE THREAD

**Issue by iqiluwxy** [pedroSG94/rtmp-rtsp-stream-client-java#1032]
Excuse me, does the streaming address have to have a port number？

**Comment by pedroSG94** [comment]
No,

You have a default port for each case:
- RTSP -> 554
- RTMP -> 1935
- RTSPS -> 443
- RTMPS -> 443
If you are not using that port in your server, you need indicate it in the address.

**Comment by iqiluwxy** [comment]
ok，Thank You!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Pedro ***@***.***&gt;; 
发送时间: 2022年1月7日(星期五) 下午4:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pedroSG94/rtmp-rtsp-stream-client-java] Excuse me, does the streaming address have to have a port number？ (Issue #1032)





 
No,
 
You have a default port for each case:
  
RTSP -&gt; 554
 
RTMP -&gt; 1935
 
RTSPS -&gt; 443
 
RTMPS -&gt; 443
  
If you are not using that port in your server, you need indicate it in the address.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
