### ISSUE TITLE
Forward H264 over RTSP

### ISSUE THREAD

**Issue by anilmaddala** [pedroSG94/rtmp-rtsp-stream-client-java#1033]
I have a H264 video stream coming in from a server as a byte[]. 

How can I forward it over RTSP? Is there a sample code I could refer to?

**Comment by pedroSG94** [comment]
You can use directly RtspClient class.
Example:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtsp/RtspCamera1.java

You only need to focus on this:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtsp/RtspCamera1.java#L192
- ByteBuffer -> You need convert byte[] to ByteBuffer
- MediaCodec.BufferInfo -> You can create an instance of it and set timestamp (ts in microseconds), flag (value 1 normal frame, 5 keyframe) and size (bytebuffer size in bytes) parameters depend of your buffer.

https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtsp/RtspCamera1.java#L187
You need call it a time to indicate videoInfo before or after connect method to stream. Normally, you can extract sps and pps from keyframes. You can use this method for it:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/c3afe264acd1715276a8119650557797678e6b18/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L356

**Comment by anilmaddala** [comment]
Thank you! How can I determine the flags to be set?

**Comment by pedroSG94** [comment]
As I told you 1 for "normal frames (no IDR)" and 5 for keyframes (IDR). You have a table with nal unit values here:
https://yumichan.net/video-processing/video-compression/introduction-to-h264-nal-unit/
You can check nal unit type like here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtsp/src/main/java/com/pedro/rtsp/rtp/packets/H264Packet.kt#L55
Remember avoid modify buffer (that code modify the buffer because extract the header). You can study the way to extact the header and adapt that code. The easier way is duplicate BytteBuffer class and use that duplicated buffer for this operation.

**Comment by anilmaddala** [comment]
Got it. I am using [rtsp-simple-server](https://github.com/aler9/rtsp-simple-server) to run the RTSP server.
The H264 server also provides information if the current video byte[] is an IDR. Does this implementation look correct? 

   @Override
    public void onVideoFrame(@NonNull byte[] frame, int size, boolean isIdr) {
        ByteBuffer h264Buffer = ByteBuffer.wrap(frame);
        info = new MediaCodec.BufferInfo();
        info.size = size;
        info.offset = 0;
        info.presentationTimeUs = System.nanoTime() / 1000 - presentTimeUs;
        if(isIdr  && !rtspClient.isStreaming()) {
            presentTimeUs = System.nanoTime() / 1000;
            info.flags = MediaCodec.BUFFER_FLAG_KEY_FRAME;
            Pair<ByteBuffer, ByteBuffer> videoData = decodeSpsPpsFromBuffer(h264Buffer, size);
            ByteBuffer newSps = videoData.first;
            ByteBuffer newPps = videoData.second;
            rtspClient.setVideoInfo(newSps, newPps, null);
            rtspClient.connect("<rtsp://<rtsp-server-IP>:8554/mystream");
        }
        rtspClient.sendVideo(h264Buffer, info);
    }

**Comment by pedroSG94** [comment]
Close but not correct at all. Try this:
```java
  public void onVideoFrame(@NonNull byte[] frame, int size, boolean isIdr) {
    ByteBuffer h264Buffer = ByteBuffer.wrap(frame);
    info = new MediaCodec.BufferInfo();
    info.size = size;
    info.offset = 0;
    info.presentationTimeUs = System.nanoTime() / 1000 - presentTimeUs;
    if(isIdr) {
      info.flags = MediaCodec.BUFFER_FLAG_KEY_FRAME;
      if (!rtspClient.isStreaming()) {
        presentTimeUs = System.nanoTime() / 1000;
        Pair<ByteBuffer, ByteBuffer> videoData = decodeSpsPpsFromBuffer(h264Buffer, size);
        ByteBuffer newSps = videoData.first;
        ByteBuffer newPps = videoData.second;
        rtspClient.setVideoInfo(newSps, newPps, null);
        rtspClient.connect("<rtsp://<rtsp-server-IP>:8554/mystream");
      }
    }
    if (rtspClient.isStreaming()) {
      rtspClient.sendVideo(h264Buffer, info); 
    }
  }
```
With this you avoid send video until you connect and keyframe flag is correctly send (previously it is only set the first time)

**Comment by anilmaddala** [comment]
Thank you!. I have tried this code and no crashes but the output on the receiving player seems to be corrupt. This is the ffplayer log.
`Initialized opengl renderer.
[rtsp @ 0x7f44ec000b80] SDP:aq=    0KB vq=    0KB sq=    0B f=0/0   
v=0
o=- 0 0 IN IP4 127.0.0.1
s=Stream
c=IN IP4 0.0.0.0
t=0 0
m=video 0 RTP/AVP 96
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1; sprop-parameter-sets=ZYiEDzxGKAAZ9ESfxHqI7STybkkck8R+k5JFJycmKxE+pJlJxEgv+Tck7iJ3aSLk5IpyckY5JXJKpOTk3JycnJFKTUm5OSLFxGtScm5OSZSRDknFGSWTk5JlJOpIlycmpOTk5OSMUnJMKyRLkiFJGi5JnJK5NScmojfpOTkiFJxEW9SQsG/CJxQxz5I9ScnNJ6uup65OTrrrvvvrrl6lk6mdSuouuox3CN9Qk61XXNFu99ddRyrVddSi76nrk7mVRTrFaja61fWr5Im+uuuuuuoUdTuuuupXXXWpv0nXXXNvVfIvt/gkCWsf6YXVz33I66iHXU7vvrrrrrcvfXXJyd8R+qWpa666hByS1LfXUfXXULKtV3utVPWq6776jHUa6666kVdR9ddRSrrd9d9RArUtTKpVe6lrrU36uuuplNK9VzQkHwPAOe0GVXXXJ11111I766nrrdd99ddcnXT1PXUU6ja676665u9dddQkq66lV8nUtddRxe4kVrVz31EK5blrvvVyO+omu+4QddS1q+p66mVT1113FKpa5oQD4HgX9MIqu++9XzepO5a3XUtddc36uutyd9dd8j1PXXXUY66lV9c07vXXcYr1J1utV1Equuuo5y7qNrrqZVLXUtdSKuup3NF+rqFHW61fU9ddddddbqKVdc8YHw8C/mhVSCrvuZT/rln/VuupXUjklvvrrrrqWTrmn9fXXXXUU6lrrrrrrd9dRivqdVI66lVarrvrqKcka76lqKVarqWpa5O5Hcs0vq6676ilJ11qXk6663UQqlrmjgLuKkN+4kYZCf0/60eTuJvrwA==,ZQDwiIQETxGKAAX9JqTklFZOTklUnJuTcnJycnJycnJycRr+TcRPaSMcnJKpOTcksnJyRSklUnJuSZSak4iNepOTkhIQ8kbJyTqSIUmpNSSuTk5NSbk3JLEfpOIk1JyakkcnJIpNREr9JuTUm5OSRScRHAui4bSIjVIuTSe74j1Jybk4iV3rvqWXrrk5Oup666665ot+rrrk6666666666hZXKq63XXXW666iHUp+omtX11q911131zT+rrVddRSrrqRVqup5O+uplXNHB8DwL+eNV596nW9raLfP3vnnvfUzrrrqWuu5a6661JzS+rrvrrk6i3fXUcq63XXXUQq63XWq1XU9dRDqQVuLvrqRXq5ZOupa65ol+k75O+++45111qb9XJPXffNDAfDwL+aEYAe+bd755dX2t8vJ1LUcqnvqVV111311Kq666766677Ymu+uop3111EKp6666mVaqd331GOo111LUQq1Utddy31zSv1z11MpO+uop111Iq63ctddf8iyL8FQSBZgh3f5o8U4nTmUnPLYvl7777775u9dTycnU9dam/ScnXfXXXfXXXT11PfXXXUIKtV1uutVqt1PXUU6lFalqWuuuuuuuut1LXXJ111111CCqNVxDqWuuv+RZF+EQkC8UxEIigZBOJOf3paWln1eeT0+vT/r4jvfgAAAAFlAG4iIQFDxGKAD6I7ybiJ7STySOTklUR+k5OSWIlepOSKck8nJLJycnJycRN/JuTk5IpSak3JO5JlEa1JqScVk5JnJIKxE7tETq8nJMpNSSycksnJxEj9JPJLJyTKTk5JlJI4iV6k4jFPpOSRySycnEQkBL2pUC8UxEaLkR0InWpOTk5OTk5OI/ScnJydRDmkuqep3XEfq666lrrrrrrqeouuuuuaO9XXXUUq1W6ldc0y1NKvXupakdTOp3UquW4hXqpa6lrrrqWuupFW5Ouuu+4pVLUzueuuaEgJ7a5RpUIiRQyT3Pa2tra2tra2t98/6++oguE654m9Supa661XUtcnXXXXUbXNu9dc0Veuuo5Vqt1uutVqt3O76iHWK1LUTXXXXXXXXNv19999ddRSuWTvrVddS3zQsCqurL//sERarGaSLV8/6+f9fP/Xz/r5/61vn/pObF2uRxE+pOf9UsnfN3rqWuuae8nXXXXTLXNFerrk666inUrrqZV1K66kdbrqLVdRCudV111LXNv1ddddddarrrqZV1I6nrmhA+9GSCDhV6f51IS61tbW1nV+nXla2traKck1aOtotFdW2/2i2td9d9dsXXXJ3quuuomuuuuunk65pr131Mrkdd9YuolXFOom4h3ut3PU6vqIVdS31zRP9RDueuuuuuplfXXXXfW4iX1c0KBaoxXJPP2k7lvd9rffPJa++I7V11q+pBPC8/ef9ffUIzd75O+u+uuuupa5OuuuuopX1u+plUSq63fUjrddRKrqIVT1111PXXXNL6uuuu+uTvrrqEHU9c0IBc4HfUTXUs/e+uuuabFXN3JvHrmx9lcn8e1n6dNcAAAAAWUAKoiIQFDxGKAxx8nJycnJyTDqiITcfpNyTKSJUkzkiZOTcnJuTcnJqTiO8mpOTkinJuSRSYuSWTcnJIKySuI3aSVRGryTKSdSbk5OSdySycnJycnJycnJyckYpOTk1JisnERgXOOnl/iP0nJycR2k1JycnJycnJLJycksnJza/vn733zzevqIHFJCN8nfXU8nXXXXJ31111EOu+ohVFqut3EOouu+tV1ydddcnXXW5Ja666666ilXXXXfNGG/TTr1cnP6vn9Wtotraz97REj+p+98/e+J73xHebVp/08lppC5mn+U/af5Ty8q6hO+u+u+TrmlvXJ3111111CCqJF3EO4l1M6ld9davqRVOqkdzyd9dbvrrrrrd8nXJ111CQdK0p6ncnXfPIrSc/a+ftP+n7Xyd97Re+f1P4p/Ui3zTFwyMj71Pnyp5dXtH8UvE/p9eqQnNC95OplXXXJydS11333111FKTrd9bqJrvrV9d8nfXNu98nfcik66lvk65OTvvlhYurJ1G3LLGNqe+upa666665u08liftffffP2vmmajz6XTzr063iF5Sdc0vr5Ou5a75pL3LJydd9S11111EC67kc8S731111yddddyz6vXJ111yddddcktddddd8kMGeomu+Tc/qXd8vLyd99ddbvn7yd9999bn711z9r60i8vLzT6rqINxHepa7lUnJ13ufvfXN3vn731LXJyS111FK5a666lvk666775O+5nJ3LJ1111311111zRV61P3riO96ReTcnXXXXXXXXgAAAAAWUAOYiIQEzxGKAMdpOTk3JycnJuTk4icV1JuSZRG7yTuTkmUnESu0nJLJEKI3eTck6k1JycnJySuI7ScnJILk5OSVyak4jvJyRjT4id2k4id3k5OTk5IhyTqIkVpJZOIkvJycR2iNXk1ESek1JycmpOTk5OTk5OTk5NScnJ1u+93ydddddZeu+ed3m3apa7766665OTqMV6lluWTqeTrrrrrrriJPV11ydxDqd31111133yd99ddbrk5O++XuKSJ33F3yddddc03q5v1c36uuuuuuuutV311PJ1111quupFUtyK5FJ11LXW7lqe+++Tk675o69aS673crqeutSd9999dddarrd9dcnXXfcik7kcnJ33ydc36u5b7763fXXXffXe4jd6kddRbrvk766666kcnXcQmol11uuuuuuubvXczk73c998nffct9dddddzKuuu++Trrvk5+98nJydd9997vk5O++++uubepO++931ycnfUtdarrvrrk675e+pHNLeuTvuZXq++upa5O+Tk7kUvJPfffXXXXWq7766675Ouu++Tvvrvd8nfXUivk6663fgAAAABZQARgiIQEjxGKAAR9EfpOTcnJycR3k5JXJLJycnJyTOIleoj9JMoie0nJxG7yckyk5NRE71Eb9JySKTk5JVJyTOTcnJyRMnJqI7ScR6k3JqI/SckQ5NSSyak3JycnJycnJLJycR3k5OTk5JlJycnJyTGw/aSJURI/RHeSdyc2/7675Ouaa9Tu+uuuuupnXfP2ueuuu+++u+5nXXJPJ1yd9c/aTk77666lrn/V11311Mq3XXXWr5O+uuuuuuuuohovL3LJz/r5Obd7lrrqR33LP3vn7311q+utV13yd96l66lrrrqZVLXfepOuuu++upXXXXXJ333zd66667765ohXnn9fXXXN+k76665pvVq9T/r3ct9ddd98nXXXXXXXXUivrrk6666665O5b77665Out13311333u+uu+++utSd9dddddc3euTvvvdd999yK+eT197T6nd9ddS331113331111113yd99dd988lr755VaTvk777iFUtRN9dRCk6lvvrvuRXPfffffJ3yd999dSKfvffXXXffP+vrrrqR133uuupa6666kUnXXXXXU9ddddcnXNrUnfN2rrrqIUnfXXWr1XUTXUivrruRX3PJLfXXXXXXXXXffffJ311111111111zxV7nrvvrrrrrrVdcnffXXXgAAAAFlABVCIhARPEYoABX+Tk4iZ+k5JZNREu0ksm5OTk5OTiNek5OTk5JlJI5OSeTk5OSWTkmUksnJycnJyTOSWSWTk5NSbk5NScnJycnJycm5OTUnJycnJEKTk3JycksnJLJycnJycnJGKTkncnJycks0j9XN+vvn9V11yS333Mrlk6666665O+++9Xyd9ddbrrrrrrrqRSdSu+uupa666667761XXXXJ31111111111113131GNPl5eom5b755tX111uuutV1M7lrrrrV9dT111333133uuuuuu4hpdcnXc9davuW+uuub9XNJ6p1XPJ6+TruW++++uuuuoxSddS1111quu+4hJRNdc3qub9ct9c/6ueS99c2vX1111uu++TknrrrrrvuZXyc8/r75+98nJ333Ir5Ouuuuupa6mVddS1yddS111311113MpO++Tvk61fXXNJqtXLEdp/18nXUyvuW5Z/1qr77ilepOp661fJyS333333zyeuVxH6uuupa66667666iHct8nXXXJ11u+pFfXU9dbvk6665OTrrrvvrrrrvwAAAAFlABhiIhATPEYoAD6Tcm5OI1eInXpOTk5OTk5NScmojdpOTckrk5JFJIpJEiTuTUnJySycnJIpNyRIrJycR3k5OI7ScnJycnJyRDklcnJqTk1JycnJyckjk1Jybk3JqTk5J3JycnJyRSk1JK5JZNySKI1aTiO8kjiJ7VIpOI1/JLXfXXWr7lvqR1311uu+5a77ilebC8nXUrvk776nrqZXycvfctdddS133ydak7766ilXXcty3ycnXXUjrrrV9yKXuWuuaW18kYk+p75OaR3rrqWutV1quut31quutScktyyddRSrVdyOpXfJzz+vvrvvrrvvrqW+uuuplJ13LXfXXfJ11M766lrrqZXyd96k7nrvVddcR3ruZX1LXXXN+rk75v16rrrvk7661fJ333z/q5O+f9ffXXXUivuW+uupXfXXXXXXffW5OTvqR33yd999dak677765OplJLXJLUt9d999cRNe+tzb9XWr4iX+++++++ubXr755vVzSi/T95OuuTrrrrFb5/1ddYuTqZ3PfXUtddddddSO+uTqWu++u++uu++Tk666667775OupFffLyc+73131IrnVdbrrrrrqIU8vr766665OTvrrrrrdyuuaT1ddSKaX1TOaX1dTKWW++9Xy9S1LXXXXXUtSK+++XqRydS1331113ydRCvV9d8nU9TO+u+u9y+A
a=control:trackID=0
m=audio 0 RTP/AVP 97
a=rtpmap:97 MPEG4-GENERIC/32000/2
a=fmtp:97 profile-level-id=1; mode=AAC-hbr; config=1290; sizelength=13; indexlength=3; indexdeltalength=3
a=control:trackID=1

[rtsp @ 0x7f44ec000b80] setting jitter buffer size to 5000B f=0/0   
[rtsp @ 0x7f44ec000b80] setting jitter buffer size to 5000B f=0/0   
[h264 @ 0x7f44ec007760] Invalid NAL unit 0, skipping.    0B f=0/0   
    Last message repeated 3 times
[h264 @ 0x7f44ec007760] Ignoring NAL type 5 in extradata
    Last message repeated 3 times
[h264 @ 0x7f44ec007760] Invalid NAL unit 0, skipping.    0B f=0/0   
    Last message repeated 3 times
[h264 @ 0x7f44ec007760] Ignoring NAL type 5 in extradata
    Last message repeated 3 times
[h264 @ 0x7f44ec007760] non-existing PPS 0 referenced    0B f=0/0   
    Last message repeated 1 times
[h264 @ 0x7f44ec007760] decode_slice_header error
[h264 @ 0x7f44ec007760] non-existing PPS 0 referenced
[h264 @ 0x7f44ec007760] decode_slice_header error
[h264 @ 0x7f44ec007760] non-existing PPS 0 referenced
[h264 @ 0x7f44ec007760] decode_slice_header error
[h264 @ 0x7f44ec007760] non-existing PPS 0 referenced`
Any ideas?
Also are there any tools that could help debugging this?

**Comment by pedroSG94** [comment]
sprop-parameter-sets is too large. It seems incorrect so your SPS and PPS is not correct.

Try create a fake sps and pps using byte[] generated by your mobile using the same resolution:
Start a stream using my app example and get sps and pps byte[] from the callback, copy it and replace the original for this one.

The correct way should be extract it from bytebuffers of the incomming stream. You can check if you receive nal unit type 7 (sps) and 8 (pps) to get the correct values.

**Comment by anilmaddala** [comment]
Your right. Fixed my sps, pps buffers and it works now. 

Thank you again for the excellent work and support!
