### ISSUE TITLE
streaming not work with camera2 RTMP (surface mode RTMP) 

### ISSUE THREAD

**Issue by medali88** [pedroSG94/rtmp-rtsp-stream-client-java#1034]
I tried to stream with RTMP to Youtube with Camera2 (surface mode Rtmp or texture mode rtmp), connection sucess but no images on the youtube side , what solution to get around this problem? thanks

**Comment by pedroSG94** [comment]
Hello,

Try to use Camera2 with OpenGlView and if you still have the same problem try with Camera1 with OpenGlView.
After that share me a logcat of both cases to know where is the problem.

**Comment by medali88** [comment]
i tested to set openGlView with camera 2 (
private RtmpCamera1 rtmpCamera1;
//to
  private RtmpCamera2 rtmpCamera1;
[logcat open gl.tar.gz](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/7838397/logcat.open.gl.tar.gz)

    rtmpCamera1 = new RtmpCamera1(openGlView, this);
//to
rtmpCamera1 = new RtmpCamera2(this, false, this);

)

but failed to start camera (black screen)  

(Camera1 with openGlView work fine but i want to use Camera2) Thanks

**Comment by pedroSG94** [comment]
RtmpCamera2(this, false this) is used for background mode. You are not using OpenGlView
You need replace:
```java
new RtmpCamera1(openGlView, this);
```
To:
```java
new RtmpCamera2(openGlView, this);
```
Also, your logcat don't show me anything about stream connection. Please compile my app example Go to:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java
And replace RtmpCamera1 to RtmpCamera2 as indicated above. After that, check if all is working and share me a logcat from press start stream button to press stop stream button

**Comment by medali88** [comment]
Thank you very much ,  it work with new RtmpCamera2(openGlView, this); 

can i use custom RTMP with camera2 (RtmpCamera2) ?

**Comment by pedroSG94** [comment]
I don't understand. Do you mean custom example?
Yes, you can do it. Camera1 and Camera2 has similar functionallity
Maybe you need adapt few lines of code like getResolutionsBack method because return a different object and replace SurfaceView to OpenGlView is also recommended

**Comment by medali88** [comment]
Thank you very much
