### ISSUE TITLE
UVC problem

### ISSUE THREAD

**Issue by jp1017** [pedroSG94/rtmp-rtsp-stream-client-java#104]
May support uvc lib? just like: https://github.com/saki4510t/UVCCamera/

**Comment by pedroSG94** [comment]
I have no plan to do it. Anyway I want develop a custom option for render a surface with your own video data.
You can do it with a little modification. This is really similar to camera2 builder

**Comment by jp1017** [comment]
OK!

**Comment by jp1017** [comment]
@pedroSG94

 I wrote a demo here : 

https://github.com/jp1017/UVCCamera/blob/master/usbCameraCommon/src/main/java/com/serenegiant/encoder/MediaEncoder.java#L632,

 but it results some warns: 

```
java.lang.IndexOutOfBoundsException: offset=13, count=-3798, length=1300
    at java.nio.Buffer.checkGetBounds(Buffer.java:173)
    at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:107)
    at com.pedro.rtsp.rtp.packets.H264Packet.createAndSendPacket(H264Packe
    at com.pedro.rtsp.rtsp.RtspClient.sendVideo(RtspClient.java:553)
    at com.serenegiant.encoder.MediaEncoder.drain(MediaEncoder.java:632)
```

This makes the APP just run for less than one minutes, can you review my code and give some advice? :+1: :smile: :100:

**Comment by pedroSG94** [comment]
Set bytebuffer position to 0 before send the packet to rtsp module.
You can try too overriding buferinfo.size with bytebuffer.remaining and discard frames with bufferinfo.size < 0
If you can tell me line crash in rtsp module maybe i can help you more.

**Comment by jp1017** [comment]
3G network results in this problem and WIFI is OK.
