### ISSUE TITLE
Zoom level with camera1

### ISSUE THREAD

**Issue by ilbonte** [pedroSG94/rtmp-rtsp-stream-client-java#1040]
First of all thanks for your work, is amazing :) 
I need to use Camera1 because I need to support an old device with API 19 and I need to be able to set zoom using a scalar value (e.g. setZoom(3)). 
Looking at the API exposed by RtmpCamera1 it seems that this is not possible but looking at the code looks like that Camera1 has the ability to set the zoom: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/c3afe264acd1715276a8119650557797678e6b18/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java#L223

Is it possible to achieve what I want using the current API?

**Comment by pedroSG94** [comment]
I did a commit for it:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/1a51958a16c1c3ba1e67d19a98f16cb5893e50f2
Update library to version 2.1.6

**Comment by ilbonte** [comment]
Wow thanks! So fast :D
