### ISSUE TITLE
How to modify the output screen display ratio column？

### ISSUE THREAD

**Issue by iqiluwxy** [pedroSG94/rtmp-rtsp-stream-client-java#1052]
Hello, how do I change the display ratio column of the DisplayRTMP output screen?

**Comment by pedroSG94** [comment]
I don't understand. Can you explain it? what do you mean with "ratio column"?
If needed, share me screenshoot to indicate it and tell me exactly the result required.

**Comment by iqiluwxy** [comment]
I'm very sorry, maybe my wording is not accurate. I mean, I'd like to change the resolution of the pulled-down image because I'm using Display Rtmp in my Android TV box. The resolution of Android TV box is 1920*1080 and the ratio is 16:9, but I found that after I pushed out the Display of Android TV box, the resolution of the picture I watched with VLC streaming was 640*480. I want to find out where in the code I can change the screen resolution of this pull stream. 
The screenshot of Android tvbox is photo one, and the screenshot of VLC streaming is photo two.
![one](https://user-images.githubusercontent.com/31097667/152904091-9737713d-be32-4c4d-bc12-e0068b4d9c80.png)
<img width="960" alt="two" src="https://user-images.githubusercontent.com/31097667/152904094-b36cc391-b646-4791-87ff-001ebd8e077e.png">

**Comment by pedroSG94** [comment]
You should use a resolution with same aspect ratio 16:9.
You can set it in prepareVideo method. By default, if you don't use parameters in prepareVideo method this line is excuted:
```java
prepareVideo(640, 480, 30, 1200 * 1024, 0, 320);
```

**Comment by iqiluwxy** [comment]
Thank you very much. It solves my problem. It's very cool
