### ISSUE TITLE
No response from server when using mobile data to stream rtsp

### ISSUE THREAD

**Issue by lchy12345** [pedroSG94/rtmp-rtsp-stream-client-java#1054]
Hi pedro,

I am encountering a problem. When I stream rtsp using WiFi, all streaming is normal. However, when I use mobile 4G network to stream rtsp, after like 10s, "DisplayService: No response from server" pop up and the stream failed. It would be great if you could suggest the direction for investigation. Thank you so much.

**Comment by pedroSG94** [comment]
I haven't log "No response from server" in DisplayService.
- Can you tell me the callback received? 
- In case that you receive onConnectionFailed, can you tell me String reason value?
- Are you sure that you have access to server from mobile data? can you test it using a ping or similar?

**Comment by lchy12345** [comment]
Yes, it is callback from onConnectionFailed. The string reason is "No response from server".
I can access the server from mobile data and ping the server. 
But when using mobile data, at first it was streaming smoothly, after like 10s, the stream stop with onConnectionFailed reason "No response from server"

**Comment by pedroSG94** [comment]
Ok,

This means that isAlive method fail for some reason.
Can you share me a logcat?
Can you check this method to know if you have checkServerAlive enabled and to know the line that return false?
RTSP:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtsp/src/main/java/com/pedro/rtsp/rtsp/RtspClient.kt#L323
RTMP:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/pedro/rtmp/rtmp/RtmpClient.kt#L230

**Comment by lchy12345** [comment]
Thanks for the idea. After setting the checkServerAlive to false, the "No response from server" error did not appear.
But there is always "CommandsManager: read error", the log is attached. Do you have any idea why? Thanks in advance.

[log.txt](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/8038523/log.txt)

**Comment by pedroSG94** [comment]
You can ignore that. The library try to read from server each 2s to know if server send any command and execute it.
This means that you are not receiving anything so you can ignore it.
Anyway, I'm interested to know where is the error in isAlive method instead of only skip it.
Where is the error? here:
```
val connected = connectionSocket?.isConnected ?: false
```
Or here:
```
val reachable = connectionSocket?.inetAddress?.isReachable(5000) ?: false
```
Check nullability step by step to know if it is the problem and check isConnected / isReachable to know if it is returning false.

**Comment by lchy12345** [comment]
I have physically relocated the server without any change in setting. But now I dont get the "No response from server even if checkServerAlive is enabled.
