### ISSUE TITLE
Push custom video buffer 

### ISSUE THREAD

**Issue by Goule** [pedroSG94/rtmp-rtsp-stream-client-java#1057]
Hello, 

I'm looking for a way to push to the library a custom video buffer, is that possible? 

Here is an example : 
![IMG_1168](https://user-images.githubusercontent.com/21126201/153560454-34fc25bf-0913-4976-997b-d563de796796.jpg)

Use case example : 
- stream the GoPro video with RTMP
- stream DJI video with RTMP
- stream local video with RTMP...
- stream any external video stream on an RTMP stream 

Is there a way to do it? 
If yes, with filters?

Thanks :)

**Comment by pedroSG94** [comment]
Hello you can try like this:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/1033
RtspClient and RtmpClient have a the same usage.

**Comment by pedroSG94** [comment]
No,

Actually it is not supported.

**Comment by Goule** [comment]
Thanks @pedroSG94 for your reponse !
