### ISSUE TITLE
Help me to test app

### ISSUE THREAD

**Issue by Aladin2** [pedroSG94/rtmp-rtsp-stream-client-java#106]
Dear
I am going to test your app
But I don't know how should I enter the endpoint address
I have tried with "rtsp://{phone ip addr}:port//{this app name}:{random name}
But I get failed 'Connection failed. Error connection stream........"
How should I enter valid endpoint?
Is this app free?
Please help me.
Cheers

**Comment by jp1017** [comment]
You may get the url in logcat.

**Comment by Aladin2** [comment]
I have tried with this
rtsp://192.168.1.162:8789/Streamer/display
But I can't find any url in logcat
This logcat info

05-12 09:34:43.337 5596-5596/com.pedro.rtmpstreamer D/ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
05-12 09:34:43.487 5596-5596/com.pedro.rtmpstreamer I/Timeline: Timeline: Activity_launch_request id:com.android.systemui time:35323797
05-12 09:34:43.597 5596-5596/com.pedro.rtmpstreamer I/MicrophoneManager: Microphone created, 44100hz, Stereo
05-12 09:34:43.597 5596-5596/com.pedro.rtmpstreamer I/MicrophoneManager: Microphone created, 44100hz, Stereo
05-12 09:34:43.597 5596-5596/com.pedro.rtmpstreamer I/ACodec:  [] Now uninitialized
05-12 09:34:43.607 5596-8892/com.pedro.rtmpstreamer I/OMXClient: Using client-side OMX mux.
05-12 09:34:43.607 5596-8892/com.pedro.rtmpstreamer E/OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
05-12 09:34:43.607 5596-8892/com.pedro.rtmpstreamer W/linker: libarac.so has text relocations. This is wasting memory and prevents security hardening. Please fix.
05-12 09:34:43.627 5596-8892/com.pedro.rtmpstreamer W/linker: libarac.so has text relocations. This is wasting memory and prevents security hardening. Please fix.
05-12 09:34:43.637 5596-8892/com.pedro.rtmpstreamer E/OMXMaster: A component of name 'OMX.SEC.hevc.sw.dec' already exists, ignoring this one.
05-12 09:34:43.637 5596-8892/com.pedro.rtmpstreamer I/ACodec: [OMX.google.aac.encoder] Now Loaded
05-12 09:34:43.637 5596-8892/com.pedro.rtmpstreamer E/ACodec: onConfigureComponent mime.c_str() = audio/mp4a-latm
05-12 09:34:43.637 5596-8892/com.pedro.rtmpstreamer I/ACodec: >>> getPortFormat 16, OMX.google.aac.encoder
05-12 09:34:43.637 5596-5596/com.pedro.rtmpstreamer I/VideoEncoder: videoEncoder OMX.qcom.video.encoder.avc type supported: video/avc
05-12 09:34:43.637 5596-5596/com.pedro.rtmpstreamer W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
05-12 09:34:43.637 5596-5596/com.pedro.rtmpstreamer I/VideoEncoder: Color supported: 2141391876
05-12 09:34:43.637 5596-5596/com.pedro.rtmpstreamer I/VideoEncoder: Color supported: 2130708361
05-12 09:34:43.637 5596-5596/com.pedro.rtmpstreamer I/VideoEncoder: Color supported: 2135033992
05-12 09:34:43.637 5596-5596/com.pedro.rtmpstreamer I/VideoEncoder: Color supported: 21
05-12 09:34:43.637 5596-5596/com.pedro.rtmpstreamer I/ACodec:  [] Now uninitialized
05-12 09:34:43.637 5596-8896/com.pedro.rtmpstreamer I/OMXClient: Using client-side OMX mux.
05-12 09:34:43.797 5596-8896/com.pedro.rtmpstreamer I/ACodec: [OMX.qcom.video.encoder.avc] Now Loaded
05-12 09:34:43.797 5596-8896/com.pedro.rtmpstreamer E/ACodec: onConfigureComponent mime.c_str() = video/avc
05-12 09:34:43.797 5596-8896/com.pedro.rtmpstreamer E/ACodec: [OMX.qcom.video.encoder.avc] storeMetaDataInBuffers (output) failed w/ err -2147483648
05-12 09:34:43.797 5596-8896/com.pedro.rtmpstreamer W/ACodec: do not know color format 0x7fa30c04 = 2141391876
05-12 09:34:43.797 5596-8896/com.pedro.rtmpstreamer W/ACodec: do not know color format 0x7f000789 = 2130708361
05-12 09:34:43.807 5596-8896/com.pedro.rtmpstreamer I/ACodec: [OMX.qcom.video.encoder.avc] setupVideoEncoder succeeded
05-12 09:34:43.807 5596-8896/com.pedro.rtmpstreamer W/ACodec: do not know color format 0x7f000789 = 2130708361
05-12 09:34:44.217 5596-8896/com.pedro.rtmpstreamer I/ACodec: [OMX.qcom.video.encoder.avc] Now Loaded->Idle
05-12 09:34:44.227 5596-8896/com.pedro.rtmpstreamer I/ACodec: [OMX.qcom.video.encoder.avc] Now Idle->Executing
05-12 09:34:44.227 5596-8892/com.pedro.rtmpstreamer I/ACodec: [OMX.google.aac.encoder] Now Loaded->Idle
05-12 09:34:44.227 5596-8892/com.pedro.rtmpstreamer I/ACodec: [OMX.google.aac.encoder] Now Idle->Executing
05-12 09:34:44.227 5596-8896/com.pedro.rtmpstreamer I/ACodec: [OMX.qcom.video.encoder.avc] Now Executing
05-12 09:34:44.227 5596-8892/com.pedro.rtmpstreamer I/ACodec: [OMX.google.aac.encoder] Now Executing
05-12 09:34:44.227 5596-5596/com.pedro.rtmpstreamer I/AudioEncoder: AudioEncoder started
05-12 09:34:44.247 5596-5596/com.pedro.rtmpstreamer I/MicrophoneManager: Microphone started
05-12 09:34:44.307 5596-5596/com.pedro.rtmpstreamer I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@1f8c2aa1 time:35324617
05-12 09:34:44.357 5596-8912/com.pedro.rtmpstreamer E/RtspClient: connection error
                                                                  java.net.ConnectException: failed to connect to /192.168.1.162 (port 8789) after 3000ms: isConnected failed: ECONNREFUSED (Connection refused)
                                                                      at libcore.io.IoBridge.isConnected(IoBridge.java:238)
                                                                      at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
                                                                      at libcore.io.IoBridge.connect(IoBridge.java:122)
                                                                      at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
                                                                      at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
                                                                      at java.net.Socket.connect(Socket.java:882)
                                                                      at com.pedro.rtsp.rtsp.RtspClient$1.run(RtspClient.java:169)
                                                                      at java.lang.Thread.run(Thread.java:818)
                                                                   Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
                                                                      at libcore.io.IoBridge.isConnected(IoBridge.java:223)
                                                                      at libcore.io.IoBridge.connectErrno(IoBridge.java:171) 
                                                                      at libcore.io.IoBridge.connect(IoBridge.java:122) 
                                                                      at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183) 
                                                                      at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456) 
                                                                      at java.net.Socket.connect(Socket.java:882) 
                                                                      at com.pedro.rtsp.rtsp.RtspClient$1.run(RtspClient.java:169) 
                                                                      at java.lang.Thread.run(Thread.java:818) 
05-12 09:34:44.367 5596-5596/com.pedro.rtmpstreamer I/MicrophoneManager: Microphone stopped
05-12 09:34:44.387 5596-8896/com.pedro.rtmpstreamer I/ACodec: [OMX.qcom.video.encoder.avc] Now Executing->Idle
05-12 09:34:44.397 5596-8896/com.pedro.rtmpstreamer I/ACodec: [OMX.qcom.video.encoder.avc] Now Idle->Loaded
05-12 09:34:44.397 5596-8896/com.pedro.rtmpstreamer I/ACodec: [OMX.qcom.video.encoder.avc] Now Loaded
05-12 09:34:44.407 5596-8896/com.pedro.rtmpstreamer I/ACodec:  [OMX.qcom.video.encoder.avc] Now uninitialized
05-12 09:34:44.417 5596-8892/com.pedro.rtmpstreamer I/ACodec: [OMX.google.aac.encoder] Now Executing->Idle
05-12 09:34:44.417 5596-8892/com.pedro.rtmpstreamer I/ACodec: [OMX.google.aac.encoder] Now Idle->Loaded
05-12 09:34:44.417 5596-8892/com.pedro.rtmpstreamer I/ACodec: [OMX.google.aac.encoder] Now Loaded
05-12 09:34:44.417 5596-8892/com.pedro.rtmpstreamer I/ACodec:  [OMX.google.aac.encoder] Now uninitialized
05-12 09:34:44.417 5596-5596/com.pedro.rtmpstreamer I/AudioEncoder: AudioEncoder stopped

Please help me
Cheers

**Comment by Aladin2** [comment]
Dear
I hope you can help me
Or do I have to buy any license?

**Comment by jp1017** [comment]
> java.net.ConnectException: failed to connect to /192.168.1.162 (port 8789) after 3000ms:

We can see: server cannot  connected.

**Comment by Aladin2** [comment]
Yes.
But I am not sure why this happened
192.168.1.162 is my phone ip
Would you please tell me full guide how to test this app?
I have installed both this app and the player for this app(https://github.com/pedroSG94/vlc-example-streamplayer)
I am waiting for your answer
Thanks

**Comment by jp1017** [comment]
You need a rtsp server, the ip is the server's ip.

**Comment by Aladin2** [comment]
How can I purchase the rtsp server?

**Comment by jp1017** [comment]
So, what do you want to do using this lib. :cry:

**Comment by Aladin2** [comment]
I am going to make an app that capture the screen and voice and see it on another phones.
I found that your app has this feature(Display RTSP)
I hope you will help me

**Comment by jp1017** [comment]
You need Socket and ServerSocket to achive it.
One phone make a wifi hotspot, another connect it by wifi.

If you need this lib, you may get a rtsp server first. 
One phone push video to server, and the server dispatch videos to another phone.

**Comment by Aladin2** [comment]
I see
Thanks for you help.
