### ISSUE TITLE
[QA] Bandwidth while streaming on notification bar

### ISSUE THREAD

**Issue by loitpuiza** [pedroSG94/rtmp-rtsp-stream-client-java#1067]
Hi @pedroSG94 

I need to display a textview with content is current bandwidth while streaming like "500Mb/s" on notification bar.
Could you guy please help me how to implement that?

Thanks in advanced.

![Screenshot_2022-03-04-18-59-39-573_com google android youtube](https://user-images.githubusercontent.com/83008646/156760329-5203ad92-f815-445d-a231-44db9479f664.jpg)

**Comment by pedroSG94** [comment]
Hello,

You can use this callback to get stream bandwidth:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L378
About show it on notification bar. It is not related with the library so you should google it but it look like a notification:
https://stackoverflow.com/questions/62059848/how-to-change-text-in-status-bar-dynamically

**Comment by loitpuiza** [comment]
Hi @pedroSG94

I use that call back onNewBitrateRtmp like you suggest but it seems the value of bitrate and the value of connection speed are not the same (my device Xiaomi has a config in setting to help me enable/disale connection speed on status bar). Are these 2 values the same thing?

`override fun onNewBitrateRtmp(bitrate: Long) {
        tv.text = "onNewBitrateRtmp bitrate $bitrate -> ${bitrate/1000}Kbps"
    }`

![Screenshot_2022-03-05-10-46-10-667_com android settings](https://user-images.githubusercontent.com/83008646/156866782-a9a371d5-2c3d-4caa-9c58-cc9178ae3191.jpg)

![Screenshot_2022-03-05-10-45-34-210_com snake broadcast](https://user-images.githubusercontent.com/83008646/156866784-1d1625f6-d812-4d17-99e3-f32f9e240fcb.jpg)

Thank you.

**Comment by pedroSG94** [comment]
The value is the upload speed used only by my library. Yes, the values could be different
Also, Kb is different that KB the first one is kilo bits and the second one is kilo bytes:
2255Kb -> 282KB

**Comment by loitpuiza** [comment]
Got it. Thank you @pedroSG94
