### ISSUE TITLE
RTMP - camera2 Streamed video stability issue while moving camera

### ISSUE THREAD

**Issue by MTayyabSarfraz** [pedroSG94/rtmp-rtsp-stream-client-java#1069]
@pedroSG94 bro,
The video stream distorts while the camera is even moving slightly.
But video quality is perfect if the camera is still.
Is there a way to control this distortion?

I've used
` rtmpCamera2.enableOpticalVideoStabilization();`
       ` rtmpCamera2.enableVideoStabilization();`
       
but nothing seems working.

I'm attaching a screenshot of the stream result of both the still and moving camera stream for reference.

      
![Screenshot (44)](https://user-images.githubusercontent.com/28774273/157852185-befc56bd-b1f9-438e-a73a-a02eef0d41eb.png)
![Screenshot (45)](https://user-images.githubusercontent.com/28774273/157852203-8593a526-c46d-4546-9cea-a0de59aaf82f.png)
 
 Before closing, I would like to extend my heartiest gratitude towards you and the tremendous open-source effort you and other contributors have put behind this wonderful module.

**Comment by pedroSG94** [comment]
I'm not sure if you still need it but this seems a low bitrate or a high iframeinterval value.

**Comment by MTayyabSarfraz** [comment]
Thanks bro... Low bitrate was the issue...
But high bitrate has its consequences like more battery drainage, more
network data usage and on cellular. Network connection mobile gets heated
more quickly.. because of high processing and bit through
