### ISSUE TITLE
Problems with audio

### ISSUE THREAD

**Issue by rodrigommacedo** [pedroSG94/rtmp-rtsp-stream-client-java#107]
I'm trying to make a livestream with youtube, but the audio quality is poor and noisy.

  if (rtmpCamera1.prepareVideo(size[0], size[1], 30, 2500 * 1024, false, 0) &&
                            rtmpCamera1.prepareAudio(128 * 1024, 44100, false, false, true)){
            rtmpCamera1.startStream(RTMP);
   }

Can someone help me?

**Comment by pedroSG94** [comment]
Increment audio bitrate and use stereo:
```java
rtmpCamera1.prepareAudio(256 * 1024, 44100, true, false, true)
```

**Comment by rodrigommacedo** [comment]
I performed the change. but the problem continues. But what can I do to improve the audio?

**Comment by pedroSG94** [comment]
Try without noise suppressor, Maybe is not working good for you:
```java
rtmpCamera1.prepareAudio(256 * 1024, 44100, true, false, false)
```
If the problem persist you can try find your own valid configuration modifying this class:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/audio/MicrophoneManager.java
I recommend you see if you can solve it with a different buffer size or using the secondary microphone.

Also make sure that it isn't a device problem, you can do a video with the default camera app to know it.

**Comment by rodrigommacedo** [comment]
Thank you, it worked.
