### ISSUE TITLE
Endpoint malformed

### ISSUE THREAD

**Issue by LutfiTekin** [pedroSG94/rtmp-rtsp-stream-client-java#108]
Hello guys, I am trying to use this library for streaming to dacast. 
And I am getting this error
` Endpoint malformed, should be: rtmp://ip:port/appname/streamname`
While I am trying to use it like, 
`rtmp://user:pass@ip:port/appname/streamname`

I have tried setAuthorization method for authorization but it doesn't work as well.
 `Fail to connect, time out`
What should I do?

**Comment by pedroSG94** [comment]
Auth is developed to work with Wowza so if it doesn't work with others server that is normal.
Dacast server response me this:
```
[ AccessManager.Reject ] : [ authmod=adobe ] : ?reason=needauth&user=210211&salt=MjA2OTIyMzI5OA==&challenge=OTUwMjY0NjQ5
```
So I need develop other auth. The problem is that I can't do a stream with ffmpeg to debug the aith method and develop it. Ffmpeg is not working for me with Dacast

**Comment by LutfiTekin** [comment]
I see, I asked because I have tried user-password in rtmp url with this swift library 
https://github.com/shogo4405/HaishinKit.swift
And it worked, was hoping to see the same thing happen with this lib. Thank you for response. Do you have any recommendation about what should use?

**Comment by pedroSG94** [comment]
I'm using adobe auth too. Maybe I can emulate that auth.
Can you share me the message produced by this methods?:
https://github.com/shogo4405/HaishinKit.swift/blob/master/Sources/RTMP/RTMPConnection.swift#L355
https://github.com/shogo4405/HaishinKit.swift/blob/master/Sources/RTMP/RTMPConnection.swift#L347
And credentials used to know codification?.

**Comment by LutfiTekin** [comment]
> Can you share me the message produced by this methods?

Like this?

`line 355 command: rtmp://210211:872262@p.ep303559.i.akamaientrypoint.net/EntryPoint?authmod=adobe&user=210211
line 347 command: rtmp://210211:872262@p.ep303559.i.akamaientrypoint.net/EntryPoint?authmod=adobe&user=210211&challenge=0b8bb43c&response=V7vEHsTgT5N/Pk59snoOFg== `

**Comment by pedroSG94** [comment]
Yes, thank you. Can you share me all values of description variable in the connection?:
https://github.com/shogo4405/HaishinKit.swift/blob/master/Sources/RTMP/RTMPConnection.swift#L337
Try with auth and without auth please.

**Comment by pedroSG94** [comment]
Sorry for it. I haven't IPhone or Mac :(

**Comment by LutfiTekin** [comment]
No worries, I am looking into it now.

**Comment by LutfiTekin** [comment]
No Auth:
`2017-23-12 21:00:46.895 [Info] [com.haishinkit.HaishinKit] [VideoIOComponent.swift:35] fps > (fps: 30.0, duration: __C.CMTime(value: 100, timescale: 3000, flags: __C.CMTimeFlags(rawValue: 1), epoch: 0))
2017-23-12 21:00:47.452 [Trace] [com.haishinkit.HaishinKit] [NetSocket.swift:91] close(isDisconnected:) > isDisconnected:true
2017-23-12 21:00:47.452 [Warn] [com.haishinkit.HaishinKit] [RTMPConnection.swift:364] on(status:) > `

**Comment by pedroSG94** [comment]
Auth is fixed! 
The problem was opaque that look optional in authmode adobe.
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/576208bf55087d1c474c2b5731f0d6a210108cd2
Try with this commit. I can see the stream in the web app of Dacast.

**Comment by LutfiTekin** [comment]
How can get that commit? I am using gradle

**Comment by pedroSG94** [comment]
I will upload to gradle 1 moment

**Comment by LutfiTekin** [comment]
It worked.
Thank you!!!
![you-are-the-best](https://user-images.githubusercontent.com/14232911/34321971-944f1ab8-e82c-11e7-88eb-2f0b41aca000.jpg)

**Comment by pedroSG94** [comment]
Nice. Issue closed.
If you have other question or problem open other issue :)
