### ISSUE TITLE
Problem Live Youtube

### ISSUE THREAD

**Issue by IntuitiveAppz** [pedroSG94/rtmp-rtsp-stream-client-java#109]
Hi,

I'm broadcasting a live video to youtube with good frame rate and audio quality, but it's happening several small cuts on video. Do you have a configuration to improve it?

**Comment by pedroSG94** [comment]
Assuming that you use rtmpcamera1 class I recommend you use openglview class instance of surfaceview (API 18+) or rtmpcamera2 (API 21+) class because it use encoding with surface and work better than buffer to buffer encoding.
Also you can try with differents resolutions and video bitrate.
