### ISSUE TITLE
How to stream camera when camera is not detected in this library.

### ISSUE THREAD

**Issue by shahryar-cmyk** [pedroSG94/rtmp-rtsp-stream-client-java#1090]
Hey there @pedroSG94 , 
I am using library for the streaming camera it is streaming through back camera but not front camera. After searching a lot it seems like in most of the devices front camera works but not in my particular device. So, I contacted with the manufacturer he gave me library from where I can access the front camera of that specific device.

My Question is how can I stream that front camera through rtmp. In manufacturer Library I can startPreview ( SurfaceView surface ),stopPreview (), and startHaiSiRecordMp4(int mins) and different functions but not for streaming rtmp. 

Thanks you again for the library.

**Comment by pedroSG94** [comment]
Hello,

If you can't open front camera I recommend you check the code of the manufacturer library and try to fix it here:
Camera1:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java
Camera2:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java

Also, check front camera resolutions to know if you are trying to open a resolution not supported.
