### ISSUE TITLE
in  Landscape Mode Can't start preview again if app is paused or put to background

### ISSUE THREAD

**Issue by MTayyabSarfraz** [pedroSG94/rtmp-rtsp-stream-client-java#1102]
Hi @pedroSG94 bro.
The library is working fine for me other than whenever I pause my app (put in the background) and resume again I am unable to start the camera preview, there is a black screen displaying probably when onResume screen configurations are changed and openGl holder's surface gots invalid **also** in this case surfaceChanged is never called so can't start preview again manually.
Can you help me out with, any solution or recommend any standard practice to overcome this issue.

One thing to clarify I don't want to RTMPService to continue streaming in the background.
So I'm using OpenGL RTMP activity code, AndroidView filter(just for reference).
Just need a preview fix.
 
 here is my surfaceDestroyed code:
 
 ```
`@Override
    public void surfaceDestroyed(SurfaceHolder surfaceHolder) {
        if (glInterFace != null)
            glInterFace.clearFilters();
        if (rtmpCamera2.isStreaming()) {
            webViewRenderer.setView(null); //stop render view
            rtmpCamera2.stopStream();
            button.setBackgroundTintList(mContext.getResources().getColorStateList(R.color.color_pop));
            button.setText(getResources().getString(R.string.go_live));
        }
        if (rtmpCamera2 != null && !rtmpCamera2.isOnPreview() && openGlView.getHolder().getSurface().isValid())
            rtmpCamera2.stopPreview();
    }`
```
    
    and surfaceChanged as 
    
   ```
 `@Override
    public void surfaceChanged(SurfaceHolder surfaceHolder, int i, int width, int height) {
        rtmpCamera2.startPreview(width, height);
    }`
```

**Comment by pedroSG94** [comment]
I think the problem is here:
```java
       if (rtmpCamera2 != null && !rtmpCamera2.isOnPreview() && openGlView.getHolder().getSurface().isValid())
```
Why are you checking surface state? Also, you should check if preview is enabled to stop it not check if preview is disabled.
So, I suggest this:
```java
       if (rtmpCamera2 != null && rtmpCamera2.isOnPreview())
```

**Comment by MTayyabSarfraz** [comment]
@pedroSG94 thanks for the quick feedback. i'm really gutted my self.. how come I applied this condition don't know what was going on my mind while writing this.. probably a copy/paste lead to this.
