### ISSUE TITLE
recording fragment

### ISSUE THREAD

**Issue by MrAlanWei** [pedroSG94/rtmp-rtsp-stream-client-java#1106]
I want to record videos to different files in one minute. Can I only stop record first and then start record.I use camera2

**Comment by pedroSG94** [comment]
Record videos in chucks is not possible using MediaMuxer and it is the way used to record videos in this library so it is not possible currently.
The only way is strart and stop record as you described.

I recommend you record a video, and after record, cut this video using other library.

**Comment by MrAlanWei** [comment]
Thanks
