### ISSUE TITLE
Loose camera access

### ISSUE THREAD

**Issue by jared-94** [pedroSG94/rtmp-rtsp-stream-client-java#1107]
Hi,

I'm using `Camera2Base` in a foreground service, together with your `RTSP-Server` plugin.

It's working fine but as soon as another app get access to the camera, the stream stops working (the `Privacy alert` system notification disappears).
I assume this is normal, but then, how can I handle this, and restart the stream ASAP (when the other app don't require cam anymore) ?

Thanks!

**Comment by pedroSG94** [comment]
Hello,

I need study this case a bit more.
Can you give more info to reproduce the case?
- Device model and Android API version.
- How to reproduce the case in steps preferibly using my app example (I think you can use background example for this case)
- Logcat to know when the app lose cammera access.

In advance. I'm not sure if you can detect if camera is in use by other app or not (I think we have[ this callback](https://developer.android.com/reference/android/hardware/camera2/CameraManager.AvailabilityCallback) for camera2 but I'm not sure if it is possible for camera1).
I think you can use it yourself and test to know if it is working. Anyway this could be interested to notify user anyway.

**Comment by jared-94** [comment]
After investigations, it turns out that cameraCallback is never called with this code :
```
 rtspServerCamera.setCameraCallbacks(new CameraCallbacks() {
                @Override
                public void onCameraChanged(CameraHelper.Facing facing) {

                }

                @Override
                public void onCameraError(String error) {
                    Log.i(TAG, "****** CAMERA ERROR *********");
                }
            });
```

But I found that `onDisconnected` from `Camera2ApiManager` (line 1000) is called.
Could you please add a public function so that we may handle this?

**Comment by pedroSG94** [comment]
Callback added here: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/2c55ec54e2674020dcaedc93998048e943bd7e19

**Comment by jared-94** [comment]
Great thank you @pedroSG94 !

I have one last request please.
Could you add another `CameraCallback` :
```
void onCameraOpened();
```

in `onOpened` function? (line 989 of `Camera2ApiManager `)

Thanks !

**Comment by pedroSG94** [comment]
Added here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/5e70c66e623ccbf9a644219901e98bece8d4d3b3

**Comment by jared-94** [comment]
Perfect, thanks !

**Comment by pedroSG94** [comment]
This seems solved, closing issue
