### ISSUE TITLE
java.net.SocketException: Socket is not connected

### ISSUE THREAD

**Issue by jp1017** [pedroSG94/rtmp-rtsp-stream-client-java#111]
3G network results in this problem?

**Comment by pedroSG94** [comment]
This look a proxy problem. I find an issue on github that could help you:
https://github.com/rubenlagus/TelegramBots/issues/288
Maybe you can try with the second response here before use my library:
https://stackoverflow.com/questions/10186069/how-to-bypass-the-proxy-using-java
