### ISSUE TITLE
Camera Face select is now working only for streaming.

### ISSUE THREAD

**Issue by JamshedAlamQaderi** [pedroSG94/rtmp-rtsp-stream-client-java#1115]
Problem: When i try to switch camera facing with `rtspCameram.switchCamera()` it doesn't work. When i investigated the code then i've found you've provided camera face set to startPreview method. So, when i only want to stream from background service i'm not able to select camera facing directly by calling `rtspCamera.setCameraFace(Facing)` method. instead i am doing `if(rtspCamera.getFacing() != facing) rtspCamera.switchCamera()`. But it doesn't work. I think it doesn't work because you have selected the camera in line no.158 of below code you didn't set that facing to cameraSelect variable.

https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/3bbdd59707855d4ccdbaea319583716ae3f5235d/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java#L153-L164

Need to solve:
Please add a `setCameraFacing` method to RtspCamera1 | RtspCamera2 | RtmpCamera1 | RtmpCamera2
change line no.157 to  `cameraSelect = selectCamera(facing);` & remove line no. 158.

Thank you!

**Comment by pedroSG94** [comment]
Hello,

It is working for me. Can you share me code example to reproduce the case?

**Comment by JamshedAlamQaderi** [comment]
```
fun setup(
        context: Context?,
        cameraFacing: CameraHelper.Facing,
        videoCodec: VideoCodec,
        res: Pair<Int, Int>,
        frameRate: Int
    ) {
        dispose()
        rtspCamera = RtspCamera1(context, StreamConnectionChecker())
        rtspCamera?.setLogs(false)
        rtspCamera?.setCheckServerAlive(true)
        rtspCamera?.setReTries(10)
        rtspCamera?.setProtocol(Protocol.UDP)
        rtspCamera?.setVideoCodec(videoCodec)
        rtspCamera?.setLimitFPSOnFly(frameRate)
        videoRes = res
        if(rtspCamera?.getCameraFacing() != cameraFacing){
            rtspCamera?.switchCamera()
        }
    }

fun startStream(ipAddress: String = "10.0.2.2", deviceId: String) {
        if (deviceId.isEmpty()) {
            Logger.e("Can't start stream. Device id is empty")
            return
        }
        if (rtspCamera?.isStreaming == false && videoRes != null) {
            if (rtspCamera?.prepareVideo(
                    videoRes?.first!!,
                    videoRes?.second!!,
                    1200 * 1024
                ) == true && rtspCamera?.prepareAudio() == true
            ) {
                rtspCamera?.startStream("rtsp://$ipAddress:15999/stream/$deviceId")
            }
        }
    }
```

**Comment by pedroSG94** [comment]
I fixed and error with switchcamera in camera2Base:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/0072abf36318719fd6a5ec900beb14abecbb09c2
Also, I tested with camera1 and it is working fine.

**Comment by JamshedAlamQaderi** [comment]
It's worked. But it would be nicer if you add an api method in `setCameraFacing `method.

Thank you!
