### ISSUE TITLE
can do rtmp proxy ?

### ISSUE THREAD

**Issue by supr3me** [pedroSG94/rtmp-rtsp-stream-client-java#1119]
Hi friend, this lib can rtmp proxy?
send rtmp stream to my app ,and my app send it to my server
how can I do it?
thank you!

**Comment by pedroSG94** [comment]
Hello,

I think that it is a proxy configuration. Nothing to do in library side. I recommend you find a guide to do it and test it using ffmpeg.
If you can connect using ffmpeg. This library should works.

**Comment by supr3me** [comment]
thank you! I 

> Hello,
> 
> I think that it is a proxy configuration. Nothing to do in library side. I recommend you find a guide to do it and test it using ffmpeg. If you can connect using ffmpeg. This library should works.
