### ISSUE TITLE
inverted video 180 degrees

### ISSUE THREAD

**Issue by digitalStyx** [pedroSG94/rtmp-rtsp-stream-client-java#112]
I have problem. 
When I use front camera (landscape) I always have inverted video (I tested on 5 phone with front and back camera)
In your test application I remove this line: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java#L305, and it's working correct. What this is for?

**Comment by pedroSG94** [comment]
I forget add a conditional to ignore in landscape. Fixed: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/97f968d21e5caf08ac974cc6282509a472f8bf1e
New gradle version: 1.2.9

**Comment by digitalStyx** [comment]
thx, now it's work
