### ISSUE TITLE
Streaming from opengl

### ISSUE THREAD

**Issue by youtengli** [pedroSG94/rtmp-rtsp-stream-client-java#1121]
Hi, 

I'm trying to use deepAR like [agora](https://github.com/DeepARSDK/videocall-android-java/blob/5b724e784fe4bfd651c75a37b86f83ca73ec9335/app/src/main/java/ai/deepar/videocall/DeepARRenderer.java#L215).

I want to push deepAR's results  to my own rtmp server.

I got results by using this code, but I don't know how to push data.

`GLES20.glReadPixels(x, 0, w, y + h, GLES20.GL_RGBA,
                GLES20.GL_UNSIGNED_BYTE, buffer);
`

Can I use this library to do that?

**Comment by pedroSG94** [comment]
So you have RGBA buffers. 
You need to convert it in h264 and you can send it using RtmpClient.
Try to find a way to convert RGBA to YUV and you can encode YUV buffer using VideoEncoder class

**Comment by youtengli** [comment]
Hi, @pedroSG94 

Thank you for reply.

How to use your VideoEncoder, Can you give me usage example?

I change my buffer to ARGB and pass to your YUVUtil.
```
byte[] yuvByteArr = YUVUtil.ARGBtoYUV420SemiPlanar(bt, w, h);

videoEncoder.inputYUVData(new Frame(yuvByteArr, w, h));

videoEncoder.prepareVideoEncoder(w, h, 30, 2500*1000, 0, 0, FormatVideoEncoder.YUV420PLANAR, -1, -1);

videoEncoder.start();
```
And where I can receive h264Buffer for sendVideo()?

```
rtmpClient.sendVideo(h264Buffer, info);
```

**Comment by pedroSG94** [comment]
Hello,

You can receive h264 buffer using GetVideoData interface provided to VideoEncoder in the constructor.

**Comment by youtengli** [comment]
Hi, @pedroSG94 

Thank you for helping. 

I can push and receive video perfectly now. 

Many thanks

**Comment by nhat108** [comment]
Hi @youtengli can you show the code send buffer from DeepAR to RtmpClient?

**Comment by nhat108** [comment]
Because RtmpClient need vps and pps buffer for frist time, I can’t get it from DeepAR @youtengli @pedroSG94

**Comment by youtengli** [comment]
Hi @nhat108 ,

Maybe you can take a look at this: 

https://github.com/DeepARSDK/ios-deepar-amazon-ivs-sample-integration
and this
https://github.com/DeepARSDK/android-deepar-amazon-ivs-sample-integration

Deepar provide aws solution for rtmp streaming.

**Comment by nhat108** [comment]
Hi @youtengli thank you so much for that, you saved my life, I've been trying for more than a week. now amazon ivs is working perfectly.
