### ISSUE TITLE
createAsyncCallback problem

### ISSUE THREAD

**Issue by xumingxin7398** [pedroSG94/rtmp-rtsp-stream-client-java#1125]
"Sets an asynchronous callback for actionable MediaCodec events. If the client intends to use the component in asynchronous mode, a valid callback should be provided before configure is called." the mediacodec docs said about the setCallback method. But  I found the method createAsyncCallback() call in BaseEncoder->initCodec，which was called by start(); So it will be call after  mediacodec's configure and not trigger in some case. Can you give me advice?

**Comment by pedroSG94** [comment]
Hello,

I added a commit to fix it: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/9ffcba3938eb870692674795a09e54cd8280ca50
