### ISSUE TITLE
filter lost after replaceGlVIew

### ISSUE THREAD

**Issue by xumingxin7398** [pedroSG94/rtmp-rtsp-stream-client-java#1141]
filter of openGlView lost after replaceGlVIew , although I have setViewToStream again, it is gone.
`public void replaceView(WeakReference<Main2Activity> weakActivity, boolean isBackground) {

        if (rtspCamera2 == null) {
            return;
        }
        if (this.weakActivity == null) {
            this.weakActivity = weakActivity;
        }
        if (this.weakActivity != null) {
            this.openGlView = this.weakActivity.get().surfaceView;
        }
        if (isBackground) {
            rtspCamera2.replaceView(this.weakActivity.get());
        } else {
            rtspCamera2.replaceView(this.openGlView);
        }
        //reset filter after replaceView
        setViewToStream(true, "camera ready");
    }`

`private void setViewToStream(boolean reset, String text) {

        if (filterRender == null) {
            filterRender = new TextObjectFilterRender();
        }
        if (rtspCamera2.getGlInterface() != null) {
            if (rtspCamera2.getGlInterface().filtersCount() > 0 && reset) {
                rtspCamera2.getGlInterface().clearFilters();
                rtspCamera2.getGlInterface().setFilter(filterRender);
                Log.e(TAG,"setViewToStream clear and set:"+text);
            }
            if (rtspCamera2.getGlInterface().filtersCount() <= 0) {
                rtspCamera2.getGlInterface().setFilter(filterRender);
                Log.e(TAG,"setViewToStream set:"+text);
            }
            filterRender.setText(" " + text, 20, Color.RED);
            filterRender.setDefaultScale(streamWidth, streamHeight);
            filterRender.setPosition(TranslateTo.TOP_LEFT);
        }
    }`

**Comment by pedroSG94** [comment]
Hello,

When you call replaceView. The openGL context is replaced by other openGL context to all texture are released.
I recomend you don't reuse filter after use that method. Maybe you can fix it like this:
```java
private void setViewToStream(boolean reset, String text) {

    if (filterRender == null || reset) { //avoid reuse filter
        filterRender = new TextObjectFilterRender();
    }
    if (rtspCamera2.getGlInterface() != null) {
        if (rtspCamera2.getGlInterface().filtersCount() > 0 && reset) {
            rtspCamera2.getGlInterface().clearFilters();
            rtspCamera2.getGlInterface().setFilter(filterRender);
            Log.e(TAG,"setViewToStream clear and set:"+text);
        }
        if (rtspCamera2.getGlInterface().filtersCount() <= 0) {
            rtspCamera2.getGlInterface().setFilter(filterRender);
            Log.e(TAG,"setViewToStream set:"+text);
        }
        filterRender.setText(" " + text, 20, Color.RED);
        filterRender.setDefaultScale(streamWidth, streamHeight);
        filterRender.setPosition(TranslateTo.TOP_LEFT);
    }
}
```
