### ISSUE TITLE
Is there a demo for cross platform implementation of this function？

### ISSUE THREAD

**Issue by zhubinsheng** [pedroSG94/rtmp-rtsp-stream-client-java#1148]

**Comment by pedroSG94** [comment]
Hello,

This library is only for Android.
Anyway if you can use Java. You can import rtsp or rtmp modules with minimal changes because this modules don't use Android dependencies.
encoder and rtplibrary modules depend totally of Android.

**Comment by zhubinsheng** [comment]
If the protocol is implemented with c++/c, ffmpeg is used for coding, and ffmpeg is compiled to enable hard coding, which means that ffmpeg will eventually be encoded with mediacodec on Android. In this way, the library can run across platforms

**Comment by pedroSG94** [comment]
Hello,

I don't fully understand your point but I don't want add c++ code to the project.
