### ISSUE TITLE
Wrong FormatVideoEncoder, different color palette 

### ISSUE THREAD

**Issue by digitalStyx** [pedroSG94/rtmp-rtsp-stream-client-java#115]
Hi

I have a problem with different color pallete on some device.
e.g
on Huawei VNS-L21 (Android 7.0) when I start streaming with your example app I see good colors on my phone but people who watch me seeing wrong colors.

WRONG COLORS (that people see):
![zrzut ekranu 2018-01-16 13 12 36](https://user-images.githubusercontent.com/902456/34988758-23b4ffba-fac0-11e7-861e-7f752ee7b714.png)

CORRECT COLORS:
![zrzut ekranu 2018-01-16 13 14 28](https://user-images.githubusercontent.com/902456/34988760-25c1a39e-fac0-11e7-9805-2ea3ee511c9c.png)

If I change FormatVideoEncoder.YUV420PACKEDPLANAR.getFormatCodec() for     FormatVideoEncoder.YUV420PLANAR then everything is displayed correctly

![image](https://user-images.githubusercontent.com/902456/34988968-fb4ab67c-fac0-11e7-96c4-a7b99dd09bd1.png)

What could be wrong?

**Comment by pedroSG94** [comment]
That was my bad. Fixed in version 1.3.0: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/aff0a603d0a6c8ce8d22cb4359cb899e77ef385a

**Comment by digitalStyx** [comment]
now it's work, thx 👍
