### ISSUE TITLE
Invalid NAL unit size

### ISSUE THREAD

**Issue by xumingxin7398** [pedroSG94/rtmp-rtsp-stream-client-java#1153]
Also runing your code and example on my device RK3568, click Rtsp OpenGl and start streaming, only start streaming(no recording). Using [ffplay](https://github.com/FFmpeg/FFmpeg/commit/9687cae2b4) to play the streaming url, afer few minutes, it shows some error and the ffplay preview pause but streaming still runing, after replay this url, it works fine again. How can I find out this error and fix it?
![issue_nal](https://user-images.githubusercontent.com/7893611/177030421-ae167753-8cde-4423-aea2-71cd1828a54e.png)

**Comment by pedroSG94** [comment]
Hello,

Are you receiving in rtmp? (I can see flv). I haven't enoughth info to know the problem. I recommend you try without transcode the protocol (receive and send in the same protocol).

If you try to find the error in Google:
https://unix.stackexchange.com/questions/471760/die-2-of-3-ffmpeg-recordings-freebsd
https://stackoverflow.com/questions/56891036/python-video-streaming-stream-ends-prematurely-at-0-should-be
This seems to be related to server or player side (memory or connections problems)

**Comment by xumingxin7398** [comment]
I will check it ,thinks
