### ISSUE TITLE
StreamBase How to display on screen in the background？

### ISSUE THREAD

**Issue by WuXiaoran** [pedroSG94/rtmp-rtsp-stream-client-java#1156]
I need to display the screen in the background.
But the live broadcast seems to be bound with surfaceview.
I refer to diasplaystream.
But I don't know how to modify it.

**Comment by WuXiaoran** [comment]
thank you
I modified the example that the preview data is not displayed in the background.

**Comment by pedroSG94** [comment]
So, All is solved?
In this case you can close the issue.
