### ISSUE TITLE
why when i choose send video without audio it keeps sending empty audio ?

### ISSUE THREAD

**Issue by AhmedHumk** [pedroSG94/rtmp-rtsp-stream-client-java#1157]
using rtmpCamera1.disableAudio(); doesnt seems to eliminate audio from the stream

also exoplayer cant play any rtmp stream that been published by this library

**Comment by AlexUrrutia** [comment]
What ExoPlayer version are you using? 
I’m using rtmpcamera1 to stream and ExoPlayer latest version to play and it works fine without any problem, disableAudio(); works as well.

**Comment by AhmedHumk** [comment]
which server you are using nginx ?

**Comment by AlexUrrutia** [comment]
Yes nginx and ExoPlayer 2.18.0

**Comment by AhmedHumk** [comment]
are you doing special setting in nginx or you using it as it is ?

**Comment by AhmedHumk** [comment]
@AlexUrrutia can you show how did you play rtmp with exoplayer 2.18.0

**Comment by pedroSG94** [comment]
Hello,

- disableAudio method replace microphone audio buffer to empty buffer because few servers like YouTube need Audio and Video or the stream stop (basically you send silence audio). If you want totally disable audio buffer you can skip prepareAudio method but you can't enable it again on fly you need stop the stream (maybe not supported in few servers as mentioned about).
- About exoPlayer. I recommend you test with a player like VLC (directly using desktop app) to make sure that you can pull rtmp stream from your server and after that you can focus on player or server side depend of the result.

**Comment by AhmedHumk** [comment]
@pedroSG94 i tested the Player on vitamio and vlc and they work normally only exoplayer cant play the stream only exoplayer cant play the stream i tried everything without luck its mandatory to use exoplayer within the project.

thats how i stream


```
 public void StartStreaming(Boolean Audioenabled, String rtUrl) {
        if (!this.rtmpcamera.isStreaming()) {
            this.surfaceView.setVisibility(View.INVISIBLE);
            this.surfaceView.setVisibility(View.VISIBLE);

            if (!Audioenabled){
                this.rtmpcamera.disableAudio();
            }

            if (this.rtmpcamera.prepareAudio() && this.rtmpcamera.prepareVideo()) {
                this.rtmpcamera.startStream(rtUrl);
            } else {
                BA.Log("this device cant init encoder");
            }

        }
    }
```

how i do disable the audio but i couldnt figure out how to totaly remove any audio buffer

**Comment by pedroSG94** [comment]
In this case replace:
```
            if (this.rtmpcamera.prepareAudio() && this.rtmpcamera.prepareVideo()) {

```
To:
```
            if (this.rtmpcamera.prepareVideo()) {

```
By this way microphone is totally disabled and you can also skip audio permission but as I told you in few servers maybe the server close connection because audio buffers are mandatory (check it in your case).

If you already tested with other players. Test other player but using the same device that implement exoPlayer app to discard connection problems to server with that device. You can download official VLC android app to do it:
https://play.google.com/store/apps/details?id=org.videolan.vlc&hl=es&gl=US
After that you can try find a project in github that implement exoPlayer rtmp, test it and copy code if it is working fine. 
You can start with this:
https://github.com/MortezaNedaei/RTMP-ExoPlayer
https://github.com/ponnamkarthik/RTMP-Exo-Player-Demo

**Comment by AhmedHumk** [comment]
i have disabled the microphone by removing the prepare audio sadly exoplay cant play it but vlc and vitamio can play it normally 

i have downloaded the exo player demo and has the same results probably because its old exoplayer version

**Comment by AhmedHumk** [comment]
https://github.com/MortezaNedaei/RTMP-ExoPlayer

you can test on my test server

rtmp://51.68.175.231:1935/live/amo

**Comment by pedroSG94** [comment]
> https://github.com/MortezaNedaei/RTMP-ExoPlayer
> 
> you can test on my test server
> 
> rtmp://51.68.175.231:1935/live/amo
> 
> and yes i test vitamio in andriod vitamio library and vlc android library both work only exoplayer were big hassle

I can't reproduce it using VLC or ffplay on desktop so...
Maybe you can try create a docker and share it

**Comment by AhmedHumk** [comment]
i did not publish stream on it you can use it to stream if you want i can run stream for 10 minutes so you can view and test

**Comment by AhmedHumk** [comment]
i am live now on rtmp://51.68.175.231:1935/live/amo you can see me through vlc windows and andriod, also you can see me through any vitamio andriod library

**Comment by pedroSG94** [comment]
Yes, I can see it using VLC

I tested using this docker:
https://github.com/tiangolo/nginx-rtmp-docker
And app exoplayer mentioned above:
https://github.com/MortezaNedaei/RTMP-ExoPlayer

And is wokriing fine

**Comment by pedroSG94** [comment]
Maybe nginx configuration. Try to copy configuration of the docker to test.

**Comment by AhmedHumk** [comment]
I have the exact configuration of the docker you mentioned, i migrated to exoplayer 2.18.0 with unfortunately same result. @AlexUrrutia can you please provide the coding side that makes you view the published stream in exoplayer

**Comment by AhmedHumk** [comment]
now its working if i remove disableAudio, if i set disableaudio stream doesnt show at all and i want to stream without audio

**Comment by AhmedHumk** [comment]
found some refence that i doubt its the issue with the library itself 

https://github.com/google/ExoPlayer/issues/6719

**Comment by AhmedHumk** [comment]
I guess rtmp stream should remove the audio header if the library initialized with disable audio property. Currently its very obvious that this library keeps sending audio header even if the audio disabled. Which cause errors in exoplayer

**Comment by AhmedHumk** [comment]
i have found the issue it was in the bitrate on the fly within the library itself not related to exoplayer at all.
its the implementation within the library that keeps sending audio empty bitrate which exoplayer couldn't understand what was that kind of data that received. that lead to inability to play that stream .

when disabling the audio the bitrate were is still have the audio bitrate in the stream header which makes exoplayer unable to read it .

seems other players ignore that kind of streaming behavior .. to get this solved i had to create BitrateAdapter on connection success event 

```
public void onConnectionSuccessRtmp() {
        bitrateAdapter = new BitrateAdapter(new BrateLisnter());
        bitrateAdapter.setMaxBitrate(rtmpCamera1.getBitrate());
```

@AlexUrrutia i doubt you can play directly and view in exoplayer without take in your consideration adjusting stream bitrate on the fly.

@pedroSG94 that was a bit tricky to find the real issue after spending 18 hours around this. hopefully in the library updates take in the consideration to completely remove the audio header if the user choose to disableAudio. thank you for your efforts..
