### ISSUE TITLE
Landscape mode, Camera preview rotation

### ISSUE THREAD

**Issue by ninyess** [pedroSG94/rtmp-rtsp-stream-client-java#116]
If I use RtmpCamera2 and OpenGlView in landscape mode,
the camera preview will be rotated 90 degrees.
How can I fix it?

**Comment by pedroSG94** [comment]
I'm assuming that you are using camera2 with a surfaceview and preapreVideo method without params
I did a fix for it: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/5d4995327ce83ef5db64af277be1d7d68d26b008
If you are using other configuration,  tell me how do you use the library.

**Comment by ninyess** [comment]
Thank you for answer.
I do rtmp-rtsp-stream-client-java Download the project,
This is the result of changing the portrait to landscape in the activity setting of manifest file and building and testing it.
I will attach the capture image and source to 1/22 (mon).

Thank you again. :)

**Comment by ninyess** [comment]
**origin code (line)**

OpenGlRtmpActivity.java
`@RequiresApi(api = Build.VERSION_CODES.JELLY_BEAN_MR2) (34)

private RtmpCamera1 rtmpCamera1; (38)

rtmpCamera1 = new RtmpCamera1(openGlView, this); (53)`

menifests
`<activity
        android:name=".openglexample.OpenGlRtmpActivity"
        android:label="@string/opengl_rtmp"
        android:screenOrientation="portrait"
        /> (92)`

**changed code (line)**

`@RequiresApi(api = Build.VERSION_CODES.LOLLIPOP) (34)

private RtmpCamera2 rtmpCamera1; (38)

rtmpCamera1 = new RtmpCamera2(openGlView, this); (53)`

menifests
`<activity
        android:name=".openglexample.OpenGlRtmpActivity"
        android:label="@string/opengl_rtmp"
        android:screenOrientation="landscape"
        /> (92)`

run OpenGlRTMP capture
[http://39degreesc.com/screen.png](url)

**Comment by ninyess** [comment]
**# origin code (line)**

OpenGlRtmpActivity.java
```
@requiresapi(api = Build.VERSION_CODES.JELLY_BEAN_MR2) //(34)
private RtmpCamera1 rtmpCamera1; //(38)
rtmpCamera1 = new RtmpCamera1(openGlView, this); //(53)
```

menifests
```
<activity
android:name=".openglexample.OpenGlRtmpActivity"
android:label="@string/opengl_rtmp"
android:screenOrientation="portrait" /> (92)
```

**# changed code (line)**

OpenGlRtmpActivity.java
```
@requiresapi(api = Build.VERSION_CODES.LOLLIPOP) //(34)
private RtmpCamera2 rtmpCamera1; //(38)
rtmpCamera1 = new RtmpCamera2(openGlView, this); //(53)
```

menifests
```
<activity
android:name=".openglexample.OpenGlRtmpActivity"
android:label="@string/opengl_rtmp"
android:screenOrientation="landscape" /> (92)
```

run OpenGlRTMP capture
[http://39degreesc.com/screen.png](url)

**Comment by ninyess** [comment]
# origin code (line)

OpenGlRtmpActivity.java
```
@requiresapi(api = Build.VERSION_CODES.JELLY_BEAN_MR2) //(34)
private RtmpCamera1 rtmpCamera1; //(38)
rtmpCamera1 = new RtmpCamera1(openGlView, this); //(53)
```

menifests
```
<activity
android:name=".openglexample.OpenGlRtmpActivity"
android:label="@string/opengl_rtmp"
android:screenOrientation="portrait" /> (92)
```


# changed code (line)

OpenGlRtmpActivity.java
```
@requiresapi(api = Build.VERSION_CODES.LOLLIPOP) //(34)
private RtmpCamera2 rtmpCamera1; //(38)
rtmpCamera1 = new RtmpCamera2(openGlView, this); //(53)
```

menifests
```
<activity
android:name=".openglexample.OpenGlRtmpActivity"
android:label="@string/opengl_rtmp"
android:screenOrientation="landscape" /> (92)
```

run OpenGlRTMP capture
http://39degreesc.com/screen.png

**Comment by pedroSG94** [comment]
This was solved here: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/5f6437d066ad42036acb92aca19497524c60c0b2

**Comment by ninyess** [comment]
I don't  know how I can ever thank you.
