### ISSUE TITLE
Question about get rtsp stream from IP Camera and then  use a new rtsp address to  push this stream.

### ISSUE THREAD

**Issue by stormxz** [pedroSG94/rtmp-rtsp-stream-client-java#1160]
Hi pedroSG94,

Thanks for your project.
And i have question , does your project support the following case.

step 1. An android app get rtsp address stream from IP Camera,
step 2. and then this Android app use rtsp-server to create a new rtsp address and  push the stream which get form IP Camera.
step 3. finally vlc can use new rtsp to show video view（data from IPCamera）.

I want to use VideoView to show IP Camera data, but i don't know how to push videoview data to rtsp.

Can you help me to check it.Thans for your help.

**Comment by pedroSG94** [comment]
Hello,

No, by default it is not supported. If you have a way to get h264/aac data from IP camera using other library. You can use RtspClient to stream it but you haven't a way to get that data using this library

**Comment by stormxz** [comment]
OK, Thanks for your help.
