### ISSUE TITLE
only green screen with rtsp stream using udp

### ISSUE THREAD

**Issue by annyjasmin39** [pedroSG94/rtmp-rtsp-stream-client-java#1161]
![image](https://user-images.githubusercontent.com/76213526/181018190-cf0c0549-a198-43f8-b28d-cec9b1f9a3c5.png)
only green screen ...getting nothing

**Comment by pedroSG94** [comment]
Closing issue because it is duplicated:
https://github.com/pedroSG94/RTSP-Server/issues/75
