### ISSUE TITLE
Is it possible to draw arbitrary view into stream?

### ISSUE THREAD

**Issue by b95505017** [pedroSG94/rtmp-rtsp-stream-client-java#117]
As title, which is much like [this library](https://github.com/lakeinchina/librestreaming) do.
>Support draw android View into video

Or could we write a class such as ViewStreamObject to achieve this?

**Comment by pedroSG94** [comment]
Yes, it is possible.
You can create a view and convert that view in bitmap, you have here view to bitmap conversion (not tested):
https://stackoverflow.com/questions/5536066/convert-view-to-bitmap-on-android
With this bitmap you can use ImageStreamObject to stream it.

**Comment by b95505017** [comment]
But I need to draw view animation, such as [Keyframes](https://facebookincubator.github.io/Keyframes/). I think convert everything into Bitmap may cause bad performance?

**Comment by pedroSG94** [comment]
Ah ok.
This library use opengl and surfacetexture too so you can emulate it in this class:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/gl/GlWatermarkRenderer.java

**Comment by pedroSG94** [comment]
This is developed using AndroidViewFilter:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L112

**Comment by b95505017** [comment]
@pedroSG94 Just saw your sample, amazing.
Just a question, what's the relationship between `OpenGlView` and `AndroidViewFilterRender `?
In the sample, you set the whole content View into `AndroidViewFilterRender`, including `OpenGlView`, does it necessary?
