### ISSUE TITLE
rga_rgb2nv12 fail

### ISSUE THREAD

**Issue by annyjasmin39** [pedroSG94/rtmp-rtsp-stream-client-java#1171]
![image](https://user-images.githubusercontent.com/76213526/187165875-fecd8a92-47e1-4c8e-af4c-1ad173d0deb0.png)

**Comment by annyjasmin39** [comment]
I am using SurfaceView with Camera2 api..I understand surfaceview is depreciated, but still I dont have to do any rotation or any other thing...

**Comment by pedroSG94** [comment]
I don't understand you.
Where do you have this error? in player side?
Did you tried other player? Did you tried with OpenGlView to discard problems only with SurfaceView?

**Comment by annyjasmin39** [comment]
any update please?

**Comment by annyjasmin39** [comment]
I tried with Openglview as well...its giving same error,
this error not giving in player side...when i run the application it is giving the error...
it seems the device(rockchip) we are using,it is giving problem(https://github.com/ayufan-rock64/android_update_from_170605_to_170630/blob/master/hardware_rockchip_omx_il/0002-log-change-log-to-more-short.patch)...

I was checking this-
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/1121

it seems it is getting data in rgb buffers in our device,could you please suggest where we can inject the 
YUVUtil.ARGBtoYUV420SemiPlanar code in current project codes...

I am using Camera2 api with surfaceview and also tried with openglview ,giving same error..

please help

**Comment by pedroSG94** [comment]
Maybe, it is a bug in your encoder device.
I can't solve it if the bug is in the device SO.

If camera2 isn't working try with camera1 with OpenGLViewbtondicard camera2 error in your device and camera1 with SurfaceView that use YUV instead of RGB.

**Comment by annyjasmin39** [comment]
Thanks for reply,could you please suggest where exactly i need to check for specific configuration in camera2apimanager class

**Comment by pedroSG94** [comment]
This is the class:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java

**Comment by annyjasmin39** [comment]
I was able to solve this rgb2nv12 fail,but now facing... getvideodata only called once,could you please point me to right direction

**Comment by pedroSG94** [comment]
VideoEncoder and Camera2ApiManager are related with the surface provided by VideoEncoder. VideoEncoder create a surface that Camera2ApiManager render. When this surface is renderer Videoencoder get data from that surface automatically.
About getVideoData only called once. Are you sure that your change is working properly? If you never render the surface provided by VideoEncoder properly you will never get new data and I think that it is the case.

**Comment by pedroSG94** [comment]
Maybe yes.

- If using camera1 with OpenGLView you have the same problem but it is working using camera1 with SurfaceView or TextureView -> the problem should be encoder. 
- If you can work using camera1 with OpenGLView -> the problem is related with camera2.
This is because camera1 with OpenGlView use the same configuration of VideoEncoder than Camera2 with SurfaceView, TextureView or OpenGLView.

Relating with your code:

> public void getVideoData(ByteBuffer h264Buffer, Android.Media.MediaCodec.BufferInfo info)
> {
> fpsListener.calculateFps();
> byte[] bytes = new byte[h264Buffer.Remaining()];
> var bb= YUVUtil.ARGBtoYUV420SemiPlanar(bytes,640,480);
> getH264DataRtp(ByteBuffer.Wrap(bb), info);
> }

This is incorrect because the bytebuffer is h264 format not argb.

> videoFormat.SetInteger(MediaFormat.KeyColorFormat,
> FormatCodecData.getFormatCodec(FormatVideoEncoder.YUV420Dynamical));

This is only used if you set yuv bytebuffers to VideoEncoder. If you are using a surface renderer by camera api this parameter must be: FormatVideoEncoder.SURFACE

Basically means:
- If you will feed VideoEncoder using a Surface -> FormatVideoEncoder.SURFACE
- If you will feed VideoEncoder using YUV buffers -> FormatVideoEncoder.YUV420Dynamical

With camera2 you will always use a surface so it have no sense.

> please help ,i think we can fix these kind of issues because this issue is happening with your demo codes as well if i use camera2,may main issue is with these kind of devices is the buffer we are getting from **inputSurface = codec.CreateInputSurface();** is in any other format ,format in the sense color format or may be sending always null values which might not be the case also as we can see a green screen

No, you can't change the color format from a Surface. The code mentioned only works if the you use FormatVideoEncoder.SURFACE for the reason mentioned above about VideoEncoder feed cases.

> [ACodec] do not know color format 0x7f000789 = 2130708361
> [ACodec] setupVideoEncoder succeeded
> [ACodec] do not know color format 0x7f000789 = 2130708361

You can ignore it. It isn't an error.

I highly recommend you use camera1 if it is working for you and forget about camera2. In most of cases you don't need camera2 features if you don't need record/stream in a resolution higher than 1080p

**Comment by annyjasmin39** [comment]
Thanks a lot for brief explanation, I really appreciate it.
Actually I started with Camera2 ,as in our project already it is using camera2 api and the codes are quite similar to yours.
Then I started testing with Camera1,it worked beautifully.

Its not about resolution,even I can show the manager with lowest resolution,problem is with encoding,color formats it seems

I think rockchip platform has issues...i am checking all-

https://github.com/codeceo-net/exoplayer1.5.0/blob/ff651b1fae5f8a00e0a3016cb4802451b7f6ef12/src/com/google/android/exoplayer/MediaCodecTrackRenderer.java

even you check the above codes whcih is actually native one(expoplayer) nowadays....they are nothing doing anything for rockchip platform...even in other repos...i was checking....they have balcklisted rockchip hardware encoders...but surprisingly,in today's world. lot of device use rockchip hardware

**Comment by pedroSG94** [comment]
Hello,
In most of cases the problem isn't chipset itself. Normally the problem is related with codec implementation in each ROM.
I mean that it is usually a software problem in your SO

**Comment by annyjasmin39** [comment]
HI,

First of all Thanks @pedroSG94 for taking out time and  explaining each single thing briefly, I really appreciate it...
Secondly I was able to fix this by implementing camera1 codes in camera2(though RGB2NV12 fail issue still exists ).
So in case if anybody need it here is what I have done-
(Note this will work only if camera1 is working with surfaceview,and you are expecting same thing in camera2)
1.Keep all codes same,change only in camera2apimanager
2.create a imagereader in camera2 with YUV similar to this and set a imagelistener-
 yuvImageReader = ImageReader.NewInstance(640, 480, ImageFormatType.Yuv420888, 2);
                    yuvImageReader.SetOnImageAvailableListener(yuvImageAvailableListener,handler);
3.Now in imagelistener (yuvImageAvailableListener),similar to below-

 try
            {
                 image = reader.AcquireNextImage();
                if (image == null)
                {
                    return;
                }
this.inputYUVData(new Frame(convertYUV420ToNV21(image), 0, true, (int)ImageFormatType.Nv21));
            }
make sure you will close image once job is done,or else camera will stuck
4.This convertYUV420ToNV21,i picked from here and its working fine-
https://stackoverflow.com/questions/39024263/incorrect-transformation-of-frames-from-yuv-420-888-format-to-nv21-within-an-ima
5.Add this image reader's surface in createcamerasession ,also target it in buildersurface
6.in preparevideoencoder in camera2base class the formatencoder should be yuv420dynamical

Thats it,no need to change existing codes...as all existing codes are working and designed beafutifully..just we need to add few line of codes in camera2apimanager class
