### ISSUE TITLE
Rtmp support multiple publisher?

### ISSUE THREAD

**Issue by SudoDios** [pedroSG94/rtmp-rtsp-stream-client-java#1174]
Hi, 
does rtmp support multiple publishers?

**Comment by pedroSG94** [comment]
Yes,
You can use this classes:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/master/rtplibrary/src/main/java/com/pedro/rtplibrary/multiple
You have a description in the header to guide you a bit about the usage

**Comment by SudoDios** [comment]
thank you so much 🌹
