### ISSUE TITLE
Sending live stream h264 data from MediaCodec callback

### ISSUE THREAD

**Issue by 1goresha** [pedroSG94/rtmp-rtsp-stream-client-java#1177]
I have live stream h264 data from MediaCodec callback and i need to send h264 data with RTSP using your lib, how can i do this?

**Comment by pedroSG94** [comment]
Hello,

You can use RtspClient class directly.
You have an example here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtsp/RtspCamera1.java
Also, you can check this issue related with your case:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/1033

**Comment by 1goresha** [comment]
thank you!
