### ISSUE TITLE
Screen distortion at 960 X 540 resolution

### ISSUE THREAD

**Issue by Timoky-DM** [pedroSG94/rtmp-rtsp-stream-client-java#1181]
Hello @pedroSG94

I am using your library well.

There is one problem, when I show the preview or start stream, there is distortion at 16:9 960 X 540 resolution (qhd).

> 1280 X 720 (HD)
![Screenshot_20221026-153956_FilterExample](https://user-images.githubusercontent.com/107375981/197953239-a877e625-2503-447e-b6a5-32f312ea6154.jpg)

> 960 X 540 (qHD)
![Screenshot_20221026-154003_FilterExample](https://user-images.githubusercontent.com/107375981/197953272-a7c20f72-b1d0-4e69-99cc-d4b23d0dfdcc.jpg)

The source code that tested the above situation is as follows.

> fragment_gl_view

``` kotlin
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools">

    <data>
        <variable
            name="viewModel"
            type="com.example.filterexample.glView.GlViewModel" />
    </data>

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <FrameLayout
            android:id="@+id/addWebViewContainer"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

        <com.pedro.rtplibrary.view.OpenGlView
            android:id="@+id/glView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:aspectRatioMode="@{viewModel.aspectRatioMode}"
            app:isFlipHorizontal="false"
            app:isFlipVertical="false"
            app:numFilters="10" />

        <androidx.constraintlayout.widget.ConstraintLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="#77777777">

            <TextView
                android:id="@+id/textView"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:text="Apply by directly entering the preview quality"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintTop_toTopOf="parent"/>

            <EditText
                android:id="@+id/widthEt"
                android:layout_width="100dp"
                android:layout_height="wrap_content"
                android:inputType="number"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/textView"
                android:layout_marginTop="10dp"/>

            <EditText
                android:id="@+id/heightEt"
                android:layout_width="100dp"
                android:layout_height="wrap_content"
                android:layout_marginStart="20dp"
                android:inputType="number"
                app:layout_constraintStart_toEndOf="@+id/widthEt"
                app:layout_constraintTop_toTopOf="@+id/widthEt" />

            <Button
                android:layout_width="100dp"
                android:layout_height="wrap_content"
                android:onClick="@{() -> viewModel.setPreviewCustomSize()}"
                android:text="apply"
                app:layout_constraintBottom_toBottomOf="@+id/heightEt"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toEndOf="@+id/heightEt"
                app:layout_constraintTop_toTopOf="@+id/heightEt" />
        </androidx.constraintlayout.widget.ConstraintLayout>

        <androidx.constraintlayout.widget.ConstraintLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_alignParentBottom="true">

            <Button
                android:id="@+id/qualityLow"
                android:layout_width="120dp"
                android:layout_height="wrap_content"
                android:onClick="@{() -> viewModel.setPreview(1)}"
                android:text="nHD\n(640*360)"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toStartOf="@+id/qualityMiddle"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent" />

            <Button
                android:id="@+id/qualityMiddle"
                android:layout_width="120dp"
                android:layout_height="wrap_content"
                android:onClick="@{() -> viewModel.setPreview(2)}"
                android:text="qHD\n(960*540)"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent" />

            <Button
                android:id="@+id/qualityHigh"
                android:layout_width="120dp"
                android:layout_height="wrap_content"
                android:onClick="@{() -> viewModel.setPreview(3)}"
                android:text="HD\n(1280*720)"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toEndOf="@+id/qualityMiddle"
                app:layout_constraintTop_toTopOf="parent" />

            <Button
                android:id="@+id/quality2k"
                android:layout_width="120dp"
                android:layout_height="wrap_content"
                android:onClick="@{() -> viewModel.setPreview(4)}"
                android:text="FHD\n(1920x1080)"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toStartOf="@+id/quality4k"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/qualityLow" />

            <Button
                android:id="@+id/quality4k"
                android:layout_width="120dp"
                android:layout_height="wrap_content"
                android:onClick="@{() -> viewModel.setPreview(5)}"
                android:text="UHD\n(3840x2160)"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toBottomOf="@+id/qualityMiddle" />

            <Button
                android:id="@+id/setAspectRatioMode"
                android:layout_width="120dp"
                android:layout_height="wrap_content"
                android:onClick="@{() -> viewModel.setAspectRatioMode()}"
                android:text="setAspectRatioMode\n(cur : adjust)"
                android:textSize="11sp"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toEndOf="@+id/quality4k"
                app:layout_constraintTop_toBottomOf="@+id/qualityMiddle" />
        </androidx.constraintlayout.widget.ConstraintLayout>
    </RelativeLayout>
</layout>
```

> GlViewModel

``` kotlin
class GlViewModel() : BaseViewModel() {
    val aspectRatioMode = MutableLiveData<AspectRatioMode>(AspectRatioMode.Adjust)

    private val _clickSetPreviewSizeChannel = Channel<Unit>(Channel.CONFLATED)
    val clickSetPreviewSizeChannel = _clickSetPreviewSizeChannel.receiveAsFlow()

    fun setPreviewCustomSize() = viewModelScope.launch {
        _clickSetPreviewSizeChannel.send(Unit)
    }

    private val _clickSetPreviewChannel = Channel<Size>(Channel.CONFLATED)
    val clickSetPreviewChannel = _clickSetPreviewChannel.receiveAsFlow()

    fun setPreview(quality: Int) = viewModelScope.launch {
        val size = when(quality) {
            1 -> Size(640, 360)
            2 -> Size(960, 540)
            3 -> Size(1280, 720)
            4 -> Size(1920, 1080)
            5 -> Size(3840, 2160)
            else -> Size(16, 9)
        }
        _clickSetPreviewChannel.send(size)
    }

    private val _setAspectRatioModeChannel = Channel<Unit>(Channel.CONFLATED)
    val setAspectRatioModeChannel = _setAspectRatioModeChannel.receiveAsFlow()

    fun setAspectRatioMode() = viewModelScope.launch {
        aspectRatioMode.postValue(
            if (aspectRatioMode.value == AspectRatioMode.Adjust)
                AspectRatioMode.Fill
            else AspectRatioMode.Adjust
        )
        _setAspectRatioModeChannel.send(Unit)
    }
}
```

> GlViewFragment

``` kotlin
class GlViewFragment : BaseFragment<FragGlViewBinding, GlViewModel>(), SurfaceHolder.Callback,
    ConnectCheckerRtmp {

    private val mainViewModel: MainViewModel by activityViewModels()

    private val camera2Base: Camera2Base by lazy {
        RtmpCamera2(binding.glView, this)
    }

    // This function is defined in BaseFragment and operates within onViewCreated
    override fun init() {
        binding.lifecycleOwner = viewLifecycleOwner
        binding.viewModel = viewModel
        binding.glView.holder.addCallback(this@GlViewFragment)
    }

    // This function is defined in BaseFragment and operates within onViewCreated
    override fun initViewModelCallback(): Unit = with(viewModel) {
        // When you click the Apply button after entering any resolution
        clickSetPreviewSizeChannel.onEach {
            val width = binding.widthEt.text.toString()
            val height = binding.heightEt.text.toString()

            if (width.isEmpty() || height.isEmpty()) {
                Common.showSnackBar(binding.root, "You must enter a resolution.")
                return@onEach
            }

            mainViewModel.width.value = width.toInt()
            mainViewModel.height.value = height.toInt()

            updateGlViewPreview()
        }.observeInLifecycle(viewLifecycleOwner)

        // Click the predefined resolution button at the bottom of the screen
        clickSetPreviewChannel.onEach { size ->
            mainViewModel.width.value = size.width
            mainViewModel.height.value = size.height

            binding.widthEt.setText(size.width.toString())
            binding.heightEt.setText(size.height.toString())

            updateGlViewPreview()
        }.observeInLifecycle(viewLifecycleOwner)

        setAspectRatioModeChannel.onEach {
            binding.setAspectRatioMode.text = "setAspectRatioMode\n(cur : ${viewModel.aspectRatioMode.value?.name})"

            updateGlViewPreview()
        }.observeInLifecycle(viewLifecycleOwner)
    }

    private fun updateGlViewPreview() = with(camera2Base) {
        stopPreview()

        prepareAudio()
        prepareVideo(
            mainViewModel.width.value,
            mainViewModel.height.value,
            2000
        )

        startPreview()
    }

    override fun surfaceCreated(holder: SurfaceHolder) {}

    override fun surfaceChanged(p0: SurfaceHolder, format: Int, width: Int, height: Int) {
        updateGlViewPreview()
    }

    override fun surfaceDestroyed(p0: SurfaceHolder) {
        if (camera2Base.isRecording) {
            camera2Base.stopRecord()
        }
        if (camera2Base.isStreaming) {
            camera2Base.stopStream()
        }
        camera2Base.stopPreview()
    }

    override fun onAuthErrorRtmp() {}

    override fun onAuthSuccessRtmp() {}

    override fun onConnectionFailedRtmp(reason: String) {
        camera2Base.stopStream()
    }

    override fun onConnectionStartedRtmp(rtmpUrl: String) {}

    override fun onConnectionSuccessRtmp() {}

    override fun onDisconnectRtmp() {}

    override fun onNewBitrateRtmp(bitrate: Long) {}

    override fun onDestroyView() {
        binding.glView.holder.removeCallback(this)
        super.onDestroyView()
    }
}
```

I am using Camera2Base. Can you solve this problem?

**Comment by pedroSG94** [comment]
Hello,

You are right, the image is distorted using 960x540.
Apparently this happens in few cases if you use a resolution not supported by the camera. Seems that Camera2 API resize other resolution to fit with it producing this distortion.
Also, I had a bug using aspect ratio 1:1 but I fixed it here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/b3b5139ab6adbaff19a69f67132add90d9c08fa2

I will need find a trick to fix it because I haven't a code error calculating the image size of OpenGlView (you can check that the stream/video is distorted and the surface is exactly the same size that your resolution selected so I'm not doing any transformation).
Meanwhile, I recommend you use resolutions listed in getResolutionsBack and getResolutionsFront methods

**Comment by Timoky-DM** [comment]
The edits above did nothing for me.

I'm trying to use the resolutions listed with getResolutionsBack and getResolutionsFront , but we are forced to use the 960 X 540 resolution because the native resolution we require is a 16:9 aspect ratio.

The picture below is the method I thought of, but is it impossible to modify it in that direction?

> Suggestion 1

![image](https://user-images.githubusercontent.com/107375981/198505496-c2cbbb3f-80ef-44c7-9808-c3f4c39c7872.png)



> Suggestion 2

![image](https://user-images.githubusercontent.com/107375981/198505524-06203287-0f5f-4479-8af9-1e86acdc9041.png)

**Comment by pedroSG94** [comment]
My idea is use the method 2. But this have a problem.
What should I do if the user set a aspect ratio not found in the supported resolutions? throw an error? ignore it and set it by default that maybe produce distortion?

**Comment by Timoky-DM** [comment]
Released devices continue to create new resolutions. Looking into the future, I think that whatever resolution you set, you need to develop a way to compress it from the nearest optimal resolution to the resolution you set.
But I think this will be very difficult.
For now, wouldn't it be better to correct only the supported resolutions by compressing them, and then modifying the other resolutions by displaying distortion?

**Comment by pedroSG94** [comment]
Hello,

I did a commit that should solve the problem:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/camera2res

With this commit 960x540 was working fine in my case. Test it and let me know if it is working as expected.
If you need use gradle you can compile it like this:
```gradle
implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:camera2res-6d2c05f0d8-1'
```

**Comment by Timoky-DM** [comment]
As a result of testing with the changed commit, it was confirmed that it works normally.

Thank you for your efforts.

**Comment by Timoky-DM** [comment]
Thank you for your efforts.

I checked that it works without distortion when the commit of the answer you sent is applied.

However, the current work is in a format in which 960 X 540 (QHD) quality is returned to 1280 X 720 (HD) quality.

Even if want to transmit the broadcast in QHD quality, if it is forced to change to HD, can't use QHD quality?

Is it impossible to work with the way I answered above?

**Comment by pedroSG94** [comment]
I think that the stream result is still 960x540 (at least in my tests.
The only difference is that the camera is opened in 1280x720 and scaled to 960x540

**Comment by Timoky-DM** [comment]
There was a confusion in the comment I wrote.

As you said, the actual broadcast transmission will be sent in a size of 960 X 540.

Thank you for the correction of broadcast distortion.

I mean, I wanted the preview screen to be displayed without distortion in the same image quality as well as correcting the broadcast transmission distortion phenomenon.

For example, if I send a broadcast in 960 x 540 (qHD) size and the same ratio size of the next level in the list of supported image quality to the device is 3840 x 2160 (UHD), the broadcast will be sent in qHD quality, but the preview screen will be displayed in UHD this example will apply equally to not only the 16:9 ratio, but to all other ratios.

This makes the preview screen and the outgoing screen look like a big difference in quality.

I sincerely hope you will consider the above as well.

**Comment by pedroSG94** [comment]
You mean use the higher resolution only on preview?
I think it is not possible because preview and stream get video frames from the same source (I'm using one surface that is copied to both). That means that if you open camera to UHD, the preview and stream will be UHD scaled.

Also, use UHD by default is not the best for all cases because open camera in the highest resolution could produce problems with temperature or performance in few devices and you can't avoid it using lower resolution because internally I'm using the highest resolution.
I can use a higher resolution and re scaled it but only if you set it using a method that is totally optional

**Comment by Timoky-DM** [comment]
answer is late I'm sorry.

I don't mean that previews should have higher resolution than streams. This means that the preview and stream should be applied at the same resolution.

When a stream is sent out at 960 X 540 resolution after a recent modification, the preview is displayed at 1280 X 720 resolution to eliminate distortion, and the stream and preview are of different sizes.

The comment above illustrates the case where the 16:9 resolution size supported by the device is 960 X 540, 3840 x 2160 with no medium size.

Of course, there are no devices that support only two sizes, but this situation is explained because the percentage you want may not be a typical percentage.

The ideal solution to this issue is to want the preview, stream screen to be displayed the same size without distortion.

**Comment by pedroSG94** [comment]
> When a stream is sent out at 960 X 540 resolution after a recent modification, the preview is displayed at 1280 X 720 resolution to eliminate distortion, and the stream and preview are of different sizes.

No, it isn't the case. In both cases the resolution is 1280x720 scaled. In preview scaled to OpenGlView resolution and in stream scaled to stream resolution but the source is exactly the same (1280x720) so the quality is the same.

It is because I'm using the same surface to copy data in preview surface and in stream surface. After copy the image I do the scale depend of the surface used (stream or preview).

**Comment by Timoky-DM** [comment]
We will close the issue because it is currently operating normally without distortion.

Thank you for the correction.

**Comment by user97116** [comment]
at preview and record and stream at 1280x720 I am getting distrotation code is same as example

**Comment by pedroSG94** [comment]
Please, avoid write in a closed issue. Open a new issue and explain with detail your case. 
You can refer to this issue if needed
