### ISSUE TITLE
rtmp streaming yuv 

### ISSUE THREAD

**Issue by supr3me** [pedroSG94/rtmp-rtsp-stream-client-java#1185]
Hi, @pedroSG94 Good afternoon!

I push stream from third library TextureView widget. It decoder from h264 and render.
I can get the h264 data  and yuv data from its function:

h264 callback : onReceive(byte[] videoBuffer, int size) (offical say it is h264 data, but i am not sure :(
yuvdata callback: onYuvDataReceived(MediaFormat mediaFormat, ByteBuffer yuvFrame, int dataSize, int width, int height);

I see SrsFlvMuxer  has  send h264buffer, but its function not match the onReceive(byte[] videoBuffer, int size)

How can I use this library push stream with h264callback or yuvdatacallback?

thank you very much!

**Comment by supr3me** [comment]
#817

**Comment by pedroSG94** [comment]
Hello,

Try to implement this it using this way:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/144#issuecomment-375305491
SrsFlvMuxer can be replace to RtmpClient.

After that, let me know the result and we can fix possible issues
