### ISSUE TITLE
Changing Background Services to use RTSP instead of RTP 

### ISSUE THREAD

**Issue by kyiakiy** [pedroSG94/rtmp-rtsp-stream-client-java#1192]
Hi, is it possible to use your library to constantly stream to my RTSP end point? I have tried adding foreground services into the Default RTSP however whenever I click back and go onto the MainActivity page, the stream will be killed immediately.

I also noticed another library using Background Services, but it is running on RTP and in Koltin, is it possible to change the end point to RTSP instead of RTP?

**Comment by pedroSG94** [comment]
Hello,

You have an example to stream in background here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/master/app/src/main/java/com/pedro/rtpstreamer/backgroundexample
About the name "RTP". You can ignore it. This example support RTMP and RTSP at same time but you can modify the service to  allow only one.

**Comment by kyiakiy** [comment]
I did tried the backgroundexample, but I am unable to ping my RTSP endpoint from there. I am using a localhost rtsp local server to test this connection out. Works with RTSP DefaultExample but not the BackgroundExample. Did I missed something out over here ?



![RTP Service Stream Fail](https://user-images.githubusercontent.com/63848291/202511343-9207d9a3-a7aa-4664-a7a1-d54b325753b8.jpg)
