### ISSUE TITLE
Blank/Black Bitmap takePhoto

### ISSUE THREAD

**Issue by rashid56156** [pedroSG94/rtmp-rtsp-stream-client-java#1193]
Hey Pedro, i am getting black/blank Bitmpap.

Device: Samsung Galaxy S10
OS Version: 12

`  rtmpCamera1.getGlInterface().takePhoto(new TakePhotoCallback() {
                            @Override
                            public void onTakePhoto(Bitmap bit) {
                               
                            }
                        }); `

Any sort of help would be appreciated. Thanks.

**Comment by pedroSG94** [comment]
Hello,

I will check it.
Do you have more info to reproduce it? 
- Stream resolution, view resolution (OpenGlView size)
- Did you have the problem record/streaming, without it or in both cases?

**Comment by pedroSG94** [comment]
Hello,

I tested takePhoto method using app example. I replaced this:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L430
To this:
```java
        rtmpCamera1.getGlInterface().takePhoto(new TakePhotoCallback() {
          @Override
          public void onTakePhoto(Bitmap bitmap) {
            setImageToStream(bitmap);
          }
        });
```
I tested around 20 times and all images working perfectly. Can you try it by this way?
Also, provide me a way to reproduce your case

**Comment by rashid56156** [comment]
Sure, let me give it a shot, will get back to you with update. Thanks mate for the effort that you put in for our issues.

**Comment by rashid56156** [comment]
Hello Pedro, the issue is resolved, it was a bug in my own implementation. Thanks for the help man.
