### ISSUE TITLE
Problem RTSP streaming to server

### ISSUE THREAD

**Issue by fkiraz** [pedroSG94/rtmp-rtsp-stream-client-java#120]
I am trying to develop an app which streams RTSP over UDP. I tried this library with code below.

```
rtspCamera1.setProtocol(Protocol.UDP);
                if (rtspCamera1.prepareAudio() && rtspCamera1.prepareVideo()) {
                    rtspCamera1.startStream("rtsp://192.168.4.54:7777/live/test.ts");
                } else {
                    Log.e(MainActivity.TAG, "ERROR RTSP");
                }
```
My logcat like this:

send packet, 457 Size, 5004 Port

I have a RTSP server at 192.168.4.54:7777 and server seems accepted my stream

```
2018-01-23 08:07:22.086 [rtsp/http/rtmpt] server started on port 7777
2018-01-23 08:07:25.161 [rtsp/http/rtmpt:client=c1] connected
2018-01-23 08:07:25.174 Unknown (not implemented) SDP: i=N/A
[rtsp/http: 1 clients]
 c1: session=68462247 addr=192.168.5.57 port=43899 type=publish-udp
2018-01-23 08:07:25.192 [rtsp/http/rtmpt:client=c1] started uploading stream live/test.ts
```
Outputs are ok but when I try to watch the stream with VLC, it timeouts and closes with black screen. Don't know what is the problem. All of my ports are opened.

Port 7777 is listening, i tested streaming with ffmpeg and it works.

**Comment by pedroSG94** [comment]
What server are you using?
Did you try watch stream with ffplay?
Is working RTSP over TCP?

**Comment by fkiraz** [comment]
I am using https://github.com/iizukanao/node-rtsp-rtmp-server
I tried with ffplay, result was the same. It timeouts after some time without showing anything.
It is not working over TCP, when I set TCP as protocol, the server has thrown an exception and closed.
I looked at server's debug logs, there were no errors. 

Streaming: Handshake was successful on 7777 port, server started to record the stream from 5004 and 5006 ports. I could see that from tcpdump. That means android app sends data with no problems.

Watching: Handshake was successful on 7777 port but no video/audio data sent from server. When I tested the server with ffmpeg, it worked, i could watch the stream. It sent the data to 7042 and 7044 ports.

**Comment by fkiraz** [comment]
I updated node for server and now I can watch TCP streams. However UDP streams are still same.

**Comment by pedroSG94** [comment]
Yes, I tried last version and UDP is not working. TCP work fine.
I think, I have an older version with UDP working, anyway I will test it.

**Comment by KeplerC** [comment]
Hi Pedro, 
Could you please give me more details on how to make it work on this node server? I tried with TCP and it works, but it does not work for udp

**Comment by pedroSG94** [comment]
I will check it and report you here

**Comment by KeplerC** [comment]
Thanks, and thank you for this great work!
