### ISSUE TITLE
How to check this streaming status?

### ISSUE THREAD

**Issue by WillyWLLu** [pedroSG94/rtmp-rtsp-stream-client-java#122]
Dear sir,

Sometimes the network might be bad. How can I check the status of current streaming is good enough?

Thanks a lot for your help!

**Comment by pedroSG94** [comment]
This could help you:
https://github.com/facebook/network-connection-class

**Comment by WillyWLLu** [comment]
Thanks a lot for your reply.

I'm sorry, I did not express it very clearly.

I mean that the quality of streaming will be affected by many reasons. It's not just the network quality on this device, it might be caused by the server side.

It is possible to check it by streaming I/O? Or something else?

**Comment by pedroSG94** [comment]
I can't check external problems.
If you want see server problems you should create your own socket and notify to device the problem from server.
After connection, I only can see connection problem (check if I lose connection with the server, received in onConnectionFailed callback).

**Comment by WillyWLLu** [comment]
Dear sir,

I found that the frame might be discarded.
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/net/ossrs/rtmp/SrsFlvMuxer.java#L873

It means that the network connection might be not good enough?

**Comment by pedroSG94** [comment]
If you see that log from SrsFlvMuxer class, it is possible. If you see it from VideoEncoder class then this is because you are using camera1 with buffer mode (with surfaceview or textureview) and your device is too slow and it can't process the frames more fast than camera produce it (in this last case, library skip frames).

**Comment by WillyWLLu** [comment]
Dear sir,

Thanks a lot for your feedback, I will try it.
