### ISSUE TITLE
rtmpDisplay with image,gif and text

### ISSUE THREAD

**Issue by mhackeras** [pedroSG94/rtmp-rtsp-stream-client-java#123]
isnt it possible to use imageobject and other on screen display stream?

**Comment by pedroSG94** [comment]
Yes, you can.
See opengl example:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java

**Comment by mhackeras** [comment]
yeah i understand. for now i use a floating watermark-image. its not a practical way though cause its touchable :/
