### ISSUE TITLE
Please help me to send timestamp

### ISSUE THREAD

**Issue by Rishabhsoti** [pedroSG94/rtmp-rtsp-stream-client-java#126]
You really help me a lot thanks for your support please help me to send time stamp still i am unable to send timestamp.

**Comment by pedroSG94** [comment]
You can change views in the layout on real time like you do in a normal activity. In the last case for example:
```
 <Button
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:text="Text to send"
        android:layout_centerInParent="true"
android:id="@+id/b_timestamps"
        />
```
Simple get button from activity and change text:
```
Button b = findViewById(R.id.b_timestamps);
b.setText("my timestamp");
```

**Comment by Rishabhsoti** [comment]
I want to send current time to server

**Comment by Rishabhsoti** [comment]
in every frame

**Comment by Rishabhsoti** [comment]
Yes, it's working now thanks for your support it was really very helpful for me.
