### ISSUE TITLE
How to read video frames from rtmp server

### ISSUE THREAD

**Issue by luoyesiqiu** [pedroSG94/rtmp-rtsp-stream-client-java#1263]
Hello, thank you for creating a great repo. but now I have a problem that how to use it to read remote video frames real-times, Is the library support the operation?

**Comment by pedroSG94** [comment]
Hello,

This library only support push video/audio frames. If you want use a player you can try with exoplayer library developed by google that support rtmp, rtsp and hls

**Comment by luoyesiqiu** [comment]
Thank you for your answer, I'm going to find out about it.
