### ISSUE TITLE
RtmpSender: Audio / Video frame discarded after certain actions

### ISSUE THREAD

**Issue by ifacify** [pedroSG94/rtmp-rtsp-stream-client-java#1264]
When building a simple rtmp screen casting frontend for your library, https://git.jerryxiao.cc/Android/DroidCast, I discovered that some actions can trigger a bug after which no frames could be sent. The bug can be reproduced by introducing a massive screen update under high system load, like playing a very flashy video, or rotating the screen while playing a video. In my case it's 100% reproducible when streaming (at a relatively high encoding resolution, like 1080p+, reducing the resolution helps mitigating the problem) as well as fullscreening a newpipe video.

With a software encoder (either on real hardware or AVD) I'm unable to reproduce this issue.

The log is attached below, though it's probably not that helpful.
```
08-18 13:46:06.054 10288 31298  3746 I RtmpSender: wrote Audio packet, size 372
08-18 13:46:07.522 10288 31298  3723 D BufferPoolAccessor2.0: bufferpool2 0x7b82193b98 : 5(38400 size) total buffers - 1(7680 size) used buffers - 333/338 (recycle/alloc) - 5/511 (fetch/transfer)
```
Screen rotates
```
08-18 13:46:07.581 10288 31298  3736 I RtmpSender: Video frame discarded
```
[err.log](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/12375957/err.log)

**Comment by pedroSG94** [comment]
Hello,

I downloaded your project and tested with default config but I'm not able to reproduce the error.
I opened a video on YouTube to 1080p 60fps with a high screen updates and rotate screen multiple times while reproducing. Exactly this one:
https://www.youtube.com/watch?v=MagELQywiGI&t=165s

Resolution according with your logs:
```
capture width 2400 height 1080
```

Also, I did changes in rtmp and rtsp modules related with the threading that maybe solve your problem and it is not compiled in version 2.2.6.
Can you try to test with my app sample in "Display RTMP or RTSP" activity to know if it is solved?

If the problem persist try to create logs or break points in this lines to know if RtmpSender stop or it is still working:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/pedro/rtmp/rtmp/RtmpSender.kt#L139
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/pedro/rtmp/rtmp/RtmpSender.kt#L174
The first one is to know if after rotate the screen the queue pulling is still working (maybe a log is a better idea to avoid block app execution since it is called in each frame that you send to server).
The second is to know if stop is called on any point causing that queue pulling stop.

**Comment by ifacify** [comment]
Thanks for your info, I'll try bumping the version to master branch first.

**Comment by pedroSG94** [comment]
Gradle that compile last commit:
```gradle
  implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:ac768f8868'
```
For testing I'm using a Pixel 6a

**Comment by ifacify** [comment]
![image](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/assets/142522899/fe2da690-7892-447d-8db8-3e8ff74014fe)
I can confirm this breakpoint is not triggering as it should be after screen rotation.
new log at commit ac768f8868
[log.txt](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/12386409/log.txt)

**Comment by pedroSG94** [comment]
> I can confirm this breakpoint is not triggering as it should be after screen rotation.

Ok, the sender stop to send for some reason.
We will need get more info about it.
Add this line:
```kotlin
job?.invokeOnCompletion { 
      Log.e("Pedro", "error", it)
    }
```
After this line:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/pedro/rtmp/rtmp/RtmpSender.kt#L170

By this way we should see that stop reason.
Also make sure that stop method or this line is not called:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/pedro/rtmp/rtmp/RtmpSender.kt#L167

**Comment by pedroSG94** [comment]
I have other idea. Try to disable battery optimization to discard that system kill the thread because it is using so much battery

**Comment by ifacify** [comment]
I've tested with battery optimization turned to "unrestricted" at https://github.com/ifacify/rtmp-rtsp-stream-client-java/commit/655e7cf340d8784acee1ca9530eeaf27043e69f2.
![image](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/assets/142522899/00e4f925-eb08-4f00-a35d-89ac4b295de3)
These two breakpoints are never tripped until I hit the "stop" button.
Also there is no log of the job completion. The job was still running but blocked for some reason. I am still investigating the reason.
[log.txt](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/12387823/log.txt)

**Comment by ifacify** [comment]
Here is the log during a normal run (no screen rotation, stopped normally with the button)
[log.txt](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/12387832/log.txt)

**Comment by ifacify** [comment]
![image](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/assets/142522899/797a3523-32fd-4239-b397-bbd11d0a53cb)
It seems that the sending thread is stuck at RtmpMessage.kt line 130

**Comment by ifacify** [comment]
It seems that setting write chunk size to a stupidly high value (1048576) can release the blocking, but the resulting stream is not playable after the screen rotation

**Comment by pedroSG94** [comment]
Try with values 4096 or 65535 that are more commons.
Also check the total packet size please (var length before first iteration or bytes.size)
It seems that your encoder produce a massive packet after rotate device for some reason

**Comment by ifacify** [comment]
tried 102400, still blocks, also in the screenshot above I think idea is showing a packet size of (10+721579)?

**Comment by ifacify** [comment]
I don't think transferring 721579 bytes is such a demanding task though.

**Comment by pedroSG94** [comment]
> I don't think transferring 721589 bytes is such a demanding task though. Also it's quite late in the night right here. Gonna continue tomorrow. Sorry for the inconvenience.

It is not the size itself. I don't know if you have a really good connection but with a packet of 721589 you are using a bandwidth of:
721589 * 30 (fps) = 21647670 (21,64 mega **bytes**).
With the default bitrate you are using 10mega **bits**:
10 / 8 = 1,25 mega **bytes**
The difference is like 20 times higher. This have no sense
Keep in mind that, according with YouTube, 4k stream with 30fps the **maximum** recommended bitrate is 45 mega bits (5,6 mega bytes):
https://support.google.com/youtube/answer/1722171?hl=en-419#zippy=%2Cc%C3%B3dec-de-video-h%2Ctasa-de-bits%2Cbitrate

> It seems that setting write chunk size to a stupidly high value (1048576) can release the blocking, but the resulting stream is not playable after the screen rotation

It is really confuse for me. Send the packet in multiple write or only one should have no difference.
That method normally stuck for internet (you can't send bytes fast enough). If you have other problems like server close connection the method should throw an IOException.

Tomorrow, maybe we can try with a local server to totally discard internet/server side problems. You can use this server for example that only need to be executed on command line (I did the tests in this server):
https://github.com/bluenviron/mediamtx

Anyway, if you can work with the software encoder I think the best idea is get a list of your encoders to know if we have more encoders to use (hardware) and discard that encoder that seems a bit buggy. You can do it by this way:
```java
for (String s: CodecUtil.showAllCodecsInfo()) {
      Log.e("Pedro", s);
}
```
Check the logcat and share me the result

**Comment by ifacify** [comment]
I am using mediamtx this whole time, albeit an older version, 0.19.3 (haven't upgraded for ages). Bandwidth is not a problem at all. I upgraded to 1.0.0 and that also (kinda) solved the blocking problem. It seems that the hardware encoder on my phone produces some nonsense frames under heavy load which is confusing enough to block mediamtx 0.19.3. With mediamtx 1.0.0 the demuxer inside mediamtx instantly disconnects on those bad packets with "muxer error: DTS is not monotonically increasing". Let mediamtx 1.0.0 convert the rtmp stream to rtsp then you get this.
![image](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/assets/142522899/d226f3d8-424a-41f0-a731-b5fd569d5649)

**Comment by ifacify** [comment]
List of encoders: https://pb.meson.cc/s/sw6opw7l.txt

**Comment by ifacify** [comment]
At this point this is probably not a solvable problem (maybe last hope would be to try h265 or vp8?) and definitely not a "pedroSG94/rtmp-rtsp-stream-client-java" bug. Thanks for your time and patience.

**Comment by pedroSG94** [comment]
Hello,

Currently this library support H265 with RTMP.
Remember that the server used need to support enhanced RTMP that is not implemented in all servers but mediamtx with version 1.0.0 support it.
So my recommendation is:
1 - Use H265 if you only will use servers that support it.
2 - If not, you use H264 and force software encoder only for that device model
3 - Provide me device model obtained from this method and I can discard that buggy encoder only for that device and you can use H264 without worry about step 2 (recommended add it anyway for future users with the same device):
```
Build.MODEL
```
If you want you can create a PR with the fix. The codec filter must be implemented here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/utils/CodecUtil.java#L438
Adding a line like (obviously changing model equals) and maybe a comment about why the codec is discarded:
```java
else if (name.equalsIgnoreCase("OMX.qcom.video.encoder.avc") && Build.MODEL.equals("xiaomimodel")) return CodecPriority.LOW;
```

**Comment by ifacify** [comment]
1. I have no problem of using h265 only. Also I can always switch it back.
2. SW encoder is just too slow even on a higher end system. So this is pretty much out of the list (at least for anything > 720p).
3. I can provide you the device model but that information could be inaccurate since I'm using a 3rd party rom (lineageos). Although that encoder is probably provided by qcom as a binary blob. The point is, I'm not sure if this is a lineageos bug, or device specific bug, or a SDM845 bug.

**Comment by pedroSG94** [comment]
If you are not using official ROM I think that filter the codec is not a good idea no matter is the model provided by your ROM is accurate.
I hope it is only a lineageOS bug

**Comment by ifacify** [comment]
Anyway. Thanks for your help. Closing.
