### ISSUE TITLE
Hey there is issue when i put a edittext in your  android view still only predifined button and edittext is visible on screen my new component still not visible

### ISSUE THREAD

**Issue by Rishabhsoti** [pedroSG94/rtmp-rtsp-stream-client-java#127]
i am using text view for the timestamp

**Comment by pedroSG94** [comment]
For some reason textcolor in black is not visible. For now change text color to the view:
```
<TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Hello"
        android:textColor="#fff"
        />
```

**Comment by pedroSG94** [comment]
Textview error with black color text is fixed now: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/9b1cd3da33a251cda2740a9b08fc6ec9f7fb4dc8
