### ISSUE TITLE
Question about hardware encoding

### ISSUE THREAD

**Issue by hhung516** [pedroSG94/rtmp-rtsp-stream-client-java#129]
Hi Pedro,

First I'd like to say thank you for putting up such a great library!!!!

I wonder if you could comment on the ability to utilize hardware encoding with MediaCodec? A quick search shows it "should" use hardware encoding when available and it's something that Google is trying to fix since API 18 given the very segmented Android market and every HW manufacturer has its own design.

So my question is, do you know if hardware encoding is in fact being utilized by your library? If so, how do I confirm it's working, perhaps with a logcat print?

Thanks again!

**Comment by pedroSG94** [comment]
Yes, you are correct. You can't know 100% if encoder or decoder selected is hardware but you have a little way to know it by encoder or decoder name.
For example OMX.google normally is software encoder or decoder but Exynos or Qualcomm should be hardware encoder or decoder.
Normally hardware encoder have manufacturer microprocessor name in it.
You can see encoder selected in the logcat.

**Comment by hhung516** [comment]
Thank you Pedro!

I saw in logcat that on S7 it's using Exynos which should be hardware encoder.

-  videoEncoder OMX.Exynos.AVC.Encoder type supported: video/avc

I also found an app that shows all available encoders/decoders, pretty handy to have.

https://coderoid.wordpress.com/2014/08/01/obtaining-android-media-codec-information/
https://bitbucket.org/bharatmolleti/mediacodecinfo

**Comment by hhung516** [comment]
Sorry I spoke too soon. Further down I saw that OMX.google was used for the encoding.

**Comment by hhung516** [comment]
Below is the logcat filtered by "encode", seems Exynos.AVC encoder is being used, and the software google.aac encoder is handing the audio. I'm streaming the surface by the way.

Thanks again!

I/VideoEncoder: videoEncoder OMX.Exynos.AVC.Encoder type supported: video/avc
I/VideoEncoder: Color supported: 2135033992
I/VideoEncoder: Color supported: 19
I/ACodec: [OMX.Exynos.AVC.Encoder] Now Loaded
I/ACodec: setupAVCEncoderParameters with [profile: Baseline] [level: Level31]
I/ACodec: [OMX.Exynos.AVC.Encoder] cannot encode color aspects. Ignoring.
I/ACodec: [OMX.Exynos.AVC.Encoder] cannot encode HDR static metadata. Ignoring.
I/ACodec: setupVideoEncoder succeeded
I/ACodec: [OMX.google.aac.encoder] Now Loaded
I/ACodec: [OMX.Exynos.AVC.Encoder] Now Loaded->Idle
I/ACodec: [OMX.google.aac.encoder] Now Loaded->Idle
I/ACodec: [OMX.Exynos.AVC.Encoder] Now Idle->Executing
I/ACodec: [OMX.Exynos.AVC.Encoder] Now Executing
I/ACodec: [OMX.google.aac.encoder] Now Idle->Executing
I/ACodec: [OMX.google.aac.encoder] Now Executing
