### ISSUE TITLE
How to capture a image while streaming 

### ISSUE THREAD

**Issue by Shanmugamsundarrajan** [pedroSG94/rtmp-rtsp-stream-client-java#132]
Need to capture a frame and send to our server while video streaming

**Comment by pedroSG94** [comment]
To do it you need use stream with OpenglView. Examples:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/master/app/src/main/java/com/pedro/rtpstreamer/openglexample
You can set any bitmap with method setImageStreamObject. Example:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L219
So you only need do a capture with camera1 or camera2(depend what camera do you want use) api or glreadpixel (if you want send [effects setted](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L459) to stream too).
The most easy way is take a photo with camera1 api with [PictureCallback](https://developer.android.com/reference/android/hardware/Camera.PictureCallback.html) ([you can find an example using google](https://stackoverflow.com/questions/23921128/take-a-picture-with-camera-and-get-bitmap)). To do it you will need create the method in this class:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java

**Comment by Shanmugamsundarrajan** [comment]
Thanks a lot for your quick response.

I am streaming using RtspCamera2 and Camera2Base for video streaming. I need to capture an image in between while streaming.

I am streaming Video for 1 minute,  and I want to send an image at random intervals (say at 10 / 20 /30 secs). 
How to achieve this.

**Comment by pedroSG94** [comment]
In this case you need modify this class to take a photo:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java
For this you need use [ImageReader class](https://developer.android.com/reference/android/media/ImageReader.html). Example:
https://github.com/pedroSG94/camera2-and-samsung-camera-example/blob/master/app/src/main/java/com/droiders/camera2apitest/cameraapi2/Camera2ApiManager.java
You should get image in [onImageAvailable callback](https://github.com/pedroSG94/camera2-and-samsung-camera-example/blob/master/app/src/main/java/com/droiders/camera2apitest/cameraapi2/Camera2ApiManager.java#L193 (Remember that this callback is called on every frame so you will need, for example, use a boolean to take only a frame).

**Comment by Shanmugamsundarrajan** [comment]
Thank you,

I will go through the same and implement it

**Comment by Shanmugamsundarrajan** [comment]
Hi pedro,

Sorry for pinging you, after a long time on this issue.

I coded accordingly as you insisted, but the call back is not happening, so i am not able to capture the image.

Please help
I will attach the Camera2ApiManager.java that i have code based on your inputs.

[Camera2ApiManager.txt](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/2216172/Camera2ApiManager.txt)
