### ISSUE TITLE
Video encoding is blurry

### ISSUE THREAD

**Issue by maan-smith** [pedroSG94/rtmp-rtsp-stream-client-java#134]
Hello @pedroSG94 ! 

Thanks for this library it helps me alot but I have a question. Video is blurry using rtmp player using default encoding. If I am increasing the video bit rate its getting delay to preview or stream that broadcast. Can you help me for this how to update the best optimal resolution and video encoding.

**Comment by pedroSG94** [comment]
If you see delay with some configurations, normally is bandwidth problems. I recommend you use a local server to test.
I did a little test and this is the result (local server and VLC to reproduce stream):
resolution -> video bitrate:

- 640x480 -> 1000 * 1024

-1280x720 -> 1800 * 1024

-1920x1080 -> 2500 * 1024

**Comment by maan-smith** [comment]
Thanks will try that can you update me about video encoders too. Which is best and why we are using mime = video/aac

**Comment by pedroSG94** [comment]
This library use mimes video = "video/avc" and audio = "audio/mp4a-latm", H264 and AAC codecs respectively but no special reason only because it is the most standard codecs in the streaming industry.
