### ISSUE TITLE
How to stream only a part of screen (or only a android view)?

### ISSUE THREAD

**Issue by sonbx** [pedroSG94/rtmp-rtsp-stream-client-java#136]
I want to stream only a part of screen without capturing status bar or navigation bar.

**Comment by pedroSG94** [comment]
If you want send an Android view you can see this (in this example you send only a button):
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/125
If you want send only the Android view but no camera you can set background color to layout or use match parent in android view to set full screen. In this case you will hide camera behind layout.
Remember that your views must be inflated.

**Comment by sonbx** [comment]
Thank you, but I want to stream a GLSurfaceView. Is it possible?

**Comment by pedroSG94** [comment]
Use GlSurfaceView instead of my OpenGlView or stream both?
The first option is possible but need so many changes. The second option, I'm not sure I never try it.

**Comment by sonbx** [comment]
GlSurface instead of your OpenGLView.
Can you please tell me what changes?

**Comment by pedroSG94** [comment]
You need get InputSurface from VideoEncoder and copy GlSurfaceView frame to this InputSurface every times (I haven't an example for you now, you will need wait to monday or maybe tuesday and I will develop the example if you really need it).
Anyway OpenglView is more flexible than GlSurfaceView, also you can see [LightOpenglView](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/view/LightOpenGlView.java) that is more easy to understand and modify. You can modify [SimpleCameraRender](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/gl/render/SimpleCameraRender.java) and emulate your GLSurfaceView (of course you can ignore SurfaceTexture id on this class and no send camera frame)

**Comment by sonbx** [comment]
Thank you very much.
I really really need it. So please help me if you have time.
Thank you.

**Comment by sonbx** [comment]
I tried replace button of example to GlsurfaceView but not succeed.
Can you please help me find a solution?

**Comment by pedroSG94** [comment]
CustomGLSurfaceView with stream was added: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/a3ff2ca07cf0952b1d68ab655f1d04b08804a90d
AndroidViewFilter doesn't work with GLSurfaceView because this view don't draw anything on draw method in the canvas. The only way to do this view work is override that method and draw in the canvas with the result of GLES20.glReadPixels();

**Comment by sonbx** [comment]
Thank you very much.
I tested but the streaming video was not smooth like this
![glsurface_stream_test](https://user-images.githubusercontent.com/4996420/36705397-8395513a-1b97-11e8-8d0c-30cc7db037ac.gif)
Can you check it please?

**Comment by pedroSG94** [comment]
Yes I know it. I didn't enabled AA in opengl. This is only an example. I will check it anyway this is only an orientation for developer to know, how to use your own custom GLSurfaceView to stream.

**Comment by sonbx** [comment]
Thank you. I want to know that enable AA in opengl can make the output as same as the input?

**Comment by pedroSG94** [comment]
AA is antialiasing (reason of jagged edges normally). If you are talking about this method:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L726
This is for FXAA antialiasing, It is low cost but no really good result (only available in OpenGlView, shader used: [fxaa](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/res/raw/fxaa.glsl)). The best way is use MSAA antialiasing.

**Comment by pedroSG94** [comment]
I did a commit to enable AA in CustomGlSurfaceView. To enable AA you need uncomment this lines:
```java
EGL14.EGL_SAMPLE_BUFFERS, 1 /* true */,
EGL14.EGL_SAMPLES, 4, /* increase to more smooth limit of your GPU */
```
You can find this lines here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/view/CustomGlSurfaceView.java#L60

https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/gl/SurfaceManager.java#L99

https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/gl/SurfaceManager.java#L111

**Comment by sonbx** [comment]
Thank you. But I am talking about the playback side.
https://user-images.githubusercontent.com/4996420/36705397-8395513a-1b97-11e8-8d0c-30cc7db037ac.gif
I sent captured glsurfaceview data to youtube server and the video is very lagged like this.

**Comment by pedroSG94** [comment]
Low frame rate(fps)? I tested with youtube and work fine. Try with other devices and with other stream mode like using OpenGlView.
If you are talking about delay, nothing to do, youtube produce delay.

**Comment by sonbx** [comment]
Thank you very much.
