### ISSUE TITLE
how to get progress while stream rtmp from file

### ISSUE THREAD

**Issue by pratheepchowdhary** [pedroSG94/rtmp-rtsp-stream-client-java#137]
thank for such good library
how to get progress while stream rtmp from mp4 file 
and also how can i add the  water marks over the video file while streaming.

**Comment by pedroSG94** [comment]
For now both features was no added. Anyway I have plan to add both.
I'm developing watermark and filter in file and display mode. Also I want add move to a file second

Add progress should be easy, you can get it with mediaextractor class in decoders using getsampletime like:
```java
extractor.getSampleTime();
```

**Comment by pedroSG94** [comment]
Loop mode, progress, duration and moveto implemented. moveTo is too slow for now (I don't know the reason but mediaextractor need few seconds to work).
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/2c4820a78593c9a2c1e3be438921106c31d0d0d8

**Comment by pedroSG94** [comment]
Watermarks and effects is now available in stream file mode: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/e48a40e11694f2413bb79c3b873254b628b34803
You only need set context to the constructor if you want use it. Also remember that if you use loop mode when file restart all watermarks or effects will be cleaned.
The method to use is like with OpenGlView mode.

**Comment by pratheepchowdhary** [comment]
thank u sir
