### ISSUE TITLE
MediaMuxer

### ISSUE THREAD

**Issue by AliceDinh** [pedroSG94/rtmp-rtsp-stream-client-java#14]
Hi,
With rtmp, you have MediaMuxer to mux the audio and video frames. What's about rtsp, which tool plays muxing role?
Thanks,

**Comment by pedroSG94** [comment]
No, I haven't a MediaMuxer.
SrsFlvMuxer is not a MediaMuxer, this class connect to server and create flv packet of video or audio (separately) and send over the net. RtspClient do a similar roll in rtsp.

**Comment by AliceDinh** [comment]
Hi,
You make some changes from yasea of Leoma, he convert RGBAToI420 and RGBAToNV12, but you convert YV12toYUV420 and NV21toYUV420.
Is there any reason behind this?
Thanks

**Comment by pedroSG94** [comment]
Yes. Because Yasea use opengl with a glreadpixel and it get RGBA format. I'm using camera data directly that get data in nv21 and yv12.
nongpuimage brach of yasea use a similar way.

**Comment by AliceDinh** [comment]
Wow, got it now, thanks

**Comment by pedroSG94** [comment]
I think that convert RBGA to YUV420. If not i don't know
