### ISSUE TITLE
 java.lang.OutOfMemoryError: Failed to allocate a 357875070 byte allocation with 16777216 free bytes and 260MB until OOM

### ISSUE THREAD

**Issue by ellu15** [pedroSG94/rtmp-rtsp-stream-client-java#141]
I have used OpenGlView for RTMP Streaming.It works fine but after long time(20-30 Min) its gives OutOfMemoryError Exception.
Any solution for this?
Thanks

**Comment by pedroSG94** [comment]
I need device model and API version.
The problem persist using other view without opengl like a surfaceview? 
If you use a lower resolution do you see the error?
Do you see frame discarded in the logcat before app crash?

For now you can extend duration using largeheap in the manifest but it is not a real solution only extend time.

**Comment by ellu15** [comment]
I need device model and API version.
>Vuzix M300 Smart Glass(Marshmallow) and Nexus 5(Marshmallow 6.0.1)

If you use a lower resolution do you see the error?
>I have tried changing to lower resolution and bitrate but problem not solved.

For now you can extend duration using largeheap in the manifest but it is not a real solution only extend time.
>Already used  largeheap

**Comment by pedroSG94** [comment]
What are you using to send timestamp? Maybe the error is opengl that no release some texture.
If you don't send timestamp the error persist?
Can you share me code used to send timestamp?

**Comment by ellu15** [comment]
If you don't send timestamp the error persist?
>Yes same problem.

Code for sending TimeStamp .
````
 private void startTimer() {
        if (timer == null) {
            timer = new Timer();
            timer.scheduleAtFixedRate(new TimerClockUpdate(), 0, 1000);
        }
    }

    private class TimerClockUpdate extends TimerTask {
        @Override
        public void run() {
            setTextToStream();
        }
    }

    @SuppressLint("NewApi")
    private void setTextToStream() {
        try {
            textStreamObject.load(dateFormat.format(Calendar.getInstance().getTime()), 23, Color.YELLOW);
            rtmpCamera1.setTextStreamObject(textStreamObject);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }`
```

**Comment by ellu15** [comment]
Do you see frame discarded in the logcat before app crash?
>Yes,

**Comment by pedroSG94** [comment]
I think the error is solved now in the last commit: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/0faec69ec1141f0b1707f40b98d5faaa7614c77d

Please clone last commit and try. If the error persist use android profiler of android studio and in memory section let me know what field(graphics, stack, code, others) increase along of the stream.
Could be useful first stable value of the stream and last value before crash.

**Comment by ellu15** [comment]
I update code but same error occur. 
Throwing OutOfMemoryError "Failed to allocate a 103232416 byte allocation with 8388608 free bytes and 173MB until OOM"

Stable Value in Memory Section 
![screenshot 19](https://user-images.githubusercontent.com/22025863/37385183-ecc075bc-2778-11e8-8863-1721a472de1f.png)

Last value in Memory Section 
![screenshot 21](https://user-images.githubusercontent.com/22025863/37385206-0fecf592-2779-11e8-9cfc-36d56a938f1c.png)

**Comment by pedroSG94** [comment]
I wanted to say memory usage when you are streaming about 30-40min (before your device crash).
I did a test with a nexus5 and no crash after 40min streaming with the fix (I'm using OpenGlRtmpActivity, try use this activity to test and discard external causes). I will do other try with 1080p and then test with vuzix.

**Comment by ellu15** [comment]
Hello,
It`s working now fine.
Thank you very much for your support.

**Comment by Rider02vn** [comment]
@pedroSG94 
Hello.
I also have `OutOfMemoryError` error on **Samsung Galaxy S20 Plus** (Android 13).
Library version is `2.5.9`, stream `SRT` protocol.
I am using `GenericStream`, preview is `SurfaceView` and `OpenGlView` both have that error.
Depending on the time, after livestreaming for about 5 -> 20 minutes, OOM occurs.
Please help me.

Here is the log when the error occurs:

[Preview_SurfaceView.txt](https://github.com/user-attachments/files/19564524/Preview_SurfaceView.txt)

[Preview_OpenGlView.txt](https://github.com/user-attachments/files/19564526/Preview_OpenGlView.txt)

**Comment by pedroSG94** [comment]
Hello,

Are you using websocket?. I'm not using websocket and the report reported come from that:
```
                                                                         java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 3145624 free bytes and 3071KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
                                                                         	at okio.Buffer.readString(Buffer.kt:313)
                                                                         	at okio.Buffer.readUtf8(Buffer.kt:297)
                                                                         	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:245)
                                                                         	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:106)
                                                                         	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
                                                                         	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
                                                                         	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
                                                                         	at 
```
To discard errors with the library try stream using the app example with the same configuration using that device and try reproduce the error.

**Comment by pedroSG94** [comment]
@Rider02vn If you want report an error, avoid write in a death/close issue.
Open a new issue and link this issue if you think that it is relevant.

**Comment by Rider02vn** [comment]
Hello.
I will try to disable the socket and try again.
If the error still occurs, I will create a new issue.
Thanks.

> [@Rider02vn](https://github.com/Rider02vn) If you want report an error, avoid write in a death/close issue. Open a new issue and link this issue if you think that it is relevant.
