### ISSUE TITLE
API Version 19

### ISSUE THREAD

**Issue by xarionxrc** [pedroSG94/rtmp-rtsp-stream-client-java#143]
Hi!

I'm struggling to get the app to compile on API Version 19 (kitkat 4.4) do you  have any previous released that might be compatible with this API version?

Thanks 
Xarion

**Comment by pedroSG94** [comment]
If you clone this repository should work with api 16+.
What problen do you have? can you share me log error?

**Comment by xarionxrc** [comment]
After i go to Project Structure and change to API 19 I get the following (i'm using Android Sutdio 3.0.1):

Information:Gradle tasks [:app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:mockableAndroidJar, :encoder:generateDebugSources, :encoder:generateDebugAndroidTestSources, :encoder:mockableAndroidJar, :rtmp:generateDebugSources, :rtmp:generateDebugAndroidTestSources, :rtmp:mockableAndroidJar, :rtplibrary:generateDebugSources, :rtplibrary:generateDebugAndroidTestSources, :rtplibrary:mockableAndroidJar, :rtsp:generateDebugSources, :rtsp:generateDebugAndroidTestSources, :rtsp:mockableAndroidJar]
Error:resource android:style/TextAppearance.Material not found.
Error:resource android:style/TextAppearance.Material.Body1 not found.
Error:resource android:style/TextAppearance.Material.Body2 not found.
Error:resource android:style/TextAppearance.Material.Button not found.
Error:resource android:style/TextAppearance.Material.Caption not found.
Error:resource android:style/TextAppearance.Material.Display1 not found.
Error:resource android:style/TextAppearance.Material.Display2 not found.
Error:resource android:style/TextAppearance.Material.Display3 not found.
Error:resource android:style/TextAppearance.Material.Display4 not found.
Error:resource android:style/TextAppearance.Material.Headline not found.
Error:resource android:style/TextAppearance.Material.Inverse not found.
Error:resource android:style/TextAppearance.Material.Large not found.
Error:resource android:style/TextAppearance.Material.Large.Inverse not found.
Error:resource android:style/TextAppearance.Material.Widget.PopupMenu.Large not found.
Error:resource android:style/TextAppearance.Material.Widget.PopupMenu.Small not found.
Error:resource android:style/TextAppearance.Material.Medium not found.
Error:resource android:style/TextAppearance.Material.Medium.Inverse not found.
Error:resource android:style/TextAppearance.Material.Menu not found.
Error:resource android:style/TextAppearance.Material.SearchResult.Subtitle not found.
Error:resource android:style/TextAppearance.Material.SearchResult.Title not found.
Error:java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Information:BUILD FAILED in 1s
Information:23 errors
Information:0 warnings
Information:See complete output in console

**Comment by xarionxrc** [comment]
Sorry I figured out the problem, I was changing the compile SDK version instead of changing the target SDK version.

**Comment by pedroSG94** [comment]
You don't need change sdk version or target version to work with API 19.
