### ISSUE TITLE
Crashed application RTMP || IP camera

### ISSUE THREAD

**Issue by Rishat7c** [pedroSG94/rtmp-rtsp-stream-client-java#144]
Hi all.

I'm writing an application, I used your libraries to transfer video to the server by RTMP.

Has connected all as it is necessary in a gradle and the manifest.

There are MainActivities and SurfaceView, I wanted to start broadcasting video from SurfaceView directly to the server, as in your examples. But there was an error and the application closes as soon as it opens.

He swears on two lines:

```
        // create builder
        RtmpCamera1 rtmpCamera1 = new RtmpCamera1 (videostreamPreviewSf, (ConnectCheckerRtmp) this);
        // start stream
        rtmpCamera1.startStream ("rtmp: //adress...");
```

![crash](https://user-images.githubusercontent.com/23475575/37472884-2aa53d12-287e-11e8-90ea-d48234093902.png)

**Comment by pedroSG94** [comment]
The error is here:
```
(ConnectCheckerRtmp) this
```
You need implement ConnectCheckerRtmp in your class.

**Comment by Rishat7c** [comment]
@pedroSG94 
I have certain events in SurfaceView that are not related to the camera, but I want to transfer them to the server via RMTP.

RtmpCamera1 is not suitable, because she is for working with the camera

Advise me what to use?

**Comment by pedroSG94** [comment]
You can do a "hacky way". You can do stream with openglview and use AndroidViewFilter to send other view of course this will use camera but your view will overlay it so you can set same size to openglview than your surfaceview and overlay all camera content.
You can see OpenglRtmpActivity to know how to use openglview and androidviewfilter. If you need more info you can see this issue still closed:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/125

**Comment by Rishat7c** [comment]
@pedroSG94 
Sorry that I'm flooding this thread.
The matter is that in SurfaceView I have a translation from another camera and I need to transfer it to the server. OpenglRtmp - I understand it works with objects

**Comment by pedroSG94** [comment]
If your camera is device camera (You still have device camera in use so you can't open with the library) nothing to do by default. You need modify the library.
If camera is like a IP camera and you want re stream it to other server you can try use AndroidViewFilter like I said but if not work you can modify the project to stream using opengl to copy surface frames to surface from VideoEncoder class (like I do using OpenglView that copy camera frames in surfaceview surface and in VideoEncoder surface) or send h264 and aac bytebuffer directly to rtmp or rtsp modules.

Other way (maybe not useful for you is stream your device screen like in [DisplayRtmpActivity](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/displayexample/DisplayRtmpActivity.java) class

**Comment by Rishat7c** [comment]
@pedroSG94 
I decided to use RtmpDisplay - it's quite a convenient thing.

At the debugging stage, everything went fine until he started complaining about the microphone

![crash](https://user-images.githubusercontent.com/23475575/37508372-cf182442-2903-11e8-9c88-9cba7feac461.png)

**Comment by pedroSG94** [comment]
This look audio permission missed. Remember get permissions on runtime if you use API23+

**Comment by Rishat7c** [comment]
Settings gradle I have such
![gradle](https://user-images.githubusercontent.com/23475575/37509371-29a1b910-2908-11e8-99ff-1bb2f1b496ea.png)

conditions added
```
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                if (rtmpDisplay.prepareAudio() && rtmpDisplay.prepareVideo()) {
                    rtmpDisplay.startStream("rtmp://adress...", resultCode, data);
                }
            }
```

**Comment by pedroSG94** [comment]
No, no. You need write code to popup permission on runtime if your device use android 6.0+.
Also you need write audio permission in manifest. Please see MainActivity in this project to know how to do runtime permissions. If you don't understand the activity search in google a more easy example.

**Comment by Rishat7c** [comment]
@pedroSG94 
Thanks for answers!
At the moment, fixed this by turning on Microfan for the application via Settings

**Comment by Rishat7c** [comment]
I learned how to process h.264 video and display it on my screen from an IP camera.
By their own methods, I wanted to use your example for streaming to the server.

I want to achieve the same result as you RtmpCamera1.
but I just send this video to the server, like .startStream (url);
RtmpDisplay unfortunately did not come up to me

Can you suggest something? pls

**Comment by pedroSG94** [comment]
You need use SrsFlvMuxer class for it. See this class: [RtmpCamera1](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtmp/RtmpCamera1.java)
The idea is get h264 frames as ByteBuffer and MediaCodec.BufferInfo.
- ByteBuffer: This contain the frame of h264.
- MediaCodec.BufferInfo contain info about h264 frame If you have not it You can simply create one and override size and presentationTimeUs parameters (size is the size of h264 frame, presentationTimeUs is the time when frames was created. You have a example of how to override timeUs in VideoEncoder class).

Useful extra info:
- You can stream without audio so you can discard all related with audio in RtmpCamera2 class. 
- Set pps and sps is not necessary SrsFlvMuxer will get it for you if anyone is setted.

**Comment by Rishat7c** [comment]
@pedroSG94 
All of the above is already implemented, below is a snippet of code. It is called when the camera is connected

```
        // The callback for receiving the raw H264 video data for camera live view
        mReceivedVideoDataCallBack = new VideoFeeder.VideoDataCallback() {

            @Override
            public void onReceive(byte[] videoBuffer, int size) {
                //Log.d(TAG, "camera recv video data size: " + size);
                if (useSurface) {
                    VideoStreamDecoder.getInstance().parse(videoBuffer, size);
                } else if (mCodecManager != null) {
                    mCodecManager.sendDataToDecoder(videoBuffer, size);
                }

            }
        };
```
If I understand correctly, do I need to use the SrsFlvMuxer class functionality to transfer video over RTMP?

**Comment by pedroSG94** [comment]
Yes. You need use this method:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtmp/RtmpCamera1.java#L95
Remember start/stop srsFlvMuxer too:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtmp/RtmpCamera1.java#L69
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtmp/RtmpCamera1.java#L80

**Comment by Rishat7c** [comment]
@pedroSG94 
There is a separate class of VideoStream, where I found the time to implement it
`rtmp.getH264Data (buffer, bufferInfo);`
and there is a _MainActivity_, where I create a **surfaceView**, initialize the scope and run 
`.startStream ("rtmp: // ...");`

How to connect all this, so that everything will work now?)

**Comment by pedroSG94** [comment]
I don't understand you but if you can use sendVideo and start methods of SrsFlvMuxer class, stream should work.

**Comment by Rishat7c** [comment]
@pedroSG94 
I use the camera c documentation for dji and when the application tries to decode using the function _getH264Data_ (..., ...);
see line 640. ( https://pastebin.com/ha99q0DB )

Slightly changed the function getH264Data, removed all unnecessary there and left

```
   @override
   public void getH264Data (ByteBuffer h264Buffer, MediaCodec.BufferInfo info) {
     if (Build.VERSION.SDK_INT> = Build.VERSION_CODES.JELLY_BEAN_MR2) {
         mediaMuxer.writeSampleData (videoTrack, h264Buffer, info);
     }
     getH264DataRtp (h264Buffer, info);
   }
```

Now in my **SurfaceView** I get a black screen and nothing is sent to the server anyway :-(

**Comment by pedroSG94** [comment]
I have a similar case when I use file stream.

I recommend you first render a surface of surfaceview with decoder to test that you are doing it correctly. And then render a VideoEncoder surface like in  my decoder rendering and send this data to stream.

You can find surface to render with decoder in this line, try emulate this class to decode your frames:

https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/decoder/VideoDecoder.java#L69

If it works correctly you can now encode frames using surface of VideoEncoder class like in this method:

https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L342

**Comment by Rishat7c** [comment]
@pedroSG94 
Swears on VideoEncoder on line 309. ( https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L309 )

The code in MainActivity when initializing objects is as follows

```
         rtmpCamera1 = new RtmpCamera1 (videostreamPreview, this);

         if (Build.VERSION.SDK_INT> = Build.VERSION_CODES.LOLLIPOP) {
             rtmpCamera1.startStream ("rtmp: // adress ...");
         }

         if (Build.VERSION.SDK_INT> = 21) {
             videoEncoder = new VideoEncoder (rtmpCamera1);
             videoEncoder.getDataFromSurfaceAPI21 ();
             showToast ("Run in 21 SDK");
         }
```

![error](https://user-images.githubusercontent.com/23475575/37666945-cc4b0826-2c71-11e8-8a7e-96af17382977.png)

**Comment by pedroSG94** [comment]
This error look a o prepared VideoEncoder:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L69

**Comment by Rishat7c** [comment]
```
/*Change this to other method. Use your own configuration. 
    You don't need use MediaExtractor because you should know stream resolution, etc. 
    The idea is create your own MediaFormat to avoid nullpointer in prepareVideo method*/
    videoDecoder.initExtractor();
```

I do not fully understand what should be in videoDecoder.initExtractor ();

in videoDecoder initExtractor inherits String, and MediaFormat is a different data type.

I got confused about how to use initExtractor (
help ))

**Comment by pedroSG94** [comment]
You need create your own MediaFormat like in VideoEncoder class:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L101

**Comment by Rishat7c** [comment]
@pedroSG94 
I already had something similar from DJI
Used in the next class
Line 16 and 20

( https://pastebin.com/w30eNCiv )

**Comment by pedroSG94** [comment]
initExtractor should look like:

```java
  public boolean initExtractor() throws IOException {
    decoding = false;
    videoFormat = MediaFormat.createVideoFormat("video/avc", 1088, 1088); //use same resolution than videoEncoder class
    mime = videoFormat.getString(MediaFormat.KEY_MIME);
    return true;
  }
```

**Comment by Rishat7c** [comment]
@pedroSG94 
**First question**.
It seems that everything was fine, but now when you try to create a connection through `rrtmp.start ("rtmp: // ....");
`
@pedroSG94 
An error occurs that references _VideoDecoder.java_ 79 line

![error](https://user-images.githubusercontent.com/23475575/37716551-d85d8d78-2d2f-11e8-816a-a0a4ba76c01e.png)

**Second question**
The `sendH264Buffer(ByteBuffer byteBuffer)` method is analogue to decodeVideo ()?
If so, where and how should I call it? or he himself called when I go to the class where he is?

Displays as an inactive class
![screenshot](https://user-images.githubusercontent.com/23475575/37717568-da2ac7fe-2d31-11e8-9673-835be8bb0336.png)

**Comment by pedroSG94** [comment]
I see multiple errors in decoder. Also I can see that you not prepared VideoEncoder class as you can see with log:
```
VideoEncoder need be prepared, VideoEncoder not enabled
```
Error in decoder:
- You need call initExtractor, prepareVideo and then start decoder in this order.
- Start method in VideoDecoder should be changed You need use decodeVideo when you receive a frame from your camera not with a loop in a thread and send byte[] to this method to feed [this buffer](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/decoder/VideoDecoder.java#L118) and delete all related with mediaextractor in this method.

**Comment by Rishat7c** [comment]
I understand what you want to explain to me, but the fact is that my level of work with Media resources is not so big, so you are my hope :) Forgive me if I ask stupid questions

Instead of `decodeVideo()`, I should now use `sendH264Video(byte[] ByteBuffer)`.

i.e. _sendH264Video()_ should be almost the same as in the _DJIVideoDecodeStream_ class as a _decodeFrame()_

There is a difference between **decodeFrame()** and **sendH264Video ()** - this is what the first uses `DJIF library inputFrame = frameQueue.poll ();` and the like, and in the second case (in our) `VideoExtractor`

I really hope for your help.

**VideoDecoder.java** ( https://pastebin.com/L00CcZ2S )
**DJIVideoStreamDecoder.java** ( https://pastebin.com/jrSAG48Q )
**rRTMP.java** (this is ur old TestH264Stream) ( https://pastebin.com/DErXLUPS )

**Comment by pedroSG94** [comment]
Your DJIVideoStreamDecoder is decoding from a surface if you set it a not null surface so you don't need my VideoDecoder.
Also rRtmp class should be used outside of DJIVideoStreamDecoder.
So I think you have 2 ways to do it:
- Get yuv data from your IYuvDataListener interface and use this data like I do in RtmpCamera1base. To do it you need know yuv frame type (NV21, YV12, I420, NV12, etc).
- Set a valid surface using VideoEncoder surface and send it to DJIVideoStreamDecoder using "init(Context context, Surface surface)" method (This way is most efficient).

This is a little code that could work for you:
```java
public class TestH264Stream implements GetH264Data, ConnectCheckerRtmp {

  //private VideoDecoder videoDecoder;
  private DJIVideoStreamDecoder decoder;
  private VideoEncoder videoEncoder;
  private SrsFlvMuxer srsFlvMuxer;
  private int width, height;

  public TestH264Stream() {
    //videoDecoder = new VideoDecoder(this, this);
    decoder = DJIVideoStreamDecoder.getInstance();
    videoEncoder = new VideoEncoder(this);
    srsFlvMuxer = new SrsFlvMuxer(this);
  }

  public void prepare(int width, int height) {
    this.width = width;
    this.height = height;
    videoEncoder.prepareVideoEncoder(width, height, 30, 1200 * 1024, 0, false, 2,
        FormatVideoEncoder.SURFACE);
    /*Change this to other method. Use your own configuration.
    You don't need use MediaExtractor because you should know stream resolution, etc.
    The idea is create your own MediaFormat to avoid nullpointer in prepareVideo method*/

  }

  public void start(Context context, String url) {
    videoEncoder.start();
    decoder.init(context, videoEncoder.getInputSurface());
    srsFlvMuxer.setVideoResolution(width, height);
    srsFlvMuxer.start(url);
  }

  public void stop() {
    decoder.stop();
    videoEncoder.stop();
    srsFlvMuxer.stop();
  }

  //callback to get frame info. This should be called a time with the first encoded frame.
  @Override
  public void onSPSandPPS(ByteBuffer sps, ByteBuffer pps) {
    srsFlvMuxer.setSpsPPs(sps, pps);
  }

  //callback called when a frame is encoded.
  @Override
  public void getH264Data(ByteBuffer h264Buffer, MediaCodec.BufferInfo info) {
    srsFlvMuxer.sendVideo(h264Buffer, info);
  }

  @Override
  public void onVideoFormat(MediaFormat mediaFormat) {
    //useful is you want record. See some Base to know about it.
  }

  @Override
  public void onConnectionSuccessRtmp() {
    //do something
  }

  @Override
  public void onConnectionFailedRtmp(String reason) {
    //do something
  }

  @Override
  public void onDisconnectRtmp() {
    //do something
  }

  @Override
  public void onAuthErrorRtmp() {
    //do something
  }

  @Override
  public void onAuthSuccessRtmp() {
    //do something
  }
}
```
To do second way you need use rRtmp and replace VideoDecoder to DJIVideoStreamDecoder.

**Comment by Rishat7c** [comment]
Really working option.

There is a small problem when I initialize the connection to `MainActivity`. On my `SurfaceView `on the phone, the video from the camera stops showing, but broadcast to the server is sent. True in poor quality, green lines appear and ruffle

Line 200 - 202. Maybe I'm in the wrong place declaring?
( https://pastebin.com/L0FTCf8m )

p.s. video in media server
![video](https://user-images.githubusercontent.com/23475575/37831756-a4962ef8-2eb7-11e8-8961-441835d36502.png)

**Comment by pedroSG94** [comment]
Lose preview in surfaceview is normal because you replace surface of your surfaceview to surface of VideoEncoder that send to media server. 
If you want both as same time you need use opengl to copy surface frames like I do in OpenGlView (it is not easy if you don't know opengl).
And bad image result can has multiple reason but my first suspect is line 200 that set resolution of VideoEncoder(I think). This resolution should be original resolution of camera that you get not surfaceview size.
Other possibility could be some bad configuration on decoder or encoder(color format is a possibility) or maybe glitch on your devices mediacodec or opengl(it is frequent on custom rooms and rare but possible with officials rooms)

**Comment by Rishat7c** [comment]
Sent by mail, can look =)

**Comment by Stranger87123** [comment]
HI @Rishat7c 


You could provide how your solution is. The links to https://pastebin do not work anymore.

Thanks
