### ISSUE TITLE
What's the relationship between OpenGlView and AndroidViewFilterRender

### ISSUE THREAD

**Issue by b95505017** [pedroSG94/rtmp-rtsp-stream-client-java#147]
In the [sample](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L135), you set the whole content View into `AndroidViewFilterRender`, including `OpenGlView`, does it necessary & what's the best practice?

**Comment by pedroSG94** [comment]
No it is not necessary only an example. You can select any view in the XML in that line.
I only set main layout to show that you can send a layout to the stream with all content in it.

**Comment by b95505017** [comment]
What's the different behavior for a layout with/without `OpenGlView` set into `AndroidViewFilterRender`?

**Comment by pedroSG94** [comment]
No differences. Technically it is redundant because AndroidViewFilter only overlay view that you set in the streaming so overlay an Openglview has no sense.
