### ISSUE TITLE
How to avoid blink screen when success connect to rtmp?

### ISSUE THREAD

**Issue by b95505017** [pedroSG94/rtmp-rtsp-stream-client-java#149]
When rtmp connection success, my device screen will blink (flash black) suddenly, could it avoid possible?

**Comment by pedroSG94** [comment]
This is because camera is reopened because preview could be use a different resolution than stream.
So if you select same resolution in preview and stream this ca be avoid but I need implement it(It can be difficult).

**Comment by TapanM** [comment]
it is still happening. is there any solution for this?
