### ISSUE TITLE
Does Not Send Video. No Error In nginx-rtmp Log.

### ISSUE THREAD

**Issue by deeepakpatil** [pedroSG94/rtmp-rtsp-stream-client-java#15]
I tried both Custom and Default RTMP. Audio received but not video.
I am using Moto G5 (Lenovo) with Android 7.0.
No error observed in nginx-rtmp Log.

I tried all variants of "YUV420" video encoder formats, none of them worked.

**Comment by pedroSG94** [comment]
Ok, I need create that server for test.
Could you give me a instalation link?

**Comment by deeepakpatil** [comment]
Hi, following are few links;
A] https://www.vultr.com/docs/setup-nginx-rtmp-on-ubuntu-14-04
B] https://docs.peer5.com/guides/setting-up-hls-live-streaming-server-using-nginx/
C] https://gist.github.com/naiwungmusic/1037f38d03b79a8e0e1f

**Comment by deeepakpatil** [comment]
Hi,
I am using Dash (not HLS), following is my configuration;
rtmp {
  server {
    listen 1935; # Listen on standard RTMP port
    chunk_size 4000;

    application app {
     live on;
     push_reconnect 5s;
     interleave on;
     meta on;
     publish_notify on;
     wait_key on;
     wait_video on;
     dash on;
     record off;
     dash_playlist_length 15s;
     dash_fragment 3s;
     dash_path path/to/storage/directory; # Change it to yours
     deny play all;
    }
  }
}

Android app "BitStream" works fine with these settings.

**Comment by pedroSG94** [comment]
nginx-rtmp is working for me following this tutorial that you posted:
https://www.vultr.com/docs/setup-nginx-rtmp-on-ubuntu-14-04

I use Ubuntu 16.04 LTS

**Comment by pedroSG94** [comment]
I did a fix in rtmp video module that could solve it.
If not solve the problem i need know some things:
1. Buffer size from camera and from encoder. You can get it in RtmpBuilder in methods:

```
 @Override
  public void getH264Data(ByteBuffer h264Buffer, MediaCodec.BufferInfo info) {
    Log.i("Encoder Size = ", "" + h264Buffer.remaining());
    srsFlvMuxer.sendVideo(h264Buffer, info);
  }

@Override
  public void inputNv21Data(byte[] buffer) {
    Log.i("Camera Size = ", "" + buffer.length);
    videoEncoder.inputNv21Data(buffer);
  }
```

2. Logs in SrsFlvMuxer video flow for know if one method is not working properly.
Logs in this methods:
writeVideoSample
writeH264SpsPps
writeH264IpbFrame

If you need, in nginx-rtmp I'm testing with this config file:

```
#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       80;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   html;
            index  index.html index.htm;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        # proxy the PHP scripts to Apache listening on 127.0.0.1:80
        #
        #location ~ \.php$ {
        #    proxy_pass   http://127.0.0.1;
        #}

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #    root           html;
        #    fastcgi_pass   127.0.0.1:9000;
        #    fastcgi_index  index.php;
        #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
        #    include        fastcgi_params;
        #}

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #    deny  all;
        #}
    }


    # another virtual host using mix of IP-, name-, and port-based configuration
    #
    #server {
    #    listen       8000;
    #    listen       somename:8080;
    #    server_name  somename  alias  another.alias;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}


    # HTTPS server
    #
    #server {
    #    listen       443 ssl;
    #    server_name  localhost;

    #    ssl_certificate      cert.pem;
    #    ssl_certificate_key  cert.key;

    #    ssl_session_cache    shared:SSL:1m;
    #    ssl_session_timeout  5m;

    #    ssl_ciphers  HIGH:!aNULL:!MD5;
    #    ssl_prefer_server_ciphers  on;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}

}

rtmp {
    server {
            listen 1935;
            chunk_size 4096;

            application live {
                    live on;
                    record off;
                    exec ffmpeg -i rtmp://localhost/live/$name -threads 1 -c:v libx264 -profile:v baseline -b:v 350K -s 640x360 -f flv -c:a aac -ac 1 -strict -2 -b:a 56k rtmp://localhost/live360p/$name;
            }
            application live360p {
                    live on;
                    record off;
        }
    }
}
```

**Comment by deeepakpatil** [comment]
Hi,
I tried the latest commit, but no success. Video is not received.
Give me some time to pull out the logs.

**Comment by deeepakpatil** [comment]
Hi,
Found issue with stream.mpd file. Following parameters for video are not set in .mpd file.

    <AdaptationSet
        maxWidth="0"
        maxHeight="0"
        maxFrameRate="0">
      <Representation
          codecs="avc1.000001" // (Correct version ?)
          width="0"
          height="0"
          frameRate="0"
          bandwidth="0">

Please look into this.

**Comment by pedroSG94** [comment]
Where is that file?

**Comment by deeepakpatil** [comment]
Hi,

This is the file generated by RTMP server for playback.

I am **not using** ffmpeg to re-stream (following line) the captured stream by RTMP server;

exec ffmpeg -i rtmp://localhost/live/$name -threads 1 -c:v libx264 -profile:v baseline -b:v 350K -s 640x360 -f flv -c:a aac -ac 1 -strict -2 -b:a 56k rtmp://localhost/live360p/$name; # Not using this line in RTMP server

I tried other apps like, BitStream, Yasea (open source - please have a look at this https://github.com/begeekmyfriend/yasea) and they are working fine with my rtmp server settings, without re-streaming.

I am not sure whether re-streaming consumes additional server resources. If it does so, I would like to avoid re-streaming.

I am using DASH (not HLS).

**Comment by pedroSG94** [comment]
I created a branch with log for debug.
Could you get rtmpdebug branch and show me the logcat?

**Comment by deeepakpatil** [comment]
Hi,
I will do that.
Meanwhile I found that following function from SrsFlvMuxer.java (line no 101) is not called, hence not able to set video width & height.

  /**
   * set video resolution for publisher
   *
   * @param width width
   * @param height height
   */
  public void setVideoResolution(int width, int height) {
    if (publisher != null) {
      publisher.setVideoResolution(width, height);
    }
  }

**Comment by pedroSG94** [comment]
Added in brach rtmpdebug

**Comment by deeepakpatil** [comment]
Hi,

File is attached.
Changed my host, app and stream names.

[rtmp-debugger-log.txt](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/1133645/rtmp-debugger-log.txt)

**Comment by pedroSG94** [comment]
Aaaah ok. You are sending video but server don't accept the video packets.
So this should be a connection config error.
I did a update config in rtmp to let it like yasea.
Test last commit in rtmpdebug and let me know if work

**Comment by pedroSG94** [comment]
```
rtmp {
server {
listen 1935; # Listen on standard RTMP port
chunk_size 4000;

application app {
 live on;
 push_reconnect 5s;
 interleave on;
 meta on;
 publish_notify on;
 wait_key on;
 wait_video on;
 dash on;
 record off;
 dash_playlist_length 15s;
 dash_fragment 3s;
 dash_path /home/pedro/test; # Change it to yours
}
}
}
```

Working in last rtmpdebug commit. This is your config but i deleted: deny play all; for test with VLC

**Comment by deeepakpatil** [comment]
Hi,
Video not received / playable.
stream.mpd file has video width & height but missing maxFrameRate, frameRate, and bandwidth.
Audio bandwidth is zero, but received audio is very good.

Also .mpd file received from BitStream mentions codecs="avc1.428015"

[02.rtmp-debugger-log.txt](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/1133682/02.rtmp-debugger-log.txt)

`   <AdaptationSet
        id="1"
        segmentAlignment="true"
        maxWidth="320"
        maxHeight="240"
        maxFrameRate="0">
      <Representation
          id="stream_H264"
          mimeType="video/mp4"
          codecs="avc1.000001"
          width="320"
          height="240"
          frameRate="0"
          startWithSAP="1"
          bandwidth="0">`

**Comment by deeepakpatil** [comment]
Hi,
I guess VLC is able to play the video. I am using dash javascript player.
Could you please test it, I am attaching the files.
Added .txt extension to file, please remove it (was not allowed to upload .js and .html).

[index.html.txt](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/1133697/index.html.txt)
[dash.all.min.js.txt](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/1133698/dash.all.min.js.txt)

**Comment by pedroSG94** [comment]
stream.mpd is writed with sudo premissions and i think that i cant play it for that. 
That player don't reproduce anything

![captura de pantalla de 2017-07-09 13-49-02](https://user-images.githubusercontent.com/17556876/27993575-6bd06b44-64ad-11e7-9c7a-15f9c6407c9f.png)

**Comment by pedroSG94** [comment]
Oh Yasea set codecs. That could be the problem. I will fix it.

**Comment by deeepakpatil** [comment]
Please add following line at the top of nginx configuration file
user  www-data www-data;

Also change user and user-group of dash_path "/home/pedro/test" to www-data.

And put .html & .js files at the server root.

**Comment by pedroSG94** [comment]
codecs in .mpd file fixed.
Try with last commit.

**Comment by deeepakpatil** [comment]
Hi,
Successfully received both audio and video.
Please commit the changes to master repository.
We are good to close this issue after testing master repository code.
Thanks.

**Comment by pedroSG94** [comment]
I added to master in commit:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/af4ae9a06a38d4da39efc87e00a9b9cfc7fa27ca

Thank you for your colaboration!
