### ISSUE TITLE
native_window_api_connect  failed (already connected to another API?)

### ISSUE THREAD

**Issue by b95505017** [pedroSG94/rtmp-rtsp-stream-client-java#150]
Any idea how this could happened? It is a random issue that I can't always reproduce, right after I approved permissions and init `RtmpCamera2`.

```
E/libEGL: eglCreateWindowSurface: native_window_api_connect (win=0xb07bc808) failed (0xffffffea) (already connected to another API?)
    eglCreateWindowSurface:481 error 3003 (EGL_BAD_ALLOC)
    
    --------- beginning of crash
03-21 16:04:38.452 22979-24447/com.android.sample E/AndroidRuntime: FATAL EXCEPTION: Thread-11
    Process: com.ikala.shoplus.staging, PID: 22979
    java.lang.RuntimeException: eglCreateWindowSurface: EGL error: 0x3003
        at com.pedro.encoder.utils.gl.GlUtil.checkEglError(GlUtil.java:131)
        at com.pedro.encoder.input.gl.SurfaceManager.eglSetup(SurfaceManager.java:146)
        at com.pedro.encoder.input.gl.SurfaceManager.<init>(SurfaceManager.java:54)
        at com.pedro.rtplibrary.view.OpenGlView.run(OpenGlView.java:151)
        at java.lang.Thread.run(Thread.java:761)
```

**Comment by pedroSG94** [comment]
This look a bad release of Opengl. I will check it.
Do you approved permissions in the same activity that you have rtmpCamera2 or you check permissions in other activity?

**Comment by b95505017** [comment]
Same activity, I will make sure permissions all granted, then set `OpenGlView` to `VISIBLE`, so that holder callback will triggered in desired ordered.

**Comment by pedroSG94** [comment]
That set to Visible could be the problem. Try use OpenglView Visible always and startPreview when you get permissions. An invisible holder is not valid for opengl and this could cause your crash.
