### ISSUE TITLE
How To Stream Picture With Audio

### ISSUE THREAD

**Issue by pratheepchowdhary** [pedroSG94/rtmp-rtsp-stream-client-java#151]
Hello sir, How can stream Picture with mp3 audio or Stream  ImageView With Audio 
Which is Works in Background.

**Comment by pedroSG94** [comment]
For now the only way is create your own mp4 video with that picture with same size that your mp3 file and use rtmpFromFile stream class.
Remember you can stream audio and video with different files so you can do it:

Your best way is create a video with your picture, of 1min for example, and select loop mode only in video. To select loop mode only in video you need comment this line:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/FromFileBase.java#L244
Also you need comment all code in this else conditional:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/FromFileBase.java#L606
After that you can use filepath to this video and filepath to your mp3 in preaprevideo and prepareaudio methods.

**Comment by pratheepchowdhary** [comment]
Thank u
