### ISSUE TITLE
How to preivew IPC Camera with RTSP ?

### ISSUE THREAD

**Issue by wuzhenzhen** [pedroSG94/rtmp-rtsp-stream-client-java#156]
Hi,   if i use "https://github.com/pedroSG94/vlc-example-streamplayer"  is can preview IPC Camera success, but I use "Surface mode RTSP" found this error:

03-31 12:03:45.518 9713-9713/com.pedro.rtpstreamer I/MicrophoneManager: Microphone created, 44100hz, Stereo
03-31 12:03:45.518 9713-9713/com.pedro.rtpstreamer I/MicrophoneManager: Microphone created, 44100hz, Stereo
03-31 12:03:45.529 9713-10247/com.pedro.rtpstreamer I/OMXClient: Using client-side OMX mux.
03-31 12:03:45.565 9713-9713/com.pedro.rtpstreamer I/VideoEncoder: VideoEncoder OMX.allwinner.video.encoder.avc
03-31 12:03:45.568 9713-9713/com.pedro.rtpstreamer I/VideoEncoder: Color supported: 2135033992
03-31 12:03:45.568 9713-9713/com.pedro.rtpstreamer I/VideoEncoder: Color supported: 21
03-31 12:03:45.573 9713-10251/com.pedro.rtpstreamer I/OMXClient: Using client-side OMX mux.
03-31 12:03:45.584 9713-10251/com.pedro.rtpstreamer W/ACodec: do not know color format 0x7f000789 = 2130708361
03-31 12:03:45.585 9713-10251/com.pedro.rtpstreamer I/ACodec: setupVideoEncoder succeeded
03-31 12:03:45.585 9713-10251/com.pedro.rtpstreamer W/ACodec: do not know color format 0x7f000789 = 2130708361
03-31 12:03:45.710 9713-9713/com.pedro.rtpstreamer I/AudioEncoder: AudioEncoder started
03-31 12:03:45.781 9713-9713/com.pedro.rtpstreamer W/System.err: android.hardware.camera2.CameraAccessException: The system-wide limit for number of open cameras has been reached, and more camera devices cannot be opened until previous instances are closed.
03-31 12:03:45.781 9713-9713/com.pedro.rtpstreamer W/System.err:     at android.hardware.camera2.utils.CameraBinderDecorator.throwOnError(CameraBinderDecorator.java:125)
03-31 12:03:45.781 9713-9713/com.pedro.rtpstreamer W/System.err:     at android.hardware.camera2.utils.CameraBinderDecorator$CameraBinderDecoratorListener.onAfterInvocation(CameraBinderDecorator.java:73)
03-31 12:03:45.781 9713-9713/com.pedro.rtpstreamer W/System.err:     at android.hardware.camera2.utils.Decorator.invoke(Decorator.java:81)
03-31 12:03:45.781 9713-9713/com.pedro.rtpstreamer W/System.err:     at java.lang.reflect.Proxy.invoke(Proxy.java:393)
03-31 12:03:45.781 9713-9713/com.pedro.rtpstreamer W/System.err:     at $Proxy0.getCameraCharacteristics(Unknown Source)
03-31 12:03:45.781 9713-9713/com.pedro.rtpstreamer W/System.err:     at android.hardware.camera2.CameraManager.getOrCreateDeviceIdListLocked(CameraManager.java:635)
03-31 12:03:45.781 9713-9713/com.pedro.rtpstreamer W/System.err:     at android.hardware.camera2.CameraManager.getCameraCharacteristics(CameraManager.java:222)
03-31 12:03:45.782 9713-9713/com.pedro.rtpstreamer W/System.err:     at com.pedro.encoder.input.video.Camera2ApiManager.openCameraFacing(Camera2ApiManager.java:238)
03-31 12:03:45.782 9713-9713/com.pedro.rtpstreamer W/System.err:     at com.pedro.encoder.input.video.Camera2ApiManager.openCameraBack(Camera2ApiManager.java:182)
03-31 12:03:45.782 9713-9713/com.pedro.rtpstreamer W/System.err:     at com.pedro.encoder.input.video.Camera2ApiManager.openLastCamera(Camera2ApiManager.java:191)
03-31 12:03:45.782 9713-9713/com.pedro.rtpstreamer W/System.err:     at com.pedro.rtplibrary.base.Camera2Base.startStream(Camera2Base.java:403)
03-31 12:03:45.782 9713-9713/com.pedro.rtpstreamer W/System.err:     at com.pedro.rtpstreamer.surfacemodeexample.SurfaceModeRtspActivity.onClick(SurfaceModeRtspActivity.java:122)
03-31 12:03:45.782 9713-9713/com.pedro.rtpstreamer W/System.err:     at android.view.View.performClick(View.java:5204)
03-31 12:03:45.782 9713-9713/com.pedro.rtpstreamer W/System.err:     at android.view.View$PerformClick.run(View.java:21153)
03-31 12:03:45.782 9713-9713/com.pedro.rtpstreamer W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
03-31 12:03:45.782 9713-9713/com.pedro.rtpstreamer W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
03-31 12:03:45.782 9713-9713/com.pedro.rtpstreamer W/System.err:     at android.os.Looper.loop(Looper.java:148)
03-31 12:03:45.782 9713-9713/com.pedro.rtpstreamer W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
03-31 12:03:45.782 9713-9713/com.pedro.rtpstreamer W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
03-31 12:03:45.782 9713-9713/com.pedro.rtpstreamer W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:742)
03-31 12:03:45.782 9713-9713/com.pedro.rtpstreamer W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:632)
03-31 12:03:45.784 9713-9713/com.pedro.rtpstreamer I/MicrophoneManager: Microphone started

**Comment by pedroSG94** [comment]
First of all:
```
android.hardware.camera2.CameraAccessException: The system-wide limit for number of open cameras has been reached, and more camera devices cannot be opened until previous instances are closed.
```
This means that you still have camera opened, you can't use BaseCamera1 or BaseCamera2 with camera in use.

Also this library can be used to stream your device camera, video files or your device screen. If you want stream other thing, you need modify this library.
So many people ask me about restream a IP camera. I have plan to create a project example to stream IP camera using VLC and this library.
