### ISSUE TITLE
How to make a streaming video MIRRORing while using the front camera?

### ISSUE THREAD

**Issue by tytung** [pedroSG94/rtmp-rtsp-stream-client-java#161]
This is a great streaming lib.
While using the **back/rear camera** of the phone, the text on the preview screen and streaming video is correct.

However, while using the **front camera** of the phone, the **text** on the preview screen and streaming video is "**mirroring**" and "**unreadable**".

How can I make the video mirroring so that the text is readable?
Thank you.

**Comment by pedroSG94** [comment]
What view are you using? OpenglView, surfaceview, etc

**Comment by tytung** [comment]
OpenglView and camera2

**Comment by tytung** [comment]
Thanks for your hint about the view type.

Well, it seems that OpenglView causes the streaming mirroring issue.
I tried your example app where "surface mode RTMP" and "Texture mode RTMP" are working fine. (No mirroring)

However, I would like to use FilterRender, so OpenglView is required. How can I do?
Thank you.

**Comment by pedroSG94** [comment]
I'm fixing it.

**Comment by pedroSG94** [comment]
This should be fixed now: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/48a37caf0075dd0a5344170adf3c7be89745dd4a

**Comment by tytung** [comment]
Thank you very much.
I will download source code including your new commit, and try it later.

BTW, are both preview and stream not mirror?
Or only stream is not mirror.

I hope that preview is mirror and stream is NOT mirror.

**Comment by pedroSG94** [comment]
Preview is not mirror. It should be mirror and stream not mirror? IN this case I need  add a change. I will go to surfaceview mode and emulate it.

**Comment by tytung** [comment]
As far as I know, in most apps, the preview of the front camera is mirror (i.e., text can not be read easily), just like that we stand in front of a real mirror.
And the streaming video is NOT mirror, so audience can watch the streaming video and read the text inside the video more easily.

The surfaceview mode is the same as I said above.

**Comment by pedroSG94** [comment]
Yes, In my default camera app the result is like you say. 
I will change it(It is more difficult than all mirror or all not mirror, so I will need some time).

**Comment by pedroSG94** [comment]
For this case I have 2 solutions:

1 - More or less easy to implement: Preview mirror or not mirror to select by user and by default no mirror, but with filters mirror or not mirror like with camera preview (If you select preview mirror and you send an image this image will be mirror on preview).

2 Difficult to implement because required change all off screen render logic: Camera preview mirror and filters not mirror on preview.

Of course both solution the stream result is always not mirror.

What do you think is the best solution?

**Comment by tytung** [comment]
I think the 1st solution is acceptable. 
And it is a great idea that users can choose to mirror or not

**Comment by pedroSG94** [comment]
Finally I did a mix of 1 and 2 options. The change is added to other branch because the solution could have bad performance and I will try optimize it: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/5222d797efc12684fe1c3f9542d7240f73eb7fbe
The final solution is:
Camera preview not mirror by default but you can select camera preview mirror and filters not mirror on preview.

To test you only need uncomment this line: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/previewmirrortest/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L85

**Comment by tytung** [comment]
Nice work. You make your library more useful.
Thank you very much.

**Comment by b95505017** [comment]
@pedroSG94 I think that the preview of the front camera is not mirror with OpenglView in 1.3.8 is very weird.

**Comment by pedroSG94** [comment]
Yes, I know. front camera mirror is not added to master branch for performance reason. I'm doing other implementation for it.
If you want it you should use this branch:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/previewmirrortest

**Comment by b95505017** [comment]
Currently all I want is WYSIWYG, which is mirror preview-> mirror streaming. My workaround is override the `setCameraFace` in OpenglView to do nothing.

**Comment by pedroSG94** [comment]
If you want preview mirrored and stream too you can change this line:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/gl/render/CameraRender.java#L108
To:
```java
GLES20.glUniform1f(uIsFrontCameraHandle, 0f);
```

**Comment by b95505017** [comment]
Thanks for your hint! But I want to use the packed library instead of modifying source code.

**Comment by pedroSG94** [comment]
This is added to master branch. To activate you should use this line:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/927b93ab601351206db265ebfcebd022ee0b773a#diff-4fd3487439274831534bc29c97ace2c3R97

**Comment by TapanM** [comment]
is it available in the latest version(1.5.9)?

**Comment by OleksandrAndro** [comment]
> 
> 
> If you want preview mirrored and stream too you can change this line:
> https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/gl/render/CameraRender.java#L108
> To:
> 
> ```java
> GLES20.glUniform1f(uIsFrontCameraHandle, 0f);
> ```

Hello, Pedro!

**Comment by pedroSG94** [comment]
Set this line to true:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/res/layout/activity_open_gl.xml#L15

**Comment by OleksandrAndro** [comment]
I using BackgroundExamle and I tried it solution, it working fine when when the Activity is in foregraund, but when I move Activity in background - image on the server mirroring again

**Comment by pedroSG94** [comment]
Sorry for late response, you can add this line here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/view/OffScreenGlThread.java#L55
```java
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/view/OffScreenGlThread.java#L55
```

**Comment by OleksandrAndro** [comment]
I tried such solution, but no result

**Comment by pedroSG94** [comment]
I tested my solution and this is working. I only replaced this line:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/view/OffScreenGlThread.java#L55
To:
```java
textureManager.setCameraFlip(true, false);
```
Also remember add this line to view in xml layout:
```xml
app:isFlipHorizontal="true"
```
About bitrate this is only a default value for 640x480 resolution when you use prepareVideo without arguments

**Comment by OleksandrAndro** [comment]
I connectштп to 2 cameras at the same time, the first cam I opened such a BACK camera, and the second - such a front camera. Therefore, if I replace the code with the one you recommended, my front camera does not flip when I move the activity to the background, but the back camera flips.
And if I don't replace code - I get the opposite situation.
Thank you

**Comment by pedroSG94** [comment]
2 cameras at same time? I don't understand your case. This library without modifications only support 1 camera. Are you using [SurfaceFilter](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/gl/render/filters/object/SurfaceFilterRender.java) to set second camera?

**Comment by OleksandrAndro** [comment]
No, I not using SurfaceFilter. I using bagroundexample and duplicate RtpService class for second camera. In layout - I created another OpenGlSurfaceView.

**Comment by pedroSG94** [comment]
Ok, I can understand now. I think you need parameterize this value to only flip one of this services.
You can do it:
- Add a custom replaceView to cameraBase like this:
```java
  public void replaceView(Context context, boolean flip) {
    isBackground = true;
    replaceGlInterface(new OffScreenGlThread(context, flip));
  }
```
- Addnew constructor to OffScreenGlThread class and create a variable flip for it:
```java
  private boolean flip = false;

  public OffScreenGlThread(Context context, boolean flip) {
    this.flip = flip;
    this.context = context;
  }
```
- Set this flip variable to setCameraFlip:
```java
    textureManager.setCameraFlip(flip, false);
```
Now, you can select if you want flip camera when you go to background so you can do it only in a service without effects in the other service (remember create 2 services with same code but with differents replaceView method)

**Comment by OleksandrAndro** [comment]
Thank you, I think I fix it, I modified the OffScreenGlThread constructor and pass another boolean variable there as a sign of the front camera
