### ISSUE TITLE
Orientation does not work on some devices

### ISSUE THREAD

**Issue by liccowee** [pedroSG94/rtmp-rtsp-stream-client-java#167]
I used Google Pixel 2 to run the RtspCamera2 with surface view. The preview looks good on my phone, but when I view it on other phone, the streamed video was rotated 90 anti clockwise.
rtspCamera2.prepareVideo(640, 480, 30, 1200 * 1024, true, 90)

But when I use the same code test on Samsung S8 phone and it just work fine. Any idea what is happening? Could it be the encoder in Google Pixel 2 does not support hardwareRotation? How can I fix the problem?

**Comment by liccowee** [comment]
Also, How can I preview my OpenGL/SurfaceView in correct aspect ratio? For example I have a SurfaceView with full width and (height/2), so how can I have a preview of camera with the correct aspect ratio render on this surface view? Right now it is stretched to the max width which is not right.

**Comment by pedroSG94** [comment]
First question:
Yes, your device don't support hardware rotation, the solution is use openglview and set hardwarerotation to false.
Second question:
To keep aspect ratio a method was added to openglview and lightopenglview. Uncomment this line and test it:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L95

**Comment by liccowee** [comment]
@pedroSG94 thank you for the quick reply!
