### ISSUE TITLE
Capture Image by RtmpDisplay

### ISSUE THREAD

**Issue by anoop-sharma** [pedroSG94/rtmp-rtsp-stream-client-java#168]
Is it possible to capture image / screenshot using RtmpDisplay? I am using RtmpDisplay to stream entire screen. I know it is using Mediaprojection but is it possible to get single image.

Can you please suggest something? Thanks

**Comment by pedroSG94** [comment]
This library, for now, can't take photos. You can try take a screenshot:
https://stackoverflow.com/questions/2661536/how-to-programmatically-take-a-screenshot-in-android

**Comment by anoop-sharma** [comment]
Thanks for the update.

**Comment by anoop-sharma** [comment]
So I have tried following to make the screenshot happen. But it's kind of crashing after few minutes. May be because I am using two virtual display. Don't know

Added following lines into
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/DisplayBase.java

`public MediaProjectionManager getMediaProjectionManager() {
    return mediaProjectionManager;
  }

  public MediaProjection getMediaProjection() {
    return mediaProjection;
  }`

Then in mainactivity where we are doing rtmppublishing

`private static String STORE_DIRECTORY;
    private static int IMAGES_PRODUCED;
    private static final String SCREENCAP_NAME = "screencap";
    private static final int VIRTUAL_DISPLAY_FLAGS = DisplayManager.VIRTUAL_DISPLAY_FLAG_OWN_CONTENT_ONLY | DisplayManager.VIRTUAL_DISPLAY_FLAG_PUBLIC;
    private static MediaProjection sMediaProjection;

    private ImageReader mImageReader;
    private Handler mHandler;
    private VirtualDisplay mVirtualDisplay;
    private int mWidth;
    private int mHeight;

// start capture handling thread
        new Thread() {
            @Override
            public void run() {
                Looper.prepare();
                mHandler = new Handler();
                Looper.loop();
            }
        }.start();

@Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        if (requestCode == REQUEST_CODE) {
            if (resultCode == Activity.RESULT_OK) {
                if (rtmpDisplay.prepareAudio() && rtmpDisplay.prepareVideo(640, 480, 25, 800 * 1024, 0, 320)) {
                    rtmpDisplay.startStream(RTMPURL, resultCode, data);
                    sMediaProjection = rtmpDisplay.getMediaProjection();
                } else {
                    AppConstants.showToast(getApplicationContext(), "Error preparing stream, This device cant do it");
                }

                if (sMediaProjection != null) {
                    File externalFilesDir = getExternalFilesDir(null);
                    if (externalFilesDir != null) {
                        STORE_DIRECTORY = externalFilesDir.getAbsolutePath() + "/images/";
                        File storeDirectory = new File(STORE_DIRECTORY);
                        if (!storeDirectory.exists()) {
                            boolean success = storeDirectory.mkdirs();
                            if (!success) {
                                AppConstants.debugLog("failed to create file storage directory.");
                                return;
                            }
                        }
                    } else {
                        AppConstants.debugLog("failed to create file storage directory, getExternalFilesDir is null.");
                        return;
                    }
                    createVirtualDisplay();
                    // register media projection stop callback
                    sMediaProjection.registerCallback(new MediaProjectionStopCallback(), mHandler);
                }
            } else {
                AppConstants.showToast(getApplicationContext(), "No permissions available");
            }
        }
    }

/****************************************** Factoring Virtual Display creation ****************/
    private void createVirtualDisplay() {
        // display metrics
        DisplayMetrics metrics = getResources().getDisplayMetrics();
        int mDensity = metrics.densityDpi;
        Display mDisplay = getWindowManager().getDefaultDisplay();

        // get width and height
        Point size = new Point();
        mDisplay.getSize(size);
        mWidth = size.x;
        mHeight = size.y;

        // start capture reader
        mImageReader = ImageReader.newInstance(mWidth, mHeight, PixelFormat.RGBA_8888, 2);
        mVirtualDisplay = sMediaProjection.createVirtualDisplay(SCREENCAP_NAME, mWidth, mHeight, mDensity, VIRTUAL_DISPLAY_FLAGS, mImageReader.getSurface(), null, mHandler);
        mImageReader.setOnImageAvailableListener(new ImageAvailableListener(), mHandler);
    }

private class ImageAvailableListener implements ImageReader.OnImageAvailableListener {
        @Override
        public void onImageAvailable(ImageReader reader) {
            Image image = null;
            FileOutputStream fos = null;
            Bitmap bitmap = null;

            try {
                image = reader.acquireLatestImage();
                if (image != null && IMAGES_PRODUCED < IMAGE_UPLOAD_MAX) {
                    Image.Plane[] planes = image.getPlanes();
                    ByteBuffer buffer = planes[0].getBuffer();
                    int pixelStride = planes[0].getPixelStride();
                    int rowStride = planes[0].getRowStride();
                    int rowPadding = rowStride - pixelStride * mWidth;

                    // create bitmap
                    bitmap = Bitmap.createBitmap(mWidth + rowPadding / pixelStride, mHeight, Bitmap.Config.ARGB_8888);
                    bitmap.copyPixelsFromBuffer(buffer);

                    // write bitmap to a file
                    File externalFilesDir = getExternalFilesDir(null);
                    if (externalFilesDir != null) {
                        if (lineupActive) {
                            STORE_DIRECTORY = externalFilesDir.getAbsolutePath() + "/lineupimages/";
                        } else {
                            STORE_DIRECTORY = externalFilesDir.getAbsolutePath() + "/screenshots/";
                        }
                    }
                    String fPath = STORE_DIRECTORY + "/chromelivescreen_" + IMAGES_PRODUCED + ".png";
                    fos = new FileOutputStream(fPath);
                    bitmap.compress(Bitmap.CompressFormat.JPEG, 100, fos);

                    IMAGES_PRODUCED++;
                    AppConstants.debugLog("captured image: " + IMAGES_PRODUCED);
                    if (new File(fPath).exists() && !lineupActive) {
                        uploadScreenShot(fPath);
                    }
                }

            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                if (fos != null) {
                    try {
                        fos.close();
                    } catch (IOException ioe) {
                        ioe.printStackTrace();
                    }
                }

                if (bitmap != null) {
                    bitmap.recycle();
                }

                if (image != null) {
                    image.close();
                }
            }
        }
    }

private class MediaProjectionStopCallback extends MediaProjection.Callback {
        @Override
        public void onStop() {
            AppConstants.debugLog("stopping projection.");
            mHandler.post(new Runnable() {
                @Override
                public void run() {
                    if (mVirtualDisplay != null) mVirtualDisplay.release();
                    if (mImageReader != null) mImageReader.setOnImageAvailableListener(null, null);
                    sMediaProjection.unregisterCallback(MediaProjectionStopCallback.this);
                }
            });
        }
    }`

**Comment by anoop-sharma** [comment]
Hey what do you think? Is it the right approach?

**Comment by anoop-sharma** [comment]
Yes I did but it didn't worked as I am using UVCCamera library and it uses surfaceview to show result. That's why need to opt for this method.

**Comment by pedroSG94** [comment]
Ah ok, I'm looking a solution for it and implement take photo method in library. Anyway you can modify this library to work with UVCCamera library using opengl and then you can take photo with glreadpixel from opengl.

**Comment by anoop-sharma** [comment]
OK thanks will try it.
