### ISSUE TITLE
Audio issue

### ISSUE THREAD

**Issue by ansariatif** [pedroSG94/rtmp-rtsp-stream-client-java#169]
Hi,
There is artifact and noise in audio when use rtmp.

**Comment by pedroSG94** [comment]
Try with prepare audio like:
```java
prepareAudio(256*1024, 44100, true, false, false)
```

**Comment by ansariatif** [comment]
same issue some artifact and noise exist

**Comment by pedroSG94** [comment]
Try enable noise suppressor and/or echo canceler:
```java
prepareAudio(256*1024, 44100, true, true/*echo canceler*/, true/*noise suppressor*/)
```
If the problem persist try modify microphone class parameters(I recommend you test with secondary microphone for example, also make sure that default camera app can record a video with good audio quality to discard hardware problems):
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/audio/MicrophoneManager.java
