### ISSUE TITLE
how can I detect if bandwidth is low and change video stream accordingly?

### ISSUE THREAD

**Issue by RKuanysh** [pedroSG94/rtmp-rtsp-stream-client-java#171]
Depending on internet connection I would like to adjust the video quality on the fly.
Can someone help me do that?
I see that I can change bitrate on the fly, but there is no way to detect if connection is handling current stream or not.

**Comment by pedroSG94** [comment]
I only know this method:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/122

**Comment by RKuanysh** [comment]
@pedroSG94 Thank you, Pedro.

**Comment by pedroSG94** [comment]
Feature developed:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/172
