### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by Loren1994** [pedroSG94/rtmp-rtsp-stream-client-java#174]
Will the server only use wowza?
is easyDarwin supported?
Can url format be like this?( rtsp://192.168.1.1:1935/live/pedroSG94 )
Is this format supported?(  rtsp://{ip}:{port}/{id} )

thanks

**Comment by pedroSG94** [comment]
1 - I don't understand the question.
2- Yes, it is supported: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Media-servers-tested
3 - Yes, url is correct.
4 - I think it is like question 3. I suppose that id is like: live/pedroSG94, if not, show me a example.

**Comment by Loren1994** [comment]
thank you :-)
