### ISSUE TITLE
How to stream video with existing camera object?

### ISSUE THREAD

**Issue by Liverpudlian88** [pedroSG94/rtmp-rtsp-stream-client-java#175]
Thank you for making a good library. 

I want to stream the video using Rtsp, but i still want to open my camera for other function (motion detection). 
Current object RtspCamera1 will start the camera by default after init, it is not suitable for me. 
In this case, do you have any advise for me?

**Comment by pedroSG94** [comment]
I only can recommend you modify https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java if you use camera1 apii of Android or https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java if you use other way.
I don't know how work your camera so advise you is difficult.
