### ISSUE TITLE
I want to use startRecord anytime, not after startStream

### ISSUE THREAD

**Issue by Loren1994** [pedroSG94/rtmp-rtsp-stream-client-java#179]
hello,

I want to use startRecord anytime, not after startStream, can you help me ?🙏

**Comment by pedroSG94** [comment]
I need develop it. I will add it like feature and try develop this week. Anyway call prepareVideo and prepareAudio methods will be necessary.

**Comment by Loren1994** [comment]
I think so. Thank you for your help.

**Comment by pedroSG94** [comment]
It is under develop. No stable for now:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/recordimprovement

**Comment by Loren1994** [comment]
Thanks for your help

**Comment by Loren1994** [comment]
I think this library will be perfect !
I got a crash exception at branch recordimprovement.
step1. startRecord()
step2.startStream()
crash...
the reason may be encoder

**Comment by pedroSG94** [comment]
If you are using buffer to buffer mode (surfaceview or textureview and camera1) I know that bug and now is solved. I did a merge to master branch now after test all possibilities and work for me.
If you find other bug let me know it and show me logcat if you can.

**Comment by Loren1994** [comment]
I use EasyDarwin as RTSP Server . this server not work.
 I remove "+ "Content-Length: 0\r\n"" (at RtspClient.java line 390) after read EasyDarwin source code,
 and server worked.
Is "Content-Length: 0" necessary for other server?  if not, i think it can be removed.

**Comment by pedroSG94** [comment]
I tested it few months ago and worked. I will test without that line and remove it if work with other servers

**Comment by Loren1994** [comment]
I got a IndexOutOfBoundsException after startStream() a few minutes,

java.lang.IndexOutOfBoundsException: offset=13, count=-3432, length=1300
        at java.nio.Buffer.checkGetBounds(Buffer.java:173)
        at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:107)
        at com.pedro.rtsp.rtp.packets.H264Packet.createAndSendPacket(H264Packet.java:62)
        at com.pedro.rtsp.rtsp.RtspClient.sendVideo(RtspClient.java:521)
        at com.pedro.rtplibrary.rtsp.RtspCamera1.getH264DataRtp(RtspCamera1.java:104)
        at com.pedro.rtplibrary.base.Camera1Base.getH264Data(Camera1Base.java:868)
        at com.pedro.encoder.video.VideoEncoder.getDataFromEncoder(VideoEncoder.java:461)
        at com.pedro.encoder.video.VideoEncoder.access$900(VideoEncoder.java:31)
        at com.pedro.encoder.video.VideoEncoder$1.run(VideoEncoder.java:245)
        at java.lang.Thread.run(Thread.java:841)

**Comment by pedroSG94** [comment]
Please write this log in line:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtsp/src/main/java/com/pedro/rtsp/rtp/packets/H264Packet.java#L54
```java
Log.e("Pedro", "length: " + naluLength + ", size: " + bufferInfo.size + ", position: " + byteBuffer.position());
```
This look some error in the logic anyway I think you can catch it and will work but I want know the error reason to fix it properly.

**Comment by Loren1994** [comment]
I write this log in the morning:
`Log.d("loren","byteBuffer.position="+byteBuffer.position()+" - count="+ cont +" - length="+length);`
result:
byteBuffer.position=12668 - count=-5193 - length=-5193

I think add " byteBuffer.clear(); " in the first line of the function createAndSendPacket.but I am not sure, beacuse of I can't reproduce it now.

**Comment by pedroSG94** [comment]
Where did you put that log? (line)

**Comment by Loren1994** [comment]
the line number is different with your lib because I add some code.
I write a log above 
"byteBuffer.get(buffer, RtpConstants.RTP_HEADER_LENGTH + 1, length);//line69 in my project"

**Comment by pedroSG94** [comment]
No problem. Try with my last commit:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/c42a362e0cbf9fd1e84bbc144bb87acf91401674
According with java documentation this should be fixed:
https://docs.oracle.com/javase/7/docs/api/java/nio/Buffer.html#rewind()

**Comment by Loren1994** [comment]
ok.👌
