### ISSUE TITLE
Question: How to manage dynamic stream preview aspect ratio in opengl view 

### ISSUE THREAD

**Issue by rkoshti** [pedroSG94/rtmp-rtsp-stream-client-java#180]
@pedroSG94 

How can i manage runtime maintain streaming preview aspect ratio while changing the device orientation ? camera preview is working fine but its not reflecting in the streaming preview. Can you help me for fix this ?

I have used opengl view.

For ex. My camere preview is landscape and its displaying like this 

![2018-05-30_1744](https://user-images.githubusercontent.com/19707208/40721038-ff88c6c8-6435-11e8-88fd-243b84608678.png)

you can see the screenshot in landscape orientation it has to be change to full width.

Thanks

**Comment by pedroSG94** [comment]
Do you want change stream resolution on fly when you change orientation?
Generally it is not supported by player so it is not developed.
If you select resolution to 720x1280 (for example) you can't change this resolution to 1280x720 if you don't restart encoder.
I'm not sure if I understand you but send me screenshot of app and player side if not.
720p stream is working now? (I need know it to close last issue or not, if it work you can close it too and If you can, let me know how did you solve issue for future issues)

**Comment by rkoshti** [comment]
Yes you are correct I want to change resolutions on the fly because when I am rotating the device orientation in player it's not getting any effect it is displaying portrait streams. Can you help me to fix this ?



My team is doing more testing on adaptive bitrate and other resolutions right now it's not happening anymore with 720p but it happens in other resolution I will give you more updates and will update the issue after our testing gets completed. Thanks for your help

**Comment by rkoshti** [comment]
Is there any way to lock the orientation ?

For ex if I am starting the streaming in portrait orientation then player has to start streaming in the portrait mode after that if I change the device orientation to landscape no need to change streaming preview to portrait .

Basically what I want  if I start streaming in portrait then it has to be strated display as a portrait in player and if I start with landscape then it should start display landscape preview .

Is it possible ? Is there any method or function available to achieve this?

**Comment by pedroSG94** [comment]
You can set orientation to 90 if you are in portrait and 0 if you are in landscape.
With this the stream result 720p is:
portrait -> 720x1280
landscape -> 1280x720

If you rotate device your resolution stream is the same if you already started stream. So, what is my recommendation and normal use with android apps camera?. When you start stream block orientation and unblock when you stop stream(It is like when you record a video with your camera app).

**Comment by rkoshti** [comment]
@pedroSG94 

Something like this ?

`if (getResources().getConfiguration().orientation == Configuration.ORIENTATION_PORTRAIT) {

            //portrait
            if (rtmpCamera1.prepareAudio() && rtmpCamera1.prepareVideo(720, 1280, 30, 1500 * 1024, false, 2, 90)) {
              button.setText(R.string.stop_button);

              rtmpCamera1.startStream(rtmpUrl);
            } else {
              Toast.makeText(this, "Error preparing stream, This device cant do it",
                      Toast.LENGTH_SHORT).show();
            }


          }else {
          // landscape
            if (rtmpCamera1.prepareAudio() && rtmpCamera1.prepareVideo(1280, 720, 30, 1500 * 1024, false, 2, 0)) {
              button.setText(R.string.stop_button);

              rtmpCamera1.startStream(rtmpUrl);
            } else {
              Toast.makeText(this, "Error preparing stream, This device cant do it",
                      Toast.LENGTH_SHORT).show();
            }

          }`


Its throwing the error 

com.pedro.rtpstreamer E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.pedro.rtpstreamer, PID: 32243
    com.pedro.encoder.input.video.CameraOpenException: This camera resolution cant be opened
        at com.pedro.encoder.input.video.Camera1ApiManager.start(Camera1ApiManager.java:108)
        at com.pedro.rtplibrary.base.Camera1Base.startStream(Camera1Base.java:414)
        at com.pedro.rtpstreamer.openglexample.OpenGlRtmpActivity.onClick(OpenGlRtmpActivity.java:368)
        at android.view.View.performClick(View.java:5678)
        at android.view.View$PerformClick.run(View.java:22667)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6293)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1065)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:926)


In portrait i have set 720 width and 1280 height and might be this was a problem .

If i set width = 1280 and height = 720 then it is displaying the landscape image (full image)

![2018-05-31_1033](https://user-images.githubusercontent.com/19707208/40762319-1f431634-64be-11e8-8b74-ae61020148c7.png)

**Comment by pedroSG94** [comment]
try with:
```java
       int orientation = (getResources().getConfiguration().orientation == 1) ? 90 : 0;
        if (rtmpCamera1.prepareAudio() && rtmpCamera1.prepareVideo(1280, 720, 30, 1500 * 1024, false, 2, orientation)) {
          button.setText(R.string.stop_button);

          rtmpCamera1.startStream(rtmpUrl);
        } else {
          Toast.makeText(this, "Error preparing stream, This device cant do it",
                  Toast.LENGTH_SHORT).show();
        }
```

**Comment by rkoshti** [comment]
@pedroSG94 Tried this Output is same

**Portrait Output**
![portrait](https://user-images.githubusercontent.com/19707208/40768387-cc528ac6-64d2-11e8-9dc0-c1add2f4045e.png)

**Landscape Output**

![landscape](https://user-images.githubusercontent.com/19707208/40768418-e37f04f4-64d2-11e8-9f75-73a9ef775556.png)

What is wrong ?

**Comment by pedroSG94** [comment]
Clone my project and go to:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L316
Replace that line to:
```java
int orientation = (getResources().getConfiguration().orientation == 1) ? 90 : 0;
              if (rtmpCamera1.prepareAudio() && rtmpCamera1.prepareVideo(1280, 720, 30, 1500 * 1024,
                  false, 2, orientation)) {
```
Now go to manifest and delete this line:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/AndroidManifest.xml#L95

It worked for me(Remember that if you rotate device while stream the stream is stopped). 
If the problem persist try stream to youtube or facebook to discard server problems. Also you can stream with OBS or ffmpeg to 1280x720(like if you stream with my library in landscape) and 720x1280(like if you stream with my library in portrait) to discard problems with your server.

**Comment by rkoshti** [comment]
Already cloned your project and also i am testing in the demo project. Also already removed screen orientation = portrait from manifest but that didn't work for me . I don't think its server problem as it works fine with the ios streamer.  let me test more

**Comment by pedroSG94** [comment]
Work with IOS streamer but no with ffmpeg or OBS(it is based on ffmpeg) :(. 
Are you using AMF3 or AMF0 in server side?
Your streamer IOS is:
https://github.com/shogo4405/HaishinKit.swift
Right?

**Comment by rkoshti** [comment]
@pedroSG94 

**Your streamer IOS is:
https://github.com/shogo4405/HaishinKit.swift** - yes this one

**Are you using AMF3 or AMF0 in server side?** - i am finding that

**Comment by rkoshti** [comment]
@pedroSG94 i am using AMF0 from server side

**Comment by pedroSG94** [comment]
I did a test with your IOS library and same result that with my library:
I only download the project example and replace this url:
https://github.com/shogo4405/HaishinKit.swift/blob/master/Examples/iOS/Preference.swift

**Comment by pedroSG94** [comment]
I haven't a public server only local server. I use this library:
https://github.com/iizukanao/node-rtsp-rtmp-server
Also I have nginx server:
https://github.com/arut/nginx-rtmp-module

**Comment by rkoshti** [comment]
@pedroSG94  Thanks can you share screenshots of your stream output in both orientation?

**Comment by rkoshti** [comment]
@pedroSG94 - I can see the strange behaviour in player (in all the player that i have tried)i have set player mode to "Auto" and In normal mode its displaying landscape view and in full screen mode its displaying portrait view ... Strange

**NORMAL VIEW** 

![normal_mode_2](https://user-images.githubusercontent.com/19707208/40822071-00fea4d4-6588-11e8-8098-7e8d991be70f.png)

After clicking on the full screen button in the player 
![full_screen_indicator](https://user-images.githubusercontent.com/19707208/40822115-4ba32e2e-6588-11e8-89f9-d6c2e4aa8775.png)

*FULL SCREEN*

![full_screen_3](https://user-images.githubusercontent.com/19707208/40822132-65ced014-6588-11e8-8f71-030e8aaea594.png)

**Comment by pedroSG94** [comment]
I think your problem is url stream no player. Why your url resize my stream to 1280x720 if I set other resolutoin?

**Comment by rkoshti** [comment]
I think it is something like this may be?

https://www.wowza.com/community/questions/45166/the-video-that-mobile-phone-vertical-capture-uploa.html

**Comment by pedroSG94** [comment]
I don't know. If you are using wowza I can confirm you that wowza server is working with my library in RTMP and RTSP with and without authentication
