### ISSUE TITLE
Could not find library error when using npm project rn-live

### ISSUE THREAD

**Issue by sagar1garg** [pedroSG94/rtmp-rtsp-stream-client-java#182]
@pedroSG94 
Could not find com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:1.3.8.
           Required by:
               screen:rn-live:unspecified

**Comment by pedroSG94** [comment]
Are you using rn-live library?
https://github.com/devhuyhq/RNLive
I tested my jitpack repository version 1.3.8 and work. This look some error in your gradle or error in rn-live gradle. Also I Tested that gradle version 1.2.0 work.
Anyway rn-live actually is using 1.2.0 version not 1.3.8:
https://github.com/devhuyhq/RNLive/blob/master/android/app/build.gradle

**Comment by pedroSG94** [comment]
But version 1.3.8 is working I did a new project in android studio and it work if you add dependencies like in my readme.
I never use that wrapper of my library and I never use react so I don't know how help you.

**Comment by sagar1garg** [comment]
Got it to work finally but it doesn't seem to be recording. Also how do I connect it to DaCast or Wowza?

**Comment by pedroSG94** [comment]
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/master/app/src/main/java/com/pedro/rtpstreamer/displayexample

**Comment by sagar1garg** [comment]
@pedroSG94 could not identify which file is responsible for screen recording. Could you point me? Also the  native android screen recording feature does not capture the screen with full clarity and in 16:9 or 16:10 mode. Can that be overcome?

**Comment by pedroSG94** [comment]
This class do screen recording:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/DisplayBase.java
I don't understand the second question :(

**Comment by sagar1garg** [comment]
@pedroSG94 I tried the DisplayExample but the app crashes as soon as I click the start stream button and it establishes a connection with the rtmp server. Logs:

I/MicrophoneManager: Microphone created, 44100hz, Stereo
I/MicrophoneManager: Microphone created, 44100hz, Stereo
I/MediaCodec: name=audio/mp4a-latm isType=true encoder=true
I/MediaCodec: (0xa5e48580) init name(audio/mp4a-latm) isType(1) encoder(1)
I/OMXClient: MuxOMX ctor
I/MediaCodec: (0xa5e48580) Component Allocated (OMX.google.aac.encoder)
I/MediaCodec: (0xa5e48580) configure surface(0x0) crypto(0x0) flags(1)
D/MediaCodec: (0xa5e48580) configure format: AMessage(what = 0x00000000) = {
                    int32_t aac-profile = 2
                    int32_t max-input-size = 0
                    int32_t bitrate = 131072
                    string mime = "audio/mp4a-latm"
                    int32_t channel-count = 2
                    int32_t sample-rate = 44100
                  }
W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
I/VideoEncoder: VideoEncoder OMX.qcom.video.encoder.avc
W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
I/VideoEncoder: Color supported: 2141391876
I/VideoEncoder: Color supported: 2130708361
I/VideoEncoder: Color supported: 2135033992
I/VideoEncoder: Color supported: 21
I/MediaCodec: name=OMX.qcom.video.encoder.avc isType=false encoder=false
I/MediaCodec: (0xa366b340) init name(OMX.qcom.video.encoder.avc) isType(0) encoder(0)
I/OMXClient: MuxOMX ctor
I/MediaCodec: (0xa366b340) Component Allocated (OMX.qcom.video.encoder.avc)
I/VideoEncoder: Prepare video info: SURFACE, 640x480
I/MediaCodec: (0xa366b340) configure surface(0x0) crypto(0x0) flags(1)
D/MediaCodec: (0xa366b340) configure format: AMessage(what = 0x00000000) = {
                    string mime = "video/avc"
                    int32_t frame-rate = 30
                    int32_t rotation-degrees = 0
                    int32_t color-format = 2130708361
                    int32_t height = 480
                    int32_t width = 640
                    int32_t max-input-size = 0
                    int32_t bitrate = 1228800
                    int32_t i-frame-interval = 2
                  }
E/ACodec: [OMX.qcom.video.encoder.avc] storeMetaDataInBuffers (output) failed w/ err -1010
I/ExtendedACodec: setupVideoEncoder()
I/ACodec: [OMX.qcom.video.encoder.avc] setupVideoEncoder mime(video/avc) colorFormat(7f000789)
W/ACodec: do not know color format 0x7fa30c04 = 2141391876
W/ACodec: do not know color format 0x7f000789 = 2130708361
I/ACodec: width height(640x480) stride(640) sliceHeight(480)
I/ACodec: bitrate(1228800) framerate(30.000000) compressionFormat(7)
I/ACodec: setupAVCEncoderParameters with [profile: Baseline] [level: Level1]
I/ACodec: [OMX.qcom.video.encoder.avc] cannot encode HDR static metadata. Ignoring.
I/ACodec: setupVideoEncoder succeeded
I/ExtendedACodec: [OMX.qcom.video.encoder.avc] configure, AMessage : AMessage(what = 'conf', target = 4) = {
                    string mime = "video/avc"
                    int32_t frame-rate = 30
                    int32_t rotation-degrees = 0
                    int32_t color-format = 2130708361
                    int32_t height = 480
                    int32_t width = 640
                    int32_t max-input-size = 0
                    int32_t bitrate = 1228800
                    int32_t i-frame-interval = 2
                    int32_t encoder = 1
                  }
W/ACodec: do not know color format 0x7f000789 = 2130708361
I/MediaCodec: (0xa366b340) start
I/MediaCodec: (0xa366b340) input buffers allocated
I/MediaCodec: (0xa366b340) numBuffers (9)
I/MediaCodec: (0xa366b340) output buffers allocated
I/MediaCodec: (0xa366b340) numBuffers (4)
I/MediaCodec: (0xa5e48580) start
I/MediaCodec: (0xa5e48580) input buffers allocated
I/MediaCodec: (0xa5e48580) numBuffers (4)
I/MediaCodec: (0xa5e48580) output buffers allocated
I/MediaCodec: (0xa5e48580) numBuffers (4)
I/AudioEncoder: AudioEncoder started
D/MediaCodec: (0xa5e48580) [OMX.google.aac.encoder] output format changed to: AMessage(what = 0x00000000) = {
                    int32_t bitrate = 131072
                    int32_t max-bitrate = 131072
                    string mime = "audio/mp4a-latm"
                    int32_t channel-count = 2
                    int32_t sample-rate = 44100
                    int32_t aac-profile = 2
                  }
I/MicrophoneManager: Microphone started
I/MediaCodec: (0xa366b340) setParameters
I/SrsFlvMuxer: worker: connecting to RTMP server by url=rtmp://192.168.1.112:8001/stream?sign=1503458721-80c1d1ad2e0c2ab63eebb50eed64201a
D/RtmpConnection: connect() called. Host: 192.168.1.112, port: 8001, appName: stream?sign=1503458721-80c1d1ad2e0c2ab63eebb50eed64201a, publishPath: null
W/System.err: java.io.FileNotFoundException: /storage/emulated/0/Movies: open failed: EISDIR (Is a directory)
W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:455)
W/System.err:     at java.io.RandomAccessFile.<init>(RandomAccessFile.java:247)
W/System.err:     at java.io.RandomAccessFile.<init>(RandomAccessFile.java:128)
W/System.err:     at android.media.MediaMuxer.<init>(MediaMuxer.java:145)
W/System.err:     at com.pedro.rtplibrary.base.DisplayBase.startRecord(DisplayBase.java:160)
W/System.err:     at com.enwitra.enwitra.DisplayRtmpActivity.onActivityResult(DisplayRtmpActivity.java:141)
W/System.err:     at android.app.Activity.dispatchActivityResult(Activity.java:6931)
W/System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:4090)
W/System.err:     at android.app.ActivityThread.handleSendResult(ActivityThread.java:4137)
W/System.err:     at android.app.ActivityThread.-wrap20(ActivityThread.java)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1529)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err:     at android.os.Looper.loop(Looper.java:154)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6123)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
W/System.err: Caused by: android.system.ErrnoException: open failed: EISDIR (Is a directory)
W/System.err:     at libcore.io.Posix.open(Native Method)
W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:187)
W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:441)
W/System.err: 	... 16 more
D/ACodec: dataspace changed to 0x10c40000 (R:2(Limited), P:3(BT601_6_625), M:3(BT601_6), T:3(SMPTE170M)) (R:2(Limited), S:4(BT601_525), T:3(SMPTE_170M))
D/RtmpConnection: connect(): socket connection established, doing handhake...
D/Handshake: writeC0
D/Handshake: writeC1
D/Handshake: writeC1(): Calculating digest offset
D/Handshake: writeC1(): (real value of) digestOffset: 622
D/Handshake: writeC1(): recalculated digestOffset: 1398
D/Handshake: writeC1(): digestOffsetBytes: 0070FFFF
D/Handshake: partBeforeDigest(): size: 1398
D/Handshake: writeC1(): Writing timestamp and Flash Player version
D/Handshake: partAfterDigest(): size: 106
D/Handshake: copying digest offset bytes in partBeforeDigest
D/Handshake: writeC1(): Calculating digest
D/Handshake: writeC1(): writing C1 packet
D/Handshake: readS0
D/MediaCodec: (0xa366b340) [OMX.qcom.video.encoder.avc] output format changed to: AMessage(what = 0x00000000) = {
                    int32_t bitrate = 1228800
                    int32_t max-bitrate = 1228800
                    string mime = "video/avc"
                    int32_t width = 640
                    int32_t height = 480
                    int32_t color-range = 2
                    int32_t color-standard = 4
                    int32_t color-transfer = 3
                  }
D/Handshake: readS1
I/SrsFlvMuxer: flv: h264 sps/pps sent, sps=17B, pps=4B
D/Handshake: readS1(): S1 total bytes read OK
D/Handshake: writeC2
D/Handshake: readS2
D/Handshake: readS2(): S2 total bytes read OK
D/RtmpConnection: connect(): handshake done
D/RtmpConnection: starting main rx handler loop
D/RtmpConnection: rtmpConnect(): Building 'connect' invoke packet
D/RtmpConnection: wrote packet: RTMP Command (command: connect, transaction ID: 1), size: 317
D/RtmpConnection: handleRxPacketLoop(): Setting acknowledgement window size: 5000000
D/RtmpConnection: handleRxPacketLoop(): Send acknowledgement window size: 5000000
D/RtmpConnection: wrote packet: RTMP Window Acknowledgment Size, size: 4
D/RtmpDecoder: readPacket(): Setting chunk size to: 60000
I/RtmpConnection: handleRxInvoke: Got result for invoked method: connect
D/RtmpConnection: createStream(): Sending releaseStream command...
E/AndroidRuntime: FATAL EXCEPTION: Thread-6
                  Process: com.enwitra.enwitra, PID: 28805
                  java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes(java.lang.String)' on a null object reference
                      at com.github.faucamp.simplertmp.amf.AmfString.writeTo(AmfString.java:59)
                      at com.github.faucamp.simplertmp.packets.VariableBodyRtmpPacket.writeVariableData(VariableBodyRtmpPacket.java:71)
                      at com.github.faucamp.simplertmp.packets.Command.writeBody(Command.java:77)
                      at com.github.faucamp.simplertmp.packets.RtmpPacket.writeTo(RtmpPacket.java:36)
                      at com.github.faucamp.simplertmp.io.RtmpConnection.sendRtmpPacket(RtmpConnection.java:494)
                      at com.github.faucamp.simplertmp.io.RtmpConnection.createStream(RtmpConnection.java:299)
                      at com.github.faucamp.simplertmp.io.RtmpConnection.publish(RtmpConnection.java:283)
                      at com.github.faucamp.simplertmp.DefaultRtmpPublisher.publish(DefaultRtmpPublisher.java:26)
                      at net.ossrs.rtmp.SrsFlvMuxer.connect(SrsFlvMuxer.java:124)
                      at net.ossrs.rtmp.SrsFlvMuxer.access$000(SrsFlvMuxer.java:45)
                      at net.ossrs.rtmp.SrsFlvMuxer$1.run(SrsFlvMuxer.java:159)
                      at java.lang.Thread.run(Thread.java:761)
I/SrsFlvMuxer: frame discarded

**Comment by pedroSG94** [comment]
I need device model and API version. Also I need know if you are using emulator.

**Comment by sagar1garg** [comment]
I am using Moto G5 Plus running Android 7.0 and not emulator. 
API 26

**Comment by pedroSG94** [comment]
Can you show me your endpoint example?
This look some error with url parse or wrong url in this class:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L53

**Comment by sagar1garg** [comment]
Endpoint: rtmp://192.168.1.112:8001/stream?sign=1503458721-80c1d1ad2e0c2ab63eebb50eed64201a
I am using Node Media Server https://github.com/iizukanao/node-rtsp-rtmp-server . This is the endpoint they have given in the documentation

**Comment by pedroSG94** [comment]
wrong url anyway I have a bug in the regular expression. I will fix it.
You don't have a streamname example correct url:
rtmp://ip:port/app/streamname

**Comment by sagar1garg** [comment]
I have been using the same url to connect with their android example apps and it works every time. Also I can see on the debug screen of the server that the server connection is successful before the app crashes

**Comment by pedroSG94** [comment]
Where is their android example?
The connection is fine but the problem is that you haven't a stream name so when you try send packet with streamname the match is null (it is my problem and I'm fixing it, the library should send you bad url) in your case the stream url should be something like this(If you don't modify any configuration of the server):
```
 rtmp://192.168.1.112:1935/live/mystream
```
Where live is the application name and mystreamname is your streamname that you missed

**Comment by sagar1garg** [comment]
Android example- https://github.com/NodeMedia/QLive-Android

**Comment by sagar1garg** [comment]
Changing the url worked! Thanks. One more thing - Can I use the record option before the stream is initiated? I know there was a similar question earlier but in that thread you had mentioned that you had made the change but was unstable. However in the code it still says to use the record method post startstream method

**Comment by pedroSG94** [comment]
For now, only if you use camera1 or camera2 builder.

**Comment by sagar1garg** [comment]
@pedroSG94 
A few issues:
1. On running the display screen example I found that screen cast is always running and I am unable to shut it down. Further I keep getting display notification as 'Notification Received' at the bottom of my screen regularly.
2. On using cloud based rtmp streaming (I used Nginx), the player had a 15-20sec lag and the video was not smooth either. I researched nginx forums and concluded that it was a client side issue.

Feature request:
1. When using the front camera streaming is there a way that I can see the feed preview on the screen in a small square/rectangular frame which I can move and place anywhere on the screen?

**Comment by pedroSG94** [comment]
1. Example issue. I will solve it.
2-3. If you are using display mode try use more dpi to get more quality and delay depend of your bandwidth. Also I test delay with nginx on local net and the result is (with VLC desktop like player that by default have 1s buffer):
- 1s delay with camera examples (it mean practically real time on local net).
- 7s delay with display example.
So I think the problem is mediaprojection api that get about 5 or 6s delay. Obviously both test with 480p and 1200 * 1024 video bitrate(The only different in both test is the way that you render surface used to stream, the first example with camera and opengl, second example directly mediaprojection).

Feature:
It don't look a stream feature it is a feature related with app interface. Maybe you can do it in a widget.

**Comment by sagar1garg** [comment]
@pedroSG94 
In the Display activity code I can see there is a provision to save the file to phone's Movies directory under screen capture but it doesn't. How do I enable it?

**Comment by pedroSG94** [comment]
I don't understand your question. Can you link me the line code?

**Comment by sagar1garg** [comment]
I meant is it possible to record and stream the screen at the same time?

**Comment by pedroSG94** [comment]
Yes, you can. Same usage like if you use other builder but you only can record while stream. I will add it today or tomorrow in the example.

**Comment by sagar1garg** [comment]
@pedroSG94 Thanks for the above help!

I have been trying to covert the DisplayRtmpExample Activity to a Service but am getting this error:
Attempt to invoke virtual method 'android.hardware.display.VirtualDisplay android.media.projection.MediaProjection.createVirtualDisplay(java.lang.String, int, int, int, int, android.view.Surface, android.hardware.display.VirtualDisplay$Callback, android.os.Handler)' on a null object reference 
at this line:  rtmpDisplay.startStream(etUrl, resultCode, data );

On further inspection I found that the exception is caused by:
mediaProjection.createVirtualDisplay("Stream Display", videoEncoder.getWidth(),
        videoEncoder.getHeight(), dpi, 0, videoEncoder.getInputSurface(), null, null);

Since I cannot use the "startActivityForResult(rtmpDisplay.sendIntent(), REQUEST_CODE);" method in a Service could you suggest a way to make it work?

**Comment by pedroSG94** [comment]
You can't do it in a service. try use rtmpDiaplay object like a singleton in the activity.

**Comment by sagar1garg** [comment]
@pedroSG94 
It seems like the streaming automatically stops after 30-40 secs. Below is the console output:
D/RtmpConnection: wrote packet: RTMP Audio, size: 382
D/RtmpConnection: wrote packet: RTMP Audio, size: 383
E/RtmpConnection: Caught SocketException while reading/decoding packet, shutting down: Connection reset
E/RtmpConnection: Caught SocketException while reading/decoding packet, shutting down: Connection reset
E/RtmpConnection: Caught SocketException while reading/decoding packet, shutting down: Connection reset

**Comment by pedroSG94** [comment]
I need more info to reproduce it.
Are you in the stream activity when you see that error or you change activity?
If you never change activity, did you get that error?

**Comment by sagar1garg** [comment]
I make the streaming activity (app) move to background while streaming is
running.

**Comment by pedroSG94** [comment]
I did a test with the new commit in my app and worked (I tested 4mins). Try with my last commit.
