### ISSUE TITLE
What is rtsp url for streaming in wifi LAN

### ISSUE THREAD

**Issue by Liverpudlian88** [pedroSG94/rtmp-rtsp-stream-client-java#183]
Thank you for making the useful library. 

I'm now developing an application that stream rtsp camera preview between 2 Android devices in same wifi network. Unfortunately it doesn't work yet. 
Can you tell me about the exact rtsp url "rtsp://yourEndPoint" in this case? 
Because i want to create the rtsp server on Server device, then Client device will play the preview using MediaPlayer with server url (for ex: rtsp://192.168.1.15:8080/live/camera). 
Is it correct to input Server ip for url, or it must be Client ip? 

Thank you.

**Comment by pedroSG94** [comment]
I'm not sure how use my library in your case.
You want create a RTSP server in your device and stream to it then you want get that stream from other device. Am I right?
In this case the url format is like:
rtsp://myserverdeviceip:serverport/appname/streamname
example: rtsp://192.168.1.1:1935/live/pedroSG94

**Comment by Liverpudlian88** [comment]
Sorry, my use case is that:
2 smartphones connect on a same wifi network, Server application will stream its camera preview to Client application. 
I would like to create new Rtsp server on Server application, then Client application will decode the rtsp url using MediaPlayer. 
In this case, can i use your library for Server application (in create new Rtsp on Server device 192.168.1.xx then stream camera preview to that server)? 
Is your library only use for Rtsp client?

**Comment by pedroSG94** [comment]
Yes, my library is only client. Similar to use OBS.
Example:
device1 --- with my library stream to --> mediaserver --- send stream from device1 to ---> device2 that use mediaplayer

**Comment by Liverpudlian88** [comment]
Thank you for your answer. 
I'm clear now, it needs to setup a PC server to use. 
Since my application requires to stream directly without PC server so i will try another OSS. 

Thank you very much.
