### ISSUE TITLE
camera preview is too dark 

### ISSUE THREAD

**Issue by MohamedElshafey** [pedroSG94/rtmp-rtsp-stream-client-java#184]
int TextureModeRtspActivity , i tried your example on my infinix hot2(android v 6.0) device and once i start streaming the preview change to be very dark and it keeps focusing in a mad way , when i use the same TextureModeRtspActivity  with RtspCamera1 it working smoothly but with the same dark preview,
 by the way i tried it with other device and its working correctly, what should i do ?

**Comment by pedroSG94** [comment]
I can't reproduce it but maybe this post could help you:
https://stackoverflow.com/questions/31330098/android-surfaceview-preview-too-dark
You should use camera1 and modify that parameters in this class:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java
If you need use camera2 you can try modify this class:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java
If you can find a solution let me know it to fix. Also make sure that your default camera app work fine to discard device problems.

**Comment by MohamedElshafey** [comment]
I found a solution

`int[] range = adaptFpsRange(fps, parameters.getSupportedPreviewFpsRange());`

range numbers are 30000 , 30000

When i change the Fps Range to 5000,30000 it works correctly 

i choose 5000,30000 according to `parameters.getSupportedPreviewFpsRange()` because this is the only not equal range.

so i added this to start() method in Camera1ApiManager 
`parameters.setPreviewFpsRange(5000, 30000);`

Thanks for help

**Comment by pedroSG94** [comment]
Thank you for share. 
If the problem is fps in parameters you can configure it in prepareVideo method to get similar result if you set 5fps you will get that result.
That look a concrete bug in a device so I will create a page in the wiki to help future users with similar bug :)

**Comment by MohamedElshafey** [comment]
yes 5fps did it right , thank you for the fast response 👍 , but i want to make sure this will not effect the quality of the stream of another high quality device.

**Comment by beerpcc** [comment]
Remove `parameters.setPreviewFpsRange(range[0], range[1])` in `Camera1ApiManager.java` can fix this issue for me.

**Comment by fahimfahadleon** [comment]
package com.horoftech.probashi_live;

import android.app.Activity;
import android.content.Context;
import android.media.MediaRecorder;
import android.util.Log;
import android.view.SurfaceHolder;
import android.view.SurfaceView;
import android.view.View;
import android.widget.FrameLayout;
import android.widget.Toast;
import com.pedro.encoder.input.sources.audio.AudioSource;
import android.util.DisplayMetrics;
import android.view.WindowManager;

import com.pedro.encoder.input.sources.video.Camera2Source;
import com.pedro.extrasources.CameraXSource;
import com.pedro.encoder.input.sources.video.Camera1Source;
import com.pedro.encoder.input.sources.video.VideoSource;

import androidx.annotation.NonNull;
import com.pedro.encoder.input.sources.audio.MicrophoneSource;

import com.pedro.common.ConnectChecker;
import com.pedro.library.generic.GenericStream;
import com.pedro.library.util.BitrateAdapter;
import io.flutter.plugin.platform.PlatformView;

public class GenericStreamView extends FrameLayout implements PlatformView, ConnectChecker {

    private final SurfaceView surfaceView;
    private final GenericStream genericStream;
    private final BitrateAdapter bitrateAdapter;
    final int bitrate = 6000*1000;


    Context context;

    public GenericStreamView(@NonNull Context context) {
        super(context);
        this.context = context;
        surfaceView = new SurfaceView(context);
        addView(surfaceView);


        genericStream = new GenericStream(context, this);




        bitrateAdapter = new BitrateAdapter(bitrat -> genericStream.setVideoBitrateOnFly(bitrat));
        bitrateAdapter.setMaxBitrate(bitrate);

        surfaceView.getHolder().addCallback(new SurfaceHolder.Callback() {
            @Override
            public void surfaceCreated(SurfaceHolder holder) {
                if (!genericStream.isOnPreview()) {
                    genericStream.startPreview(surfaceView);
                }
            }

            @Override
            public void surfaceChanged(SurfaceHolder holder, int format, int width, int height) {

               Log.e("width",String.valueOf(width));
               Log.e("height",String.valueOf(height));

                genericStream.getGlInterface().setPreviewResolution(width, height);
            }

            @Override
            public void surfaceDestroyed(SurfaceHolder holder) {
                if (genericStream.isOnPreview()) {
                    genericStream.stopPreview();
                }
            }
        });

        DisplayMetrics metrics = new DisplayMetrics();
        ((Activity)context).getWindowManager().getDefaultDisplay().getRealMetrics(metrics);
        int width = metrics.widthPixels;
        int height = metrics.heightPixels;

        Log.e("width",String.valueOf(width));
        Log.e("height",String.valueOf(height));

        boolean prepared =  genericStream.prepareVideo(1920,1080,bitrate,60,2,90)
                && genericStream.prepareAudio(
                44100,     // sampleRate
                true,      // isStereo
                128000,    // bitrate
                true,     // echoCanceler
                true      // noiseSuppressor
        );
        if (!prepared) {
            Log.e("error","could not prepare video or audio");
            return;
        }



    }

    public void startStream(String url) {
        Toast.makeText(context, "start stream called", Toast.LENGTH_SHORT).show();
        genericStream.startStream(url);
    }

    public void stopStream() {
        genericStream.stopStream();
    }

    public void switchCamera() {
        VideoSource videoSource = genericStream.getVideoSource();
        if (videoSource instanceof Camera2Source) {
            ((Camera2Source) videoSource).switchCamera();
        }
        else if (videoSource instanceof Camera1Source) {
            ((Camera1Source) videoSource).switchCamera();
        } else  if (videoSource instanceof CameraXSource) {
            ((CameraXSource) videoSource).switchCamera();
        }
        Toast.makeText(context, "switch camera called", Toast.LENGTH_SHORT).show();
    }

    public void release() {
        genericStream.release();
    }

    public void mute() {
        AudioSource source = genericStream.getAudioSource();
        if(source instanceof MicrophoneSource){
            ((MicrophoneSource) source).mute();
        }
        Toast.makeText(context, "microphone mute called", Toast.LENGTH_SHORT).show();
    }

    public void unmute() {
        AudioSource source = genericStream.getAudioSource();
        if(source instanceof MicrophoneSource){
            ((MicrophoneSource) source).unMute();
        }
        Toast.makeText(context, "microphone unmute called", Toast.LENGTH_SHORT).show();
    }

    // ConnectChecker events
    @Override public void onConnectionStarted(String s) {}
    @Override public void onConnectionSuccess() {}
    @Override public void onConnectionFailed(@NonNull String s) {
        Log.e("error",s);
    }
    @Override public void onNewBitrate(long bitrate) {
        bitrateAdapter.adaptBitrate(bitrate, genericStream.getStreamClient().hasCongestion());
    }
    @Override public void onDisconnect() {}
    @Override public void onAuthError() {}
    @Override public void onAuthSuccess() {}

    @NonNull
    @Override
    public View getView() {
        return this; // This FrameLayout that holds SurfaceView
    }

    @Override
    public void dispose() {
        genericStream.release(); // Clean up stream resources
    }
}

anyone knows why my preview and stream is dark? can anyone help?
