### ISSUE TITLE
frame discarded

### ISSUE THREAD

**Issue by Loren1994** [pedroSG94/rtmp-rtsp-stream-client-java#189]
VideoEncoder.java
@Override
  public void inputYUVData(Frame frame) {
    synchronized (sync) {
      if (running) {
        try {
          queue.add(frame);
        } catch (IllegalStateException e) {
          Log.i(TAG, "frame discarded");
        }
      }
    }
  }
Log "frame discarded" often appear,  What could be the cause?  network? device?
thanks.

**Comment by pedroSG94** [comment]
If the log is from VideoEncoder class normally the reason is that device can't do color conversion more fast than camera provide frames (Your device do it too slow).
The best solution is use Openglview or LightOpenglview that use surface mode. With it you skip color conversion.

**Comment by Loren1994** [comment]
thank you very much!
