### ISSUE TITLE
How to open camera preview in onCreate instead of start Streaming

### ISSUE THREAD

**Issue by Kishore1224** [pedroSG94/rtmp-rtsp-stream-client-java#19]
Hi

I need to know how to open camera preview while activity opens instead of start streaming..

can some one help on this

Thanks

**Comment by pedroSG94** [comment]
Go to your builder and create a method for open camera before start other things. For example you could do a method like:

```
public void startCamera() {
  cameraManager.start();
}
```
And delete cameraManager.start(); in start method.
Remember you need wait surface inflate (use a SurfaceHolder.Callback to know it) or the app will crash.

**Comment by lzlcss** [comment]
im not really know about endpoint, would u please give an example? And all i want is open camera and put camera stream to PC, so PC can use VLC to connect with rtsp port to see, how can i do that.

thx

**Comment by pedroSG94** [comment]
First of all, you need a media server installed in your PC.
If you want RTSP you can use trial version of wowza:
https://www.wowza.com/pricing/trial
By default wowza have a application name live and port 1935 so a endpoint example is like:
rtsp://yourpcip:1935/live/test
You can change test for other thing.
Then you can use that endpoint to open a url in your vlc
