### ISSUE TITLE
Front Camera orientation issue.

### ISSUE THREAD

**Issue by shravanteegala** [pedroSG94/rtmp-rtsp-stream-client-java#190]
In OpenGl RTMP  ,. when  i tap switch camera (Front), put it landscape it shows upside down video preview.
How i can resolve it.
please help me any one.

**Comment by pedroSG94** [comment]
Library version and view used?
You see this only on preview or in stream too?

**Comment by pedroSG94** [comment]
Ok, sorry. Now, I understand the question.
You need flip front camera in openglview to solve it:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L97

**Comment by aponcanos** [comment]
The link is not working. I need this solution. Can you help please?
