### ISSUE TITLE
Display RTMP/RTSP

### ISSUE THREAD

**Issue by bonanza333** [pedroSG94/rtmp-rtsp-stream-client-java#192]
Hi there,
I'm working on this library to add my project, i allready added it but there is few things that i cannot understand or change it.
Sorry im new at JAVA Android

(Display) can we remove black gaps on left and right of stream ? I mean the phone display is for example 640*480 only phone display not widescreen i turned false rotations already changed width and height but doesnt works.

Thank you

**Comment by bonanza333** [comment]
Thank you @pedroSG94
That was quick reply

Can i contact you with mail for something ?

**Comment by pedroSG94** [comment]
Of course, you have my email in the profile.
