### ISSUE TITLE
Parameters Camera

### ISSUE THREAD

**Issue by camillo860** [pedroSG94/rtmp-rtsp-stream-client-java#193]
Hello, 
I use RTMPCCamera1 because RTMPCamera2 don't send video in streaming ( only audio ) I try with Android 7.0
I need set Antibadding to 50Hz in Camera.Parameters 
[https://developer.android.com/reference/android/hardware/Camera.Parameters#ANTIBANDING_50HZ](url) and set Flash in Torch Mode.
Where do I change code?

Thanks

**Comment by pedroSG94** [comment]
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java
You can add it in start() method.

**Comment by camillo860** [comment]
Thanks.
