### ISSUE TITLE
Rotation streaming

### ISSUE THREAD

**Issue by camillo860** [pedroSG94/rtmp-rtsp-stream-client-java#194]
Can i set rotation when i'm streaming? when rotation device to horizontal, rotate video.
If I set rotation before streaming in method prepareVideo, the streaming is horizontal  but i change it dynamics.

**Comment by pedroSG94** [comment]
No, You can't do it while stream but I will add a filter to rotate and flip image on real time

**Comment by camillo860** [comment]
ok, 
Do I create class in package "com.pedro.encoder.input.gl.render;" where superclass is BaseRenderOffScreen and work in it?

**Comment by pedroSG94** [comment]
Yes, you can create your own render. You only need extends from BaseFilterRender and add the filter when you finish it like I do in the opengl example in the app.
I recommend you copy greyscale filter and modify it.
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Real-time-filters

**Comment by pedroSG94** [comment]
Rotation filter was added to the project:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/c47383af5130065e3024c08459c6455d3dc0dbfd
Use example in openglrtmp or openglrtsp activities.

**Comment by camillo860** [comment]
Thanks!.
I try it.  
When I'm streaming  I set rotation, the video on server and preview on device rotation.
I need set rotation only video to the streaming and not the preview.

**Comment by camillo860** [comment]
What is the parameter "hardware rotation"  when i create object rtmpcamera1?

**Comment by pedroSG94** [comment]
It means that use rotation with encoder or use other way (I recommend you never use true because some device can't do it and ignore that parameter).

**Comment by camillo860** [comment]
Ok Thanks.
I create streaming vertical or horizontal with parameter rotation in instance class and onOrientationChanged method
