### ISSUE TITLE
RTSP server

### ISSUE THREAD

**Issue by rniebecker** [pedroSG94/rtmp-rtsp-stream-client-java#195]
Reviewing your code it looks like you only support pushing RTSP to a server.

 My use case is that I want to be able to pull the RTSP stream instead using a client like VLC using UDP.

Can I do this with your library?

Thanks,
Ralf

**Comment by pedroSG94** [comment]
No. It is not supported for now.

**Comment by jdonzallaz** [comment]
Is there any plan for this feature ?
It would be very appreciated !

Thanks for your work !
