### ISSUE TITLE
How to stream only audio?

### ISSUE THREAD

**Issue by denebchorny** [pedroSG94/rtmp-rtsp-stream-client-java#197]
Is there a way to use the library to just stream audio?

I dont need to show a camera feedback to the user. But the RtmpCamera1 needs a surface to be init.

This idea for streaming only audio is almost the same to stream video without feedback. Is there a way to doy or a workaround?

PD: If you dont understand me at all I could find another way to be understandable.

**Comment by pedroSG94** [comment]
I did an implementation of it. Only tested in RTMP but RTSP should work.
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/6141815ca9b7fcf8e392d0c1a995e7a5a4ee863b
For now you only can stream. I have plan to add record audio.

**Comment by denebchorny** [comment]
Thanksssssssssssss you rockssssssssss
