### ISSUE TITLE
Two way streaming

### ISSUE THREAD

**Issue by denebchorny** [pedroSG94/rtmp-rtsp-stream-client-java#198]
Hi, I have an android camera.The idea is let the phone establish a communication with it. Then, I would like to implement two ways communication where I can stream to the camera and vice versa.

I mean, in the phone I would like to see the video-audio streamed by the camera meanwhile I could stream video-audio to the camera.

I tried the echo canceller and the noise suppersor (both in the videoview and in the library) but I have a horrible feedback. Its like a loop sound from the hell XD.

Do you have any idea of implementing such thing?

IDK if this feature, to be implemented well, depends of controlling the noise in both ways, on the videoplayer for receiving and your library for streaming.

I am using IjkVideoView (Asian videoView found on internet to solve the problem of streaming RTMPS and works well) to receive the streaming and using your library I stream exactly as the demo of default RTMP with the difference of:

Initializing with nothing special than bitrate:
```
rtmpCamera1 = new RtmpCamera1(mVideoFeedback, this);
rtmpCamera1.setVideoBitrateOnFly(300 * 1024);
```

And the audio prepared like this:
`        rtmpCamera1.prepareAudio(96 * 1024, 44100, true, true, true)`

If you have any idea to solve this or any approach I'm all ears

**Comment by pedroSG94** [comment]
If you want stream P2P the best protocol that I know is webrtc. https://webrtc.org/
rtmp and rtsp is 1 to n protocol and only 1 way. I mean 1 user stream to n users but this 1 user never receive anything from others user, like when you see TV where TV canal is this user and you are one of that n users.
Yes, echo canceller and the noise suppressor work bad in some devices. Nothing to do here, it is an audio filter from android api. Try increase audio bitrate maybe it work.
