### ISSUE TITLE
Brutal crash on Nexus4 with Android 5.1.1

### ISSUE THREAD

**Issue by moster67** [pedroSG94/rtmp-rtsp-stream-client-java#2]
Thanks for this project. 
I have tried it out with Wowza Streaming CLoud but I have a brutal crash where my device gets killed and restarts. Unfortunately LogCat does not show any logs.
I tested the CustomRTSP example and only changing the resolution to 640 x 480 otherwise everything left as default. Wowza sees the connection and streaming starts but after 30 seconds the device reboots..

Any idea?

**Comment by pedroSG94** [comment]
I never see a reboot. Maybe your encoder crash.
If you try with low fps and low videobitrate the mobile reboot too?

If you delete the code in methods in the builder:

```
@Override
  public void inputYv12Data(byte[] buffer, int width, int height) {
    videoEncoder.inputYv12Data(buffer, width, height);
  }

  @Override
  public void inputNv21Data(byte[] buffer, int width, int height) {
    videoEncoder.inputNv21Data(buffer, width, height);
}
```
You will do a only audio stream (you never send video data to encoder). If the problem is solved then maybe your device has a problem with videoencoder.
In this case:
You can try with other video colorformat. Go to preparevideo() in the builder and test with camera in YV12 and FormatVideoEncoder in all YUV420 (YUV420PLANAR, YUV420SEMIPLANAR, YUV420PACKEDPLANAR, YUV420PACKEDSEMIPLANAR).
FormatVideoEncoder.YUV420Dynamical automatically select the first compatible color format for your encoder and maybe that color is bug in your device.

Other way is try select other h264 video encoder if your device have more than one. For this go to VideoEncoder class in encoder module and hardcode the other encoder name in:

`videoEncoder = MediaCodec.createByCodecName(encoder.getName());`

Use this method for know all h264 encoders in your device (mime = "video/avc"):

```
private void chooseVideoEncoder(String mime) {
    int count = MediaCodecList.getCodecCount();
    for (int i = 0; i < count; i++) {
      MediaCodecInfo mci = MediaCodecList.getCodecInfoAt(i);
      if (!mci.isEncoder()) {
        continue;
      }
      String[] types = mci.getSupportedTypes();
      for (String type : types) {
        if (type.equalsIgnoreCase(mime)) {
          Log.i(TAG, String.format("videoEncoder %s type supported: %s", mci.getName(), type));
        }
      }
    }
  }


```

**Comment by moster67** [comment]
I think the phone should be OK - works fine with for example the libstreaming-project. I am really interested in RTMP support so I hope to get your project working.
Many thanks for your informative reply. I will try out your suggestions and report back.

**Comment by moster67** [comment]
Well, I have tried your suggestions.

With RTSP, the only configuration I can get working is using 320x240, BR 1500, FPS 21, audio BR 64, 44100 and Mono. I have now tried all possible configurations but generally lowering quite a bit the values, things gets better although sometimes the device reboots.

I tried to disable video as suggested but if I do then there is no connection with Wowza. Maybe I am doing it wrong.

I also tried changing the FormatVideoEncoder as suggested, some worked, some not but would still lead to a reboot unless I lowered the configuration values. I also tried to hardcode the encoder but I noted it was the same which your code already detected. So no change.

Then I tried using RTMP and got similar problems although the device would rarely reboot. It seems, at least in RTMP, the problem is due to OutOfMemoryErrors. I tried to increase the heap-size in the manifest (android:largeHeap="true) but no change. The logs are:

`04-08 18:36:02.870 9049-9067/com.pedro.rtmpstreamer E/art: Throwing OutOfMemoryError "Failed to allocate a 576012 byte allocation with 509056 free bytes and 497KB until OOM"
04-08 18:36:02.870 9049-9067/com.pedro.rtmpstreamer E/Camera-JNI: Couldn't allocate byte array for JPEG data
04-08 18:36:02.875 9049-10911/com.pedro.rtmpstreamer E/AndroidRuntime: FATAL EXCEPTION: Thread-741
                                                                       Process: com.pedro.rtmpstreamer, PID: 9049
                                                                       java.lang.NullPointerException: Attempt to get length of null array
                                                                           at com.pedro.encoder.utils.YUVUtil.NV21toYUV420SemiPlanar(YUVUtil.java:192)
                                                                           at com.pedro.encoder.utils.YUVUtil.NV21toYUV420byColor(YUVUtil.java:157)
                                                                           at com.pedro.encoder.video.VideoEncoder$2.run(VideoEncoder.java:228)
                                                                           at java.lang.Thread.run(Thread.java:818)
04-08 18:36:02.880 9049-9049/com.pedro.rtmpstreamer I/SrsFlvMuxer: SrsFlvMuxer closed
04-08 18:36:02.897 9049-10913/com.pedro.rtmpstreamer D/RtmpConnection: closeStream(): setting current stream ID to 0
04-08 18:36:02.898 9049-10913/com.pedro.rtmpstreamer D/RtmpConnection: wrote packet: RTMP Command (command: closeStream, transaction ID: 0), size: 24
04-08 18:36:02.902 9049-10457/com.pedro.rtmpstreamer I/SrsFlvMuxer: flv: h264 sps/pps sent, sps=13B, pps=4B
04-08 18:36:02.926 9049-10913/com.pedro.rtmpstreamer D/RtmpConnection: socket closed
04-08 18:36:02.929 9049-10913/com.pedro.rtmpstreamer I/SrsFlvMuxer: worker: disconnect ok.
04-08 18:36:03.057 9049-9049/com.pedro.rtmpstreamer I/MicrophoneManager: Microphone stopped
04-08 18:36:03.075 9049-10457/com.pedro.rtmpstreamer I/Process: Sending signal. PID: 9049 SIG: 9`

I really don't know what to make out of it...

**Comment by moster67** [comment]
Well, today I tested with a Samsung S3 neo running 4.2.2 and it behaved MUCH better. Still had to fiddle with the configuration to find the perfect stream (for phone and server) but the result was good. I actually changed the streaming server and used SRS (Simple-RTMP-Server) which is very nice and easy to set up.

I don't know how to resolve the problems with my Nexus4 which is a pity because you get doubts if I implement your great library in an app and will it work most devices. I need to get hold of more phones. Are you able to tell me on which which devices you have tested it on?

**Comment by pedroSG94** [comment]
Hi. Thanks for report the result of your test.
At the moment I only could test in nexus 5x, nexus 6P, samsung j5 and bq e5 (working all).
I will try test in more device and reproduce the crash but it could be really difficult to solve

**Comment by pedroSG94** [comment]
I did a update for outofmemory rtmp crash. I think that it could be caused because your device work so slow and then generate so much buffer in memory and then crash. If it is solved with the update, maybe the reboot in rtsp could be for that reason. Let me know if it work and i will do other update for rtsp

**Comment by moster67** [comment]
Hi, just saw your msg and update now. Thanks.
I will check this evening when I am back home from work and then let you know.

**Comment by moster67** [comment]
Managed to do some tests now using RTMP. The Nexus4 is now behaving much better, even with higher values,  although I still get that occasional reboot but more rarely. It might be something with the phone.

I have two questions:
1) Occasionally I would like to broadcast only audio (no video). In this moment, you have a VideoEnabled-option but if I set it to true, the library will send a black screen and I guess this will still occupy some bandwidth in upload. Is it possible to "switch off" the videoencoder somehow so only audio is sent?
2)  If I use your CustomRTMP app, the orientation will be correct when the phone is in landscape when I watch the stream with VLC on my PC. However, if the phone is in portrait, the video is shown in landscape on VLC. This happens both on my Samsung S3 Neo and my Nexus4. I tried to change the orientation in the sample-app but it has no effect.

I like this library very much and it is very nice clear code - my compliments to your coding!

**Comment by pedroSG94** [comment]
1. I tried to add video disable feature stopping encode video but sometimes stream freeze so I send a black screen but with so low bitrate for bandwidth preserve (bitrate change on fly only work for api 19+ so you will send same birate on api 19- with camera disable). Audio disable work similar.

2. Actually orientation only change stream result (encoder change orientation frame) not preview camera. Remember change orientation before start stream.
Anyway if the problem persist you can set camera to nv21 color format and rotate with YUVUtil class (actually I dont use this method because it could cause a drop frame).

**Comment by moster67** [comment]
Your DisableVideo (in the TRMPBuilder) resulting in a black screen works just fine to braodcast only Audio. Thank you.

However, I still have not been able to sort out the orientation-problem. I tried what you suggested which I believe is done here:
` @Override
  public void onPreviewFrame(byte[] data, Camera camera) {
    if (fpsController.fpsIsValid()) {
      if (imageFormat == ImageFormat.YV12) {
        getCameraData.inputYv12Data(data, width, height);
      } else if (imageFormat == ImageFormat.NV21) {
        getCameraData.inputNv21Data(data, width, height);
        YUVUtil.rotateNV21(data,width,height,90);
      }
    }
  }

but it does not work....
So you are saying that on your devices the orientation is OK? I am wondering if this could be a problem with the SRS-server. I haven't checked with Wowza.`

**Comment by pedroSG94** [comment]
You are not doing rotation properly with YUVUtil. You should do it:

```
@Override
public void onPreviewFrame(byte[] data, Camera camera) {
if (fpsController.fpsIsValid()) {
if (imageFormat == ImageFormat.YV12) {
getCameraData.inputYv12Data(data, width, height);
} else if (imageFormat == ImageFormat.NV21) {
getCameraData.inputNv21Data(YUVUtil.rotateNV21(data,width,height,90), width, height);
}
}
}
```
