### ISSUE TITLE
take photo

### ISSUE THREAD

**Issue by Loren1994** [pedroSG94/rtmp-rtsp-stream-client-java#200]
I would like take photo while streaming.
 I add function getTargetFrame() in Camera1ApiManager, and add
` @Override
    public void onPreviewFrame(byte[] data, Camera camera) {
        targetFrame = new Frame(data, isFrontCamera && (orientation == 90 || orientation == 270), imageFormat);
        getCameraData.inputYUVData(targetFrame);
        camera.addCallbackBuffer(yuvBuffer);
    }`

I use getTargetFrame() to get buffer in my Activity,and convert to bitmap.

`
private fun getCurrentBitmap(): Bitmap? {
        if (null == rtspCamera1!!.cameraManager.targetFrame) {
            toast("camera not init")
            return null
        }
        val width = 480
        val height = 640
        val buffer = rtspCamera1!!.cameraManager.targetFrame.buffer
        var data = YUVUtil.rotateNV21(buffer, width, height, 90)
        val yuvDatalength = width * height * 3 / 2
        val aIn = Allocation.createSized(rs, Element.U8(rs), yuvDatalength)
        val bmpout = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888)
        val aOut = Allocation.createFromBitmap(rs, bmpout)
        yuvToRgbIntrinsic.setInput(aIn)
        aIn.copyFrom(data)
        yuvToRgbIntrinsic.forEach(aOut)
        aOut.copyTo(bmpout)
        return bmpout
    }
`

why did I get a wrong bitmap? and getCurrentBitmap() many times only get once right bitmap.

**Comment by pedroSG94** [comment]
I don't know where is the error now (I'm watching it from my smartphone). But I did a method that should work for convert nv21 to bitmap in my YuvUtils class. Try with that. 
Anyway I have plan to add this functionality to my library in all modes except display.

**Comment by Loren1994** [comment]
can you share you method that nv21 to bitmap ?
I would like to try it

**Comment by pedroSG94** [comment]
You can try this:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/utils/YUVUtil.java#L260
If no work try:
```java
YuvImage im = new YuvImage(data, ImageFormat.NV21, size.width,
                        size.height, null);
Rect r = new Rect(0,0,size.width,size.height);
ByteArrayOutputStream baos = new ByteArrayOutputStream();
im.compressToJpeg(r, parameters.getJpegQuality(), baos);

try{
   FileOutputStream output = new FileOutputStream(String.format(
        "/sdcard/%s_%d.jpg", strPrevCBType, System.currentTimeMillis()));
   output.write(baos.toByteArray());
   output.flush();
   output.close();
}catch(FileNotFoundException e){
}catch(IOException e){
}
```

**Comment by Loren1994** [comment]
dumpYUVData doesn't works.
The second method generate a wrong picture. like this:
![426de4cbe583558cd41e4f3bff831205](https://user-images.githubusercontent.com/19885732/42729567-81ded846-880e-11e8-9aa3-7444d918da0c.png)
Same effect as my method

**Comment by pedroSG94** [comment]
I did a method to get bitmap from a frame in camera1manager. Usage:
- Update project to get new method in YUVUtil class. https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/9e11272b9f8e9d06c5d3032c0c9767eb056ff17a
- Get bitmap from frame like:
```java
private boolean takePhoto = true;

  @Override
  public void onPreviewFrame(byte[] data, Camera camera) {
    Frame frame =
        new Frame(data, isFrontCamera && (orientation == 90 || orientation == 270), imageFormat);
    if (takePhoto) {
      YUVUtil.preAllocateBuffers(width * height * 3 / 2);
      saveBitmap(YUVUtil.frameToBitmap(frame, width, height, orientation));
      takePhoto = false;
    }
    getCameraData.inputYUVData(frame);
    camera.addCallbackBuffer(yuvBuffer);
  }
```
- Modify saveBitmap to change image format and destiny path:
```java
private void saveBitmap(Bitmap bitmap) {
    File folder = new File(Environment.getExternalStorageDirectory().getAbsolutePath()
        + "/rtmp-rtsp-stream-client-java");
    SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault());
    String currentDateAndTime = sdf.format(new Date());
    FileOutputStream out = null;
    try {
      out = new FileOutputStream(folder.getAbsolutePath() + "/" + currentDateAndTime + ".png");
      bitmap.compress(Bitmap.CompressFormat.PNG, 100, out); // bmp is your Bitmap instance
      // PNG is a lossless format, the compression factor (100) is ignored
    } catch (Exception e) {
      e.printStackTrace();
    } finally {
      try {
        if (out != null) {
          out.close();
        }
      } catch (IOException e) {
        e.printStackTrace();
      }
    }
  }
```

**Comment by Loren1994** [comment]
It works.
I found that the frame obtained by the getter in Activity will get an incorrect bitmap,
but it get a correct bitmap in onPreviewFrame().
it's weird.

**Comment by pedroSG94** [comment]
You can do a callback(with an interface) if you want get it from activity.

**Comment by Loren1994** [comment]
yes, I have done. 
:-)
