### ISSUE TITLE
(Enhancement) Add http live streaming?

### ISSUE THREAD

**Issue by sagar1garg** [pedroSG94/rtmp-rtsp-stream-client-java#201]
@pedroSG94 

Any plans to add http live streaming anytime soon?

**Comment by pedroSG94** [comment]
Maybe yes, but no in this library. If I do it I think that I will create other project

**Comment by sagar1garg** [comment]
@pedroSG94

Any decision on this yet?

**Comment by pedroSG94** [comment]
No for now. Maybe in the future but I don't know when.
