### ISSUE TITLE
How can I stream video without showing a preview?

### ISSUE THREAD

**Issue by denebchorny** [pedroSG94/rtmp-rtsp-stream-client-java#204]
I want to avoid the use of Suface or another view that shows a preview.

Is there any way to streaming without this preview?

**Comment by pedroSG94** [comment]
Yes, you can.
Camera constructor: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtmp/RtmpCamera1.java#L50
Camera2 constructor: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtmp/RtmpCamera2.java#L50
