### ISSUE TITLE
Can the motion detection be done using this library and stream the video based on that, similarly for camera mask and unmask

### ISSUE THREAD

**Issue by Shanmugamsundarrajan** [pedroSG94/rtmp-rtsp-stream-client-java#205]

**Comment by pedroSG94** [comment]
I'm not sure what you want but... Do you want start or stop stream based on if you detect any motion in the image?
In this case you can't do it. Motion detection should be done for you and start or stop stream manually.

**Comment by Shanmugamsundarrajan** [comment]
Yeah, on the detection of motion , mask or unmask, we need to start the stream.
I wanted to know on how to detect the motion, mask and unmask?

**Comment by pedroSG94** [comment]
I don't know how to detect motion in android camera.
Also I don't know what do you want say with "mask and unmask".
