### ISSUE TITLE
empty file when start record in service

### ISSUE THREAD

**Issue by omarmakeen** [pedroSG94/rtmp-rtsp-stream-client-java#207]
I can start stream successfully in service but I've problem when start record after that, it give me an empty file

Here are the code

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR2) {
            File folder = new File(Environment.getExternalStorageDirectory().getAbsolutePath());
            if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.LOLLIPOP) {
                if (!rtmpCamera2.isRecording() && rtmpCamera2.isStreaming()) {
                    try {
                        if (!folder.exists()) {
                            folder.mkdir();
                        }
                        SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault());
                        currentDateAndTime = sdf.format(new Date());
                        rtmpCamera2.startRecord(folder.getAbsolutePath() + "/" + currentDateAndTime + ".mp4");
                        Toast.makeText(this, "Recording... ", Toast.LENGTH_SHORT).show();
                    } catch (IOException e) {
                        rtmpCamera2.stopRecord();
                        Toast.makeText(this, e.getMessage(), Toast.LENGTH_SHORT).show();
                    }
                } else {
                    rtspCamera2.stopRecord();
                    Toast.makeText(this,
                            "file " + currentDateAndTime + ".mp4 saved in " + folder.getAbsolutePath(),
                            Toast.LENGTH_SHORT).show();
                    currentDateAndTime = "";
                }
            } 
}

Here are some logs:

D/RtmpConnection: wrote packet: RTMP Audio, size: 383
D/RtmpConnection: wrote packet: RTMP Audio, size: 379
D/RtmpConnection: wrote packet: RTMP Audio, size: 380
D/RtmpConnection: wrote packet: RTMP Audio, size: 378
D/RtmpConnection: wrote packet: RTMP Audio, size: 380
D/RtmpConnection: wrote packet: RTMP Audio, size: 376
D/RtmpConnection: wrote packet: RTMP Audio, size: 380
D/RtmpConnection: wrote packet: RTMP Audio, size: 383
D/RtmpConnection: wrote packet: RTMP Audio, size: 396
D/RtmpConnection: wrote packet: RTMP Audio, size: 391
D/RtmpConnection: wrote packet: RTMP Audio, size: 380
D/RtmpConnection: wrote packet: RTMP Audio, size: 373
D/RtmpConnection: wrote packet: RTMP Audio, size: 378

**Comment by pedroSG94** [comment]
First try record a video with my app demo in any mode for example use this class (You can record  streaming or without stream):
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java
If all is fine then change your constructor object library object to object that you use in your service.
for example this line:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L102
To:
```java
rtmpCamera1 = new RtmpCamera1(this);
```
And retry record a file. 

If all is fine you should have some code error. If you want you can share me full code of service to know where is the error. If something failed let me know what failed and share me your service to try reproduce your fail.

If you can't record with my app code maybe the error is related with this issue that will be difficult to solve because it could be an encoder issue of any devices: 
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/202

**Comment by pedroSG94** [comment]
You are doing somethings bad like use constructor with a surfaceview for stream in background, you should use context instead of surfaceview.
I did a service that work for me on API 18+. This service start stream and record when you start it and stop record and stream when you stop it.
```java
package com.pedro.rtpstreamer;

import android.app.Service;
import android.content.Intent;
import android.os.Build;
import android.os.Environment;
import android.os.IBinder;
import android.support.annotation.RequiresApi;
import android.util.Log;
import com.pedro.rtplibrary.rtmp.RtmpCamera1;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import net.ossrs.rtmp.ConnectCheckerRtmp;

/**
 * Created by pedro on 6/08/18.
 *
 * Little service demo to startStream and record at time when service start and stop stream and record when service finish.
 * If you want only audio stream use: {@link com.pedro.rtplibrary.base.OnlyAudioBase}
 * As you can see startPreview and stopPreview is not necessary with background stream mode.
 */

@RequiresApi(api = Build.VERSION_CODES.JELLY_BEAN_MR2)
public class LiveStreamService extends Service implements ConnectCheckerRtmp {

  private static final String TAG = "LiveStreamService";
  private RtmpCamera1 rtmpCamera1;
  private String currentDateAndTime = "";
  private File folder = new File(Environment.getExternalStorageDirectory().getAbsolutePath()
      + "/rtmp-rtsp-stream-client-java");

  @Override
  public void onCreate() {
    rtmpCamera1 = new RtmpCamera1(this, this);
    if (!rtmpCamera1.isStreaming()) {
      if (rtmpCamera1.prepareAudio() && rtmpCamera1.prepareVideo()) {
        rtmpCamera1.startStream("rtmp://192.168.1.130/live/pedro");
      }
    }
    startStopRecord();
  }

  // Stop recording and stream
  @Override
  public void onDestroy() {
    startStopRecord();
    rtmpCamera1.stopStream();
  }

  @Override
  public IBinder onBind(Intent intent) {
    return null;
  }

  @Override
  public int onStartCommand(Intent intent, int flags, int startId) {
    super.onStart(intent, startId);
    return START_NOT_STICKY;
  }

  private void startStopRecord() {
    if (!rtmpCamera1.isRecording()) {
      try {
        if (!folder.exists()) {
          folder.mkdir();
        }
        SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault());
        currentDateAndTime = sdf.format(new Date());
        if (!rtmpCamera1.isStreaming()) {
          if (rtmpCamera1.prepareAudio() && rtmpCamera1.prepareVideo()) {
            rtmpCamera1.startRecord(folder.getAbsolutePath() + "/" + currentDateAndTime + ".mp4");
            Log.i(TAG, "Recording... ");
          } else {
            Log.i(TAG, "Error preparing stream, This device cant do it");
          }
        } else {
          rtmpCamera1.startRecord(folder.getAbsolutePath() + "/" + currentDateAndTime + ".mp4");
          Log.i(TAG, "Recording... ");
        }
      } catch (IOException e) {
        rtmpCamera1.stopRecord();
        Log.i(TAG, e.getMessage());
      }
    } else {
      rtmpCamera1.stopRecord();
      Log.i(TAG, "file " + currentDateAndTime + ".mp4 saved in " + folder.getAbsolutePath());
      currentDateAndTime = "";
    }
  }

  @Override
  public void onConnectionSuccessRtmp() {
  }

  @Override
  public void onConnectionFailedRtmp(String s) {
  }

  @Override
  public void onDisconnectRtmp() {
  }

  @Override
  public void onAuthErrorRtmp() {

  }

  @Override
  public void onAuthSuccessRtmp() {

  }
}

```
Start and stop service:
```java
 startService(new Intent(this, LiveStreamService.class));
stopService(new Intent(this, LiveStreamService.class));
```

**Comment by omarmakeen** [comment]
Thanks a lot for your great help, your example is working fine for me
I've one problem I'm display streaming video in web using jwplayer it was working fine with library version 1.3.8 after upgrade to 1.4.0 the video is playing for 1 or 2 seconds then video is freezed
do you have any clue?

**Comment by pedroSG94** [comment]
I don't know it work fine for me with VLC. 
Please test with other device and also try stream with preview using my app demo to know where is the problem more exactly, I will try investigate it.
