### ISSUE TITLE
Enhance REGEX

### ISSUE THREAD

**Issue by denebchorny** [pedroSG94/rtmp-rtsp-stream-client-java#208]
I was trying a RTMPS url and I got a message that says: 
Endpoint malformed, should be: rtmp://ip:port/appname/streamname

I found that the RTMPS url is correct but in the form of:
rtmps://ip:port/appname/publishPoint/streamname

As you can see a publishPoint could be valid into the RTMP url.

I dont suggest an REGEX yet because I am trying to find a better one that can fit not only for my but in general. 

Uf you find something better It would be nice. I'll try to bring you an answer soon.

Even I think you can change the toast message by RTMP type to be more accurate.

Tell me if this is useful or practical to continue investigating it

**Comment by pedroSG94** [comment]
I though that stream name like:
```
publishPoint/streamname
```
Is not valid. If it is valid I will try change in the next days for now if you want test you can modify it in this class to force validate:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L100

**Comment by pedroSG94** [comment]
Fixed: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/40360356094d4e6079394db87c487fce915eb750
