### ISSUE TITLE
Screen - Display stream limit fps issue (Dont write over fps set at video encoder)

### ISSUE THREAD

**Issue by mhackeras** [pedroSG94/rtmp-rtsp-stream-client-java#213]
Well as I told you before in privately fps is a big problem specially in streaming.
As I read frame rate doesn't really work in encoder, cause encoder will get every frame it's fed. So there is a need of dropping frames if input frame number is more than the given one.

**Comment by pedroSG94** [comment]
Yes, you are right. FPS parameter is used for this: 
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L109
But that line no limit fps or skip if you send so much fps. I will do a commit to add this feature in the future but you only need limit that in this callback with some function: 
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L625
You can find that callback in all base if you use other base.

**Comment by pedroSG94** [comment]
No, you can't do it. You only can change video bitrate on fly and with API19+. If you want change fps you need stop encoder change configuration and start encoder.

**Comment by mhackeras** [comment]
If it could help you.. when testing.. i set encoder to 30fps but the game frame rate is 27 fps. so the video bitrate lowers according to missed fps.
if it is set on 30fps 3000 video bitrate and real fps is 27.. then video bitrate send is (3000*27)/30=2700.

Also as a feature request we ve talked and you told me video record cant be used without streaming display video :/

**Comment by mhackeras** [comment]
format.setInteger(MediaFormat.KEY_CAPTURE_RATE, frameRate);
Could this limit the capture rate of mediaprojection to encoder? :/

**Comment by pedroSG94** [comment]
I don't know I need test it.

**Comment by mhackeras** [comment]
Pedro if you play with these.. i thought of implementing fps indicator.. and it's easy just listen to frames got from mediaprojection and calculate them to get fps. This would be a nice implementation

**Comment by mhackeras** [comment]
ok nevermind just copied and merged with mine :/ so whatever improvement i
make i ll email you cause i dont know how to push things :/
Also if you could give me a direction on what i should do to enable display
recording without streaming it should be great.

Στις Κυρ, 16 Σεπ 2018 στις 2:18 μ.μ., ο/η Bill M <billmenekos@gmail.com>
έγραψε:

**Comment by mhackeras** [comment]
pedro i made some changes it seems it works good. Though can you tell me a
fast way to get fps used to start streaming?
i used MediaCodec.BUFFER_FLAG_KEY_FRAME but it returns wrong fps

Στις Κυρ, 16 Σεπ 2018 στις 2:28 μ.μ., ο/η Bill M <billmenekos@gmail.com>
έγραψε:

**Comment by mhackeras** [comment]
Pedro i used a timer to get fps and limited getH264DataRtp(h264Buffer, info);
but is this really working? does it limit the frames sent? also is it wise to not send some fps that maybe essential ?

**Comment by mhackeras** [comment]
Also by messing up with these things got unsupported video message in twitch.tv

**Comment by pedroSG94** [comment]
The only way to limit fps is like you did but you should do it in videoencoder class because if you do a  filter, you could skip keyframes and you will get errors.
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L312

**Comment by mhackeras** [comment]
ok thats what i thought.. Is it possible to know when it is a keyframe so not to ignore it ? i read somewhere that it is essential to write the frame to know this

**Comment by pedroSG94** [comment]
You have this flag to know it:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L615
Anyway if you only encode 10 times per second or something like that you haven't that problem.

**Comment by mhackeras** [comment]
yeah but on 30 fps i get bad image. it misses key frames i think or something like that. cause i limit it to 30 fps and maybe there is a missing piece in the 1000ms

**Comment by mhackeras** [comment]
if i limit to 30fps it sends a keyframe every one second.. is that right?

**Comment by pedroSG94** [comment]
Depend iframeinterval setted:
https://developer.android.com/reference/android/media/MediaFormat.html#KEY_I_FRAME_INTERVAL

**Comment by mhackeras** [comment]
yeap it is set at 2 but sends every 1

Στις Δευ, 17 Σεπ 2018 στις 12:55 μ.μ., ο/η Pedro Sánchez <
notifications@github.com> έγραψε:

**Comment by pedroSG94** [comment]
Maybe this is the reason:
```java
Most video encoders will convert this value of the number of non-key-frames between key-frames, using the frame rate information; therefore, if the actual frame rate differs (e.g. input frames are dropped or the frame rate changes), the time interval between key frames will not be the configured value.
```
You can see it in the link that I shared you

**Comment by mhackeras** [comment]
yeap noticed this a long time ago and i remember reporting this to you..
ignoring frames doesnt really work :/ i get bad image. even if i limit
getDatafromsurfaceapi21..
I am really digging this.. if i get something i ll report back to you. and
i am sorry for disturbing you. :/

Στις Δευ, 17 Σεπ 2018 στις 1:56 μ.μ., ο/η Pedro Sánchez <
notifications@github.com> έγραψε:

**Comment by mhackeras** [comment]
it is impossible to send less changes to video encoder right :/ ?

Στις Δευ, 17 Σεπ 2018 στις 2:02 μ.μ., ο/η Bill M <billmenekos@gmail.com>
έγραψε:

**Comment by pedroSG94** [comment]
Oh, I didn't know it. I will test it and add to display mode if it works.

**Comment by mhackeras** [comment]
Ok by using simple Thread.Sleep(1000/fps) on getDataFromSurfaceAPI21() seems to limit fps fine and without any problem when streaming.  Just should do something to avoid error cause of thread working or something like that. if you think this is a good solution please add this.

try {
               Thread.sleep(1000/fps);
 }catch (InterruptedException e){

 }

**Comment by pedroSG94** [comment]
I did tests with MediaFormat.KEY_REPEAT_PREVIOUS_FRAME_AFTER but no work :( (do you know how to do it?)
Your sleep solution works for surface mode but no for buffer to buffer mode:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L392
I need adapt it for it (used in default activity or custom activity examples) and then I will add it.

**Comment by mhackeras** [comment]
Yeap still working on this.. if i do more i ll surely send here. You have the knowledge and is your project you know more. (this issue is big and if solved will be big too.)
Also tried key_repeat and didnt work for me too.

**Comment by pedroSG94** [comment]
I did it:
```java
private boolean validFps() {
    if (System.currentTimeMillis() - lastFrameTimestamp > 1000 / fps) {
      lastFrameTimestamp = System.currentTimeMillis();
      return true;
    }
    return false;
  }
```
To implement you should do:
```java
if (!validFps()) continue;
```
You only need implement it here (in while loop):
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L316

**Comment by mhackeras** [comment]
i used inside while loop and didnt work.
BUT it worked like a charm in the for loop! LIKE A CHARM :) Good job!
This can be used for camera bases too. To limit unless google took care of this already. (Haven't tried yet)
Also studying to figure out how MediaFormat.KEY_REPEAT_PREVIOUS_FRAME_AFTER could work... 
this issue can be closed as it is fixed! :) 👍

**Comment by mhackeras** [comment]
Also @pedroSG94 test with this
videoFormat.setLong(MediaFormat.KEY_REPEAT_PREVIOUS_FRAME_AFTER,500000);
it seems to kinda work.. this is supposed to repeat frame after 500ms
I think smaller values are not acceptable.. even with this it showed 0 fps some times but most time 2 fps sent which means it did work i double checked with no screen changes

**Comment by pedroSG94** [comment]
The problem in this config is that only repeat a time (apparently). Description from android documentation:
Applies only when configuring a video encoder in "surface-input" mode. The associated value is a long and gives the time in microseconds after which the frame previously submitted to the encoder will be repeated **(once)** if no new frame became available since.

In this case it is no usable because you can't send a constant frame rate you have the same problem.
Limit fps was added here: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/22b3f337c00aa4d80ba95e34ca14a935139f4028

**Comment by mhackeras** [comment]
Saving last frame and send if no screen change using timer or something?

Στις Τρί, 18 Σεπ 2018 στις 10:38 π.μ., ο/η Pedro Sánchez <
notifications@github.com> έγραψε:

**Comment by pedroSG94** [comment]
No work because you only can save h264 buffer in surface mode so you can't send a constant keyframe.
In case that last frame is a keyframe you send all time a big frame, bad idea for bandwidth and could produce errors on the stream.

**Comment by mhackeras** [comment]
Also in youtube solution works good! But in twitch i am getting "Resource format not supported"
