### ISSUE TITLE
Can I just use it for audio streaming

### ISSUE THREAD

**Issue by CoolVenkee** [pedroSG94/rtmp-rtsp-stream-client-java#216]
Hi @pedroSG94 ，can the library support only audio streaming，cause no video stream is needed. By the way，I try to streaming on my OnePlus 5 Android 8.1 phone，and the server is EasyDarwin，I got 403 error code on my phone and can not setup streaming.

**Comment by pedroSG94** [comment]
Hi. You can do audio stream with this:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtsp/RtspOnlyAudio.java
Are you using easydarwin with C++ version or JS version (master  branch). I only tested C++ version (apple branch).
403 is forbidden so maybe any configuration in my library with JS version is not working.
