### ISSUE TITLE
[Question] How to change the audio format profile?

### ISSUE THREAD

**Issue by tplloi** [pedroSG94/rtmp-rtsp-stream-client-java#217]
Hi @pedroSG94 , thanks for your great library. I import you library in my project, it works fine but i have a question for you.

I use
prepareAudio(128 * 1024, 44100, true, true, true);
and 
prepareVideo(1280, 720,, 30, 3000000, false, 0);
before calling startStream();
It works, but my system team get the audio format profile is LPT. 

Audio
```
ID                                       : 257 (0x101)
Menu ID                                  : 1 (0x1)
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format version                           : Version 4
Format profile                           : LTP
Muxing mode                              : MPEG-TS / ADTS
Codec ID                                 : 15
Duration                                 : 3 s 844 ms
Bit rate mode                            : Variable
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 44.1 kHz
Frame rate                               : 43.066 FPS (1024 SPF)
Compression mode                         : Lossy
Delay relative to video                  : -138 ms
Source                                   : testapp-5.ts
```

So i wanna the correct audio format is LC.
I've checked this class https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/audio/AudioEncoder.java
and can see you set the audio format is LC (?).
```
audioFormat.setInteger(MediaFormat.KEY_AAC_PROFILE,
          MediaCodecInfo.CodecProfileLevel.AACObjectLC);
```
Please help.
Thanks in advance.

**Comment by tplloi** [comment]
Hi @pedroSG94 , thanks for your reply.
Im using RTMP.
Ive tried with other devices (Huawei Nexus 6, Xiaomi redmi note4, Huawei Nova 2i, Samsung Note 5) and still get the same result (LTP, not LC).
So I try with other lib stream, like https://github.com/ant-media/LiveVideoBroadcaster and the system team get the correct (audio format profile is LC now).

**Comment by pedroSG94** [comment]
I check a video recorded on Samsung S7 and audio info show me LC profile:
```
ffmpeg -i 20180903_103547.mp4
ffmpeg version 3.4.4-0ubuntu0.18.04.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
  configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '20180903_103547.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2018-09-03T08:35:53.000000Z
    com.android.version: 8.0.0
  Duration: 00:00:04.94, start: 0.000000, bitrate: 1368 kb/s
    Stream #0:0(eng): Video: h264 (Baseline) (avc1 / 0x31637661), yuv420p, 480x640, 1223 kb/s, SAR 1:1 DAR 3:4, 30 fps, 90k tbr, 90k tbn, 180k tbc (default)
    Metadata:
      creation_time   : 2018-09-03T08:35:53.000000Z
      handler_name    : VideoHandle
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 130 kb/s (default)
    Metadata:
      creation_time   : 2018-09-03T08:35:53.000000Z
      handler_name    : SoundHandle
```
Confirm me that you get same result to discard encoder problem on your device. If you only get this error on stream maybe is a packetization fail. In this case I need know protocol used (RTMP or RTSP) and a way to check audio profile on stream.

**Comment by tplloi** [comment]
Hi @pedroSG94 
When i check the record file (the file is created by calling startRecord();-stopRecord()) in my device, its a LC profile.
I only get LTP prfile if on stream.

**Comment by pedroSG94** [comment]
The error should be here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/net/ossrs/rtmp/SrsFlvMuxer.java#L745
Try:
- comment that line
- replace SrsAacObjectType.AacLC value to 4 (LTP value)
- delete - 1 operation. 

I don't know if this will work but I can't test it because I don't know how to see it on my server.
If no work, if you can, share me correct bits values of audio headers for see the differences in my headers and fix.

**Comment by pedroSG94** [comment]
I meant, try it separate:
- comment that line:
```
frame[offset + 2] = (SrsAacObjectType.AacLC - 1) << 6;
```
to
```
//frame[offset + 2] = (SrsAacObjectType.AacLC - 1) << 6;
```
- replace SrsAacObjectType.AacLC value to 4 (LTP value):
```
SrsAacObjectType.AacLC = 2
```
to
```
SrsAacObjectType.AacLC = 4
```
- delete - 1 operation:
```
frame[offset + 2] = (SrsAacObjectType.AacLC - 1) << 6;
```
to
```
frame[offset + 2] = (SrsAacObjectType.AacLC) << 6;
```

**Comment by tplloi** [comment]
Yes @pedroSG94 
I've tried some case you suggest, but its still LTP.
Im on stream with url ```rtmp://14.161.0.68/live-origin/testapp```, can you check this?

**Comment by pedroSG94** [comment]
My bad. I forget uncomment that. Thanks
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/d0282e07e091a8dcd8a0171f5263e79bd3b9742b

**Comment by KAZUMA87** [comment]
Hi @pedroSG94.
I have same trouble.Using RTMP and F8132(SONY Xperia XP) and still get the same result (LTP, not LC).
Download and use commit "d0282e0" , but still the audio format profile is LTP.

Please tell me how to solve it. Thanks.
