### ISSUE TITLE
GEting device bandwidth for upload streaming 

### ISSUE THREAD

**Issue by rxvidia** [pedroSG94/rtmp-rtsp-stream-client-java#219]
Hi Pedro,

How can i get the upload bandwidth available at the device

**Comment by mhackeras** [comment]
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Adaptative-video-bitrate.

**Comment by pedroSG94** [comment]
Yes, in your case you can use bandwidth variable and skip parser of you don't want change video bitrate on fly

**Comment by rxvidia** [comment]
Hi Pedro,
If possible please share sample code

**Comment by pedroSG94** [comment]
You have example code in wiki link.
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Adaptative-video-bitrate.
If you don't understand something let me know how I can help you.

**Comment by rxvidia** [comment]
Thank You Pedro!!!
