### ISSUE TITLE
cann't hear sound by web flash plugin

### ISSUE THREAD

**Issue by yongkaka** [pedroSG94/rtmp-rtsp-stream-client-java#220]
Hi Pedro,
i build a flash player(code in as3). when i use the client to push stream, use flash player to pull the stream(rtmp) on PC , image is normal, but unable to hear sound. when use VLC to pull stream ,sound and image are normal.where is the problem? thanks!

**Comment by pedroSG94** [comment]
If you can hear it with VLC then the problem should be your player. Check you audio encoder supported, you need support AAC with LC profile

**Comment by yongkaka** [comment]
thanks a lot! My red5 server has problem, my red5 server never send AAC parameter to web flash client,so web flash can't decode AAC frame.
