### ISSUE TITLE
Surface filter stops after a few seconds.

### ISSUE THREAD

**Issue by ryan0987** [pedroSG94/rtmp-rtsp-stream-client-java#222]
If I turn on the surface filter while streaming, the sample video stops after a few seconds.
It is played well if I turn it on when it is not streaming. 
Is this a known issue? Or there are some settings that I should check before start streaming?

I tried this:
`MediaPlayer mediaPlayer = MediaPlayer.create(this, R.raw.big_bunny_240p); mediaPlayer.setSurface(surfaceFilterRender.getSurface());
mediaPlayer.start();`

And this:
`MediaPlayer mediaPlayer = new MediaPlayer();
try {
     mediaPlayer.setDataSource("http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4");
     mediaPlayer.prepare();
     mediaPlayer.setSurface(surfaceFilterRender.getSurface());
     mediaPlayer.start();
} catch (IOException e) {
     e.printStackTrace();
}`

But currently, both are not working.

**Comment by pedroSG94** [comment]
Yes, this is a know issue but for now I don't know the reason.
Maybe any error when mediaplayer and opengl draw in surface at same time but I don't know how to check it.
I will do other try to find the solution.

**Comment by haseeb362-amoxt** [comment]
This issue still persists even after 3 years :(
