### ISSUE TITLE
Screen Display Video Record issue when audio is muted

### ISSUE THREAD

**Issue by mhackeras** [pedroSG94/rtmp-rtsp-stream-client-java#226]
When recording screen, if audio is muted, video seems to be ruined.
Raised pcmBufferMuted from Byte[11] to Byte[1024] and this seems to fix video record.

**Comment by pedroSG94** [comment]
Thanks I will implement it and test.

**Comment by pedroSG94** [comment]
If I do it the result is a video with whistle audio. I will work in a solution for this bt for now I can't implement it.

**Comment by mhackeras** [comment]
When testing didnt hear any sound :/ will do more tests.
At first i used smaller buffer size at 128 and 256 but it was still ruinned..
i read it excpects at least 1024 so used this.
Also when on mono and not stereo big bitrates and sample rates where not supported. I hoped you can confirm this.

**Comment by mhackeras** [comment]
I was thinking maybe audio encoder should be limited after limiting fps on video encoder.
I am also writing a pauseRecord method and work on timestamps so i will take a look.

**Comment by pedroSG94** [comment]
No good idea because audio result could be choked.

**Comment by mhackeras** [comment]
Pedro even with your values on microphone muted.. i streamed and when i disabled mic.. it did a strange noise. Also black image doesnt work when disabling video stream-record.

**Comment by pedroSG94** [comment]
black image only work if you use SurfaceView or TextureView with camera1.
I will investigate audio noise.

**Comment by pedroSG94** [comment]
Try this:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/5f24fb98acf9052b0adb7b8f4b368b8ddc34c5eb

**Comment by mhackeras** [comment]
It's working great and this solves the issue with ruinned video when audio is muted!

**Comment by mhackeras** [comment]
It seems though to break streaming.. will test more

**Comment by mhackeras** [comment]
Sometimes it seems it breaks streaming maybe syncing problem.. dont really know.. and get bad output or even stops stream for a little bit. then resumes.
This happens only when disabling audio

**Comment by mhackeras** [comment]
I didnt use a server cause my linux is off.
I just streamed to youtube.
After sometimes i use disable it seems stream stabilizes.
Can u suggest me a server to use using windows?

**Comment by mhackeras** [comment]
Resulting video on youtube seems good though.

**Comment by pedroSG94** [comment]
I will check with youtube.

**Comment by mhackeras** [comment]
Also if you could check on twitch too it would be nice.
It shows a message machine got unplugged error 4000
Thought it was adblocker but it seems it still there.
This appeared after using fps limiter

**Comment by pedroSG94** [comment]
Ok

**Comment by mhackeras** [comment]
but getting this on twitch maybe the problem is in my pc so dont be distracted by this.
though even on twitch inspector when i turn audio got instability.
When i get back from work i ll set my ubuntu and rtmp with statistics

**Comment by mhackeras** [comment]
if it helps you when on twitch it shows me wrong resolution. i set 720 but it shows 1080p

**Comment by pedroSG94** [comment]
I did stream to youtube and twitch sucessfully disabling and enabling audio multiple times (I saw a little stop on youtube after disable audio but only 1 of 20 or 30 times and only 1 second. In twitch, I never saw that). In twitch resolution look good for me. Twitch select height like resolution quality. In case that you are streaming in portrait (vertical) mi library rotate image and send 720x1280

**Comment by mhackeras** [comment]
ok. pedro i consider this issue fully fixed. :)
