### ISSUE TITLE
Landscape issue

### ISSUE THREAD

**Issue by mmaschenko** [pedroSG94/rtmp-rtsp-stream-client-java#227]
When previewing or streaming i have issue with landscape right mode. For some reason if i rotate device for example in preview from portrait to landscapeLeft it works ok, if i rotate to landscapeRight - preview is rotated for 180 degrees. It seems that that lib finds that device is in landscape and compensate image for that mode, but it's always landscapeLeft.
Using: 
- android 7.1 (Moto Turbo 2)
- 1.3.8 version of lib

**Comment by pedroSG94** [comment]
With landscape right, do you mean?
```xml
android:screenOrientation="reverseLandscape"
```

**Comment by mmaschenko** [comment]
Yes, streaming is also affected. 
`android:screenOrientation="fullSensor"`
It seems that on when device is in reverseLandscape mode, it still autorotates to regular landscape
![2018-09-28 14 59 19](https://user-images.githubusercontent.com/23169876/46207244-5ca50d00-c32f-11e8-94e5-38d9da99a33c.jpg)
![2018-09-28 14 59 14](https://user-images.githubusercontent.com/23169876/46207243-5ca50d00-c32f-11e8-92c9-f195f9342bbb.jpg)

**Comment by pedroSG94** [comment]
I'm working on it. For now, camera1 is fixed I need fix camera2 too.

**Comment by pedroSG94** [comment]
fixed: 
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/f371aa42fe4fd24a2bbd9f73fb262e509fc05599
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/1d46fb2c80a2306b9daa2e7f18c3bc1b2b9f1c86

**Comment by mmaschenko** [comment]
It seems that preview is fixed, but streaming still has this issue. And more thing after i downloaded library to my project and downloaded last version of lib (1.4.1) streaming doesnt work anymore, If i downgrade to 1.3.8 it streams as it was previously. I will try to apply this two commits to 1.3.8 version or some other version that's not 1.4.1 and check if it helps

**Comment by pedroSG94** [comment]
You can ignore frame discarded, this is because you are waiting server response and you have buffer queue full so you discard frames to preserve memory.
This look a connection error in RtmpConnection class.

First of all check if you receive any reason in this callback:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L297

After, check if connection is successfull here (connected variable should be true):
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L206

**Comment by mmaschenko** [comment]
Hi, from what i investigated preview mode works fine. But here is new issue that i've found. If you rotate directly from landscape to landscapeReverse it is still showing wrong view that is upside (stream is also is upside down). I am using OpenGLView and last version your lib 1.4.2. Do you have any suggestions?

**Comment by andrewBatutin** [comment]
Hi
OpenGLView works ok.
But if i use surface view - i have an issue with front camera in landscape_reverse - it's flipped upside down.
OpenGLView is ok for me.
But maybe you should take a look at SurfaceView activity
Thnx

**Comment by pedroSG94** [comment]
> Hi
> OpenGLView works ok.
> But if i use surface view - i have an issue with front camera in landscape_reverse - it's flipped upside down.
> OpenGLView is ok for me.
> But maybe you should take a look at SurfaceView activity
> Thnx

I will check it.
