### ISSUE TITLE
How to use front camera as default in RTMP?

### ISSUE THREAD

**Issue by denebchorny** [pedroSG94/rtmp-rtsp-stream-client-java#229]
I need to start showing streaming preview from Front Camera if it is possible. How could I do this?

**Comment by pedroSG94** [comment]
Camera1:
rtmpCamera1.startPreview(Camera.CameraInfo.CAMERA_FACING_FRONT);
Camera2:
rtmpCamera2.startPreview(CameraMetadata.LENS_FACING_FRONT);
