### ISSUE TITLE
Can not record rtmp display 

### ISSUE THREAD

**Issue by dungdt3SmartOSC** [pedroSG94/rtmp-rtsp-stream-client-java#230]
Dear developer,

My device: Samsung Galaxy Tab A.
I have implemented version 1.4.1.
But function record rtmp display is not working. After I call **stopRecord** function and exit app. I saw file video had been saved. But I can not open it. It display popup **Failed to play video/ An unknown error has occurred**.
It only work when I add library module (encoder, rtmp, rtp library, rtsp)  in your master branch into my project. File video can open, but duration of file is not true.
![image](https://user-images.githubusercontent.com/37684311/46515377-a9d43200-c88d-11e8-8b3a-207e9de2bcb1.png)

Please check it.

Thanks!

**Comment by pedroSG94** [comment]
If record error is solved for you with master branch. I fixed your error here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/5e49ca8253e217a8c1711ece5be734891bb19bc1

This commit is not added to gradle for now. I will add it today

**Comment by pedroSG94** [comment]
Updated to 1.4.2

**Comment by dungdt3SmartOSC** [comment]
Hi @pedroSG94,

Could you help me check about duration or give me a suggestion? I can investigate it with you.

Thanks!

**Comment by pedroSG94** [comment]
I did a little investigation but I can't reproduce your issue. What gallery are you using? In my gallery I can't see video duration so I did it:
I did a video and share with my PC (linux and windows) and duration in info works. 
Also, I did a metadata check with ffmpeg and all is working fine.

**Comment by dungdt3SmartOSC** [comment]
Hi @pedroSG94,

Thank for your reply. I have recorded and save it on folder Movie of Internal Memory. And I open the folder on PC (windows).

**Comment by pedroSG94** [comment]
I tested with windows 10 and work fine. can you try record other video with my app?. 
I did a video using OpenGlRtmp activity (8 second duration in my case).

Also try with other device (maybe this is a specific device problem). I tested with samsung s7, samsung s6 and nexus 5.
