### ISSUE TITLE
Surface mode RTMP data is being transfer, But unable to open .MP4 file.

### ISSUE THREAD

**Issue by divyashamar** [pedroSG94/rtmp-rtsp-stream-client-java#231]
Hello, 
I am trying to stream data over network using wowza. just getting some input from android mobile camera and sending it to wowza server. although wowza server showing file transfer over the connection and storing it into a file(ie on wowza server) but media players are not showing any video streaming. Can you please help in this regard??

**Comment by pedroSG94** [comment]
I use VLC to open same endpoint that you use to stream in wowza. I tested with my wowza and works with default configuration.
