### ISSUE TITLE
Video - Audio out of sync Display

### ISSUE THREAD

**Issue by mhackeras** [pedroSG94/rtmp-rtsp-stream-client-java#232]
Video and audio get out of sync when recording display and live streaming.
Used on recording video on youtube.. voice came faster.
I suppose it is caused from fps limiter.
it happens when using 30 fps encoder and limiter.
when limiter is on 60fps it is synced.

**Comment by mhackeras** [comment]
Ok pedro when you see this.
instead of setting lasttimestamp inside the limitfps()
i took lasttimestamp from last frame sent and seems to fixing video audio sync

**Comment by mhackeras** [comment]
private boolean limitFPS() {
    if (System.currentTimeMillis() - lastFrameTimestamp > 1000 / fps) {

      return false;
    }
    return true;
  }

@RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)
  private void getDataFromSurfaceAPI21() {
    thread = new Thread(new Runnable() {
      @Override
      public void run() {
        while (!Thread.interrupted()) {
          for (; ; ) {
            if (limitFPS()) continue;
            int outBufferIndex = videoEncoder.dequeueOutputBuffer(videoInfo, 0);
            if (outBufferIndex == MediaCodec.INFO_OUTPUT_FORMAT_CHANGED) {
              MediaFormat mediaFormat = videoEncoder.getOutputFormat();
              getH264Data.onVideoFormat(mediaFormat);
              getH264Data.onSPSandPPS(mediaFormat.getByteBuffer("csd-0"),
                  mediaFormat.getByteBuffer("csd-1"));
              spsPpsSetted = true;
            } else if (outBufferIndex >= 0) {
              //This ByteBuffer is H264
              ByteBuffer bb = videoEncoder.getOutputBuffer(outBufferIndex);
              if ((videoInfo.flags & MediaCodec.BUFFER_FLAG_CODEC_CONFIG) != 0) {
                if (!spsPpsSetted) {
                  Pair<ByteBuffer, ByteBuffer> buffers =
                      decodeSpsPpsFromBuffer(bb.duplicate(), videoInfo.size);
                  if (buffers != null) {
                    getH264Data.onSPSandPPS(buffers.first, buffers.second);
                    spsPpsSetted = true;
                  }
                }
              }
              videoInfo.presentationTimeUs = System.nanoTime() / 1000 - mPresentTimeUs;
              lastFrameTimestamp = videoInfo.presentationTimeUs; <----
              getH264Data.getH264Data(bb, videoInfo);
              videoEncoder.releaseOutputBuffer(outBufferIndex, false);
            } else {
              break;
            }
          }
        }
      }
    });
    thread.start();
  }

**Comment by mhackeras** [comment]
or maybe didnt :/

**Comment by pedroSG94** [comment]
So the reason is skip frames. I will check it.

**Comment by mhackeras** [comment]
I tried a lot of things. On ffmpeg I got a message that it needed to add a bitstream filter cause of something missing. H264_mp4toannexb
Maybe it misses a key frame or something.

**Comment by mhackeras** [comment]
I hope this isnt something stupid.. but limitting OffScreenGlThreads instead of getSurface on VideoEncoder seems to be working.
i hope you can confirm this.

**Comment by mhackeras** [comment]
Yeap it seems to work fine! used limiter in encoder and render. Audio synced.

**Comment by pedroSG94** [comment]
Where did you write limitfps, here?:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/view/OffScreenGlThread.java#L159

**Comment by mhackeras** [comment]
Tested fast by writing under While(running)

**Comment by mhackeras** [comment]
Also Streaming audio is synced! tried on 30 fps when screen rendered 54+ fps

**Comment by pedroSG94** [comment]
Nice! I will add it after test in other off screen modes

**Comment by mhackeras** [comment]
Test in streaming Pedro cause there I heard some weird noise.. but I think it's ok.

**Comment by mhackeras** [comment]
Pedro if you import just test the fps created cause i think by using limiter everywhere lowers quality a lot fps and bitrates too. Maybe i do a bad use. I ll wait for ur solution.

**Comment by mhackeras** [comment]
Gonna test stream and record and if all good I 'll close the issue!

**Comment by mhackeras** [comment]
Work even better than my integration! will close it.
