### ISSUE TITLE
Unable to implement the dependency.

### ISSUE THREAD

**Issue by divyashamar** [pedroSG94/rtmp-rtsp-stream-client-java#234]
Hello!
I am adding dependency in my project. following these instructions "https://github.com/pedroSG94/rtmp-rtsp-stream-client-java". But every time system showing message "com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed", and App Compilation stops Immediately. 

My Project is about streaming data from Mobile camera to wowza server (Only Video Streaming), Am I on right track. I mean your Library is strong enough to deal with this ??

Also, if you can explain in simple steps how to perform the task.

**Comment by pedroSG94** [comment]
In wiki you have a little explication to add library manually if gradle fail for you:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Add-library-to-your-project

Anyway this error look an error indexing res folder. Try to create a new project totally empty of dependencies and files in Android studio and write dependencies in your app build.gradle to discard conflict with other dependencies (also make you that you can compile it before add my dependency).

If the problem persist share me build.gradle code and full logcat error to get more info and help you.
