### ISSUE TITLE
How about adding an enum or static in onConnectionFailedRtmp method?

### ISSUE THREAD

**Issue by denebchorny** [pedroSG94/rtmp-rtsp-stream-client-java#235]
Currently, the method only brings a reason `onConnectionFailedRtmp(final String reason)`. A readable reason. It is closer to a message for a final user than a message to a developer.

I do not know how many reasons may exist but it could be good to be able to place an Enum that allows the developer to know how to handle the problem/issue. Regarding the message, that could change over time and would imply that the developer would be aware of it and change it in the application if it is used as a comparison condition.

I suggest you send something like this:
public void onConnectionFailedRtmp(final int reasonCode, final String reason)

I hope this will be helpful.

**Comment by pedroSG94** [comment]
Yes, this is a good idea. I will implement it.
