### ISSUE TITLE
Face Detection is not working 

### ISSUE THREAD

**Issue by divyashamar** [pedroSG94/rtmp-rtsp-stream-client-java#237]
hello,
I am trying to run the code on device "honor 7a", need a face detection during the video streaming (RTMP, Only Video: 240 X 320). Although, Video streaming is working fine, but Face Detection is not working.

**Comment by pedroSG94** [comment]
Camera1 or Camera2? with camera2 work bad (I'm looking a solution). Remember that you need call this callback after startPreview or startStream.
