### ISSUE TITLE
Video encoding issues with Galaxy S9, Wowza Streaming Cloud

### ISSUE THREAD

**Issue by banggaoo** [pedroSG94/rtmp-rtsp-stream-client-java#238]
We having an issue about using rtmp-rtsp-stream-client-java with Galaxy S9, Wowza Streaming Cloud.
The Video output is have no issue so Wowza passthrough output is works fine. But when Wowza transcoding this video, encoding is not working properly. We attach the output video screenshot transcoded by Wowza Streaing Cloud.

![2](https://user-images.githubusercontent.com/284765/47058787-843a1780-d201-11e8-866f-aa4411ad571f.jpg)
 
We assume that is Android Media Codec setting problem because Wowza GoCoder is works fine with Galaxy S9. So we try to change color format to SemiPlanar/Planar but none of these work properly. Only Software encoding is works properly with right color but video streaming is not works fine.

So we share this issue to solve this problem with others. 

Thanks for your contribution.

**Comment by pedroSG94** [comment]
I know the issue:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/176
Use OpenGlView or LightOpenGlView to solve it.

The problem is that I can't find the error in the code. I think that mediacodec select a different color format than yuvutil or some code error in yuvutil.
For now, I can't get a S8 or S9 to test and solve it. If you are interesting in use buffer to buffer mode (the only advantage is work with API16 and API17) you can try fix it here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/utils/YUVUtil.java#L168

**Comment by pedroSG94** [comment]
Can you test me this to solve the issue?
Replace this method:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/video/FormatVideoEncoder.java#L17
To:
```java
public int getFormatCodec() {
    switch (this) {
      case YUV420FLEXIBLE:
        return MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV420Flexible;
      case YUV420PLANAR:
        return Build.VERSION.SDK_INT >= 21
            ? MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV420Flexible
            : MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV420Planar;
      case YUV420SEMIPLANAR:
        return Build.VERSION.SDK_INT >= 21
            ? MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV420Flexible
            : MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV420SemiPlanar;
      case YUV420PACKEDPLANAR:
        return Build.VERSION.SDK_INT >= 21
            ? MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV420Flexible
            : MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV420PackedPlanar;
      case YUV420PACKEDSEMIPLANAR:
        return Build.VERSION.SDK_INT >= 21
            ? MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV420Flexible
            : MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV420PackedSemiPlanar;
      case YUV422FLEXIBLE:
        return MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV422Flexible;
      case YUV422PLANAR:
        return Build.VERSION.SDK_INT >= 23
            ? MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV422Flexible
            : MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV422Planar;
      case YUV422SEMIPLANAR:
        return Build.VERSION.SDK_INT >= 23
            ? MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV422Flexible
            : MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV422SemiPlanar;
      case YUV422PACKEDPLANAR:
        return Build.VERSION.SDK_INT >= 23
            ? MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV422Flexible
            : MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV422PackedPlanar;
      case YUV422PACKEDSEMIPLANAR:
        return Build.VERSION.SDK_INT >= 23
            ? MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV422Flexible
            : MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV422PackedSemiPlanar;
      case YUV444FLEXIBLE:
        return MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV444Flexible;
      case YUV444INTERLEAVED:
        return MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV444Interleaved;
      case SURFACE:
        return MediaCodecInfo.CodecCapabilities.COLOR_FormatSurface;
      default:
        return -1;
    }
  }
```

**Comment by banggaoo** [comment]
We really appreciate with your reply.

We replace getFormatCodec() method as you provide but the problem is occur same as. Also we try to set FormatCodec to Flexible already but there is no difference.

We already test with Galaxy S8 and Galaxy Note 9 but these devices work fine with no color issue. Also we tested various device with rtmp-rtsp-stream-client-java but only Galaxy S9 occur problem.

And it is hard to change viewer-side because we service our live service with various platform like iOS, PC web. and one of the problem is that auto-creating thumbnail feature provided Wowza also has a color issue.

We still suspicious the color format setting is reason of this problem. And we guessing because GoCoder restrict API level to 23. 

If you have any idea please comment then we will follow up.

**Comment by pedroSG94** [comment]
You dont need change viewer side. Only change xml to use LightOpenGlView or OpenGlView (depend if you want use filters or not).
Replace:
```xml
    <SurfaceView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/surfaceView"
        />
```
To:
```xml
  <com.pedro.rtplibrary.view.OpenGlView
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      android:id="@+id/surfaceView"
      />
```
With this you skip color converter and should work in all devices.

**Comment by banggaoo** [comment]
We tested streaming using OpenGlView/LightOpenGlView but unfortunately there is no difference with.

**Comment by pedroSG94** [comment]
This is so rare with OpenGlView you are not using color conversion because you encode directly from Surface. Remember that you need in the code cast your view to OpenGlView not to SurfaceView or you are not doing anything.
```java
SurfaceView surfaceView = findViewById(R.id.surfaceView);
//To
OpenGlView openGlView = findViewById(R.id.surfaceView);
```
Also I need confirm this:

In streamer side, is preview working fine?

Can you test with my app example?
Use OpenGl RTMP and Surfacemode RTMP.
I need discard encoder problems.

**Comment by banggaoo** [comment]
We encounter problem while applying OpenGlView. We will inform when we fix this problem.

The app crashed when we start Streaming engine. This is error log.

{{E/libEGL: eglCreateWindowSurface: native_window_api_connect (win=0xb07bc808) failed (0xffffffea) (already connected to another API?)
eglCreateWindowSurface:481 error 3003 (EGL_BAD_ALLOC)}}
{{ --------- beginning of crash}}
{{03-21 16:04:38.452 22979-24447/com.android.sample E/AndroidRuntime: FATAL EXCEPTION: Thread-11
Process: com.ikala.shoplus.staging, PID: 22979}}
{{ java.lang.RuntimeException: eglCreateWindowSurface: EGL error: 0x3003
at com.pedro.encoder.utils.gl.GlUtil.checkEglError(GlUtil.java:131)
at com.pedro.encoder.input.gl.SurfaceManager.eglSetup(SurfaceManager.java:146)
at }}
{{com.pedro.encoder.input.gl.SurfaceManager.<init>(SurfaceManager.java:54)
at com.pedro.rtplibrary.view.OpenGlView.run(OpenGlView.java:151)
at }}
java.lang.Thread.run(Thread.java:761)
{{}}

**Comment by banggaoo** [comment]
We solve encoder problem by changing OpenGlView. Thanks for your support :)

**Comment by pedroSG94** [comment]
Can you share code fix?

**Comment by kndol2** [comment]
I change xml to use OpenGlView.

The problem occurred because I removed stopPreview() in prepareVideo() method.
Everything works fine when I modify it.
<img width="917" alt="2018-10-29 6 07 56" src="https://user-images.githubusercontent.com/33836986/47639875-a3dc2300-dba5-11e8-98ba-47471f3d2272.png">

Or it works fine when I remove some code in prepareGlView() method.
<img width="804" alt="2018-10-29 6 05 57" src="https://user-images.githubusercontent.com/33836986/47639914-b5252f80-dba5-11e8-93e8-3d53bb32b1e9.png">
