### ISSUE TITLE
[Question] How to get ammount of packets sent to be shown on UI?

### ISSUE THREAD

**Issue by andrewBatutin** [pedroSG94/rtmp-rtsp-stream-client-java#239]
At log i can see 

> wrote packet: RTMP Video, size: 1818

is there any way to get this info to be shown on UI?

is there any sort of callback to get that?

thnx

**Comment by pedroSG94** [comment]
Yes, this should be easy (Rtmp).

1 - Write your callback method here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/net/ossrs/rtmp/ConnectCheckerRtmp.java
```java
void myCallbackInfo(int length);
```
2 - Go to log info class:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L496
3 - Add callback to this method:
```java
if (rtmpPacket instanceof Video) {
connectCheckerRtmp.myCallbackInfo(rtmpPacket.getHeader().getPacketLength());
}
```
4 - Implement callback to activity.

**Comment by andrewBatutin** [comment]
thnx
