### ISSUE TITLE
SoftCoding supported

### ISSUE THREAD

**Issue by AliceDinh** [pedroSG94/rtmp-rtsp-stream-client-java#24]
I want to integrate the soft coding H264 or H265, that would be the first step to start, please advise. Thanks

**Comment by pedroSG94** [comment]
If you want do soft encoding you need know it.
RTMP can't use H265 because FLV packets have not standard but you can add it to RTSP because RTP packets have it:

https://tools.ietf.org/html/draft-ietf-payload-rtp-h265-14#section-4.4.1

**Comment by AliceDinh** [comment]
Yes, I am trying with softCoding H264 first, but got trouble with the input for encoder. In particular, with hard coding, the input raw data (YV12 and NV12, will be converted to I420), but I did try to do the same with soft coding without success. Can you have a look to my code and give me some comments please:

> This is prepareVideoEncoder() function

`public boolean prepareVideoEncoder(int width, int height, int fps, int bitRate, int rotation,
                                     boolean hardwareRotation, FormatVideoEncoder formatVideoEncoder) {
    this.width = width;
    this.height = height;
    this.fps = fps;
    this.bitRate = bitRate;
    this.rotation = rotation;
    this.hardwareRotation = hardwareRotation;
    this.formatVideoEncoder = formatVideoEncoder;
    MediaCodecInfo encoder;
    if (Build.VERSION.SDK_INT >= 21) {
      encoder = chooseVideoEncoderAPI21(mime);
    } else {
      encoder = chooseVideoEncoder(mime);
    }

    if (useSoftEncoder) {
      canSoftEncode = openSoftEncoder();
      if (!canSoftEncode) {
        return false;
      }
    }
    
    try {
      if (encoder != null) {
        videoEncoder = MediaCodec.createByCodecName(encoder.getName());
        if (this.formatVideoEncoder == FormatVideoEncoder.YUV420Dynamical) {
          this.formatVideoEncoder = chooseColorDynamically(encoder);
          if (this.formatVideoEncoder == null) {
            Log.e(TAG, "YUV420 dynamical choose failed");
            return false;
          }
        }
      } else {
        Log.e(TAG, "valid encoder not found");
        return false;
      }
      MediaFormat videoFormat;
      //if you dont use mediacodec rotation you need swap width and height in rotation 90 or 270
      // for correct encoding resolution
      if (!hardwareRotation && (rotation == 90 || rotation == 270)) {
        videoFormat = MediaFormat.createVideoFormat(mime, height, width);
      } else {
        videoFormat = MediaFormat.createVideoFormat(mime, width, height);
      }
      videoFormat.setInteger(MediaFormat.KEY_COLOR_FORMAT,
              this.formatVideoEncoder.getFormatCodec());
      videoFormat.setInteger(MediaFormat.KEY_MAX_INPUT_SIZE, 0);
      videoFormat.setInteger(MediaFormat.KEY_BIT_RATE, bitRate);
      videoFormat.setInteger(MediaFormat.KEY_FRAME_RATE, fps);
      videoFormat.setInteger(MediaFormat.KEY_I_FRAME_INTERVAL, 2);
      if (hardwareRotation) {
        videoFormat.setInteger("rotation-degrees", rotation);
      }
      videoEncoder.configure(videoFormat, null, null, MediaCodec.CONFIGURE_FLAG_ENCODE);
      running = false;
      if (formatVideoEncoder == FormatVideoEncoder.SURFACE
              && Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR2) {
        inputSurface = videoEncoder.createInputSurface();
      }
      prepareBlackImage();
      return true;
    } catch (IOException e) {
      Log.e(TAG, "create videoEncoder failed.");
      e.printStackTrace();
      return false;
    } catch (IllegalStateException e) {
      e.printStackTrace();
      return false;
    }
  }`

> This is the start() function:
`private boolean useSoftEncoder = false;
  private boolean canSoftEncode = false;
  public void start() {
    spsPpsSetted = false;
    mPresentTimeUs = System.nanoTime() / 1000;
    videoEncoder.start();
    //surface to buffer

    if (formatVideoEncoder == FormatVideoEncoder.SURFACE
            && Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR2) {
      thread = new Thread(new Runnable() {
        @Override
        public void run() {
          Process.setThreadPriority(Process.THREAD_PRIORITY_MORE_FAVORABLE);
          while (!Thread.interrupted()) {
            try {
              byte[] b = queue.take();
              long pts = System.nanoTime() / 1000 - mPresentTimeUs;
              if (b == null) continue;
              if (useSoftEncoder) {
                swRgbaFrame(b, width, height, pts);
              } else {
                if (Build.VERSION.SDK_INT >= 21) {
                  getDataFromSurfaceAPI21();
                } else {
                  getDataFromSurface();
                }
              }

            } catch (InterruptedException e) {
              thread.interrupt();
            }
          }
        }
      });
      thread.start();
      //buffer to buffer
    } else {
      thread = new Thread(new Runnable() {
        @Override
        public void run() {
          Process.setThreadPriority(Process.THREAD_PRIORITY_MORE_FAVORABLE);
          while (!Thread.interrupted()) {
            try {
              byte[] b = queue.take();
              byte[] i420;
              long pts = System.nanoTime() / 1000 - mPresentTimeUs;
              if (b == null) continue;
              if (useSoftEncoder) {
                swYuvFrame(b, width, height, pts);
              } else {
                if (imageFormat == ImageFormat.NV21) {
                  if (!hardwareRotation) {
                    if (rotation == 0 || rotation == 90 || rotation == 180 || rotation == 270) {
                      b = YUVUtil.rotateNV21(b, width, height, rotation);
                    } else {
                      throw new RuntimeException(
                              "rotation value unsupported, select value 0, 90, 180 or 270");
                    }
                  }
                  i420 = (sendBlackImage) ? blackImage
                          : YUVUtil.NV21toYUV420byColor(b, width, height, formatVideoEncoder);
                } else if (imageFormat == ImageFormat.YV12) {
                  i420 = (sendBlackImage) ? blackImage
                          : YUVUtil.YV12toYUV420byColor(b, width, height, formatVideoEncoder);
                } else {
                  stop();
                  Log.e(TAG, "Unsupported imageFormat");
                  break;
                }
                if (Build.VERSION.SDK_INT >= 21) {
                  getDataFromEncoderAPI21(i420);
                } else {
                  getDataFromEncoder(i420);
                }
              }
            } catch (InterruptedException e) {
              thread.interrupt();
            }
          }
        }
      });
      thread.start();
    }
    running = true;
  }`
 
`private void swRgbaFrame(byte[] data, int width, int height, long pts) {
    RGBASoftEncode(data, width, height, true, 180, pts);
  }
  private void swYuvFrame(byte[] data, int width, int height, long pts) {
    NV21SoftEncode(data, width, height, true, 180, pts);
  }`
`static jint libenc_RGBASoftEncode(JNIEnv *env, jobject thiz, jbyteArray frame, jint src_width,
                                  jint src_height, jboolean need_flip, jint rotate_degree,
                                  jlong pts) {
    jbyte *rgba_frame = env->GetByteArrayElements(frame, NULL);

    if (!convert_to_i420((uint8_t *) rgba_frame, src_width, src_height, need_flip, rotate_degree,
                         FOURCC_RGBA)) {
        return JNI_ERR;
    }

    int es_len = x264_ctx.global_nal_header ? encode_global_nal_header() : x264_encode(
            &i420_scaled_frame, pts);
    if (es_len <= 0) {
        LIBENC_LOGE("Fail to encode nalu");
        return JNI_ERR;
    }

    jbyteArray outputFrame = env->NewByteArray(es_len);
    env->SetByteArrayRegion(outputFrame, 0, es_len, (jbyte *) h264_es);

    jclass clz = env->GetObjectClass(thiz);
    jmethodID mid = env->GetMethodID(clz, "onSoftEncodedRGBAData", "([BJZ)V");
    env->CallVoidMethod(thiz, mid, outputFrame, x264_ctx.pts, x264_ctx.is_key_frame);

    env->ReleaseByteArrayElements(frame, rgba_frame, JNI_ABORT);
    return JNI_OK;
}
static jint libenc_NV21SoftEncode(JNIEnv *env, jobject thiz, jbyteArray frame, jint src_width,
                                  jint src_height, jboolean need_flip, jint rotate_degree,
                                  jlong pts) {
    jbyte *nv21_frame = env->GetByteArrayElements(frame, NULL);

    if (!convert_to_i420((uint8_t *) nv21_frame, src_width, src_height, need_flip, rotate_degree,
                         FOURCC_NV21)) {
        return JNI_ERR;
    }

    int es_len = x264_ctx.global_nal_header ? encode_global_nal_header() : x264_encode(
            &i420_scaled_frame, pts);
    if (es_len <= 0) {
        LIBENC_LOGE("Fail to encode nalu");
        return JNI_ERR;
    }

    jbyteArray outputFrame = env->NewByteArray(es_len);
    env->SetByteArrayRegion(outputFrame, 0, es_len, (jbyte *) h264_es);

    jclass clz = env->GetObjectClass(thiz);
    jmethodID mid = env->GetMethodID(clz, "onSoftEncodedNV21Data", "([BJZ)V");
    env->CallVoidMethod(thiz, mid, outputFrame, x264_ctx.pts, x264_ctx.is_key_frame);

    env->ReleaseByteArrayElements(frame, nv21_frame, JNI_ABORT);
    return JNI_OK;
}`

**Comment by AliceDinh** [comment]
Sorry if the codes are not shaped properly, I put them into code blocks but don't know why the format is not proper

**Comment by pedroSG94** [comment]
I need more information to know where is the problem, but for know, I don't understand where is the byte[] result because you never return anything in C code.

`swYuvFrame(b, width, height, pts);`

Should return byte[], I think
