### ISSUE TITLE
setZoom not found in sample app

### ISSUE THREAD

**Issue by ToysoftInc** [pedroSG94/rtmp-rtsp-stream-client-java#240]
setZoom is not found from the sample app in RtmpActivity.class

I'm using 

  compile 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:1.4.2'

**Comment by pedroSG94** [comment]
Are you using gradle to compile library?. That mehtod is not added in last gradle version. I will update it tomorrow

**Comment by ToysoftInc** [comment]
did you get a chance to update the gradle version yet? thanks

**Comment by pedroSG94** [comment]
Updated
