### ISSUE TITLE
Can't compile OpenGlRtmpActivity

### ISSUE THREAD

**Issue by ToysoftInc** [pedroSG94/rtmp-rtsp-stream-client-java#241]
compile 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:1.4.2'

**OpenGlRtmpActivity.class**
  
private SpriteGestureController spriteGestureController = new SpriteGestureController();

**SpriteGestureController.class**

    public SpriteGestureController(Sprite sprite, SpriteGestureController.UpdateGestureCallback updateGestureCallback) 

There are other errors in the gl sample class too.

am I missing something?

**Comment by pedroSG94** [comment]
Same response that the other post:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/240
