### ISSUE TITLE
[Question]How to get current codec profile and level?

### ISSUE THREAD

**Issue by andrewBatutin** [pedroSG94/rtmp-rtsp-stream-client-java#245]
Hi
From VideoEncoder i can get MediaCodec and see all supported codec profiles and levels.

But how i can get info about profile that is actually used for video encoding?

Thnx!

**Comment by pedroSG94** [comment]
VideoEncoder profile should be always baseline. At least in my devices.
I don't know level used by default but you can specify it with this:
https://developer.android.com/reference/android/media/MediaFormat#KEY_LEVEL

**Comment by andrewBatutin** [comment]
i've ended up parsing sps unit from the stream
