### ISSUE TITLE
Problem with size of image (ImageObjectFilterRender)

### ISSUE THREAD

**Issue by miwaniec** [pedroSG94/rtmp-rtsp-stream-client-java#246]
Hi, 
I am trying to add image with ImageObjectFilterRender, but image in result is too big. I don't know how to set scale.

I prepared video with HD resolution:
`rtmpCamera1.prepareVideo(1280, 720, 30, 1228800, false, 0)`

Next, put sample image (original size 540x210, png format) with ImageObjectFilterRender (like in example with opnegl):
`ImageObjectFilterRender imageObjectFilterRender = new ImageObjectFilterRender();
 rtmpCamera1.getGlInterface().setFilter(imageObjectFilterRender);
imageObjectFilterRender.setImage(BitmapFactory.decodeResource(getResources(), R.mipmap.test));
imageObjectFilterRender.setDefaultScale(rtmpCamera1.getStreamWidth(), rtmpCamera1.getStreamHeight());
imageObjectFilterRender.setPosition(TranslateTo.TOP_LEFT);`

And the result is something like that:
![device-2018-10-26-162216](https://user-images.githubusercontent.com/1790724/47573083-bacc0c80-d93c-11e8-8da9-89318c2c2718.png)

How it is possible? Video width is 1280, so image should put up in half of width.
What is wrong with code or scale?

Orginal image:
![test](https://user-images.githubusercontent.com/1790724/47573288-3f1e8f80-d93d-11e8-95b4-aed19f38fa86.png)

Thanks for the great library!

**Comment by pedroSG94** [comment]
Code look correct. I will tests it. For now, you can try set size with seScale in percent like here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L242
In your case:
```java
float width = 540 * 100 / 1280;
float height= 210 * 100 / 720;
```

**Comment by miwaniec** [comment]
Great! It now works correctly.
