### ISSUE TITLE
Bitrate Mode Encoder

### ISSUE THREAD

**Issue by mhackeras** [pedroSG94/rtmp-rtsp-stream-client-java#248]
Hi Pedro Again :D 
Well of course i keep playing with settings to make a more better streaming code..
I would like to ask you..
is there a way to know the bitrate mode that video encoder uses?
Cause i think its vbr and it lets more bitrates sometimes to be encoded.
i tried this peace of code
videoFormat.setInteger(MediaFormat.KEY_BITRATE_MODE,2);
where 2 is the constant value for CBR bitrate mode that is most used for streaming on youtube twitch etc.
and it seems to be working. I mean it keeps bitrate lower than set.. never send more.

**Comment by pedroSG94** [comment]
I don't know bitrate mode used by default. (It is not documented by Google)
For this reason, I think bitrate mode used by default depend of your CPU.
You can get modes supported by your CPU and use it by your preferences with this:
https://developer.android.com/reference/android/media/MediaCodecInfo.EncoderCapabilities#isBitrateModeSupported(int)

**Comment by mhackeras** [comment]
OK nice!
Will check when at home and will post back

**Comment by mhackeras** [comment]
it seems to be a good import using cbr - constant bitrate cause it keeps quality of video and doesnt allow burst of video bitrates.
On the other side if phone uses vbr as default.. is bad for streaming cause even if bitrates are set to 4000KB for instance.. when moving it may burst up to 8000kb for instance.
Though it is supported on android 21+

**Comment by mhackeras** [comment]
Also KEY_CAPTURE_RATE seems to make encode working better.

**Comment by mhackeras** [comment]
Also pedro if you could point me on how to try record on nv and not yuv would be nice :)
DisplayRtmp.

**Comment by pedroSG94** [comment]
Yes, maybe a good solution is add other param to prepareVideo method to add custom configuration to encoder.

**Comment by mhackeras** [comment]
i already added a check if cbr is supported and use it in video encoder.
