### ISSUE TITLE
Camera id always set to 1 on Raspberry Pi

### ISSUE THREAD

**Issue by Alex0jk** [pedroSG94/rtmp-rtsp-stream-client-java#260]
Hi,
So,some friends and I decided to test the code in Android Things and it worked great except for a small issue. For some reason it always tries to set the Camera Id to 1, even if i try to change the configuration at the start. 
The camera in my Raspberry Pi, is identified with id 0, that prevented me from achieving the stream. I had to force in code for the id to be 0, ignoring the functions for id set up or change, for the camera to work.
Maybe I am missing something.
Thanks.

**Comment by pedroSG94** [comment]
Asuming that you are using camera1. 
The reason of this is that I'm getting both cameras resolutions on init method. I will try fix it. 
For now, try:
- Set final to cameraSelect and initialize to 0:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java#L37
- Now delete all lines that change value of cameraSelect.

With this you are 100% sure that camera opened is always id 0.

**Comment by pedroSG94** [comment]
Can you tell me SO used on raspberry to reproduce error?
A link to download or something.

**Comment by Alex0jk** [comment]
Sorry I didn't mention it, but I was using camera2. I don't know if the solution is the same.
I was using Android Things version 1.0.5 with Android version 8.1.0. 
I used Android Things Setup Utility for the installation and setup process:[https://partner.android.com/things/console/?pli=1#/tools](url)

**Comment by pedroSG94** [comment]
In this case go to camera2Base and replace this 3 lines:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera2Base.java#L300
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera2Base.java#L377
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera2Base.java#L379
To:
```java
cameraManager.openCameraId(0);
```

**Comment by Alex0jk** [comment]
Yes, that works great, thanks.

Another way that I used to fix the problem was changing this lines:
[https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/75ba67b5ae3a1e9f95d505a24f90c708344ef967/encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java#L252](url)
To:
`openCameraId(0);`

I wast just wondering if there is a way to set the camera id without having to change your code, so I could use your library without having to download the code.

**Comment by pedroSG94** [comment]
Try your solution but replace line to this:
```
openCameraId(cameraManager.getCameraIdList().length - 1);
```
It is to discard problems with device with only 1 camera.
