### ISSUE TITLE
OpenGlViewBase.stop() takes 1 second to finish

### ISSUE THREAD

**Issue by andrewBatutin** [pedroSG94/rtmp-rtsp-stream-client-java#265]
Hi

I've profiled the app and have noticed that OpenGlViewBase.stop() takes 1 second to finish

`  public void stop() {
        Object var1 = this.sync;
        synchronized(this.sync) {
            if (this.thread != null) {
                this.thread.interrupt();

                try {
                    this.thread.join(1000L);
                } catch (InterruptedException var4) {
                    this.thread.interrupt();
                }

                this.thread = null;
            }

            this.running = false;
            this.rotation = 0;
        }
    }`

Looks like we always wait for 1 sec to join threads but then proceed with InterruptedException 
Can we make a delay smaller? like 0.1 second? 

Also why do we need thread sync at this method in general?

Thnx for your work!

**Comment by pedroSG94** [comment]
Yes I can do a smaller delay it is only to make sure that all is correctly closed but normally you are not waiting 1s to stop thread.
I use join to wait release opengl renders and make sure that you can correctly re start thread immediately without problems.

Maybe it is not the best way and I should use AtomicBoolean?
