### ISSUE TITLE
Preview/Streaming is rotated upside down on Nexus 6P

### ISSUE THREAD

**Issue by mmaschenko** [pedroSG94/rtmp-rtsp-stream-client-java#266]
I have found that specifically on Nexus 6P camera is rotated upside down for some reason.

**Comment by pedroSG94** [comment]
- In portrait or lanscape? 
- Front or back camera?
- Which view are you using? SurfaceView, TextureView, LightOpenGlView or OpenGlView?

**Comment by mmaschenko** [comment]
OpenGlView, front and back camera, portrait/landscape, livestream/preview

**Comment by pedroSG94** [comment]
If this is only with nexus 6P you can do it in onCreate method:
```java
if (is6p) {
    openGlView.setCameraFlip(false, true);
}
```

**Comment by paNjii** [comment]
I would like to add that with the Nexus 5X we experience the same behavior. As far as I have been able to tell, this is in the preview only, using a SurfaceView.

**Comment by pedroSG94** [comment]
Try use openglview with camera1 and camera2 and use setCameraFlip. Other way could be change rotate in prepareVideo method only with nexus 5x and with camera2.
I had a nexus 5x years ago and I know that camera is rotated for some reason(I think this is a hardware problem). Unfortunately I haven't this device anymore so I can't find a valid solution to work with all devices (Maybe it is not possible with surfaceview).
If the problem persist the only way is develop a method to rotate only preview with openglview and lightopenglview.

**Comment by paNjii** [comment]
Thanks for the quick reply. I followed your advice and changed my standard surface view to the OpenGLView. I then check for the model type and apply the vertical flip if necessary. Am I correct in that this is necessary? Or should it work out of the box with the OpenGL View. As a note, I am using RtmpCamera1 for compatibility reasons.

**Comment by paNjii** [comment]
Also, I don't know how much the emulator differs. But I use a 5X image in the emulator and the preview there is fine. So probably hardware issue?
