### ISSUE TITLE
Missing fps cause of fps limiter

### ISSUE THREAD

**Issue by mhackeras** [pedroSG94/rtmp-rtsp-stream-client-java#267]
Video loses 2-3 fps cause of fps limiter on OffScreenGlThread. By removing it got smoother video and more fps.
We had added it because of audio out of sync. Gonna test more on this.
Also this may cause the laggy sound when streaming. I am gonna test record and stream.

**Comment by mhackeras** [comment]
Ok its better to use fpslimiter only on OffScreenGlThread and none in video encoder. It doesnt need two limiters.
Fps are back. Though if we could use limiter only on video encoder would be better. But audio is out of sync.

**Comment by mhackeras** [comment]
It's with display. But I ll check others too!
I tried a lot of configs. When on 30fps I get audio out of sync. 
I tried all resolutions and several fps settings.
Audio too.

**Comment by mhackeras** [comment]
And something that i remembered pedro.. is that with limiter are we sure that key frames are passed as it should ? cause in resulted video i can see lag.. maybe it misses key frame or something like that and cause the lag.

**Comment by mhackeras** [comment]
change limitfps to this and out of sync audio is fixed. No need to use limiter on GlThreads.
Tested on Offscreenglthread with DisplayBase recording
public boolean limitFPS(int fps) {
    if (System.currentTimeMillis() - lastFrameTimestamp < 1000 / fps) {
      lastFrameTimestamp = System.currentTimeMillis();
      return true;
    }
    return false;
  }
}

**Comment by pedroSG94** [comment]
Tested and not working. If you set 5fps and test with camera1 or camera in
openglview it isn't working.

**Comment by mhackeras** [comment]
Yeah that's why I had this removed.
