### ISSUE TITLE
[Question] Toggle flash

### ISSUE THREAD

**Issue by tplloi** [pedroSG94/rtmp-rtsp-stream-client-java#269]
Dear @pedroSG94 .
Im using your great library v1.4.8 in my project.
I found 2 funcs enableLantern() and disableLantern() in this [class](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java#L374)
Can you add some funcs in [Camera1Base](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java) like enableLantern(), disableLantern() then publish with new release v1.4.9, it will help me iplm the flash toggle feature without edit any codes of you?
Thanks a ton.

**Comment by pedroSG94** [comment]
Commited and uploaded.
8aea9c88c902130fc0c550f6d6edb56fcac09f42

**Comment by tplloi** [comment]
Thanks you very much @pedroSG94
