### ISSUE TITLE
it is work on the web camera?

### ISSUE THREAD

**Issue by hug2008** [pedroSG94/rtmp-rtsp-stream-client-java#270]
the android web camera has not display screen, the app work？

**Comment by pedroSG94** [comment]
If you means connect an external camera to your phone. No this feature is not implemented.
If your device is an Android device. This library was tested and work with rasberry pi using Android things.
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/260

**Comment by hug2008** [comment]
my device is android Mobile phone module whithout lcd

**Comment by pedroSG94** [comment]
I think this should work but the best solution is test yourself and open an issue if you have any problems.
I recomend you use background stream mode if you haven't preview.
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtmp/RtmpCamera1.java#L50

**Comment by hug2008** [comment]
OK
