### ISSUE TITLE
[Question]How to record a video as a file  while streaming？

### ISSUE THREAD

**Issue by Ashion-AS** [pedroSG94/rtmp-rtsp-stream-client-java#271]

**Comment by pedroSG94** [comment]
You have an example code in app module. For example this activity:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/defaultexample/ExampleRtmpActivity.java#L137

If you are using other mode you can see other activtity but all activities are using a code really similar.
