### ISSUE TITLE
Recording flv file or streaming to local UDP port

### ISSUE THREAD

**Issue by EitanGoldfrad** [pedroSG94/rtmp-rtsp-stream-client-java#274]
Hi Pedro,

Is it possible to use the muxer to capture a local flv file?

Also is it possible to stream video to a local udp port (e.g udp://127.0.0.1:12345) ?

Thanks!

**Comment by pedroSG94** [comment]
You can't record flv file with mediamuxer. You can see format supported here(remember that you need encode with a codec supported by that format):
https://developer.android.com/reference/android/media/MediaMuxer.OutputFormat

The second question. I think that you want use this library like an IP camera without media server but this library only support stream to media server.

**Comment by pedroSG94** [comment]
I don't know how to record in flv format. :(

**Comment by EitanGoldfrad** [comment]
No worries, we found a different solution

**Comment by troy-lamerton** [comment]
@EitanGoldfrad how did you manage to do local recording flv?

The [SrsFlvMuxer.java](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/net/ossrs/rtmp/SrsFlvMuxer.java#L48) in this project is not doing what I expect.

**Comment by EitanGoldfrad** [comment]
@troy-lamerton I think I used a mpeg-ts muxer

**Comment by icewst** [comment]
> mpeg-ts muxer

Please，how did you manage to do local recording flv?
