### ISSUE TITLE
PCMU Audio

### ISSUE THREAD

**Issue by VasanthNeel** [pedroSG94/rtmp-rtsp-stream-client-java#276]
In Android, Is it possible to stream H.264 video and do a software level encoding of raw pcm to pcmu (not AAC) and publish the streams using this library?
if so any advice for me to make those changes in this library. i really appreciate it.

**Comment by pedroSG94** [comment]
Yes, it is possible. RTP and FLV support G711 packetization (PCMU).
If you want do it you need create a packetizer for rtmp or rtsp (depend protocol that you need) and create an audio encoder for pcmu.
Classes that you need change:
- Audio encoder:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/audio/AudioEncoder.java
- Rtmp packetizer:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/net/ossrs/rtmp/SrsFlvMuxer.java
- Rtsp packetizer:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtsp/src/main/java/com/pedro/rtsp/rtp/packets/AacPacket.java

Also you will need change server negotiation to notify thta you will use PCMU.
-RTMP:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java
-RTSP:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtsp/src/main/java/com/pedro/rtsp/rtsp/RtspClient.java#L323

Usefull documentation for rtp packetization:
https://tools.ietf.org/html/rfc7655
https://tools.ietf.org/html/rfc5391
