### ISSUE TITLE
Problem with OpenGl FilterRender in some devices

### ISSUE THREAD

**Issue by miwaniec** [pedroSG94/rtmp-rtsp-stream-client-java#278]
Hi,
I used Image and Text ObjectFilterRender to add extra information to video. It works great, but some users give me a notice that it doesn't work for them. Image and text disappear when they start record/stream.
I got a real device and tested it. I can't find anything useful in logs. It looks exactly the same, as logs from another device, where it works (`I/ImageStreamObject: finish load image`).
I notice that it doesn't work in your test app too. Doesn't work on devices:
Huawei P10 VTR-L29, Samsung Galaxy S7 SM-G930F.

How I tested:
A.
1. Open OpenGl RTMP
2. Click Filters -> Image or Text
3. Image/text is visible.
4. Click Start record or Start stream
5. Image/text disappears
6. Try add again, nothing display (image/text)

B.
1. Open OpenGl RTMP
2. Click Start record or Start stream
3. Click Filters -> Image or Text
4. Image/text is visible.
5. Click stop.
6. Click start.
7. Image/text disappears

Other filters (eg Color) works all time.

Maybe it will be helpful (diffrent camera service):
For Huawei:
`I/Camera2ClientBase: Camera 0: Opened. Client: com.pedro.rtpstreamer (PID 20717, UID 10163)`
For Xiaomi:
`I/CameraService: CameraService::connect call (PID -1 "com.pedro.rtpstreamer", camera ID 0)`

**Comment by pedroSG94** [comment]
Yes, you are right but this error was fixed here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/0ab882ad6fd590319b190f526b0ec3365ce11c8e
Filter still disappear when start record or stream but now you can reload filter correctly.
It is not added to 1.4.9 version I will upgrade it now.

**Comment by pedroSG94** [comment]
Updated:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/81b891b29f479d55cf3817360626dd6a0090706c

**Comment by miwaniec** [comment]
Thank you. Works great.
Amazing support!
