### ISSUE TITLE
Fix for Flashlight

### ISSUE THREAD

**Issue by moster67** [pedroSG94/rtmp-rtsp-stream-client-java#28]
In the enableLantern() method of the Camera1ApiManager.class, the following statement should be added:

> lanternEnable = true;

otherwise lanternEnable will always be false.

**Comment by pedroSG94** [comment]
Fixed in:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/be8cf1ab3ea5c00dede9560e248efddbb719ec75

Thank you!
