### ISSUE TITLE
Consuming rtsp stream

### ISSUE THREAD

**Issue by MohammadFneish7** [pedroSG94/rtmp-rtsp-stream-client-java#281]
I'd searched the repository for if it supports consuming external rtsp stream (like this **`rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov`**) into a buffer or displaying it into a surfaceview or a textureview, but i didn't find if it is possible. Any help would be highly appreciated.

Thanks!!

**Comment by pedroSG94** [comment]
You can't do it with this library. This library is for push stream.
You need a player like VLC:
https://github.com/pedroSG94/vlc-example-streamplayer

**Comment by MohammadFneish7** [comment]
@pedroSG94 thanks for your reply. I'm currently using VLC to consume the rtsp stream and render it into a textureview and it is working perfectly. Here, i need to continuously get the current frame to preform real time processing with the frame, however i have a big problem here where since vlc preforms hardware decoding and rendering, the only way to get the current frame from the textureView is through textureView.getBitmap() function. The issue is that this function is too slow (For example, getting 1080*720 takes about 2000ms!! this prevents me from making a real time processing with the results. please check [my question here](https://stackoverflow.com/questions/53988652/is-there-any-fast-alternatives-for-textureview-getbitmap-function) for more info:

Because of that, i started searching for lower level alternatives, any help or hint would be appreciated. Thanks in advance.

**Comment by pedroSG94** [comment]
In this case you can replace textureView.getBitmap() with OpenGl.
The idea is similar to this view:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/view/OpenGlView.java
Basically you can replace Camera2Manager with VLC and get similar result (So you can use this library with VLC video input).
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera2Base.java
As you can see in this view you can get a photo:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/view/OpenGlView.java#L123

The idea is:
- Create a SurfaceTexture with OpenGl.
-  Set this texture to VLC that will render it.
- Optionally you can apply image processing with OpenGl.
- If you need preview you should copy VLC input to a view (See OpenGlView).
- Get output result with GlReadPixel method of OpenGl (you are getting a argb buffer).
- Convert RGB buffer to Bitmap.

With this way you can get around 15-20 FPS in 1920x1080 but it is difficult to develop if you don't know OpenGl.

**Comment by MohammadFneish7** [comment]
To be honest i think i will have a long term work and research to do it successfully, especially that i know nothing about working with OpenGL. Anyway, thanks for your great answer, i will try to benefit the most from it. Best regards ♥️
