### ISSUE TITLE
How to scale and/or align just the camera preview window?

### ISSUE THREAD

**Issue by function1983** [pedroSG94/rtmp-rtsp-stream-client-java#283]
Hi, I spent a day digging through your code without luck.

I use OpenGlRtmpActivity and try to scale the camera windows, then align it to the top right.
- When I set scale to the CameraRender, it scales but I cannot align it. Also, as soon as I hit start stream, the camera window comes back to full screen
- Then I tried another approach and set pivotX, pivotY, setScaleX, setScaleY, then the scaling and positioning effects only shown my view on the streaming device but not on the viewer's device (still full screen).

What should I try next?

**Comment by pedroSG94** [comment]
I can modify this class if you are using OpenGlView:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/gl/render/ScreenRender.java#L79
Or this class if you are using LightOpenGlView:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/gl/render/SimpleCameraRender.java#L88

In both cases you should modify GLES20.glViewport method where you can select scale and where do you want to start and end draw. example:
```java
//GLES20.glViewport(xPixelStart, yPixelStart, xPixelEnd, yPixelEnd);
GLES20.glViewport(0, 0, width, height);
```

**Comment by function1983** [comment]
Thank you for your quick feedback. I will test this soon.

**Comment by function1983** [comment]
Hi Pedro,
Thank you for your suggestion. Sadly, `GLES20.glViewport(0, 0, width, height);` is for cropping the outter OpenGlView.
I am trying to scale+reposition only the **Camera view** inside OpenGlView, I need to keep OpenGlView and other views intact.
