### ISSUE TITLE
only audio stream

### ISSUE THREAD

**Issue by abdulla1992** [pedroSG94/rtmp-rtsp-stream-client-java#285]
can you please give an example for only audio stram?thank you

**Comment by pedroSG94** [comment]
The code is similar in all modes. In this case you only need prepareAudio
```java
//initialize stream object
RtmpOnlyAudio rtmp = new RtmpOnlyAudio();
// start stream
if (rtmp.prepareAudio()) {
  //You can check if streaming is already started with rtmp.isStreaming();
  rtmp.startStream(enpoint);
}
//stop stream
rtmp.stopStream();
```
If you want RTSP replace RtmpOnlyAudio to RtspOnlyAudio. I will add activities example but with this should work. Let me know if you have any problem.

**Comment by abdulla1992** [comment]
thank you very much ,the library is very useful, i use RtspOnlyAudio , here is my code:
RtspOnlyAudio rtsp = new RtspOnlyAudio(MainActicity.this);

private void startAudio(String url) {
        if (rtspOnlyAudio != null && !rtspOnlyAudio.isStreaming()) {
            if (rtspOnlyAudio.prepareAudio()) {
                rtspOnlyAudio.startStream(url);
            }
        }
    }
 and another one problem is , when the network state changed,the rtspaudionly disconnected and it cant auto reconnected. i already listen the network state on my activity .how can i do to reconnect after network available ?

**Comment by pedroSG94** [comment]
If you want reconnect you should stop and start stream.

**Comment by abdulla1992** [comment]
thank you!
