### ISSUE TITLE
Can't to chenge screen resolution for RTMP video stream 

### ISSUE THREAD

**Issue by abrakadabrar** [pedroSG94/rtmp-rtsp-stream-client-java#286]
This function dosn't work, on server i got video with resolution 640x480 

    private boolean prepareEncoders() {
        return streamCamera.prepareVideo(1280, 720, 10,
                768 * 1024,
                true, CameraHelper.getCameraOrientation(context))
                && streamCamera.prepareAudio(32 * 1024, 32 * 1024, false, false, false);
    }

All code of class
===========================================================================
public class StreamManager implements ConnectCheckerRtmp, SurfaceHolder.Callback {

    private Activity context;
    private RtmpCamera1 streamCamera;
    private Handler handler;

    public StreamManager(Activity context) {
        this.context = context;
    }

    @Override
    public void surfaceCreated(SurfaceHolder surfaceHolder) {

    }

    @Override
    public void surfaceChanged(SurfaceHolder surfaceHolder, int i, int i1, int i2) {
        streamCamera.startPreview();
    }

    @Override
    public void surfaceDestroyed(SurfaceHolder surfaceHolder) {
        if (streamCamera.isStreaming()) {
            streamCamera.stopStream();
        }
        streamCamera.stopPreview();
    }

    @Override
    public void onConnectionSuccessRtmp() {
        context.runOnUiThread(() -> Toast.makeText(context, "Connection success", Toast.LENGTH_SHORT).show());
    }

    @Override
    public void onConnectionFailedRtmp(final String reason) {
        context.runOnUiThread(() -> {
            Toast.makeText(context, "Connection failed. " + reason, Toast.LENGTH_SHORT).show();
            streamCamera.stopStream();
        });
    }

    @Override
    public void onDisconnectRtmp() {
        context.runOnUiThread(() -> Toast.makeText(context, "Disconnected", Toast.LENGTH_SHORT).show());
    }

    @Override
    public void onAuthErrorRtmp() {
        context.runOnUiThread(() -> Toast.makeText(context, "Auth error", Toast.LENGTH_SHORT).show());
    }

    @Override
    public void onAuthSuccessRtmp() {
        context.runOnUiThread(() -> Toast.makeText(context, "Auth success", Toast.LENGTH_SHORT).show());
    }

    public void initStream(SurfaceView surfaceView, String url) {
        streamCamera = new RtmpCamera1(surfaceView, this);
        surfaceView.getHolder().addCallback(this);
        if (!streamCamera.isStreaming()) {
            if (streamCamera.isRecording() || streamCamera.prepareAudio() && streamCamera.prepareVideo() || prepareEncoders()) {
                streamCamera.startStream(url);
            } else {
                Toast.makeText(context, "Error preparing stream, This device cant do it", Toast.LENGTH_SHORT).show();
            }
        } else {
            streamCamera.stopStream();
        }
    }

    public void releaseStream() {
        if (streamCamera != null) streamCamera.stopStream();
    }

    public void switchCamera() {
        streamCamera.switchCamera();
    }

    public boolean checkAudioMuted() {
        if (!streamCamera.isAudioMuted()) {
            streamCamera.disableAudio();
            return true;
        } else {
            streamCamera.enableAudio();
            return false;
        }
    }

    private boolean prepareEncoders() {
        return streamCamera.prepareVideo(1280, 720, 10,
                1280 * 720,
                true, CameraHelper.getCameraOrientation(context))
                && streamCamera.prepareAudio(32 * 1024, 32 * 1024, false, false, false);
    }
}

**Comment by pedroSG94** [comment]
I think you have a logic error. The problem is here:
```java
if (streamCamera.isRecording() || streamCamera.prepareAudio() && streamCamera.prepareVideo() || prepareEncoders())
```
Replace to:
```java
if (streamCamera.isRecording() || prepareEncoders())
```
As you can see prepareVideo without params set resoluton to 640x480:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L226

**Comment by abrakadabrar** [comment]
> I think you have a logic error. The problem is here:
> 
> ```java
> if (streamCamera.isRecording() || streamCamera.prepareAudio() && streamCamera.prepareVideo() || prepareEncoders())
> ```
> 
> Replace to:
> 
> ```java
> if (streamCamera.isRecording() || prepareEncoders())
> ```
> 
> As you can see prepareVideo without params set resoluton to 640x480:
> https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L226

Thank a lot! Of course it was my bad. 
But problem don't solved. Now i getting this error in log:
W/CameraBase: An error occurred while connecting to camera 1: Status(-8): '8: connectHelper:1305: Cannot open camera 1 for "com.superproject.andrey." (PID -1): Too many other clients connecting'
If this

**Comment by abrakadabrar** [comment]
So, I have not errors when I don't fill data in function prepareEncoders, 
 **private boolean prepareEncoders() {
        return streamCamera.prepareVideo() && streamCamera.prepareAudio();
    }**
But, when fill:
 private boolean prepareEncoders() {
        return streamCamera.prepareVideo(720, 1024, 10,
                720 * 1024,
                false, CameraHelper.getCameraOrientation(context))
                && streamCamera.prepareAudio(128 * 1024, 720 * 1024, false, false, false);
    }
In log :
W/AudioCapabilities: Unsupported mime audio/x-ima
W/AudioCapabilities: Unsupported mime audio/mpeg-L1
W/AudioCapabilities: Unsupported mime audio/mpeg-L2
W/AudioCapabilities: Unsupported mime audio/x-ms-wma
W/VideoCapabilities: Unsupported mime video/mp43
W/VideoCapabilities: Unrecognized profile/level 1/32 for video/mp4v-es
W/VideoCapabilities: Unrecognized profile/level 32768/2 for video/mp4v-es
W/VideoCapabilities: Unrecognized profile/level 32768/64 for video/mp4v-es
W/VideoCapabilities: Unsupported mime video/wvc1
W/VideoCapabilities: Unsupported mime video/wvc1
W/VideoCapabilities: Unsupported mime video/x-ms-wmv7
W/VideoCapabilities: Unsupported mime video/x-ms-wmv8
W/ACodec: recording-mode has no value at here

I'm checking calls of func initStream(), but not sure what is the reason.
Anyway thank for help.
