### ISSUE TITLE
[Question]: Stream activity view only shows partial

### ISSUE THREAD

**Issue by ToysoftInc** [pedroSG94/rtmp-rtsp-stream-client-java#289]
I have an main activity with CoordinatorLayout that contains a toolbar and simpledrawer layout.

The toolbar is on the top and have another layout on the bottom.  In the middle is a custom fragment that contains my free hand drawing.

When I stream the view on the top and bottom views are showing and the middle shows the camera view.

On the actual device the camera preview is hidden and is covered by the top, middle and top layouts.

How do I stream the entire view?

**Comment by pedroSG94** [comment]
I'm not sure what you want but you can stream a view with this:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L137

You can clone my project go to opengl example, stream and test it to see the result.
Other way could be stream your device screen with display mode:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/master/app/src/main/java/com/pedro/rtpstreamer/displayexample
