### ISSUE TITLE
Black frames at the beginning of recording

### ISSUE THREAD

**Issue by miwaniec** [pedroSG94/rtmp-rtsp-stream-client-java#293]
Hi,
I found a curious case.
If you start recording without starting streaming, the video file has black frames at the beginning.
This is particularly problematic if you want to view these files later, all thumbnails are black.

**Comment by pedroSG94** [comment]
This should be related with keyframe. I will try fix it.

**Comment by pedroSG94** [comment]
I can't find the solution for now but you can get thumbnail of a concret second to solve this:
```java
MediaMetadataRetriever metadataRetriever = new MediaMetadataRetriever();
    try {
        metadataRetriever.setDataSource(path);
        String duration=metadataRetriever.extractMetadata(MediaMetadataRetriever.METADATA_KEY_DURATION);
        long time=Long.valueOf(duration)/2; //Get frame in the middle of the file.
        Bitmap bitmap = metadataRetriever.getFrameAtTime(time,MediaMetadataRetriever.OPTION_NEXT_SYNC);
    } catch (Exception ex) {
    }
```

**Comment by miwaniec** [comment]
Yes, I know about it and did similar for my app. But problem still exists if you want to view these files in other apps or if you want to share video. Facebook also display black screen for preview.

**Comment by pedroSG94** [comment]
For me. This issue is only with camera2. 
Is camera1 working for you or only fail with camera2 too?.

**Comment by pedroSG94** [comment]
If you use OpenGlView all should work fine with camera1 and camera2. I was doing tests and this error is only with surfaceview or textureview with camera2.
I think that camera2 draw the first frame black when you render in 2 surfaces.

**Comment by miwaniec** [comment]
Sorry for the delay, I use RtmpCamera1 and com.pedro.rtplibrary.view.OpenGlView like as in the example here https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java.

**Comment by pedroSG94** [comment]
This is working for me in Sansumg S7 API 26.
Can you tell me device model and API?

**Comment by miwaniec** [comment]
API28
I checked on XIAOMI Mi5, XIAOMI Mi A2 Lite and Huawei P10 VTR-L29

**Comment by pedroSG94** [comment]
I was looking a solution for it but no luck. I saw that you need to wait 2 keyframe to get preview. You can set all frame like key frame. For this you need set 0 to iFrameInterval variable on prepareVideo method:
```java
prepareVideo(width, height, fps, bitrate, hardwareRotation, 0, rotation);
```

**Comment by miwaniec** [comment]
This option works. Thanks.
