### ISSUE TITLE
[Improvement] Stream only camera without mic permission

### ISSUE THREAD

**Issue by troy-lamerton** [pedroSG94/rtmp-rtsp-stream-client-java#295]
At the moment, both the video and audio encoders are started together
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera2Base.java#L344-L346

This requires that the user give Camera and Microphone permission for us to call `RtmpCamera1.startStream` or `RtmpCamera2.startStream`.

I made some small changes so that audio encoders are started only when necessary.

[Camera1 start encoders](https://github.com/troy-lamerton/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L411-L417)

[Camera1 enableAudio](https://github.com/troy-lamerton/rtmp-rtsp-stream-client-java/blob/39fbd300feca605666ca218dfd574736bafbcef9/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L510-L518)

~~It was working for a while, but now I am getting strange crashes. Perhaps there is something wrong with these snippets?~~. I was trying to start a camera stream while an RtmpOnlyAudio stream was running.

**Comment by pedroSG94** [comment]
I only find that you forget no stop microphone manager when you call to stopStream() if you have it muted. The rest look good. 
https://github.com/troy-lamerton/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L465

Show me a crash log and I could help you more.

**Comment by troy-lamerton** [comment]
There was a bug in my code that stopped and restarted the stream (startStream got called before it stopped).
