### ISSUE TITLE
[request] I need to restream an RTSP stream to RTMP server

### ISSUE THREAD

**Issue by andree93** [pedroSG94/rtmp-rtsp-stream-client-java#296]
instead the camera video or local file as source, I need to re-stream an RTSP video stream (from a local server) to an RTMP server (internet or LAN). Is this possibile through this library? Thanks

**Comment by pedroSG94** [comment]
No. Actually you can restream RTSP but only video using SurfaceFilterRender instead of CameraRender and get stream with a player (for this you need modify the library) but you can't get audio.

For this you need develop a RTSP player to get video and audio buffers and send it to rtsp module.
