### ISSUE TITLE
Recording Bluetooth microphone sound

### ISSUE THREAD

**Issue by sport0102** [pedroSG94/rtmp-rtsp-stream-client-java#297]
Hi, I use your library very well. Thank you very much.

I want to know that how to record sound using bluetooth microphone. 

I used below code to set recoding
if (rtmpCamera1.isRecording() || rtmpCamera1.prepareAudio()) 

And I used below code to stream to my server by RTMP 
rtmpCamera1!!.startStream(streamUrl)

Experiment
1. Before set recoding, I connected blutooth microphone(microphone device : Air pod)
2. set recoding, start stream, but I heard sound from phone device

Please let me know, how to stream using bluetooth microphone.
Thank you!

**Comment by pedroSG94** [comment]
This library not support external bluetooth devices. To support this you need set this device like default audio device and library will get audio from your bluetooth microphone. In WebRTC you have an example for it:
https://github.com/njovy/AppRTCDemo/blob/master/app/src/main/java/org/appspot/apprtc/AppRTCBluetoothManager.java
