### ISSUE TITLE
stop function of MicrophoneManager is not thread safe

### ISSUE THREAD

**Issue by yanqinglu** [pedroSG94/rtmp-rtsp-stream-client-java#298]
The start function launchs a thread to read pcm from microphone. There is a potential issues in MicrophoneManager's stop function:

At the beginning the stop function set the 'running' to false, then executes other codes immediatlly. For safe thread consideration, it must wait for thread to quit really, because the 'getMicrophoneData' may be released after the stop calling but the thread is running.

**Comment by pedroSG94** [comment]
You are right. I will fix it tomorrow.

**Comment by pedroSG94** [comment]
Fixed: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/664e294e144f486a711d37be83e69bde68bfb871

**Comment by yanqinglu** [comment]
Great change! Thanks!
