### ISSUE TITLE
disableVideo or send black image not working 

### ISSUE THREAD

**Issue by medozeus** [pedroSG94/rtmp-rtsp-stream-client-java#299]
in screen stream tried to disableVideo and send black image

>   rtmpDisplay.disableVideo();
no thing changed in stream still get same stream no black image

**Comment by pedroSG94** [comment]
This is only working for camera1 with surfaceview or textureview. I will implement this feature to others modes (maybe like a filter).

**Comment by medozeus** [comment]
i am trying to update the code when encode from surface

**Comment by pedroSG94** [comment]
I did a commit for it. Now you can use opengl to set a black image.
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L151

Remember use opengl in screen stream mode with this constructor and boolean in true:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/DisplayBase.java#L65
