### ISSUE TITLE
Its can stream to facebook live?

### ISSUE THREAD

**Issue by lordmen99** [pedroSG94/rtmp-rtsp-stream-client-java#3]
Dear pedro,

this app can make live stream to facebook timeline from our profiles?

**Comment by pedroSG94** [comment]
No tested but should work. Facebook use rtmp protocol. Youtube use rtmp too and work.

**Comment by lordmen99** [comment]
For youtube, how make stream?

**Comment by pedroSG94** [comment]
Go creator studio in youtube, select live stream, stream now and use data in configuration.
Example result: rtmp://a.rtmp.youtube.com/live2/yournamereveal

**Comment by lordmen99** [comment]
ok,for facebook i try put rtmp url : rtmp://rtmp-api.facebook.com:80/rtmp/10206961474594258?ds=1&s_l=1&a=AThR6e6Lvxjjxwwi

not working stream into my timeline. can u fix it and check

**Comment by pedroSG94** [comment]
ok, I will check it.

**Comment by lordmen99** [comment]
i try use you tube and put format rtmp like this = rtmp://a.rtmp.youtube.com/live2/yournamereveal

but still cant stream to my youtbe

**Comment by pedroSG94** [comment]
Are you sure you did well? I tested youtube after tell you and work.

**Comment by lordmen99** [comment]
u have skype? add mine please = poster994.  i want discuss how setup it

**Comment by pedroSG94** [comment]
facebook is working in the last commit :)

**Comment by lordmen99** [comment]
realy? how the setting ?

**Comment by pedroSG94** [comment]
Was a rtmp module problem. You can use defaultrtmp activity for test

**Comment by lordmen99** [comment]
i mean url format rtmp facebook? how put format. Only like this = http://rtmp-api.facebook.com/rtmp/ ?

or http://rtmp-api.facebook.com/rtmp/user-id?ds=1&s_l=1&a=ATj6kVTxfnHJlMPN ?

**Comment by pedroSG94** [comment]
like this: 
rtmp://rtmp-api.facebook.com:80/rtmp/1892213090993296?ds=1&s_l=1&a=ATj36DtGn3Xbe_9O

**Comment by lordmen99** [comment]
its can stream to facebook timeline? istill not success

**Comment by lordmen99** [comment]
-18 07:35:58.857 5812-6321/com.pedro.rtmpstreamer W/System.err: java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
04-18 07:35:58.857 5812-6321/com.pedro.rtmpstreamer W/System.err:     at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:588)
04-18 07:35:58.857 5812-6321/com.pedro.rtmpstreamer W/System.err:     at libcore.io.IoBridge.recvfrom(IoBridge.java:552)
04-18 07:35:58.857 5812-6321/com.pedro.rtmpstreamer W/System.err:     at java.net.PlainSocketImpl.read(PlainSocketImpl.java:481)
04-18 07:35:58.857 5812-6321/com.pedro.rtmpstreamer W/System.err:     at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
04-18 07:35:58.857 5812-6321/com.pedro.rtmpstreamer W/System.err:     at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
04-18 07:35:58.857 5812-6321/com.pedro.rtmpstreamer W/System.err:     at java.io.InputStream.read(InputStream.java:162)
04-18 07:35:58.857 5812-6321/com.pedro.rtmpstreamer W/System.err:     at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:149)
04-18 07:35:58.857 5812-6321/com.pedro.rtmpstreamer W/System.err:     at java.io.BufferedInputStream.read(BufferedInputStream.java:234)
04-18 07:35:58.857 5812-6321/com.pedro.rtmpstreamer W/System.err:     at com.github.faucamp.simplertmp.packets.Handshake.readS0(Handshake.java:49)
04-18 07:35:58.857 5812-6321/com.pedro.rtmpstreamer W/System.err:     at com.github.faucamp.simplertmp.io.RtmpConnection.handshake(RtmpConnection.java:104)
04-18 07:35:58.857 5812-6321/com.pedro.rtmpstreamer W/System.err:     at com.github.faucamp.simplertmp.io.RtmpConnection.connect(RtmpConnection.java:147)
04-18 07:35:58.857 5812-6321/com.pedro.rtmpstreamer W/System.err:     at com.github.faucamp.simplertmp.DefaultRtmpPublisher.connect(DefaultRtmpPublisher.java:28)
04-18 07:35:58.857 5812-6321/com.pedro.rtmpstreamer W/System.err:     at net.ossrs.rtmp.SrsFlvMuxer.connect(SrsFlvMuxer.java:117)
04-18 07:35:58.857 5812-6321/com.pedro.rtmpstreamer W/System.err:     at net.ossrs.rtmp.SrsFlvMuxer.access$000(SrsFlvMuxer.java:48)
04-18 07:35:58.857 5812-6321/com.pedro.rtmpstreamer W/System.err:     at net.ossrs.rtmp.SrsFlvMuxer$1.run(SrsFlvMuxer.java:152)
04-18 07:35:58.857 5812-6321/com.pedro.rtmpstreamer W/System.err:     at java.lang.Thread.run(Thread.java:818)
04-18 07:35:58.857 5812-6321/com.pedro.rtmpstreamer W/System.err: Caused by: android.system.ErrnoException: recvfrom failed: ECONNRESET (Connection reset by peer)
04-18 07:35:58.857 5812-6321/com.pedro.rtmpstreamer W/System.err:     at libcore.io.Posix.recvfromBytes(Native Method)
04-18 07:35:58.857 5812-6321/com.pedro.rtmpstreamer W/System.err:     at libcore.io.Posix.recvfrom(Posix.java:189)
04-18 07:35:58.857 5812-6321/com.pedro.rtmpstreamer W/System.err:     at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
04-18 07:35:58.857 5812-6321/com.pedro.rtmpstreamer W/System.err:     at libcore.io.IoBridge.recvfrom(IoBridge.java:549)
04-18 07:35:58.857 5812-6321/com.pedro.rtmpstreamer W/System.err: 	... 14 more

**Comment by pedroSG94** [comment]
http://stackoverflow.com/questions/11207394/getting-socketexception-connection-reset-by-peer-in-android

**Comment by lordmen99** [comment]
please update ur code so, working on wifi with firewall..
