### ISSUE TITLE
is there ability to take screenshot while stream or record the screen ? 

### ISSUE THREAD

**Issue by medozeus** [pedroSG94/rtmp-rtsp-stream-client-java#301]

**Comment by pedroSG94** [comment]
Yes, first you should use opengl. Then, use this method: 
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/view/GlInterface.java#L50
Example:
```java
rtmpDisplay.getGlInterface().takePhoto(new TakePhotoCallback() {
      @Override
      public void onTakePhoto(Bitmap bitmap) {
         //You receive your image here.
      }
    });
```
You can do it in all modes with opengl.

**Comment by harisab2547** [comment]
how to Initialize the  RtmpDisplay and record the screen
