### ISSUE TITLE
pause and resume the record if not streaming 

### ISSUE THREAD

**Issue by Loxen9** [pedroSG94/rtmp-rtsp-stream-client-java#302]

**Comment by pedroSG94** [comment]
Pause and resume record is not available for record. I will add this like feature.

**Comment by Loxen9** [comment]
waiting for that :)

**Comment by mhackeras** [comment]
Hi guys.. i personally get pieces of video and merge them.. when i press pause and then start again i record new video and when on stop i merge the pieces.
Though i had the idea to play with timestamps.. but couldnt achieve a good result :/

**Comment by pedroSG94** [comment]
I'm working on it. For now, I have all working but when you resume produce pixelate effect because video need a new keyframe in first frame after resume. I'm working to solve it.

**Comment by pedroSG94** [comment]
Pause and resume added: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/379e6bbb613864636870593713be61d816cc88c3
I need test more and try find error but for now it is working.
This is not added to UI(because it is under test) so, if you want test It:
- Go to OpenGlRtmpActivity.
- In onClick method replace switch camera content to this code:
```java
        if (rtmpCamera1.getRecordStatus() == RecordController.Status.RECORDING) {
          rtmpCamera1.pauseRecord();
        } else if (rtmpCamera1.getRecordStatus() == RecordController.Status.PAUSED) {
          rtmpCamera1.resumeRecord();
        }
```
Now, You can test it in my app.

**Comment by mhackeras** [comment]
Today while testing new Version got an error cause of the new pause - resume method.
Stopped video and got exception on 3thd line from the end
@RequiresApi(api = Build.VERSION_CODES.JELLY_BEAN_MR2)
  public void recordVideo(ByteBuffer videoBuffer, MediaCodec.BufferInfo videoInfo) {
    if (status == Status.STARTED
        && videoInfo.flags == MediaCodec.BUFFER_FLAG_KEY_FRAME
        && videoFormat != null
        && audioFormat != null) {
      videoTrack = mediaMuxer.addTrack(videoFormat);
      audioTrack = mediaMuxer.addTrack(audioFormat);
      mediaMuxer.start();
      status = Status.RECORDING;
      if (listener != null) listener.onStatusChange(status);
    } else if (status == Status.RESUMED && videoInfo.flags == MediaCodec.BUFFER_FLAG_KEY_FRAME) {
      status = Status.RECORDING;
      if (listener != null) listener.onStatusChange(status);
    }
    if (status == Status.RECORDING) {
      updateFormat(this.videoInfo, videoInfo);
      mediaMuxer.writeSampleData(videoTrack, videoBuffer, this.videoInfo);  <--- THIS LINE HERE
    }
  }

**Comment by pedroSG94** [comment]
Can you show me exception trace? (logcat) I want know exception reason.

**Comment by mhackeras** [comment]
Lost the log from android studio cause of cable reconnection.
Trying to reproduce it now.
:SSS
