### ISSUE TITLE
Camera2 fps issues while streaming 

### ISSUE THREAD

**Issue by hbergqvist** [pedroSG94/rtmp-rtsp-stream-client-java#303]
Hello!

I've been experimenting a little with the SDK, and I've ran into a problem with Camera2. The preview runs smooth, but when I start streaming the fps drops to what feels like 15 and stays there consistently. This does not occur when I use Camera1. 

My main activity looks like [this](https://gist.github.com/hbergqvist/ce0dcf1e177596df6593b1a1f367443b)

Any ideas to why this is happening?

**Comment by pedroSG94** [comment]
Are you using surfaceview or textureview? 
Try replace it with openglview or lightopenglview.

**Comment by hbergqvist** [comment]
This solved it! Thank you.

**Comment by tbeyou** [comment]
Hey !

I have tried to use an OpenGLView instead of a SurfaceView for an RTMP stream. It did solve the issue (we get 30 fps). Unfortunately, audio and video are not sync anymore with an OpenGLView. There is the same issue with your sample example.

Do you if we can have both get a fixed 30 fps and a good audio/video sync ?

**Comment by pedroSG94** [comment]
Can you tell me device model and android api?

**Comment by tbeyou** [comment]
Samsung C7 Pro - Android 7.0

**Comment by psegalen** [comment]
I have the same behaviour with a LG V30 - Android 8.0

**Comment by pedroSG94** [comment]
Can you try clone project, delete [this line](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L380) and retry?

**Comment by psegalen** [comment]
It appears that deleting this line prevent the app from streaming.
Without deleting it, the audio/video sync is good during the first 5 seconds and then it slips more and more until reaching a point where audio occurs about 1 second before video (~ 30 seconds after stream start) then it stays that way (tried a 10 minutes session).

**Comment by psegalen** [comment]
Here you can see a small session and how sync slips: https://www.twitch.tv/videos/394304146

**Comment by pedroSG94** [comment]
Normally this is related with timestamp. For now I can't reproduce it :(. I will try on twitch more late.
For now, can you try this? (This is my last suggestion and I need investigate more).
Before [this line](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/audio/AudioEncoder.java#L148) add this:
```java
 audioInfo.presentationTimeUs = System.nanoTime() / 1000 - presentTimeUs;
```

**Comment by pedroSG94** [comment]
Also try delete [this line](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L360)

**Comment by pedroSG94** [comment]
This is working for me with samsung S7 in my demo example I only replace RtmpCamera1 to RtmpCamera2 in OpenGlRrtmpActivity. Video example on twitch:
https://www.twitch.tv/videos/394313473

**Comment by psegalen** [comment]
I tried both modifications you suggested and it seems to have fixed the issue (cf. https://www.twitch.tv/videos/394314752)
