### ISSUE TITLE
Camera2 cant stopStream after onAuthErrorRtmp

### ISSUE THREAD

**Issue by quanseesaa** [pedroSG94/rtmp-rtsp-stream-client-java#305]
Im using rtmp with wowza authentication. 

when user or password doesnt match, the onAuthErrorRtmp is called, I have to stop the stream before start new stream.

but it doesnt stop, and error has occurred as below:

> E/Camera2ApiManager: Error
>     java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.camera2.CameraCaptureSession.stopRepeating()' on a null object reference
>         at com.pedro.encoder.input.video.Camera2ApiManager.closeCamera(Camera2ApiManager.java:409)
>         at com.pedro.rtplibrary.base.Camera2Base.stopStream(Camera2Base.java:395)
>         at jp.liveplus_app.broadcaster.ui.live.LiveActivity$onAuthErrorRtmp$1.run(LiveActivity.kt:690)
>         at android.os.Handler.handleCallback(Handler.java:789)
>         at android.os.Handler.dispatchMessage(Handler.java:98)
>         at android.os.Looper.loop(Looper.java:251)
>         at android.app.ActivityThread.main(ActivityThread.java:6563)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by pedroSG94** [comment]
You don't should call stopStream on AuthError callback because connectionFailed is called after that. In this case you are doing 2 calls to stopStream and this produce your error. 
I will check a synchronization way to solve it but this never should occur if you are doing stopStream only on connectionFailed.

**Comment by quanseesaa** [comment]
ah, yes, thank you.
I didnt think about this 

change stopStream to onConnectionFailedRtmp and it works fine.
