### ISSUE TITLE
enable or disable internal audio in recording or streaming

### ISSUE THREAD

**Issue by Loxen9** [pedroSG94/rtmp-rtsp-stream-client-java#308]

**Comment by pedroSG94** [comment]
What do you mean with internal audio? Filter device audio and only capture the others sources?
In this case, I don't know how to do it.

**Comment by Loxen9** [comment]
i mean record only system audio or enable record mic audio too

**Comment by pedroSG94** [comment]
You only can do it with [vizualizer](https://developer.android.com/reference/android/media/audiofx/Visualizer) but the result is bad quality and partial so I will not do it for now.

**Comment by mhackeras** [comment]
Otherwise you can do it by using audio source as remote submix but it requires to be rooted and app to be a system app.
Also in my project i wrote code to disable audio completely when recording.
