### ISSUE TITLE
The image is stretch when try to set ratio 16:9

### ISSUE THREAD

**Issue by quanseesaa** [pedroSG94/rtmp-rtsp-stream-client-java#313]
I have checked below issues but did not find the solution:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/76
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/87
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/139
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/291

I"m using RtmpCamera2, your OpenGlView, set keepAspectRatio true

it works with default value, like in your example, which is 4:3.
but 4:3 with keepAspectRatio = true, it cuts the small part at top and bottom.

I want to show the preview full screen in 16:9 ratio, like the default camera app.

with your newest version 1.5.7 I tried 

rtmpCamera2.prepareVideo(720, 1280, 30, 1200 * 1024, false, 90)

override fun surfaceChanged(surfaceHolder: SurfaceHolder, i: Int, i1: Int, i2: Int) {
     rtmpCamera2.startPreview(CameraHelper.Facing.BACK, 720, 1280,90)
}

override fun surfaceChanged(surfaceHolder: SurfaceHolder, i: Int, i1: Int, i2: Int) {
     rtmpCamera2.startPreview(CameraHelper.Facing.BACK, i1, i2,90)
}

none of above works and the image is sketched and weird. 

I can get it work now by reverse back to version 1.5.3 and set
 
rtmpCamera2.prepareVideo(1280, 720, 30, 1200 * 1024, false, 90)

that the closest I got. if I set to 1600x900 or 1920×1080 (still 16:9) it sketches, only works if set to 1280x720

and btw, I dont know why but on version 1.5.7 (compared to 1.5.3) width and height value seems inverted (width is height and height is width), the default rtmpCamera2.startPreview() does not work for me the height preview is only in half (but in your example is fine)

**Comment by pedroSG94** [comment]
StartPreview is fixed here: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/7c2fe07e996ec35e9fd1325e726431dfbd7566fb
I will upload 1.5.8 after fix aspect ratio bug.

**Comment by pedroSG94** [comment]
I was doing test but I only can find that with some resolution preview could be cropped but aspect ratio is fine.
I did a commit to extract preview viewport to other class. You can play with this method to find a configuration that work for you:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/utils/gl/PreviewSizeCalculator.java

**Comment by quanseesaa** [comment]
sorry, how to use this class?

btw, is your current github code match the 1.5.7 version from jitpack, because want to use it from library from gradle, not directly from this github code.

at this moment, this is how it looks

The default camera app preview : 
https://i.imgur.com/Q8hREdR.jpg


Your newest github sample app preview: (I set NoActionBar) 
https://i.imgur.com/gq2tBsE.jpg

and here is my app Im currently working with 1.5.7 version from gradle
https://i.imgur.com/TaEViO9.jpg

--> as you can see the image is weirdly sketched

**Comment by pedroSG94** [comment]
Can you tell me your device screen aspect ratio?. Maybe the reason is that my devices has 16:9 and you have other resolution.

**Comment by quanseesaa** [comment]
I dont know where to check device screen aspect ratio, but my tested devices are Sony Xperia XZ1, Nesus 5, and Sony Xperia Z5. 

all 3 pictures above taken from Sony Xperia XZ1, in the same angle.

**Comment by quanseesaa** [comment]
Sony Xperia XZ1 is 1080 x 1920 pixels, 16:9 ratio (~424 ppi density)

**Comment by pedroSG94** [comment]
I will try reproduce the 3º image case. Can you tell me your activity style configuration in your app to reproduce the error?

**Comment by quanseesaa** [comment]
I created new test project, only add this library to gradle : 
implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:1.5.7'

the style is 
<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
</style>

the activity is 
window.addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)
window.addFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN)

the camera code is simple: 
rtmpCamera2 = new RtmpCamera2(openGlView, this);
rtmpCamera2.prepareVideo(1280, 720, 30, 1200 * 1024, false, 90);

and in surfaceChanged(....) add: 
 rtmpCamera2.startPreview


and the result still the same.

**Comment by quanseesaa** [comment]
[TestAndDeleteRightAwayApp.zip](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/3006242/TestAndDeleteRightAwayApp.zip)
here is the test app

**Comment by pedroSG94** [comment]
This look work fine in actual commit. I did a gradle update to project. Try use version 1.5.8. Also you should modify the code a little. Here is the app with the modifications:
[TestAndDeleteRightAwayApp2.zip](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/3007969/TestAndDeleteRightAwayApp2.zip)

**Comment by quanseesaa** [comment]
thanks, that seems to fix the camera preview

thank you for your comment. 

so I need to set camera resolution in surfaceChanged using startPreview() and then before calling startStream I need to prepareVideo again to keep the ratio? 
because I tried only set resolution in startPreview without prepareVideo, after it go to live stream, it back to normal 4:3 ratio.

**Comment by pedroSG94** [comment]
Yes, that is correct. You need prepare video and audio each time you start stream or record

**Comment by Geremp** [comment]
Hello,

I have read all the issue but can't find a solution.
I have just launch your app on my Honor 20 Lite.
OpenGL RTMP.
The preview is stretch so i did what you say : set aspectRatio to true.

It is working, but the image is cropped (top and bottom).
I would like, as quanseesaa to have a 16:9 preview, but i can find a way in your example… can you help me for this ?
