### ISSUE TITLE
Resulted video laggy

### ISSUE THREAD

**Issue by mhackeras** [pedroSG94/rtmp-rtsp-stream-client-java#314]
I notice when recording display.. even when recording on 60fps video seems laggy.. 
i think it is because of fps limiter we created some time ago..
i would be really glad if you could check it.. or tell me on how to help you on this.

You can test on Geometry dash game.. that easily renders on 60fps.

**Comment by pedroSG94** [comment]
I removed fps limiter with surface render in a commit because produce audio sync problems in stream with some devices. https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/303
Did you tried with my app example in last commit? I did a video and seems fine

[20190322_140623.zip](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/2996588/20190322_140623.zip)

**Comment by mhackeras** [comment]
If you think this result is ok! I trust you!
i always admit that your work is the best! I have learnt tons of things!

**Comment by pedroSG94** [comment]
Maybe no 60fps but this look smooth in my opinion. The zip attached above is a video recorded on Samsung S7 in Geometry dash game

**Comment by mhackeras** [comment]
Ok nice! 
is there a way to start video recording using h265? or should i write the code?

**Comment by pedroSG94** [comment]
If you want use RTMP it is not implemented because FLV don't support H265 so you can't stream H265 with RTMP You can record and stream H265 with RTSP.
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtsp/RtspCamera1.java#L117

**Comment by mhackeras** [comment]
Ok i will make my own code for this.
One more thing i would like to discuss on video is that the resulted video is yuv420p(tv) format.
Not just yuv420p

**Comment by pedroSG94** [comment]
yuv420p(tv, bt709) is yuv420p but with more info about frames. This is only info about the conversion matrix used to convert RGB frame to YUV.
You can get more info about BT709 here:
https://en.wikipedia.org/wiki/YUV#HDTV_with_BT.709

**Comment by mhackeras** [comment]
One more i would like to note is that when we record on 60fps for example.. if screen renders on 25 fps.. i get a very pixelized video result.
Cause of frames bitrate lowers on its own.

**Comment by pedroSG94** [comment]
You can try calculate real fps and change bitrate on fly with this method:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/DisplayBase.java#L383

**Comment by mhackeras** [comment]
This what i thought of doing but wanted to ask you if you could find a lighter way.. 
Currently testing the method. i will post back!

**Comment by mhackeras** [comment]
Pedrooooooooooo
it worked!!! and instead of pixelized video i got crystal video!!!!
i used a method that runs every second to calculate drops and it worked!!
Was setting bitrate on fly.. i just added some bitrates on overall and it worked!
I ll write it clearly if i can,.. or i can email you so as to write it on your own so as to be better

**Comment by mhackeras** [comment]
For me this is a very good enhancement.. cause it will work around your setting of bitrate.
and will provide better video quality.

**Comment by pedroSG94** [comment]
This could be interesting but remember that this bitrate affect to stream so you will consume more bandwidth. If you want, you can do a pull request.

**Comment by mhackeras** [comment]
Will do in some hours after work!
When you set some bitrate you expect the encoder to work on this. It will consume the bandwidth you set at the beginning. Also adaptive bitrate will lower this. Will make it perfect before pull request.
Currently from testing I get good results. Also will record better video on lower bitrates. Cause it keep it some kind stable.

**Comment by mhackeras** [comment]
Got some conflict with AdaptiveBitrate.. 
also it seems AdaptiveBitrate.maxVideoBitrate doesnt work as it should :/

**Comment by pedroSG94** [comment]
You mean my [adaptative bitrate](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/network/AdapterBitrateParser.java)? This change your videobitrate depend of upload bandwidth.
Where is the conflict? maybe I can help you.

The actual idea is set a limit of bitrate if you bandwidth can use more. For example:
You have 20Mb of upload bandwidth but you only want use 2Mb because you are using 480p stream so you set this variable to 2000. This means that stream will consume a limit of 2Mb

**Comment by mhackeras** [comment]
I meant that my code was changing bitrates cause of fps drops.. and this was changing values according to net.(Fixed this)
Also i set max video bitrate but it seems to ignore it.

**Comment by mhackeras** [comment]
thread.setPriority(Thread.MAX_PRIORITY);
with this on encoder thread i got smoother video.. will test further.. not a good solution but it works good

**Comment by pedroSG94** [comment]
This could be a solution. If this work for you I can add this like a pull request

**Comment by ulohani90** [comment]
I am seeing the same problem as mentioned over here. The video is a bit laggy that I stream on facebook gaming. I would like to try the solution given above i.e setting the bitrate on the fly. But not sure how should it be related to the fps. Can you please help over here?
