### ISSUE TITLE
Streaming rstp from Another SurfaceView

### ISSUE THREAD

**Issue by kashkashio** [pedroSG94/rtmp-rtsp-stream-client-java#317]
Hi,
I've found in the repo few people that asked this question but unfortunately i cant figure the answer...

This is my story.
i have a camera that stream in rstp..
i'm using vlc to consume the rstp stream and put it in a SurfaceView in the UI and it works.

Now i want to take this same surface view and "tunnel" it or stream it directly to wowza..
if i use the camera the stream works well, when i did some changes to use the same surface view for both, it failed...

i think that figuring this out can be a great addition to the library and will help other people that are looking for it.

This is the library i use to consume the rstp from my other device:
https://github.com/pedroSG94/vlc-example-streamplayer

its really small project and it works great.
i wonder if you can find time to create or modify a class that will be able to work with this library, i mean to get the output from the surface view that the vlc lay the frames on and stream them to the wowza rstp link.
For you it will be really easy i guess :)
i will be really greatful !

Or any other advises will be more then awesome!
Thank you very much and keep up with the briliant work ! <3

@pedroSG94

**Comment by pedroSG94** [comment]
Is possible get video frames from VLC with an openglview and a little modification but you can't get audio. I can enable microphone and use that to capture sounds speaker but no more.
I can try create a project example if I have time.

**Comment by kashkashio** [comment]
Thank you for the fast reply !
A demo project will be realllllyy helpul !

Tough i actually managed to get to the : public void inputYUVData(Frame frame)
I used textureView and im calling textureView.getBitmap() to get my camera out put and trying to call:
videoEncoder.inputYUVData(framee);
with my new frame i took from the other surfaceView it actualy works!!
i can see the out put on the wowza ! the issue i'm facing right now is that something gets wrong when im converting my bitmap to frame. the output is a weird green image with lines on the left 

do you have any idea of how to convert that bitmap so the encoder will be able to use it easly ?
i tried converting to nv21 using examples online but none worked.

your help is a diamond thank you
i'm attaching the relevant code and result

![Screen Shot 2019-03-29 at 17 42 25](https://user-images.githubusercontent.com/13186361/55240495-0e26eb80-524a-11e9-9bf4-3c8126094b7e.png)

  public void inputYUVData(Frame frame) {
    Bitmap bmp = textureView.getBitmap();
    Frame framee = new Frame(getYV12(bmp.getWidth(), bmp.getHeight(), bmp), frame.getOrientation(), frame.isFlip(), frame.getFormat());
    videoEncoder.inputYUVData(framee);
  }

  private byte [] getYV12(int inputWidth, int inputHeight, Bitmap scaled) {

    int [] argb = new int[inputWidth * inputHeight];

    scaled.getPixels(argb, 0, inputWidth, 0, 0, inputWidth, inputHeight);

    byte [] yuv = new byte[inputWidth*inputHeight*3/2];
    encodeYV12(yuv, argb, inputWidth, inputHeight);

    scaled.recycle();

    return yuv;
  }

  private void encodeYV12(byte[] yuv420sp, int[] argb, int width, int height) {
    final int frameSize = width * height;

    int yIndex = 0;
    int uIndex = frameSize;
    int vIndex = frameSize + (frameSize / 4);

    int a, R, G, B, Y, U, V;
    int index = 0;
    for (int j = 0; j < height; j++) {
      for (int i = 0; i < width; i++) {

        a = (argb[index] & 0xff000000) >> 24; // a is not used obviously
        R = (argb[index] & 0xff0000) >> 16;
        G = (argb[index] & 0xff00) >> 8;
        B = (argb[index] & 0xff) >> 0;

        // well known RGB to YUV algorithm
        Y = ( (  66 * R + 129 * G +  25 * B + 128) >> 8) +  16;
        U = ( ( -38 * R -  74 * G + 112 * B + 128) >> 8) + 128;
        V = ( ( 112 * R -  94 * G -  18 * B + 128) >> 8) + 128;

        // YV12 has a plane of Y and two chroma plans (U, V) planes each sampled by a factor of 2
        //    meaning for every 4 Y pixels there are 1 V and 1 U.  Note the sampling is every other
        //    pixel AND every other scanline.
        yuv420sp[yIndex++] = (byte) ((Y < 0) ? 0 : ((Y > 255) ? 255 : Y));
        if (j % 2 == 0 && index % 2 == 0) {
          yuv420sp[uIndex++] = (byte)((V<0) ? 0 : ((V > 255) ? 255 : V));
          yuv420sp[vIndex++] = (byte)((U<0) ? 0 : ((U > 255) ? 255 : U));
        }

        index ++;
      }
    }
  }

**Comment by pedroSG94** [comment]
Hi, I did the demo app. This is not stable for now. Remember change urls in MainActivity before test and accept permissions manually.
https://github.com/pedroSG94/AndroidReStreamer

**Comment by kashkashio** [comment]
Thank you very very much !

**Comment by FunnyDevs** [comment]
Hi! I would like to do same action but without Vlc Player: i have a surfaceview ( LightOpenGLView) that plays rtsp video from lan endpoint and i should publish this stream to a remote rtsp server.
I'm trying to use your VLCRestreamerBase removing vlcplayer but i'm not able to go on. 
The app crashes in the "prepareGlView" method.
