### ISSUE TITLE
Streaming in background mode and preview if need

### ISSUE THREAD

**Issue by someclick** [pedroSG94/rtmp-rtsp-stream-client-java#318]
I want to livestream in background and preview on a glview when my app in foreground
I read all examples and some code in lib, but i can't found any way to do it
how can i do it?

**Comment by pedroSG94** [comment]
There is not a specific form to do it.

For now, the only way is use 2 stream instances. A background instance when you go to background that you should stop if app go to foreground and other instance with preview that start when you go to foreground and stop when you go to background.
Also you can use a widget to create a preview with app in foreground:
https://www.simplifiedcoding.net/android-floating-widget-tutorial/

**Comment by someclick** [comment]
> There is not a specific form to do it.
> 
> For now, the only way is use 2 stream instances. A background instance when you go to background that you should stop if app go to foreground and other instance with preview that start when you go to foreground and stop when you go to background.
> Also you can use a widget to create a preview with app in foreground:
> https://www.simplifiedcoding.net/android-floating-widget-tutorial/

Yeah, I will use this way, thank you very muck!

**Comment by Sermilion** [comment]
@pedroSG94 so that means that the stream would be stopped and continued using two different camera instances and that the server would need to support continuing?
