### ISSUE TITLE
Is there a way to do face recognition?

### ISSUE THREAD

**Issue by safefy** [pedroSG94/rtmp-rtsp-stream-client-java#319]
Hello @pedroSG94 I use your project and it works very well but I want to implementand face recognition feature. I don't know how to start because I want to do something like put the mask on face.

**Comment by pedroSG94** [comment]
Hi,
Actually it is not working well because I need change face parse in porttrait and landscape and in camera2 it too slow for some reason. You can try with camera1.
```java
rtmpCamera1.enableFaceDetection(new Camera1ApiManager.FaceDetectorCallback() {
          @Override
          public void onGetFaces(Camera.Face[] faces) {
            
          }
        });
```
