### ISSUE TITLE
Camera1 with openGL view is laggy

### ISSUE THREAD

**Issue by safefy** [pedroSG94/rtmp-rtsp-stream-client-java#320]
Hi again
I've tried to set fps to 30 when use prepareVideo method it's smooth but preview is too dark, and I changed it to 5fps it's crystal but it's very lag, So the question is what is the best fps to make preview smooth and how to? Thank you in advance

**Comment by pedroSG94** [comment]
Hi,
This preview error is an error in specific devices. Read this:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/184

You can try use this reference to fix your error. Can you tell me your device model and API?
