### ISSUE TITLE
Why simple rtmp is different from faucamp/SimpleRtmp

### ISSUE THREAD

**Issue by OhYee** [pedroSG94/rtmp-rtsp-stream-client-java#321]
[faucamp/SimpleRtmp](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java)
I want to use this package with publisher.

**Comment by pedroSG94** [comment]
This project use SimpleRtmp library like a base but with modifications to support auth, rtmps, etc. If you want change package you can do a modification to the library.

**Comment by OhYee** [comment]
Thanks for your reply.
