### ISSUE TITLE
how to stream byte[] from another UVCcamera

### ISSUE THREAD

**Issue by XiaoXu09** [pedroSG94/rtmp-rtsp-stream-client-java#322]
in my project,  Obtaine byte[] through UVCCamera.  how stream byte[]?

**Comment by pedroSG94** [comment]
If your byte[] is nv21 or yv12 you can try modify Camera1Base class and replace CameraManager with UVCCamera library.

**Comment by XiaoXu09** [comment]
thank you for your answer.
Added up.  Two video streams are uploaded simultaneously.   A video stream from mobile camera. another video stream form extranal device camera(UVCCanmera).   How to upload both video streams at the same time.   Can you understand that? My English is not good.

**Comment by pedroSG94** [comment]
If you want do 2 streams with different video source you should create 2 instances class that use different video source and modify library to share microphone manager in both instances because you can't open two times the microphone.
