### ISSUE TITLE
How to stream RTMP from unityplayer (non-screenshot mode)?

### ISSUE THREAD

**Issue by wkl-coder** [pedroSG94/rtmp-rtsp-stream-client-java#324]
For android camera,I used unity to load the face in 3d. The export project included unitypalyer, and I wanted to broadcast RTMP.

**Comment by 544531645** [comment]
@pedroSG94

**Comment by pedroSG94** [comment]
I don't know how to integrate this library with unity (I never did a plugin for Android in unity). Also I don't know how unity send frames to Android in your case.

**Comment by 544531645** [comment]
Another way is to display unityplayer on surfaceview. How to perform RTMP on surfacaview?
@pedroSG94

**Comment by pedroSG94** [comment]
If you are rendering a Surface (Not SurfaceView) You can modify the library using Camera1Base or Camera2Base like example and rendering an OpenGlview Surface. 
In this case you should use your Unity plugin to replace CameraManager class.

**Comment by 544531645** [comment]
This is my recorded demo (obtained through online research), because I am not very familiar with RTMP. I wonder if this can be improved with your RTMP library. Could you please help me to have a look?I send the demo to your email .

**Comment by 544531645** [comment]
wait .a litter big zip file

**Comment by 544531645** [comment]
Similar to your AndroidReStreamer demo, can I just delete the VLCRTSP and new my surfaceview ,if it can work ?
@pedroSG94

**Comment by pedroSG94** [comment]
Yes, this should work.

**Comment by 544531645** [comment]
but I see need openglview. I need create customsurfaceview or only cast it okay ?,I will tomorrow try it . if I meet with difficulty. can I ask for your help ?

**Comment by pedroSG94** [comment]
You need chagen SurfaceView to OpenGlView in your xml layout and cast to OpenGliew in code

**Comment by 544531645** [comment]
19-04-12 11:47:01.084 10677-10757/com.binaryvr.HyprfaceUnityExample E/AndroidRuntime: FATAL EXCEPTION: Thread-4
    Process: com.binaryvr.HyprfaceUnityExample, PID: 10677
    java.lang.RuntimeException: eglCreateWindowSurface: EGL error: 0x3003
        at com.pedro.encoder.utils.gl.GlUtil.checkEglError(GlUtil.java:134)
        at com.pedro.encoder.input.gl.SurfaceManager.eglSetup(SurfaceManager.java:131)
        at com.pedro.encoder.input.gl.SurfaceManager.<init>(SurfaceManager.java:46)
        at com.pedro.rtplibrary.view.OpenGlView.run(OpenGlView.java:106)
        at java.lang.Thread.run(Thread.java:764)
I happend this @pedroSG94 ...

**Comment by 544531645** [comment]
I think a litter different , I use the                     mUnityPlayer.displayChanged(0, new Surface(inputSurface));
let unityplayer show in openglview, when  new RtmpUnity(openGlview,UnityPlayerActivity.this);
happend error

**Comment by 544531645** [comment]
Did you check the email I sent? It USES a c++ method to display it on a surfaceview. The recording is also

**Comment by pedroSG94** [comment]
I did a check to you app example and you are using surface from surfaceview in onChanged callback. For now, I haven't time to write an example for you. I will try do it in a few days.

**Comment by 544531645** [comment]
very thank you ，I also will try it for myself , Thanks again

**Comment by 544531645** [comment]
requestWindowFeature(Window.FEATURE_NO_TITLE);
        super.onCreate(savedInstanceState);

        mUnityPlayer = new UnityPlayer(this);
        setContentView(mUnityPlayer);
        mUnityPlayer.requestFocus();
this is only from to unity export .  my demo is for use finengine library to show my surfaceview

**Comment by 544531645** [comment]
After I tried, I could only connect, but the streaming was wrong. Is the surface from the holder different?
@pedroSG94

**Comment by 544531645** [comment]
Have you been busy lately? Any thoughts on this?

**Comment by pedroSG94** [comment]
Hi. Sorry actually i'm on holidays and I have no time to program

**Comment by 544531645** [comment]
okay，When you have time to look at it. Happy holiday

**Comment by troy-lamerton** [comment]
@544531645 you can use OpenGlView and replace Unity's main display with the surface renderer.

```
UnityPlayer.displayChanged(0, openGlView.getSurface());
```

Works for me 🤷‍♂ .
