### ISSUE TITLE
Image filter and Text filter together

### ISSUE THREAD

**Issue by mylaimani** [pedroSG94/rtmp-rtsp-stream-client-java#325]
Is there way to implement image filter and text filter together. I had seen the examples you had given for GL, but when I apply image filter first  and text filter next, the image gets disappeared. I need to show logo and text together 

Something like this
rtmpCamera1.getGlInterface().setFilter( imageFilter, textFilter)

**Comment by pedroSG94** [comment]
Yes you can.
1- Select in xml layout the num of filters you want use (In your case 2): https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/res/layout/activity_open_gl.xml#L14
2- When you set a filter inform to library position where you set filter(If you selected 2 filter in xml you can use position 0 or 1 if you use other position the app will crash):
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/view/GlInterface.java#L59
