### ISSUE TITLE
can resolve method setRetries(int)

### ISSUE THREAD

**Issue by XiaoXu09** [pedroSG94/rtmp-rtsp-stream-client-java#326]
implementation  'com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:1.5.8‘
and 
 import com.pedro.encoder.input.video.CameraOpenException;
import com.pedro.rtplibrary.rtmp.RtmpCamera1;

but can resolve method 'setReTries(int)'.
 can you tell me why can reolve this method? thank you!

**Comment by pedroSG94** [comment]
This feature is no available in 1.5.8. I will update 1.5.9 soon
