### ISSUE TITLE
Caught IOException during write loop, shutting down

### ISSUE THREAD

**Issue by denebchorny** [pedroSG94/rtmp-rtsp-stream-client-java#329]
Hi Mr. Pedro, 

I am using your library and sometimes I get the following error:

`E/RtmpConnection: Caught IOException during write loop, shutting down: Write error: ssl=0x7379a9bd00: I/O error during system call, Broken pipe`

I would like to know if you have knowledge to which this could be due.

I must admit that I am not making use of the latest version of your library. I promise to update it in the project but I need to make a big change. I'll try soon in the next few days.

But my question is oriented to know if you have an idea of what might be happening. Why is this due? Does it have to do with the connection to the internet? Or could it be due to an error in the url? or is it something else?

It's weird. Sometimes connects, sometimes dont. When it dont, then, could show me the error or just it fail with onConnectionFailedRtmp. If the second one happen there is no problem because there is a reason. In the first one IDK what is happening because there is no trace.

**Comment by pedroSG94** [comment]
This means that server close connection. 
https://stackoverflow.com/questions/38016109/javax-net-ssl-sslexception-write-error-ssl-0x7f70604080-i-o-error-during-syst

Library line:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L509

You should receive this in onConnectionFailed callback. If you are not receiving it. Update library version.

**Comment by denebchorny** [comment]
I am updating right now the library. I will tell you how it's going.

**Comment by b95505017** [comment]
I received this exception when device turned offline, `onConnectionFailedRtmp` only thrown when `SocketException` happened, so I didn’t receive any callback, it just stuck there.

**Comment by denebchorny** [comment]
> I received this exception(SSLException) when device turned offline, `onConnectionFailedRtmp` only thrown when `SocketException` happened, so I didn’t receive any callback, it just stuck there.

What version of the library are you using?

**Comment by b95505017** [comment]
@denebchorny I always use latest version, you could see [the code](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L510-L520)
`SSLException` not belongs to `SocketException`, so it only be ignored.
