### ISSUE TITLE
Handling error messages

### ISSUE THREAD

**Issue by denebchorny** [pedroSG94/rtmp-rtsp-stream-client-java#330]
Hello sir, I would like to know what messages can the onConnectionFailedRtmp receive?

I would like to know if the messages are local, that is, generated by your library or are mixed where they can be generated by the library, by exceptions of the OS and / or possibly server responses?

I am trying to find the most the possible causes in which onConnectionFailedRtmp can be executed and thus take a measure as the case may be.

**Comment by pedroSG94** [comment]
Hi, You can see all onConnectionFailed cases here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java
Go this class and filter with onConnectionFailed. You will find 12 different cases.
