### ISSUE TITLE
Front camera switches to back camera when backgrounding and foregrounding app

### ISSUE THREAD

**Issue by Sermilion** [pedroSG94/rtmp-rtsp-stream-client-java#336]
When you switch to the front-facing camera, quit the app (background), and come back to the app again the camera switches back to the rear camera. Also, `RtmpCamera1#isFrontCamera()` still returns true even though rear camera is shown. How to preserve currently used camera when backgrounding and foregrounding app.

I tried to save state in presenter for currently used camera and call `switchCamera()` `onAttach` but this does not do anything because `onPreview` is `false` for some reason.

**Comment by Sermilion** [comment]
@mhackeras right, that's what I actually do. I have a local variable `isFrontCamera`. In `onAttach` I do `switchCamera()`. The problem is here: ```if (isStreaming() || onPreview) {
      cameraManager.switchCamera();
    }```  `onPreview` is false because I don's stop preview when I quit app. If I do `stopPreview()` and come back to app and call `startPreview()` for some reason preview is not shown. I guess if I would figure out why preview is not shown after I stop it, I might fix the issue.

**Comment by Sermilion** [comment]
@mhackeras Found the problem. Indeed, I saved the state but my problem was that I try to switch the camera back before `surfaceChanged` called. Thanks.

**Comment by mhackeras** [comment]
Why dont you save the current state of preview and when launch the app again @override on resume and check this. :)

**Comment by Sermilion** [comment]
@mhackeras @pedroSG94 even though saving the state of which camera was used before leaving the app works. But I still not satisfied with this solution as it seems like a bandaid. I would suppose that when I enter my app again, the camera switches back to the rear camera because a new Camera instance created. Not sure if that is what happens internally. I am sure that `RtmpCamera1` is not recreated in my app. Would you guys have any thought on this? Thank you
