### ISSUE TITLE
system ui has stopped when start record on emulator (phoenix Os)

### ISSUE THREAD

**Issue by Loxen9** [pedroSG94/rtmp-rtsp-stream-client-java#337]
close the error message and get it again close and get again

**Comment by pedroSG94** [comment]
Hi,
I never tried with phoenix OS. I dont know if this work.
Can you share me logcat error to know the problem?

**Comment by Loxen9** [comment]
Hi, 
no error on my app but (system ui has stopped ) on emulator  there is UI for the emulator made the emulator like windows and that's was stopped and restarted and stopped again while i'am recording 

i will check logcat and send to you
