### ISSUE TITLE
Stream with audio while microphone is being used

### ISSUE THREAD

**Issue by cvasquez-github** [pedroSG94/rtmp-rtsp-stream-client-java#338]
Hello, Is there a way to stream video and audio, while the microphone is already being used? Maybe streaming the system audio or be able to open the microphone again? (It is already open, by our video chat based in Tokbox)

Thanks!

**Comment by pedroSG94** [comment]
Hi,
You can try use secondary microphone (Normally all device have 2 microphones). If you only have a microphone you can't open it 2 times you only can use a instance at time.

https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/audio/MicrophoneManager.java#L52
Try replace "MediaRecorder.AudioSource.DEFAULT" with "MediaRecorder.AudioSource.CAMCORDER"

The other way is capture audio buffers from the other library and send it to my library (You need modify my library)
