### ISSUE TITLE
Weird view filter size in AndroidViewFilterRender

### ISSUE THREAD

**Issue by b95505017** [pedroSG94/rtmp-rtsp-stream-client-java#339]
https://drive.google.com/file/d/1kwH-2ynS7dfUI3sLLbjqzmrfFS5fdAgR/view?usp=sharing

In 1.3.8, real view and view filter aligns together.

**Comment by pedroSG94** [comment]
Do you means that in 1.3.8 this is working fine?

**Comment by b95505017** [comment]
Yes in 1.3.8 they are in the same position

**Comment by b95505017** [comment]
Just tried 1.5.0 works as well.

**Comment by b95505017** [comment]
I think maybe https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/29f4bee9efdc4351c3aa977ed2795f517e543285 causing this issue

**Comment by pedroSG94** [comment]
You are right. I'm doing a fix.

**Comment by pedroSG94** [comment]
Fixed in version 1.6.0
