### ISSUE TITLE
App not streaming

### ISSUE THREAD

**Issue by zameelpichen** [pedroSG94/rtmp-rtsp-stream-client-java#34]
The app i created without changing any code from this repo, is not uploading any data.

it simply establishes connection, and then does nothing.

**Comment by pedroSG94** [comment]
with gradle or manually?
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Add-library-to-your-project

**Comment by maan-smith** [comment]
I am facing the same issue. Auth connection is successful but streaming is not starting. I am using wowza auth rtmp custom. After providing the required credentials it successfully connects but after that noting happens and it does not start stream.
I have attached the logcat file. Hope you will help me finding the solution.
[Logcat.txt](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/1260084/Logcat.txt)

**Comment by pedroSG94** [comment]
That is all in logcat? 
In that logcat all is ok, after that you should see packets writed.
Can you tell me device and API?

**Comment by maan-smith** [comment]
Device: samsung G928t
Android version: nougat(24)

**Comment by pedroSG94** [comment]
You should see more logcat before the txt that you provided.
Can you post a more long logcat? (that don't show any issue)
After the connection you should see more log.

**Comment by maan-smith** [comment]
Can you please share with me the step to follow how to connect with wowza I will double check what I am missing?

**Comment by pedroSG94** [comment]
If you have wowza configured only need use project example and write your URL. No special code :(
Try without auth and with default activity.
I recomend you show me more logcat information if the problem persists.

**Comment by maan-smith** [comment]
Default activity is not working says auth error. 
And its now not connecting saying 
Connection failed: Application folder ([install-location]/applications/app-a988) is missing.

**Comment by maan-smith** [comment]
Still facing the same issue and a new issue mentioned above 
I am using the project example.
when i click start stream button it show auth success and then after some time it shows connect success and after that it show some output on wowza web but after a few seconds every thing on wowza become 0 i have attached both screen shots and a logcat from start stream button click till when the output become 0.

[Detailed Logcat.txt](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/1262517/Detailed.Logcat.txt)
  
![yes](https://user-images.githubusercontent.com/5314675/29857152-a1580eb6-8d70-11e7-9be0-75c1feefb049.png)

![no](https://user-images.githubusercontent.com/5314675/29857156-a2ebd3d4-8d70-11e7-8406-f83ecd4623cc.png)

**Comment by pedroSG94** [comment]
Disable auth on wowza and try. Maybe my auth is bugged for that version of wowza.
My last test was in:
Wowza Streaming Engine 4 Subscription Edition 4.6.0 build19395
You have more updated version:
Wowza Streaming Engine 4 Subscription Edition 4.6.0.03 build19948

Verify your server work with ffmpeg:
`ffmpeg -i pathtomp4file -f flv rtmp://yourendpoint`

Test with other device to discard device problems. 
If the problem persists with other device adn without auth requered I will install that version and test to debug.

**Comment by pedroSG94** [comment]
I test with last wowza version:
Wowza Streaming Engine 4 Trial Edition (Expires: oct 01, 2017) 4.7.1 build20635

Working with auth and without auth so I can discard server problems in this version.
I created a branch debug to get more info from your device. This could be the problem. Download the branch debug and show me a log please and test with other device to comfirm only that device get problems.

**Comment by maan-smith** [comment]
can you please set up a new stream for me might be i am doing something wrong while setting up a stream

https://cloud.wowza.com
Email: smithmaan706@gmail.com
password: github706

I have downloaded the debug branch and run it the logcat is attached below. still same issue 

[Logcat.txt](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/1264639/Logcat.txt)
[Logcat2.txt](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/1264640/Logcat2.txt)

**Comment by maan-smith** [comment]
@pedroSG94 Can you please respond?

**Comment by pedroSG94** [comment]
That is a cloud wowza. I'm not sure how to configure a cloud but normally wowza streaming engine is installed from here:
https://www.wowza.com/pricing/trial
Get trial free for 30 days here and install.

In Linux this is simple:
1) Execute the .run file downloaded.
2) Go to /usr/local/WowzaStreamingEngine-4.7.1/bin/ and execute startup.sh (with sudo)
3) (With startup.sh running)  Go to /usr/local/WowzaStreamingEngine-4.7.1/manager/bin/ and execute startmgr.sh
4) Go to brownser and access to server with http://ip:8080
5) When you logged in the server go to Applications > live > Source security > edit > disable auth required in rtmp and rtsp.
6) Use my library to stream in RTSP or RTMP. Example: rtmp://ip/live/mytest
7) Get stream with VLC or ffplay to confirm all is working. You can get stream with VLC example android in the readme of this project with other device but a recomend you use VLC desktop for more secure test.

**Comment by maan-smith** [comment]
can you made any modifications in library so that it will work for cloud wowza

**Comment by pedroSG94** [comment]
Yes, I will try.

**Comment by maan-smith** [comment]
Thanks I am waiting your feedback

**Comment by pedroSG94** [comment]
Cloud Wowza working in last ocmmit: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/73693e048d3c9012a1d4829aae2ad4d738e0d489

**Comment by maan-smith** [comment]
@pedroSG94 cloud wowza now working fine but the preview is rotated can you fix that

**Comment by pedroSG94** [comment]
No error. Go to options and modify the rotation. If you are using custom activities that is 0 by default but in portrait you need select 90 (selected in others activities because don't use the menu).
