### ISSUE TITLE
How to make a streaming video MIRRORing while using the front camera?

### ISSUE THREAD

**Issue by TapanM** [pedroSG94/rtmp-rtsp-stream-client-java#340]
is it available in the latest version(1.5.9)?

**Comment by pedroSG94** [comment]
You can change this line to true:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/res/layout/activity_open_gl.xml#L15

**Comment by TapanM** [comment]
Great. It worked. Thanks for the awesome library.
