### ISSUE TITLE
Can not streaming rtmp with camera1 on OnePlus2

### ISSUE THREAD

**Issue by TapanM** [pedroSG94/rtmp-rtsp-stream-client-java#341]
I try to live stream video with camera1 on oneplus2 device but the video cannot publish to server. The logs prints video packet size: 16. 

`D/RtmpConnection: wrote packet: RTMP Video, size: 16
D/RtmpConnection: wrote packet: RTMP Video, size: 16
D/RtmpConnection: wrote packet: RTMP Video, size: 16`

It is working in oneplus6t. Can you guide me to fix this for oneplus2?

I'm using LightOpenGlView.

**Comment by pedroSG94** [comment]
Size of 16 is probably because you only have the header in the packet. Also this could happens if you send a image totally black.
Do you have your screen totally black or you have preview?
Can you try with SurfaceView to discard a bug with OpenGl?

**Comment by TapanM** [comment]
I have preview and it is displaying totally fine but video being sent over the server is totally black.
I can try with SurfaceView but I need to keep aspect ratio. Let's first see if it is working with SurfaceView or not.

**Comment by TapanM** [comment]
Awesome. It worked with SurfaceView. How can I keep aspect ratio with SurfaceView? Face Detection is also not working. Is it something related to SurfaceView? How should I make sure that Face Detection works perfectly? I'm using Camera1 api. It is working with OnePlus6t but not OnePlus2.

**Comment by pedroSG94** [comment]
If this work with surfaceview this is an OpenGl fail I will try fix it.
If you want keep aspect ratio you can try with texteview that should work because it doesn't use OpenGl.
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/texturemodeexample/TextureModeRtmpActivity.java#L185
Face detection is a feature that I never finished because it isn't working with camera2 and I can't find a solution so it can be bugged.

**Comment by TapanM** [comment]
Awesome. I'll try with textureview.

**Comment by TapanM** [comment]
Yes, It's working with textureview but aspect ratio is bad compare to OpenGl. If you can fix OpenGl than it would be great.

**Comment by pedroSG94** [comment]
I did a fix in LightOpenGlView but I can't reproduce your case.
Can you test if this commit fix this issue?

**Comment by TapanM** [comment]
sure

**Comment by TapanM** [comment]
It's not working

**Comment by pedroSG94** [comment]
Ok, I will try find the error.
