### ISSUE TITLE
How to hot swap the streaming?

### ISSUE THREAD

**Issue by denebchorny** [pedroSG94/rtmp-rtsp-stream-client-java#342]
Hi sir. I would like to know if there is a way to change streaming orientation in hot swap.

I mean, there is a method to change streaming orientation but only when preparing streaming:
rtspCamera1.prepareVideo(width, height, fps, bitrate, hardwareRotation, **rotation**)) {

with this whe can define the streming orientation as Landscape or portrait but, is there a way to do it meanwhile streaming?

**Comment by pedroSG94** [comment]
You cna try with rotation filter:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L234
