### ISSUE TITLE
Avoid blink at Start Stream and Stream Freeze for first few seconds of the video

### ISSUE THREAD

**Issue by TapanM** [pedroSG94/rtmp-rtsp-stream-client-java#343]
Hi,

I'm using LightOpenGlView with camera1 API. When I called the startStream method, it blinks for a second and I guess because of that my streamed video freeze for a second at starts. I tried to use the same resolution for preview and stream but didn't work.

Can you suggest me how to avoid this?

I appreciate your efforts for the library. Keep up Good work.

**Comment by pedroSG94** [comment]
For now, it isnt possible because I'm reopen camera to change resolution that was used in startPreview.
But I will try find a way to no reopen it if you use same resolution in startPreview and in prepareVideo.

**Comment by pedroSG94** [comment]
Now you can avoid freeze. You need the last commit.
For this you need use same resolution in startPreview and in prepareVideo method

**Comment by TapanM** [comment]
Awesome. It is working. Can you please release new version in gradle?
