### ISSUE TITLE
Android audio streaming happens stop for a moment at regular intervals by iOS and Safari

### ISSUE THREAD

**Issue by FujiKinaga** [pedroSG94/rtmp-rtsp-stream-client-java#344]
Hello sir. I'm using your library for audio streaming app(especially using `OnlyAudioBase.java`).
But I have a problem.
When I broadcast Rtmp stream and convert to Hls by Wowza server, we can't enough listen by iOS(AVPlayer) and also Safari Player.

```
1. Stream by iOS(RTMP) to Receive by Android(HLS) : 🙆‍♀️
2. Stream by iOS(RTMP) to Receive by iOS(HLS) : 🙆‍♀️
3. Stream by android(RTMP) to Receive by Android(HLS) : 🙆‍♀️(Using this library)
4. Stream by android(RTMP) to Receive by iOS(HLS) : 🙅‍♀️(Using this library)
```

Maybe, it seems to be related to wowza's `cupertinoChunkDurationTarget` setting.
If set `1000`, audio stops at 1000ms intervals. If set `5000`, audio stops at 5000ms intervals...

Is there a way to improve this problem?

**Comment by pedroSG94** [comment]
Try use VLC player to discard player probems. If your stream work without change protocol and with VLC I can't do anything. This is wowz configuration and I don't know so much about it.

**Comment by FujiKinaga** [comment]
Hi, @pedroSG94 .
Thanks for your response.
When I listen to my stream by VLC Player, there was no problem.

 > I can't do anything.

I see...😭
