### ISSUE TITLE
messenger curently recording audio MY_APP_NAME will not able stream ... i changed audio source and same problem 

### ISSUE THREAD

**Issue by Loxen9** [pedroSG94/rtmp-rtsp-stream-client-java#345]
cannot record or stream while the mic used by other application like messenger

**Comment by Loxen9** [comment]
cannot record or stream while the mic used by other application like messenger

**Comment by pedroSG94** [comment]
I can't do anything about this the only way is use the secondary microphone and not always work:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/338

**Comment by Loxen9** [comment]
yes please disable audio recording and allow record screen without audio
