### ISSUE TITLE
Provide some methods for Eye Movement Tracking

### ISSUE THREAD

**Issue by divyashamar** [pedroSG94/rtmp-rtsp-stream-client-java#346]
Hey! first of all I want thank you guys for this helpful library. As per my projects current requirement. Can you please add Eye Tracking in library (i.e. eye's moving direction) that would be a great help for me, and please reply soon if this is possible.

Thanks 
DIVYA PRAKASH
email : divyaprakash007@gmail.com
WhatsApp : +91-7983629622

**Comment by pedroSG94** [comment]
Hi,

Unfortunately this is not possible. 
I only know a library that allow you detect eye position and if this eye is open or close but no movement tracking. Anyway implement that feature is too difficult so it will take so much time. For now, I prefer do other features.

**Comment by divyashamar** [comment]
Okay, please suggest library that can help in detecting eye position (Open/Close).

**Comment by pedroSG94** [comment]
https://developers.google.com/vision/
