### ISSUE TITLE
srteaming fps 

### ISSUE THREAD

**Issue by wkl-coder** [pedroSG94/rtmp-rtsp-stream-client-java#347]
How can I get real-time FPS？

**Comment by pedroSG94** [comment]
Each time this method is called you get a new frame: 
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L673

You can create an interface that is called when that method is executed and calculate fps with that.
