### ISSUE TITLE
using RTSP to stream h.265 to "wowza streaming engine" server

### ISSUE THREAD

**Issue by wsw2435** [pedroSG94/rtmp-rtsp-stream-client-java#350]
Hi everyone, would you mind helping on this issue?

I am using the Wowza streaming engine on my pc as the server, and this android app to broadcast a video. How do I make it to stream H.265 video by "Default RTSP" button function to my server? Thank you.

**Comment by pedroSG94** [comment]
If you want use H265 RTSP you only need use this method before prepareVideo:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtsp/RtspCamera1.java#L117

**Comment by wsw2435** [comment]
> If you want use H265 RTSP you only need use this method before prepareVideo:
> https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtsp/RtspCamera1.java#L117

Dear Pedro, 
where should I place `rtspCamera1.setVideoCodec(VideoCodec.H265);` in **ExampleRtspActivitt.java** ? I keep crashing the app after I tried a few positions.

**Comment by pedroSG94** [comment]
In this line:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/defaultexample/ExampleRtspActivity.java#L56

Share crash logcat if you can to see error reason

**Comment by redknight-test** [comment]
can you provide the exact location and the line of the script where it should be changed to get H265 video

**Comment by pedroSG94** [comment]
This is the method:
https://github.com/pedroSG94/RootEncoder/blob/master/library/src/main/java/com/pedro/library/rtsp/RtspCamera1.java#L137
This is the line to use it:
https://github.com/pedroSG94/RootEncoder/blob/master/app/src/main/java/com/pedro/streamer/defaultexample/ExampleRtspActivity.java#L75
The result should be like this:
```java
    rtspCamera1 = new RtspCamera1(surfaceView, this);
    rtspCamera1.setVideoCodec(VideoCodec.H265);
    rtspCamera1.setReTries(10);
    surfaceView.getHolder().addCallback(this);
}
```
Remember that you need to import rtsp VideoCodec:
```java
import com.pedro.rtsp.rtsp.VideoCodec;
```
You can apply the same logic for rtmp, srt and rtsp in all examples (call the method after create the instance and before call preparevideo method)

**Comment by redknight-test** [comment]
I have done the above changes but still iam getting `H264.
pas@pas-Z690M-AORUS-ELITE-AX-DDR4:~$ ffplay -rtsp_flags listen -i rtsp://192.168.0.110:2222/app/stream
ffplay version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2003-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, rtsp, from 'rtsp://192.168.0.110:2222/app/stream':f=0/0   
  Metadata:
    title           : Unnamed
    comment         : N/A
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(tv, unknown/bt470bg/unknown, progressive), 1080x2340, 90k tbr, 90k tbn, 180k tbc
  Stream #0:1: Audio: aac (LC), 44100 Hz, stereo, fltp
  17.53 A-V:  3.063 fd= 251 aq=    0KB vq=    0KB sq=    0B f=0/0 `

**Comment by redknight-test** [comment]
The resolution is coming up as width*height, it should come up as 1920*1080 but its coming up as below  duration and bitrate is coming up as N/A,   
Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: hevc (Main), yuv420p(tv, unknown/bt470bg/unknown), 1080x1920, 90k tbr, 90k tbn, 90k tbc
  Stream #0:1: Audio: aac (LC), 44100 Hz, stereo, fltp
  11.87 A-V:  0.002 fd=   2 aq=   47KB vq=  794KB sq=    0B f=1/1

**Comment by pedroSG94** [comment]
Hello,

The resolution 1080x1920 is because you are streaming in portrait so the library rotate resolution. You can try rotate it using rotation value of prepareVideo method
About duration and bitrate. I'm not sure about it because this also depend of the server used. 
- Is the streaming working fine anyway? 
- Can you share me prepareVideo method parameters used?

**Comment by redknight-test** [comment]
Streaming is working fine, but how i can confirm the bitrate?

**Comment by pedroSG94** [comment]
In the stream side you can check it in the onNewBitrate callback:
https://github.com/pedroSG94/RootEncoder/blob/master/app/src/main/java/com/pedro/streamer/defaultexample/ExampleRtspActivity.java#L102
In server/player side this depend of the software used so I can't guide you because each one can use their own way.
For example using VLC as player you can check it in tools -> media information -> statistics. This post maybe can help you:
https://techviral.net/check-videos-bitrate-in-vlc/

**Comment by redknight-test** [comment]
But iam unable to play the the stream in VLC or OBS studio, may i know the steps to stream in VLC or Obs-studio

**Comment by pedroSG94** [comment]
Try this way for VLC:
https://www.thewindowsclub.com/how-to-play-rtsp-stream-in-vlc-media-player

**Comment by redknight-test** [comment]
iam unable to stream in VLC,  in the app iam using the endpoint as rtsp://192.168.0.110:2222/app/stream and in the VLC Media Network STream iam using url rtsp://192.168.0.110:2222/app/stream the error is, 
00007f60e80010f0] live555 demux error: Failed to connect with rtsp://192.168.0.110:2222
[00007f60e8002f30] main stream error: connection failed: Connection refused

**Comment by pedroSG94** [comment]
Are you using the same url than in ffmpeg and the same PC? It should work with the same url
If you have wowza server instaled in the same PC where you use VLC you can try replace your IP to localhost or 127.0.0.1

**Comment by redknight-test** [comment]
Iam selecting Custom RTSP in device and the end points are rtsp://192.168.0.110:2222/app/stream
In VLC in Network iam using, rtsp://192.168.0.110:2222/app/stream 
its not working

**Comment by pedroSG94** [comment]
I don't know then. Maybe you can try ask on VLC forum or also you can try get bitrate in wowza server side but I don't know how to do it. I think you will need ask on official forums or try to find it yourself
