### ISSUE TITLE
streaming show question

### ISSUE THREAD

**Issue by 544531645** [pedroSG94/rtmp-rtsp-stream-client-java#352]
The live broadcast is not a mirror reflection, as opposed to the mobile phone display, how to make the live broadcast is also a mirror

**Comment by pedroSG94** [comment]
Are you using lighopenglview or openglview?

**Comment by 544531645** [comment]
only default @pedroSG94

**Comment by 544531645** [comment]
use demo defaultRtmp

**Comment by pedroSG94** [comment]
If you use surfaceview or textureview with front camera youwill have that result.

Try with opengl rtmp.
