### ISSUE TITLE
Problems with example application against virtualized Wowza server

### ISSUE THREAD

**Issue by adrianrejas** [pedroSG94/rtmp-rtsp-stream-client-java#353]
Hi,

I'm trying your library using the test application for streaming camera to a Wowza server installed on a virtual machine and I've experimented problems for getting a robust streaming.

What happens is that the stream always starts correctly, and the incoming streams interface of the Wowza console shows the new streaming and the throughtput statistics seems to be correct. But when I play the stream on a player (I use VLC most of times, but other web-based players have also been tested) I'm able to establish the outgoing stream just 5-6 times of every 10. The other times the VLC player seems to detect a stream, but keeps it loading forever.

I've test with almost every option of the application: both RTMP and RTSP, H.264 and H.265, different resolutions from 1920x1080 to 320x240, audio on and off, 15 and 30 frames per second ... But always happens the same.

I'm in a LAN and connectivity doesn't seem to be a problem. I've tested to stream using RTSP with another library to the same virtualized Wowza server, the same network and the same VLC player and it works fine.

Maybe it could be something related with Wowza configuration. Can a special configuration in Wowza server be required?

Thanks in advance.

**Comment by pedroSG94** [comment]
This is so rare.. I never have seen that.
Did you test with rtmp?

**Comment by adrianrejas** [comment]
Yes, I've tested with RTMP. It seems to work a bit better, but almost the same. Wowza version is 8.7.4. The only changes done to default configuration were some changes at HLS configuration, but it's not being used at the scenario I'm using.

Now I'm in the middle of another thing, but maybe in some days I'll be able to repeat the test and get verbose logs from VLC.

**Comment by pedroSG94** [comment]
I need download the last version. I was testing in a server with this version: 4.6.0 build19395.
All work fine I can reproduce stream all times.

**Comment by adrianrejas** [comment]
Sorry, Wowza version is 4.7.4, my fault

**Comment by adrianrejas** [comment]
Sorry for not having update status about this problem in the last days.

I've tested a couple of times in the last weeks and It wasn't possible to reproduce the problem.

I keep on testing from time to time and if I'm able to reproduce it again I'll take logs and share them.
