### ISSUE TITLE
RTSP Streaming stopped when the Activity is in background (onPaused, onStop)

### ISSUE THREAD

**Issue by myt06** [pedroSG94/rtmp-rtsp-stream-client-java#357]
Hello, we developed a streaming app using this library, using the rtsp protocol and our server is on wowza, the streaming running ok until we want to share the stream, because the activity is in background when the share dialog appear, the stream stopped (onDisconnectRtsp() callback method called), how can i keep the stream running? Thank you in advance

**Comment by pedroSG94** [comment]
This is related with preview lifecycle. If you want stream in background you need do it without preview with this constructors:
-Camera1:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L95
-Camera2:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera2Base.java#L88
Remember that you should use it in a service to keep stream alive.

If you want to use preview while you are in foreground and keep stream in background. There isnt specific way to do it but you can try with this solution::
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/318

**Comment by myt06** [comment]
ok, I'll try, thanks for your answer

**Comment by myt06** [comment]
hello, I've implemented the service using intentservice and service, but i got the same result, when i minimize the app, the disconnected callback doesnt called, but the stream when blank, how to solve it?

**Comment by myt06** [comment]
the problem when the activity is in background is the socket is closed, it there any way to keep it open and keep the connection to the server alive? I already start the stream in a service

**Comment by pedroSG94** [comment]
Hi,
Are you using a background stream object without preview? (camera2 or camera1 with context, display mode or fromfile mode).

Remember allow background use if your device is Android 8.0+
I will create an example today with camera2.

**Comment by pedroSG94** [comment]
Test my new activity example:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/master/app/src/main/java/com/pedro/rtpstreamer/backgroundexample

**Comment by myt06** [comment]
Hello,
Yeah I use stream without preview, I used the preview feature before, but now I remove it, btw I'm using OpenGlView that you provided and used Camera1, but I already tried both, I use rtsp endpoint and the server is in wowza.
I use real device with API 23 (Android 6.0 Marshmallow) for testing.

Thanks for your example, I already implemented that kind of service, I've tried using IntentService and Foreground service, just now I tried your example and implemented it in my app, but it still give blank streaming, or the stream is stopped. It seems the service is still running just fine, but the streaming it self stopped, and the method for disconnected is not called.
Any idea whats happen Sir?

**Comment by myt06** [comment]
Hi, I just try your example in your own app example, and what do you mean by no preview is the camera not showing the streaming progress? which is not live streaming here? So, it doesn't support live streaming then? Because in my case the stream server is still running when using service but the live streaming progress is terminated.
