### ISSUE TITLE
VR mode record

### ISSUE THREAD

**Issue by mhackeras** [pedroSG94/rtmp-rtsp-stream-client-java#359]
I was thinking of adding a good vr mode record..
Screen splits in half creating two screens with same frames..
is it possible to cut video frams in half so we can one screen?

**Comment by pedroSG94** [comment]
Yes, This should be easy with a filter.
Do you mean cardboard mode filter?

**Comment by mhackeras** [comment]
I mean i wanna keep only one half of the screen and place it in frame.

**Comment by mhackeras** [comment]
screen is like this 
https://youtu.be/0ZudnGfMgN0
i wanna keep in record only half the screen. so as to avoid the second screen..
what do you think?

**Comment by pedroSG94** [comment]
The problem is that you need 360 content to get this effect you can't sobit with a normal camera frame. 
The effect is easy the problem is sensor implementation to move camera. (Sensor implementation is really hard to develop)

**Comment by mhackeras** [comment]
No pedro i think you misunderstand me... i just want to record the mobile screen.. but when you use real vr screen splits in two screens for 3d purposes. i just wanna record one screen not both.

**Comment by pedroSG94** [comment]
Record only a selected device screen area?
Yes this is possible. This is interesting i will try develop it.

**Comment by mhackeras** [comment]
Do you want to point me on something so i can do it and copy here the code.
it would need to crop the frame right?

**Comment by pedroSG94** [comment]
You can try modify this method:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/utils/gl/PreviewSizeCalculator.java#L11

If you change values in GLES20.glViewport line you should get a frame cropped. 
If this isnt working, you need play with matrix to change it.
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/gl/render/ScreenRender.java#L23

**Comment by pedroSG94** [comment]
Ok, you can do it only if you modify glviewport.
You can extend viewport to crop frame. For example (10x10 screen size)
```java
glviewport(0, 0, 10, 10); //this means record all screen like Im doing now
glviewport(0, 0, 10 * 2, 10 * 2); //this means record fourth part of screen because the other part is off screen so it is discarded.
```

**Comment by mhackeras** [comment]
found an easy way by changing values on classes you point. but will try this too.
Will report very fast

**Comment by mhackeras** [comment]
@pedroSG94  tried your way but it gives me bad result.. also i test on landscape.
tried by changing only width but it is streched.
so what i did and worked is:
1. set glsurface in half size from displaybase.
2. and in ScreenRender Class i use this PreviewSizeCalculator.calculateViewPort(true, width*2, height, streamWidth, streamHeight);
keep aspect ratio and Previewwidth * 2

and this crops half screen and also set it in the center with correct values but it doesnt fill the screen.. not that this is bad.
