### ISSUE TITLE
RTMP only audio stream

### ISSUE THREAD

**Issue by dineshbiwall** [pedroSG94/rtmp-rtsp-stream-client-java#362]
C:\WINDOWS\system32>ffmpeg -f flv -listen 1 -i rtmp://192.168.43.139:8888/live/app -c copy -f flv -listen 1 -c 1 C:\VED\ved\freelance.wav
ffmpeg version 4.1.3 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.3.1 (GCC) 20190414
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
rtmp://192.168.43.139:8888/live/app: I/O error

Hello guys i am getting I/O error when connect and start to stream audio. The message type is abort and then crash the app. Help me asap

Thanks

**Comment by pedroSG94** [comment]
Ffmpeg server send an unexpected packet in connection. I will try find reason.

**Comment by pedroSG94** [comment]
Fixed in this commit:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/9d125a33e88a2f9f0b3a3f1756c1d65deaa2344d
Read this comment to know more info about the problem:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/9d125a33e88a2f9f0b3a3f1756c1d65deaa2344d#diff-3b00316a89fdca670b75dba01357fea4R583
