### ISSUE TITLE
rtsp address issue

### ISSUE THREAD

**Issue by change1** [pedroSG94/rtmp-rtsp-stream-client-java#363]
i am a beginning learner,
now i have a issue as below:

rtspCamera1.startStream("rtsp://yourEndPoint");
where is rtsp address from ? just ip+port+url ? or from rtsp server ?

if anyone could help me ?
 thanks inadvance.

BR.

**Comment by pedroSG94** [comment]
Like this:
rtsp://192.168.1.120:554/live/app

Where:
192.168.1.120 -> rtsp server ip
554 -> rtsp port of server configured for stream
live -> application name used in your server (normally named live by default)
app -> Any ramdom string

**Comment by change1** [comment]
thank you very much :)
