### ISSUE TITLE
JAR Version of Library

### ISSUE THREAD

**Issue by tgb20** [pedroSG94/rtmp-rtsp-stream-client-java#364]
I would like to use this library for a special project where I cannot use gradle. Is there a way to get the .jar version of this library with its dependencies?

**Comment by pedroSG94** [comment]
I only have 2 ways to compile project:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Add-library-to-your-project
If you want you can try compile in a .jar yourself. Maybe this post could help you:
https://stackoverflow.com/questions/21712714/how-to-make-a-jar-out-from-an-android-studio-project

**Comment by tgb20** [comment]
I solved this by building the project into their .aar files from Android Studio. From there I unarchived the .aar files and extracted the built .jars for the classes.
