### ISSUE TITLE
Endpoint malformed when trying rtsp url with auth

### ISSUE THREAD

**Issue by zhengxiangwen** [pedroSG94/rtmp-rtsp-stream-client-java#366]
Hello, I am trying to use this library.
But while I am trying to use it like,
rtsp://user:pass@ip:port/appname/streamname
And I am getting this error:
Endpoint malformed, should be: rtsp://ip:port/appname/streamname

I've seen a similar problem. [https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/108](url)
But it's rtmp, not rtsp, What should I do? Can you change it to support the RTSP? Thank you very much!

**Comment by pedroSG94** [comment]
You should set auth with this method:
```java
//Call it any time before startStream()
rtspCamera1.setAuthorization(user, password);
```

**Comment by zhengxiangwen** [comment]
Is auth developed to work with Wowza? 
On your demo,I fill the address with "rtsp://192.168.1.168:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1", and set auth with "rtspCamera1.setAuthorization(user, password);"
When I click "Start stream", the log show error:
java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)

What should I do? Thank you very much!

**Comment by pedroSG94** [comment]
Yes, auth is working with wowza (RTSP and RTMP).
I think that your endpoint is wrong (why this?: ?transportmode=unicast&profile=Profile_1).

Did you try with ffmpeg? If yes, share me your command and I will adapt you the command to library code.
