### ISSUE TITLE
AndroidViewFilter size

### ISSUE THREAD

**Issue by mhackeras** [pedroSG94/rtmp-rtsp-stream-client-java#368]
Is there any chance we can resize AndroidViewFilter?

**Comment by pedroSG94** [comment]
You can modify your view setted to filter and result will be added to the filter.
For example, you can change background color or resize with layoutparams.
Or maybe do you want resize only view in filter without modify the original?

**Comment by mhackeras** [comment]
Yeah it would be better to resize view like imageobject.
i extended AndroidViewFilter to BaseObjectFilterRender but setscale doesnt work :/

**Comment by mhackeras** [comment]
Also setposition would be good. :/

**Comment by pedroSG94** [comment]
I'm looking a way to do it but maybe it is not possible because with this filter I'm using canvas of the view and I can't do a copy to preserve original view

**Comment by mhackeras** [comment]
can we set the position when we draw on canvas?

**Comment by pedroSG94** [comment]
Sorry for late response. I will add this feature.

**Comment by pedroSG94** [comment]
Position, rotation and scale added to androidviewfilter. For now, gesture controller is not added to androidviewfilter but I will add it in the future.
