### ISSUE TITLE
RTMP unknown encoder 

### ISSUE THREAD

**Issue by dineshbiwall** [pedroSG94/rtmp-rtsp-stream-client-java#369]
ffmpeg -f flv -listen 1 -i rtmp://192.168.43.139:8888/live/app -acodec aac -f s32le -ar 32000 -c 1 C:\VED\ved\freelance.aac
ffmpeg version 4.1.3 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.3.1 (GCC) 20190414
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, flv, from 'rtmp://192.168.43.139:8888/live/app':
  Duration: 00:00:00.00, start: 0.166000, bitrate: N/A
    Stream #0:0: Subtitle: text
    Stream #0:1: Audio: aac (LC), 32000 Hz, stereo, fltp
Unknown encoder '1'

Sometime getting this error 

[tcp @ 00000164cfcea780] RTMP packet size mismatch 11565963 != 3414999
[tcp @ 00000164cfcea780] RTMP packet size mismatch 7886877 != 2845361
Input #0, flv, from 'rtmp://192.168.43.139:8888/live/app':
  Duration: 00:00:00.00, start: 0.170000, bitrate: N/A
    Stream #0:0: Subtitle: text
    Stream #0:1: Audio: aac (LC), 32000 Hz, stereo, fltp
Unknown encoder '1'

Hello I am getting unknown encoder '1' issue. help me 

Thanks

**Comment by pedroSG94** [comment]
I'm checking it. I did a test with last commit and it is working for me but .aac file is unreachable

**Comment by dineshbiwall** [comment]
File is created but nor play and when stop streaming then getting "Error reading packet: Unexpected EOF reached before read buffer was filled"
