### ISSUE TITLE
RTSP to machine/server ?

### ISSUE THREAD

**Issue by the-information-guy** [pedroSG94/rtmp-rtsp-stream-client-java#37]
Hey,

Just wondering if you could help me out.
I am trying to find a free RTSP server (that handles UDP) or a FFMPEG command so I can watch the RTSP stream.

```
RtspBuilder rtspBuilder = new RtspBuilder(surfaceView, Protocol.UDP, this);
if (rtspBuilder.prepareAudio() && rtspBuilder.prepareVideo()) {
    rtspBuilder.startStream("rtsp://10.0.0.18:5000/Test");
} else {
    Log.d("error","encoding");
    /**This device cant init encoders, this could be for 2 reasons: The encoder selected doesnt support any configuration setted or your device hasnt a H264 or AAC encoder (in this case you can see log error valid encoder not found)*/
}
```

`ffplay -rtsp_flags listen -i rtsp://10.0.0.18:5000 -rtsp_transport udp`

This ffplay command works and the logs say I am connected but I cannot see any video from it even though I can see the UDP packets coming (from TCPDUMP).

I cannot really find a working example in your application.
What do you recommend to use with your lib ?

**Comment by pedroSG94** [comment]
I use wowza media sever. You can get a free trial for 30 days here:
https://www.wowza.com/pricing/trial

I never tested RTSP with other media server :(. If you find other server working let me know, if crash let me know too for implement support for it.

**Comment by the-information-guy** [comment]
I just tried Wowza Media Server.

`rtspBuilder.startStream("rtsp://10.0.0.14:554/live");`

Everything is working fine, the packets are sent to the server : 

```
08-24 10:57:40.158 26650-26851/RtpSocket: send packet, 378 Size, 6972 Port
08-24 10:57:40.169 26650-26846/RtpSocket: send packet, 975 Size, 6970 Port
```

Now, i don't know how to actually play the stream in VLC or Ffplay for example.

If I try to play with `rtsp://10.0.0.14:554/live` or `rtsp://10.0.0.14:6970/live` it is not working.

Wowza is in default configuration. What URL should I use to play it ?

Many thanks.

**Comment by pedroSG94** [comment]
First of all your URL isn't correct. You should specify a stream name like:
rtsp://10.0.0.14:554/live/yourstreamname

For VLC use my project example, you can get the link in the readme. Ffplay command look correct I think the URL was the problem.
