### ISSUE TITLE
Main/High Profile support?

### ISSUE THREAD

**Issue by haisk** [pedroSG94/rtmp-rtsp-stream-client-java#375]
Hi

How can I set the h264 profile to Main or High profile instead of default Baseline profile?

**Comment by pedroSG94** [comment]
try add this line to [videoFormat](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L109):
```java
videoFormat.setInteger(MediaFormat.KEY_PROFILE, MediaCodecInfo.CodecProfileLevel.AVCProfileMain);
```
Anyway, normally it is not supported by devices so this will be ignored.

**Comment by haisk** [comment]
Thanks

**Comment by mkrn** [comment]
@pedroSG94  why is it not supported?
On Pixel 4 (top Google Device) It's streaming using Baseline profile and level 1.0  which I believe is causing playback problems on iPhone 

Can this be added as an option (Set without changing library code?)

**Comment by pedroSG94** [comment]
You can do it with this prepare video:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera2Base.java#L206

**Comment by mkrn** [comment]
Thanks, I see it now! 

Does this make sense?
```         return rtmpCamera2.prepareVideo(1280, 720, VIDEO_FPS, 2000 * 1024, false, 2, CameraHelper.getCameraOrientation(this), MediaCodecInfo.CodecProfileLevel.AVCProfileHigh, MediaCodecInfo.CodecProfileLevel.AVCLevel41)
```
Seems like Profile and Level are of same kind?

**Comment by pedroSG94** [comment]
That is correct.
Maybe i should create an enum to avoid confusion.
Remember that this could be ignored by your encoder if not supported or fail doing configure. In this last case you will get a return false in prepareVideo.
