### ISSUE TITLE
Retry race condition?

### ISSUE THREAD

**Issue by b95505017** [pedroSG94/rtmp-rtsp-stream-client-java#376]
```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void java.net.Socket.close()' on a null object reference
com.github.faucamp.simplertmp.io.RtmpConnection.shutdown
com.github.faucamp.simplertmp.io.RtmpConnection.close
com.github.faucamp.simplertmp.DefaultRtmpPublisher.close
net.ossrs.rtmp.SrsFlvMuxer.disconnect
net.ossrs.rtmp.SrsFlvMuxer.access$1000
net.ossrs.rtmp.SrsFlvMuxer$3.run
java.lang.Thread.run (Thread.java:764)
```

**Comment by pedroSG94** [comment]
I tested and it is working. Can you share me example code to reproduce error?

**Comment by b95505017** [comment]
it happens randomly. I noticed that you place `reTry(5000)` on [UI thread](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/defaultexample/ExampleRtmpActivity.java#L72), is it necessary? Because I use same thread with callback currently

**Comment by pedroSG94** [comment]
I use main thread to avoid sync problems. I will test without it and try reproduce the error.

**Comment by pedroSG94** [comment]
Fixed:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/d28930535d3a3f5466a132e397c176e91e0c822f

**Comment by b95505017** [comment]
Thanks. Did it mean that I could call `reTry(5000)` in the same thread with callback?
