### ISSUE TITLE
Remove filter

### ISSUE THREAD

**Issue by lakhanrathi65** [pedroSG94/rtmp-rtsp-stream-client-java#378]
Is there any way to remove filter from openGlView  in case of multiple filter applied

**Comment by pedroSG94** [comment]
Set no filter to that filter position:
```java
rtmpCamera1.getGlInterface().setFilter(0, new NoFilterRender());
```

**Comment by lakhanrathi65** [comment]
Hey Thanks for quick reply.
Yeah its work, Great library!
