### ISSUE TITLE
URL RTMP

### ISSUE THREAD

**Issue by nguyenanh1** [pedroSG94/rtmp-rtsp-stream-client-java#379]
I Use RTMP with URLL: rtmp://52.74.170.96/live/livestream and stream key(name): test123 
start stream errror disconnected

**Comment by pedroSG94** [comment]
Hi,
URL look fine. 
When you get a conexion error you should have reason in this callback:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/defaultexample/ExampleRtmpActivity.java#L71

I dont understand this: 
```java
stream key(name): test123
```
Is this an auth? In this case use this method to set auth: 
```java
rtmpCamera1.setAuthorization(user, password);
```

**Comment by nguyenanh1** [comment]
Hi,  yes stream name, when i input url rtmp://52.74.170.96/live/livestream/test123 and see log 
appname: live and stream name livestream/test123 leads to loss of connection
