### ISSUE TITLE
hi i find a error

### ISSUE THREAD

**Issue by 983045775** [pedroSG94/rtmp-rtsp-stream-client-java#38]
08-25 15:13:21.220 30796-30796/com.pedro.rtmpstreamer I/android.media.AudioRecord: startRecording
08-25 15:13:21.230 30796-30796/com.pedro.rtmpstreamer I/AudioRecordPermission: remindWithResult:false
08-25 15:13:21.240 30796-30796/com.pedro.rtmpstreamer I/AudioRecord: sendStateChangedIntent, state=3
08-25 15:13:21.240 30796-30796/com.pedro.rtmpstreamer I/MicrophoneManager: Microphone started
08-25 15:13:21.240 30796-30796/com.pedro.rtmpstreamer I/Choreographer: Skipped 34 frames!  The application may be doing too much work on its main thread.
08-25 15:13:22.050 30796-31612/com.pedro.rtmpstreamer I/System: core_booster, getBoosterConfig = false
08-25 15:13:22.050 30796-31612/com.pedro.rtmpstreamer I/System.out: [socket][3] connection /192.168.253.1:554;LocalPort=53544(3000)
08-25 15:13:22.050 30796-31612/com.pedro.rtmpstreamer I/System.out: [CDS]connect[/192.168.253.1:554] tm:3
08-25 15:13:22.060 30796-31612/com.pedro.rtmpstreamer I/System.out: [socket][/192.168.253.3:53544] connected
                                                                    
                                                                    [ 08-25 15:13:22.070  2643:31588 I/         ]
                                                                    [Grace_0.0.5.0][smartAf]af_doAF: flow: 0, giNumFlagDoAF: 1, afType: 1
08-25 15:13:22.100 30796-31612/com.pedro.rtmpstreamer I/RtspClient: RTSP/1.0 415 Unsupported Media Type
                                                                    Server: EasyDarwin/7.0.5 (Build/16.0518; Platform/Win32; Release/EasyDarwin; State/Development; )
                                                                    Cseq: 1
                                                                    Connection: Close
08-25 15:13:22.100 30796-31612/com.pedro.rtmpstreamer I/System.out: [CDS]shutdownInput in read
08-25 15:13:22.100 30796-31612/com.pedro.rtmpstreamer I/System.out: [CDS]shutdownInput in read
08-25 15:13:22.110 30796-31613/com.pedro.rtmpstreamer W/System.err: java.net.SocketException: sendto failed: EPIPE (Broken pipe)
08-25 15:13:22.110 30796-31613/com.pedro.rtmpstreamer W/System.err:     at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:572)
08-25 15:13:22.110 30796-31613/com.pedro.rtmpstreamer W/System.err:     at libcore.io.IoBridge.sendto(IoBridge.java:541)
08-25 15:13:22.110 30796-31613/com.pedro.rtmpstreamer W/System.err:     at java.net.PlainSocketImpl.write(PlainSocketImpl.java:506)
08-25 15:13:22.110 30796-31613/com.pedro.rtmpstreamer W/System.err:     at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:37)
08-25 15:13:22.110 30796-31613/com.pedro.rtmpstreamer W/System.err:     at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:266)
08-25 15:13:22.110 30796-31613/com.pedro.rtmpstreamer W/System.err:     at java.io.OutputStreamWriter.flushBytes(OutputStreamWriter.java:167)
08-25 15:13:22.110 30796-31613/com.pedro.rtmpstreamer W/System.err:     at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:158)
08-25 15:13:22.110 30796-31613/com.pedro.rtmpstreamer W/System.err:     at java.io.BufferedWriter.flush(BufferedWriter.java:124)
08-25 15:13:22.110 30796-31613/com.pedro.rtmpstreamer W/System.err:     at com.pedro.rtsp.rtsp.RtspClient$2.run(RtspClient.java:217)
08-25 15:13:22.110 30796-31613/com.pedro.rtmpstreamer W/System.err:     at java.lang.Thread.run(Thread.java:831)
08-25 15:13:22.110 30796-31613/com.pedro.rtmpstreamer W/System.err: Caused by: android.system.ErrnoException: sendto failed: EPIPE (Broken pipe)
08-25 15:13:22.110 30796-31613/com.pedro.rtmpstreamer W/System.err:     at libcore.io.Posix.sendtoBytes(Native Method)
08-25 15:13:22.110 30796-31613/com.pedro.rtmpstreamer W/System.err:     at libcore.io.Posix.sendto(Posix.java:206)
08-25 15:13:22.110 30796-31613/com.pedro.rtmpstreamer W/System.err:     at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
08-25 15:13:22.110 30796-31613/com.pedro.rtmpstreamer W/System.err:     at libcore.io.IoBridge.sendto(IoBridge.java:539)
08-25 15:13:22.110 30796-31613/com.pedro.rtmpstreamer W/System.err: 	... 8 more
08-25 15:13:22.260 30796-30796/com.pedro.rtmpstreamer I/android.media.AudioRecord: stopRecording
08-25 15:13:22.340 30796-30796/com.pedro.rtmpstreamer I/AudioRecord: sendStateChangedIntent, state=1
08-25 15:13:22.340 30796-30796/com.pedro.rtmpstreamer I/android.media.AudioRecord: stopRecording
08-25 15:13:22.340 30796-30796/com.pedro.rtmpstreamer I/AudioRecord: sendStateChangedIntent, state=1
08-25 15:13:22.340 30796-30796/com.pedro.rtmpstreamer I/MicrophoneManager: Microphone stopped
08-25 15:13:22.400 30796-30796/com.pedro.rtmpstreamer I/AudioEncoder: AudioEncoder stopped

**Comment by 983045775** [comment]
I don't know why

**Comment by 983045775** [comment]
![image](https://user-images.githubusercontent.com/13258336/29703507-6168807c-89a8-11e7-96f7-6c72e6fa364e.png)

**Comment by pedroSG94** [comment]
What media server are you using?

**Comment by pedroSG94** [comment]
Need develop RTSP connection with servers that URL need finish on .sdp

**Comment by pedroSG94** [comment]
EasyDarwin server working:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/3204f723a1393bc164c59f45954ef7a13b58d5a6
