### ISSUE TITLE
Streaming produce a black video+correct audio with Android 9 (pixel 3a)

### ISSUE THREAD

**Issue by EmmanuelVinas** [pedroSG94/rtmp-rtsp-stream-client-java#381]
I teste the sample app using my pixel 3a phone and several rtmp server (youtube, local server, twitch...) and the result stream result in a blank video + audio. 

I Looked a bit in the code, and it seems VideoEncoder::chooseVideoEncoder choose OMX.qcom.video.encoder.avc as an encoder in that case (c2.android.avc.encoder the 3 available for hardware seems to work fine). Also, there is a lot of "frame discarded", don't know whether it is related.

**Comment by pedroSG94** [comment]
Hello,
Can you test with Default RTMP, Opengl RTMP and Surface RTMP examples and tell me the result?
The library get video stream in 3 differents ways in that examples and we can discard problems with camera input data.
After that share me a logcat to get more info about the problem.

About frame discarded this is because you have a queue with video and audio frames (this is like a cache) it means that queue is full and you try set more frames to queue so library discard frames to preserve memory usage. Normally this is because you have a low bandwidth (you are generating frames more fast than you send to server) also you can see that if you take so much time to connect, but in this case this should be temporal.

**Comment by EmmanuelVinas** [comment]
Same result with Default, OpenGl and Surface. 

Here is the logcat. 
[rtpstreamer.txt](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/3432347/rtpstreamer.txt)

**Comment by pedroSG94** [comment]
Logcat look fine. Is your preview working in all modes?
Also we can try with other encoder. Set software video encoder with this line:
```java
//write this before preparevideo/audio methods
rtmpCamera1.setForce(CodecUtil.Force.SOFTWARE, CodecUtil.Force.FIRST_COMPATIBLE_FOUND);

```

**Comment by EmmanuelVinas** [comment]
Yes preview is working fine in all modes. 
```tmpCamera1.setForce(CodecUtil.Force.SOFTWARE, CodecUtil.Force.FIRST_COMPATIBLE_FOUND);
``` is working. 


Some information about codecs available in pixel 3a

SOFTWARE : OMX.google.h264.encoder

HARDWARE : 
Name: OMX.qcom.video.encoder.avc
Type: video/avc
Max instances: 16
----- Encoder info -----
Complexity range: 0 - 0
Quality range: 0 - 0
CBR supported: false
VBR supported: true
CQ supported: false
----- -----
----- Video info -----
Supported colors: 
2130708361
2135033992
19
21
20
39
Profile: 1, level: 65536
Profile: 65536, level: 65536
Profile: 8, level: 65536
Profile: 2, level: 65536
Bitrate range: 1 - 100000000
Frame rate range: 1 - 240
Width range: 96 - 4096
Height range: 96 - 2160

Name: c2.qti.avc.encoder
Type: video/avc
Max instances: 16
----- Encoder info -----
Complexity range: 0 - 0
Quality range: 0 - 0
CBR supported: false
VBR supported: true
CQ supported: false
----- -----
----- Video info -----
Supported colors: 
2130708361
2135033992
19
21
20
39
Profile: 1, level: 65536
Profile: 65536, level: 65536
Profile: 8, level: 65536
Profile: 2, level: 65536
Bitrate range: 1 - 100000000
Frame rate range: 1 - 240
Width range: 96 - 4096
Height range: 96 - 2160


HARDWARE WOrking
Name: c2.android.avc.encoder
Type: video/avc
Max instances: 32
----- Encoder info -----
Complexity range: 0 - 0
Quality range: 0 - 0
CBR supported: false
VBR supported: true
CQ supported: false
----- -----
----- Video info -----
Supported colors: 
2135033992
19
21
20
39
2130708361
Profile: 1, level: 16384
Profile: 65536, level: 16384
Profile: 2, level: 16384
Bitrate range: 1 - 12000000
Frame rate range: 0 - 960
Width range: 16 - 2048
Height range: 16 - 2048
----- -----
Max instances: 32

**Comment by pedroSG94** [comment]
We can try with your hardware encoder. Go to [VideoEncoder](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L85) and change to:
```java
videoEncoder = MediaCodec.createByCodecName("c2.android.avc.encoder");
```
After that test with Default, Surface and Opengl examples. If it is not working try with all encoders of  your commentary. I will do a little change in chooseVideEencoder to fix it.

**Comment by EmmanuelVinas** [comment]
c2.android.avc.encoder
Default / OpenGl : :heavy_check_mark: 
Surface / Texture : :negative_squared_cross_mark: preview and video muxing gets stuck. 

---
c2.qti.avc.encoder or OMX.qcom.video.encoder.avc
 Default/OpenGl/Surface : :negative_squared_cross_mark: preview is ok, but rtmp video is black

**Comment by pedroSG94** [comment]
I did a commit to exclude bugged codecs:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/59f51f3883cbc6f5598cfc6548807933f570a078
Check if conditional in is valid

**Comment by EmmanuelVinas** [comment]
I posted a comment on your fix. Let me know if you need more information. 
I tested using start record, and the video produced is fine. I'm wondering if it's not a SrsFlvMuxer issue.

**Comment by pedroSG94** [comment]
If this is working with that encoder it is possible. I will check it but without the device this look really hard.

**Comment by roxk** [comment]
With nokia 8.1 Android 9, the filter is breaking stuff for me since it incorrectly filters out the working `omx.qcom.video.encoder.avc`, it turns out the filter logic is missing a `()`, i.e.
```
if (name.equals("OMX.qcom.video.encoder.avc")
        || name.equals("c2.qti.avc.encoder") && Build.MODEL.equals("Pixel 3a"))
```
should be 
```
if ((name.equals("OMX.qcom.video.encoder.avc")
        || name.equals("c2.qti.avc.encoder")) && Build.MODEL.equals("Pixel 3a"))
```

@pedroSG94 Should I submit a PR for this or is this trivial for you to do it yourself? Thanks. I'd appreciate it if this can be fix asap as this is a major roadblock for me. Everything else works like a charm by the way, thanks for the work.

**Comment by pedroSG94** [comment]
fixed: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/9a315f7b09c919a09ed7c81b2afe288a5a5254bf

**Comment by roxk** [comment]
Thanks a ton!

**Comment by fabio-delorenzo-wowza** [comment]
My humble note is this is not a real solution to the problem but rather a work-around.
Indeed, there's no known issue with Pixel 3a and c2.qti.avc.encoder.
And I know for sure, using other SDKs, I can use this encoder.

I'm sure there's some parameter that we are missing and causes the encoder to skip creating any key frames (all the frames encoded are not keys).

The workaround definitely works but it might cause the loop to pick a software encoder that will degrade the performance.
Thanks

**Comment by pedroSG94** [comment]
You are right, but I haven't a Pixel 3a. This is my only way to solve this without a device to test it.
If you have a way to solve it you can create a PR.

**Comment by pedroSG94** [comment]
@fabio-delorenzo-wowza If you can, try this:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/net/ossrs/rtmp/SrsFlvMuxer.java#L882
To:
```java
if (nal_unit_type == SrsAvcNaluType.IDR || bi.flags == MediaCodec.BUFFER_FLAG_KEY_FRAME) {
```
Now, delete isValid conditional for Pixel 3a encoder:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/utils/CodecUtil.java#L262

Let me know if this is working and I will add this to rtmp and rtsp modules

**Comment by fabio-delorenzo-wowza** [comment]
@pedroSG94 I confirm that line fixes the issue. Awesome !! I still do not understand why the frame, from the header, doesn't look like a key frame, but MediaCodeInfo is right saying it's a KEY frame.
Thanks so much ! You saved me so much time !

**Comment by troy-lamerton** [comment]
The names of google's software encoders changed in a recent android version (api 28 maybe?). `c2.android.avc.encoder` might even be a hardwaer encoder.

https://github.com/thesingularitygroup/rtmp-rtsp-stream-client-java/commit/ea6ef0457fcda31155a389f396799fe0dda0288a
Updated the check in this commit, don't remember if I made a PR.

**Comment by troy-lamerton** [comment]
also google/ExoPlayer source code mentions the Pixel 3a model, don't remember exactly where though, probably in choosing a decoder.

**Comment by pedroSG94** [comment]
PIxel 3a codec fixed here: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/4be8f0a799510a988a4687b7dfeb3458863ba143
@troy-lamerton You didn't a PR. You can create a PR and I will do merge or I can add it myself.

**Comment by troy-lamerton** [comment]
@pedroSG94 I don't care about PR flow, you can add it.

**Comment by pedroSG94** [comment]
Added in this commit: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/683f9868ac5481ac95f6146167862640b22e970a
I will close both issues related with pixel 3a cause this is solved.

**Comment by bstrandjev** [comment]
I hate to be bringer of bad news, but, again on Pixel 3a, version 1.9.9, I get the same state (no video but ok audio). The software encoder did fix the video, but apparently the commits that were supposedly fixing no longer work. 

I am using SurfaceView and am running latest android.

**Comment by pedroSG94** [comment]
This is weird, according with the post it should work checking buffer info to detect keyframes.
Can you check if this line is called?:
Rtmp:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/net/ossrs/rtmp/SrsFlvMuxer.java#L943
Rtsp:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtsp/src/main/java/com/pedro/rtsp/rtp/packets/H264Packet.kt#L35
If that line is not called then the fix is not working. If you can share me a logcat to know type/nal_unit_type values it could help to fix the error.
Anyway I will add codec filter for Pixel 3a if it is not possible to fix.

**Comment by bstrandjev** [comment]
Regretfully, there is no error visible in logcat. I am streaming using rtmp. The line you showed is being called and some frames come in as keyframes.

**Comment by bstrandjev** [comment]
Give it a rest for a bit. This might be an issue with our rtmp server / side. I will need some time to verify that. Weird thing is that this issue is still happening only on Pixel 3a out of the about 10 phone models I have at hand.

**Comment by pedroSG94** [comment]
Maybe you have a similar problem in server side that I had in my side.
Is possible that keyframes is not detected in your server as keyframe? Remember that header nal type is not marked as keyframe for that reason I check it in MediaCodec.BufferInfo flag
