### ISSUE TITLE
Draw on using paints or other option

### ISSUE THREAD

**Issue by lakhanrathi65** [pedroSG94/rtmp-rtsp-stream-client-java#384]
So here is my requirement 
when video is stream is there any way to indicate some object by drawing circle around it and pointing arrow  to it like paint
I tried to add filter by extend BaseFilterRender class  but I failed .
So can you add this option to library 

Thanks.

**Comment by pedroSG94** [comment]
You can create a png with photoshop and add to stream with an imagefilter. Then you can resize and move to object position

**Comment by bhavinatharva** [comment]
@pedroSG94 

Can we have alternate option to achieve this?

**Comment by pedroSG94** [comment]
Hello,

First of all, avoid write in dead issues. Open a new issue and refer to this issue if you think that it is necessary.

Currently you have ways to do it.
You can use a SurfaceFilterRender render which can be renderer using canvas.
Other alternative is create a custom view, draw into the view using canvas and add the view using a XML with AndroidViewFilterRender.
Of course, both filters support draw on fly

**Comment by bhavinatharva** [comment]
Hello,

Thank you for your response and the clarification. I appreciate the guidance regarding issue handling and the options you've shared. I'll explore both the SurfaceFilterRender and the AndroidViewFilterRender approaches as suggested.

Thanks again!
