### ISSUE TITLE
Can I write my own buffer to streaming without cameraview ?

### ISSUE THREAD

**Issue by 1612052** [pedroSG94/rtmp-rtsp-stream-client-java#386]

**Comment by pedroSG94** [comment]
Yes. You can use this samples.
RTMP (you only need use SrsFlvMuxer class):
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtmp/RtmpCamera1.java
RTSP (You only need use RtspClient class):
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtsp/RtspCamera1.java

**Comment by 1612052** [comment]
I tried a lot but I my buffer from MediaCodec and MediaProjection is not type of SrsFlvMuxer's input. Plz give me some advices.

**Comment by pedroSG94** [comment]
You need encode to h264.
You have an example with media projection and video encoding in this classes:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/DisplayBase.java

https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java

**Comment by 1612052** [comment]
t
