### ISSUE TITLE
RtmpCamera1 initialization takes 1 second.

### ISSUE THREAD

**Issue by Sermilion** [pedroSG94/rtmp-rtsp-stream-client-java#388]
I have noticed what when I enter my streaming screen, it would hang for ~1 sec. Started digging and found that `RtmpCamera1` initialization takes 1 second. Basically I put `System.currentTimeMillis()` before and after initialization. My tests show value from 920 - 950 milliseconds on Pixel XL 2.
Is that something you know to be true? Any suggestions to go about it? Or any possible reason for it?

**Comment by pedroSG94** [comment]
I can't do anything about it. You can use a thread or DI to instantiate it.
Anyway. I will do test and I will try reduce it.
