### ISSUE TITLE
Stream from file in background

### ISSUE THREAD

**Issue by mynew-github-account** [pedroSG94/rtmp-rtsp-stream-client-java#389]
Is there any way to stream from backgound if I am streaming from file (i.e using RtmpFromFileActivity.java) 
So if I select file and start stream so I can leave that screen and do my other work while streaming  from file is also going on.

Thank You

**Comment by pedroSG94** [comment]
You can stream without preview with this instance:
```java
rtmpFromFile = new RtmpFromFile(ConnectCheckerRtmp, VideoDecoderInterface, AudioDecoderInterface);
```
