### ISSUE TITLE
RTSPClient URL without App Name

### ISSUE THREAD

**Issue by spudnick02** [pedroSG94/rtmp-rtsp-stream-client-java#390]
Change RtspClient.java's connect method to allow for a URL without appname i.e. accept both rtsp://ip:port/appname/streamname and rtsp://ip:port/streamname

e.g. rtsp://X.X.X.X:554/stream.sdp

Currently your code always expects an app name:
      String path = "/" + rtspMatcher.group(3) + "/" + rtspMatcher.group(4);
      commandsManager.setUrl(host, port, path);

**Comment by pedroSG94** [comment]
Regex expression already accept "rtsp://X.X.X.X:554/stream.sdp", but in this case stream.sdp is an app name. I don't know how to different app name from stream name in a regular expression.
You can do a pull request to add this feature if you know the way.

Anyway, I never seen a server without app name in end point. If you can tell me the server, maybe I can find any rule to accept this format.
