### ISSUE TITLE
Trying to make RTMP Connection using URL w/ encoded Params

### ISSUE THREAD

**Issue by ross-meyer** [pedroSG94/rtmp-rtsp-stream-client-java#392]
Hello

I absolutely love your library!! Thank you so much!!! Ive been using it without Auth for the most part but Ive come to an issue when I am working with an already established Wowza server that takes a normal RTMP Url with an additional base64 encoded params string appended to the end. 

`rtmp://wowzaServer.specificServer.com/applicationName/applicationInstance?params=base64EncodedParameters`

The param string is a set of variables that the wowza server uses for multiple functions. It does not take a standard username/password or I'd use 

`setAuthorization(String user, String password);`

Ive been using the haishinKit lib in Swift and it seems to just pass the whole params string to the wowza server with no issues. 

Is this something that is supported or can be made to work with your amazing library?

Thank you again!!!

**Comment by pedroSG94** [comment]
Hello,
I never tried it with my library and I'm not sure how to send that data in the url like haishinKit. You can try use same url like in haishinKit and see the result, but if it isnt working.
I will try find how to implement it reading haishinKit. If you can share class file used for this in haishinKit I will really appreciate it.

**Comment by ross-meyer** [comment]
You are amazing!! Thank you so much! I included all of the source files of the haishinKit as well as the two files I think are most of interest. 

I make the call with
`rtmpConnection.connect(urlString)`
with 
`urlString = rtmp://wowzaServer.com/appName/appInstance/appInstance?params=base64EncodedString`
as well as 
`streamnameString = mp4:appInstance`
which is called with
`rtmpStream.publish(streamnameString)`

Thank you again!!!

[filesOfInterest.zip](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/3478100/filesOfInterest.zip)

[Sources.zip](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/3478052/Sources.zip)

**Comment by ross-meyer** [comment]
Hello : )

I hope you are doing well! I have been messing with the rtmpUrlPattern matcher in RtmpConnection to try to modify it so that the regex expression takes in all the params info with the rest of the app instance. Ive gotten this expression that works well when tested against my url and stream name data. 

`^rtmps?://([^/:]+)(?::(\d+))*/([^*]*)//?(mp4[^*]*)$`

Ive downloaded a zip of the src files but cannot seem to compile them back into the library after making the changes. 

Have you had any success with the haishinkit code? Or do you know how to get the library to compile from src on a separate project? Ive followed some stackoverflow forums but can't seem to get all the dependencies of the library satisfied so it will compile.

Thank you so much!

**Comment by pedroSG94** [comment]
Sorry for late response but I'm on holydays. About haishinkit code I read interest files but I can't find a regular expression or anything about params. I need study the code but this is more difficult and take more time because I haven't apple device so I can't compile it.

About compile you can add all module manually to your project and modify code to test your regular expression (if you add rtplibrary first, the others modules will be added automatically because this module have that dependencies):
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Add-library-to-your-project

**Comment by ross-meyer** [comment]
AMAZING! No apologies necessary! By no means expecting a response :) Just wanted to update you on my progress. 

The haishinkit passes the full url string to its rtmp connection function but separate of the stream name which it uses in an rtmp publish function. The rtmp connection function takes the full url from domain to app instance and params.

I think with the modified regex it might work for your incredible library so going to try to get that to work.

Thank you so so much for your support and enjoy your holiday!!!
