### ISSUE TITLE
Preview with service streaming

### ISSUE THREAD

**Issue by maxcriser** [pedroSG94/rtmp-rtsp-stream-client-java#393]
Hi,
How I can use surface view for preview with service streaming?
In my case was created second instance in activity, but after starting streaming from service surface is stopped.

**Comment by pedroSG94** [comment]
I think that you are looking for this:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/318

This look work for other users. Maybe you have a fail in logic.

**Comment by maxcriser** [comment]
@pedroSG94  But it will be looks like disconnect and reconnect to server? (
