### ISSUE TITLE
Change bitrate and quality on runtime streaming

### ISSUE THREAD

**Issue by maxcriser** [pedroSG94/rtmp-rtsp-stream-client-java#395]
Hi,
How i can change bitrate and quality on runtime after starting streaming depends on internet connection quality.

**Comment by pedroSG94** [comment]
You can't change video quality. Normally, you should do it with the server but you can change bitrate:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Adaptative-video-bitrate.
