### ISSUE TITLE
Crash issue after switching off WiFi

### ISSUE THREAD

**Issue by maxcriser** [pedroSG94/rtmp-rtsp-stream-client-java#397]
Hi,
Can you help me with crash after turning off WiFi connection in device settings?
Now streaming implemented from your example (RtpService)

Crash log:

com.pedro.encoder.utils.gl.GlUtil.checkEglError + 134 (GlUtil.java:134)
--
  | com.pedro.encoder.input.gl.SurfaceManager.eglSetup + 131 (SurfaceManager.java:131)
  | com.pedro.encoder.input.gl.SurfaceManager.<init> + 32 (SurfaceManager.java:32)
  | com.pedro.rtplibrary.view.OffScreenGlThread.addMediaCodecSurface + 81 (OffScreenGlThread.java:81)
  | io.github.maxcriser.pryer.background.Camera2Base.resetVideoEncoder + 396 (Camera2Base.java:396)
  | io.github.maxcriser.pryer.background.Camera2Base.reTry + 458 (Camera2Base.java:458)
  | io.github.maxcriser.pryer.background.RtpService.sendReconnectBroadcastEvent + 187 (RtpService.kt:187)
  | io.github.maxcriser.pryer.background.RtpService.onConnectionFailedRtp + 170 (RtpService.kt:170)
  | io.github.maxcriser.pryer.background.ConnectCheckerRtp$DefaultImpls.onConnectionFailedRtmp + 31 (ConnectCheckerRtp.kt:31)
  | io.github.maxcriser.pryer.background.RtpService.onConnectionFailedRtmp + 29 (RtpService.kt:29)
  | com.github.faucamp.simplertmp.io.RtmpConnection.handleRxPacketLoop + 586 (RtmpConnection.java:586)
  | com.github.faucamp.simplertmp.io.RtmpConnection.access$000 + 44 (RtmpConnection.java:44)
  | com.github.faucamp.simplertmp.io.RtmpConnection$1.run + 160 (RtmpConnection.java:160)
  | java.lang.Thread.run + 764 (Thread.java:764)

**Comment by pedroSG94** [comment]
Sorry for late response but actually I'm on holydays. I will check that as soon as I can
