### ISSUE TITLE
Keyframes not sent if display is not moving?

### ISSUE THREAD

**Issue by pesutt** [pedroSG94/rtmp-rtsp-stream-client-java#398]
Hi,

First of all thank you for your great project! :)

I've been testing with a red5pro server and Samsung phones,
and I've been wondering if it's possible to send a constant video stream,
even when there is no user interaction? I am using the DisplayRtmpActivity
without audio.

The issue is that if the connection quality is not perfect, then it is possible that the last
frame sent was not received in a good quality by the consumer, so it sometimes stays in a pixelated state.

The initNotification Method is called, but I don't see any notification.
I'm running a Samsung S8 with Android 9. Tested it with Android 8, but did not see any notification either. Any hints to what might be wrong would be highly appreciated.

I noticed that it only periodically sends audio packets, and not video packets.

Thanks in advance!
Best regards,
Toni

**Comment by pesutt** [comment]
Sorry, my description was a bit wrong.
I just checked the log and observed:

- Video packets are sent periodically (quite small size, RTMP Video, size: 71)
- I would expect that keyframes would be sent, but the sent video packet size is too small

Is it possible that the Keyframes would still be sent, even without any change on the screen?

**Comment by pedroSG94** [comment]
I think this is related with your issue
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/63

**Comment by pesutt** [comment]
Agreed, unfortunately the Notification is not showing up on my devices, but I'm haven't found the issue yet.

**Comment by pesutt** [comment]
Ok, so for Android API 26+ a Notificationchannel has to be created first, that's why it didn't work.
Also I had to use NotificationCompat instead of Notification. [https://developer.android.com/training/notify-user/build-notification](Android doc)

**Comment by gopopov** [comment]
Hello, I am having a similar issue it seems where the encoder send keyframes irregularly ( seems at first it does not send keyframe for 30secs then it will send keyframe every 180 frames, independently from what I have it set. ( I've played around with 30fps and 60fps values )
public class MainActivity extends AppCompatActivity implements ConnectCheckerRtmp {

    `private boolean isStreaming = false;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Toolbar toolbar = findViewById(R.id.toolbar);
//        TextInputEditText myInputText = findViewById(R.id.my_input);
        setSupportActionBar(toolbar);
        TextView submitButton = findViewById(R.id.my_submit_button);
        final SurfaceView mySurfaceView = findViewById(R.id.my_surface_view);
        final RtmpCamera1 rtmpCamera1 = new RtmpCamera1(mySurfaceView, MainActivity.this);

        submitButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {

                if (isStreaming) {
                    rtmpCamera1.stopStream();
                    isStreaming = false;
                } else if (rtmpCamera1.prepareAudio() && rtmpCamera1.prepareVideo(640, 480,15, 4500000, false, 2
                , 0)) {
                    rtmpCamera1.startStream("rtmp://live.twitch.tv/app/$$$$");
                    isStreaming = true;
                }
            }
        });

    }
`

**Comment by pedroSG94** [comment]
According with Android documentation encoder should send a keyframe like this:
FPS / iframe = 1 key frame each encoding these frames.
If you set iframe = 0 this means all frames will be keyframes and this result in a large buffer that could be related with your frame discarded log.
This log means that you are producing frames faster than you can send it.
About inconsistency, I don't know the reason. I think this is related with mediaprojection api.

**Comment by mkrn** [comment]
I've used a different library on iOS that had a setting for minimumKeyframeInterval and it was in seconds. It worked great, and it was possible to dynamically change it. 

We need to be able to set minimal keyframe interval or else we're risking to have inconsistent HLS encoding.

Can you please point me how it is set? @gopopov @pedroSG94

**Comment by mkrn** [comment]
The value for iFrameInterval seems to be in seconds (int) 

Android documentation says:

Most video encoders will convert this value of the number of non-key-frames between key-frames, using the frame rate information; therefore, if the actual frame rate differs (e.g. input frames are dropped or the frame rate changes), the time interval between key frames will not be the configured value.

So the issue then is that due to the initial frame dropping keyframe interval may be too long.
