### ISSUE TITLE
Decode Audio crash

### ISSUE THREAD

**Issue by MohammadRezaei92** [pedroSG94/rtmp-rtsp-stream-client-java#399]
I got this error in FileStream and my app was crashed:
java.lang.IndexOutOfBoundsException: off=0, len=12288 out of bounds (size=4096)
in AudioDecoder.java line 159:
outBuffer.get(pcmBuffer, 0, outBuffer.remaining());

**Comment by pedroSG94** [comment]
Can you share file that produce this error?

**Comment by MohammadRezaei92** [comment]
> Can you share file that produce this error?

I used this video:
https://github.com/umair13adil/KotlinFFMpeg/blob/master/app/src/main/res/raw/video2.mp4
