### ISSUE TITLE
Can I switch between camera streaming and screen capturing.

### ISSUE THREAD

**Issue by mynew-github-account** [pedroSG94/rtmp-rtsp-stream-client-java#401]
My question is  there any way that I can switch between video streaming from camera and 
screen-share after steaming started.
Thank you!

**Comment by pedroSG94** [comment]
This is not available for now. You should do a custom base for it.

**Comment by lakhanrathi65** [comment]
Ok thanks

**Comment by mynew-github-account** [comment]
hey @pedroSG94 can you tell me how can I achieve this.

**Comment by pedroSG94** [comment]
You should do a mix with:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java
and:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/DisplayBase.java
You have an example for change opengl render on fly here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L313
You can adapt this method to accept display render.
