### ISSUE TITLE
Image Stretch in front camera 

### ISSUE THREAD

**Issue by 02gaurav** [pedroSG94/rtmp-rtsp-stream-client-java#402]
I am using rtmpCamera1 in this images are being stretched while using front camera. Working fine with back camera . Do i need to specify the width and height during prepareVideo or it should work by default

**Comment by pedroSG94** [comment]
This should work by default. If you call prepareVideo without parameters, it means 640x480.
If you want keep aspect ratio you need use Lightopenglview or openglview and set keppaspect ratio to true:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/res/layout/activity_open_gl.xml#L12

**Comment by 02gaurav** [comment]
By default its not working for me . I am using MI A1.
