### ISSUE TITLE
turn off micro when capture screen

### ISSUE THREAD

**Issue by exxKx** [pedroSG94/rtmp-rtsp-stream-client-java#403]
How we can disable microphone without muting other programs sounds?
 rtmpDisplay.disableAudio() - disable fully audio

**Comment by pedroSG94** [comment]
This is not possible. Other programs are captured with microphone. Audio is captured from speakers with the microphone.
https://developer.android.com/preview/features/playback-capture
This could be uselfull to replace microphone but only available with Android Q

**Comment by exxKx** [comment]
Ty for anawer, waiting for Android Q
