### ISSUE TITLE
Bitrate almost double what I set with setVideoBitrateOnFly()

### ISSUE THREAD

**Issue by dotnick** [pedroSG94/rtmp-rtsp-stream-client-java#404]
Hey Pedro

I'm trying to use your library to figure out a user's connection bandwidth to a specific RTMP server.

I start with a very low bitrate and increase it until I start dropping frames. Essentially my solution right now is to show the highest bitrate that the user is not dropping any frames at.

I'm using an RtmpFromFile as such:

```
mRTMPStream = new RtmpFromFile(this, this, this);
mRTMPStream.prepareVideo(pathToVideoFile);
mRTMPStream.prepareAudio(pathToVideoFile);
mRTMPStream.startStream(URL);
```

I'm setting the bitrate with `mRTMPStream.setVideoBitrateOnFly(bitrate)` but the bitrate I'm seeing on the other end (and this is confirmed by `onNewBitrateRtmp()`) is double what I'm setting with `setVideoBitrateOnFly()`

Am I doing something wrong here?

**Comment by pedroSG94** [comment]
Hi,
The code look fine so I'm not sure about the problem.
Anyway you can use adaptative bitrate for it. You should select the best quality for your file in preparevideo and adaptative bitrate will reduce it automatically acording with your bandwidth.
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Adaptative-video-bitrate.
