### ISSUE TITLE
Crash : Make sure the SurfaceView or associated SurfaceHolder has a valid Surface 

### ISSUE THREAD

**Issue by floriangbh** [pedroSG94/rtmp-rtsp-stream-client-java#406]
Hello, 

Some of our users encountered a crash which I'm unable to reproduce : 
```
Fatal Exception: java.lang.IllegalArgumentException: Make sure the SurfaceView or associated SurfaceHolder has a valid Surface
       at android.opengl.EGL14._eglCreateWindowSurface(EGL14.java)
       at android.opengl.EGL14.eglCreateWindowSurface + 263(EGL14.java:263)
       at com.pedro.encoder.input.gl.SurfaceManager.eglSetup + 129(SurfaceManager.java:129)
       at com.pedro.encoder.input.gl.SurfaceManager.(SurfaceManager.java:10)
       at com.pedro.rtplibrary.view.OpenGlView.run + 106(OpenGlView.java:106)
       at java.lang.Thread.run + 764(Thread.java:764)
```

Here is the related code for surfaceView holder and filter  : 

```kotlin
override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
    super.onViewCreated(view, savedInstanceState)
    surfaceView.apply {
        holder.addCallback(this@StudioFragment)
    }
}
```
```kotlin
val imageObjectFilterRender = ImageObjectFilterRender()
rtmpCamera2.glInterface.setFilter(1, imageObjectFilterRender)
imageObjectFilterRender.apply {
    setImage(bitmapToDisplay.copy(bitmapToDisplay.config, true))
    setPosition(TranslateTo.CENTER)
}
```

Have you any idea how to fix this or reproduce it ? 
Is there any way to check if the `glInterface` is valid before set a filter on it ? 

Thanks

**Comment by pedroSG94** [comment]
I think this is not related with filter because filter is setted after crash line:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/view/OpenGlView.java#L134

I think that you are starting openglview before surfaceview is created.
Can you share surfacechanged callback of openglview? (You should start stream, record or preview after this callback is called).

**Comment by floriangbh** [comment]
I just found the problem, it was related to my fragment lifecycle .. Sorry for the inconvenience and thanks for your reply !

**Comment by mynew-github-account** [comment]
Hey, how to fix this I have the same issue?

**Comment by floriangbh** [comment]
It was related to my fragment lifecycle (mistake in my code, something wasn't initialized).
