### ISSUE TITLE
Font for text

### ISSUE THREAD

**Issue by mylaimani** [pedroSG94/rtmp-rtsp-stream-client-java#409]
I am using this function for video streaming

       TextObjectFilterRender textObjectFilterRender = new TextObjectFilterRender();
        rtmpCamera1.getGlInterface().setFilter(7,textObjectFilterRender);
        textObjectFilterRender.setText(scores, 15, Color.BLUE);
        textObjectFilterRender.setDefaultScale(rtmpCamera1.getStreamWidth(),
                rtmpCamera1.getStreamHeight());
        textObjectFilterRender.setPosition(49,87);
        spriteGestureController.setBaseObjectFilterRender(textObjectFilterRender); 

Is there any way to use custom font like Trebuchet MS.ttf

**Comment by pedroSG94** [comment]
Hello,
I did a commit for it:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/e2942191cab1216c26f58d4d484639480dda5b84
If you want know how to create a Typeface instance see this post:
https://stackoverflow.com/questions/6042977/android-set-custom-font-to-a-paint

**Comment by mylaimani** [comment]
Thank you very much, I will use this update
