### ISSUE TITLE
uses-feature camera2 cause issues with Play Store

### ISSUE THREAD

**Issue by mkrn** [pedroSG94/rtmp-rtsp-stream-client-java#411]
I've followed instructions on README and added the following to the AndroidManifest.xml
```
<uses-feature android:name="android.hardware.camera2.full" />
<uses-feature android:name="android.hardware.camera2.autofocus" />
```

However, that resulted in 0 compatible devices in Play Store and the inability to install it on any device through the Play Store.

This could be removed from README sparing some trouble to others.

@pedroSG94 was there a reason for these features? It looks like they're non-existing.

I'll be happy to submit a PR, once I get the app approved. 

Thanks for the amazing library.

**Comment by pratheepchowdhary** [comment]
<uses-feature android:name="android.hardware.camera" android:required="false" />
    <uses-feature android:name="android.hardware.camera.autofocus" android:required="false"/>

Add android:required="false"

**Comment by pedroSG94** [comment]
That lines was for this:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/58
You can delete it. The library should work without it.

**Comment by mkrn** [comment]
Thanks. I've currently re-uploaded it with only <uses-feature android:name="android.hardware.camera" /> and getting a crash on start intent with streaming component.  
Will investigate further before making conclusions.
