### ISSUE TITLE
Zoom for Camera view

### ISSUE THREAD

**Issue by mylaimani** [pedroSG94/rtmp-rtsp-stream-client-java#413]
I tried to zoom inside the application but it is not working, this is my code, am I doing anything wrong ?

<com.pedro.rtplibrary.view.OpenGlView
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:id="@+id/surfaceView"
            app:keepAspectRatio="true"
            app:AAEnabled="false"
            app:numFilters="15"
            app:isFlipHorizontal="false"
            app:isFlipVertical="false"
            />

@Override
    public boolean onTouch(View view, MotionEvent motionEvent) {

        int action = motionEvent.getAction();
        if (motionEvent.getPointerCount() > 1) {
            if (action == MotionEvent.ACTION_MOVE) {
                rtmpCamera1.setZoom(motionEvent);
            }
        } else {
            if (action == MotionEvent.ACTION_UP) {
                Log.e("Stop","Zoom");
            }
        }
        if (spriteGestureController.spriteTouched(view, motionEvent)) {
            spriteGestureController.moveSprite(view, motionEvent);
            spriteGestureController.scaleSprite(motionEvent);
            return true;
        }
        return false;
    }

**Comment by pedroSG94** [comment]
You should return true.
Also remember add listener to your view:
```java
    surfaceView.setOnTouchListener(this);
```
