### ISSUE TITLE
How to improve stream latency

### ISSUE THREAD

**Issue by abadoliverco** [pedroSG94/rtmp-rtsp-stream-client-java#414]
I tried to publish a live stream using your library to Facebook live but there's a 30 seconds delay, is there a way to improve this delay? Thank you!

**Comment by pedroSG94** [comment]
I think this is facebook latency.
You can try with other server.
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Media-servers-tested

**Comment by abadoliverco** [comment]
I see, alright Thanks!
