### ISSUE TITLE
Image and Text filter 

### ISSUE THREAD

**Issue by lakhanrathi65** [pedroSG94/rtmp-rtsp-stream-client-java#416]
How to give cross/cancel button on right top corner of text or image to close that filter.

**Comment by pedroSG94** [comment]
You can create 2 image filter (main image and close image).
For this you need one spritegesturedetector per filter and when you touch main image move both and when you touch on close image delete both.
Remember that you can get position and scale of a image filter to create a relative position for other image filter

**Comment by lakhanrathi65** [comment]
Thanks I will try this
