### ISSUE TITLE
Blur filter is not as required 

### ISSUE THREAD

**Issue by lakhanrathi65** [pedroSG94/rtmp-rtsp-stream-client-java#417]
Why blur filter is not as other app show 
library blur effect (https://user-images.githubusercontent.com/41420619/64857851-6197c500-d643-11e9-9ed0-8c164bc7496d.png)
 how other show (https://user-images.githubusercontent.com/41420619/64857884-74aa9500-d643-11e9-9c05-b52cba35991b.jpg)

I try to reduce or increase blur factor its not  working
private float blur = 40f; this on in BlurFilterRender.java

please let know how can I achevie blur filter in good way
I also try to find blur filter file online but I could not  find any like in library thisone blur_fragment.glsl

**Comment by pedroSG94** [comment]
Hello,
I changed blur filter in this commit:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/f9fd5e51fc64cc86a7e9389e4d156ce4d2617544
Now, this should work as expected.
