### ISSUE TITLE
Pause Streaming and resolution

### ISSUE THREAD

**Issue by mylaimani** [pedroSG94/rtmp-rtsp-stream-client-java#418]
Is there any way to Pause the stream and start again... It looks for recording this feature is available but streaming we are having only Start and Pause.

There is one more issue I noticed, I am using a graphic image to display the scores background, it is not getting expanded as per the camera resolution.

![St9pqD7](https://user-images.githubusercontent.com/4998347/64916163-e85cb700-d795-11e9-87d8-f22b3cc2dae2.jpg)

I use the following code for changing the resolution but it is not working, it is showing same old resolution

private boolean prepareEncoders(int getSelectedItemPosition, int Fps, int VideoBitrate) {
        Camera.Size resolution =
                rtmpCamera1.getResolutionsBack().get(getSelectedItemPosition);
        int width = resolution.width;
        int height = resolution.height;

        return rtmpCamera1.prepareVideo(width, height, Fps,
                VideoBitrate * 1024,
                false, CameraHelper.getCameraOrientation(this))
                && rtmpCamera1.prepareAudio(128 * 1024,44100,
                true, true,
                true);
    }

**Comment by pedroSG94** [comment]
Hello,
For now, pause command is not available for stream.

About image resolution. I suppose that you are using an image filter, in this case, you should use:
- setDefaultScale -> Calculate resolution to create a real image size according with actual stream resolution. example: If you have a image file with 200x200px and you select stream with resolution 200x200px this means that image will be full screen.
- setScale -> set image size in percent.
