### ISSUE TITLE
Stream in background 

### ISSUE THREAD

**Issue by lakhanrathi65** [pedroSG94/rtmp-rtsp-stream-client-java#420]
Can I stream in background when I go out of app to share my live link on whatapp,chat etc and come back to streaming after sharing link 

Or can i use 
https://developer.android.com/guide/topics/ui/picture-in-picture 

for going out of app

**Comment by pedroSG94** [comment]
Depend of surface lifecycle. I recommend you use picture on picture or a widget

**Comment by lakhanrathi65** [comment]
Sorry But I didn't get how to do it using widget?? 
can you explain more
Thanks

**Comment by pedroSG94** [comment]
You can see a widget example here:
https://stackoverflow.com/questions/6264809/how-to-build-a-simple-android-widget
