### ISSUE TITLE
RTP stream without using RTMP or RTSP

### ISSUE THREAD

**Issue by TheDoctorr** [pedroSG94/rtmp-rtsp-stream-client-java#422]
I am trying to make RTP stream without using RTSP or RTMP is it possible? Can I make this stream with your projects? I am trying to use "backgroundexample" example but it's using RTMP or RTSP.

**Comment by pedroSG94** [comment]
This library is not developed to work only with RTP.
https://stackoverflow.com/questions/4303439/what-is-the-difference-between-rtp-or-rtsp-in-a-streaming-server
If you want only RTP protocol maybe you can replace rtspclient class with rtspsender witch is a RTP and RTCP implementation.

**Comment by TheDoctorr** [comment]
Thank you so much for your help and for this great library. :)
