### ISSUE TITLE
Camera resolution not changing

### ISSUE THREAD

**Issue by mylaimani** [pedroSG94/rtmp-rtsp-stream-client-java#423]
I am trying to stream video for this resolution 1280 x 720 but it always goes to default 640 x 480

I am using the following function and calling it before the streaming is started and resolution.width and resolution.height comes correctly as 1280 and 720 but when I see the streaming output it shows only 640 x 480 resolution.

        private boolean prepareEncoders(int getSelectedItemPosition, int Fps, int VideoBitrate) {
        Camera.Size resolution =
                rtmpCamera1.getResolutionsBack().get(getSelectedItemPosition);
        int width = resolution.width;
        int height = resolution.height;

        return rtmpCamera1.prepareVideo(width, height, Fps,
                VideoBitrate * 1024,
                false, CameraHelper.getCameraOrientation(this))
                && rtmpCamera1.prepareAudio(128 * 1024,44100,
                true, true,
                true);
         }

I am keeping the AspectRation = true

<com.pedro.rtplibrary.view.OpenGlView
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:id="@+id/surfaceView"
            app:keepAspectRatio="true"
            app:AAEnabled="false"
            app:numFilters="15"
            app:isFlipHorizontal="false"
            app:isFlipVertical="false"
            />

Am I doing anything wrong here.

**Comment by pedroSG94** [comment]
Make sure that this log show your resolution correctly:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java#L170
Try with a surfaceview instead of openglview to discard opengl problems.
If you can share me an activity code to reproduce your case.

**Comment by mylaimani** [comment]
I had used WebView for getting values from Website and display it inside the application. My Final output looks like this 
![device-2019-09-17-200956](https://user-images.githubusercontent.com/4998347/65125076-befc8f00-da12-11e9-8a4f-d028f3bdf123.png)

import android.app.ProgressDialog;
import android.content.Context;
import android.content.res.AssetManager;
import android.graphics.BitmapFactory;
import android.graphics.Color;
import android.graphics.Point;
import android.graphics.Typeface;
import android.hardware.Camera;
import android.os.Build;
import android.os.Bundle;
import android.os.Environment;
import android.util.Log;
import android.view.Display;
import android.view.MotionEvent;
import android.view.SurfaceHolder;
import android.view.View;
import android.view.Window;
import android.view.WindowManager;
import android.webkit.ConsoleMessage;
import android.webkit.WebChromeClient;
import android.webkit.WebSettings;
import android.widget.Button;
import android.widget.TextView;
import android.widget.Toast;
import androidx.annotation.RequiresApi;
import androidx.appcompat.app.AppCompatActivity;
import com.pedro.encoder.input.gl.SpriteGestureController;
import com.pedro.encoder.input.gl.render.filters.object.ImageObjectFilterRender;
import com.pedro.encoder.input.gl.render.filters.object.TextObjectFilterRender;
import com.pedro.encoder.input.video.CameraHelper;
import com.pedro.encoder.input.video.CameraOpenException;
import com.pedro.encoder.utils.gl.TranslateTo;
import com.pedro.rtplibrary.rtmp.RtmpCamera1;
import com.pedro.rtplibrary.view.OpenGlView;
import java.io.File;
import net.ossrs.rtmp.ConnectCheckerRtmp;
import android.webkit.WebView;

import com.facebook.AccessToken;
import com.facebook.GraphRequest;
import com.facebook.GraphResponse;
import com.lastmanstands.tv.ui.MultiStateButton;

import org.json.JSONObject;


@RequiresApi(api = Build.VERSION_CODES.JELLY_BEAN_MR2)


public class StreamingActivity extends AppCompatActivity
        implements ConnectCheckerRtmp, View.OnClickListener, SurfaceHolder.Callback,
        View.OnTouchListener {
    private Integer[] orientations = new Integer[] { 0, 90, 180, 270 };
    private Context contextForDialog = null;
    private RtmpCamera1 rtmpCamera1;
    private MultiStateButton mBroadCast;
    private Button bRecord;
    private Button getvalue;
    String strTheme;
    String value="";
    String videoId="";
    private String currentDateAndTime = "";
    private File folder = new File(Environment.getExternalStorageDirectory().getAbsolutePath()
            + "/rtmp-rtsp-stream-client-java");
    private OpenGlView openGlView;
    private SpriteGestureController spriteGestureController = new SpriteGestureController();
    WebView myWebView;
    TextView myResultView;
    String strHomeTeam="";
    String strAwayTeam="";
    private ProgressDialog dialog;
    String FixtureId="";
    int width = 0;
    int height = 0;
    String strBattingTeamName;
    String strBowlingTeamName;
    String strBattingTeamRuns;
    String strBattingTeamWickets;
    String strBattingTeamOvers;
    String[] strBatting;
    String[] strCurrentBatsman;
    String[] strNonStriker;
    String[] strCurrentBowler;
    String[] strInnings;
    AssetManager assetManager;
    int iSelectedItemPosition;
    int iFPS;
    int iVideoBitrate;
    @Override
    protected void onResume() {
        super.onResume();
        setLMSLogoToStream();
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        requestWindowFeature(Window.FEATURE_NO_TITLE);
        getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);
        getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
        setContentView(R.layout.activity_streaming);
        Display display = getWindowManager(). getDefaultDisplay();
        Point size = new Point();
        display. getSize(size);
        width = size. x;
        height = size. y;

        openGlView = findViewById(R.id.surfaceView);
        contextForDialog = this;
        dialog = new ProgressDialog(contextForDialog);
        Bundle extras = getIntent().getExtras();
        assetManager = getAssets();
        if (extras != null) {
            value = extras.getString("stream_url");
            videoId = extras.getString("id");
            FixtureId = extras.getString("FixtureId");
            strHomeTeam = extras.getString("HomeTeam");
            strAwayTeam = extras.getString("AwayTeam");
            iSelectedItemPosition = extras.getInt("getSelectedItemPosition");
            iFPS = extras.getInt("Fps");
            iVideoBitrate = extras.getInt("etVideoBitrate");
            strTheme = extras.getString("ThemeName");
        }
        getvalue = (Button) findViewById(R.id.getvalue);
        myResultView = (TextView)this.findViewById(R.id.myResult);
        myWebView = (WebView)this.findViewById(R.id.myWebView);
        WebSettings webSettings = myWebView.getSettings();
        webSettings.setJavaScriptEnabled(true);
        myWebView.setWebChromeClient(new WebChromeClient());
        myWebView.getSettings().setJavaScriptCanOpenWindowsAutomatically(true);
        myWebView.getSettings().setBlockNetworkImage(false);
        myWebView.getSettings().setAllowFileAccess(true);
        myWebView.getSettings().setAllowFileAccessFromFileURLs(true);
        myWebView.getSettings().setAllowUniversalAccessFromFileURLs(true);
        String url= getResources().getString(R.string.fixture);
        url = url.replace("FixtureId",FixtureId);
        myWebView.loadUrl(url);

        myWebView.setWebChromeClient(new WebChromeClient() {
            public void onProgressChanged(WebView view, int progress){

            }
            public boolean onConsoleMessage(ConsoleMessage cm) {
                if(cm.message().contains("Score::::")){
                    strBatting = cm.message().split("::::");
                    strBattingTeamName = strBatting[1];
                    strBowlingTeamName = strBatting[2];
                    strBattingTeamRuns = strBatting[3];
                    strBattingTeamWickets = strBatting[4];
                    strBattingTeamOvers = strBatting[5];
                    setBottomImageToStream();
                    setLMSLogoToStream();
                    setBattingTeamToStream(strBatting[1]);
                    setBowlingTeamToStream(strBatting[2]);
                    setBattingTeamScoreToStream(strBatting[3] + " - " + strBatting[4]);
                    setBattingTeamOversToStream(strBatting[5]);
                }
                if(cm.message().contains("currentbatsman::::")){
                    strCurrentBatsman = cm.message().split("::::");
                    setCurrentBatsmanNameToStream(strCurrentBatsman[1]);
                    setStrikerRunsScoreToStream(strCurrentBatsman[2] + "("+strCurrentBatsman[3]+")");
                }

                if(cm.message().contains("nonstriker::::")){
                    strNonStriker = cm.message().split("::::");
                    setNonStrikerBatsmanNameToStream(strNonStriker[1]);
                    setNonStrikerRunsScoreToStream(strNonStriker[2] + "("+strNonStriker[3]+")");
                }

                if(cm.message().contains("currentbowler::::")){
                    strCurrentBowler = cm.message().split("::::");
                    setCurrentBowlerScoreToStream(strCurrentBowler[1] + " "+ strCurrentBowler[3] +"-" + strCurrentBowler[4] + "("+strCurrentBowler[2]+")");
                }

                if(cm.message().contains("innings::::")){
                    strInnings = cm.message().split("::::");
                    if(strInnings[1].equals("1")) {
                        setInningsToStream("1st Innings");
                    } else {
                        setInningsToStream("2nd Innings");
                    }
                }

                return true;
            }
        });



        mBroadCast = findViewById(R.id.ic_broadcast);
        mBroadCast.setOnClickListener(this);
        mBroadCast.setState(false);
        mBroadCast.setEnabled(true);
        bRecord = findViewById(R.id.b_record);
        bRecord.setOnClickListener(this);
        MultiStateButton switchCamera = findViewById(R.id.ic_switch_camera);
        switchCamera.setOnClickListener(this);
        getvalue.setOnClickListener(this);

        rtmpCamera1 = new RtmpCamera1(openGlView, this);
        rtmpCamera1.setVideoBitrateOnFly(iVideoBitrate);
        openGlView.getHolder().addCallback(this);
        openGlView.setOnTouchListener(this);

    }

    private void setBowlingTeamToStream(String scores) {
        String upToNCharacters = scores.substring(0, Math.min(scores.length(), 15));
        upToNCharacters = upToNCharacters.toUpperCase();
        Typeface plain = Typeface.createFromAsset(assetManager, "trebuchet.ttf");
        Typeface bold = Typeface.create(plain, Typeface.BOLD);
        TextObjectFilterRender textObjectFilterRender = new TextObjectFilterRender();
        rtmpCamera1.getGlInterface().setFilter(3,textObjectFilterRender);
        textObjectFilterRender.setText(upToNCharacters, 15, Color.BLACK, bold);
        textObjectFilterRender.setDefaultScale(rtmpCamera1.getStreamWidth(),
                rtmpCamera1.getStreamHeight());
        textObjectFilterRender.setPosition(9,84);
        spriteGestureController.setBaseObjectFilterRender(textObjectFilterRender); //Optional
    }

    private void setBattingTeamToStream(String scores) {
        String upToNCharacters = scores.substring(0, Math.min(scores.length(), 15));
        upToNCharacters = upToNCharacters.toUpperCase();
        Typeface plain = Typeface.createFromAsset(assetManager, "trebuchet.ttf");
        Typeface bold = Typeface.create(plain, Typeface.BOLD);
        TextObjectFilterRender textObjectFilterRender = new TextObjectFilterRender();
        rtmpCamera1.getGlInterface().setFilter(4,textObjectFilterRender);
        textObjectFilterRender.setText(upToNCharacters, 17, Color.WHITE, bold);
        textObjectFilterRender.setDefaultScale(rtmpCamera1.getStreamWidth(),
                rtmpCamera1.getStreamHeight());
        textObjectFilterRender.setPosition(9,89);
        spriteGestureController.setBaseObjectFilterRender(textObjectFilterRender); //Optional
    }

    private void setBattingTeamScoreToStream(String scores) {
        Typeface plain = Typeface.createFromAsset(assetManager, "trebuchet.ttf");
        Typeface bold = Typeface.create(plain, Typeface.BOLD);
        scores = scores.toUpperCase();
        TextObjectFilterRender textObjectFilterRender = new TextObjectFilterRender();
        rtmpCamera1.getGlInterface().setFilter(5,textObjectFilterRender);
        Log.e("Score",scores);
        textObjectFilterRender.setText(scores, 15, Color.BLACK, bold);
        textObjectFilterRender.setDefaultScale(rtmpCamera1.getStreamWidth(),
                rtmpCamera1.getStreamHeight());
        textObjectFilterRender.setPosition(30,89);
        spriteGestureController.setBaseObjectFilterRender(textObjectFilterRender); //Optional
    }

    private void setBattingTeamOversToStream(String scores) {
        Typeface plain = Typeface.createFromAsset(assetManager, "trebuchet.ttf");
        Typeface bold = Typeface.create(plain, Typeface.BOLD);
        scores = scores.toUpperCase();
        TextObjectFilterRender textObjectFilterRender = new TextObjectFilterRender();
        rtmpCamera1.getGlInterface().setFilter(6,textObjectFilterRender);
        Log.e("Score",scores);
        textObjectFilterRender.setText(scores, 15, Color.WHITE, bold);
        textObjectFilterRender.setDefaultScale(rtmpCamera1.getStreamWidth(),
                rtmpCamera1.getStreamHeight());
        textObjectFilterRender.setPosition(42,89);
        spriteGestureController.setBaseObjectFilterRender(textObjectFilterRender); //Optional
    }

    private void setCurrentBatsmanNameToStream(String scores) {
        Typeface plain = Typeface.createFromAsset(assetManager, "trebuchet.ttf");
        Typeface bold = Typeface.create(plain, Typeface.BOLD);
        scores = "*"+ scores.toUpperCase();
        TextObjectFilterRender textObjectFilterRender = new TextObjectFilterRender();
        rtmpCamera1.getGlInterface().setFilter(7,textObjectFilterRender);
        Log.e("Score",scores);
        textObjectFilterRender.setText(scores, 15, Color.BLACK, bold);
        textObjectFilterRender.setDefaultScale(rtmpCamera1.getStreamWidth(),
                rtmpCamera1.getStreamHeight());
        textObjectFilterRender.setPosition(52,88);
        spriteGestureController.setBaseObjectFilterRender(textObjectFilterRender); //Optional
    }

    private void setNonStrikerBatsmanNameToStream(String scores) {
        Typeface plain = Typeface.createFromAsset(assetManager, "trebuchet.ttf");
        Typeface bold = Typeface.create(plain, Typeface.BOLD);
        scores = scores.toUpperCase();
        TextObjectFilterRender textObjectFilterRender = new TextObjectFilterRender();
        rtmpCamera1.getGlInterface().setFilter(8,textObjectFilterRender);
        textObjectFilterRender.setText(scores, 15, Color.BLACK, bold);
        textObjectFilterRender.setDefaultScale(rtmpCamera1.getStreamWidth(),
                rtmpCamera1.getStreamHeight());
        textObjectFilterRender.setPosition(52,93);
        spriteGestureController.setBaseObjectFilterRender(textObjectFilterRender); //Optional
    }



    private void setCurrentBowlerScoreToStream(String scores) {
        Typeface plain = Typeface.createFromAsset(assetManager, "trebuchet.ttf");
        Typeface bold = Typeface.create(plain, Typeface.BOLD);
        scores = scores.toUpperCase();
        TextObjectFilterRender textObjectFilterRender = new TextObjectFilterRender();
        rtmpCamera1.getGlInterface().setFilter(9,textObjectFilterRender);
        Log.e("Score",scores);
        textObjectFilterRender.setText(scores, 15, Color.BLACK, bold);
        textObjectFilterRender.setDefaultScale(rtmpCamera1.getStreamWidth(),
                rtmpCamera1.getStreamHeight());
        textObjectFilterRender.setPosition(72,88);
        spriteGestureController.setBaseObjectFilterRender(textObjectFilterRender); //Optional
    }

    private void setNonStrikerRunsScoreToStream(String scores) {
        Typeface plain = Typeface.createFromAsset(assetManager, "trebuchet.ttf");
        Typeface bold = Typeface.create(plain, Typeface.BOLD);
        scores = scores.toUpperCase();
        TextObjectFilterRender textObjectFilterRender = new TextObjectFilterRender();
        rtmpCamera1.getGlInterface().setFilter(10,textObjectFilterRender);
        textObjectFilterRender.setText(scores, 15, Color.BLACK, bold);
        textObjectFilterRender.setDefaultScale(rtmpCamera1.getStreamWidth(),
                rtmpCamera1.getStreamHeight());
        textObjectFilterRender.setPosition(64,93);
        spriteGestureController.setBaseObjectFilterRender(textObjectFilterRender); //Optional
    }

    private void setStrikerRunsScoreToStream(String scores) {
        Typeface plain = Typeface.createFromAsset(assetManager, "trebuchet.ttf");
        Typeface bold = Typeface.create(plain, Typeface.BOLD);
        scores = scores.toUpperCase();
        TextObjectFilterRender textObjectFilterRender = new TextObjectFilterRender();
        rtmpCamera1.getGlInterface().setFilter(11,textObjectFilterRender);
        textObjectFilterRender.setText(scores, 15, Color.BLACK, bold);
        textObjectFilterRender.setDefaultScale(rtmpCamera1.getStreamWidth(),
                rtmpCamera1.getStreamHeight());
        textObjectFilterRender.setPosition(64,88);
        spriteGestureController.setBaseObjectFilterRender(textObjectFilterRender); //Optional
    }

    private void setInningsToStream(String scores) {
        Typeface plain = Typeface.createFromAsset(assetManager, "trebuchet.ttf");
        Typeface bold = Typeface.create(plain, Typeface.BOLD);
        scores = scores.toUpperCase();
        TextObjectFilterRender textObjectFilterRender = new TextObjectFilterRender();
        rtmpCamera1.getGlInterface().setFilter(12,textObjectFilterRender);
        textObjectFilterRender.setText(scores, 15, Color.WHITE, bold);
        textObjectFilterRender.setDefaultScale(rtmpCamera1.getStreamWidth(),
                rtmpCamera1.getStreamHeight());
        textObjectFilterRender.setPosition(74,93);
        spriteGestureController.setBaseObjectFilterRender(textObjectFilterRender); //Optional
    }

    private void setLMSLogoToStream() {
        ImageObjectFilterRender imageObjectFilterRender = new ImageObjectFilterRender();
        rtmpCamera1.getGlInterface().setFilter(2,imageObjectFilterRender);
        imageObjectFilterRender.setImage(
                BitmapFactory.decodeResource(getResources(), R.drawable.rlogo));
        imageObjectFilterRender.setDefaultScale(rtmpCamera1.getStreamWidth(),
                rtmpCamera1.getStreamHeight());
        imageObjectFilterRender.setPosition(TranslateTo.TOP_RIGHT);
        spriteGestureController.setBaseObjectFilterRender(imageObjectFilterRender); //Optional
        spriteGestureController.setPreventMoveOutside(true); //Optional
    }

    private void setBottomImageToStream() {
        ImageObjectFilterRender imageObjectFilterRender = new ImageObjectFilterRender();
        rtmpCamera1.getGlInterface().setFilter(1,imageObjectFilterRender);
        if(strTheme.equals("Green")) {
            imageObjectFilterRender.setImage(
                    BitmapFactory.decodeResource(getResources(), R.drawable.background_green640));
        } else if(strTheme.equals("Purple")){
            imageObjectFilterRender.setImage(
                    BitmapFactory.decodeResource(getResources(), R.drawable.background_purple640));
        } else if(strTheme.equals("Navy")){
            imageObjectFilterRender.setImage(
                    BitmapFactory.decodeResource(getResources(), R.drawable.background_navy640));
        } else {
            imageObjectFilterRender.setImage(
                    BitmapFactory.decodeResource(getResources(), R.drawable.background_green640));
        }
        imageObjectFilterRender.setDefaultScale(rtmpCamera1.getStreamWidth(),
                rtmpCamera1.getStreamHeight());
        imageObjectFilterRender.setPosition(TranslateTo.BOTTOM);
        spriteGestureController.setBaseObjectFilterRender(imageObjectFilterRender);
        spriteGestureController.setPreventMoveOutside(false); //Optional
    }

    @Override
    public void onConnectionSuccessRtmp() {
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                Toast.makeText(StreamingActivity.this, "Connection success", Toast.LENGTH_SHORT).show();
            }
        });
    }


    @Override
    public void onConnectionFailedRtmp(final String reason) {
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                Toast.makeText(StreamingActivity.this, "Connection failed. " + reason, Toast.LENGTH_SHORT)
                        .show();
                rtmpCamera1.stopStream();
                ///But
            }
        });
    }

    @Override
    public void onNewBitrateRtmp(long bitrate) {

    }

    @Override
    public void onDisconnectRtmp() {
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                Toast.makeText(StreamingActivity.this, "Disconnected", Toast.LENGTH_SHORT).show();
            }
        });
    }

    @Override
    public void onAuthErrorRtmp() {
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                Toast.makeText(StreamingActivity.this, "Auth error", Toast.LENGTH_SHORT).show();
            }
        });
    }

    @Override
    public void onAuthSuccessRtmp() {
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                Toast.makeText(StreamingActivity.this, "Auth success", Toast.LENGTH_SHORT).show();
            }
        });
    }

    @Override
    public void onClick(View view) {
        switch (view.getId()) {
            case R.id.getvalue:
                break;
            case R.id.ic_broadcast:
                //if(prepareEncoders(iSelectedItemPosition,iFPS,iVideoBitrate)){
                if (!rtmpCamera1.isStreaming()) {
                    if (rtmpCamera1.isRecording()
                            || rtmpCamera1.prepareAudio() && rtmpCamera1.prepareVideo()) {
                        mBroadCast.setState(true);
                        mBroadCast.setEnabled(true);
                        rtmpCamera1.startStream(value);
                        setLMSLogoToStream();
                    } else {
                        Toast.makeText(this, "Error preparing stream, This device cant do it",
                                Toast.LENGTH_SHORT).show();
                    }
                } else {
                    try {

                        GraphRequest request = GraphRequest.newPostRequest(
                                AccessToken.getCurrentAccessToken(),
                                "/"+videoId,
                                new JSONObject("{\"end_live_video\":\"true\"}"),
                                new GraphRequest.Callback() {
                                    @Override
                                    public void onCompleted(GraphResponse response) {
                                        try {
                                            Log.e("response", response.toString());
                                        } catch (Exception e) {
                                            Log.e("Err", e.toString());
                                        }
                                    }
                                });
                        request.executeAsync();
                        mBroadCast.setState(false);
                        mBroadCast.setEnabled(true);
                        rtmpCamera1.stopStream();

                    } catch (Exception e){
                        Log.e("Exception",e.toString());
                    }
                }
               // }
                break;
            case R.id.ic_switch_camera:
                try {
                    rtmpCamera1.switchCamera();
                } catch (CameraOpenException e) {
                    Toast.makeText(this, e.getMessage(), Toast.LENGTH_SHORT).show();
                }
                break;
            default:
                break;
        }
    }

    @Override
    public void surfaceCreated(SurfaceHolder surfaceHolder) {

    }

    @Override
    public void surfaceChanged(SurfaceHolder surfaceHolder, int i, int i1, int i2) {
        rtmpCamera1.startPreview();
    }

    @Override
    public void surfaceDestroyed(SurfaceHolder surfaceHolder) {
        if (rtmpCamera1.isStreaming()) {
            rtmpCamera1.stopStream();
        }
        rtmpCamera1.stopPreview();
    }

    @Override
    public boolean onTouch(View view, MotionEvent motionEvent) {

        int action = motionEvent.getAction();
        if (motionEvent.getPointerCount() > 1) {
            if (action == MotionEvent.ACTION_MOVE) {
                rtmpCamera1.setZoom(motionEvent);
            }
        } else {
            if (action == MotionEvent.ACTION_UP) {
                Log.e("Stop","Zoom");
            }
        }
        if (spriteGestureController.spriteTouched(view, motionEvent)) {
            spriteGestureController.moveSprite(view, motionEvent);
            spriteGestureController.scaleSprite(motionEvent);
            return true;
        }
        return true;
    }

    @Override
    public void onBackPressed() {
        if (myWebView.canGoBack()) { //if going back is possible in webview then go back within webview
            myWebView.goBack();
        } else {
            super.onBackPressed(); //otherwise go back within the app
        }
    }


    private boolean prepareEncoders(int getSelectedItemPosition, int Fps, int VideoBitrate) {
        Camera.Size resolution =
                rtmpCamera1.getResolutionsBack().get(getSelectedItemPosition);
        int width = resolution.width;
        int height = resolution.height;

        return rtmpCamera1.prepareVideo(width, height, Fps,
                VideoBitrate * 1024,
                false, CameraHelper.getCameraOrientation(this))
                && rtmpCamera1.prepareAudio(128 * 1024,44100,
                true, true,
                true);
    }
}


<?xml version="1.0" encoding="utf-8"?>
<androidx.drawerlayout.widget.DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:sampleui="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:openDrawer="start"
    android:id="@+id/activity_custom"
    >

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        >

    

    <FrameLayout
        android:id="@+id/cameraView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="#0d0d0d">

        <com.pedro.rtplibrary.view.OpenGlView
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:id="@+id/surfaceView"
            app:keepAspectRatio="true"
            app:AAEnabled="false"
            app:numFilters="15"
            app:isFlipHorizontal="false"
            app:isFlipVertical="false"
            />
        <WebView
            android:id="@+id/myWebView"
            android:visibility="gone"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content">
        </WebView>

    </FrameLayout>

    <RelativeLayout
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="end|center_vertical"
        android:layout_alignParentEnd="false"
        android:layout_alignParentRight="false"
        android:padding="2dp"
        android:layout_alignParentStart="true"
        android:layout_alignParentLeft="true"
        >

        <LinearLayout
            android:orientation="horizontal"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentTop="true"
            android:background="@drawable/rounded_corner"
            android:layout_alignParentLeft="true"
            android:layout_alignParentStart="false">

            <com.lastmanstands.tv.ui.MultiStateButton
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:id="@+id/ic_switch_camera"
                android:src="@drawable/ic_switch_camera"
                android:cropToPadding="false"
                android:background="#000000ff"
                android:padding="10dp"
                android:contentDescription="Switch Camera" />
            <com.lastmanstands.tv.ui.MultiStateButton
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:id="@+id/ic_broadcast"
                android:src="@drawable/ic_stop"
                sampleui:offSrc="@drawable/ic_start"
                android:layout_alignParentTop="true"
                android:cropToPadding="false"
                android:background="#000000ff"
                android:layout_centerHorizontal="true"
                android:layout_margin="10dp" />

            <com.lastmanstands.tv.ui.MultiStateButton
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:id="@+id/ic_settings"
                android:src="@drawable/ic_settings"
                android:background="#000000ff"
                android:padding="10dp"
                android:layout_alignParentEnd="true"
                android:layout_alignParentRight="true"
                android:layout_alignParentTop="true" />

            <com.lastmanstands.tv.ui.TimerView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="00:00:00"
                android:id="@+id/txtTimer"
                android:layout_centerHorizontal="true"
                android:background="@drawable/rounded_corner"
                android:textColor="#ffffff"
                android:textStyle="bold"
                android:typeface="monospace"
                android:textAppearance="@android:style/TextAppearance.Medium"
                android:visibility="gone"/>

        </LinearLayout>




    </RelativeLayout>
    <Button
        android:text="Get Value"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:visibility="gone"
        android:id="@+id/getvalue"
        />

    <TextView
        android:id="@+id/myResult"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content" />
    <EditText
        android:textColor="@color/appColor"
        android:textColorHint="@color/appColor"
        android:inputType="textUri"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:gravity="center"
        android:layout_margin="20dp"
        android:visibility="gone"
        android:id="@+id/et_rtp_url"
        />
    <Button
        android:text="@string/start_record"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginRight="5dp"
        android:id="@+id/b_record"
        android:visibility="gone"
        />
</RelativeLayout>

</androidx.drawerlayout.widget.DrawerLayout>

**Comment by pedroSG94** [comment]
You have a code error:
```java
 //if(prepareEncoders(iSelectedItemPosition,iFPS,iVideoBitrate)){
            if (!rtmpCamera1.isStreaming()) {
                if (rtmpCamera1.isRecording()
                        || rtmpCamera1.prepareAudio() && rtmpCamera1.prepareVideo()) {
                    mBroadCast.setState(true);
                    mBroadCast.setEnabled(true);
                    rtmpCamera1.startStream(value);
                    setLMSLogoToStream();
                } else {
                    Toast.makeText(this, "Error preparing stream, This device cant do it",
                            Toast.LENGTH_SHORT).show();
                }
            } 
```
As you can see you never set 1280x720 resolution because prepareEncoders method is commented, you are using prepareVideo without params

**Comment by mylaimani** [comment]
I only commented it because when we press the Streaming button, the images got disappeared, so only commented it.

             if(prepareEncoders(6,30,2500)){    // in my mobile the value for 6 is 1280 x 720 resolution... I tried but it did not worked
                if (!rtmpCamera1.isStreaming()) {
                  if (rtmpCamera1.isRecording()
                        || rtmpCamera1.prepareAudio() && rtmpCamera1.prepareVideo()) {
                    mBroadCast.setState(true);
                    mBroadCast.setEnabled(true);
                    rtmpCamera1.startStream(value);
                    setLMSLogoToStream();
                } else {
                    Toast.makeText(this, "Error preparing stream, This device cant do it",
                            Toast.LENGTH_SHORT).show();
                }
            } 
          }

**Comment by mylaimani** [comment]
There is one more thing, when I stop the streaming the following error comes

E/AndroidRuntime: FATAL EXCEPTION: Thread-6
    Process: com.lastmanstands.tv, PID: 30554
    java.lang.IllegalStateException
        at android.media.MediaCodec.getBuffer(Native Method)
        at android.media.MediaCodec.getOutputBuffer(MediaCodec.java:3178)
        at com.pedro.encoder.video.VideoEncoder.getDataFromSurfaceAPI21(VideoEncoder.java:371)
        at com.pedro.encoder.video.VideoEncoder.access$000(VideoEncoder.java:33)
        at com.pedro.encoder.video.VideoEncoder$1.run(VideoEncoder.java:249)
        at java.lang.Thread.run(Thread.java:764)

**Comment by mylaimani** [comment]
Now I called this function from onCreate(Bundle savedInstanceState) 

         prepareEncoders(iSelectedItemPosition,iFPS,iVideoBitrate);

Then again from here 

          if(prepareEncoders(iSelectedItemPosition,iFPS,iVideoBitrate)){
            if (!rtmpCamera1.isStreaming()) {
                if (rtmpCamera1.isRecording()
                        || rtmpCamera1.prepareAudio() && rtmpCamera1.prepareVideo()) {
                    mBroadCast.setState(true);
                    mBroadCast.setEnabled(true);
                    rtmpCamera1.startStream(value);
                    setLMSLogoToStream();
                } else {
                    Toast.makeText(this, "Error preparing stream, This device cant do it",
                            Toast.LENGTH_SHORT).show();
                }
            } 

I set the resolution 1920 x 1080 it worked correctly for a period of time, after that it went back to 640 x 480 

After that whatever I change the resolution is not changing it takes only 640 x 480 only...

**Comment by pedroSG94** [comment]
You still have a code error, try this:
```java
if (!rtmpCamera1.isStreaming()) {
            if (rtmpCamera1.isRecording()
                    || prepareEncoders(iSelectedItemPosition,iFPS,iVideoBitrate)) {
                mBroadCast.setState(true);
                mBroadCast.setEnabled(true);
                rtmpCamera1.startStream(value);
                setLMSLogoToStream();
            } else {
                Toast.makeText(this, "Error preparing stream, This device cant do it",
                        Toast.LENGTH_SHORT).show();
            }
        } 
```
About videoencoder crash i'm working in a solution for it.

**Comment by mylaimani** [comment]
Now resolution works perfectly thanks a lot
