### ISSUE TITLE
Camera Resolution

### ISSUE THREAD

**Issue by mylaimani** [pedroSG94/rtmp-rtsp-stream-client-java#424]
At present whenever I load the StreamActivity, it loads 640x480 as default preview, is there any way to change this default preview according resolutions I select. Whenever the Activity loads I want to show 1280x720 resolution...

At present preview changes only at the time I press the Stream Button, before that the Preview is in 640x480

When I load this function onCreate the screen becomes black

      private boolean prepareEncoders(int getSelectedItemPosition, int Fps, int VideoBitrate) {
        Camera.Size resolution =
                rtmpCamera1.getResolutionsBack().get(getSelectedItemPosition);
        int width = resolution.width;
        int height = resolution.height;
        return rtmpCamera1.prepareVideo(width, height, Fps,
                VideoBitrate * 1024,
                false, CameraHelper.getCameraOrientation(this))
                && rtmpCamera1.prepareAudio(128 * 1024,44100,
                true, true,
                true);
      }

**Comment by pedroSG94** [comment]
When you call startPreview method you can select resolution, rotation and camera:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L327
Remember call this method in surfaceChanged callback:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/defaultexample/ExampleRtmpActivity.java#L203
