### ISSUE TITLE
Blank Screenshot

### ISSUE THREAD

**Issue by abadoliverco** [pedroSG94/rtmp-rtsp-stream-client-java#425]
I used this function to take photo

```
rtmpDisplay?.glInterface?.takePhoto {
// save screenshot
}
```

but the screenshot is blank, just black image

**Comment by pedroSG94** [comment]
Can you tell me device model and android version?

**Comment by abadoliverco** [comment]
@pedroSG94 

model: Samsung Galaxy j8
version: 9

**Comment by pedroSG94** [comment]
fixed
