### ISSUE TITLE
How to create 2 stream instances for background and foreground 

### ISSUE THREAD

**Issue by mynew-github-account** [pedroSG94/rtmp-rtsp-stream-client-java#428]
Basically I am trying to implement #318 but I couldn't succeed ,Can you tell how to achieve this  

https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/318#issuecomment-479364151

**Comment by pedroSG94** [comment]
I don't know how to explain it better, This is a common issue so I will develop this feature for camera1 and camera2.

**Comment by lakhanrathi65** [comment]
Thank you ! 
Please let me know once you develop this feature

**Comment by lakhanrathi65** [comment]
Hey on this any update or can you please tell when you are planning to do this according to your convenience 

Thank you!

**Comment by pedroSG94** [comment]
Hi,

For now, I have no time to develop it. 
I'm focus to solve issues because I think that this is more priority than develop other feature.
Remember this is a simply hobby, so I can't tell you a concrete date, but I already started it.
I will write here when the first version is ready.

**Comment by pedroSG94** [comment]
I uploaded first version of this feature. Now, you can change gl view on fly.
This means that you can change to openglview, lightopenglview or background with opengl on fly.

**Comment by lakhanrathi65** [comment]
Hey thanks for feature I tried this but still it disconnect from streaming.

**Comment by pedroSG94** [comment]
Did you try with a service?

**Comment by lakhanrathi65** [comment]
You mean start service and normal streaming together at start of streaming right?
and than on disconnect start service streaming

**Comment by pedroSG94** [comment]
Similar to this:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/backgroundexample/BackgroundActivity.kt
But you should set openglview in surfaceChanged and context in surfaceDestroyed with the new feature. You can use a static method to comunicate with the service

**Comment by lakhanrathi65** [comment]
Yes i am starting service and openglview at same time but when i start stream it disconnect openglview stream and start stream in background both are not running simultaneously so that I can replace one on disconnect of other

**Comment by pedroSG94** [comment]
You don't need 2 instances now. Only one, for this reason I did the last feature. I updated sergice example with this feature:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/backgroundexample/BackgroundActivity.kt
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/backgroundexample/RtpService.kt

**Comment by lakhanrathi65** [comment]
Hey Thank you so much for this.
Just one thing why camera open only on starting the stream not before only


This mean when i open services activity it is complete black
![Screenshot_20191119-163926](https://user-images.githubusercontent.com/41420619/69141796-813be580-0aeb-11ea-97c5-d3dd5db4fc15.png)


And again thanks for feature

**Comment by pedroSG94** [comment]
Yes, this isn't a bug. I didn't add startPreview to example to keep it simple. You can modify it to startPreview, remember that you need wait that surfaceChanged callback is called.

**Comment by lakhanrathi65** [comment]
do you have java version of both file??


https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/backgroundexample/BackgroundActivity.kt
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/backgroundexample/RtpService.kt

**Comment by pedroSG94** [comment]
No, I haven't.

**Comment by mynew-github-account** [comment]
Hey I added startPreview but its not woking

Here is what I have done 

Rtpservice.kt
`package com.pedro.rtpstreamer.backgroundexample

import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.Service
import android.content.Context
import android.content.Intent
import android.os.Build
import android.os.IBinder
import android.util.Log
import androidx.annotation.RequiresApi
import androidx.core.app.NotificationCompat
import com.pedro.encoder.input.gl.render.filters.GreyScaleFilterRender
import com.pedro.rtplibrary.base.Camera1Base
import com.pedro.rtplibrary.base.Camera2Base
import com.pedro.rtplibrary.rtmp.RtmpCamera1
import com.pedro.rtplibrary.rtmp.RtmpCamera2
import com.pedro.rtplibrary.rtsp.RtspCamera1
import com.pedro.rtplibrary.rtsp.RtspCamera2
import com.pedro.rtplibrary.view.OpenGlView
import com.pedro.rtpstreamer.R


/**
 * Basic RTMP/RTSP service streaming implementation with camera2
 */
@RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)
class RtpService : Service(), ConnectCheckerRtp {

  private val TAG = "RtpService"
  private val channelId = "rtpStreamChannel"
  private val notifyId = 123456
  private var notificationManager: NotificationManager? = null
  private var endpoint: String? = null

  override fun onCreate() {
    super.onCreate()
    Log.e(TAG, "RTP service create")
    notificationManager = getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
      val channel = NotificationChannel(channelId, channelId, NotificationManager.IMPORTANCE_HIGH)
      notificationManager?.createNotificationChannel(channel)
    }
    keepAliveTrick()
  }

  private fun keepAliveTrick() {
    if (Build.VERSION.SDK_INT > Build.VERSION_CODES.O) {
      val notification = NotificationCompat.Builder(this, channelId)
        .setOngoing(true)
        .setContentTitle("")
        .setContentText("").build()
      startForeground(1, notification)
    } else {
      startForeground(1, Notification())
    }
  }

  override fun onBind(p0: Intent?): IBinder? {
    return null
  }

  override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
    Log.e(TAG, "RTP service started")
    endpoint = intent?.extras?.getString("endpoint")
    if (endpoint != null) {
      prepareStreamRtp()
      startStreamRtp(endpoint!!)
    }
    return START_STICKY
  }

  companion object {
    private var camera2Base: Camera1Base? = null
//      private var rtmp1 : RtmpCamera1? = null
    private var openGlView: OpenGlView? = null
//      rtmp1=RtmpCamera1(openGlView, this)


    fun setView(openGlView: OpenGlView) {
      this.openGlView = openGlView
      camera2Base?.replaceView(openGlView)
    }
      fun preview(openGlView: OpenGlView) {
          this.openGlView = openGlView

          camera2Base?.startPreview()
      }
    fun setView(context: Context) {
      this.openGlView = null
      camera2Base?.replaceView(context)
    }
  }

  override fun onDestroy() {
    super.onDestroy()
    Log.e(TAG, "RTP service destroy")
    stopStreamRtp()
  }

  private fun prepareStreamRtp() {
    if (endpoint!!.startsWith("rtmp")) {
      camera2Base = if (openGlView == null) {
        RtmpCamera1(baseContext,this)
      } else {
        RtmpCamera1(openGlView, this)

      }
    } else {
      camera2Base = if (openGlView == null) {
        RtspCamera1(baseContext, this)
      } else {
        RtspCamera1(openGlView, this)
      }
    }
  }

  private fun startStreamRtp(endpoint: String) {
    if (!camera2Base!!.isStreaming) {
      if (camera2Base!!.prepareVideo() && camera2Base!!.prepareAudio()) {
        camera2Base!!.startStream(endpoint)
        camera2Base!!.getGlInterface().setFilter(GreyScaleFilterRender())
      }
    } else {
      showNotification("You are already streaming :(")
    }
  }

  private fun stopStreamRtp() {
    if (camera2Base != null) {
      if (camera2Base!!.isStreaming) camera2Base!!.stopStream()
      if (camera2Base!!.isOnPreview) camera2Base!!.stopPreview()
    }
  }

  private fun showNotification(text: String) {
    val notification = NotificationCompat.Builder(this, channelId)
      .setSmallIcon(R.mipmap.ic_launcher)
      .setContentTitle("RTP Stream")
      .setContentText(text).build()
    notificationManager?.notify(notifyId, notification)
  }

  private fun stopNotification() {
    notificationManager?.cancel(notifyId)
  }

  override fun onConnectionSuccessRtp() {
    showNotification("Stream started")
    Log.e(TAG, "RTP service destroy")
  }

  override fun onNewBitrateRtp(bitrate: Long) {

  }

  override fun onConnectionFailedRtp(reason: String) {
    showNotification("Stream connection failed")
    Log.e(TAG, "RTP service destroy")
  }

  override fun onDisconnectRtp() {
    showNotification("Stream stopped")
  }

  override fun onAuthErrorRtp() {
    showNotification("Stream auth error")
  }

  override fun onAuthSuccessRtp() {
    showNotification("Stream auth success")
  }
}
`






and BackgroundActivity.kt

`package com.pedro.rtpstreamer.backgroundexample

import android.app.ActivityManager
import android.content.Context
import android.content.Intent
import android.os.Bundle
import android.view.SurfaceHolder
import androidx.appcompat.app.AppCompatActivity
import com.pedro.rtpstreamer.R
import kotlinx.android.synthetic.main.activity_background.*

class BackgroundActivity : AppCompatActivity(), SurfaceHolder.Callback {

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    setContentView(R.layout.activity_background)
    b_start_stop.setOnClickListener {
      if (isMyServiceRunning(RtpService::class.java)) {
        stopService(Intent(applicationContext, RtpService::class.java))
        b_start_stop.setText(R.string.start_button)
      } else {
        val intent = Intent(applicationContext, RtpService::class.java)
        intent.putExtra("endpoint", et_rtp_url.text.toString())
        startService(intent)
        b_start_stop.setText(R.string.stop_button)
      }
    }
    surfaceView.holder.addCallback(this)
  }

  override fun surfaceChanged(p0: SurfaceHolder?, p1: Int, p2: Int, p3: Int) {
    RtpService.setView(surfaceView)
    RtpService.preview(surfaceView)


  }

  override fun surfaceDestroyed(p0: SurfaceHolder?) {
    RtpService.setView(applicationContext)
  }

  override fun surfaceCreated(p0: SurfaceHolder?) {
    RtpService.setView(surfaceView)

  }

  override fun onResume() {
    super.onResume()
    if (isMyServiceRunning(RtpService::class.java)) {
      b_start_stop.setText(R.string.stop_button)
    } else {
      b_start_stop.setText(R.string.start_button)
    }
  }

  @Suppress("DEPRECATION")
  private fun isMyServiceRunning(serviceClass: Class<*>): Boolean {
    val manager = getSystemService(Context.ACTIVITY_SERVICE) as ActivityManager
    for (service in manager.getRunningServices(Integer.MAX_VALUE)) {
      if (serviceClass.name == service.service.className) {
        return true
      }
    }
    return false
  }
}
`

**Comment by mynew-github-account** [comment]
Any update on this ???

**Comment by pedroSG94** [comment]
Example modified to work with preview:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/6fd633cd5fb19eede8ed186e270cb476e2c2e124

**Comment by mynew-github-account** [comment]
Thanks working fine
