### ISSUE TITLE
Camera api2 streaming video is rotated

### ISSUE THREAD

**Issue by minmax9493** [pedroSG94/rtmp-rtsp-stream-client-java#429]
I used RTMP with texture mode example. However, when I start streaming on portrait mode the streaming video is rotated. It works only for inverse landscape mode. I handled portrait and fake landscape issues using camera1 api by changing rotation parameter in `videoEncoder.prepareVideoEncoder(width, height, fps, bitrate, rotation, hardwareRotation,
        iFrameInterval, formatVideoEncoder);` 
 
function and also send rotated frame by inputYUV to encoder. 

`  @Override
  public void onPreviewFrame(byte[] data, Camera camera) {
    getCameraData.inputYUVData(new Frame(data, rotation, isFrontCamera && isPortrait, imageFormat));
  }`
Portrait and landscape mode worked for me by changing rotation. How can I achieve this with camera 2 api on texture mode.

**Comment by pedroSG94** [comment]
If you are using camera2 you should change to lightopenglview or openglview to solve rotation problems because your device doesn't support hardware rotation.
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/167
