### ISSUE TITLE
Clarifications about camera initiating

### ISSUE THREAD

**Issue by Radcat501** [pedroSG94/rtmp-rtsp-stream-client-java#431]
Hello! Thanks for nice lib and good feedback! I have some troubles, can i have some clarifications?

I am using rtmpCamera1 on usual SurfaceView. Here is my initial code:

```
 surfaceView.holder.addCallback(this)
 rtmpCamera = RtmpCamera1(surfaceView, this)
 if (!rtmpCamera.prepareVideo() && !rtmpCamera.prepareVideo()) return

 if (rtmpCamera.isStreaming) rtmpCamera.stopStream()

 if (rtmpCamera.isRecording || rtmpCamera.prepareAudio() && rtmpCamera.prepareVideo()) {
      rtmpCamera.startStream(streamURL)
 }
```

in SurfaceHolder callback surfaceChanged(...) i am calling 
`rtmpCamera.startPreview()`

Stream works nice, but problem is in camera. When stream just launched surfaceView was just black screen, but when i started to switch camera, image appeared and all worked fine. I tried use `rtmpCamera.startPreview(CameraHelper.Facing.BACK)` to prevent initial black screen but this not helped. 

Here is my workaround for this issue 
```
fun setCamera(state: Boolean) {
        // false - Back camera
        // true - Front camera
        if(state && rtmpCamera.isFrontCamera) return

        if(state && !rtmpCamera.isFrontCamera) rtmpCamera.switchCamera()

        if(!state && rtmpCamera.isFrontCamera) rtmpCamera.switchCamera()

        if(!state && !rtmpCamera.isFrontCamera) {
            rtmpCamera.switchCamera()
            rtmpCamera.switchCamera()
        }
}
```
But this looks very unstable. Maybe i didnt noticed some special method for camera settings, something like
`rtmpCamera.setCameraFacing(CameraHelper.Facing.BACK)`

**Comment by pedroSG94** [comment]
Are you calling startStream in onCreate method?
You need call it in surfaceChanged callback because startStream() also start a preview.
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L381

**Example:**
```kotlin
class ActivityExample : AppCompatActivity(), ConnectCheckerRtmp, SurfaceHolder.Callback {

  private lateinit var rtmpCamera1: RtmpCamera1

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    setContentView(R.layout.activity_main)
    rtmpCamera1 = RtmpCamera1(surfaceView, this)
    surfaceView.holder.addCallback(this)
  }

  override fun surfaceChanged(p0: SurfaceHolder?, p1: Int, p2: Int, p3: Int) {
    //Start stream when activity is created or resumed
    if (rtmpCamera1.prepareAudio() && rtmpCamera1.prepareVideo()) {
      rtmpCamera1.startStream("streamURL")
    }
  }

  override fun surfaceDestroyed(p0: SurfaceHolder?) {
    //Stop stream when activity is closed or paused
    if (rtmpCamera1.isStreaming) rtmpCamera1.stopStream()
    if (rtmpCamera1.isRecording) rtmpCamera1.stopRecord()
    if (rtmpCamera1.isOnPreview) rtmpCamera1.stopPreview()
  }
}
```

**Comment by Radcat501** [comment]
Yes, i called it in onViewCreated() of fragment, my mistake. Your code solved the problem, thanks a lot!
