### ISSUE TITLE
Filters and bitmap memory leak ? 

### ISSUE THREAD

**Issue by Goule** [pedroSG94/rtmp-rtsp-stream-client-java#436]
Hello ! 

Firstly, thank for this library ! :-) 

I have some trouble with the memory management of my application and the filter. When I perform a filter change the memory (the Graphics part) increase at every occurence and the app crash after 25/40m of stream. 

Use case : every X seconde, filters are changed on the stream. 

Here is my code : 
```kotlin
private var logos: List<Bitmap> = mutableListOf()    

private fun showPartners() {
	val delayMillis = delay * 1000L
	Observable.interval(0, delayMillis, TimeUnit.MILLISECONDS)
		.map {
			getBitmap() // retrieve the right Bitmap object from logos array
		}
	.autoDispose(this, Lifecycle.Event.ON_DESTROY)
	.subscribe { bitmapToDisplay ->
				withCamera {
					val imageObjectFilterRender = ImageObjectFilterRender()
                    it.glInterface.setFilter(1, imageObjectFilterRender)
                    imageObjectFilterRender.apply {
                    	setImage(bitmapToDisplay.copy(bitmapToDisplay.config, true))
                        setPosition(TranslateTo.CENTER)
					}
				}
			   }
}
```
In the memory profiler I can see the increase number of Bitmap staying in memory.
It is possible that the `setFilter` is not release the older filter and keep it in memory ? 
Or do you think it's not related to the filters ?

Thanks !

**Comment by pedroSG94** [comment]
The filter should be released automatically when you set a filter in the same position:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/gl/render/ManagerRender.java#L97
It seems a bug. I will check it

**Comment by pedroSG94** [comment]
I'm not sure about it but this look the problem.
```java
bitmapToDisplay.copy(bitmapToDisplay.config, true)
```
You are doing a copy of the original bitmap but I can't see a release of the original bitmap

**Comment by Goule** [comment]
The original bitmap are stored into an array `private var logos: List<Bitmap> = mutableListOf() `. If I don't make a copy the stream crash with the reason that the bitmap are already recycled. 

I tried to store the bitmap copy into a variable and recycle it but the leak is remaining.
```kotlin
                    withCamera {
                        val imageObjectFilterRender = ImageObjectFilterRender()
                        it.glInterface.setFilter(1, imageObjectFilterRender)
                        val bitmap = bitmapToDisplay.copy(bitmapToDisplay.config, true)
                        imageObjectFilterRender.apply {
                            setImage(bitmap)
                            setPosition(TranslateTo.CENTER)
                        }
                        previousBitmapFilter?.recycle()
                        previousBitmapFilter = bitmap
                    }
```

**Comment by pedroSG94** [comment]
Ok. I can confirm that memory increase if you set multiple times bitmaps but recycled bitmap is called.
Can you tell me where are you getting number of bitmap in memory?

**Comment by Goule** [comment]
I double checked, the number of bitmap seems to be ok (even it's a big number).
You can check it in the profile + click on the heap dump button. 

<img width="1274" alt="Screenshot 2019-10-25 at 14 39 34" src="https://user-images.githubusercontent.com/21126201/67571863-48e7f800-f735-11e9-931a-fe08507640bc.png">

So, the increase of memory is the normal behavior when we are set multiple times bitmaps ? :( 
Is there any way to purge or optimise this ? 
Actually we can't stream more than 30 min with some device (like Huawei). It seems to be different accross devices (Nexus or Pixel seems to be less impacted).

**Comment by pedroSG94** [comment]
This seems to be an OpenGL problem. Maybe in release texture or program.

**Comment by Goule** [comment]
Ok, many thanks 🤞🏻

**Comment by pedroSG94** [comment]
I did a fix for it:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/87da9d4ce5ec17626e3d2d3cf652b906a7e02c30
I did a test of 45min with this result:
![Captura de pantalla de 2019-10-25 23-26-33](https://user-images.githubusercontent.com/17556876/67605730-7b1e4780-f77f-11e9-8ad0-6f7567521993.png)
![Captura de pantalla de 2019-10-25 23-26-57](https://user-images.githubusercontent.com/17556876/67605732-7b1e4780-f77f-11e9-8b1a-586a52eefe4e.png)

To discard problems with my library clone last commit, go to OpenGl RTMP or OpenGl RTSP and replace:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L293
with (This code is similar to your code):
```java
  private void setImageToStream() {
    final ImageObjectFilterRender imageObjectFilterRender = new ImageObjectFilterRender();
    final Bitmap bitmap = BitmapFactory.decodeResource(getResources(), R.mipmap.ic_launcher);
    rtmpCamera1.getGlInterface().setFilter(imageObjectFilterRender);
    new Thread(new Runnable() {
      @Override
      public void run() {
        while (true) {
          imageObjectFilterRender.setImage(bitmap.copy(bitmap.getConfig(), true));
          imageObjectFilterRender.setPosition(TranslateTo.RIGHT);
          imageObjectFilterRender.setScale(50, 50);
          //spriteGestureController.setBaseObjectFilterRender(imageObjectFilterRender); //Optional
          //spriteGestureController.setPreventMoveOutside(false); //Optional
          try {
            Thread.sleep(1000);
          } catch (InterruptedException e) {
            e.printStackTrace();
          }
        }
      }
    }).start();
  }
```

**Comment by Goule** [comment]
Wow thanks ! I will try this asap, thanks !

**Comment by Goule** [comment]
I just tried and it's ok, the memory leak seems to be gone ! 
Thanks for your fix :)

**Comment by Goule** [comment]
Hello, 
It work ! Thanks :-)

**Comment by Goule** [comment]
Hello ! 
Since I updated the library with this commit I have a new crash only in this version : 

<img width="1152" alt="Screenshot 2019-11-04 at 09 17 35" src="https://user-images.githubusercontent.com/21126201/68107146-25b30a80-fee4-11e9-9839-f35d57b55416.png">

Do you think it can be related with your fix ? 

Thanks !

**Comment by pedroSG94** [comment]
This was related with this commit:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/d3a899c9e52beca11739da8259ec3d2d46442b0d
Fixed here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/6b99514ea8674f358787f1631ab7d99f42d8a02b

**Comment by Goule** [comment]
Ok thanks !!

**Comment by Goule** [comment]
Are you sure this commit is fixing this crash ? 

I still got it even with `implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:da957ae'`

**Comment by Goule** [comment]
Oh, it wasn't the right commit ref (`da957ae` instead of `6b99514`) ! 
This is ok now :)

**Comment by pedroSG94** [comment]
Can you tell steps to reproduce it?
I only detected this error on camera switch with openglview.

**Comment by Goule** [comment]
It's ok, it was my mistake, I pointed the wrong commit in my gradle file ! Thanks
