### ISSUE TITLE
Access denied finding property "persist.camera.cfa.packagelist"

### ISSUE THREAD

**Issue by AnatolyKuznetsov** [pedroSG94/rtmp-rtsp-stream-client-java#437]
I am using camera2 code for camera
but when I swipe nfc card, I can't capture image because above error
please help me

**Comment by pedroSG94** [comment]
This look an error with specific device model.
Can you tell me your device model and Android API?
Also you can try this:
https://stackoverflow.com/questions/48260712/access-denied-finding-property-camera-hal1-packagelist?rq=1
