### ISSUE TITLE
RTMPDisplay service

### ISSUE THREAD

**Issue by kamal0808** [pedroSG94/rtmp-rtsp-stream-client-java#438]
Hi, I am trying to trigger display streaming from a remote server, hence there's no user activity involved.
But RTMPDisplay requires onActivityResult(..) in order to proceed, so I'm unable to build an IntentService class for it.
Can you help how to do it?

**Comment by pedroSG94** [comment]
Unfortunatelly you can't do it without an activity. I think that it is for security reasons
This is a part of MediaProjectionManager APi:
https://developer.android.com/reference/android/media/projection/MediaProjectionManager
