### ISSUE TITLE
rear and front camera rotation conflict

### ISSUE THREAD

**Issue by K0EZ** [pedroSG94/rtmp-rtsp-stream-client-java#44]
Hello,
i tried the library on 9 devices
by default the rear cam working great (portrait) but the front cam is flipped up side down
if i set the rotation degree to 270 , the front cam is ok but the rear is now flipped

also if possible to set which camera to start from the builder would be useful
 
thanks in advance

**Comment by pedroSG94** [comment]
I will implement the rotation but select camera, in my opinion, is not necesary. You can simply change camera after use start. Anyway if you really need you can modify base builder that you need and add the camera id in the constructor.

**Comment by pedroSG94** [comment]
fixed on version 1.1.2 or last commit: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/4b2675fb73bef32b8f1caa79e93d214dbcdb41ed
remember gradle compile change go to readme to know the change

**Comment by K0EZ** [comment]
thanks for your help 
do you accept donation via paypal for such amazing work ?

**Comment by pedroSG94** [comment]
I never thought about it. This is a hobby.
