### ISSUE TITLE
Get frames from stream.

### ISSUE THREAD

**Issue by Radcat501** [pedroSG94/rtmp-rtsp-stream-client-java#441]
Hello again!
I am sorry for another one question, but looks like i cant handle it without your help. 

So, i am using RtmpCamera1 for stream, and OpenGlView as surface. I am making MotionDetector class, which will detect motion on video with help Android OpenCV library. The main idea is:
1. We taking frames from screen one by one
2. Comparing them with OpenCV instruments
3. If frames not equal - alarm! Motion detected.

 At the moment i have problem with getting frames from stream. When surfaceChanged() is called, i am calling start method where tried to get frames:

```
val frame = Mat() // Matrix from OpenCV
val surfaceTexture = openGlView.surfaceTexture

surfaceTexture.setOnFrameAvailableListener {
   // somehow here i need to get frame and convert it to OpenCv Mat()
}
```
But when i add listener, stream screen becomes black and listener gets frame only one time. As i figured it, thats because this listener already setted and used in OpenGlView class and when i reset it, this ruining all work with stream. So i need some better solution, which will not ruin another stream engines. I will appreciate any help.

Thanks!

**Comment by pedroSG94** [comment]
You have multiple ways to do it but you need modify the library for it. In my opinion the best solution is with camera1 and OpenGlView.
You should:
- Go to Camera1ApiManager and modify start to get buffer from camera continuously.
Modify this line:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java#L167
To:
```java
        camera.setPreviewTexture(surfaceTexture);
        camera.addCallbackBuffer(yuvBuffer);
        camera.setPreviewCallbackWithBuffer(this);
```
- Now you should avoid that VideoEncoder receive a frame from it because this is still configured to work surface to buffer for this reason you cant set a buffer to VideoEncoder.

Delete this line:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L684
And replace it with a custom callback created for you where you will receive frames continously and you can use it with OpenCV (remenber that this frame always have rotation to 0 so maybe you need rotate it).
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L412

**Comment by Radcat501** [comment]
Alright, thanks a lot! I'll try it and inform you about results later.

**Comment by Radcat501** [comment]
So, at the moment forked project and made changes, which you proposed. Then, i am added my custom frame listener:

```
 @Override
  public void inputYUVData(Frame frame) {
    framesListener.getFrames(frame);
  }
```

After, i made some preparations from side of my app, and firstly i had a crash on this string:

` getCameraData.inputYUVData(new Frame(data, rotation, isFrontCamera && isPortrait, imageFormat));`

Because getCameraData was null, so i fixed it, adding parameter getCameraData in this constructors:

```
public Camera1ApiManager(TextureView textureView, GetCameraData getCameraData) {
    this.textureView = textureView;
    this.getCameraData = getCameraData;
    this.context = textureView.getContext();
    init();
  }

  public Camera1ApiManager(SurfaceTexture surfaceTexture, GetCameraData getCameraData, Context context) {
    this.surfaceTexture = surfaceTexture;
    this.getCameraData = getCameraData;
    this.context = context;
    init();
  }
```

Now i getting Frames and trying create bitmap from them:

```
fun start(streamFrame: Frame) { 
val bitmap = BitmapFactory.decodeByteArray(streamFrame.buffer, streamFrame.offset, streamFrame.buffer.size)
...
}
```

 but seems something goes wrong, here is my logs:

> 2019-11-04 13:28:41.000 23119-23119 E/TEST: ===================================================
> 2019-11-04 13:28:41.000 23119-23119 E/TEST: FRAME BYTES SIZE 460800
> 2019-11-04 13:28:41.000 23119-23119 E/TEST: FRAME OFFSET 0
> 2019-11-04 13:28:41.001 23119-23119 E/TEST: BITMAP: null
> 2019-11-04 13:28:41.035 23119-23119 E/TEST: ===================================================
> 2019-11-04 13:28:41.035 23119-23119 E/TEST: FRAME BYTES SIZE 460800
> 2019-11-04 13:28:41.035 23119-23119 E/TEST: FRAME OFFSET 0
> 2019-11-04 13:28:41.035 23119-23119 E/TEST: BITMAP: null
> 2019-11-04 13:28:41.069 23119-23119 E/TEST: 

Maybe i mistaked in something?

**Comment by Radcat501** [comment]
Found the problem, i should convert YUV image to JPEG before get bitmap. Looks like i am alredy have frames. Thanks for help and assistance!

**Comment by Radcat501** [comment]
P.S.

Maybe this will be usefull for you or your lib - this is my code for motion detection. Sensivity of detection depends on MOTION_DETECTOR_THRESHOLD.

```
object MotionDetector {

    const val MOTION_DETECTOR_THRESHOLD = 300
    const val YUV_TO_JPEG_CONVERTATION_QUALITY = 80

    private val compareFrameBuffer = ArrayList<Mat>()

    fun bitmapToMat(bitmap: Bitmap): Mat {
        val mat = Mat(bitmap.height, bitmap.width, CvType.CV_8U, Scalar(4.0))
        val bitmap32 = bitmap.copy(Bitmap.Config.ARGB_8888, true)
        Utils.bitmapToMat(bitmap32, mat)
        return mat
    }

    private fun convertYuvToJpeg(frame: Frame, size: Size): ByteArray {

        val width = size.width
        val height = size.height

        val yuv = YuvImage(frame.buffer, frame.format, width, height, null)

        val outputStream = ByteArrayOutputStream()
        val quality = YUV_TO_JPEG_CONVERTATION_QUALITY
        val rect = Rect(0, 0, width, height)
        yuv.compressToJpeg(rect, quality, outputStream)

        return outputStream.toByteArray()
    }

    private fun bytesToBitmap(imageBytes: ByteArray): Bitmap {
        return BitmapFactory.decodeByteArray(imageBytes, 0, imageBytes.size)
    }

    private fun compareFrames() {

        val firstMat = compareFrameBuffer[0]
        val secondMat = compareFrameBuffer[1]

        val outputImageMat = Mat()
        val outputMat = Mat()

        Core.compare(firstMat, secondMat, outputImageMat, Core.CMP_LE)

        val contours = ArrayList<MatOfPoint>()

        Imgproc.cvtColor(outputImageMat, outputMat, Imgproc.COLOR_BGR2GRAY)
        Imgproc.findContours(outputMat, contours, Mat(), Imgproc.RETR_EXTERNAL, Imgproc.CHAIN_APPROX_SIMPLE)

        if(contours.size > MOTION_DETECTOR_THRESHOLD) Log.e("TEST", "MOTION DETECTED")

        compareFrameBuffer.remove(firstMat)
    }

    fun start(streamFrame: Frame, streamSize: Size) {

        val convertedBytes = convertYuvToJpeg(streamFrame, streamSize)
        val bitmap = bytesToBitmap(convertedBytes)

        compareFrameBuffer.add(bitmapToMat(bitmap))

        if(compareFrameBuffer.size == 2) {
            compareFrames()
        }
    }
}
```

**Comment by AlexanderKozhevin** [comment]
@Radcat501 Hello, sorry can you give an example your your * framesListener* ?
I want to modify frame to add some effects.
