### ISSUE TITLE
Amplitude of the streaming

### ISSUE THREAD

**Issue by TapanM** [pedroSG94/rtmp-rtsp-stream-client-java#444]
Hello,

Is there any way to get the amplitude of the streaming? If not then can we get the buffer data that is being sent so that we can calculate the amplitude? 

Thank you for the awesome library.

**Comment by pedroSG94** [comment]
Do you means audio amplitude?

In this case, this is not supported, you sneed modify library. If you want get audio buffer, you can create a callback in your base used. You can find the buffer here for camera1, if you want other case, the method name is the same in all bases.
- PCM buffer:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L678
- AAC buffer:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L647

**Comment by TapanM** [comment]
Yes, audio amplitude. cool, I'll try to modify library and get the buffer.

**Comment by TapanM** [comment]
`@Override
  public void inputPCMData(Frame frame) {
    audioBufferListener.sendBuffer(frame.getBuffer());
    audioEncoder.inputPCMData(frame);
  }`

is this a correct way to get audio buffer array?

**Comment by pedroSG94** [comment]
Yes, but remember that you will need create a copy of buffer to avoid issues when you modify it.

**Comment by TapanM** [comment]
sure. thanks for your support.
