### ISSUE TITLE
RTPService getting destroyed

### ISSUE THREAD

**Issue by GGPENG** [pedroSG94/rtmp-rtsp-stream-client-java#448]
Hi!

I'm trying to stream from ''background'' using RTPService. It works fine when the activity is on the foreground. When I swipe to another app, the streaming service lasts for about 20 seconds and then gets destroyed. 

Logcat shows onDestroy log message "E/RtpService: RTP service destroy" and "E/Camera2ApiManager: Open failed"

Using Samsung Note8 API 28

**Comment by pedroSG94** [comment]
This seems that system destroy your service for battery safe:
https://stackoverflow.com/questions/49637967/minimal-android-foreground-service-killed-on-high-end-phone
I can't do anything about it.

**Comment by GGPENG** [comment]
Just solve this issue in API 26+. 
It works if you build a service with WakeLock.
https://robertohuertas.com/2019/06/29/android_foreground_services/
