### ISSUE TITLE
Image filter position 

### ISSUE THREAD

**Issue by Goule** [pedroSG94/rtmp-rtsp-stream-client-java#451]
Hello, 

I'm trying to place a filter (with `ImageObjectFilterRender`) at specific position of my stream like this : 
![jpeg](https://user-images.githubusercontent.com/21126201/69150635-61032b00-0ad9-11ea-877b-590c4b1ce0d7.jpg)
And with the code : 
```kotlin
val imageObjectFilterRender = ImageObjectFilterRender()
it.glInterface.setFilter(1, imageObjectFilterRender)
imageObjectFilterRender.apply {
    setImage(bitmap)
    setPosition(TranslateTo.TOP_RIGHT)
}
```

Is there any way to specify ratio or position like in my picture ? 

Thanks :)

**Comment by pedroSG94** [comment]
As you can read here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Real-time-filters
setFilter(position, filter) is only necessary if you use multiple filters.
In your case, you can use set filter like:
```java
val imageObjectFilterRender = ImageObjectFilterRender()
it.glInterface.setFilter(imageObjectFilterRender)
imageObjectFilterRender.apply {
            setImage(bitmap)
            setPosition(TranslateTo.TOP_RIGHT)
            setScale(50f, 20f)
}
```

**Comment by Goule** [comment]
Many thanks ! 

I have noticed that the `BaseFilterRender` is less cleaner than the `ImageObjectFilterRender` (it depends on the device). So finally I'm converted all my watermark into Bitmap and I make only `ImageObjectFilterRender`.  I guess this is less efficiant in term of performance, but the incrustation is in better quality.
