### ISSUE TITLE
Error handling & Broken pipe

### ISSUE THREAD

**Issue by floriangbh** [pedroSG94/rtmp-rtsp-stream-client-java#453]
Hello, 

I'm working on stream resiliance and I would like to inform my users when the stream is down.
When I'm launching stream on Facebook, if I stop (or delete) the stream from Facebook, the librarie logs indefinitely this informations : 
```java
E/RtmpConnection: Caught IOException during write loop, shutting down: Write error: ssl=0x6fc0e10408: I/O error during system call, Broken pipe
V/NativeCrypto: Write error: ssl=0x6fc0e10408: I/O error during system call, Broken pipe
```
According to this issue : https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/329 the error should be appear in `onConnectionFailedRtmp` but my breakpoint is never called inside. 
The `onDisconnectRtmp` is also never called. 

I'm using the v1.7.2.

What is the best way to make a good error handling ? 

Thanks

**Comment by pedroSG94** [comment]
This was a bug. Fixed here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/6470ff39207d957456a92b3a6b8f5cbae0799ac9
You can compile this version if you need use gradle:
```
implementation 'com.github.pedroSG94:rtmp-rtsp-stream-client-java:6470ff3920'
```

**Comment by floriangbh** [comment]
Thanks I will try it asap :)
