### ISSUE TITLE
Support new customized protocol?

### ISSUE THREAD

**Issue by zhaiduo** [pedroSG94/rtmp-rtsp-stream-client-java#454]
Hi pedroSG94,

I am new to stream coding in java, thank you to share us with this great library. 
I wonder how to add a whole new private protocol to this library, just like rtmp and rtsp.

First, I want to create my own customized camera1, client and sender, which I can get H264 data. The second step is to send data to my own private protocol.

That's what I want to do. Do you have any suggestions for this? Thanks very much!

**Comment by pedroSG94** [comment]
Hi,

The best way is create a class to replace SrsFlvMuxer or RtspClient but with your own protocol and extends from Camera1Base like here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtmp/RtmpCamera1.java

**Comment by zhaiduo** [comment]
Thanks a lot, very appreciate!
