### ISSUE TITLE
Awesome code !!!

### ISSUE THREAD

**Issue by fabio-delorenzo-wowza** [pedroSG94/rtmp-rtsp-stream-client-java#455]
I love this:
        || name.equals("c2.qti.avc.encoder")) && Build.MODEL.equals("Pixel 3a")) {

Took me forever to find Pixel 3a encoder is broken !

**Comment by pedroSG94** [comment]
That code was a solution for this issue:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/381
Feel free to create a PR if you find other encoder bugged.

**Comment by pedroSG94** [comment]
Already solved in: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/381
