### ISSUE TITLE
Camera doesn't work after switch

### ISSUE THREAD

**Issue by exxKx** [pedroSG94/rtmp-rtsp-stream-client-java#457]
RtmpCamera2

caught bug steps:
1 start preview 
2 stop preview
3 start stream
4 switch camera - this step broke camera 
5 stop stream

if we decide start preview or stream again camera doesn't work. No data from camera.

**Comment by pedroSG94** [comment]
What view are you using? SurfaceView, TextureView orOpenglview ?

**Comment by exxKx** [comment]
Log: Camera2ApiManager: Open failed.
I use Openglview.

**Comment by pedroSG94** [comment]
You need close camera
Try this:
1 start preview
2 stop preview
3 start stream
4 switch camera - this step broke camera
5 stop stream
6 stop Preview (this will release camera and solve startPreview problem. StartStream should work, I will check it)

About broke camera, what do you means? do you get a preview freeze or an error?. 
In error case make sure that your camera support same resolution for back and front camera.
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/surfacemodeexample/SurfaceModeRtmpActivity.java#L147

**Comment by pedroSG94** [comment]
I did a little modification to reproduce your step and this is working for me. I added this to reproduce your case:
```java
  int cont = 0;
  @Override
  public void onClick(View view) {
    switch (view.getId()) {
      case R.id.b_start_stop:
        if (cont == 0) rtmpCamera1.stopPreview();
        cont++;
        if (!rtmpCamera1.isStreaming()) {
       ...
```
Here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/surfacemodeexample/SurfaceModeRtmpActivity.java#L129
Also replace RtmpCamera1 to RtmpCamera2:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/surfacemodeexample/SurfaceModeRtmpActivity.java#L34

**Comment by exxKx** [comment]
**Solved**

Ty, I had this problem because I don't call stopPreview  after stopStream.
