### ISSUE TITLE
screenRender ends up rendering at encoder resolution

### ISSUE THREAD

**Issue by troy-lamerton** [pedroSG94/rtmp-rtsp-stream-client-java#458]
OpenGlView can be used record anything by drawing into the surface provided by `OpenGlView.getSurface()` (OpenGlView extends GlInterface).

File:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/24d3130e4aca3cbc39c1a4af464b29c5658731ec/rtplibrary/src/main/java/com/pedro/rtplibrary/view/OpenGlView.java#L127

1. cameraRender.draw() draws at preview resolution
2. baseFilterRender.draw() draws on top at the smaller *encoder resolution*
3. `drawScreen(previewWidth, previewHeight)` draws pixelated frame to screen

## Reproduce steps

1. set a low resolution for the encoder.
```kt
openGlView.setEncoderSize(570, 270)
```
2. Add openGlView to the window
```kt
// fullscreen view
val matchParent = ViewGroup.LayoutParams.MATCH_PARENT
openGlView.layoutParams = ViewGroup.LayoutParams(matchParent, matchParent)
```
3. When surface is ready
```kt
openGlView.init()
openGlView.start()
```
4. `getSurface()` and start drawing into it

What resolution should the view be rendering at?
I would expect to see fullscreen resolution, full HD quality.
What actually happens is the view looks pixelated, the surface is rendering 
at the encoder size!

Actual: Fullscreen view with setEncoderSize(570, 270)
![570x270 Screenshot_20191203-115610](https://user-images.githubusercontent.com/13446008/70046837-1ac4c600-15c7-11ea-89e8-2c89a30de476.jpg)

Expected: looks good but setEncoderSize is same as preview size
![2280x1080 Screenshot_20191203-115801](https://user-images.githubusercontent.com/13446008/70046838-1ac4c600-15c7-11ea-9d7d-ce5a90ab2dc6.jpg)

## Cause
When the drawing loop runs, I belive this happens:

```java
  // OpenGlView.java
  @Override
  public void run() {
    ...
    // draw camera at preview size, then draw filters at encoder size
    managerRender.drawOffScreen();
    // now draw the output (last filter) at preview size
    // but wait, the filters were drawn at encoder size!
    managerRender.drawScreen(previewWidth, previewHeight, keepAspectRatio);
    ...
  }
```

## Relevant code

Why does baseFilterRender get initialized with `encoderWidth` and `encoderHeight`?

https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/24d3130e4aca3cbc39c1a4af464b29c5658731ec/encoder/src/main/java/com/pedro/encoder/input/gl/render/ManagerRender.java#L51

Is there good reason for this behaviour?
I want to understand this line because I will be changing it in my fork.
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/24d3130e4aca3cbc39c1a4af464b29c5658731ec/encoder/src/main/java/com/pedro/encoder/input/gl/render/ManagerRender.java#L51

**Comment by pedroSG94** [comment]
First of all. Draw resolution depend of surfaceManager focused in that moment.
- Focus to Preview surface (Surface from SurfaceView):
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/view/OpenGlView.java#L125
- Focus to VideoEncoder surface:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/view/OpenGlView.java#L137

This line is used to let filter know resolution of encoder and preview. 
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/gl/render/ManagerRender.java#L51
Preview resolution is necessary only in this filter:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/gl/render/filters/AndroidViewFilterRender.java#L88
Also encoder resolution is used in others filters like:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/gl/render/filters/PolygonizationFilterRender.java#L76
Or in FBO:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/gl/render/filters/BaseFilterRender.java#L41

About drawScreen. Resolution is necessary to set a correct aspect ratio and resolution. It depends on whether it is preview or encoder draw:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/gl/render/ScreenRender.java#L80

This means that the real resolution should be encoder resolution and preview is only an encoder resolution scaled to fit preview

**Comment by troy-lamerton** [comment]
> This means that the real resolution should be encoder resolution and preview is only an encoder resolution scaled to fit preview

Ok understood. The goal is to render view at fullscreen resolution and draw into small sized encoder.

So maybe I can just swap the idea around:
The real resolution will be preview resolution and encoder resoluton would be preview scaled down to fit encoder.

I don't need to use filters, so maybe I can skip them since `ManagerRender.cameraRender` draws at preview resolution.
What to do at step 2?
1. draw the `cameraRender` into the preview surface
1. ???
1. draw the `screenRender` into encoder surface scaled to fit

**Comment by troy-lamerton** [comment]
fixed in fork
