### ISSUE TITLE
可以获取直播rtsp流的音视频数据 然后发送给服务器吗

### ISSUE THREAD

**Issue by wflian** [pedroSG94/rtmp-rtsp-stream-client-java#459]

**Comment by pedroSG94** [comment]
If you means re stream other stream see this example:
https://github.com/pedroSG94/AndroidReStreamer

**Comment by wflian** [comment]
form live  rtsp://192.168.1.167:554/recorder stream to rtp://117.28.165.190:8090

**Comment by wflian** [comment]
example ：Push LAN live address rtsp://192.168.1.167:554/recorder to server address rtp://117.28.165.190:8090

**Comment by pedroSG94** [comment]
You can do it with this:
https://github.com/pedroSG94/AndroidReStreamer
But rtp protocol is not supported only rtmp, rtmps, rtsp and rtsps.

**Comment by wflian** [comment]
OK！Thank you
