### ISSUE TITLE
java.lang.IllegalArgumentException: Make sure the SurfaceView or associated SurfaceHolder has a valid Surface

### ISSUE THREAD

**Issue by ssttll5** [pedroSG94/rtmp-rtsp-stream-client-java#463]
我在做RTMP推流的时候遇到了一个问题，使用vivo手机进行推流时，有时候会报错。
错误信息如下：
java.lang.IllegalArgumentException: Make sure the SurfaceView or associated SurfaceHolder has a valid Surface	
at android.opengl.EGL14._eglCreateWindowSurface(Native Method)	
at android.opengl.EGL14.eglCreateWindowSurface(EGL14.java:263)	
at com.pedro.encoder.input.gl.SurfaceManager.eglSetup(SurfaceManager.java:129)	
at com.pedro.encoder.input.gl.SurfaceManager.<init>(SurfaceManager.java:46)	
at com.pedro.rtplibrary.view.OpenGlView.run(OpenGlView.java:106)	
at java.lang.Thread.run(Thread.java:764)
我去查找egl的源码发现可能是surfaceView在传输过程中丢了。。  
在底层它判断surfaceView为空就会抛出这个异常，请问您有遇到过吗？如何解决？

**Comment by floriangbh** [comment]
I had the same issue but it's not really due to the library it's probably because you are accessing to the surfaceView before his initialization.

**Comment by ssttll5** [comment]
> I had the same issue but it's not really due to the library it's probably because you are accessing to the surfaceView before his initialization.

假设我在layout中加入一个<com.pedro.rtplibrary.view.OpenGlView ……>的布局，
那么其中报错的at com.pedro.rtplibrary.view.OpenGlView.run(OpenGlView.java:106)，也就是run()方法是在什么时候被执行的呢，是在findViewById(...)的时候吗？
我写的方法和example中的执行流程类似，初始化都是放在onCreate()方法中执行。
但有报这个IllegalArgumentException的目前就只有vivo，其他机型并没有发现这个错误，而且vivo手机也不是每次都会报错，有成功过。
接下来我会尝试使用现在最新的1.7.3版本来看下是否能够解决这个问题。

**Comment by pedroSG94** [comment]
Are you doing startPreview, startStream or startRecord after that surfaceChanged callback is called?
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/defaultexample/ExampleRtmpActivity.java#L202
If you are doing it, this could be a bug.
Did you get this error with multiple vivo devices or only one model? 
If you can let me know model and android API.
Since I can't reproduce your case. If you have a vivo and you can reproduce the error I will need you to test some things to help me debug it.

**Comment by ssttll5** [comment]
> Are you doing startPreview, startStream or startRecord after that surfaceChanged callback is called?
> https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/defaultexample/ExampleRtmpActivity.java#L202
> If you are doing it, this could be a bug.
> Did you get this error with multiple vivo devices or only one model?
> If you can let me know model and android API.
> Since I can't reproduce your case. If you have a vivo and you can reproduce the error I will need you to test some things to help me debug it.

1.这是我的onChange()方法。
    public void surfaceChanged(SurfaceHolder holder, int format, int width, int height) {
        if (holder == openGlView.getHolder()) {
            CameraHelper.getCameraOrientation(VideoActivity.this);
            rtmpCamera1.startPreview(CameraHelper.Facing.FRONT, 90);
        }
    } 
2.这个错误目前只发现了2台vivo手机有，其他vivo手机并没有。
  其中一台vivo手机的设备信息如下：
  型号：vivo X20A
  android版本：8.1.0
  android安全补丁程序级别：2019-10-01
  处理器：2.2GHz 骁龙660 八核
3.我并没有vivo手机，这些都是客户的手机，但是如果需要协助的步骤不是很复杂，我想应该可以让客户帮忙测试一下。

**Comment by pedroSG94** [comment]
This is pretty difficult for a client (I wanted modify library with somes logs and post logcat to debug it)
In this case, ask your client about steps to reproduce the fail and we can suppose which methods were called in app's life cycle to debug it.

**Comment by ssttll5** [comment]
> This is pretty difficult for a client (I wanted modify library with somes logs and post logcat to debug it).
> 
> In this case, ask your client about steps to reproduce the fail and we can suppose which methods were called in app's life cycle to debug it.

谢谢。但是可能要等到下周一再测试了。

**Comment by pedroSG94** [comment]
Post it when you can. For now, I will try find crash reason by myself.

**Comment by ssttll5** [comment]
> Post it when you can. For now, I will try find crash reason by myself.
> Also ask if this error is casual or library never work in this device.

并不是一定会发生，但是大多数情况下还是会抛出异常，正常的情况只是少数。
今天又发生了一起是oppo手机的，和vivo手机是同一个厂家。。

**Comment by ssttll5** [comment]
> Post it when you can. For now, I will try find crash reason by myself.
> Also ask if this error is casual or library never work in this device.

我们开发的是一个类似视频通话的软件。由app发出请求到服务器，服务器接收到请求后pc端建立通话，RTMP使用的是nging-rtmp-module，手机在推流的同时也会拉取pc端的画面。openGlView在右上角，显示本地的画面；当中的画面播放拉取到的RTMP流，使用的是IjkPlayer框架。
客户操作的时候，刚跳转到通话的Activity就抛出了异常，但由于客户不在身边，只能听他们描述，具体的情况也不能很是确定，只能通过捕获到的错误日志来猜测。

**Comment by pedroSG94** [comment]
Can you provide a code example of your Activity? You can share it via email if you don't want publish it here. pedrossgg1994@gmail.com
By this way, maybe I can find a logic for this problem.
