### ISSUE TITLE
file create,but cant play url with vlc

### ISSUE THREAD

**Issue by LauJJ** [pedroSG94/rtmp-rtsp-stream-client-java#467]
hi pedro~
i find that i use rtmp push stream to the server ,but i cant play the url "rtmp**" with vlc . i saw that file creates,and can open with vlc .
i use your demo and player test too ,but still not work

**Comment by pedroSG94** [comment]
Can you tell me media server used?
Also you should check that you receive stream in mediaserver (normally you have a monitor to check number of clients connected and a list of active streams) and you have access to it with VLC player device (check ports opens, proxy, etc).
You can use ffmpeg to replace my library for tests and discard server problems.
