### ISSUE TITLE
Proper release

### ISSUE THREAD

**Issue by OleksandrAndro** [pedroSG94/rtmp-rtsp-stream-client-java#468]
Hi!
Please, help with the problem:
I implemented your library in my project for streaming image from embed phone camera to server over RTMP, all works properly, but when I rotate the screen of phone in some device with API 21 occurring crash with message "failed to connect to camera service", in the emulator (Galaxy Nexus API 23) and real device Samsung with API28 I have error message "Camera: Error 2" without crash. Also in Samsung with API28 I have periodical error message:
 - "E/CameraService:    Conflicts with: Device 0, client package..."
Last error appears immediately after opening the camera and continues to be displayed in the logcat even after closing the Fragment with the camera.

This is the sequence of my actions:

1. Creating RtmpCamera1 in onActivityCreated method of myFragment:
if(rtmpCamera1 == null)
                rtmpCamera1 = new RtmpCamera1(surfaceView, this);

2. Start preview in surfaceChanged method:
if(rtmpCamera1 != null){
            rtmpCamera1.startPreview(CameraHelper.Facing.BACK);

3. Start stream to server by tap on button

 if (!rtmpCamera1.isStreaming()) {
                    if (rtmpCamera1.isRecording()
                            || rtmpCamera1.prepareAudio() && rtmpCamera1.prepareVideo()) {
                        //mBroadcastControlButton.setText("Stop stream");
                        rtmpCamera1.startStream(url);
                        //Toast.makeText(appContext, "Stream started", Toast.LENGTH_SHORT).show();
                    } else {
                        Toast.makeText(appContext, "Error preparing stream, This device cant do it",
                                Toast.LENGTH_SHORT).show();
                    }
                } else {
                    isStream = false;
                    mBroadcastControlButton.setText("Start stream");
                    rtmpCamera1.stopStream();
                }

That work fine....

And for avoiding stoping stream after change orientation, I do so:

1. In surfaceDestroyed method:

 if (rtmpCamera1 != null && rtmpCamera1.isStreaming()) {
            rtmpCamera1.stopStream();
            mBroadcastControlButton.setText("Start Record");
            rtmpCamera1.stopPreview();
        }

2. In onSaveInstanceState method I saving the variable isStream and restore it in onCreate method of my Fragment.
- isStream it is my boolean variable, I set it to true in onConnectionSuccessRtmp() method and set it to false when stoping stream manualy by tap on button.

3. In surfaceChanged method I checking variable isStream and is "true" - restore stream

if (isStream && !rtmpCamera1.isStreaming()) {
                if (rtmpCamera1.prepareAudio() && rtmpCamera1.prepareVideo()) {
                    mBroadcastControlButton.setText("Stop stream");
                    rtmpCamera1.startStream(url);
                    //Toast.makeText(appContext, "Stream started", Toast.LENGTH_SHORT).show();
                } else {
                    Toast.makeText(appContext, "Error preparing stream, This device cant do it",
                            Toast.LENGTH_SHORT).show();
                }
            }

Please, correct me where am i wrong.

**Comment by pedroSG94** [comment]
You can't avoid stop stream if you rotate your view because you are destroying view used for stream also you need stop camera and video encoder if you want rotate it.
For this reason you should block activity orientation while you are streaming or recording (This is the most common use in all camera apps like in a default camera app).

**Comment by OleksandrAndro** [comment]
I stoping stream, closing camera in surfaceDestroyed method and after change orientation try open camera and start stream, but seems to camera not closing before change orientation.

**Comment by pedroSG94** [comment]
replace your code on surfaceDestroyed to:
```java

  @Override
  public void surfaceDestroyed(SurfaceHolder surfaceHolder) {
     if (rtmpCamera1.isStreaming()) rtmpCamera1.stopStream();
     if (rtmpCamera1.isRecording()) rtmpCamera1.stopRecord();
     if (rtmpCamera1.isOnPreview()) rtmpCamera1.stopPreview();
  }
```

**Comment by OleksandrAndro** [comment]
Thank you its work fine!

**Comment by minmax9493** [comment]
@OleksandrAndro If you want to support landscape mode, just lock orientation to Portrait in android Manifest file. Then you can make fake landscape with ui. However, you're not able to change from portrait to landscape while streaming is going on. To stream in landscape mode, restart streaming. Hope it'll help to you.
