### ISSUE TITLE
about the problem of echo

### ISSUE THREAD

**Issue by ssttll5** [pedroSG94/rtmp-rtsp-stream-client-java#469]
在使用RTMP流和PC视频通话的时候，PC说一句话，android可以听到，但是android在推流的时候会把PC的声音再传回去，导致PC会听到自己说话的声音。请问有什么解决方法吗？

**Comment by pedroSG94** [comment]
Try enable echoCanceler:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L222
Also you can try modify audio source:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/c3d1e38be65843d4936728b3777868369ab55021/encoder/src/main/java/com/pedro/encoder/input/audio/MicrophoneManager.java#L56
To:
```java
MediaRecorder.AudioSource.VOICE_COMMUNICATION
```
or:
```java
MediaRecorder.AudioSource.VOICE_CALL
```

**Comment by ssttll5** [comment]
> Try enable echoCanceler:
> https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L222
> Also you can try modify audio source of microphone:
> https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/c3d1e38be65843d4936728b3777868369ab55021/encoder/src/main/java/com/pedro/encoder/input/audio/MicrophoneManager.java#L56
> 
> 
> To:
> ```java
> MediaRecorder.AudioSource.VOICE_COMMUNICATION
> ```
> 
> or:
> 
> ```java
> MediaRecorder.AudioSource.VOICE_CALL
> ```

上面2个试了没有效果
第三个VOICE_CALL使用了之后报错：
java.lang.IllegalStateException: startRecording() called on an uninitialized AudioRecord.
        at android.media.AudioRecord.startRecording(AudioRecord.java:993)
        at com.pedro.encoder.input.audio.MicrophoneManager.init(MicrophoneManager.java:95)
        at com.pedro.encoder.input.audio.MicrophoneManager.start(MicrophoneManager.java:74)
        at com.pedro.rtplibrary.base.Camera2Base.startEncoders(Camera2Base.java:420)
        at com.pedro.rtplibrary.base.Camera2Base.startStream(Camera2Base.java:408)

**Comment by Ha2ryZhang** [comment]
最后怎么解决的 好像得播放端AudioTrack 也需要传入audioSessionId
