### ISSUE TITLE
Rtmp live streaming from 2 different source

### ISSUE THREAD

**Issue by akktis** [pedroSG94/rtmp-rtsp-stream-client-java#473]
Hello guys,

I'm trying to send video and audio from 2 different source to rtmp.

Video : i have hdmi input (for now i'm able to getting the bytes and to send it with ffmpeg with parcelFileDescriptor.createPipe, and is working)
Audio : i have mic, and i can record as standard microphone

but now i have to mux audio and video, the pb is ffmpeg support only one pipe,

so i checked for some other way than calling the binary of ffmpeg

so as i checked in your lib by default is not possible to use like how i want, but check a bit the code and 2 way seems to be good choice

1/ stream Surface + audio from MediaRecorder(or someting like this)
2/ Direclty send the bytes of video to srsFlvMuxer.sendVideo  + audio from MediaRecorder(or someting like this)

could you please tell me if one solution is possible (or both), for now i'm trying to do the 1st solution but ( the rtmp connection is done, but nothing is send, cause i think i didn't know exactly how to send the video from VideoEncoder to srsFlvMuxer)

Best

**Comment by pedroSG94** [comment]
Both is possible but in the first you can't get audio from MediaRecorder you need do it from AudioRecorder like in my library.
I recommend you try this way replacing cameraManager to a custom class but with your hdmi source. You can do it with nv21 byte array or with surface as you want:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java

In the second case you need create H264 video buffer and AAC audio buffer (this last from AudioRecord for example) and send it to SrsFlvMuxer.
For tis implementation you need know that "MediaCodec.BufferInfo info" is only a class that could be set with a empty instance of it with modify timestamp with the current timestamp of your buffer like here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L464

**Comment by akktis** [comment]
Thanks you very much for your anwser, 

I understood some important thing with your message,  and first of all i will need to know exactly which color are sent from the hdmi input, the main problem is realtek didn't provide any datasheet :S, so btw i record the hdmi input and i check the media info  then i got this result

Color space :
YUV
Chroma subsampling :
4:2:0
Chroma subsampling :
4:2:0
Bit depth :
8
Bit depth :
8 bits


which seems good according to wikipedia : https://en.wikipedia.org/wiki/YUV#Y%E2%80%B2UV420sp_(NV21)_to_RGB_conversion_(Android)

but i'm not sure at 100% but i will continue to dive into this to know that important information.
