### ISSUE TITLE
Video in dark light

### ISSUE THREAD

**Issue by mynew-github-account** [pedroSG94/rtmp-rtsp-stream-client-java#474]
Hi,
While using library if we try to stream in dark light or at night video quality is very very bad as compared to if we capture video with default camera 

Can you tell me the reason ?

Look at the result 
Below one is taken from library 
![Screenshot_20191230-144520](https://user-images.githubusercontent.com/41420619/71575508-3910d980-2b13-11ea-8737-055aaa56f60a.png)

Below one is from default camera
![Screenshot_20191230-144530](https://user-images.githubusercontent.com/41420619/71575542-5776d500-2b13-11ea-961a-01959fd78156.png)

**Comment by pedroSG94** [comment]
This is camera configuration.
Maybe you are using night mode or you have lantern enabled.
Other reason could be that setPreviewFps is not working fine in your device:
https://stackoverflow.com/questions/26967490/android-camera-preview-is-dark
You can delete this line to test:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java#L144
I recommend you play with camera configuration in this method and adapt it to your case:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java#L128
