### ISSUE TITLE
The problem with avsync

### ISSUE THREAD

**Issue by namndev** [pedroSG94/rtmp-rtsp-stream-client-java#475]
Hi @pedroSG94.
I implement '1.7.4' and have a problem with the audio is slower than video.
I think to have a problem with avsync, How to resolve it?

**Comment by pedroSG94** [comment]
Hi, can you give me more info?
RTMP or RTSP? 
What server and player are you using?
Can you try with a server of this [list](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Media-servers-tested) and VLC to discard it?
Do you get this error after several minutes streaming or when you start it? 
Did you try with other device?

**Comment by namndev** [comment]
Hi, 
I use rtmp to connect into my server (nginx-rtmp-module).
And I play with any player ( from exoplay to browser)
However, I will try with other cases.
Thanks,
