### ISSUE TITLE
UVC camera RTMP Streaming issue

### ISSUE THREAD

**Issue by PayalPatel28** [pedroSG94/rtmp-rtsp-stream-client-java#477]
Hello, 
Can you please help me to stream USB camera attached to the android device.
I have used https://github.com/saki4510t/UVCCamera library to preview USB camera o/p to the texture view.
I have used RtmpCamera2 for RTMP streaming.
Is it necessary to call startpreview() of RtmpCamera2 class bcoz I am already calling startPreview() from UVCCamera library.
Can you please help me out what changes are need to make as of now only audio packets are sent and FYI sendvideo() is not called.

**Comment by pedroSG94** [comment]
This issue is related with your problem:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/434

**Comment by PayalPatel28** [comment]
Hello,
I have referred above issue and tried to follow given steps still I am not able to reach to the output. Can you please help from where I am going wrong. 
I have follwed below steps : 

- created object of SrsFlvMuxer in my activity
- on the button click of start stream I have written mSrsFlvMuxer.start(URL)
- on the callback of IFrameCallback  I have written mSrsFlvMuxer.sendVideo(byteBufferObj,new BufferInfo())


Here is my logs : 
I/SrsFlvMuxer: worker: connecting to RTMP server by url=rtmp://192.168.4.15/LiveApp/582636318947891687528440
D/RtmpConnection: connect() called. Host: 192.168.4.15, port: 1935, appName: LiveApp, publishPath: 582636318947891687528440
D/RtmpConnection: connect(): socket connection established, doing handhake...
D/Handshake: writeC0
D/Handshake: writeC1
D/Handshake: writeC1(): Calculating digest offset
D/Handshake: writeC1(): (real value of) digestOffset: 210
D/Handshake: writeC1(): recalculated digestOffset: 986
D/Handshake: writeC1(): digestOffsetBytes: 000000D2
D/Handshake: partBeforeDigest(): size: 986
D/Handshake: writeC1(): Writing timestamp and Flash Player version
D/Handshake: partAfterDigest(): size: 518
D/Handshake: copying digest offset bytes in partBeforeDigest
D/Handshake: writeC1(): Calculating digest
D/Handshake: writeC1(): writing C1 packet
D/Handshake: readS0
D/Handshake: readS1
D/Handshake: readS1(): S1 total bytes read OK
D/Handshake: writeC2
D/Handshake: readS2
D/Handshake: readS2(): S2 total bytes read OK
D/RtmpConnection: connect(): handshake done
D/RtmpConnection: rtmpConnect(): Building 'connect' invoke packet
D/RtmpConnection: starting main rx handler loop
D/RtmpConnection: wrote packet: RTMP Command (command: connect, transaction ID: 1), size: 272
D/RtmpConnection: handleRxPacketLoop(): Setting acknowledgement window size: 10000000
D/RtmpConnection: handleRxPacketLoop(): Send acknowledgement window size: 10000000
D/RtmpConnection: wrote packet: RTMP Window Acknowledgment Size, size: 4
I/RtmpConnection: handleRxInvoke: Got result for invoked method: connect
D/RtmpConnection: createStream(): Sending releaseStream command...
D/RtmpConnection: wrote packet: RTMP Command (command: releaseStream, transaction ID: 2), size: 53
D/RtmpConnection: createStream(): Sending FCPublish command...
D/RtmpConnection: wrote packet: RTMP Command (command: FCPublish, transaction ID: 3), size: 49
D/RtmpConnection: createStream(): Sending createStream command...
D/RtmpConnection: wrote packet: RTMP Command (command: createStream, transaction ID: 4), size: 25
I/RtmpConnection: handleRxInvoke: Got result for invoked method: releaseStream
D/RtmpConnection: handleRxInvoke(): 'releaseStream'
I/RtmpConnection: handleRxInvoke: Got result for invoked method: FCPublish
D/RtmpConnection: handleRxInvoke(): 'FCPublish'
I/RtmpConnection: handleRxInvoke: Got result for invoked method: createStream
D/RtmpConnection: handleRxInvoke(): Stream ID to publish: 1
D/RtmpConnection: fmlePublish(): Sending publish command...
D/RtmpConnection: wrote packet: RTMP Command (command: publish, transaction ID: 0), size: 54
D/RtmpConnection: handleRxInvoke(): onStatus NetStream.Publish.Start
D/RtmpConnection: onMetaData(): Sending empty onMetaData...
D/RtmpConnection: wrote packet: com.github.faucamp.simplertmp.packets.Data@b5ed9b8, size: 238
I/libUVCCamera: [11717*UVCPreview.cpp:281:callbackPixelFormatChanged]:PIXEL_FORMAT_NV21:
D/InputTransport: Input channel constructed: fd=100
D/ViewRootImpl@f7e6882[Toast]: setView = android.widget.LinearLayout{3364b93 V.E...... ......I. 0,0-0,0} TM=true MM=false
V/Toast: Text: Donn in android.widget.Toast$TN@fd727d0
D/ViewRootImpl@f7e6882[Toast]: dispatchAttachedToWindow
V/Surface: sf_framedrop debug : 0x4f4c, game : false, logging : 0
D/ViewRootImpl@f7e6882[Toast]: Relayout returned: old=[0,0][0,0] new=[467,1758][733,1824] result=0x7 surface={valid=true 3435343872} changed=true
W/libUVCCamera: [12137*UVCPreview.cpp:119:get_frame]:allocate new frame
D/ViewRootImpl@f7e6882[Toast]: MSG_RESIZED_REPORT: frame=Rect(467, 1758 - 733, 1824) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
I/MediaCodec: setCodecState state : 0
I/SrsFlvMuxer: Skipping iteration, frame null
I/SrsFlvMuxer: Skipping iteration, frame null
D/ViewRootImpl@f7e6882[Toast]: dispatchDetachedFromWindow
D/InputEventReceiver: channel '130b42a Toast (client)' ~ Disposing input event receiver.
D/InputEventReceiver: channel '130b42a Toast (client)' ~NativeInputEventReceiver.
D/InputTransport: Input channel destroyed: fd=100
D/RtmpConnection: handleRxPacketLoop(): Sending PONG reply..
D/RtmpConnection: wrote packet: RTMP User Control (type: PONG_REPLY, event data: [I@79d83c9), size: 6
I/SrsFlvMuxer: Skipping iteration, frame null
I/SrsFlvMuxer: Skipping iteration, frame null
D/RtmpConnection: handleRxPacketLoop(): Sending PONG reply..
D/RtmpConnection: wrote packet: RTMP User Control (type: PONG_REPLY, event data: [I@2ae8ace), size: 6
I/SrsFlvMuxer: Skipping iteration, frame null
I/SrsFlvMuxer: Skipping iteration, frame null
D/RtmpConnection: handleRxPacketLoop(): Sending PONG reply..
D/RtmpConnection: wrote packet: RTMP User Control (type: PONG_REPLY, event data: [I@bf00def), size: 6
D/ViewRootImpl@60209c8[DashboardActivityNew]: ViewPostIme pointer 0
I/SrsFlvMuxer: Skipping iteration, frame null
D/ViewRootImpl@60209c8[DashboardActivityNew]: ViewPostIme pointer 1
I/SrsFlvMuxer: SrsFlvMuxer closed
D/RtmpConnection: closeStream(): setting current stream ID to 0
D/RtmpConnection: wrote packet: RTMP Command (command: closeStream, transaction ID: 0), size: 24
D/RtmpConnection: socket closed
I/SrsFlvMuxer: worker: disconnect ok.

**Comment by pedroSG94** [comment]
I uploaded an old project for it. I'm not sure if it is working, but you can try with it:
https://github.com/pedroSG94/Stream-USB-test

**Comment by PayalPatel28** [comment]
@pedroSG94 Thank you so much for the help, it works for me.
