### ISSUE TITLE
The data in ByteBuffer is H.264 format?

### ISSUE THREAD

**Issue by zhaiduo** [pedroSG94/rtmp-rtsp-stream-client-java#478]
I try to push H264 data to server, but get wrong data. It seems the wrong length. But if I save bytebuffer to local file in android, I can play the H264 video.

So My question is the return size from getBuffsize is not the length of H264 data?

Somebody can help me?

**Comment by pedroSG94** [comment]
Where are you using getBuffSize?
The h264 (raw) size is here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L743
with this method:
```java
h264Buffer.remaining();
```

**Comment by zhaiduo** [comment]
@pedroSG94  I customized Frame class, set buffer to Frame from H264Packet. 
Already use remaining() to get H264 Data. 
I found the H264 data is Annex B. Could it possible to change to AVCC?

**Comment by pedroSG94** [comment]
You can do it but you need change header manually. I don't know about avcc format but this post could help you:
https://stackoverflow.com/questions/23404403/need-to-convert-h264-stream-from-annex-b-format-to-avcc-format

**Comment by zhaiduo** [comment]
@pedroSG94 Thanks a lot!
