### ISSUE TITLE
Crashing app when incorrect rtmp link

### ISSUE THREAD

**Issue by OleksandrAndro** [pedroSG94/rtmp-rtsp-stream-client-java#479]
Hello!
There is issue in case using RTMPCamera2, when I receive: onStatus NetConnection.Connect.Rejected - app is crashing with error:
Attempt to invoke virtual method 'int com.github.faucamp.simplertmp.amf.AmfType.ordinal()' on a null object reference
This is logcat:
01-10 15:10:27.745 10683-10828/com.serenegiant.usbcameratest4:uvcservice2 D/RtmpConnection: fmlePublish(): Sending publish command...
01-10 15:10:27.752 10683-10828/com.serenegiant.usbcameratest4:uvcservice2 D/RtmpConnection: handleRxInvoke(): onStatus NetConnection.Connect.Rejected
    
    --------- beginning of crash
01-10 15:10:27.753 10683-10828/com.serenegiant.usbcameratest4:uvcservice2 E/AndroidRuntime: FATAL EXCEPTION: Thread-789
    Process: com.serenegiant.usbcameratest4:uvcservice2, PID: 10683
    java.lang.NullPointerException: Attempt to invoke virtual method 'int com.github.faucamp.simplertmp.amf.AmfType.ordinal()' on a null object reference
        at com.github.faucamp.simplertmp.amf.AmfDecoder.readFrom(AmfDecoder.java:17)
        at com.github.faucamp.simplertmp.packets.VariableBodyRtmpPacket.readVariableData(VariableBodyRtmpPacket.java:62)
        at com.github.faucamp.simplertmp.packets.Command.readBody(Command.java:69)
        at com.github.faucamp.simplertmp.io.RtmpDecoder.readPacket(RtmpDecoder.java:93)
        at com.github.faucamp.simplertmp.io.RtmpConnection.handleRxPacketLoop(RtmpConnection.java:527)
        at com.github.faucamp.simplertmp.io.RtmpConnection.access$000(RtmpConnection.java:44)
        at com.github.faucamp.simplertmp.io.RtmpConnection$1.run(RtmpConnection.java:160)
        at java.lang.Thread.run(Thread.java:818)
01-10 15:10:27.780 463-486/system_process D/WindowManagerService: Window{292b0fd3 u0 Application Error: com.serenegiant.usbcameratest4}  ==========setInputFocusLw ==========  =======
01-10 15:10:27.853 10683-10824/com.serenegiant.usbcameratest4:uvcservice2 D/RtmpConnection: socket closed
01-10 15:10:27.853 10683-10824/com.serenegiant.usbcameratest4:uvcservice2 D/CameraServer: onConnectionFailedRtmp camera 2
01-10 15:10:27.853 10683-10824/com.serenegiant.usbcameratest4:uvcservice2 D/CameraServer: camera 2 Connection failed. 
In the demo SurfaceModeRtmpActivity such issue present too.

**Comment by pedroSG94** [comment]
Can you share link example and crash logcat?

**Comment by OleksandrAndro** [comment]
rtmp://mydomain.com.ua:myport/myapp-mb/1578734206&t=1f48b00db60695cefb7fc6bc1e389f66&c=&m=3d895c0e465d746786f27fae467c48b8

**Comment by pedroSG94** [comment]
Fixed here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/ea18a328cfbbaf77d6241a87b2a4d46962450da4

**Comment by OleksandrAndro** [comment]
Thank's, I tried it, working fine.
