### ISSUE TITLE
Rtmp streaming is not working on Pixel 3  with android Q

### ISSUE THREAD

**Issue by minmax9493** [pedroSG94/rtmp-rtsp-stream-client-java#486]
Thanks for great library. 
Rtmp streaming on Android Q is not working, It's not showing any errors and exceptions, but the video is not streamed. I've set resolution to 1920x1440 by settings, it worked, however, it did not work with other resolution on Pixel 3(Android Q).
If anyone has faced the same issue, please help me to resolve it, Thanks.

**Comment by marinesco** [comment]
Huh, not so much info actually

- Which mode do you use? Or it doesn't work in any mode?
- In 1920x1440 it works ok, right? How do you select any other resolution?

May be this could be helpful you: #485

**Comment by minmax9493** [comment]
Sorry for replying late. I've selected Custom Rtmp with camera api 1. Yes, working resolution has been set manually, but streaming is not stable. I have also tried #485 issue, but I don't have service. Please, help me if there's some update.

**Comment by marinesco** [comment]
Try with other resolutions, it seems that 1920x1440 is not "standard" resolution
Try something from these:
- 1280x720
- 1920x1080
- 2560x1440

**Comment by minmax9493** [comment]
@marinesco , I've tried all resolutions, may be it's not about resolution. Streaming was working, before upgrading Pixel 3 from 9 to 10.

**Comment by pedroSG94** [comment]
What do you means with stable? Crash, FPS?
I'm updating display example to support android 10. This should be finished today or tomorrow.
