### ISSUE TITLE
camera2base.switchCamera() not working in Service

### ISSUE THREAD

**Issue by GGPENG** [pedroSG94/rtmp-rtsp-stream-client-java#487]
Hi, 

I'm trying to stream front camera from RtpService.
When I call switchCamera() before start streaming, it keeps streaming back camera. 
Is it possible to stream front camera with RtpService?

**Comment by pedroSG94** [comment]
Yes, you can. Replace:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera2Base.java#L437
To:
```java
cameraManager.openCameraFront();
```
And:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java#L192To:
```java
openCameraFront();
```
