### ISSUE TITLE
VideoStreaming with RtmpDisplay works only with small resolution

### ISSUE THREAD

**Issue by DoPinG83** [pedroSG94/rtmp-rtsp-stream-client-java#493]
Hello. I use your RtmpDisplay solution as plugin for my Unity3D application to stream my game view, cameraView and microphone. It works fine with 320x240 streaming resolution and I can receive streaming video and audio result with my vlc-player for example. But if I change streaming resolution to 640x480 then on my vlc-player I receive only first several seconds of streaming video and audio and after that video stops and I receive only audio from microphone. I tried three different rtmp-servers with same result. How can I fix this? Does this depends of FPS of my Unity game? Thanks.

**Comment by DoPinG83** [comment]
Btw, If I change to RtspDisplay video and audio streaming works fine with any resolution. Maybe that matters for any answer...

**Comment by pedroSG94** [comment]
Can you check if video packets stop send in device log when you use rtmp?
If you can try this:
- Force software video encoder to discard rtmp module bug with your encoder (add this line after create RtmpDisplay class):
```java
rtmpDisplay.setForce(CodecUtil.Force.SOFTWARE, CodecUtil.Force.FIRST_COMPATIBLE_FOUND);
```
If this solve your problem let me know device model, API and encoder used that fail for you.

Maybe de error is that your encoder create a bad header after some seconds in high resolution. In rtsp module I'm not doing h264 header check and this could be the problem.

**Comment by DoPinG83** [comment]
@pedroSG94 Thanks for the answer. Force software video encode doesn't solve my problem.
Video packets doesn't stop send in both cases.

**Comment by pedroSG94** [comment]
Which server and player are you using?
Can you try change both to discard problems with that side?

**Comment by DoPinG83** [comment]
Tried node-rtsp-rtmp-server from wiki. Same result: Rtsp works great, Rtmp stops showing video after several seconds on standard vlc application.

**Comment by DoPinG83** [comment]
Changed player to Live Stream Player, connected to node-rtsp-rtmp-server and Rtmp started working normal. Strange that VLC player have such problems

**Comment by popisdead** [comment]
Is this closed now? @DoPinG83 we are building a plugin too for unity3d. How was your overall experience?
