### ISSUE TITLE
rtmpDisplay audio stops when there is break in between

### ISSUE THREAD

**Issue by vinny3273** [pedroSG94/rtmp-rtsp-stream-client-java#494]
Hi, i have an issue related to rtmp display . if i have a continuous stream of audio and video it works but if somehow audio is not there for even if  2-3 seconds or muted . and then unmuted . next time i doesn't hear audio . i have to end stream and restart it which fix the issue

**Comment by pedroSG94** [comment]
I was doing tests but this is working fine for me. Can you share any code about your audio configuration? Are you using internal audio?

I only added a button to this [class](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/displayexample/DisplayActivity.java) with this code:
```java
if (DisplayService.Companion.isMuted()) {
    DisplayService.Companion.unmute();
} else {
    DisplayService.Companion.mute();
}
```

**Comment by vinny3273** [comment]
im working with version https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/releases/tag/1.7.3 
also , can i have system audio as well as mic audio ? 
thanks,
