### ISSUE TITLE
Screen, can flv push?

### ISSUE THREAD

**Issue by icewst** [pedroSG94/rtmp-rtsp-stream-client-java#495]

**Comment by pedroSG94** [comment]
raw flv push is not available. You only can send flv packets with rtmp protocol using this library. Maybe you can replace this class with your flv server negotiation:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java
