### ISSUE TITLE
Prevent freezing when recording in background

### ISSUE THREAD

**Issue by GGPENG** [pedroSG94/rtmp-rtsp-stream-client-java#496]
Hi folks!

My application is recording in the background using a foreground service. But when other apps that uses camera API comes to foreground, the recorded video frame freezes and log register cameraAccessException: CAMERA_DISCONNECTED (2).
It unfreezes when APP comes to foreground and recreates the surfaceView.

Similar behavior can be tested using the **example RTP Service**. If you open Camera APP, it freezes the streaming. When the example application comes to foreground, the stream unfreezes. 

I'm seeking a solution that prevents video from freezing when the camera is requested by another app or a way to automatic unfreeze the frame from foreground service/RTP example service.

**Comment by pedroSG94** [comment]
This is not possible. Camera hardware only can be used by an app at same time (Android limitation). You have same problem with microphone.

**Comment by GGPENG** [comment]
Thanks @pedroSG94. 

I'm wondering if I can retake the camera control from foreground service.
I can do it calling setPreview when app comes to foreground, but didn't find a way to do it from background.

**Comment by pedroSG94** [comment]
No, because you can't detect when camera is closed by other app.

You can open camera every 5 second, for example, to do it (if it fails, it is in use if it is not free) but I think, that this could block your camera and force that user need reset device to unblock camera if you have a bug in the code. I don't like this way.

**Comment by GGPENG** [comment]
On RTP Service, for example, how could I open camera from service?
