### ISSUE TITLE
Want to stream screen display with camera stream as an overlay.

### ISSUE THREAD

**Issue by ulohani90** [pedroSG94/rtmp-rtsp-stream-client-java#497]
Hi. I am using this library for streaming screen onto my rtmp server and it seems to work perfectly fine.
Now what I want to achieve is that while streaming screen recording, I also want my Camera streamed as an overlay on to the screen display stream.

One way would be to place a camera surface onto the top of the screen and then stream the whole screen display onto my rtmp server. But this will place a camera surface on the screen so it will hinder the users interaction with whatever app he/she is using.

How I am thinking of trying to achieve this - 
I would take frames from both the screen display stream and camera stream and create a canvas with the screen display frame at the bottom and camera frame on the top of it as an overlay. Then from this canvas I can take a bitmap and make a frame and then simply send it to the stream.

I am not able to figure out as to how can I get the frames from both the individual stream. 

Please help me with the same. 
In case you have a different idea as to how I can proceed that would also be a great help.

Any help here would be appreciated.

**Comment by pedroSG94** [comment]
You have a way to do it with my library without modify anything.
You can use display mode with opengl and add a SurfaceFilter to it. In this filter you can render a surface with camera api.
Opengl display constructor (use bollean = true):
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/DisplayBase.java#L63
SurfaceFilter example:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L258
You can replace MediaPlayer with [camera1](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java) or [camera2](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java) manager

**Comment by ulohani90** [comment]
Thanks for the prompt reply. I tried achieving this but I am facing an issue with creating a SurfaceFilter. The SurfaceFilter surface is null every time.

Even in the above given SurfaceFilter example, the SurfaceFilter's surface is null hence MediaPlayer doesn't play any media. It shows a black screen. Not sure if the issue is somewhere with the SurfaceFilterRender class

**Comment by pedroSG94** [comment]
Remember use it after start stream and maybe you need add a post delay before start camera render (also try without post delay). Try this code:
```java
  //Create filter
    final SurfaceFilterRender surfaceFilterRender = new SurfaceFilterRender();
    //Add filter to stream, in the next stream frame surface will be created automatically
    rtmpCamera1.getGlInterface().setFilter(surfaceFilterRender);
    //Render SurfaceFilter surface with camera data, maybe you need add a post delay for it.
    new Handler().postDelayed(new Runnable() {
      @Override
      public void run() {
        Camera1ApiManager camera1ApiManager =
            new Camera1ApiManager(surfaceFilterRender.getSurfaceTexture(), getApplicationContext());
        camera1ApiManager.start(CameraHelper.Facing.BACK, 640, 480, 30);
      }
    }, 1000);
```
If post delay solve your problem let me know it and I will try fix it.

**Comment by ulohani90** [comment]
Yes adding a delay did the job for me. I had to increase the delay and it worked. If we can get some kind of callback when we can do the runnable job i guess that would fix the time dependency over here.

**Comment by pedroSG94** [comment]
Ok, I will fix it.

**Comment by pedroSG94** [comment]
Fixed here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/da25c243f79e310f774d8ffcd9a56a8ecdb83a09
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/65505918c827591716650a8be97daf89df707399

Try with this gradle if you are using it:
```xml
implementation 'com.github.pedroSG94:rtmp-rtsp-stream-client-java:65505918c8'
```
