### ISSUE TITLE
Correct way to handle rotation?

### ISSUE THREAD

**Issue by DaveMurchison83** [pedroSG94/rtmp-rtsp-stream-client-java#499]
First of all, thank you for a wonderful library. This is so much easier to use than others I've tried!

This is more of a question than an issue... what is the best way to handle device rotation? I have my activity fixed to Portrait in the manifest. If I physically rotate my device to landscape then tap to start streaming, my output stream is rotated 90 degrees clockwise.

**Comment by pedroSG94** [comment]
Hi,
The best way to get a correct rotation is use this method:
```java
CameraHelper.getCameraOrientation(context);
```
If you block activity to portrait and you rotate to landscape your case is normal. You should unblock activity and block it when you press start stream or record to get correct orientation. After that, stream result rotation is the same that if you record a video with default camera app. I recommend you emulate camera app case.

**Comment by wklimczyk** [comment]
@pedroSG94 
Is it possible to change the output resolution during the stream? 
I got AWS configuration on server side that consumes only resolution:maxWidth: 1920 maxHeight: 1080. So In portrait I'd have to get 1080x1080 and landscape 1920x1080.
Or somehow to restart stream in short time to change the output resolution?

Thank you for feedback.

**Comment by pedroSG94** [comment]
No, you can't. RTMP can't do it you need reset stream to do it because you send stream resolution when you negotiate with server to accept stream.
Normally server do this work. For example if you push a stream in YouTube with 1080p. YouTube server resize it to 720p, 480p, etc in runtime for this reason you have multiple resolutions to get.
