### ISSUE TITLE
Facebook RTMP handshake s0 no answer

### ISSUE THREAD

**Issue by mentor971** [pedroSG94/rtmp-rtsp-stream-client-java#50]
Hi PedroSG94,

I'm trying to connect to facebook live RTMP via the "defaultexample". For some reason the readS0 property in the Handshake class doesn't read anything from the inputstream at the row 49 => "byte s0 = (byte) in.read();" 
It stay stuck on that line, and according to the answer here, looks like I'm not getting any response from the socket : https://stackoverflow.com/questions/9129381/java-stuck-when-reading-from-inputstream
But from what I can see in debug, the "isConnected" socket attribute have the value "true".

Any idea how to solve this ?

Thanks

**Comment by pedroSG94** [comment]
Facebook is woking for me. I tried from this url:
https://www.facebook.com/live/create?step=landing

Are you sure that your endpoint is correct?
You should write urlserver + transmision key like:
rtmp://live-api-a.facebook.com:80/rtmp/1959096080971663?ds=1&s_l=1&a=AThD15qWbqO6Tc-3

If you start stream should see a preview and you can start it.

**Comment by mentor971** [comment]
Hey pedro - Thanks for you answer.

The end point is correct. From what I can see for facebook it's working only when the phone is on wifi (even not working on 4G+ network). For Youtube it's working on wifi and 4G without any issue.

The Handshake method is invoked from here : https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L144

and stay stuck on the readS0 command : https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L99

specificly here : https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/github/faucamp/simplertmp/packets/Handshake.java#L49

We should get from the inputstream 0x03 at that point (works with facebook only on wifi) but the inputstream buffer stays fully empty so we stay here indefinitly. 

Is it working for you without wifi ?

Let me know if you need more details.

Thanks in advance

**Comment by pedroSG94** [comment]
I always test with wifi. I will test with 4G and tell you (today or tomorrow). If it work you can considerate that your company block some port or ip.

**Comment by mentor971** [comment]
Hi Pedro - Did you had a chance to try without the wifi connection ?

**Comment by pedroSG94** [comment]
I did a test without log and not working. Maybe same error, I will test more to find the error but this is rare should do the same :(.

**Comment by mentor971** [comment]
I just found this : https://github.com/shogo4405/HaishinKit.swift/issues/83

Do you have an example to connect via RTMPS ? Maybe that will work

**Comment by pedroSG94** [comment]
I haven't an example. I can try create a sslsocket and test but I don't know if it will work.

**Comment by pedroSG94** [comment]
rtmps added. Facebook is working over 4g with rtmps: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/eddd475f64e0778aad290e6ca520fae2702d068a
issue closed.
