### ISSUE TITLE
Not handling unimplemented/unknown packet of type: ACKNOWLEDGEMENT

### ISSUE THREAD

**Issue by alexeyvasilyev** [pedroSG94/rtmp-rtsp-stream-client-java#502]
When streaming to Twitch.tv getting the following error:

`RtmpConnection: handleRxPacketLoop(): Not handling unimplemented/unknown packet of type: ACKNOWLEDGEMENT`

It looks like that this causes connection close from Twitch.tv side.

**Comment by pedroSG94** [comment]
This is only a log but connection is not closed for this reason:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L584

When I close connection. OnCOnnectionFailed callback is called like here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L592
Twitch.tv is working for me. 
Can you share a full logcat of your device when you lose connection? 
Also try with other server. I use Madrid server: rtmp://live-mad.twitch.tv/app/{stream_key}

https://stream.twitch.tv/ingests/
