### ISSUE TITLE
Connection Failed; Failed to Connect; Time Out

### ISSUE THREAD

**Issue by Nosscc** [pedroSG94/rtmp-rtsp-stream-client-java#503]
Hi I've downloaded latest pack, compiled with no error, and tried OpenGI RTMP, Custom RTMP and Default RMPT, they don't seem to connect to my typed URL, a few seconds after pressing "start stream" I got following errors:
 
"Connection failed. Failed to Connect. Time out" for OpenGI and "retry" for Default mode

The same end point URL is working for other RTMP projects I tested, and is in the following format:

rtmp://xxxx.channel.media.azure.net:1935/live/xxxx/stream1

What could be the issue here?

**Comment by pedroSG94** [comment]
I never tried with Azure server but your error seems that server never response to my library.

First of all, test that you have access to the server in that device. For example, you can open your server admin panel from device browser.
If you can, share me a full log of your device when you press start stream and let me know a name of a project that is working for you to debug your case.
