### ISSUE TITLE
Sample SurfaceModeRTMP is not working in Pixel 3(Android 10) on AVD

### ISSUE THREAD

**Issue by baikdohyup** [pedroSG94/rtmp-rtsp-stream-client-java#508]
After log message "annexb not match", 
app start wrote packet but in twitch the video does not printed.

sorry for my low english skill

**Comment by pedroSG94** [comment]
Can you see video packets in logcat?
Can you tell me AVD configuration? (API, architecture, etc)

**Comment by luarropa** [comment]
Hi @pedroSG94, i'm having the same issue with my Pixel 3XL "SrsFlvMuxer: annexb not match.". The audio works fine. The video doesn't work.

Packets in logcat:
<img width="523" alt="Screen Shot 2020-05-15 at 3 09 20 PM" src="https://user-images.githubusercontent.com/18237562/82087453-2102b680-96be-11ea-8d4a-0fbdb578fa1b.png">

I'm using API 29

**Comment by pedroSG94** [comment]
Lets check if you have a problem with videoEncoder. Try force software encoder.
Before prepareVideo use this:
```java
rtmpCamera1.setForce(CodecUtil.Force.SOFTWARE, CodecUtil.Force.FIRST_COMPATIBLE_FOUND);
```
Also, if you can, check if you are producing keyframes. Add a logcat in this line:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/net/ossrs/rtmp/SrsFlvMuxer.java#L934

**Comment by luarropa** [comment]
By adding the line that you suggest, this error is printed:
<img width="525" alt="Screen Shot 2020-05-16 at 11 27 23 PM" src="https://user-images.githubusercontent.com/18237562/82135162-5ba74480-97cd-11ea-9025-06a650a23866.png">

On the other hand, i can't edit the SrsFlvMuxer.java file, is read only, so i can't see if i'm producing keyframes.

**Comment by pedroSG94** [comment]
If you are using gradle. Please download this project and edit SrsFlvMuxer file. After that, compile project and share logcat.
Also let me know which codec has your device using this line (it print in logcat all codec info about your device):
```java
for (String s: CodecUtil.showAllCodecsInfo()) {
      Log.e("Pedro", s);
}
```

**Comment by luarropa** [comment]
The codecs info For Loop prints this:
`E/Pedro: ----------------
    Name: OMX.google.aac.decoder
    Type: audio/mp4a-latm
    Max instances: 32
    ----- Decoder info -----
    ----- -----
    ----- Audio info -----
    Profile: 2, level: 0
    Profile: 5, level: 0
    Profile: 29, level: 0
    Profile: 23, level: 0
    Profile: 39, level: 0
    Profile: 20, level: 0
    Profile: 42, level: 0
    Bitrate range: 8000 - 510000
    Channels supported: 8
    Supported sample rate: 
    7350
    8000
    11025
    12000
    16000
    22050
    24000
    32000
    44100
    48000
    ----- -----
    Max instances: 32
    ----------------
    ----------------
    Name: OMX.google.amrnb.decoder
    Type: audio/3gpp
    Max instances: 32
    ----- Decoder info -----
    ----- -----
    ----- Audio info -----
    Bitrate range: 4750 - 12200
    Channels supported: 1
    Supported sample rate: 
    8000
    ----- -----
    Max instances: 32
    ----------------
    ----------------
    Name: OMX.google.amrwb.decoder
    Type: audio/amr-wb
    Max instances: 32
    ----- Decoder info -----
    ----- -----
    ----- Audio info -----
    Bitrate range: 6600 - 23850
    Channels supported: 1
    Supported sample rate: 
    16000
    ----- -----
    Max instances: 32
    ----------------
    ----------------
    Name: OMX.google.flac.decoder
    Type: audio/flac
    Max instances: 32
    ----- Decoder info -----
    ----- -----
    ----- Audio info -----
    Bitrate range: 1 - 21000000
    Channels supported: 8
    ----- -----
    Max instances: 32
    ----------------
    ----------------
    Name: OMX.google.g711.alaw.decoder
    Type: audio/g711-alaw
    Max instances: 32
    ----- Decoder info -----
    ----- -----
    ----- Audio info -----
    Bitrate range: 64000 - 64000
    Channels supported: 1
    Supported sample rate: 
    8000
    ----- -----
    Max instances: 32
    ----------------
    ----------------
    Name: OMX.google.g711.mlaw.decoder
    Type: audio/g711-mlaw
    Max instances: 32
    ----- Decoder info -----
    ----- -----
    ----- Audio info -----
    Bitrate range: 64000 - 64000
    Channels supported: 1
    Supported sample rate: 
    8000
    ----- -----
    Max instances: 32
    ----------------
    ----------------
    Name: OMX.google.gsm.decoder
    Type: audio/gsm
    Max instances: 32
    ----- Decoder info -----
    ----- -----
    ----- Audio info -----
    Bitrate range: 13000 - 13000
    Channels supported: 1
    Supported sample rate: 
    8000
    ----- -----
    Max instances: 32
    ----------------
    ----------------
    Name: OMX.google.mp3.decoder
    Type: audio/mpeg
    Max instances: 32
    ----- Decoder info -----
    ----- -----
    ----- Audio info -----
    Bitrate range: 8000 - 320000
    Channels supported: 2
    Supported sample rate: 
    8000
    11025
    12000
    16000
    22050
    24000
    32000
    44100
    48000
    ----- -----
    Max instances: 32
    ----------------
    ----------------
    Name: OMX.google.opus.decoder
    Type: audio/opus
    Max instances: 32
    ----- Decoder info -----
    ----- -----
    ----- Audio info -----
    Bitrate range: 6000 - 510000
    Channels supported: 8
    Supported sample rate: 
    48000
    ----- -----
    Max instances: 32
    ----------------
    ----------------
    Name: OMX.google.raw.decoder
    Type: audio/raw
    Max instances: 32
    ----- Decoder info -----
    ----- -----
    ----- Audio info -----
    Bitrate range: 1 - 10000000
    Channels supported: 8
    ----- -----
    Max instances: 32
    ----------------
    ----------------
    Name: OMX.google.vorbis.decoder
    Type: audio/vorbis
    Max instances: 32
    ----- Decoder info -----
    ----- -----
    ----- Audio info -----
    Bitrate range: 32000 - 500000
    Channels supported: 8
    ----- -----
    Max instances: 32
    ----------------
    ----------------
    Name: OMX.google.aac.encoder
    Type: audio/mp4a-latm
    Max instances: 32
    ----- Encoder info -----
    Complexity range: 0 - 0
    Quality range: 0 - 0
    CBR supported: false
    VBR supported: true
    CQ supported: false
    ----- -----
    ----- Audio info -----
    Profile: 2, level: 0
    Profile: 5, level: 0
    Profile: 29, level: 0
    Profile: 23, level: 0
    Profile: 39, level: 0
    Bitrate range: 8000 - 510000
    Channels supported: 6
    Supported sample rate: 
    8000
    11025
    12000
    16000
    22050
    24000
    32000
    44100
    48000
    ----- -----
    Max instances: 32
    ----------------
    ----------------
    Name: OMX.google.amrnb.encoder
    Type: audio/3gpp
    Max instances: 32
    ----- Encoder info -----
    Complexity range: 0 - 0
    Quality range: 0 - 0
    CBR supported: true
    VBR supported: false
    CQ supported: false
    ----- -----
    ----- Audio info -----
    Bitrate range: 4750 - 12200
    Channels supported: 1
    Supported sample rate: 
    8000
    ----- -----
    Max instances: 32
    ----------------
    ----------------
    Name: OMX.google.amrwb.encoder
    Type: audio/amr-wb
    Max instances: 32
    ----- Encoder info -----
    Complexity range: 0 - 0
    Quality range: 0 - 0
    CBR supported: true
    VBR supported: false
    CQ supported: false
    ----- -----
    ----- Audio info -----
    Bitrate range: 6600 - 23850
    Channels supported: 1
    Supported sample rate: 
    16000
    ----- -----
    Max instances: 32
    ----------------
    ----------------
    Name: OMX.google.flac.encoder
    Type: audio/flac
    Max instances: 32
    ----- Encoder info -----
    Complexity range: 0 - 8
    Quality range: 0 - 0
    CBR supported: false
    VBR supported: false
    CQ supported: true
    ----- -----
    ----- Audio info -----
    Bitrate range: 1 - 21000000
    Channels supported: 2
    ----- -----
    Max instances: 32
    ----------------
    ----------------
    Name: OMX.google.h264.decoder
    Type: video/avc
    Max instances: 32
    ----- Decoder info -----
    ----- -----
    ----- Video info -----
    Supported colors: 
    2135033992
    19
    Profile: 65536, level: 65536
    Profile: 1, level: 65536
    Profile: 2, level: 65536
    Profile: 524288, level: 65536
    Profile: 8, level: 65536
    Bitrate range: 1 - 12000000
    Frame rate range: 0 - 960
    Width range: 16 - 1920
    Height range: 16 - 1088
    ----- -----
    Max instances: 32
    ----------------
    ----------------
    Name: OMX.google.h263.decoder
    Type: video/3gpp
    Max instances: 32
    ----- Decoder info -----
    ----- -----
    ----- Video info -----
    Supported colors: 
    2135033992
    19
    Profile: 1, level: 4
    Profile: 1, level: 16
    Profile: 8, level: 4
    Profile: 8, level: 16
    Bitrate range: 1 - 384000
    Frame rate range: 1 - 30
    Width range: 4 - 352
    Height range: 4 - 288
    ----- -----
    Max instances: 32
    ----------------
    ----------------
    Name: OMX.google.hevc.decoder
    Type: video/hevc
    Max instances: 32
    ----- Decoder info -----
    ----- -----
    ----- Video info -----
    Supported colors: 
    2135033992
    19
    Profile: 1, level: 65536
    Profile: 4, level: 65536
    Bitrate range: 1 - 10000000
    Frame rate range: 0 - 960
    Width range: 2 - 2048
    Height range: 2 - 2048
    ----- -----
    Max instances: 32
    ----------------
    ----------------
    Name: OMX.google.mpeg4.decoder
    Type: video/mp4v-es
    Max instances: 32
    ----- Decoder info -----
    ----- -----
    ----- Video info -----
    Supported colors: 
    2135033992
    19
    Profile: 1, level: 16
    Bitrate range: 1 - 384000
    Frame rate range: 12 - 60
    Width range: 2 - 352
    Height range: 2 - 288
    ----- -----
    Max instances: 32
    ----------------
    ----------------
    Name: OMX.google.vp8.decoder
    Type: video/x-vnd.on2.vp8
    Max instances: 32
    ----- Decoder info -----
    ----- -----
    ----- Video info -----
    Supported colors: 
    2135033992
    19
    Bitrate range: 1 - 40000000
    Frame rate range: 0 - 960
    Width range: 2 - 2048
    Height range: 2 - 2048
    ----- -----
    Max instances: 32
    ----------------
    ----------------
    Name: OMX.google.vp9.decoder
    Type: video/x-vnd.on2.vp9
    Max instances: 32
    ----- Decoder info -----
    ----- -----
    ----- Video info -----
    Supported colors: 
    2135033992
    19
    Profile: 1, level: 256
    Profile: 4, level: 256
    Profile: 4096, level: 256
    Profile: 16384, level: 256
    Bitrate range: 1 - 40000000
    Frame rate range: 0 - 960
    Width range: 2 - 2048
    Height range: 2 - 2048
    ----- -----
    Max instances: 32
    ----------------
    ----------------
    Name: OMX.google.h264.encoder
    Type: video/avc
    Max instances: 32
    ----- Encoder info -----
    Complexity range: 0 - 0
    Quality range: 0 - 0
    CBR supported: false
    VBR supported: true
    CQ supported: false
    ----- -----
    ----- Video info -----
    Supported colors: 
    2135033992
    19
    21
    2130708361
    Profile: 65536, level: 4096
    Profile: 1, level: 4096
    Profile: 2, level: 4096
    Bitrate range: 1 - 20000000
    Frame rate range: 0 - 960
    Width range: 16 - 1920
    Height range: 16 - 1088
    ----- -----
    Max instances: 32
    ----------------
    ----------------
    Name: OMX.google.h263.encoder
    Type: video/3gpp
    Max instances: 32
    ----- Encoder info -----
    Complexity range: 0 - 0
    Quality range: 0 - 0
    CBR supported: false
    VBR supported: true
    CQ supported: false
    ----- -----
    ----- Video info -----
    Supported colors: 
    2135033992
    19
    21
    2130708361
    Profile: 1, level: 16
    Bitrate range: 1 - 128000
    Frame rate range: 1 - 15
    Width range: 176 - 176
    Height range: 144 - 144
    ----- -----
    Max instances: 32
    ----------------
    ----------------
    Name: OMX.google.mpeg4.encoder
    Type: video/mp4v-es
    Max instances: 32
    ----- Encoder info -----
    Complexity range: 0 - 0
    Quality range: 0 - 0
    CBR supported: false
    VBR supported: true
    CQ supported: false
    ----- -----
    ----- Video info -----
    Supported colors: 
    2135033992
    19
    21
    2130708361
    Profile: 4, level: 8
    Bitrate range: 1 - 64000
    Frame rate range: 12 - 60
    Width range: 16 - 176
    Height range: 16 - 144
    ----- -----
    Max instances: 32
    ----------------
    ----------------
    Name: OMX.google.vp8.encoder
    Type: video/x-vnd.on2.vp8
    Max instances: 32
    ----- Encoder info -----
    Complexity range: 0 - 0
    Quality range: 0 - 0
    CBR supported: true
    VBR supported: true
    CQ supported: false
    ----- -----
    ----- Video info -----
    Supported colors: 
    2135033992
    19
    21
    2130708361
    Profile: 1, level: 1
    Profile: 1, level: 2
    Profile: 1, level: 4
    Profile: 1, level: 8
    Bitrate range: 1 - 40000000
    Frame rate range: 0 - 960
    Width range: 2 - 2048
    Height range: 2 - 2048
    ----- -----
    Max instances: 32
    ----------------`

This is printed before the connection is stablished successfully:
`E/SrsFlvMuxer: annexb not match.
D/Handshake: writeC1(): Writing timestamp and Flash Player version
    partAfterDigest(): size: 274
I/SrsFlvMuxer: flv: h264 sps/pps sent, sps=14B, pps=6B
D/Handshake: copying digest offset bytes in partBeforeDigest
    writeC1(): Calculating digest
D/Handshake: writeC1(): writing C1 packet
    readS0
I/SrsFlvMuxer: frame discarded
I/chatty: uid=10133(com.pedro.rtpstreamer) MicrophoneManag identical 6 lines
I/SrsFlvMuxer: frame discarded
I/SrsFlvMuxer: 1
I/SrsFlvMuxer: frame discarded
I/SrsFlvMuxer: frame discarded
I/SrsFlvMuxer: frame discarded
I/chatty: uid=10133(com.pedro.rtpstreamer) MicrophoneManag identical 2 lines
I/SrsFlvMuxer: frame discarded
I/SrsFlvMuxer: frame discarded
I/chatty: uid=10133(com.pedro.rtpstreamer) MicrophoneManag identical 11 lines
I/SrsFlvMuxer: frame discarded
I/OpenGLRenderer: Davey! duration=851ms; Flags=0, IntendedVsync=651405796167, Vsync=651405796167, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=651408107571, AnimationStart=651408232591, PerformTraversalsStart=651408233370, DrawStart=651409426847, SyncQueued=651410800243, SyncStart=651411112077, IssueDrawCommandsStart=651411860898, SwapBuffers=651430254884, FrameCompleted=652258090334, DequeueBufferDuration=362000, QueueBufferDuration=595586000, 
I/SrsFlvMuxer: frame discarded
I/chatty: uid=10133(com.pedro.rtpstreamer) MicrophoneManag identical 2 lines
I/SrsFlvMuxer: frame discarded`

Seems like the one frame is generated and the other ones are discarded.

Let me know if you need something else.

**Comment by pedroSG94** [comment]
I was testing in AVD device but I can't reproduce your problem. This is my AVD:
![Captura de pantalla de 2020-05-20 11-26-43](https://user-images.githubusercontent.com/17556876/82430112-30527d00-9a8d-11ea-8c4d-fee82486c20c.png)
Test example using a local server:
![Captura de pantalla de 2020-05-20 11-30-23](https://user-images.githubusercontent.com/17556876/82430203-50823c00-9a8d-11ea-8725-c93aa71ffbd3.png)

I can see in logcat annexb not match but this is not related with your error because this is only info about library that you are using other method to find h264 header:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/net/ossrs/rtmp/SrsFlvMuxer.java#L733

**Comment by luarropa** [comment]
I get it. Could it be the server that is encoding the video badly ?. I think it is a bit daring on my part, but is there a chance you can try connecting to my server and see if it works?

**Comment by luarropa** [comment]
I get it. Let me try it. Thanks.
