### ISSUE TITLE
Problem: bitrate: N/A and No FPS info

### ISSUE THREAD

**Issue by namndev** [pedroSG94/rtmp-rtsp-stream-client-java#512]
Hi @pedroSG94,
I use the latest version (1.7.8) and all version before then it has a problem, when I check live's infomation with ffmpeg:
```
Metadata:
    server          : SRS/2.0.263(ZhouGuowen)
    srs_primary     : SRS/2.0release
    srs_authors     : winlin,wenjie.zhao
    server_version  : 2.0.263
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Data: none
    Stream #0:1: Audio: aac (LC), 44100 Hz, stereo, fltp
    Stream #0:2: Video: h264 (High), yuv420p(tv, bt709/bt709/smpte170m, progressive), 1080x1920, 1k tbr, 1k tbn
```

`bitrate`: `N/A` and not have `fps`.

**Comment by pedroSG94** [comment]
Hello,
That info is optional in RTMP protocol. You can add metadata info here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L366

**Comment by namndev** [comment]
Thank @pedroSG94,
