### ISSUE TITLE
Front camera is stretch and poor quality image

### ISSUE THREAD

**Issue by abadoliverco** [pedroSG94/rtmp-rtsp-stream-client-java#514]
Hi,
I'm trying to use the camera1 but the preview is stretch also it's not clear as the camera view (default camera app)

rtmpCamera2?.startPreview(CameraHelper.Facing.FRONT, 720, 1280) --- is not working, throwing error like this -> This camera resolution cant be opened

**Comment by pedroSG94** [comment]
Hello,
Are you using OpenGlView with keepAspectRatio enabled?
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/res/layout/activity_open_gl.xml#L12

About camera2 you should use a valid resolution to open it.
You can get valid resolutions from here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera2Base.java#L577

**Comment by abadoliverco** [comment]
hi @pedroSG94 
I'm using the OpenGlView but I want a fullscreen view of the camera how can I achieve this one? Thank you!

**Comment by pedroSG94** [comment]
If you want full screen and lose part of the view because this is cropped. I need develop it.
Other way is use a resolution with same aspect ratio than your device screen.

**Comment by abadoliverco** [comment]
understand, I'll try to look at this one 

> About camera2 you should use a valid resolution to open it.
You can get valid resolutions from here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera2Base.java#L577
>

**Comment by abadoliverco** [comment]
another thing, can I use this library for the camera view? --> https://github.com/RedApparat/Fotoapparat

**Comment by pedroSG94** [comment]
Unfortunately you can't mix both libraries. 
I need do a dedicated develop for it but I prefer implement support for CameraX if I do it in the future.

**Comment by abadoliverco** [comment]
hi @pedroSG94
if surfaceDestroyed called how to restart the CameraView to open again? surfaceDestroyed is called when the device is put into sleep

**Comment by pedroSG94** [comment]
Surfacechanged is called when it is ready to use.
You should stop camera when surface destroyed is called and start after surfacechanged

**Comment by hoangtuanitstar** [comment]
camera is low quality, how can I improve it please ?

**Comment by pedroSG94** [comment]
Try with camera2 and use more resolution. Other way is modify camera parameters in this class as you need:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java
If you are using camera1:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java

If you can't solve with this. Post here your device model, api, an image of you camera and describe your problems to know how to configure it, for example: 
(image)
Samsung s10 api 29 -> autofocus is not working, low brightness and white balance problems with camera2.

**Comment by vishistv** [comment]
> If you want full screen and lose part of the view because this is cropped. I need develop it.
> Other way is use a resolution with same aspect ratio than your device screen.

How do i do this? Am I to change the width and height of SurfaceView programmatically according to my resolution? Please provide an example

**Comment by pedroSG94** [comment]
Using OpenGlView set this param:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/res/layout/activity_open_gl.xml#L13
to:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/res/values/attrs.xml#L12
