### ISSUE TITLE
Simple RTMP only player?

### ISSUE THREAD

**Issue by AlexUrrutia** [pedroSG94/rtmp-rtsp-stream-client-java#516]
Hello Pedro, I want to play live RTMP video only, can you suggest a simple and light RTMP player? not sure which one to use as we only stream RTMP live video, thanks!

**Comment by pedroSG94** [comment]
Hello,
Maybe exoplayer with rtmp plugin could be a good solution:
https://github.com/google/ExoPlayer
This tutorial could help:
https://medium.com/@KarthikPonnam/rtmp-player-android-using-exo-media-player-ac7a012b7a25

**Comment by AlexUrrutia** [comment]
Thanks
