### ISSUE TITLE
Remove Subtitles

### ISSUE THREAD

**Issue by woipot** [pedroSG94/rtmp-rtsp-stream-client-java#518]
Hi, how can i remove subtitles thread from stream?

**Comment by pedroSG94** [comment]
Hello,
I don't understand. What do you means with subtitles thread?

**Comment by woipot** [comment]
Sorry, I mean it
 ![image](https://user-images.githubusercontent.com/29792927/77426101-e038a080-6de4-11ea-9426-52991b691847.png)

**Comment by pedroSG94** [comment]
I'm not sending subtitles in stream. Only protocol commands and video/audio packets.
Maybe your server is doing it. What server are you using?
