### ISSUE TITLE
Camera should show preview image

### ISSUE THREAD

**Issue by MikeMannox** [pedroSG94/rtmp-rtsp-stream-client-java#52]
The flow for `RT*PCamera` classes appears to be wrong. (I am looking at `TextureModeRtmpActivity` and `RtmpCamera2` in particular as `Camera1` is deprecated in most cases.

The expected flow would be to:
  * open the app
  * see a preview 
    * (allow someone to adjust themselves)
  * start streaming 

It does not seem possible to draw the camera preview image to the surface before pressing `startStream(...)`

Is there a workaround?

**Comment by pedroSG94** [comment]
I am developing it. For now if you want do develop it you will need modify Camera2Base and maybe VideoEncoder and CameraManager.
Depend of my time and develop difficult this could be finished this week.

**Comment by MikeMannox** [comment]
Ahh, thank you - that is good news 👍
