### ISSUE TITLE
Expose API for custom audio processing

### ISSUE THREAD

**Issue by mzgreen** [pedroSG94/rtmp-rtsp-stream-client-java#520]
The library exposes public API for custom Video Filters. It would be good to have a similar thing but for audio. There already is `AudioPostProcessEffect` which does audio processing but I couldn't find a way to define my own AudioProcessor.

**Comment by pedroSG94** [comment]
Yes, this is a good idea but I don't know how to mix [android AudioEffect](https://developer.android.com/reference/android/media/audiofx/AudioEffect) with a custom effect because you can't extend this class to create a new one.
I need to think of a good solution

**Comment by mzgreen** [comment]
I don't know much about this library yet (just started exploring it) but please take a look at ExoPlayer's AudioProcessor API:
https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/audio/AudioProcessor.html

Maybe it'll inspire you somehow :)

And thank you for maintaining this awesome library! :clap:

**Comment by mzgreen** [comment]
This `GetMicrophoneData` interface seems like a nice entry point. AudioProcessor can be a thing that gets access to audio buffer, transforms it and returns it. Such processors could be then used to form something like a pipeline of transformations.

**Comment by pedroSG94** [comment]
I was reading Exoplayer implementation and I can't find how they are doing buffer modification to add audio filters.
I think your idea is the best solution for it. I'm trying to find an effect to test this but I can't find an algorithm to know that it is working.

**Comment by mzgreen** [comment]
Quickly looking at ExoPlayer I found this: https://github.com/google/ExoPlayer/blob/62092e664586175107a3aaac3e1b0efa3059049f/library/core/src/main/java/com/google/android/exoplayer2/audio/DefaultAudioSink.java#L709

seems like this class is a default sink that is responsible for managing the buffers and audio processors pipeline, and this method that I pasted above executes AudioProcessor's methods passing audio buffers into processors and getting the results back.

**Comment by pedroSG94** [comment]
I tried add audio sink but I can't heard any difference. For now, I added a class without effect.
The idea is similar to gl filter. Use this method to set an effect:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L117
You can clear audio effect with this:
```java
rtspCamera1.setCustomAudioEffect(new NoAudioEffect());
```
To create a new effect you should extend from [CustomAudioEffect](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/audio/CustomAudioEffect.java) and modify buffer in process method.
