### ISSUE TITLE
Discarded Frames

### ISSUE THREAD

**Issue by abadoliverco** [pedroSG94/rtmp-rtsp-stream-client-java#523]
Hi,

Is there a way to detect upload speed in your library to avoid "discarded frames"? 
thank you!

**Comment by pedroSG94** [comment]
You have bps in this callback:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/customexample/RtmpActivity.java#L341
Also you can do automatic adaptative video bitrate to avoid it:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Adaptative-video-bitrate.

**Comment by abadoliverco** [comment]
Hi

`public void onNewBitrateRtmp(final long bitrate)` is not returning the correct bitrate. I got some value but it says that "frame discarded". Is there a way to create a listener if the frame is discarded?

btw, I'm trying to test it on poor/slow internet connection

Thank you!

**Comment by pedroSG94** [comment]
"frame discarded" is not related with bitrate received in the callback.
I am counting after sending the packets to the server, therefore the discarded frames do not count.
If you want add other callback this is symple. Add a method to ConnectCheckerRtmp interface:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/net/ossrs/rtmp/ConnectCheckerRtmp.java
Call this method after frame discarded happens:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/net/ossrs/rtmp/SrsFlvMuxer.java#L1029

As I told you in my previous comment if you want to avoid that logcat you should use adaptative video bitrate
