### ISSUE TITLE
Surface Mode and Texture mode is not working on Android 5.0 : Camera2 API problem to param CameraDevice ?

### ISSUE THREAD

**Issue by Geremp** [pedroSG94/rtmp-rtsp-stream-client-java#524]
Hello,

Sorry to bother you again.

Your app work great on my phone : 
Honor 20 Lite - Android 10

I try to test it on : 
Samsung Galaxy S4 - Android 5.0

- Custom RTMP, OpenGL work : Screen in full size with no distortion : 
The debugger says : OpenGlViewBase: size: 1080x1845

- Texture mode and Surface mode is not workinf : Black image : 
The debugger says : 
CameraDevice-0-LE: Surface with size (w=1080, h=1845) and format 0x1 is not valid, size not in valid set: [1440x1080, 1280x720, 1056x864, 960x720, 720x480, 640x480, 320x240, 176x144]

I develop my own app, I use your OpenGL example, and it is not working.
So i test your example.
I can't figure out what is the problem…

I guess it is very easy for you…

**Comment by pedroSG94** [comment]
This look that you aren't using a valid resolution.
Try set one of the debug log:
1440x1080, 1280x720, 1056x864, 960x720, 720x480, 640x480, 320x240, 176x144.
Also you can use this method to get all valid resolutions:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera2Base.java#L568

**Comment by Geremp** [comment]
The problem seems to come with the use of Camera2 API for the Galaxy S4 on Android 5

**Comment by pedroSG94** [comment]
Now that you mention it:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/249

**Comment by Geremp** [comment]
Ok thanks !
So i use my old encoder to the previous API and >28 I use yours.
Thank you very much !
