### ISSUE TITLE
Is possible to have preview got size different than stream ?

### ISSUE THREAD

**Issue by Geremp** [pedroSG94/rtmp-rtsp-stream-client-java#525]
Hello,

I would like to know if it is possible to have a preview size different that the stream we send to the server ?

I want that my preview fill the screen, but i want to downsize the video that i stream.

For example :
` public void surfaceChanged(SurfaceHolder surfaceHolder, int i, int i1, int i2) {
{
rtmpCamera2.startPreview();

    int orientation = getScreenRotationOnPhone();

    rtmpCamera2.stopPreview();
   
    if(orientation == 90 || orientation == 270)
    {
      rtmpCamera2.startPreview(CameraHelper.Facing.BACK,i2,i1,orientation);
    }
    else
    {
      rtmpCamera2.startPreview(CameraHelper.Facing.BACK,i1,i2,orientation);
    }
}`

Click to stream button :
`rtmpCamera2.prepareVideo(640,480,fps,bitrate,false,orientation_degree);
rtmpCamera2.startStream(stream_url+"/"+stream_id); `

Image before stream : 
![before](https://user-images.githubusercontent.com/6321146/77959009-39696e00-72d6-11ea-85ea-1714b6222c39.jpg)

Image during the stream : 
![during](https://user-images.githubusercontent.com/6321146/77959029-42f2d600-72d6-11ea-830e-62f56533e04d.jpg)

**Comment by pedroSG94** [comment]
When you say downsize, Do you means set preview, for example, to 1080p but stream to 480p?

I need modify library. In my case I use same resolution because your idea is only possible with opengl (I started this library using only SurfaceView) so if you use SurfaceView or TextureView I need use different logic for it. I means that it is a chaos to maintain the code.

**Comment by Geremp** [comment]
Hello Pedro,

I am using your OpenGL example.
I would like to have a preview in full screen on my device, but yes, can stream in 480p for example, so : 
rtmpCamera2.prepareVideo(640,480,fps,bitrate,false,orientation_degree); 

And this without touch the preview, so
- I can stream in 480p
- But my device preview is in full screen

**Comment by pedroSG94** [comment]
Yes, The second is possible and more easy. 
The question is:
Full screen without aspect ratio or with aspect ratio and crop if needed?

**Comment by Geremp** [comment]
With aspect ratio. You cannot show a preview with distorsion. It is mandatory. 
The better is without crop. 
As the two image I send in my first question.

**Comment by pedroSG94** [comment]
Ok. Replace this line:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/utils/gl/PreviewSizeCalculator.java#L19
To:
```java
GLES20.glViewport(0, 0, previewWidth, realHeight);
```

**Comment by Geremp** [comment]
Here the result in image : 
![Screenshot_20200331_144552_com visitemonappart vma](https://user-images.githubusercontent.com/6321146/78028164-de2f8e00-735e-11ea-9807-1322a8f44b27.jpg)

So not working, but i am sure you are not to far :)

**Comment by Geremp** [comment]
if i change this line with this : 
`GLES20.glViewport(0, 0, previewWidth, previewHeight);`

The preview is in full screen, but the ratio is not good, so the image is "strech", distortion.

**Comment by pedroSG94** [comment]
Replace this:
```java
if (previewWidth > previewHeight) { //landscape
        int realWidth = previewHeight * streamWidth / streamHeight;
        GLES20.glViewport((previewWidth - realWidth) / 2, 0, realWidth, previewHeight);
} else { //portrait
        int realHeight = previewWidth * streamHeight / streamWidth;
        GLES20.glViewport(0, (previewHeight - realHeight) / 2, previewWidth, realHeight);
}
```
To:
```java
if (previewWidth > previewHeight) { //landscape
        int realHeight = previewWidth * streamHeight / streamWidth;
        GLES20.glViewport(0, -((realHeight - previewWidth) / 2), previewWidth, realHeight);
} else { //portrait
        int realWidth = previewHeight * streamWidth / streamHeight;
        GLES20.glViewport(-((realWidth - previewWidth) / 2), 0, realWidth, previewHeight);
}
```

**Comment by Geremp** [comment]
It's better as you can see, because it is in fullscreen.

But il you look the mobile device screen AND the computer screen, you can see that the mobiel is crop.
The stream is larger than the mobile preview.
So people think the camera stream less than the reality.
![Screenshot_20200331_175333_com visitemonappart vma](https://user-images.githubusercontent.com/6321146/78047692-f3b1b180-7378-11ea-96aa-b5127e7aa4ee.jpg)

**Comment by pedroSG94** [comment]
Yes, I know.

In your first post. Your first image you can't see fridge, but in your second image you can.

You can't set full screen without crop or distortion image if you are streaming with a different aspect ratio of your device. For example:
If you have a device with a screen of 100x200px but you do a stream of 200x200. Mathematically, you have 2 options:
- Reduce image to 100x100 to keep aspect ratio but no full screen (you lose 100px of screen). This is the default case.
- Set image to 200x200 doing a crop in width because physically you can't set an image of 200x200 in a 100x200 screen. This is my last modification.

Other option is use same aspect ratio in screen and stream. If you have a device with 16:9 screen try set a resolution of 16:9 (640x480 is 4:3 that is your actual case)

**Comment by Geremp** [comment]
My bad pedro…
I change to 640x360.
and i set this : 
`GLES20.glViewport(0, 0, previewWidth, previewHeight);` L19 and it is working like a charm.

Can you confirm me that is correct ?

Thanks a lot !

**Comment by pedroSG94** [comment]
Yes, 640x360 is 16:9 propably like your screen. 
Your screen could be 120x720px, 1920x0180px or 2560x1440px

**Comment by Geremp** [comment]
Thanks !

**Comment by Geremp** [comment]
Hello Pedro,

I test again the openGL preview, here the code i change :
`if (keepAspectRatio) {
      if (previewWidth > previewHeight) { //landscape
        int realWidth = previewHeight * streamWidth / streamHeight;
        //GLES20.glViewport((previewWidth - realWidth) / 2, 0, realWidth, previewHeight);
        GLES20.glViewport(0, 0, previewWidth, previewHeight);
      } else { //portrait
        int realHeight = previewWidth * streamHeight / streamWidth;
        //GLES20.glViewport(0, (previewHeight - realHeight) / 2, previewWidth, realHeight);
        GLES20.glViewport(0, 0, previewWidth, previewHeight);
      }`

The great thing is this change put the preview in full screen on the device.
But as you can see below, preview and stream are stretch/ have distorsion on vertical/horizontal …

Can you help me ? 
I think my change is not good : 
![Capture d’écran 2020-04-02 à 12 23 33](https://user-images.githubusercontent.com/6321146/78239404-f2e66000-74dd-11ea-9514-782b5ab0bde6.png)

**Comment by pedroSG94** [comment]
Your code is basically adapt image to fill screen doing distortion.
What do you want exactly?
I means:
- Let me know your view resolution and your stream resolution.
- Your expected image result.

**Comment by pedroSG94** [comment]
This code means:
```java
GLES20.glViewport(0, 0, previewWidth, previewHeight);
```
I want start draw in pixel 0,0 (cardinal point 0X, 0Y) and finish this draw in my max view width and my max view height (for example my openglview has 200x200 this menas that you are doing this:
```java
GLES20.glViewport(0, 0, 200, 200);
```

**Comment by Geremp** [comment]
Ok I see my mistake…
As the beginnning of this open issue:
: Preview resolution : 720p 16:9
: Stream resolution : 640x360 -> 360p 16:9

Screen is in 16:9

I find the good code for vertical stream : 
`GLES20.glViewport(0, 0, previewWidth, previewHeight);` L19
As you said in reponse 6.
i got a little gap at the top of the preview, but i have a black header, so the user will not see the difference.

But I try to do the same for landscape (horizontal) : 
This code is not good :  `GLES20.glViewport(0, 0, realWidth, previewHeight);`

preview before stream :  
![Screenshot_20200402_134024_com visitemonappart vma](https://user-images.githubusercontent.com/6321146/78245464-d0f1db00-74e7-11ea-9590-edd31a772031.jpg)

Preview during stream :
![Screenshot_20200402_134031_com visitemonappart vma](https://user-images.githubusercontent.com/6321146/78245430-c33c5580-74e7-11ea-893c-f2b6fa8ab596.jpg)

if I try to put the same code than portrait for the landscape, my preview is in fullscreen, but the preview show less than the real stream : 
code : `GLES20.glViewport(0, 0, previewWidth, previewHeight);
Preview during stream : 
![Screenshot_20200402_134713_com visitemonappart vma](https://user-images.githubusercontent.com/6321146/78245953-9fc5da80-74e8-11ea-90d6-38459d0be0c5.jpg)

Real stream : 
![Capture d’écran 2020-04-02 à 13 47 12](https://user-images.githubusercontent.com/6321146/78245963-a5bbbb80-74e8-11ea-8b87-e745d079f7c4.png)

**Comment by Geremp** [comment]
So I guess we have no solution because it depends of the device screen.
The difference between device preview and real stream is lite so for me it is the good solution :
Not have a stretch preview and steam.
User see approximately same thing in preview and stream.

So my solution is this : (as Pedro say)

if (keepAspectRatio) {
      if (previewWidth > previewHeight) { //landscape
        int realHeight = previewWidth * streamHeight / streamWidth;
        GLES20.glViewport(0, 0, previewWidth, realHeight);
      } else { //portrait
        int realHeight = previewWidth * streamHeight / streamWidth;
        GLES20.glViewport(0, 0, previewWidth, realHeight);
      }
