### ISSUE TITLE
How to set the frame rate and bit rate

### ISSUE THREAD

**Issue by icewst** [pedroSG94/rtmp-rtsp-stream-client-java#527]
How to set the frame rate and bit rate?

`public boolean prepareVideo(int width, int height, int fps, int bitrate, int rotation, int dpi) `

Is it here?

**Comment by AlexUrrutia** [comment]
Yes it is

**Comment by icewst** [comment]
But I found that after setting the frame rate, the actual frame rate will be slightly different in the end. For example, set to 60, the final result is 60.56

**Comment by icewst** [comment]
> Yes it is


But I found that after setting the frame rate, the actual frame rate will be slightly different in the end. For example, set to 60, the final result is 60.56
