### ISSUE TITLE
Record while Streaming : video result is laggy

### ISSUE THREAD

**Issue by Geremp** [pedroSG94/rtmp-rtsp-stream-client-java#529]
Hello Pedro,

I fond something weird…
I try to record a video while streaming.

Everythink work but the video record is laggy.
But the stream is smooth.
I don't know why.

My stream params : 
`int fps = 30;
int bitrate = 650*1024;
rtmpCamera2.prepareVideo(640,360,fps,bitrate,false,orientation_degree);
rtmpCamera2.prepareAudio();`

I am using opengl and Camera2 api

**Comment by pedroSG94** [comment]
This is weird...
When you record a video this should be the same that stream result (I'm recording and streaming same buffer).
Try set iFrame parameter to 5.
Also check if you have same problem if you record without stream

**Comment by Geremp** [comment]
When you say iframe, you whant to say : iFrameInterval that is located in encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java ?

**Comment by pedroSG94** [comment]
Yes, but you can modify with this method:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera2Base.java#L202

**Comment by Geremp** [comment]
So here my test on your app : 
No modification, so IFrameInterval = 2
Custom RTMP example : 
- Only record : preview good, but video record laggy 
- Record and stream : preview good, stream good, but video record laggy 

With IFrameInterval = 5 
Custom RTMP example : 
- Only record : preview good, but video record laggy 
- Record and stream : preview good, stream good, but video record laggy 

So same result…

**Comment by pedroSG94** [comment]
I don't know the reason so I want discard anythings:

- Is your default camera app is working fine, right?
- Did you try with camera1?
- Try increasing iFrame from 5 to 5 up to 30 (10, 15, 20, 25, 30).
- Finally try with other device if you have it (I tested with 2 devices and all seems fine)

**Comment by Geremp** [comment]
I test in your app, custom rtmp example, so it is using Camera1 API.
I will try with Camera2 API, always in your app

**Comment by pedroSG94** [comment]
Can you test with opengl example?

**Comment by Geremp** [comment]
Yes, i did, same result…
Maybe the prob is not the record video, but the stream itself.
It is not a big lag.

To see the difference, i did used  Larix broadcaster.
The video seems smoother than your lib… with the same params.

So myabe is not the recordet, but the encoder.
You say that recrod and stream use the same buffer.

What do you think ?

**Comment by pedroSG94** [comment]
I'm not sure. 
I was testing with 3 devices that I have but I can't see any difference.
I need to find the reason for this error but it seems difficult because I can't reproduce it.
