### ISSUE TITLE
How to reconnect

### ISSUE THREAD

**Issue by icewst** [pedroSG94/rtmp-rtsp-stream-client-java#530]
How do I reconnect if I receive "onConnectionFailedRtmp". I tried "reConnect" but didn't succeed

**Comment by pedroSG94** [comment]
Try this:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/defaultexample/ExampleRtmpActivity.java#L75
The number is ms before reconnect . I recommend you wait at least 1s (1000).
Also remember set number of retries:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/defaultexample/ExampleRtmpActivity.java#L56
This is the number of times that library will try reconnect to server
