### ISSUE TITLE
Text filter become jitter

### ISSUE THREAD

**Issue by mynew-github-account** [pedroSG94/rtmp-rtsp-stream-client-java#535]
It works well when I choose 720p 
but as resolution decrease, it become more jitter, not so clear.
Is there a way to solve an issue

**Comment by pedroSG94** [comment]
Hi,
You are right, with low resolution it become more jitter.
You can do it to reduce jitter:
- Increase precision to highp:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/res/raw/object_fragment.glsl#L1
To:
```glsl
precision highp float;
```
- Use a bold TypeFace and increase textsize (After add filter you can resize if you want reduce size with setScale method):
```java
textObjectFilterRender.setText("Hello world", 40, Color.RED, Typeface.defaultFromStyle(Typeface.BOLD));
```
