### ISSUE TITLE
java.lang.Security.Exception:Invalid media projection

### ISSUE THREAD

**Issue by icewst** [pedroSG94/rtmp-rtsp-stream-client-java#536]
java.lang.Security.Exception:Invalid media projection

DisplayBase 

 mediaProjection = mediaProjectionManager.getMediaProjection(resultCode, data);

If you use the last "mediaProjection", then this error will occur. Almost inevitable.
Every time you create a new one, it's normal.

vivo x9s 8.1.0

**Comment by pedroSG94** [comment]
I can't reproduce your error.
Can you explain how to reproduce it? Are you using example app?

**Comment by icewst** [comment]
> I can't reproduce your error.
> Can you explain how to reproduce it? Are you using example app?

Only appeared on an old phone, other phones are normal.
The second time, it will appear.
