### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by mynew-github-account** [pedroSG94/rtmp-rtsp-stream-client-java#537]
After reconnect
its show message "Error send packet: Connection reset"
after this onConnectionFailedRtmp called infinitely.

**Comment by pedroSG94** [comment]
Checking...

**Comment by pedroSG94** [comment]
Fixed: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/00d0fb470550e5cf8d2ec44d759cf856d6cedda3
