### ISSUE TITLE
Filter after replace view

### ISSUE THREAD

**Issue by mynew-github-account** [pedroSG94/rtmp-rtsp-stream-client-java#539]
When we called replaceview to go outside of the app and after when come back all the filter which were applied are gone 
Is there a way to preserve the same filters at same position after replaceView.
I tried passing filter array list to replaceView method and applied the same filters in replaceGlInterface method but didn't work

**Comment by pedroSG94** [comment]
When you replace glInterface with replaceView all filters are released but tecnically you can create a new filter and set it after use replaceView method.
```java
rtmpCamera1.replaceView(context);
rtmpCamera1.getGlInterface().setFilter(filter);
```
I think the best way is create a list with all filter and add that filter with a new instance getting old parameters, for example:
```java
private List<BaseFilterRender> list = new ArrayList<>();

  public void sample() {
    rtmpCamera1.replaceView(this);
    for (BaseFilterRender filter : list) {
      BaseFilterRender newFilter;
      if (filter instanceof GifObjectFilterRender) {
        newFilter = new GifObjectFilterRender();
        ((GifObjectFilterRender) newFilter).setPosition(
            ((GifObjectFilterRender) filter).getPosition().x,
            ((GifObjectFilterRender) filter).getPosition().y);
        ((GifObjectFilterRender) newFilter).setScale(
            ((GifObjectFilterRender) filter).getScale().x,
            ((GifObjectFilterRender) filter).getScale().y);
        //Maybe you need create other list with sources associated to some filters
        ((GifObjectFilterRender) newFilter).setGif(input);
      } else {
        newFilter = new NoFilterRender();
      }
      rtmpCamera1.getGlInterface().setFilter(newFilter);
    }
  }
```
I know that this isn't clear. I will add a method to all filter to do it automatically
