### ISSUE TITLE
Stretched Preview

### ISSUE THREAD

**Issue by zonell** [pedroSG94/rtmp-rtsp-stream-client-java#542]
Hi
I replaced that on the preview the picture is a little stretched, the circle looks like an oval
This problem is only for preview, there are no problems in the video stream

Thanks

**Comment by pedroSG94** [comment]
I don't understand.
What do you means with preview oval?
What did you replaced?

**Comment by zonell** [comment]
[https://dropmefiles.com/P8Rgd]
the picture is stretched up
I took some screenshots
