### ISSUE TITLE
How publish H264 raw data to server  via rtsp

### ISSUE THREAD

**Issue by bigbigcloudy** [pedroSG94/rtmp-rtsp-stream-client-java#544]
i would like live stream video from DJI TO  Server. I got H264 raw data from this callback, And I'm looking a library which supports live stream from H264 raw data or any document about live stream from H264 data. Thank for any support.

**Comment by pedroSG94** [comment]
You can download the project and install example app. After test with that let me know if you have any problem. Remember read example codes to know how to use it:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/master/app/src/main/java/com/pedro/rtpstreamer

**Comment by bigbigcloudy** [comment]
i have read the examples and  i test the TexturemodeExample successful , it seems encode camra date to h264 and sent to server.now i get the H264 raw data from callback 
mReceivedVideoDataListener = new VideoFeeder.VideoDataListener() {
            @Override
            public void onReceive(byte[] videoBuffer, int size) {
                     onFrame(videoBuffer,0,size);
}
but i dont konw what to do next,i try to decode the videoBuffer with mediacodec  
    private void onFrame(byte[] buf,int offset,int length){
        if(codec!=null){
            MediaCodec.BufferInfo bufferInfo = new MediaCodec.BufferInfo();
            int inputBufferIndex = codec.dequeueInputBuffer(-1);
            if (inputBufferIndex >= 0) {
                ByteBuffer inputBuffer = codec.getInputBuffer(inputBufferIndex);
                inputBuffer.clear();
                inputBuffer.put(buf,offset,length);
                codec.queueInputBuffer(inputBufferIndex, 0, buf.length, count*1000/25, 0);
                count++;
            }
            for (; true; ) {
                int outBufferIndex = codec.dequeueOutputBuffer(bufferInfo, 1000);
                if (outBufferIndex == MediaCodec.INFO_OUTPUT_FORMAT_CHANGED) {
                    MediaFormat mediaFormat = codec.getOutputFormat();
                    rtspCamera2.videoEncoder.formatChanged(codec,mediaFormat);
                } else if (outBufferIndex >= 0) {
                    rtspCamera2.videoEncoder.outputAvailable(codec, outBufferIndex, bufferInfo);
                } else {
                    break;
                }
            }
        }
    }
but i find that  sps and pps just be  null.

from the example given,i dont kown what to do with the h264 raw video data,and how to sent to server with rtsp,thank for your helping. or whitch example can help me

**Comment by pedroSG94** [comment]
I don't understand. I thought you wanted to use the default examples.
Can you explain your case better? Do you have your own h264 data and you want stream it?

**Comment by bigbigcloudy** [comment]
i can get h264 raw data from 
@override
 //receiving the raw H264 video data for camera live view
public void onReceive(byte[] videoBuffer, int size) {

}
now i want to stream the data  to my server with rtsp.but i dont know how to stream it.

**Comment by bigbigcloudy** [comment]
i read your example,but i cant understand the following code ,how this callback be triggered.
private void createAsyncCallback() {
    callback = new MediaCodec.Callback() {
      @Override
      public void onInputBufferAvailable(@NonNull MediaCodec mediaCodec, int inBufferIndex) {
        try {
          inputAvailable(mediaCodec, inBufferIndex, null);
        } catch (IllegalStateException e) {
          Log.i(TAG, "Encoding error", e);
        }
      }

      @Override
      public void onOutputBufferAvailable(@NonNull MediaCodec mediaCodec, int outBufferIndex,
          @NonNull MediaCodec.BufferInfo bufferInfo) {
        try {
          outputAvailable(mediaCodec, outBufferIndex, bufferInfo);
        } catch (IllegalStateException e) {
          Log.i(TAG, "Encoding error", e);
        }
      }

      @Override
      public void onError(@NonNull MediaCodec mediaCodec, @NonNull MediaCodec.CodecException e) {
        Log.e(TAG, "Error", e);
      }

      @Override
      public void onOutputFormatChanged(@NonNull MediaCodec mediaCodec,
          @NonNull MediaFormat mediaFormat) {
        formatChanged(mediaCodec, mediaFormat);
      }
    };
  }
 
And after i get the h264 raw video data,what shoud i do next to stream it.

**Comment by pedroSG94** [comment]
Ok. I suppose you have other library where you can get h264 buffer and you want stream it.
You only need use RtspClient class and extract sps and pps from your buffer.
First of all read this class to know more or less how work RtspClient:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtsp/RtspCamera1.java
You need use RtspClient to stream your buffer but to do it you need stream data (audio and video information). Audio info is irrelevant because you havent audio so we can select stereo channal and 44100hz sample rate for example. But you need extract video data.
This could be a code example **(Remember change your endpoint url in rtspClient.setUrl method):**
```java
  private MediaCodec.BufferInfo videoInfo = new MediaCodec.BufferInfo();
  private long presentTimeUs = 0L;
  private RtspClient rtspClient = new RtspClient(new ConnectCheckerRtsp() {
    @Override
    public void onConnectionSuccessRtsp() {
      Log.e("Pedro", "connection success");
    }

    @Override
    public void onConnectionFailedRtsp(String reason) {

    }

    @Override
    public void onNewBitrateRtsp(long bitrate) {

    }

    @Override
    public void onDisconnectRtsp() {

    }

    @Override
    public void onAuthErrorRtsp() {

    }

    @Override
    public void onAuthSuccessRtsp() {

    }
  });

  //receiving the raw H264 video data for camera live view
  public void onReceive(byte[] videoBuffer, int size) {
    videoInfo.size = size;
    videoInfo.offset = 0;
    videoInfo.flags = MediaCodec.BUFFER_FLAG_PARTIAL_FRAME;
    videoInfo.presentationTimeUs = System.nanoTime() / 1000 - presentTimeUs;
    int naluType = videoBuffer[0] & 0x1f;
      //First keyframe received and you start stream.
      // Change conditional as you want but stream must start with a keyframe
    if (naluType == 5 && !rtspClient.isStreaming()) {
      videoInfo.flags = MediaCodec.BUFFER_FLAG_KEY_FRAME;
      Pair<ByteBuffer, ByteBuffer> videoData = decodeSpsPpsFromBuffer(videoBuffer, size);
      if (videoData != null) {
        rtspClient.setIsStereo(true);
        rtspClient.setSampleRate(44100);
        presentTimeUs = System.nanoTime() / 1000;
        ByteBuffer newSps = videoData.first;
        ByteBuffer newPps = videoData.second;
        rtspClient.setSPSandPPS(newSps, newPps, null);
        rtspClient.setUrl("rtsp://myendpointserver");
        rtspClient.connect();
      } else {
        Log.e("Pedro", "Error to extract video data");
      }
    }
    ByteBuffer h264Buffer = ByteBuffer.wrap(videoBuffer);
    rtspClient.sendVideo(h264Buffer, videoInfo);
  }

  /**
   * decode sps and pps from a byte[]
   */
  private Pair<ByteBuffer, ByteBuffer> decodeSpsPpsFromBuffer(byte[] csd, int length) {
    byte[] mSPS = null, mPPS = null;
    int i = 0;
    int spsIndex = -1;
    int ppsIndex = -1;
    while (i < length - 4) {
      if (csd[i] == 0 && csd[i + 1] == 0 && csd[i + 2] == 0 && csd[i + 3] == 1) {
        if (spsIndex == -1) {
          spsIndex = i;
        } else {
          ppsIndex = i;
          break;
        }
      }
      i++;
    }
    if (spsIndex != -1 && ppsIndex != -1) {
      mSPS = new byte[ppsIndex];
      System.arraycopy(csd, spsIndex, mSPS, 0, ppsIndex);
      mPPS = new byte[length - ppsIndex];
      System.arraycopy(csd, ppsIndex, mPPS, 0, length - ppsIndex);
    }
    if (mSPS != null && mPPS != null) {
      return new Pair<>(ByteBuffer.wrap(mSPS), ByteBuffer.wrap(mPPS));
    }
    return null;
  }
```
To stop stream you must call:
```java
rtspClient.disconnect();
```

**Comment by wolfheros** [comment]
what about if I want add a pcm audio data sync with the video data. is that possible using RtspClient? if it can , could you show me the code, the pcm data is short[] .Thanks

**Comment by pedroSG94** [comment]
You must encode PCM to AAC audio and use:
```java
rtspClient.sendAudio(aacBuffer, audioInfo);
```
You can use AudioEncoder class to do it but you need change short[] to byte[]:
https://stackoverflow.com/questions/10804852/how-to-convert-short-array-to-byte-array
AudioEncoder example:
```java
AudioEncoder audioEncoder = new AudioEncoder(new GetAacData() {
      @Override
      public void getAacData(ByteBuffer aacBuffer, MediaCodec.BufferInfo info) {
        //get aac data encoded, send it to rtspClient
        rtspClient.sendAudio(aacBuffer, info);
      }

      @Override
      public void onAudioFormat(MediaFormat mediaFormat) {

      }
    });
    /*
     * set audio parameters
     * bitrate -> bitrate used 64000 is normally fine
     * samplerate -> samplerate of pcmbuffer
     * isStereo -> audio channel. True if pcm buffer is stereo, false if pcm buffer is mono
     * maxInputSize -> the size of pcmbuffer in bytes. If you don't know it try with default value 0.
     */
    audioEncoder.prepareAudioEncoder(bitrate, samplerate, isStereo, maxInputSize);
    //start encoder
    audioEncoder.start();
    /*
     * send pcm buffer to encode.
     * pcmbuffer -> pcm buffer in bytes
     * offset -> normally 0. Indicate if you have any empty buffer on start of pcm buffer
     * size -> pcmbuffer size.
     */
    audioEncoder.inputPCMData(new Frame(pcmbuffer, offset, size));
    //stop encoder
    audioEncoder.stop();
```

**Comment by wolfheros** [comment]
hi, again. lets say I want to send the raw data to localhost (Stream on localhost) and play as a stream .  I set the url `rtsp://localhost:22445/app/test` then use `rtspClient.connect(url, false)` base on new api. but I got a error, like this:

- java.net.ConnectException: failed to connect to localhost/127.0.0.1 (port 22445) after 5000ms: isConnected failed: ECONNREFUSED (Connection refused)
        at libcore.io.IoBridge.isConnected(IoBridge.java:238)
        at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
        at libcore.io.IoBridge.connect(IoBridge.java:122)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
        at java.net.Socket.connect(Socket.java:882)
        at com.pedro.rtsp.rtsp.RtspClient$connect$$inlined$let$lambda$1.run(RtspClient.kt:162)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
        at libcore.io.IoBridge.isConnected(IoBridge.java:223)
        at libcore.io.IoBridge.connectErrno(IoBridge.java:171) 
        at libcore.io.IoBridge.connect(IoBridge.java:122) 
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183) 
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456) 
        at java.net.Socket.connect(Socket.java:882) 
        at com.pedro.rtsp.rtsp.RtspClient$connect$$inlined$let$lambda$1.run(RtspClient.kt:162) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
06-05 16:56:37.055 10006-10125/com.hassmedia.meto.tv E/APlayerActivity.kt: (APlayerActivity.kt:303).onConnectionFailedRtsp(): ****** Connection Failed :
     Error configure stream, failed to connect to localhost/127.0.0.1 (port 22445) after 5000ms: isConnected failed: ECONNREFUSED (Connection refused)

Did I misunderstand this post or what other thing should I do?

**Comment by pedroSG94** [comment]
The problem is IP (localhost).

You should use IP of your server because localhost is yourself not the
server

**Comment by wolfheros** [comment]
Thanks for you reply , Right now , I'm building a app on android, the data received from internet and the remote server send raw h264 data , I want covert it to a rtsp stream,  so I  can play it on a rtsp player like ffmeg.  cause I dont know how to play a raw h264 data directly , then come to this Idea. Feel free to any thing about , thanks

**Comment by pedroSG94** [comment]
You need a media server, send raw h264 data to that server using my library and get stream from that server using a player.

If you only want reproduce video data in your device and send that data to other device is not mandatory. Your best option is decode it in a surface. You have a decoder in this library but you need modify it to accept external data instead of use a mediaextractor:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/decoder/VideoDecoder.java

**Comment by wolfheros** [comment]
Like you said I need a Media Server to send raw h264 data, That's KIND of what I'm doing then got a Exception. Get data from other source then build a server on local device ( localhost with local port) feed it raw data, then play it with a player. Is that possible with using this library? any thoughts really helpful, and thanks

**Comment by pedroSG94** [comment]
No, it is not possible. In your case use a decoder is recommended.
I have a VideoDecoder in this project but It is used to decode a file using MediaExtractor. You need replace MediaExtractor with your raw data:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/decoder/VideoDecoder.java

In your case you need modify extract and decode method.
extract to set video configuration manually, and decode to accept an external buffer instead of get it from mediaextractor

**Comment by wolfheros** [comment]
That's too bad for me , anyway thanks a lot for taking so many question from me, it help a lot.
