### ISSUE TITLE
Using this server, you cannot pull streams

### ISSUE THREAD

**Issue by icewst** [pedroSG94/rtmp-rtsp-stream-client-java#547]
https://github.com/gwuhaolin/livego

Using this server, you cannot pull streams. But there are files saved on the server

**Comment by pedroSG94** [comment]
I was testing this server but I can't do it work with ffmpeg and ffplay.

**Comment by icewst** [comment]
tcUrl

**Comment by icewst** [comment]
Remove the trailing slash

Just normal
