### ISSUE TITLE
Fast switching between camera and file streaming

### ISSUE THREAD

**Issue by doma** [pedroSG94/rtmp-rtsp-stream-client-java#548]
Hi @pedroSG94,

Thanks for this great lib!

I'd like to switch between camera streaming and local file streaming (maybe looping) without any delays, reconnects, black screens. Is there an easy way to do this without deep code changes? Like camera preview and local file decode going into two opengl surfaces, and just switching the video encoder source between these two surfaces. Maybe your code can already do that.

Thanks!

**Comment by pedroSG94** [comment]
This is possible but you need a bit work(not allowed by default).
First of all you need use OpenGlView. Now, we need modify this method:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L321
The idea is adapt to it work with a VideoDecoder. To do it we need create a OffScreenGlThread like here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L303
Now, we need replace CameraManager with a VideoDecoder to switch render(lines 340 to 343):
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L340
This should be like this:
```java
videoDecoder = new VideoDecoder(i1, i2);
videoDecoder.initExtractor(fileSource);
videoDecoder.prepareVideo(offScreenGlThread.getSurface());
videoDecoder.start();
```
Remember that you need stop cameraManager before this and modify stopStream to stop videodecoder or camera manager depend what you are using

**Comment by doma** [comment]
Thanks!

**Comment by chiragsudani** [comment]
@pedroSG94 @doma Can you have this functionality in latest version?
If not can you share more details about his to implement
