### ISSUE TITLE
Reverse camera video display

### ISSUE THREAD

**Issue by rajapulau** [pedroSG94/rtmp-rtsp-stream-client-java#55]
My phone is Nexus 5x Android Oreo. I use rear camera and the display video is reverse to 180 but front camera is fine. how I to fix it ?

**Comment by pedroSG94** [comment]
In this line:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java#L104
Add this code:
```
if (!isFrontCamera) {
  orientation += 180;
}
```

**Comment by rajapulau** [comment]
what the issue @pedroSG94 ? I was add line code from you and the problem fixed in my nexus. but other device now video is reverse to 180. this is specific device or version android ?

**Comment by pedroSG94** [comment]
I think that is hardware bug of your device. I have that device in my office and I have that problem too. I recomend you add device model to the conditional.
https://stackoverflow.com/questions/1995439/get-android-phone-model-programmatically

**Comment by rajapulau** [comment]
Thanks pedro
