### ISSUE TITLE
Unexpected EOF reached before read buffer was filled.

### ISSUE THREAD

**Issue by vijayvvj** [pedroSG94/rtmp-rtsp-stream-client-java#550]
Hi Pedro Sánchez,
              I am developing a Streaming App in Ionic for which i am developing a Cordova Plugin by referencing your code. Every thing looks good. Encoders are working good. 
But, while connecting to Rtmp Server ( Youtube ) i am getting error "Unexpected EOF reached before read buffer was filled".

Digging Further into code.
PATH of issue.
connect(String url)  ->
handleRxPacketLoop() ->
rtmpDecoder.readPacket(inputStream) -->
RtmpHeader.readHeader(in, rtmpSessionInfo)-- >
Util.readBytesUntilFull(in, messageStreamIdBytes)  ->this throws Error.

 I'm new to android and Sockets. Can you please help me Fix this issue?

**Comment by pedroSG94** [comment]
Hi,
You have an error reading stream packet id necessary to create a packet and response to server.
Do you have this error always?
Can you share a logcat of your connection to know in which part of the connection it fails?
Also, if you can try with other network to discard internet problems.

**Comment by vijayvvj** [comment]
I fixed that issue, i think i just missed some code as well as internet issues.
But now i am having another issue now.
Video packets are sent for some time and then they only audio was sent.
Attached adb Logs
[logs.txt](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/4550062/logs.txt)
.

**Comment by pedroSG94** [comment]
Did you tried with my app example to discard problems with implementation?
Can you share example code used?
Which mode are you using? (camera1, camera2, display or from file)

**Comment by vijayvvj** [comment]
my implementation consists of only display.
it worked once got stream up and running for 26sec and then video data was not uploading.
up from 2nd use data was not going i'm getting the same logs every time as above only few frames of video(Dislpay) from then no video data was uploaded.

**Comment by pedroSG94** [comment]
Maybe your error is this:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/63
MediaProjectionManager API of android never render a frame if you are not doing something in your screen

**Comment by vijayvvj** [comment]
is it something like keepAliveTrick() in DisplayService.kt?

**Comment by vijayvvj** [comment]
worked like a charm.
can we add an overlay for stream with current implementation?
Thnq for such a awesome project and much greater support.

As you are expert in Android.
One last out of box question
i saw an application which is displaying entire mobile screen inside of the app's main activity/view.
and that to without asking permission for screen capture(media projection). 
If possible can you explain me how to achieve that?

**Comment by pedroSG94** [comment]
You can add an overlay with filters (necessary use opengl constructor in true): 
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L293
About your second question it is possible if you are recording only your own app because you can use canvas to get frames of your view like I'm doing in AndroidViewFilter:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/gl/render/filters/AndroidViewFilterRender.java

**Comment by vijayvvj** [comment]
Thnq so much for the Help.
