### ISSUE TITLE
RtmpDisplay orientation is always Portrait

### ISSUE THREAD

**Issue by abadoliverco** [pedroSG94/rtmp-rtsp-stream-client-java#551]
Hi @pedroSG94,

I tried the latest version and I found a bug in the orientation it always shows PORTRAIT mode when you're using RtmpDisplay, the previous version is not like this. Please let me know if I need to change something to fix the issue. 

Thank you!

**Comment by pedroSG94** [comment]
You are right, fixed. Thank for report!
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/725fc2faf280a177e34d4461f7c178d9f6f4801b

**Comment by abadoliverco** [comment]
thank you so much! :)
