### ISSUE TITLE
Is there a way to detect upload bandwidth of user

### ISSUE THREAD

**Issue by mynew-github-account** [pedroSG94/rtmp-rtsp-stream-client-java#552]
I know the concept of adaptive bitrate.
But is there a way to show actual bandwidth of user while streaming.

So I if goes below some bandwidth I can detect and tell user bandwidth is very low.

**Comment by pedroSG94** [comment]
If you means something similar to a speedtest to get max bandwidth. No with this library and I dont know any library for it

**Comment by mynew-github-account** [comment]
Can you tell what is your bitrate ??
HOw it get calculated

**Comment by pedroSG94** [comment]
I'm doing a sum of video and audio packets size every second
