### ISSUE TITLE
Difficulty using this library to write a flutter plugin

### ISSUE THREAD

**Issue by pinkfish** [pedroSG94/rtmp-rtsp-stream-client-java#554]
Writing a flutter plugin for rtmp and using this library to do the rtmp streaming, however flutter just gives you a surface or a surface texture, not a surfaceview.  I am not sure if I can just wrap the surface in a view and then put that into the activity then it will work? If I don't use the flutter surface I think it will incorrectly render flutter content on top of the activity.  Is there a way to get access to the byte stream being sent up to the cloud?  I cannot figure out where in the setup the data could be pulled out of the image reader and written into the encoder?

Thanks,
David.

**Comment by pedroSG94** [comment]
I don't know about flutter (I never use it) but maybe you can use OpenGlView because when you import this library you have this custom view and should be similar to use other class.

**Comment by pinkfish** [comment]
Ok, I got this working by pulling the Surface out of the code and deleting a lot of the code in camera2/camera2base to make a working system.  Pull that out and pushed that in the existing rendering in the camera plugin and hey presto, works nicely.  Thanks!
