### ISSUE TITLE
Stream all video file types

### ISSUE THREAD

**Issue by MohammadRezaei92** [pedroSG94/rtmp-rtsp-stream-client-java#555]
I know that this library only supports mp4, webp, and h264 videos but, what do you suggest if I want to support all video formats? 
Is convert video type is a correct way? 
What is the best library to convert videos for android?

**Comment by pedroSG94** [comment]
If you want use this library the only way is convert video format. I only know ffmpeg, Maybe you can use javacv (wrapper of ffmpeg for android) for it:
Example (not tested):
https://stackoverflow.com/questions/57259495/how-to-convert-video-to-mp4-javacv
LIbrary:
https://github.com/bytedeco/javacv
