### ISSUE TITLE
Output stream resolution

### ISSUE THREAD

**Issue by Dimitri330** [pedroSG94/rtmp-rtsp-stream-client-java#556]
Hi! 
Is it possible to change output stream resolution before video sending to server? I prepared video with resolution available for camera, but in output want scale to one resolution, for example: camera support 480x640 or 720x1280 but output 540x960 in ratio 9:16.
best regards

**Comment by pedroSG94** [comment]
This is possible but no by default you need modify library for it (obviously I means about rescaled resolution and could produce pixelation). You need use OpenGlView and change:

VideoEncoder and CameraApiManager resolution to select a different resolution. 
After that you need change render viewport and matrix to rescale resolution:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/utils/gl/SizeCalculator.java
