### ISSUE TITLE
Text getting blur 

### ISSUE THREAD

**Issue by mynew-github-account** [pedroSG94/rtmp-rtsp-stream-client-java#557]
I am using rtmpdisplay to stream in 720p  but still while streaming text getting blur.
Can you suggest any setting to make text clear?

**Comment by AlexUrrutia** [comment]
increase bitrate maybe?

**Comment by mynew-github-account** [comment]
I tried ,
I am using prepareVideo(1280, 720, 30, 2500 * 1024, 0, 320) 
but still it produce blur text.

**Comment by mynew-github-account** [comment]
I think this is definitely about aspect ratio. 

While camera capture could be 16x9, screen dimensions are not going to be 16x9 on most phones. On my phone, natural screen dimensions are 2220x1080. So the captured screen video from my phone should have been 1480x720. But the it is 1280x720.

I guess if we maintain the screen aspect ratio then output quality will be better.

So can you suggest how can I achieve this??

**Comment by pedroSG94** [comment]
A solution could be use AndroidViewFilter with a TextView instead of Text filter. I will check it with multiple resolution to know if this is related

**Comment by mynew-github-account** [comment]
Hey maybe I explained it wrong not text filter getting blur but all the text like a name of other apps, notification text all other text on phone getting blur while streaming in screen share

**Comment by pedroSG94** [comment]
Try increase video bitrate and dpi using this value:
https://developer.android.com/reference/android/util/DisplayMetrics#densityDpi

**Comment by mynew-github-account** [comment]
do you know how to add black border while encoding video to make it 16:9 if it's not in ratio

So basically I want to capture screen with the highest resolution supported by mobile but the server can handle only 16:9 aspect ratio
so is there any way to added black padding while encoding itself to make is 16:9.

**Comment by pedroSG94** [comment]
This is possible but I need modify so much things in the library. I'm trying fix this without use 16:9 aspect ratio

**Comment by mynew-github-account** [comment]
If you know such a library or method I can try it.
You can suggest it.

**Comment by pedroSG94** [comment]
This is producing several problems for keep compatibility with SurfaceView and TextureView.
Draw different resolution in preview and output is only possible with OpenGlView.

I'm really wondering to remove support for SurfaceView and TextureView (The only problem is lose support for API 16 and 17) because I'm having problems to add new features related to this.

**Comment by mynew-github-account** [comment]
How to do it in OpenGL view 
Anyway I am using only OpenGL view

**Comment by pedroSG94** [comment]
This could be difficult.

You should select your output resolution in [VideoEncoder](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L72) to be different from CameraApiManager.
After that, you need modify glViewPort and Matrix to get a proper scale in output:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/utils/gl/SizeCalculator.java
