### ISSUE TITLE
SurfaceFilterRender only plays the audio, the image does not appear

### ISSUE THREAD

**Issue by Racker79** [pedroSG94/rtmp-rtsp-stream-client-java#558]
The video does not play when I use surfaceFilterRender, only the audio plays, the video screen appears black. I have tried with MediaPlayer and ExoPlayer.

rtspServerCamera2!!.getGlInterface().setFilter(surfaceFilterRender)
val player = SimpleExoPlayer.Builder(this).build()      player.setVideoSurface(surfaceFilterRender.surface)
val dataSourceFactory: DataSource.Factory = DefaultDataSourceFactory(
          this,
          Util.getUserAgent(this, "ExoPlayerDemo")
        )
        val uri: Uri = Uri.parse("http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4")
        val videoSource: MediaSource = ProgressiveMediaSource.Factory(dataSourceFactory)
          .createMediaSource(Uri.fromFile(File(folder.absolutePath + "/20200503_222914.mp4")))
        player.prepare(videoSource)
        player.playWhenReady = true

Thanks

**Comment by pedroSG94** [comment]
Did you try wait until surface is ready to draw using this callback?
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/gl/render/filters/object/SurfaceFilterRender.java#L62

Also check if app example if working for you.

**Comment by mhoyosga** [comment]
In the example it doesn't work either, can it be due to the model of the mobile? I am testing with a LG G4 and a motorola E4.

**Comment by pedroSG94** [comment]
Did you try with callback?
```java
//create a variable to avoid initialization problems
private SurfaceFilterRender surfaceFilterRender = null; 

surfaceFilterRender = new SurfaceFilterRender(new SurfaceFilterRender.SurfaceReadyCallback() {
              @Override
              public void surfaceReady() {
                if (surfaceFilterRender != null) {
                  MediaPlayer mediaPlayer = MediaPlayer.create(OpenGlRtmpActivity.this, R.raw.big_bunny_240p);
                  mediaPlayer.setSurface(surfaceFilterRender.getSurface());
                  mediaPlayer.start();
                }
              }
            });
        rtmpCamera1.getGlInterface().setFilter(surfaceFilterRender);
        //Video is 360x240 so select a percent to keep aspect ratio (50% x 33.3% screen)
        surfaceFilterRender.setScale(50f, 33.3f);
        spriteGestureController.setBaseObjectFilterRender(surfaceFilterRender); //Optional
```
Make sure that callback is called

**Comment by mhoyosga** [comment]
Ok, Thanks!!!

Great Work!!!

**Comment by mhoyosga** [comment]
Another thing that has happened to me and that I imagine will have a similar solution is that when I take a photo, on many occasions, it appears in black. I imagine that the Frame will not be ready, could I add a listener to wait for the surface to be ready?

    fun capturePhotoAndSend(rtspcam2: RtspServerCamera2?) {
        rtspcam2!!.glInterface.takePhoto(object : TakePhotoCallback {
            override fun onTakePhoto(bitmap: Bitmap) {
                saveImage(bitmap)
            }
        })
    }

**Comment by pedroSG94** [comment]
Your code seems fine.
I think this is a bug. I will test it

**Comment by mhoyosga** [comment]
Ok, Thanks!!!

**Comment by pedroSG94** [comment]
I did a fix for it:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/ed2ad3f3a17b3b099f8dab5c5b8fb71eca3a40a9
The error was that your first photo is always black.
