### ISSUE TITLE
stop stream

### ISSUE THREAD

**Issue by liodali** [pedroSG94/rtmp-rtsp-stream-client-java#56]
when i stop the streaming (i use nginx to stream)
i get this error 
E/AndroidRuntime: FATAL EXCEPTION: Thread-1518
                                                          java.lang.NullPointerException
                                                              at com.pedro.encoder.video.VideoEncoder$1.run(VideoEncoder.java:244)
                                                              at java.lang.Thread.run(Thread.java:841)

**Comment by pedroSG94** [comment]
Are you using my app? What activity?
Project clone or gradle?

**Comment by liodali** [comment]
no, i integrate your library to make streaming from my phone

**Comment by pedroSG94** [comment]
This line:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L248
Or this?:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L265
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L269

Lines 265 and 269 should be totally imposible.
I will add a null check on line 248 and upgrade library version in gradle.

**Comment by liodali** [comment]
thanks for all #pedro

**Comment by pedroSG94** [comment]
This look solved. Closing issue.
