### ISSUE TITLE
There is almost always a black photo on takePhoto

### ISSUE THREAD

**Issue by Racker79** [pedroSG94/rtmp-rtsp-stream-client-java#561]
Another thing that has happened to me and that I imagine will have a similar solution is that when I take a photo, on many occasions, it appears in black. I imagine that the Frame will not be ready, could I add a listener to wait for the surface to be ready?

fun capturePhotoAndSend(rtspcam2: RtspServerCamera2?) {
    rtspcam2!!.glInterface.takePhoto(object : TakePhotoCallback {
        override fun onTakePhoto(bitmap: Bitmap) {
            saveImage(bitmap)
        }
    })
}

**Comment by pedroSG94** [comment]
Your code seems fine.
I think this is a bug. I will test it

**Comment by huongvu1397** [comment]
I have same issue :(

**Comment by mhoyosga** [comment]
Hi.

This bug must be related to the api version.

In my case it works with Android 6, however, it does not work with Android
9.

A greeting

**Comment by pedroSG94** [comment]
I thought this was solved here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/ed2ad3f3a17b3b099f8dab5c5b8fb71eca3a40a9
I will test it again. Can you tell me mode used? (display, camera1, camera2, etc) and if you are using an openglview or not (background mode)

**Comment by huongvu1397** [comment]
When I used version 1.7.8 ,sometimes  can take pictures but sometimes it was still black, but when I used version 1.8.3 everything was black.

```
rtmpDisplay?.glInterface?.takePhoto {
                    if (it != null) {
                        saveImage(it)
                        Log.e("HVV1312", "take screen shot complete!")
                    }
                }
```

This image when i using version 1.7.8 to takePhoto()

![image](https://user-images.githubusercontent.com/39198328/84978476-32286280-b157-11ea-9bc3-9aafec23d866.png)

**Comment by huongvu1397** [comment]
![image](https://user-images.githubusercontent.com/39198328/85914791-ac4d9b00-b86b-11ea-9a22-119788e6b97a.png)
When I read this issue and change the code, I could capture images with bitmap.

```
 ...
 try {
      while (running) {
       
        if (frameAvailable) {
          ...

          surfaceManager.swapBuffer();

//          if (takePhotoCallback != null) {
//            takePhotoCallback.onTakePhoto(
//                GlUtil.getBitmap(encoderWidth, encoderHeight, encoderWidth, encoderHeight));
//            takePhotoCallback = null;
//          }


          synchronized (sync) {
            if (surfaceManagerEncoder != null && !fpsLimiter.limitFPS()) {
              surfaceManagerEncoder.makeCurrent();
              textureManager.drawScreen(encoderWidth, encoderHeight, false, 0, streamRotation,
                  false);
              surfaceManagerEncoder.swapBuffer();

              if (takePhotoCallback != null) {
                takePhotoCallback.onTakePhoto(
                        GlUtil.getBitmap(encoderWidth, encoderHeight, encoderWidth, encoderHeight));
                takePhotoCallback = null;
              }

            }
          }

          ...

    }
```
