### ISSUE TITLE
Support for Horizontal Camera and Pinch Zoom in and Out

### ISSUE THREAD

**Issue by sraja415** [pedroSG94/rtmp-rtsp-stream-client-java#564]
Your app is a life saver. Been looking for it everywhere. It will be great to have Horizontal Camera Live Stream and Pinch to Zoom in and Out functionality.

**Comment by AlexUrrutia** [comment]
I’ve asked for that feature too, horizontal stream while device is in portrait mode, it’ll be great to have that no matter if it’s a little bit cropped 🙂

**Comment by sraja415** [comment]
My issue has been solved. My bad...it is in settings of app for changing orientation. Works. 

**But changing orientation Stops Live Stream. (THIS IS A BUG)**

Pinch to Zoom and Zoom Out is available

https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Camera1Base#startstream
