### ISSUE TITLE
Why audio permission is always required

### ISSUE THREAD

**Issue by svprdga** [pedroSG94/rtmp-rtsp-stream-client-java#571]
I found that for the library to correctly work the app must have the audio permission granted. 

It would be nice that the library only use audio related features in the case that the streaming is going to have audio input.

**Comment by marinesco** [comment]
But it's very strange case when you're streaming without any sound О_о

**Comment by svprdga** [comment]
I think that there are a few use cases in which is not strange at all streaming without sound, imagine for instance that you want to do a presentation of your new android app and all you want to show is the screen of your device. No sound involved, hence, I think that the sound permission should only be needed when the streaming has audio enabled.

**Comment by sergeych** [comment]
Strange. I have upgraded to new release that should work with no audio permission, but now  RTMP does not work without prepareAudio() at all.
```
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaCodec.start()' on a null object reference
        at com.pedro.encoder.audio.AudioEncoder.start(AudioEncoder.java:79)
        at com.pedro.encoder.BaseEncoder.start(BaseEncoder.java:25)
        at com.pedro.rtplibrary.base.Camera1Base.startEncoders(Camera1Base.java:490)
        at com.pedro.rtplibrary.base.Camera1Base.startStream(Camera1Base.java:480)
```
- 1.8.5.

**Comment by pedroSG94** [comment]
This change was only for display mode. In camera1 and camera2 audio is necessary. I basically merged PR that only included display mode.
I will implement it in the next version if you need it.
