### ISSUE TITLE
Display stream with internal audio crash

### ISSUE THREAD

**Issue by svprdga** [pedroSG94/rtmp-rtsp-stream-client-java#572]
I have a Samsung Galaxy A3, when I try to perform a streaming of my display the app crashes with the following output:

> 2020-05-18 16:59:00.228 20164-20164/com.svprdga.screenshare E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.svprdga.screenshare, PID: 20164
>     java.lang.NoClassDefFoundError: Failed resolution of: Landroid/media/AudioPlaybackCaptureConfiguration$Builder;
>         at com.pedro.rtplibrary.base.DisplayBase.prepareInternalAudio(DisplayBase.java:171)
>         at com.svprdga.screenshare.presentation.ui.service.StreamService.startScreencast(StreamService.kt:167)
>         at com.svprdga.screenshare.presentation.ui.service.StreamService.onStartCommand(StreamService.kt:133)
>         at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3679)
>         at android.app.ActivityThread.-wrap21(Unknown Source:0)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1801)
>         at android.os.Handler.dispatchMessage(Handler.java:105)
>         at android.os.Looper.loop(Looper.java:164)
>         at android.app.ActivityThread.main(ActivityThread.java:6944)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
>      Caused by: java.lang.ClassNotFoundException: Didn't find class "android.media.AudioPlaybackCaptureConfiguration$Builder" on path: DexPathList[[zip file "/data/app/com.svprdga.screenshare-WGc_egbbXqh6QkizZsAmXw==/base.apk"],nativeLibraryDirectories=[/data/app/com.svprdga.screenshare-WGc_egbbXqh6QkizZsAmXw==/lib/arm, /system/lib, /system/vendor/lib]]
>         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

**Comment by marinesco** [comment]
Did you notice that prepareInternalAudio function has **@RequiresApi(api = Build.VERSION_CODES.Q)** annotation? 
Which Android version your device uses?

**Comment by svprdga** [comment]
True, I didn't saw it and I don't know why Android Studio was letting me use that method if it's annotated.
