### ISSUE TITLE
Stream preview Doesnot include Texture View

### ISSUE THREAD

**Issue by vijayvvj** [pedroSG94/rtmp-rtsp-stream-client-java#573]
Hi Pedro Sánchez,
           i have a View with some ImageView's and TextureView for Camera2Api preview. using [AndroidViewFilterRender.java](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/gl/render/filters/AndroidViewFilterRender.java)
i get canvas and post it to VideoEncoder Surface.
final stream output contains images but TextureView is missing.

can you please help me on this?

**Comment by vijayvvj** [comment]
And also i'm getting this issue in logs "annexb not match."

**Comment by pedroSG94** [comment]
Unfortunately, your problem with TextureView is not an error.
TextureView and SurfaceView use SurfaceTexture and Surface respectively so you can get a canvas from it.
About annexb not match. It is only informative log (I should change log type).
Do you have a problem with video? 
Can you test if you are producing keyframes? (write a logcat here to know it):
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/net/ossrs/rtmp/SrsFlvMuxer.java#L934

**Comment by vijayvvj** [comment]
is there any way i can preview camera without TextureView or SurfaceView. Which can be drawn to canvas?

**Comment by vijayvvj** [comment]
Hi Pedro,

Regarding TextureView not showing on Stream. 
I'm actually showing preview to user in my activity with this textureView. and i am using canvas to draw this to Video Encoder Surface.
issue Im facing here is i am getting the preview when app in foreground. when app goes background i am not getting any preview. 
any idea on how to fix this.

**Comment by pedroSG94** [comment]
If you need show a TextureView you can replace it with SurfaceFilter and draw in that filter instead of TextureView:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L261

**Comment by vijayvvj** [comment]
Just to be sure before starting implementation.
by using opengl instead of textureview.
my preview will not stop even if app goes to background(this is where im having issue)

**Comment by pedroSG94** [comment]
Yes, you can avoid that problem if you set a background render using this method:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/backgroundexample/RtpService.kt#L83

I recommend you check this example to know how to implement it:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/master/app/src/main/java/com/pedro/rtpstreamer/backgroundexample

Basically when you go to background your view is destroyed (android life cycle) for this reason you can't render anything and your preview stop. After that, if you go to foreground you are creating a new view but you refer to old view (already destroyed) so you lose preview.

With this implementation you replace your view with a background render when you go to background and when you go to foreground, after create your new view, you are attaching this view rendering it.

**Comment by vijayvvj** [comment]
Thnq For the help
