### ISSUE TITLE
Crash - Camera id 1 does not match any currently connected camera device

### ISSUE THREAD

**Issue by marcin-adamczewski** [pedroSG94/rtmp-rtsp-stream-client-java#575]
Hello @pedroSG94 ,

We have some crashes with the following message:
`Camera id 1 does not match any currently connected camera device`
This is the stacktrace
`
- android.hardware.camera2.CameraManager.getCameraCharacteristics (CameraManager.java:222)
- com.pedro.encoder.input.video.Camera2ApiManager.getCameraResolutionsFront (Camera2ApiManager.java:223)
- com.pedro.rtplibrary.base.Camera2Base.getResolutionsFront (Camera2Base.java:586)
`

I guess we shouldn't depend on hardcoded camera ids like "0" and "1", but rather on  `cameraManager.getCameraIdList()` as there may be many cameras.

I'll try to prepare PR for that.

**Comment by marcin-adamczewski** [comment]
@pedroSG94 Here it is https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/pull/576

**Comment by pedroSG94** [comment]
Thank for your PR. Merged
