### ISSUE TITLE
SocketException ignored when sending packets

### ISSUE THREAD

**Issue by marcin-adamczewski** [pedroSG94/rtmp-rtsp-stream-client-java#579]
Hi @pedroSG94 ,

I have an issue that when I get out of the WiFi range while streaming then I don't get any error. Packets are being sent all the time though, however, every time the SocketException is raised. It's happening here https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L475
The exception is with the following message:
`java.net.SocketException: Broken pipe`
So probably the server already disconnected but RtmpConnection is constantly sending packets to the void :)

Is there any reason for this error to be ignored?
If not, then I've added PR that allows handling this error as connection error so we are able to use retry logic and we'll get an error message.
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/pull/578

PS I don't know if this also concerns RTSP as I can't find such an exception there.
PS 2 I could reproduce it on 3 devices, however, on OnePlus 6T it was disconnecting right away after leaving WiFi range.

**Comment by pedroSG94** [comment]
This is a bug. Thank for PR.
Maybe I forgot to remove it in the last code refactor.
