### ISSUE TITLE
Streamed video not visible

### ISSUE THREAD

**Issue by raj9686** [pedroSG94/rtmp-rtsp-stream-client-java#58]
> if (rtmpCamera1.prepareAudio() && rtmpCamera1.prepareVideo(720, 480, 30, 600000, false, 90)) {
                etUrl.setText(random);
                rtmpCamera1.startStream("URL");
                rtmpCamera1.switchCamera();
                for (String s : rtmpCamera1.getResolutions()) {
                    Log.e(TAG, "onClick: " + s);
                }
            } else {
                Toast.makeText(this, "Error preparing stream, This device cant do it", Toast.LENGTH_SHORT).show();
>            }

I can not see the video at player I used `ijkplayer `to stream but it not working if I stream from android 7.1.1 device.

Is there any one who can help me please.

**Comment by pedroSG94** [comment]
Android version isn't the problem. I use a device with that version.
I need know:
1) Log when you start the stream.
2) Device model.
3) Media server used.
4) If you get the stream with VLC, Is it working?
5) If you do a stream with ffmpeg, Is it working?

**Comment by raj9686** [comment]
09-28 18:28:24.845 7579-7579/com.atologist.stramvideo I/ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
09-28 18:28:24.942 7579-7579/com.atologist.stramvideo I/ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
09-28 18:28:24.945 7579-7579/com.atologist.stramvideo I/AudioManagerEx: AudioManagerEx created
09-28 18:28:25.164 7579-7579/com.atologist.stramvideo E/ExampleRtmpActivity: onClick: 1280X960
09-28 18:28:25.165 7579-7579/com.atologist.stramvideo E/ExampleRtmpActivity: onClick: 1280X720
09-28 18:28:25.165 7579-7579/com.atologist.stramvideo E/ExampleRtmpActivity: onClick: 1280X688
09-28 18:28:25.165 7579-7579/com.atologist.stramvideo E/ExampleRtmpActivity: onClick: 960X720
09-28 18:28:25.165 7579-7579/com.atologist.stramvideo E/ExampleRtmpActivity: onClick: 880X720
09-28 18:28:25.165 7579-7579/com.atologist.stramvideo E/ExampleRtmpActivity: onClick: 720X480
09-28 18:28:25.165 7579-7579/com.atologist.stramvideo E/ExampleRtmpActivity: onClick: 640X480
09-28 18:28:25.165 7579-7579/com.atologist.stramvideo E/ExampleRtmpActivity: onClick: 480X640
09-28 18:28:25.165 7579-7579/com.atologist.stramvideo E/ExampleRtmpActivity: onClick: rotation :0
09-28 18:28:25.171 7579-7579/com.atologist.stramvideo D/AudioRecord: getMinFrameCount 1776
09-28 18:28:25.172 7579-7579/com.atologist.stramvideo D/AudioRecord: set(): inputSource 0, sampleRate 44100, format 0x1, channelMask 0xc, frameCount 8192, notificationFrames 0, sessionId 0, transferType 0, flags 0, opPackageName com.atologist.stramvideo uid -1, pid -1
09-28 18:28:25.173 7579-7579/com.atologist.stramvideo D/AudioRecord: set: Create AudioRecordThread
09-28 18:28:25.185 7579-7579/com.atologist.stramvideo I/MicrophoneManager: Microphone created, 44100hz, Stereo
09-28 18:28:25.185 7579-7579/com.atologist.stramvideo I/MicrophoneManager: Microphone created, 44100hz, Stereo
09-28 18:28:25.186 7579-7579/com.atologist.stramvideo D/MediaCodec: Mediacodec create pid=7579
09-28 18:28:25.192 7579-7579/com.atologist.stramvideo I/ACodec: Now uninitialized
09-28 18:28:25.195 7579-7719/com.atologist.stramvideo I/ACodec: onAllocateComponent
09-28 18:28:25.197 7579-7719/com.atologist.stramvideo I/OMXClient: MuxOMX ctor
09-28 18:28:25.204 7579-7719/com.atologist.stramvideo I/ACodec: [OMX.google.aac.encoder] Now Loaded
09-28 18:28:25.212 7579-7579/com.atologist.stramvideo W/AudioCapabilities: Unsupported mime audio/x-lg-alac
09-28 18:28:25.215 7579-7579/com.atologist.stramvideo W/AudioCapabilities: Unsupported mime audio/x-lg-flac
09-28 18:28:25.216 7579-7579/com.atologist.stramvideo W/AudioCapabilities: Unsupported mime audio/adpcm
09-28 18:28:25.218 7579-7579/com.atologist.stramvideo W/AudioCapabilities: Unsupported mime audio/g726
09-28 18:28:25.220 7579-7579/com.atologist.stramvideo W/AudioCapabilities: Unsupported mime audio/lg-wma-voice
09-28 18:28:25.221 7579-7579/com.atologist.stramvideo W/AudioCapabilities: Unsupported mime audio/x-lg-ms-wma
09-28 18:28:25.224 7579-7579/com.atologist.stramvideo W/VideoCapabilities: Unsupported mime video/mjpg
09-28 18:28:25.228 7579-7579/com.atologist.stramvideo W/VideoCapabilities: Unsupported mime video/theora
09-28 18:28:25.232 7579-7579/com.atologist.stramvideo W/AudioCapabilities: Unsupported mime audio/mp4a-adts-1seg
09-28 18:28:25.234 7579-7579/com.atologist.stramvideo W/AudioCapabilities: Unsupported mime audio/mp4a-latm-1seg
09-28 18:28:25.264 7579-7579/com.atologist.stramvideo W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
09-28 18:28:25.264 7579-7579/com.atologist.stramvideo W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
09-28 18:28:25.280 7579-7579/com.atologist.stramvideo W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
09-28 18:28:25.280 7579-7579/com.atologist.stramvideo W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
09-28 18:28:25.298 7579-7579/com.atologist.stramvideo W/VideoCapabilities: Unsupported mime video/mp4v-esdp
09-28 18:28:25.311 7579-7579/com.atologist.stramvideo W/VideoCapabilities: Unsupported mime video/mp4v-esdp
09-28 18:28:25.327 7579-7579/com.atologist.stramvideo W/Utils: could not parse long range '35-34'
09-28 18:28:25.350 7579-7579/com.atologist.stramvideo I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
09-28 18:28:25.359 7579-7579/com.atologist.stramvideo I/VideoEncoder: videoEncoder OMX.qcom.video.encoder.avc type supported: video/avc
09-28 18:28:25.359 7579-7579/com.atologist.stramvideo W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
09-28 18:28:25.359 7579-7579/com.atologist.stramvideo W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
09-28 18:28:25.362 7579-7579/com.atologist.stramvideo I/VideoEncoder: Color supported: 2141391876
09-28 18:28:25.362 7579-7579/com.atologist.stramvideo I/VideoEncoder: Color supported: 2130708361
09-28 18:28:25.362 7579-7579/com.atologist.stramvideo I/VideoEncoder: Color supported: 2135033992
09-28 18:28:25.362 7579-7579/com.atologist.stramvideo I/VideoEncoder: Color supported: 21
09-28 18:28:25.363 7579-7579/com.atologist.stramvideo D/MediaCodec: Mediacodec create pid=7579
09-28 18:28:25.363 7579-7579/com.atologist.stramvideo I/ACodec: Now uninitialized
09-28 18:28:25.365 7579-7727/com.atologist.stramvideo I/ACodec: onAllocateComponent
09-28 18:28:25.367 7579-7727/com.atologist.stramvideo I/OMXClient: MuxOMX ctor
09-28 18:28:25.386 7579-7727/com.atologist.stramvideo I/ACodec: [OMX.qcom.video.encoder.avc] Now Loaded
09-28 18:28:25.387 7579-7579/com.atologist.stramvideo W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
09-28 18:28:25.387 7579-7579/com.atologist.stramvideo W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
09-28 18:28:25.391 7579-7727/com.atologist.stramvideo E/ACodec: [OMX.qcom.video.encoder.avc] storeMetaDataInBuffers (output) failed w/ err -1010
09-28 18:28:25.391 7579-7727/com.atologist.stramvideo I/ExtendedACodec: setupVideoEncoder()
09-28 18:28:25.392 7579-7727/com.atologist.stramvideo W/ACodec: do not know color format 0x7fa30c04 = 2141391876
09-28 18:28:25.393 7579-7727/com.atologist.stramvideo W/ACodec: do not know color format 0x7f000789 = 2130708361
09-28 18:28:25.404 7579-7727/com.atologist.stramvideo I/ACodec: bitrateMode = 1
09-28 18:28:25.407 7579-7727/com.atologist.stramvideo I/ACodec: [OMX.qcom.video.encoder.avc] cannot encode HDR static metadata. Ignoring.
09-28 18:28:25.407 7579-7727/com.atologist.stramvideo I/ACodec: setupVideoEncoder succeeded
09-28 18:28:25.408 7579-7727/com.atologist.stramvideo I/ExtendedACodec: [OMX.qcom.video.encoder.avc] configure, AMessage : AMessage(what = 'conf', target = 4) = {
                                                                          int32_t width = 480
                                                                          int32_t height = 720
                                                                          int32_t bitrate = 600000
                                                                          int32_t max-input-size = 0
                                                                          string mime = "video/avc"
                                                                          int32_t frame-rate = 30
                                                                          int32_t i-frame-interval = 2
                                                                          int32_t color-format = 21
                                                                          int32_t encoder = 1
                                                                        }
09-28 18:28:25.489 7579-7727/com.atologist.stramvideo I/ACodec: [OMX.qcom.video.encoder.avc] Now Loaded->Idle
09-28 18:28:25.490 7579-7733/com.atologist.stramvideo I/SrsFlvMuxer: worker: connecting to RTMP server by url=rtmp://198.15.82.37/live/956
09-28 18:28:25.491 7579-7733/com.atologist.stramvideo D/RtmpConnection: connect() called. Host: 198.15.82.37, port: 1935, appName: live, publishPath: 956
09-28 18:28:25.502 7579-7727/com.atologist.stramvideo I/ACodec: [OMX.qcom.video.encoder.avc] Now Idle->Executing
09-28 18:28:25.503 7579-7727/com.atologist.stramvideo I/ACodec: [OMX.qcom.video.encoder.avc] Now Executing
09-28 18:28:25.505 7579-7719/com.atologist.stramvideo I/ACodec: [OMX.google.aac.encoder] Now Loaded->Idle
09-28 18:28:25.510 7579-7719/com.atologist.stramvideo I/ACodec: [OMX.google.aac.encoder] Now Idle->Executing
09-28 18:28:25.512 7579-7719/com.atologist.stramvideo I/ACodec: [OMX.google.aac.encoder] Now Executing
09-28 18:28:25.512 7579-7579/com.atologist.stramvideo I/AudioEncoder: AudioEncoder started
09-28 18:28:25.626 7579-7579/com.atologist.stramvideo I/Camera1ApiManager: 720X480
09-28 18:28:25.641 7579-7579/com.atologist.stramvideo I/MicrophoneManager: Microphone started
09-28 18:28:25.791 7579-7733/com.atologist.stramvideo D/RtmpConnection: connect(): socket connection established, doing handhake...
09-28 18:28:25.791 7579-7733/com.atologist.stramvideo D/Handshake: writeC0
09-28 18:28:25.792 7579-7733/com.atologist.stramvideo D/Handshake: writeC1
09-28 18:28:25.792 7579-7733/com.atologist.stramvideo D/Handshake: writeC1(): Calculating digest offset
09-28 18:28:25.792 7579-7733/com.atologist.stramvideo D/Handshake: writeC1(): (real value of) digestOffset: 392
09-28 18:28:25.792 7579-7733/com.atologist.stramvideo D/Handshake: writeC1(): recalculated digestOffset: 1168
09-28 18:28:25.792 7579-7733/com.atologist.stramvideo D/Handshake: writeC1(): digestOffsetBytes: 000089FF
09-28 18:28:25.792 7579-7733/com.atologist.stramvideo D/Handshake: partBeforeDigest(): size: 1168
09-28 18:28:25.793 7579-7733/com.atologist.stramvideo D/Handshake: writeC1(): Writing timestamp and Flash Player version
09-28 18:28:25.793 7579-7733/com.atologist.stramvideo D/Handshake: partAfterDigest(): size: 336
09-28 18:28:25.793 7579-7733/com.atologist.stramvideo D/Handshake: copying digest offset bytes in partBeforeDigest
09-28 18:28:25.793 7579-7733/com.atologist.stramvideo D/Handshake: writeC1(): Calculating digest
09-28 18:28:25.795 7579-7733/com.atologist.stramvideo D/Handshake: writeC1(): writing C1 packet
09-28 18:28:25.795 7579-7733/com.atologist.stramvideo D/Handshake: readS0
09-28 18:28:26.087 7579-7733/com.atologist.stramvideo D/Handshake: readS1
09-28 18:28:26.087 7579-7733/com.atologist.stramvideo D/Handshake: readS1(): S1 total bytes read OK
09-28 18:28:26.087 7579-7733/com.atologist.stramvideo D/Handshake: readC2
09-28 18:28:26.087 7579-7733/com.atologist.stramvideo D/Handshake: readS2
09-28 18:28:26.464 7579-7733/com.atologist.stramvideo D/Handshake: readS2(): S2 total bytes read OK
09-28 18:28:26.464 7579-7733/com.atologist.stramvideo D/RtmpConnection: connect(): handshake done
09-28 18:28:26.465 7579-7733/com.atologist.stramvideo D/RtmpConnection: rtmpConnect(): Building 'connect' invoke packet
09-28 18:28:26.465 7579-7833/com.atologist.stramvideo D/RtmpConnection: starting main rx handler loop
09-28 18:28:26.469 7579-7733/com.atologist.stramvideo D/RtmpConnection: wrote packet: RTMP Command (command: connect, transaction ID: 1), size: 265
09-28 18:28:26.629 7579-7579/com.atologist.stramvideo I/Camera1ApiManager: 720X480
09-28 18:28:26.638 7579-7579/com.atologist.stramvideo E/ExampleRtmpActivity: onClick: 1280X960
09-28 18:28:26.638 7579-7579/com.atologist.stramvideo E/ExampleRtmpActivity: onClick: 1280X720
09-28 18:28:26.638 7579-7579/com.atologist.stramvideo E/ExampleRtmpActivity: onClick: 1280X688
09-28 18:28:26.638 7579-7579/com.atologist.stramvideo E/ExampleRtmpActivity: onClick: 960X720
09-28 18:28:26.638 7579-7579/com.atologist.stramvideo E/ExampleRtmpActivity: onClick: 880X720
09-28 18:28:26.638 7579-7579/com.atologist.stramvideo E/ExampleRtmpActivity: onClick: 720X480
09-28 18:28:26.638 7579-7579/com.atologist.stramvideo E/ExampleRtmpActivity: onClick: 640X480
09-28 18:28:26.638 7579-7579/com.atologist.stramvideo E/ExampleRtmpActivity: onClick: 480X640
09-28 18:28:26.639 7579-7579/com.atologist.stramvideo I/Choreographer: Skipped 101 frames!  The application may be doing too much work on its main thread.
09-28 18:28:26.650 7579-7778/com.atologist.stramvideo I/SrsFlvMuxer: frame discarded
09-28 18:28:26.689 7579-7778/com.atologist.stramvideo I/SrsFlvMuxer: frame discarded
09-28 18:28:26.708 7579-7778/com.atologist.stramvideo I/SrsFlvMuxer: frame discarded
09-28 18:28:26.728 7579-7778/com.atologist.stramvideo I/SrsFlvMuxer: frame discarded
09-28 18:28:26.750 7579-7778/com.atologist.stramvideo I/SrsFlvMuxer: frame discarded
09-28 18:28:26.762 7579-7833/com.atologist.stramvideo D/RtmpConnection: handleRxPacketLoop(): Setting acknowledgement window size: 5000000
09-28 18:28:26.789 7579-7778/com.atologist.stramvideo I/SrsFlvMuxer: frame discarded
09-28 18:28:26.793 7579-7778/com.atologist.stramvideo I/SrsFlvMuxer: frame discarded
09-28 18:28:26.842 7579-7778/com.atologist.stramvideo I/SrsFlvMuxer: frame discarded
09-28 18:28:26.862 7579-7778/com.atologist.stramvideo I/SrsFlvMuxer: frame discarded
09-28 18:28:26.878 7579-7778/com.atologist.stramvideo I/SrsFlvMuxer: frame discarded
09-28 18:28:26.902 7579-7778/com.atologist.stramvideo I/SrsFlvMuxer: frame discarded
09-28 18:28:26.918 7579-7778/com.atologist.stramvideo I/SrsFlvMuxer: frame discarded
09-28 18:28:26.965 7579-7778/com.atologist.stramvideo I/SrsFlvMuxer: frame discarded
09-28 18:28:26.984 7579-7778/com.atologist.stramvideo I/SrsFlvMuxer: frame discarded
09-28 18:28:27.000 7579-7778/com.atologist.stramvideo I/SrsFlvMuxer: frame discarded
09-28 18:28:27.020 7579-7778/com.atologist.stramvideo I/SrsFlvMuxer: frame discarded
09-28 18:28:27.040 7579-7778/com.atologist.stramvideo I/SrsFlvMuxer: frame discarded
09-28 18:28:27.065 7579-7778/com.atologist.stramvideo I/SrsFlvMuxer: frame discarded
09-28 18:28:27.067 7579-7778/com.atologist.stramvideo I/SrsFlvMuxer: frame discarded
09-28 18:28:27.118 7579-7778/com.atologist.stramvideo I/SrsFlvMuxer: frame discarded
09-28 18:28:27.140 7579-7734/com.atologist.stramvideo I/SrsFlvMuxer: frame discarded
09-28 18:28:27.140 7579-7778/com.atologist.stramvideo I/SrsFlvMuxer: frame discarded
09-28 18:28:27.140 7579-7734/com.atologist.stramvideo I/SrsFlvMuxer: flv: h264 sps/pps sent, sps=17B, pps=4B
09-28 18:28:27.144 7579-7734/com.atologist.stramvideo I/SrsFlvMuxer: frame discarded
09-28 18:28:27.146 7579-7734/com.atologist.stramvideo I/SrsFlvMuxer: frame discarded
09-28 18:28:27.160 7579-7833/com.atologist.stramvideo D/RtmpConnection: handleRxPacketLoop(): Send acknowledgement window size: 5000000
09-28 18:28:27.161 7579-7833/com.atologist.stramvideo D/RtmpConnection: wrote packet: RTMP Window Acknowledgment Size, size: 4
09-28 18:28:27.162 7579-7833/com.atologist.stramvideo D/RtmpDecoder: readPacket(): Setting chunk size to: 4096
09-28 18:28:27.169 7579-7778/com.atologist.stramvideo I/SrsFlvMuxer: frame discarded
09-28 18:28:27.174 7579-7778/com.atologist.stramvideo I/SrsFlvMuxer: frame discarded
09-28 18:28:27.181 7579-7833/com.atologist.stramvideo I/RtmpConnection: handleRxInvoke: Got result for invoked method: connect
09-28 18:28:27.182 7579-7733/com.atologist.stramvideo D/RtmpConnection: createStream(): Sending releaseStream command...
09-28 18:28:27.183 7579-7733/com.atologist.stramvideo D/RtmpConnection: wrote packet: RTMP Command (command: releaseStream, transaction ID: 2), size: 32
09-28 18:28:27.183 7579-7733/com.atologist.stramvideo D/RtmpConnection: createStream(): Sending FCPublish command...
09-28 18:28:27.183 7579-7733/com.atologist.stramvideo D/RtmpConnection: wrote packet: RTMP Command (command: FCPublish, transaction ID: 3), size: 28
09-28 18:28:27.184 7579-7733/com.atologist.stramvideo D/RtmpConnection: createStream(): Sending createStream command...
09-28 18:28:27.184 7579-7733/com.atologist.stramvideo D/RtmpConnection: wrote packet: RTMP Command (command: createStream, transaction ID: 4), size: 25
09-28 18:28:27.208 7579-7587/com.atologist.stramvideo W/art: Suspending all threads took: 7.269ms
09-28 18:28:27.213 7579-7778/com.atologist.stramvideo I/SrsFlvMuxer: frame discarded
09-28 18:28:27.215 7579-7778/com.atologist.stramvideo I/SrsFlvMuxer: frame discarded
09-28 18:28:27.249 7579-7734/com.atologist.stramvideo I/SrsFlvMuxer: frame discarded
09-28 18:28:27.260 7579-7778/com.atologist.stramvideo I/SrsFlvMuxer: frame discarded
09-28 18:28:27.262 7579-7778/com.atologist.stramvideo I/SrsFlvMuxer: frame discarded
09-28 18:28:27.288 7579-7734/com.atologist.stramvideo I/SrsFlvMuxer: frame discarded
09-28 18:28:27.300 7579-7778/com.atologist.stramvideo I/SrsFlvMuxer: frame discarded
09-28 18:28:27.319 7579-7778/com.atologist.stramvideo I/SrsFlvMuxer: frame discarded

**Comment by pedroSG94** [comment]
I need more log.
You should see log like:
```
09-28 15:04:13.255 20850-21223/com.pedro.rtmpstreamer D/RtmpConnection: wrote packet: RTMP Video, size: 4585
09-28 15:04:13.286 20850-21223/com.pedro.rtmpstreamer D/RtmpConnection: wrote packet: RTMP Audio, size: 374
09-28 15:04:13.289 20850-21223/com.pedro.rtmpstreamer D/RtmpConnection: wrote packet: RTMP Video, size: 5174
09-28 15:04:13.306 20850-21223/com.pedro.rtmpstreamer D/RtmpConnection: wrote packet: RTMP Audio, size: 381
09-28 15:04:13.308 20850-21223/com.pedro.rtmpstreamer D/RtmpConnection: wrote packet: RTMP Audio, size: 391
```
I need the media server name (wowza, nginx, etc).
I recommend you use ffmpeg to verify your server is working.

**Comment by pedroSG94** [comment]
I did a stream to that server with 2 devices and it is working for me.
Do you have a email or something to contact with you and debug? This look like device problem

**Comment by raj9686** [comment]
rajesh.atologist@gmail.com my Email and Skype also

**Comment by raj9686** [comment]
```
10-02 13:35:04.298 2829-27549/? E/mm-camera: <STATS_AEC ><E> 2109: aec_process_calc_current_hist_metered_luma: error: out of range, exit
10-02 13:35:04.323 27360-27439/com.atologist.stramvideo D/RtmpConnection: wrote packet: RTMP Audio, size: 365
10-02 13:35:04.341 2813-13388/? W/Camera2Client: releaseYUVFrame: Not supported in buffer queue mode.
10-02 13:35:04.365 27360-27439/com.atologist.stramvideo D/RtmpConnection: wrote packet: RTMP Audio, size: 364
10-02 13:35:04.365 2829-27549/? E/mm-camera: <STATS_AEC ><E> 2109: aec_process_calc_current_hist_metered_luma: error: out of range, exit
10-02 13:35:04.385 27360-27439/com.atologist.stramvideo D/RtmpConnection: wrote packet: RTMP Audio, size: 362
10-02 13:35:04.387 27360-27439/com.atologist.stramvideo D/RtmpConnection: wrote packet: RTMP Audio, size: 371
10-02 13:35:04.410 2813-13388/? W/Camera2Client: releaseYUVFrame: Not supported in buffer queue mode.
10-02 13:35:04.423 27360-27439/com.atologist.stramvideo D/RtmpConnection: wrote packet: RTMP Audio, size: 375
10-02 13:35:04.432 2829-27549/? E/mm-camera: <STATS_AEC ><E> 2109: aec_process_calc_current_hist_metered_luma: error: out of range, exit
10-02 13:35:04.443 27360-27439/com.atologist.stramvideo D/RtmpConnection: wrote packet: RTMP Audio, size: 381
10-02 13:35:04.464 27360-27439/com.atologist.stramvideo D/RtmpConnection: wrote packet: RTMP Audio, size: 440
10-02 13:35:04.467 27360-27439/com.atologist.stramvideo D/RtmpConnection: wrote packet: RTMP Audio, size: 379
```
This my log

**Comment by pedroSG94** [comment]
Are you using camera1 or camera2?
Try with the other camera. This look a unsupported configuration for your device.

**Comment by raj9686** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.atologist.stramvideo">

    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-feature android:name="android.hardware.camera2.full" />

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity android:name=".MainActivity">

        </activity>

        <activity android:name=".ExampleRtmpActivity">

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>

        </activity>
    </application>

</manifest>
```

**Comment by raj9686** [comment]
my skype is rajesh.atologist@gmail.com

**Comment by raj9686** [comment]
```
    private RtmpCamera1 rtmpCamera1;
  rtmpCamera1 = new RtmpCamera1(mSurface, this);

@Override
    public void onClick(View view) {
        if (!rtmpCamera1.isStreaming()) {
            final String random = randomString(3);
            b_play.setVisibility(View.GONE);
            button.setText("Stop Streaming");

            if (!hasPermissions(this, VIDEO_PERMISSIONS)) {
                ActivityCompat.requestPermissions(this, VIDEO_PERMISSIONS, REQUEST_VIDEO_PERMISSIONS);
            }

            ArrayList<String> resol = new ArrayList<>();

            for (String s : rtmpCamera1.getResolutions()) {
                resol.add(s);
                Log.e(TAG, "onClick: " + s);
            }

            int width = Integer.parseInt(resol.get(4).split("X")[0]);
            int height = Integer.parseInt(resol.get(4).split("X")[1]);

            //1280, 720, 80, 600000, false, 90
            Log.e(TAG, "onClick: width " +width );
            Log.e(TAG, "onClick: height "+height );
            if (rtmpCamera1.prepareAudio() && rtmpCamera1.prepareVideo(width, height, 80, 600000, false, 90)) {
                etUrl.setText(random);
                rtmpCamera1.startStream("rtmp://198.15.82.37/live/" + etUrl.getText().toString());
                rtmpCamera1.switchCamera();

            } else {
                Toast.makeText(this, "Error preparing stream, This device cant do it", Toast.LENGTH_SHORT).show();
            }
        } else {
            button.setText("Start Streaming");
            b_play.setVisibility(View.VISIBLE);
            rtmpCamera1.stopStream();
        }
    }
```

**Comment by raj9686** [comment]
tried with 
` private RtmpCamera2 rtmpCamera2;`
which cant show even in view also.

**Comment by raj9686** [comment]
I have changed my manifest and issue resolved 
```

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.atologist.stramvideo">

    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-feature android:name="android.hardware.camera" />
    <uses-feature android:name="android.hardware.camera2.full" />
    <uses-feature android:name="android.hardware.camera2.autofocus" />

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity android:name=".MainActivity">

        </activity>

        <activity android:name=".ExampleRtmpActivity">

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>

        </activity>
    </application>

</manifest>
```
