### ISSUE TITLE
How to insert sei?

### ISSUE THREAD

**Issue by wangtaoT** [pedroSG94/rtmp-rtsp-stream-client-java#580]

**Comment by pedroSG94** [comment]
I don't know how to do it but maybe this could help you:
https://software.intel.com/en-us/forums/media/topic/311805
H264 buffer is here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L751

**Comment by wangtaoT** [comment]
I have implemented this function。Everyone can make my changes。
https://wangtaot.github.io/2020/06/03/Android%E6%8E%A8%E6%B5%81rtmp%E6%8F%92%E5%85%A5SEI/

**Comment by ksc91u** [comment]
@wangtaoT 
after insert that sei code, ffmpeg can not play my stream.

[h264 @ 0x7fe3a28be800] decode_slice_header error
[h264 @ 0x7fe3a28be800] no frame!

I push my stream to AWS IVS.
