### ISSUE TITLE
Using face detection functions

### ISSUE THREAD

**Issue by Racker79** [pedroSG94/rtmp-rtsp-stream-client-java#585]
Hi.

In the code I see that the functions on face detection have the experimental label and I do not understand very well how to use these functions.

Could you give me an example of how they are used in an activity?

Thank you

**Comment by pedroSG94** [comment]
I did experimental annotation because that functions in camera2 is not working properly and in camera1 is not totally finished (Because only face is detected. Eyes or mouth aren't developed)
