### ISSUE TITLE
screen record

### ISSUE THREAD

**Issue by mhackeras** [pedroSG94/rtmp-rtsp-stream-client-java#59]
is there a way to use ur library to screen record and stream ?
cant really find a way i am so much noob in these even studying it for a week :(

**Comment by pedroSG94** [comment]
RtmpDisplay and RtspDisplay do it.
Install app and test that activity. It doesn't need preview so you can do it on background

**Comment by mhackeras** [comment]
i was like blind yesterday.. :S
thanks a lot your work is great and works like a charm :)
