### ISSUE TITLE
Want some info

### ISSUE THREAD

**Issue by mynew-github-account** [pedroSG94/rtmp-rtsp-stream-client-java#590]
Where I can find 
1.size of data upload 
2.time taken to upload
3.when upload start
4.when upload completed

**Comment by pedroSG94** [comment]
Assume that you are using rtmp:
You can get it all here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L458
1 - 
```java
rtmpPacket.getHeader().getPacketLength();
```
2 - Write a timestamp when it start to upload and ge tthe different when it is finished.
3 - This line start upload:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L467
4 - This line finish upload:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L474
