### ISSUE TITLE
Dacast stops after 2 seconds

### ISSUE THREAD

**Issue by marcin-adamczewski** [pedroSG94/rtmp-rtsp-stream-client-java#592]
Hi @pedroSG94 
I've tried streaming to Dacast with authentication. The auth succeeded according to the `onAuthSuccessRtmp` callback, I could see a video for 2 seconds and then the screen is black and no audio as well. In logs, I could see video and audio packets being sent though. Streaming worked well using OBS desktop app.
Below I paste some logs. Maybe you could notice something interesting:

> I/Camera2ApiManager: Camera opened
I/Camera2ApiManager: Camera configured
D/RtmpConnection: connect(): socket connection established, doing handhake...
D/Handshake: writeC0
D/Handshake: writeC1
D/Handshake: writeC1(): Calculating digest offset
D/Handshake: writeC1(): (real value of) digestOffset: 484
D/Handshake: writeC1(): recalculated digestOffset: 1260
D/Handshake: writeC1(): digestOffsetBytes: 0000E5FF
D/Handshake: partBeforeDigest(): size: 1260
D/Handshake: writeC1(): Writing timestamp and Flash Player version
D/Handshake: partAfterDigest(): size: 244
D/Handshake: copying digest offset bytes in partBeforeDigest
D/Handshake: writeC1(): Calculating digest
D/Handshake: writeC1(): writing C1 packet
D/Handshake: readS0
D/Handshake: readS1
D/Handshake: readS1(): S1 total bytes read OK
D/Handshake: writeC2
D/Handshake: readS2
D/Handshake: readS2(): S2 total bytes read OK
D/RtmpConnection: connect(): handshake done
D/RtmpConnection: rtmpConnect(): Building 'connect' invoke packet
D/RtmpConnection: starting main rx handler loop
D/RtmpConnection: wrote packet: RTMP Command (command: connect, transaction ID: 1), size: 352
I/RtmpConnection: [ AccessManager.Reject ] : [ authmod=adobe ] : ?reason=needauth&user=942141&salt=MTYyNjgyOTYxMw==&challenge=MTIzOTg3Mjg1MQ==
D/RtmpConnection: socket closed
D/RtmpConnection: connect(): socket connection established, doing handshake...
D/Handshake: writeC0
D/Handshake: writeC1
D/Handshake: writeC1(): Calculating digest offset
D/Handshake: writeC1(): (real value of) digestOffset: 112
D/Handshake: writeC1(): recalculated digestOffset: 888
D/Handshake: writeC1(): digestOffsetBytes: 00000070
D/Handshake: partBeforeDigest(): size: 888
D/Handshake: writeC1(): Writing timestamp and Flash Player version
D/Handshake: partAfterDigest(): size: 616
D/Handshake: copying digest offset bytes in partBeforeDigest
D/Handshake: writeC1(): Calculating digest
D/Handshake: writeC1(): writing C1 packet
D/Handshake: readS0
D/Handshake: readS1
D/Handshake: readS1(): S1 total bytes read OK
D/Handshake: writeC2
D/Handshake: readS2
D/Handshake: readS2(): S2 total bytes read OK
D/RtmpConnection: rtmpConnect(): Building 'connect' invoke packet
D/RtmpConnection: wrote packet: RTMP Command (command: connect, transaction ID: 2), size: 458
D/RtmpConnection: handleRxPacketLoop(): Setting acknowledgement window size: 1250000
D/RtmpConnection: handleRxPacketLoop(): Send acknowledgement window size: 1048576
D/RtmpConnection: wrote packet: RTMP Window Acknowledgment Size, size: 4
I/RtmpConnection: handleRxInvoke: Got result for invoked method: connect
D/RtmpConnection: createStream(): Sending releaseStream command...
D/RtmpConnection: wrote packet: RTMP Command (command: releaseStream, transaction ID: 3), size: 49
D/RtmpConnection: createStream(): Sending FCPublish command...
D/RtmpConnection: wrote packet: RTMP Command (command: FCPublish, transaction ID: 4), size: 45
D/RtmpConnection: createStream(): Sending createStream command...
D/RtmpConnection: wrote packet: RTMP Command (command: createStream, transaction ID: 5), size: 25
V/ViewRootImpl: The specified message queue synchronization  barrier token has not been posted or has already been removed
I/Surface: opservice is null false
I/RtmpConnection: handleRxInvoke: Got result for invoked method: releaseStream
D/RtmpConnection: handleRxInvoke(): 'releaseStream'
D/RtmpConnection: handleRxInvoke(): 'onFCPublish'
I/RtmpConnection: handleRxInvoke: Got result for invoked method: FCPublish
D/RtmpConnection: handleRxInvoke(): 'FCPublish'
I/RtmpConnection: handleRxInvoke: Got result for invoked method: createStream
D/RtmpConnection: handleRxInvoke(): Stream ID to publish: 1
D/RtmpConnection: fmlePublish(): Sending publish command...
D/RtmpConnection: wrote packet: RTMP Command (command: publish, transaction ID: 0), size: 50
D/RtmpConnection: handleRxInvoke(): onStatus NetStream.Publish.Start
D/RtmpConnection: onMetaData(): Sending empty onMetaData...
D/RtmpConnection: wrote packet: com.github.faucamp.simplertmp.packets.Data@f6bd885, size: 284
D/RtmpConnection: handleRxPacketLoop(): Sending PONG reply..
D/RtmpConnection: wrote packet: RTMP User Control (type: PONG_REPLY, event data: [I@8c1e6da), size: 6
D/RtmpConnection: wrote packet: RTMP Audio, size: 11
I/SrsFlvMuxer: worker: send frame type=9, dts=60, size=131072B
D/RtmpConnection: wrote packet: RTMP Video, size: 39
D/RtmpConnection: wrote packet: RTMP Audio, size: 264
I/SrsFlvMuxer: worker: send frame type=9, dts=64, size=131072B
D/RtmpConnection: wrote packet: RTMP Video, size: 213

and later audio and video packets were being sent all the time until manually disconnected.

What's suspicious to me is that the auth has been rejected, and after that, the second connection succeeded.

```
I/RtmpConnection: [ AccessManager.Reject ] : [ authmod=adobe ] : ?reason=needauth&user=942141&salt=MTYyNjgyOTYxMw==&challenge=MTIzOTg3Mjg1MQ==
D/RtmpConnection: socket closed

```

I saw that you were working on some auth issue related to Dacast, and you fixed it https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/108

Are you still able to connect to Dacast?
I would be grateful for any suggestions on the issue.

PS Is there any documentation for adobe auth for RTMP? I can't find one.

**Comment by marcin-adamczewski** [comment]
I've captured some RTMP frames from OBS app using Wireshark
https://cl.ly/98731b743905

**Comment by pedroSG94** [comment]
I haven't any documentation about adobe auth. I developed this using other library examples and using wireshark.
If you can try reproduce stream with other player to make sure that dacast player is working fine and stream without authentication to discard a problem with that (I don't remember if it is possible with dacast).

I need check this case and report you the result.

**Comment by marcin-adamczewski** [comment]
I've tried it with VLC. I grabbed m3u8 url from Dacast and played it using VLC. The result was a bit different but still wrong. I could see some video frames from time to time, usually no sound. For sure some packets were lost or synchronization failed as I could see blurred video from time to time, so I guess IFames were lost?

I've found some interesting sentence in Akamai auth documenataion

> When using Adobe authentication in a multi-TCP connection, ensure that you sequence your multi-bitrate TCP connection in series and not in parallel.

Are we following this rule?
Here is the link https://learn.akamai.com/en-us/webhelp/media-services-live/media-services-live-encoder-compatibility-testing-and-qualification-guide-v4.0/GUID-85F0D2A0-FD4E-4386-8AED-643EE4846D0E.html

Regarding authentication, I didn't find an option to disable it for Dacast.

**Comment by marcin-adamczewski** [comment]
I've found something interesting in Akamai documentation

> Media Services Live for Stream Packaging requires FLV timestamp data from encoders to be in increasing order regardless of type (audio/video/metadata/etc.). Adobe’s RTMP specification only requires that timestamps be increasing within a type and timestamps can be out of order across different types. Akamai, however requires timestamps to monotonically increase across types.
https://learn.akamai.com/en-us/webhelp/media-services-live/media-services-live-encoder-compatibility-testing-and-qualification-guide-v4.0/GUID-F941C88B-9128-4BF4-A81B-C2E5CFD35BBF.html

As I was logging all the frames being sent, I've seen that timestamp is not increasing monotonically for video and audio. Maybe this is the case. I was logging all SrsFlvFrame.dts in SrsFlvMuxer.start() method.

Here are some of logged frames timestamps

> ts: 0 isAudio: true
ts: 231 isAudio: false
ts: 112 isAudio: true
ts: 283 isAudio: false
ts: 142 isAudio: true
ts: 380 isAudio: false
ts: 174 isAudio: true
ts: 407 isAudio: false
ts: 204 isAudio: true
ts: 427 isAudio: false
ts: 234 isAudio: true

**Comment by pedroSG94** [comment]
I'm testing with dacast to find the problem, but I don't think that ts is the problem, because for this reason all servers should fail and this isn't the case.
Sorry if I'm going too slow but I'm not having time these days.

**Comment by marcin-adamczewski** [comment]
I'm not sure if all servers should fail because not all servers use Akamai. Standard RTMP doesn't require increasing timestamps across all frame types, only Akamai does.
I've checked frames from OBS app using Wireshark and it sends all frames with an increasing timestamp in contrary to the library. What do you think?

**Comment by pedroSG94** [comment]
My timestamp is when I generate that frame but microphone and camera is not using same thread so timestamp is different but always increase repect to last frame of same type (video or audio). 
I have an idea to test it. I will create a new branch to test but this could produce audio and video sync problems. The idea is change timestamp before send packet to all frames.

**Comment by marcin-adamczewski** [comment]
As I understand the Akamai doc I quoted above, timestamp has to be increasing for audio and video as a whole. So the frames stream like: audio(100ms), video(120ms), audio(110ms) would be wrong as 110 < 120.

Yeap it would be cool to have an idea to quickly verify this theory to not make bigger implementation unnecessarily :)

**Comment by marcin-adamczewski** [comment]
@pedroSG94 I've implemented it and it seems to work well!
Here is my implementation https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/pull/598
It is an alpha version but I just wanted to let you know it worked.
