### ISSUE TITLE
Stream in actual aspect ratio

### ISSUE THREAD

**Issue by mynew-github-account** [pedroSG94/rtmp-rtsp-stream-client-java#593]
I am using rtmpdisplay ,is their way to stream video screen in actual resolution of mobile.
My mobile resolution is 2081 x 1080
But when I stream in 1280x720 it's not clear 

I tried to give 2081 x 1080 to rtmpdisplay.preparevideo()   but it failed

can you suggest the correct way to do so.?

**Comment by pedroSG94** [comment]
You must use a pair value for resolution. Try with 2080x1080
