### ISSUE TITLE
Support for USB camera

### ISSUE THREAD

**Issue by pk178** [pedroSG94/rtmp-rtsp-stream-client-java#594]
Hi,
I tried your library, it's awesome, do almost thing I need.
Can you help to upgrade your library to work with USB camera ?

Many thanks

**Comment by pedroSG94** [comment]
Hi,
You can try with this:
https://github.com/pedroSG94/Stream-USB-test
If this isn't working I can't help you because I havent an USB camera to test. You can post here for help but I'm not sure If I can help you.
