### ISSUE TITLE
stream on YouTube.

### ISSUE THREAD

**Issue by alexeyshevchnko** [pedroSG94/rtmp-rtsp-stream-client-java#595]
Hello, I apologize for the stupid question. I downloaded your project I'm trying to make a stream on YouTube. I can’t understand where to enter the key

**Comment by pedroSG94** [comment]
Hi,
You should write your endpoint in the editext of one rtmp example like this (this is an example you should find your own URL and key in your control panel):
URL server:
rtmp://a.rtmp.youtube.com/live2
key:
aa1-aa2-aa3-aa4
In edit text you should write this:
rtmp://a.rtmp.youtube.com/live2/aa1-aa2-aa3-aa4

**Comment by mlph-sreyes** [comment]
This worked, thanks!
