### ISSUE TITLE
Last few second stream is not sent

### ISSUE THREAD

**Issue by mynew-github-account** [pedroSG94/rtmp-rtsp-stream-client-java#597]
When I tried to stream with opengl view, at the end last 5~10 video is not visible to  user
So library stop sending data immediately after stop or it wait until all buffered data to send

**Comment by pedroSG94** [comment]
Library stop send data inmediately and also send a stop request to server to inform that stream is finished.
My library only can buffered around 1s if you have weak connection so I think that this is related with delay (I think I can't do anything here)

**Comment by marcin-adamczewski** [comment]
We did a workaround for it recently. Basically, we delayed disconnecting the stream by 30 seconds. So once user clicks `stop` or leaves the Activity we started 30s countdown. You'd need to mute video and audio at this time so people that have no delay on the stream can't hear and see you.
You'd also need to store your CameraManager object out of Activity, like in the foreground Service so you don't close the stream when leaving the Activity.
It's a pretty hacky way though.
