### ISSUE TITLE
Why SurfaceFilterRender.getSurface() draw camera preview is landscape?

### ISSUE THREAD

**Issue by iori71721** [pedroSG94/rtmp-rtsp-stream-client-java#600]
thank you do this lib，this lib is very good.sorry,my english is poor.i try to used SurfaceFilterRender to draw camera preview,now camera preview is portrait,but SurfaceFilterRender always is landscape?
can you tell me how to fixed it,thanks.
==============================================
error image
![surface方向不對](https://user-images.githubusercontent.com/61674096/84499818-e7859100-ace5-11ea-960e-18737c0bb761.jpg)
==============================================
my code is below,see private void initCamera() to start
==============================================
public class MoreCameraPreview_back extends AppCompatActivity {
    private static final int PERMISSION_REQUEST = 1;
    private SurfaceView first;
    private SurfaceView second;
    private CameraManager cameraManager;
    public static final String[] PERMISSIONS = {
            Manifest.permission.RECORD_AUDIO, Manifest.permission.CAMERA, Manifest.permission.READ_EXTERNAL_STORAGE
    };
    private List<Surface> drawSurfaces = new ArrayList<>(10);
    private CameraDevice cameraDevice;
    private CameraCaptureSession cameraCaptureSession;
    private Handler handler;
    private OpenGlView surfaceView;
    private RtmpCamera2 streamCamera;
    private SurfaceFilterRender surfaceFilterRender;
    private static final String CAMERA_ID = "1";

    private GLSurfaceView glSurfaceView;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.more_camera_preview_layout);
        surfaceView = findViewById(R.id.camera_surface);
        first = findViewById(R.id.first);
        second = findViewById(R.id.second);
        handler = new Handler();
        if (allPermissionsGranted(PERMISSIONS)) {
            initCamera();
        } else {
            ActivityCompat.requestPermissions(this, PERMISSIONS, PERMISSION_REQUEST);
        }
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        if (requestCode == PERMISSION_REQUEST) {
            if (permissions.length == grantResults.length) {
                initCamera();
            }
        }
    }

    /**
     * Process result from permission request dialog box, has the request
     * been granted? If yes, start Camera. Otherwise display a toast
     */
    protected boolean allPermissionsGranted(String[] requestPermissions) {
        boolean allPermissionsGranted = true;
        for (String checkPermission : requestPermissions) {
            if (ContextCompat.checkSelfPermission(this, checkPermission) != PackageManager.PERMISSION_GRANTED) {
                allPermissionsGranted = false;
                break;
            }
        }
        return allPermissionsGranted;
    }

    private void addSurfaces(CaptureRequest.Builder builder) {
        for (Surface addSurface : drawSurfaces) {
            builder.addTarget(addSurface);
        }
    }

    private void initRtmp() {
        streamCamera = new RtmpCamera2(surfaceView, new ConnectCheckerRtmp() {
            @Override
            public void onConnectionSuccessRtmp() {

            }

            @Override
            public void onConnectionFailedRtmp(@NonNull String reason) {

            }

            @Override
            public void onNewBitrateRtmp(long bitrate) {

            }

            @Override
            public void onDisconnectRtmp() {

            }

            @Override
            public void onAuthErrorRtmp() {

            }

            @Override
            public void onAuthSuccessRtmp() {

            }
        });
        surfaceView.getHolder().addCallback(new SurfaceHolder.Callback() {
            @Override
            public void surfaceCreated(SurfaceHolder holder) {

            }

            @Override
            public void surfaceChanged(SurfaceHolder holder, int format, int width, int height) {
                Log.d("iori_surface", "surfaceChanged: start preview");
                streamCamera.startPreview(CameraHelper.Facing.FRONT);

                drawSurfaces.add(surfaceView.getSurface());
            }

            @Override
            public void surfaceDestroyed(SurfaceHolder holder) {

            }
        });
    }

    /**
     * to ask git
     */
    private void drawCameraPreviewToSurfaceFilterRender() {
        cameraManager = (CameraManager) getSystemService(Context.CAMERA_SERVICE);
        initRtmp();
        initSurfaceRender();

        handler.postDelayed(new Runnable() {
            @Override
            public void run() {
                try {
                    if (ActivityCompat.checkSelfPermission(MoreCameraPreview_back.this, Manifest.permission.CAMERA) != PackageManager.PERMISSION_GRANTED) {
                        // TODO: Consider calling
                        //    ActivityCompat#requestPermissions
                        // here to request the missing permissions, and then overriding
                        //   public void onRequestPermissionsResult(int requestCode, String[] permissions,
                        //                                          int[] grantResults)
                        // to handle the case where the user grants the permission. See the documentation
                        // for ActivityCompat#requestPermissions for more details.
                        return;
                    }
                    cameraManager.openCamera(CAMERA_ID, new CameraDevice.StateCallback() {
                                @Override
                                public void onOpened(@NonNull final CameraDevice camera) {
                                    cameraDevice = camera;
                                    try {
                                        camera.createCaptureSession(drawSurfaces, new CameraCaptureSession.StateCallback() {
                                            @Override
                                            public void onConfigured(@NonNull CameraCaptureSession session) {
                                                try {
                                                    CaptureRequest.Builder builder = cameraDevice.createCaptureRequest(CameraDevice.TEMPLATE_PREVIEW);
                                                    addSurfaces(builder);
                                                    CaptureRequest captureRequest = builder.build();
                                                    session.setRepeatingRequest(captureRequest, null, null);

                                                } catch (CameraAccessException e) {
                                                    e.printStackTrace();
                                                }
                                            }

                                            @Override
                                            public void onConfigureFailed(@NonNull CameraCaptureSession session) {

                                            }
                                        }, null);
                                    } catch (CameraAccessException e) {
                                        e.printStackTrace();
                                    }
                                }

                                @Override
                                public void onDisconnected(@NonNull CameraDevice camera) {

                                }

                                @Override
                                public void onError(@NonNull CameraDevice camera, int error) {

                                }
                            }
                            , null);
                } catch (CameraAccessException e) {
                    e.printStackTrace();
                }
            }
        },6000);

    }
    private void initSurfaceRender(){
        surfaceFilterRender=new SurfaceFilterRender(new SurfaceFilterRender.SurfaceReadyCallback() {
            @Override
            public void surfaceReady() {
                Log.d("iori_surface", "surfaceReady: ");
                drawSurfaces.add(surfaceFilterRender.getSurface());

                surfaceFilterRender.getSurfaceTexture().setOnFrameAvailableListener(new SurfaceTexture.OnFrameAvailableListener() {
                    @Override
                    public void onFrameAvailable(SurfaceTexture surfaceTexture) {
                        Log.d("iori_surface", "onFrameAvailable: ");
                    }
                });

            }
        });

        surfaceFilterRender.setScale(50f, 50f);
        streamCamera.getGlInterface().setFilter(surfaceFilterRender);
    }
    private void initCamera(){
        drawCameraPreviewToSurfaceFilterRender();
    }
}

**Comment by pedroSG94** [comment]
You need rotate camera using your CameraManager implementation (this is possible with camera1 but I'm not sure with camera2 because all examples I saw was rotating a TextureView). Other way could be add rotation implementation to this class:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/gl/Sprite.java

**Comment by iori71721** [comment]
thank you,i try to fix.
