### ISSUE TITLE
Preview does not resume after closing and re-opening app while using OpenGlView.

### ISSUE THREAD

**Issue by Sermilion** [pedroSG94/rtmp-rtsp-stream-client-java#601]
We have been using TextureView, but due to some rotation issues, we switched to OpenGlView with RmtpCamera2. Now, however, when we background the app, and foreground it again (and calling startPreview/startStream), the preview turns black and does not resume.
The only way to works is if I reinitialize RmtpCamera2, but that takes a second of dark preview.
As I said, it worked fine with TextureView. What kind of special treatment should be applied to OpenGlView?

**Comment by pedroSG94** [comment]
The treatment should be similar if you are doing properly lyfecycle. I means stop stream when view is destroyed and start it when view is created (surfaceDestroyed and surfaceChanged callbacks as you can see in example).
If you can share an example code I can help you if you have any error about it. Also you can check background example if you want implement stream while you are in background (Service RTP button).
