### ISSUE TITLE
Integrate with AR

### ISSUE THREAD

**Issue by chongieball** [pedroSG94/rtmp-rtsp-stream-client-java#602]
In this repository https://github.com/argear/argear-android-sample/tree/master/sample-kotlin , i got raw data as a ByteBuffer. How to integrate with this library? Thanks!

**Comment by pedroSG94** [comment]
If you have h264 bybuffer you can send it directly to RtspClient or SrsFlvMuxer (rtsp or rtmp). If it isn't h264 I need know image format to help you

**Comment by chongieball** [comment]
I'm using RTMP. It is just `srsFlvMuxer.sendVideo(byteBuffer, MediaCodec.BufferInfo())` ?

**Comment by pedroSG94** [comment]
Yes, but you need set video and audio info with this methods:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtmp/RtmpCamera1.java#L120
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtmp/RtmpCamera1.java#L128
And start stream before send video frames. Also, MediaCodec.BufferInfo should be update each frame with time stamp and size of each frame:
```java
private void updateInfo(ByteBuffer byteBuffer, MediaCodec.BufferInfo info) {
    //startStreamTimeStamp = System.nanoTime() / 1000 when you call srsFlvMuxer.start();
    info.presentationTimeUs = System.nanoTime() / 1000 - startStreamTimeStamp;
    info.size = byteBuffer.remaining();
    info.offset  = 0;
    //You need know if your bytebuffer is keyframe to set this line or you can let library do it for you if you don't know it
    info.flags = isKeyFrame ? 1 : 0;
  }
```

**Comment by chongieball** [comment]
I got NPE , log:

java.lang.NullPointerException: Attempt to invoke virtual method 'byte java.nio.ByteBuffer.get(int)' on a null object reference
        at net.ossrs.rtmp.SrsFlvMuxer$SrsFlv.writeVideoSample(SrsFlvMuxer.java:932)
        at net.ossrs.rtmp.SrsFlvMuxer.sendVideo(SrsFlvMuxer.java:340)

My Code:
`
//In the onDrawFrame GLSurface function 
ByteBuffer rawData = getRawData(); //return readonly byte buffer
publisher.inputData(rawData, new MediaCodec.BufferInfo());
`
Input Data function
`
public void inputData(ByteBuffer rawData, MediaCodec.BufferInfo info) {
    info.presentationTimeUs = System.nanoTime() / 1000 - startStreamTimeStamp;
    info.size = byteBuffer.remaining();
    info.offset  = 0;
    info.flags = isKeyFrame ? 1 : 0;
    srsFlvMuxer.sendVideo(byteBuffer, info);
}
`

**Comment by pedroSG94** [comment]
Your bytebuffer seems null. Check it.

**Comment by chongieball** [comment]
bytebuffer from raw data?

**Comment by chongieball** [comment]
> bytebuffer from raw data?

`
GLSurface function ByteBuffer rawData = getRawData();
if (rawData != null) publisher.inputData(rawData, new MediaCodec.BufferInfo());
`
still NPE, because getRawData return read only ByteBuffer?

**Comment by pedroSG94** [comment]
Maybe yes. Library fail in this line:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/d5ec1e42144bd813f2af9637a9eddb197c142d70/rtmp/src/main/java/net/ossrs/rtmp/SrsFlvMuxer.java#L932
Can you do bytebuffer.duplicate()?
After that try to get a byte from your bytebuffer like this:
bytebuffer.get(0);

**Comment by chongieball** [comment]
Trying to log bytebufferduplicated.get(0)

`ByteBuffer bd = bb.duplicate();
  Log.d("duplicate", bd.get(0) + "");`

success, but when put to inputData(), still NPE

**Comment by chongieball** [comment]
> Trying to log bytebufferduplicated.get(0)
> 
> `ByteBuffer bd = bb.duplicate(); Log.d("duplicate", bd.get(0) + "");`
> 
> success, but when put to inputData(), still NPE

trying to log original rawData, success too

**Comment by chongieball** [comment]
> > Trying to log bytebufferduplicated.get(0)
> > `ByteBuffer bd = bb.duplicate(); Log.d("duplicate", bd.get(0) + "");`
> > success, but when put to inputData(), still NPE
> 
> trying to log original rawData, success too

got this error log E/SrsFlvMuxer: annexb not match.

**Comment by pedroSG94** [comment]
That error is not a problem. Did you fix nullpointer?
If yes, we need be sure that rawData from that library is h264 and check that you send a keyframe to start stream.

**Comment by chongieball** [comment]
I think raw data from that library is not h264. I'll ask that. If not, can you tell me how to convert the raw data to h264 data?

**Comment by pedroSG94** [comment]
Yes but we need image format of that buffer to encode it.

**Comment by chongieball** [comment]
image format of that buffer is ImageFormat.NV21

**Comment by chongieball** [comment]
this is how i get the raw data from AR library https://gist.github.com/chongieball/4b2937fabf68b9b1391d7fc0af42e3bf

**Comment by pedroSG94** [comment]
Ok.
Now, we need know image resolution to encode it and use VideoEncoder class.
You can use something like this(remember stop srsFlvMuxer and Videoencoder when you want stop stream):
```java
   final SrsFlvMuxer srsFlvMuxer = new SrsFlvMuxer(this);
    int width = 640;
    int height = 480;
    srsFlvMuxer.setVideoResolution(width, height);
    srsFlvMuxer.setIsStereo(true);
    srsFlvMuxer.setSampleRate(44100);
    srsFlvMuxer.start("endpoint");
    VideoEncoder videoEncoder = new VideoEncoder(new GetVideoData() {
      @Override
      public void onSpsPps(ByteBuffer sps, ByteBuffer pps) {
        srsFlvMuxer.setSpsPPs(sps, pps);
      }

      @Override
      public void onSpsPpsVps(ByteBuffer sps, ByteBuffer pps, ByteBuffer vps) {
        
      }

      @Override
      public void getVideoData(ByteBuffer h264Buffer, MediaCodec.BufferInfo info) {
        srsFlvMuxer.sendVideo(h264Buffer, info);
      }

      @Override
      public void onVideoFormat(MediaFormat mediaFormat) {

      }
    });
    videoEncoder.prepareVideoEncoder(width, height, 30, 3000 * 1024, 0, false, 2, FormatVideoEncoder.YUV420Dynamical);
    videoEncoder.start();
    //call this line all time you get a frame
    videoEncoder.inputYUVData(new Frame(rawData.array(), 0, false, ImageFormat.NV21));
```

**Comment by chongieball** [comment]
my rawData is readonly, so i convert it to prevent ReadOnlyException. This the function:
`private fun getByteArrayFromByteBuffer(byteBuffer: ByteBuffer): ByteArray {
        val bytesArray = ByteArray(byteBuffer.remaining())
        byteBuffer.get(bytesArray)
        return bytesArray
    }`

got error :
java.lang.IndexOutOfBoundsException: off=0, len=6220800 out of bounds (size=460800)
        at java.nio.Buffer.checkBounds(Buffer.java:559)
        at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:272)
        at com.pedro.encoder.BaseEncoder.processInput(BaseEncoder.java:73)

**Comment by pedroSG94** [comment]
Did you modify width and height with resolution used in your library? You are still using 640x480

**Comment by chongieball** [comment]
i set width and height of encoder based on width and height in AR library, got error:
java.lang.IndexOutOfBoundsException: off=0, len=6220800 out of bounds (size=2332800)
        at java.nio.Buffer.checkBounds(Buffer.java:559)
        at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:272)
        at com.pedro.encoder.BaseEncoder.processInput(BaseEncoder.java:73)

**Comment by chongieball** [comment]
width in AR library: 1080, height: 1440

**Comment by pedroSG94** [comment]
In that case modify that values in my exampled shared:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/602#issuecomment-646116163

**Comment by pedroSG94** [comment]
I don't understand that. 6220800 is not 1080x1440 YUV image
YUV image size is  = width x height x 3/2.
Are you sure that this bytebuffer is NV21?

**Comment by pedroSG94** [comment]
Your image is ARGB888:
If you want calculate size of ARGB888:
width x height x depth (ARGB888 edpth is 4) = 1080x1440x4 = 6220800.
You need change image format to NV21.

**Comment by pedroSG94** [comment]
Try with this. But I never test this method so maybe fail:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/utils/yuv/YUVUtil.java#L123

**Comment by chongieball** [comment]
I'll try it. Thank you
