### ISSUE TITLE
Send watermark using RtmpDisplay

### ISSUE THREAD

**Issue by abadoliverco** [pedroSG94/rtmp-rtsp-stream-client-java#603]
Hi,

is it possible to include watermark while streaming using RtmpDisplay?

Thank you!

**Comment by pedroSG94** [comment]
You can use ImageFilter like here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L301
Remember that you need enable opengl in constructor:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtmp/RtmpDisplay.java#L26

**Comment by abadoliverco** [comment]
Hi @pedroSG94 
I tried your suggestion but the screen record turns black, also is it possible to put a watermark on the viewer side only and the streamer side will not see the watermark?

Thank you!
