### ISSUE TITLE
Result stream and video record have black border.

### ISSUE THREAD

**Issue by huongvu1397** [pedroSG94/rtmp-rtsp-stream-client-java#604]
Result video stream and video record have black border.
Device screen size : 1080 x 2076 
And prepareVideo with width = 1080 and height = 1920 
I call this method for streaming and recording video but my video always have black border. I need help to fix this
```
if (rtmpDisplay!!.prepareVideo(
                                1080,
                                1920,
                                fps,
                                bitrate,
                                orientation,
                                density_dpi
                            )
                        )
```
![image](https://user-images.githubusercontent.com/39198328/84852422-ffaf3480-b086-11ea-8ebf-4e795c047040.png)

**Comment by pedroSG94** [comment]
I will check it. Did you enabled opengl in constructor?

**Comment by huongvu1397** [comment]
yes, in constructor i using it.
```
 private fun instanceRtmpDisplay(): RtmpDisplay? {
        return if (rtmpDisplay == null) {
            RtmpDisplay(this, true, connectCheckerRtmp)
        } else rtmpDisplay
    }
```

**Comment by pedroSG94** [comment]
I'm working on it.
