### ISSUE TITLE
disabling video while streaming

### ISSUE THREAD

**Issue by ilyko** [pedroSG94/rtmp-rtsp-stream-client-java#605]
There is a point about disabling video while streaming in docs, but I can't succeed in it. There is no methods like for audio disabling, can you please explain how to achieve this?

**Comment by pedroSG94** [comment]
While you are using openglview:
```java
rtmpCamera1.getGlInterface().muteVideo();
```

**Comment by ilyko** [comment]
@pedroSG94 i didn't see such methods in that class, am I missing anything?

**Comment by pedroSG94** [comment]
Are you using gradle? IN this case try with this:
```
implementation 'com.github.pedroSG94:rtmp-rtsp-stream-client-java:e75a68b761'
```
I haven't uploaded the latest version yet for gradle because I want fix others issues first. That line is my last commit that should implement that feature.
