### ISSUE TITLE
Access to flashlight

### ISSUE THREAD

**Issue by DipanshKhandelwal** [pedroSG94/rtmp-rtsp-stream-client-java#609]
Is it possible to get access to the `flashlight` of the camera while streaming ?

**Comment by pedroSG94** [comment]
Yes, you can use this methods:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L158

**Comment by DipanshKhandelwal** [comment]
Oh thanks a lot.
I was looking for `torch` and `flashlight`.  Didn't expect it to be `lantern`.

**Comment by romio95** [comment]
> 

Bro, enableLantern()/disabledLantern()  methods not working for me. Buttons changed, no errors , but FLASHligth is not turned on / off. Maybe I need additional access? Xiaomi MiA3

**Comment by pedroSG94** [comment]
Hello,

Did you try using back camera?
Are you using camera1 or camera2?

**Comment by romio95** [comment]
> Hello,
> 
> Did you try using back camera? Are you using camera1 or camera2?


import com.pedro.encoder.input.video.Camera1ApiManager;
private Camera1ApiManager camera1ApiManager;

    if (!isFlashOn) {
            try {
                camera1ApiManager.enableLantern();
                isFlashOn = true;
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            camera1ApiManager.disableLantern();
            isFlashOn = false;
        }

**Comment by pedroSG94** [comment]
Your code is totally wrong.
First of all, camera must be opened before enable or disable flashlight.
Also, you are duplicating cameramanager instacnes (you have one in RtmpCamera1.

Go to [this line](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/defaultexample/ExampleRtmpActivity.java#L164) and replace that case code to this:
```java
try {
          if (rtmpCamera1.isLanternEnabled()) {
            rtmpCamera1.disableLantern();
          } else {
            rtmpCamera1.enableLantern();
          }
        } catch (Exception e) {
          Toast.makeText(this, e.getMessage(), Toast.LENGTH_SHORT).show();
        }
        break;
```
Now, compile app example and, open default RTMP and press switch camera to enable/disable flashlight

**Comment by romio95** [comment]
> Your code is totally wrong. First of all, camera must be opened before enable or disable flashlight. Also, you are duplicating cameramanager instances (you have one in RtmpCamera1).
> 
> Go to [this line](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/defaultexample/ExampleRtmpActivity.java#L164) and replace that case code to this:
> 
> ```java
> try {
>           if (rtmpCamera1.isLanternEnabled()) {
>             rtmpCamera1.disableLantern();
>           } else {
>             rtmpCamera1.enableLantern();
>           }
>         } catch (Exception e) {
>           Toast.makeText(this, e.getMessage(), Toast.LENGTH_SHORT).show();
>         }
>         break;
> ```
> 
> Now, compile app example, open default RTMP and press switch camera to enable/disable flashlight

Yep, its working. Thanks!!!!

I have 1 more question, tell me how to add 2 buttons to set the zoom +1 and -1, do I need to do any checks?
That is, on the left there will be a zoom button -1, in the middle a field with a zoom value (active value), and on the right a zoom button +1?

**Comment by pedroSG94** [comment]
Like in flashlight case, you need start camera before change zoom.
In this case you have this methods to get the zoom range:
```java
rtmpCamera1.getMinZoom();
rtmpCamera1.getMaxZoom();
```
An this method to get actual value:
```java
rtmpCamera1.getZoom();
```
To change the value you can set an int value in the range of min and max values using setZoom method or use gestures like here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/customexample/RtmpActivity.java#L447

**Comment by romio95** [comment]
> Like in flashlight case, you need start camera before change the zoom. In this case you have this methods to get the zoom range:
> 
> ```java
> rtmpCamera1.getMinZoom();
> rtmpCamera1.getMaxZoom();
> ```
> 
> An this method to get actual value:
> 
> ```java
> rtmpCamera1.getZoom();
> ```
> 
> To change the value you can set an int value in the range of min and max values using setZoom method or use gestures like here: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/customexample/RtmpActivity.java#L447

Can you help implement this, now I get a lot of errors and the application closes?

**Comment by pedroSG94** [comment]
```java
          //increase
          int nextZoom = (int) rtmpCamera1.getZoom() + 1;
          if (nextZoom <= rtmpCamera1.getMaxZoom()) rtmpCamera1.setZoom(nextZoom);
          //decrease
          int previousZoom = (int) rtmpCamera1.getZoom() - 1;
          if (previousZoom >= rtmpCamera1.getMinZoom()) rtmpCamera1.setZoom(previousZoom);
```

**Comment by pedroSG94** [comment]
> **I use the capasitor-rtmp-stream plugin. I need to add to this code the ability to do zoomIn and zoomOut**

Yes, I think that. I only can give you support for native implementations so if modify that class is not working I recommend you contact with the owner to know which classes you need to modify.

**Comment by romio95** [comment]
> ```java
> rtmpCamera1.getZoom();
> ```

Awesome bro, all working. Really perfect plugin. Thanks!

I mostly work with javascript, and its frameworks, but I see that the java community is incredible)
