### ISSUE TITLE
Create VideoEncoder failed

### ISSUE THREAD

**Issue by abadoliverco** [pedroSG94/rtmp-rtsp-stream-client-java#610]
Hi,

I encountered this error I'm using RtmpDisplay: 
<img width="616" alt="Screen Shot 2020-06-22 at 5 03 26 PM" src="https://user-images.githubusercontent.com/13760154/85269428-72b31380-b4aa-11ea-9690-fdd731558a23.png">

Device:
Samsung Galaxy J8
Android version: 9

Thank you!

**Comment by pedroSG94** [comment]
Can you tell me prepareVideo params?
Also if you can share an example code to reproduce the case.

**Comment by abadoliverco** [comment]
Hi @pedroSG94,

prepareVideo params i used:

<img width="341" alt="Screen Shot 2020-06-24 at 9 33 42 AM" src="https://user-images.githubusercontent.com/13760154/85486803-f2052c00-b5fd-11ea-8d3e-eac481553133.png">

Thank you!

**Comment by pedroSG94** [comment]
Sorry for late response.
I was testing it but I can't reproduce your error. 
According with internet that error is related with other app using that encoder or resolution not supported.
https://stackoverflow.com/questions/44764833/mediacodec-codecexception-in-samsung-galaxy-note-4
