### ISSUE TITLE
Unable to instantiate decoder 'AACEncoder'

### ISSUE THREAD

**Issue by H4M3DR** [pedroSG94/rtmp-rtsp-stream-client-java#613]
startStream crash on android 4.1.2 api version 16, huawei g525-u00.
crash will occur in  codec = MediaCodec.createByCodecName(encoder.getName()) line in prepareAudioEncoder function in AudioEncoder.java

you can produce the crash on genymotion emulator google galaxy nexus api 16 device.

**Comment by pedroSG94** [comment]
Can you show me a list of encoders?
```java
CodecUtil.showAllCodecsInfo();
```

**Comment by H4M3DR** [comment]
I don't have the device today but i can post it later. here is the emulator ones:

`06-28 10:25:30.341 1476-1476/com.sample.live I/Pedro: ----------------
    Name: OMX.google.mp3.decoder
    Type: audio/mpeg
    ----- Decoder info -----
    ----- -----
    ----- Audio info -----
    ----- -----
    ----------------
06-28 10:25:30.341 1476-1476/com.sample.live I/Pedro: ----------------
    Name: OMX.google.amrnb.decoder
    Type: audio/3gpp
    ----- Decoder info -----
    ----- -----
    ----- Audio info -----
    ----- -----
    ----------------
06-28 10:25:30.345 1476-1476/com.sample.live I/Pedro: ----------------
    Name: OMX.google.amrwb.decoder
    Type: audio/amr-wb
    ----- Decoder info -----
    ----- -----
    ----- Audio info -----
    ----- -----
    ----------------
06-28 10:25:30.345 1476-1476/com.sample.live I/Pedro: ----------------
    Name: OMX.google.aac.decoder
    Type: audio/mp4a-latm
    ----- Decoder info -----
    ----- -----
    ----- Audio info -----
    ----- -----
    ----------------
06-28 10:25:30.349 1476-1476/com.sample.live I/Pedro: ----------------
    Name: OMX.google.g711.alaw.decoder
    Type: audio/g711-alaw
    ----- Decoder info -----
    ----- -----
    ----- Audio info -----
    ----- -----
    ----------------
06-28 10:25:30.349 1476-1476/com.sample.live I/Pedro: ----------------
    Name: OMX.google.g711.mlaw.decoder
    Type: audio/g711-mlaw
    ----- Decoder info -----
    ----- -----
    ----- Audio info -----
    ----- -----
    ----------------
06-28 10:25:30.349 1476-1476/com.sample.live I/Pedro: ----------------
    Name: OMX.google.vorbis.decoder
    Type: audio/vorbis
    ----- Decoder info -----
    ----- -----
    ----- Audio info -----
    ----- -----
    ----------------
06-28 10:25:30.353 1476-1476/com.sample.live I/Pedro: ----------------
    Name: OMX.google.mpeg4.decoder
    Type: video/mp4v-es
    ----- Decoder info -----
    ----- -----
    ----- Video info -----
    Supported colors: 
    19
    Profile: 1, level: 1
    Profile: 1, level: 2
    Profile: 1, level: 4
    Profile: 1, level: 8
    Profile: 1, level: 16
    ----- -----
    ----------------
06-28 10:25:30.357 1476-1476/com.sample.live I/Pedro: ----------------
    Name: OMX.google.h263.decoder
    Type: video/3gpp
    ----- Decoder info -----
    ----- -----
    ----- Video info -----
    Supported colors: 
    19
    Profile: 1, level: 1
    Profile: 1, level: 2
    Profile: 1, level: 4
    Profile: 1, level: 16
    Profile: 8, level: 1
    Profile: 8, level: 2
    Profile: 8, level: 4
    Profile: 8, level: 16
    ----- -----
    ----------------
06-28 10:25:30.357 1476-1476/com.sample.live I/Pedro: ----------------
    Name: OMX.google.h264.decoder
    Type: video/avc
    ----- Decoder info -----
    ----- -----
    ----- Video info -----
    Supported colors: 
    19
    Profile: 1, level: 1
    Profile: 1, level: 2
    Profile: 1, level: 4
    Profile: 1, level: 8
    Profile: 1, level: 16
    Profile: 1, level: 32
    Profile: 1, level: 64
    Profile: 1, level: 128
    Profile: 1, level: 256
    Profile: 1, level: 512
    Profile: 1, level: 1024
    Profile: 1, level: 2048
    Profile: 1, level: 4096
    Profile: 1, level: 8192
    Profile: 1, level: 16384
    Profile: 1, level: 32768
    ----- -----
    ----------------
06-28 10:25:30.357 1476-1476/com.sample.live I/Pedro: ----------------
    Name: OMX.google.vpx.decoder
    Type: video/x-vnd.on2.vp8
    ----- Decoder info -----
    ----- -----
    ----- Video info -----
    Supported colors: 
    19
    ----- -----
    ----------------
06-28 10:25:30.357 1476-1476/com.sample.live I/Pedro: ----------------
    Name: OMX.google.aac.encoder
    Type: audio/mp4a-latm
    ----- Encoder info -----
    ----- -----
    ----- Audio info -----
    ----- -----
    ----------------
06-28 10:25:30.357 1476-1476/com.sample.live I/Pedro: ----------------
    Name: OMX.google.amrnb.encoder
    Type: audio/3gpp
    ----- Encoder info -----
    ----- -----
    ----- Audio info -----
    ----- -----
    ----------------
06-28 10:25:30.357 1476-1476/com.sample.live I/Pedro: ----------------
    Name: OMX.google.amrwb.encoder
    Type: audio/amr-wb
    ----- Encoder info -----
    ----- -----
    ----- Audio info -----
    ----- -----
    ----------------
06-28 10:25:30.357 1476-1476/com.sample.live I/Pedro: ----------------
    Name: OMX.google.h263.encoder
    Type: video/3gpp
    ----- Encoder info -----
    ----- -----
    ----- Video info -----
    Supported colors: 
    19
    21
    Profile: 1, level: 16
    ----- -----
    ----------------
06-28 10:25:30.357 1476-1476/com.sample.live I/Pedro: ----------------
    Name: OMX.google.h264.encoder
    Type: video/avc
    ----- Encoder info -----
    ----- -----
    ----- Video info -----
    Supported colors: 
    19
    21
    Profile: 1, level: 1
    Profile: 1, level: 2
    Profile: 1, level: 4
    Profile: 1, level: 8
    Profile: 1, level: 16
    Profile: 1, level: 32
    ----- -----
    ----------------
06-28 10:25:30.357 1476-1476/com.sample.live I/Pedro: ----------------
    Name: OMX.google.mpeg4.encoder
    Type: video/mp4v-es
    ----- Encoder info -----
    ----- -----
    ----- Video info -----
    Supported colors: 
    19
    21
    Profile: 4, level: 8
    ----- -----
    ----------------
06-28 10:25:30.357 1476-1476/com.sample.live I/Pedro: ----------------
    Name: OMX.google.flac.encoder
    Type: audio/flac
    ----- Encoder info -----
    ----- -----
    ----- Audio info -----
    ----- -----
    ----------------
06-28 10:25:30.357 1476-1476/com.sample.live I/Pedro: ----------------
    Name: AACEncoder
    Type: audio/mp4a-latm
    ----- Encoder info -----
    ----- -----
    ----- Audio info -----
    ----- -----
    ----------------
06-28 10:25:30.357 1476-1476/com.sample.live I/Pedro: ----------------
    Name: OMX.google.raw.decoder
    Type: audio/raw
    ----- Decoder info -----
    ----- -----
    ----- Audio info -----
    ----- -----
    ----------------
`

**Comment by pedroSG94** [comment]
Hi, 
I did a fix for it:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/e8eefb80e188fc35be2f45bcf14f00829fdd51d4
Anyway video encoder produce buffer without h264 startcode and this produce an error in SrsFlvMuxer. I'm looking a way to fix it.
https://stackoverflow.com/questions/30505875/how-to-use-software-codec-in-android-using-mediacodec/30506941

Also you need know that in my emulator I only can start audio encoder with 8000 sample rate and in mono (1 channel) and video encoder with 320x240 or less resolution. This is a limitation of that version of OMX google encoder (video an audio), nothing to do here.
