### ISSUE TITLE
how can add multiple textObjectFilterRender ?

### ISSUE THREAD

**Issue by reon69** [pedroSG94/rtmp-rtsp-stream-client-java#619]
I want to display text on the streaming screen.
One text is displayed using textObjectFilterRender. But when I add text, the previous text disappears. I want to display multiple texts using.
private void rtmpText(){
        TextObjectFilterRender textObjectFilterRender = new TextObjectFilterRender();
//        rtmpCamera1.getGlInterface().setFilter(0,textObjectFilterRender);
        textObjectFilterRender.setText(textOverlay, 50.0f, textOverlayColor);
        textObjectFilterRender.setDefaultScale(rtmpCamera1.getStreamWidth(),
                rtmpCamera1.getStreamHeight());
        textObjectFilterRender.setPosition(TranslateTo.CENTER);
//        mBaseObjectFilter.add(textObjectFilterRender);

        rtmpCamera1.getGlInterface().setFilter(textObjectFilterRender);

        spriteGestureController.setBaseObjectFilterRender(textObjectFilterRender); //Optional
    }

public class TextObjectFilterRender extends BaseObjectFilterRender {

  private List<TextStreamObject> mTextStreamList;
  private TextureLoader textureLoader = new TextureLoader();
  public TextObjectFilterRender() {
    super();
    streamObject = new TextStreamObject();
    mTextStreamList =  new ArrayList<>(); //cmkim test
  }

  @Override
  protected void drawFilter() {
    super.drawFilter();
    streamObjectTextureId = textureLoader.load(streamObject.getBitmaps());

    GLES20.glBindTexture(GLES20.GL_TEXTURE_2D, streamObjectTextureId[0]);
    //Set alpha. 0f if no image loaded.
    GLES20.glUniform1f(uAlphaHandle, streamObjectTextureId[0] == -1 ? 0f : alpha);
  }

  public void setText(String text, float textSize, int textColor) {
    setText(text, textSize, textColor, null);
  }

  public void setText(String text, float textSize, int textColor, Typeface typeface) {
    ((TextStreamObject) streamObject).load(text, textSize, textColor, typeface);
    shouldLoad = true;
    mTextStreamList.add((TextStreamObject) streamObject); //cmkim test
  }
}

**Comment by pedroSG94** [comment]
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Real-time-filters

**Comment by reon69** [comment]
thanks..
but ,I know multiple filter.
I want to add in TextStreamObject.
 public void load(String text, float textSize, int textColor, Typeface typeface) {
    numFrames = 1;
    imageBitmap = textAsBitmap(text, textSize, textColor, typeface);
    Log.i(TAG, "finish load text");
  }

**Comment by pedroSG94** [comment]
Do you want concatenate text to your filter?
For example:
```java
filter.setText("hello ");
filter.addMoreText("world");
```

**Comment by reon69** [comment]
Dear. pedro
Thanks for your advice.
I have a questions.
I know that numFilter set before create stream object.
But can't I add numFilter during RTMP streams?
onCreate() in my source
managerRender =  new ManagerRender();
private void createEffectfilter(int nType){
        if(mBaseObjectFilter.isEmpty() || mBaseObjectFilter ==null){
            mBaseObjectFilter =  new ArrayList<>();
        }
//        ManagerRender mr =  new ManagerRender();
        if(nType == EFFECTER_FILTER_TYPE_TEXT){
            TextObjectFilterRender textObjectFilterRender =  new TextObjectFilterRender();
            textObjectFilterRender.setText(textOverlay, 50.0f, textOverlayColor);
            textObjectFilterRender.setDefaultScale(rtmpCamera1.getStreamWidth(),
                    rtmpCamera1.getStreamHeight());
            textObjectFilterRender.setPosition(TranslateTo.CENTER);
            spriteGestureController.setBaseObjectFilterRender(textObjectFilterRender); //Optional
            rtmpCamera1.getGlInterface().setFilter(mEffectFilterIndex,textObjectFilterRender);
            mBaseObjectFilter.add(textObjectFilterRender);
            if(managerRender.getNumFilters() < mEffectFilterIndex){
                managerRender.addNumfilter(mEffectFilterIndex);
            }
        }else if(nType == EFFECTER_FILTER_TYPE_IMAGE){

        }
        mEffectFilterIndex++;
}
and added function in ManagerRender.java
public void addNumfilter(int num){
    baseFilterRender.add(new NoFilterRender());
  }
  public int getNumFilters(){
    return numFilters;
  }
  public void setNumFilters(int numfilter){
    numFilters = numfilter;
  }
but ,I had an execution error like below.
ava.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.pedro.encoder.input.gl.render.ManagerRender.setFilter(ManagerRender.java:100)
        at com.pedro.rtplibrary.view.OpenGlView.run(OpenGlView.java:155)

**Comment by pedroSG94** [comment]
No, you can't do it because you need re start opengl to change it because each filter position has a pointer to the next filter.
