### ISSUE TITLE
other problem in video encoder

### ISSUE THREAD

**Issue by liodali** [pedroSG94/rtmp-rtsp-stream-client-java#62]
W/MemoryDealer: madvise(0x622b4000, 114688, MADV_REMOVE) returned Operation not permitted
 W/System.err:     at com.pedro.encoder.video.VideoEncoder.access$1100(VideoEncoder.java:32)
W/System.err:     at com.pedro.encoder.video.VideoEncoder$1.run(VideoEncoder.java:245)
E/AndroidRuntime: FATAL EXCEPTION: Thread-511
                                                          Process: dali.dvr, PID: 20351
                                                          java.lang.IllegalStateException
                                                              at android.media.MediaCodec.getBuffers(Native Method)
                                                              at android.media.MediaCodec.getOutputBuffers(MediaCodec.java:556)
                                                              at com.pedro.encoder.video.VideoEncoder.getDataFromEncoder(VideoEncoder.java:427)
                                                              at com.pedro.encoder.video.VideoEncoder.access$1100(VideoEncoder.java:32)
                                                              at com.pedro.encoder.video.VideoEncoder$1.run(VideoEncoder.java:245)
                                                              at java.lang.Thread.run(Thread.java:841)

**Comment by pedroSG94** [comment]
Device model and API?

**Comment by liodali** [comment]
i'm using in my phone but when i back to the previous version of library the error disappear

**Comment by pedroSG94** [comment]
What version crash? what version work?

**Comment by liodali** [comment]
1.1.4 working fine but 1.1.5 crash

**Comment by pedroSG94** [comment]
Ok I will try see the differences. For now please clone my project and test my app. Tell me too device model and API used.

**Comment by liodali** [comment]
device model is samsung s3 and api 18

**Comment by pedroSG94** [comment]
VideoEncoder no change since I did your fix on thread.interrupt error, so error should be in Camera1Base. I did a library update with changes on Camera1Base that maybe solve your fail. (version 1.1.6)
Anyway try with my app and I can know if it is a implementation error.

**Comment by liodali** [comment]
i have new error in this at VideoEncoder.java: 474
java.lang.IllegalStateException at android.media.MediaCodec.releaseOutputBuffer(Native Method)

**Comment by liodali** [comment]
i think the problem from  me because i drop all  connection with server (i using nginx like media server) before i stop the stream

**Comment by liodali** [comment]
i have another question : you can explain to me the role of startpreview and how i cant use it because in my code 
i have to 2 surfaceview one for stream and other for normale camera

**Comment by pedroSG94** [comment]
startPreview is only for draw a preview if you want do it before start stream and stopPreview is used after stopStream if you want stop draw preview in your surfaceview.
when you see that crash? when you stop stream after drop connections?
If you don't drop connections all is working fine?
How do you drop connections? (I want reproduce the error)

**Comment by liodali** [comment]
yes  it working fine 
i make request to server to drop connection in specific channel
 can I for example record camera without stream to server  ?

**Comment by pedroSG94** [comment]
That feature is not added for now

**Comment by liodali** [comment]
ok thanks  pedro ;)

**Comment by pedroSG94** [comment]
How do you do request drop to nginx? I can't find a example

**Comment by liodali** [comment]
make http request like this : 
http://IP_ADR:1935/control/drop/client?app=name_app&name=channel_name
and in nginx.conf 
add this line in server{ ..... }
        location /control {
            rtmp_control all;
        }
see more : https://github.com/arut/nginx-rtmp-module/wiki/Control-module

**Comment by pedroSG94** [comment]
I reproduce the case with my Sansumg S7. I force method used for API < 21 in VideoEncoder and all is working fine.
When you drop connection library return you event on callback called onConnectionFailedRtmp and then I do stopStream and stopPreview (I use ExampleRtmpActivity class of my project, Default RTMP). Remember you will receive onDisconnectRtmp callback after that so you can't stopStream and stopPreview in that callback too.
I will continue test with other devices and tell you the result. The error could be on specific devices or slow devices.

**Comment by liodali** [comment]
ok pedro, i already stop stream in onConnectionFailedRtmp but i think the problem in device  and thanks ;)
