### ISSUE TITLE
I need to release all resources, is this the case?

### ISSUE THREAD

**Issue by icewst** [pedroSG94/rtmp-rtsp-stream-client-java#621]
I need to release all resources, is this the case?

stopStream
stopStreamRtp
stopRecord

**Comment by pedroSG94** [comment]
stopStreamRtp is called with stopStream but stopStream and stopRecord if you are streaming or recording is necessary like here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/defaultexample/ExampleRtmpActivity.java#L207
