### ISSUE TITLE
Need  to show audio Meter(VU Meter) how to get audio amplitude from rtmpcamera1

### ISSUE THREAD

**Issue by ansariatif** [pedroSG94/rtmp-rtsp-stream-client-java#622]
Hi Pedro,
I am looking audio amplitude from rtmpcamera1 for showing audio meter . 

in your library has this feature to get audio amplitude or rms_peak value.

**Comment by pedroSG94** [comment]
I haven't a way to get audio amplitude. But maybe you can crete a method to calculate it using PCM buffer from here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L765

**Comment by cryinrain69** [comment]
Hi @pedroSG94 
Does the current version support this audio meter feature?
Audio Meter is quite necessary for professional livestream users to know the signal/sound level.

**Comment by Rider02vn** [comment]
Hello.
I have the same need as above.
Have you found a way yet?

**Comment by pedroSG94** [comment]
Hello,

I added a CustomAudioEffect which support return the audio amplitude from microphone:
https://github.com/pedroSG94/RootEncoder/commit/7ddb05bfaa118e87feba40882c851369bae5fc7d
example code:
```kotlin
      val amplitudeEffect = AmplitudeEffect(object: AmplitudeEffect.Listener {
        override fun onAmplitude(value: Float) {
          //amplitude value from 0f to 100f. 
          //Avoid block this thread if you will do a heavy task
        }
      })
      (audioSource as? MicrophoneSource)?.setAudioEffect(amplitudeEffect)
      //start the listener thread
      amplitudeEffect.start()
      //stop the listener thread
      amplitudeEffect.stop()
```
It is not available in the last version. Code the code from the commit or wait for the next release if you want it.

**Comment by Rider02vn** [comment]
Hi.
I think this is a pretty useful feature.
Thank you very much.

**Comment by noho501** [comment]
Hi @pedroSG94 

Currently, the audio meter only receives data when recording is started. 
Is there a way to receive audio data and update the meter without starting the recording?

Any guidance on how to trigger meter updates independently of the recording process would be appreciated.

**Comment by pedroSG94** [comment]
Hello,

Currently I haven't a way to do it so maybe the best solution is get the audio source of the StreamBase and start it manually:
```kotlin
//call it any time after prepareAudio
genericStream.audioSource.start(object : GetMicrophoneData {
        override fun inputPCMData(frame: Frame) {
            //use here the custom filter to get meters
        }
      })
```
I think that you don't need worry about it because the audioSource change GetMicrophoneData callback inside StreamBase when start is called so when you call startRecord/startStream it will change automatically and the previous one is not called anymore.

Remember that you will need call start to audio source again if you want get frames after stopRecord and stopStream.
