### ISSUE TITLE
[Question] How cat to set auto focus mode off.

### ISSUE THREAD

**Issue by reon69** [pedroSG94/rtmp-rtsp-stream-client-java#623]
Dear. Pedro
I have a question.
I has used the RtmpCamear2 API for streaming broadcasting in OpenGl Surface view.
I want to auto focus mode off but can not to set  the auto focus off.
It does not supported in Camera2ApiManager.java
How can set to auto focus mode off at front and rear camera?
I has set false value of use feature in android manifest .xml

        android:name="android.hardware.camera"
        android:required="false"
   
        android:name="android.hardware.camera2"
        android:required="false"
  
        android:name="android.hardware.camera.autofocus"
        android:required="false"

**Comment by pedroSG94** [comment]
I added this feature to my last commit:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/f27cf4c372e9a6ceca04a90b0570d9362c1dedfd

**Comment by reon69** [comment]
Hi. Pedro
I have applied the last commit for camera auto focus setting.
but , auto focusing still working .

[auto focus.zip](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/4916313/auto.focus.zip)

**Comment by reon69** [comment]
Hi , Pedro.
thanks for your advice.
Auto focus setting working well  which has apply at the camera capture session callback function.

private void startPreview(CameraDevice cameraDevice) {
    try {
      final List<Surface> listSurfaces = new ArrayList<>();
      Surface preview = addPreviewSurface();
      if (preview != null) listSurfaces.add(preview);
      if (surfaceEncoder != preview && surfaceEncoder != null) listSurfaces.add(surfaceEncoder);

      cameraDevice.createCaptureSession(listSurfaces, new CameraCaptureSession.StateCallback() {
        @Override
        public void onConfigured(@NonNull CameraCaptureSession cameraCaptureSession) {
          Camera2ApiManager.this.cameraCaptureSession = cameraCaptureSession;
          try {
            CaptureRequest captureRequest = drawSurface(listSurfaces);
            if (captureRequest != null) {
              cameraCaptureSession.setRepeatingRequest(captureRequest,
                  faceDetectionEnabled ? cb : null, cameraHandler);
              Log.i(TAG, "Camera configured");
            } else {
              Log.e(TAG, "Error, captureRequest is null");
            }
            // auto focus disable when started streaming
            **disableAutoFocus();**
          } catch (CameraAccessException | NullPointerException e) {
            Log.e(TAG, "Error", e);
          } catch (IllegalStateException e) {
            reOpenCamera(cameraId != -1 ? cameraId : 0);
          }
        }

And recover camera auto focus when the close camera
public void closeCamera(boolean resetSurface) {
    resetCameraValues();
           ...
          ....
  if(!isAutoFocusEnabled()){
       enableAutoFocus();
     }
}

**Comment by reon69** [comment]
Hi.Pedro.
I have a question.
Can I auto focus off only the front camera and keep the auto focus setting on the Back camera?

**Comment by pedroSG94** [comment]
The only way to do it is switch camera to front camera and disable autofocus in the next line:
```java
rtmpCamera1.switchCamera();
if (rtmpCamera1.isFrontCamera()) rtmpCamera1.disableAutoFocus();
else rtmpCamera1.enableAutoFocus();
```
I will fix autofocus disable before startPreview in next commit.
