### ISSUE TITLE
Use RtmpFromFile with ExoPlayer

### ISSUE THREAD

**Issue by MohammadRezaei92** [pedroSG94/rtmp-rtsp-stream-client-java#625]
I want to prepare a file for streaming and play it with exo player as same time, but when exo player is using MediaCodec, RtmpFromFile crashes because MediaCodec is being used by exo player. What is the solution?

**Comment by pedroSG94** [comment]
You can use rtmpFromFile with preview:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/FromFileBase.java#L85
The reason about this crash could be that you exceed your maximum mediacodec instances.

**Comment by MohammadRezaei92** [comment]
> You can use rtmpFromFile with preview:
> https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/FromFileBase.java#L85
> The reason about this crash could be that you exceed your maximum mediacodec instances.

Thank you @pedroSG94 it works but, how do I pause and resume preview when activity pause and resume?

**Comment by pedroSG94** [comment]
This could work for you:
- When your surface is destroyed check if you are streaming and save your actual video time:
```java
 @Override
  public void surfaceDestroyed(SurfaceHolder surfaceHolder) {
    if (rtmpFromFile.isStreaming()) {
      streaming = true;
      videoTime = rtmpFromFile.getVideoTime();
      rtmpFromFile.stopStream();
    }
}
```
- In surface changed check if you was streaming and start stream automatically. After that move video to your old time:
```java
@Override
  public void surfaceChanged(SurfaceHolder surfaceHolder, int i, int i1, int i2) {
    if (streaming) {
      startStream();
      rtmpFromFile.moveTo(videoTime);
    }
  }
```

**Comment by pedroSG94** [comment]
I have done a commit to add replaceView method to fromfile mode for this.
Basically you need add:
- When surfaceDestroyed callback is called:
```java
rtmpFromFile.replaceView(context);
```
- When surfaceChaged is called:
```java
rtmpFromFile.replaceView(openglview);
```
Also you have playAudiodevice() and stopAudioDevice() if you want enable audio.
Try with this gradle and le tme know if it is working for you:
```gradle
implementation 'com.github.pedroSG94:rtmp-rtsp-stream-client-java:cdbb522f84'
```

**Comment by MohammadRezaei92** [comment]
> ```groovy-gradle
> implementation 'com.github.pedroSG94:rtmp-rtsp-stream-client-java:cdbb522f84'
> ```

You are awesome @pedroSG94 . Thank you
