### ISSUE TITLE
Framerate not being saved in video file?

### ISSUE THREAD

**Issue by ElectronHerder** [pedroSG94/rtmp-rtsp-stream-client-java#626]
I have an nginx video streaming server that saves the video files into .flv format. It then converts them to .mp4 format. The streams sent from your rtplibrary:1.5.2 work just fine. The transcoding goes properly. I still have an Android app build using that version and it works correctly.

But, when I updated to version 1.7.1, something strange happened. In the original .flv file, the video is still visible. But when it is transcoded to .mp4, the audio is present but the screen is black and the file information shows a framerate of 1000 fps.

I just updated to your version 1.8.4 and it still gives black video that does not seem to have the correct frame rate in it.

I have studied the information on the .flv files. The big difference seems to be that in the .flv files that work correctly, the Frame Rate Mode is Constant.

In the newer version of the library, I am getting a Frame Rate Mode that is Variable.

But, my code sets a constant bitrate and frame rate. So, perhaps the information for the constant frame rate is not being sent? I am getting the same result whether I put the parameters in the prepareVideo() or use the prepareEncoders() method. I have also removed the parameters from prepareAudio() and prepareVideo() to allow for default settings and get the same result.

CODE:

```
@Override
public void surfaceChanged(SurfaceHolder surfaceHolder, int i, int i1, int i2) {
	if (!rtmpCamera1.isStreaming()) {
		if (rtmpCamera1.isRecording() || (rtmpCamera1.prepareAudio(48 * 1024, 16000, false, false, false) && rtmpCamera1.prepareVideo(720, 480, 6, 256 * 1024, false, CameraHelper.getCameraOrientation(mContext))) ) {
//		if (rtmpCamera1.isRecording() || prepareEncoders()) {
			try {
				rtmpCamera1.startStream(stream_url);
			} catch (Exception e) {
				e.printStackTrace();
			}
		} else {
			Toast.makeText(this, "Error preparing stream, This device cant do it",
					Toast.LENGTH_SHORT).show();
		}
	}
	rtmpCamera1.startPreview();
}



private boolean prepareEncoders() {
	int width = 720;                    // Default 1920 x 1080
	int height = 480;
	int etFps = 6;                    // up to 30
	int etVideoBitrate = 256 * 1024;    // range 256 to 2500
	Boolean cbHardwareRotation = false;
	int etAudioBitrate = 48 * 1024;        // default 128
	int etSampleRate = 16000;            // default 44100
	Boolean isStereo = false;
	Boolean cbEchoCanceler = false;
	Boolean cbNoiseSuppressor = false;

	try {
		return rtmpCamera1.prepareVideo(width, height, etFps, etVideoBitrate,
				cbHardwareRotation, CameraHelper.getCameraOrientation(mContext))
				&& rtmpCamera1.prepareAudio(etAudioBitrate,
				etSampleRate,
				isStereo, cbEchoCanceler,
				cbNoiseSuppressor);
	} catch (Exception e) {
		e.printStackTrace();
		Log.e(TAG, "prepareEncoders() failed");
		return false;
	}
}
```

**Comment by pedroSG94** [comment]
Are you using SurfaceView or OpenGlView?
About constant frame rate, maybe you means this:
```java
videoFormat.setInteger(MediaFormat.KEY_BITRATE_MODE, MediaCodecInfo.EncoderCapabilities.BITRATE_MODE_CBR);
```
You can add this line here to test:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L116
But I don't remember add this to any version. I will check differences between versions to know reason but my first suspect is changes in VideoEncoder to support async mode. Try with this version to confirm that:
- Last version without async encoders: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/releases/tag/1.6.7
- First version with async encoders: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/releases/tag/1.6.8

**Comment by ElectronHerder** [comment]
UPDATE:

I am using OpenGlView.

I am loading your library through the Gradle: implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:1.8.4'

I am using Android Studio. I'm not sure how to edit your source code then import it into my project, instead of importing it via Gradle. Do I have to make a .jar file and import it as a library or something?

I have been experimenting with this for several days. I have gone back to your code version 1.6.3 but can't go any further back, due to a bunch of other dependencies that break in earlier versions. 

I am trying to get access to the video streaming server to see if I can force it to use a constant framerate in its encoding. I believe that would solve the problem. The problem might not really be your video code. I will report back when I know more.

**Comment by ElectronHerder** [comment]
I was able to force FFMPEG to convert the video files using a constant framerate. This seems to have resolved the problem, in my initial tests. I don't know whether your video code has anything to do with the issue or not and will further experiment. 

Closing this issue for now. Thanks so much for all you do!
