### ISSUE TITLE
Flushing the stream when user stops streaming

### ISSUE THREAD

**Issue by Tim-Kindberg** [pedroSG94/rtmp-rtsp-stream-client-java#628]
Hi Pedro,

I'm streaming using your SrsFlvMuxer class and testing with Facebook Live. If I stop streaming and then start again, the last 10 seconds (or whatever Facebook's buffer is) of the previous session plays before the video in the new stream.

I don't see a flush() call in your library.  I stop by calling stop() on the instances of your classes that I'm using: OffScreenGlThread, VideoEncoder (plus my custom audio class). If I call stop() on the instance of SrsFlvMuxer, the whole app crashes. 

What is the correct procedure to flush the stream as far as your software is concerned? Is there a way of flushing whatever has been buffered at the Facebook end - or whatever streaming site is being used e.g. YouTube?

Many thanks.

**Comment by pedroSG94** [comment]
I never see that. In my library when you call stop method all buffers are released.
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/net/ossrs/rtmp/SrsFlvMuxer.java#L322
Also close session command is called:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L361
Maybe you need call deletestream command in facebook (let me know if this is working to add it in my library). Try add this:
```java
Command deleteStream = new Command("deleteStream", 0);
deleteStream.getHeader().setChunkStreamId(ChunkStreamInfo.RTMP_CID_OVER_STREAM);
deleteStream.getHeader().setMessageStreamId(currentStreamId);
deleteStream.addData(new AmfNull());
sendRtmpPacket(deleteStream);
```
Here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L376

Other solution could be use facebook API to create a new event.
