### ISSUE TITLE
Not able to reconnect to stream

### ISSUE THREAD

**Issue by rahul-chugh97** [pedroSG94/rtmp-rtsp-stream-client-java#629]
I am streaming to our streaming server setup, The streaming works fine
When the stream is connected and I disconnect from my wifi (can also be case when publisher has slow or intermittent internet), the app receives callback onConnectionFailedRtmp and stream disconnects. 
When I connect back to internet, and try to reconnect it fails to connect with following reason "Error configure stream, publish permitted failed"

there are a lot of discarded frames in Logcat. Maybe the stream buffer is not getting cleared. Is there any way to flush the stream buffer?
Help me out

**Comment by pedroSG94** [comment]
Buffer is cleared when you call stopStream method:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/net/ossrs/rtmp/SrsFlvMuxer.java#L322
Can you tell me server used to reproduce it?

**Comment by rahul-chugh97** [comment]
It is a ngnix media server.
Whenever I reconnect after network has failed, error logged is "RtmpConnection: handleRxInvoke(): onStatus NetStream.Publish.BadName"
Can you help me knowing when this occurs?

**Comment by pedroSG94** [comment]
Try add this to file configuration:
https://github.com/arut/nginx-rtmp-module/wiki/Directives#drop_idle_publisher

**Comment by rahul-chugh97** [comment]
Thanks `drop_idle_publisher 15s;` worked for me like a charm.
