### ISSUE TITLE
Stream display issue

### ISSUE THREAD

**Issue by mhackeras** [pedroSG94/rtmp-rtsp-stream-client-java#63]
example using facebook
it seems package not sent to facebook continiously. except if i use screen.. 
if i dont use screen it sends only audio packets.. when it sends video packages too.. maybe this is the issue that causes video to buffer on facebook even on youtube too.
i use recommended settings for facebook too.
and i use prepareaudio-video with custom settings.
also is it right to send audio packets when i have it disabled?
also need some declerations on hardware rotation , dpi. whether should i use that.? and what are some proper values for these?

**Comment by pedroSG94** [comment]
No send all time video packets is normal in this mode because [MediaProjection](https://developer.android.com/reference/android/media/projection/MediaProjection.html) class only draw (render) in the surface setted on createVirtualDisplay method when your device refresh your screen. So if your device is blocked or no used your device doesn't need refresh and surface is not renderer.

When you use disableAudio method it only set buffer lenght of audio to 11 (adts padding) and this do the mute effect, no real totally disable microphone, the microphone is still working but the buffer filled hasn't any audo data.

hardware rotation -> rotate stream result. (Some [Mediacodec](https://developer.android.com/reference/android/media/MediaCodec.html) devices don't support it and ignore the parameter)
dpi -> dpi used to render surface used in createVirtualDisplay. Max and min value depend of your screen device.

**Comment by mhackeras** [comment]
yeah thats what i thought... but  i think it causes the stream to stop.. its like fb or youtube waiting for video packet... so i think there is a need to find a way to render screen all the time so as to send video packets even when no screen change.. i look a little bit deep.. i wonder if u could show me where to look in ur workspace to find some solution

**Comment by mhackeras** [comment]
do you think this is the issue that causing video stream to buffer at times on facebook and youtube..?
if so one hacky way it would be to.. send same video packet when mediaprojection stops producing..

**Comment by pedroSG94** [comment]
You can do a little thing but I'm not sure if this will work fine.
You can go to DisplayBase class and create a queue that get frames and from getH264 callback and duplicate that Bytebuffer and MediacoderInfo and save it in the queue then you can send to the SrsFlvMuxer object the duplicate Bytebuffer and MediacoderInfo all time and change it when you receive a new buffer from getH264 callback.

I will try do it this week to know if the result is good and add to library if all is working fine.

**Comment by mhackeras** [comment]
this is the reason streams stops.. cause of no render and now video packet send. so cause i really not have the time to dig so much deep in ur code :/ i ll wait till u make changes and i ll surely test as soon as u do some fixes..
if i find some time to play with ur code it will be only at weekend :/ but as i said i am noob at this yet so it needs some time for me :/

**Comment by pedroSG94** [comment]
My idea is not working. I will need find other solution.

**Comment by mhackeras** [comment]
ok bro.. i am already playing a little with your code.. i am looking also a little bit in bitrates... so i hope you find a workaround.. i ll think of a solution too.

**Comment by pedroSG94** [comment]
I had a idea that work. You can create a notification with animation to force screen render.
code example:
```java
private void initNotification() {
    Notification.Builder notificationBuilder =
        new Notification.Builder(this)
            .setSmallIcon(R.drawable.notification_anim)
            .setContentTitle("MayUp")
            .setContentText("Downloading new tools")
            .setTicker("Downloading in progress");
    notificationBuilder.setAutoCancel(true);
    ((NotificationManager) getSystemService(NOTIFICATION_SERVICE)).notify(12345, notificationBuilder.build());
  }
```
xml notification (it should be in drawable folder and use a icon of my project):
```xml
<?xml version="1.0" encoding="utf-8"?>
<animation-list android:id="@+id/selected"
    android:oneshot="false"
    xmlns:android="http://schemas.android.com/apk/res/android"
    >
  <item android:drawable="@drawable/icon_camera" android:duration="500" />
  <item android:drawable="@drawable/icon_camera_off" android:duration="500" />
</animation-list>
```

**Comment by mhackeras** [comment]
nice one bro.. its a good workaround for this issue.. i ll add this to my notification and i can report back if there any performance issues etc. thanks sir
