### ISSUE TITLE
Resume record when app moves from background to foreground

### ISSUE THREAD

**Issue by KhushbooR** [pedroSG94/rtmp-rtsp-stream-client-java#632]
I want to pause recording if any user presses home button of android device during live streaming and resume record on same channel when app comes to foreground.

**Comment by pedroSG94** [comment]
You only need stop stream when you press home button saving a variable that indicate you that after surfaceChanged callback is called (this means that activity was resumed and you can start stream), you can start stream using same channel.

**Comment by KhushbooR** [comment]
By using this method, (stop stream on home button click and start stream when activity resumed), timer on twitch gets reset. That I understand is due to the new connection established. Is there any way to resume that timer on twitch?

**Comment by pedroSG94** [comment]
Yes, that is a new connection. I will try develop a way to reconnect doing a resume.
