### ISSUE TITLE
How to resolve Surface preview camera aspect ratio

### ISSUE THREAD

**Issue by punnoket** [pedroSG94/rtmp-rtsp-stream-client-java#633]
First of all, Thank you for the brilliant library 👍 .
I have a problem surface preview camera shows the wrong aspect ratio
When I use OpenGlView then aspect ratio is work but the quality of preview is low. How to resolve it? (Screenshot below)
FYI. I use RtmpCamera2 class because the quality better than RtmpCamera1 class

[RtmpCamera1](https://ibb.co/ZWhbNm3)

[OpenGlView with RtmpCamera2](https://ibb.co/VJWX4Ym)

[Surface with RtmpCamera2](https://ibb.co/tbhDg96)

And when I use RtmpCamera2, video preview is shown portrait but show wrong orientation in Facebook live 
[RtmpCamera2 on Facebook](https://ibb.co/QnL0fsT)

**Comment by pedroSG94** [comment]
Did you tried this line?
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/res/layout/activity_open_gl.xml#L12

**Comment by punnoket** [comment]
Thank you for your response.

I have already used that code you suggest in OpenGlView and an aspect ratio it works and resolves wrong orientation on Facebook but the quality of preview still low.

Could you please explain more about upgrade camera resolution?

**Comment by pedroSG94** [comment]
Use higher resolution. For example try with 1080p
```java
rtmpCamera2.startPreview(CameraHelper.Facing.BACK, 1920, 1080);
```

**Comment by punnoket** [comment]
Big thanks to support. So very easy to resolve it !!

Ok my all problem is clear. 
:D

**Comment by pedroSG94** [comment]
Remember that you need set that resolution to prepareVideo method to keep that resolution:
```java
rtmpCamera2.prepareVideo(1920, 1080, 30, 3000 * 1024, false, CameraHelper.getCameraOrientation(this));
```

**Comment by punnoket** [comment]
Thank you for your response, I found this quality low issue after start stream.

Should I set "prepareVideo" before call "startStream" right? 

I found a little problem when start stream a video preview will be blink before a record.

**Comment by pedroSG94** [comment]
That is normal because camera is reopened. The reason is that you can choose different resolution in startPreview an in prepareVideo, so camera is reopened to set prepareVideo resolution.
