### ISSUE TITLE
Samsung S8 issue

### ISSUE THREAD

**Issue by mylaimani** [pedroSG94/rtmp-rtsp-stream-client-java#635]
Hi, we are facing one strange problem. I had set the video bitrate as 2000000

This is working fine in all the mobiles (streaming at 2mbps) when we try to stream through Samsung S8 it ignores 2mbps, streams at 20mbps 

My code is like this

@Override
    public void onConnectionSuccessRtmp() throws ExecutionException, InterruptedException {
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                Toast.makeText(StreamingActivity.this, "Connection success", Toast.LENGTH_SHORT).show();
                bitrateAdapter = new BitrateAdapter(new BitrateAdapter.Listener() {
                    @Override
                    public void onBitrateAdapted(int bitrate) {
                        rtmpCamera1.setVideoBitrateOnFly(2000000);
                    }
                });
                bitrateAdapter.setMaxBitrate(rtmpCamera1.getBitrate());

            }
        });
    }

**Comment by pedroSG94** [comment]
Are you using SurfaceView? In that case, Can you try with OpenGlview?
Also try with sofware encoder to discard problems with your video encoder:
```java
//before prepareVideo
rtmpCamera1.setForce(CodecUtil.Force.SOFTWARE, CodecUtil.Force.FIRST_COMPATIBLE_FOUND);
```

**Comment by mylaimani** [comment]
I am using OpenGlview

I will try the solution you had given.
