### ISSUE TITLE
How to setup server side code for RTSP from file.

### ISSUE THREAD

**Issue by amir102Khan** [pedroSG94/rtmp-rtsp-stream-client-java#636]
I want to stream a video file. I got the code for client side for streaming through file using this library. But not getting server side code for streaming the file i.e the code which will select the file and stream it.

**Comment by pedroSG94** [comment]
I'm not sure if you means this but.
You need download a server and install it in a computer:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Media-servers-tested
After that you need play stream in other device using a player like VLC. I did a project example of VLC stream player in this project but you can download official app in play store. My example:
https://github.com/pedroSG94/vlc-example-streamplayer

**Comment by amir102Khan** [comment]
Thank you for your reply. But I solve my problem earlier only using your
server library.
And this library is really awesome. Thanks very much for your time.

Md Amir Khan

**Comment by pedroSG94** [comment]
Good to know. 
Issue closed, open other issue if you have more questions.
