### ISSUE TITLE
[Question]Display web view page on streaming screen

### ISSUE THREAD

**Issue by reon69** [pedroSG94/rtmp-rtsp-stream-client-java#637]
Dear. pedro
I need a your advice.
I want to display the webview page on the broadcast screen.
The web view page displays a timer.
Is there a filter render that can display a timer without bitmap convert?
The image below is before applying the filter.

![timer_webview](https://user-images.githubusercontent.com/66772439/89008271-5c1f9800-d345-11ea-81d0-5372b77e8f0b.png)

**Comment by pedroSG94** [comment]
Did you tried with [AndroidViewFilter](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L146)?
It works using canvas of the view. I recommend you add a layout with ImageView and TextView for this.

**Comment by reon69** [comment]
Dear. pedro
spriteGestureController cannot be applied.
I have modified the AndrodViewFilterRender like SurfaceFilterRender for display web view screen. 
like below.
my code:
public void onPageFinished(WebView view, String url)
        {
            super.onPageFinished(view, url);
            int width = PopkonUtils.convertDpToPixels(LiveStreamingActivity.this, 200.0f);
            int height = PopkonUtils.convertDpToPixels(LiveStreamingActivity.this, 100.0f);
            RelativeLayout.LayoutParams preSetLayoutParams = new RelativeLayout.LayoutParams(width,height);
            preSetLayoutParams.addRule(RelativeLayout.CENTER_IN_PARENT);
            presetWebView.setLayoutParams(preSetLayoutParams);
            presetWebView.setBackgroundColor(0);
            if(view != null){
                AndroidViewFilterRender androidViewFilterRender = new AndroidViewFilterRender();
                rtmpCamera1.getGlInterface().setFilter(3, androidViewFilterRender);
                androidViewFilterRender.setView(presetWebView);
//                androidViewFilterRender.setScale(1.0f,1.0f);
                androidViewFilterRender.setScale(50.0f,50.0f);
//                rtmpCamera1.getGlInterface().setFilter(3, androidViewFilterRender);
                **spriteGestureController.setBaseObjectFilterRender(androidViewFilterRender);**

            }
            presetWebView.setVisibility(View.INVISIBLE);
        }
AndroidViewFilterRender code :
public class AndroidViewFilterRender extends **BaseObjectFilterRender** {
 }
and modify scale function as below
 public void setScale(float scaleX, float scaleY) {
  **mSprite.scale(scaleX,scaleY);
  squareVertexSurface.put(mSprite.getTransformedVertices()).position(0);**
  }


When I run the app, I get an error like below.
 java.lang.RuntimeException: drawFilter end: glError 1281
        at com.pedro.encoder.utils.gl.GlUtil.checkGlError(GlUtil.java:129)
        at com.pedro.encoder.input.gl.render.filters.BaseFilterRender.draw(BaseFilterRender.java:55)
        at com.pedro.encoder.input.gl.render.ManagerRender.drawOffScreen(ManagerRender.java:61)
        at com.pedro.rtplibrary.view.OpenGlView.run(OpenGlView.java:129)
        at java.lang.Thread.run(Thread.java:764)

How can I use spriteGestureController in AndroidViewFilterRender?

**Comment by pedroSG94** [comment]
This is working now: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/b4fbe0f907bf2898e7c612984938cf5a93d3abbb
Try with this gradle (last commit):
```
implementation 'com.github.pedroSG94:rtmp-rtsp-stream-client-java:b4fbe0f907'
```

**Comment by reon69** [comment]
Dear. pedro
thank you so much.
I will try to work that commit.
After applying the filter, I was working on Android native because of the problem of modifying the web view location.
