### ISSUE TITLE
SurfaceManager error

### ISSUE THREAD

**Issue by MohammadRezaei92** [pedroSG94/rtmp-rtsp-stream-client-java#639]
I've got this error on FileStream with openGL
`Make sure the SurfaceView or associated SurfaceHolder has a valid Surface`
`com.pedro.encoder.input.gl.SurfaceManager.eglSetup (SurfaceManager.java:129)`

**Comment by pedroSG94** [comment]
Did you get this error always?
Can you share a code example to reproduce this error?

**Comment by MohammadRezaei92** [comment]
I found this error in my crash report system.
I didn't face this error personally.

**Comment by MohammadRezaei92** [comment]
This error happens when the surface replaced with the offScreen surface before the stream started.

**Comment by pedroSG94** [comment]
I did 2 commits for decoders that should solve both errors:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commits?author=pedroSG94

**Comment by MohammadRezaei92** [comment]
> I did 2 commits for decoders that should solve both errors:
> https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commits?author=pedroSG94

Doesn't work yet.
I still have this error.

**Comment by MohammadRezaei92** [comment]
I have another error on prepare File Stream with openGL
`Attempt to invoke virtual method 'android.content.Context android.view.SurfaceView.getContext()' on a null object reference
com.pedro.rtplibrary.base.FromFileBase.<init> (FromFileBase.java:88)
com.pedro.rtplibrary.rtmp.RtmpFromFile.<init> (RtmpFromFile.java:44)
`

**Comment by pedroSG94** [comment]
Your OpenGlView is null. Check it

**Comment by MohammadRezaei92** [comment]
I need a solution to prepare file stream with offScreen or null openGl view and set it later.

**Comment by pedroSG94** [comment]
This should be related with android lifecycle. Can you share a code example to find error?

**Comment by MohammadRezaei92** [comment]
I have a `StreamService` class for stream works and an Activity that bind to this service and show preview of the stream

**Activity:**

```
override fun surfaceChanged(holder: SurfaceHolder?, format: Int, width: Int, height: Int) {
        streamService?.onPreviewCreate(openGlView)
    }

override fun surfaceDestroyed(holder: SurfaceHolder?) {
        streamService?.onPreviewDestroyed()
    }

override fun surfaceCreated(holder: SurfaceHolder?) {
    }
```

**Service:**

```
fun onPreviewDestroyed() {
        rtmpFromFile?.replaceView(this)
        rtmpFromFile?.stopAudioDevice()
  }

fun onPreviewCreate(openGlView: OpenGlView) {
        rtmpFromFile?.replaceView(openGlView)
        rtmpFromFile?.playAudioDevice()
    }
```
` rtmpFromFile = RtmpFromFile(openGlView, this, this, this)`

**Comment by pedroSG94** [comment]
That part is fine. How did you bind service with activity?
Did you tried using a companion object like I did in my background example?

**Comment by MohammadRezaei92** [comment]
I tried with your solution but, I still have this error
`Make sure the SurfaceView or associated SurfaceHolder has a valid Surface`

**Comment by pedroSG94** [comment]
check if surface is valid with this:
```java
openglview.holder.surface.isValid()
```
