### ISSUE TITLE
Swicthing camera back eats next click on the view where survaceView belongs

### ISSUE THREAD

**Issue by sergeych** [pedroSG94/rtmp-rtsp-stream-client-java#640]
STR:

- run the samoe
- select Default RTMP (RTSP, practically, everywhere)
- click "switch camera" - it DOES NOTHING
- click it again: it switches OK
- click again, it switches OK
- click again - it does nothing.

Last 3 steps could be repeated infinitely. When it switches camera for the

**Comment by pedroSG94** [comment]
This is working for me. 
Can you tell me device model?
Can you check with other device?

**Comment by sergeych** [comment]
Very, very strange. Maybe the emulator bug: it runs on emulator android R 10+ google api image, but on my phone runs like a charm (thought I don't have any phone with api 30). So let's think it's an emulator bug. Lost 5 hours trying to fix ;)
