### ISSUE TITLE
 Cordova issues rtmp

### ISSUE THREAD

**Issue by Mate20x** [pedroSG94/rtmp-rtsp-stream-client-java#647]
Can I start the camera on cordova?

Push stream rtmp?

**Comment by Mate20x** [comment]
Hello @pedroSG94

thank you for your reply

You provide the cordova plugin URL (https://github.com/disono/cordova-rtmp-rtsp-stream)

Can be used after testing

Disono author hasn't maintained the plugin for a long time

No author found

Have serious problems

The image quality of the rtmp stream is poor

I don't know how to change the Java code?

Can you help me make some changes?

https://github.com/disono/cordova-rtmp-rtsp-stream/tree/master/src/android/com/webmons/disono/rtmpandrtspstreamer

**Comment by pedroSG94** [comment]
Sorry but as I told you I can't give you support for this.
I need learn about cordova to test this and I don't want do it.
I only can tell you that you can change resolution and bitrate used here:
https://github.com/disono/cordova-rtmp-rtsp-stream/blob/master/src/android/com/webmons/disono/rtmpandrtspstreamer/RTMPActivity.java#L290
like this:
```java
//width, height, fps, video bitrate.
//if you want more, 1080p could be = 1920, 1080, 30, 4000 * 1024, false, 0
if (rtmpCameral.prepareAudio() && rtmpCameral.prepareVideo(1280, 720, 30, 2500 * 1024, false, 0)) {
```

**Comment by Mate20x** [comment]
Hello @pedroSG94

It is very effective to modify the code you provided

rtmp image quality has been greatly improved

Thank you for your assistance and help

grateful

**Comment by Mate20x** [comment]
Hello @pedroSG94

Mobile push streaming live (vertical)

The audience watched the live broadcast incorrectly

As attached picture

Don't know how to solve it?

![2020-08-29_060408](https://user-images.githubusercontent.com/46883314/91618781-e6e3c900-e9bd-11ea-896e-15d3dc94271e.jpg)

**Comment by pedroSG94** [comment]
You can change rotation in that prepareVideo method:
```java
//supported 90, 180, 270, 0
//recommended use CameraHelper.getCameraOrientation(this); to get correct rotation automatically
int rotation = 90;
if (rtmpCameral.prepareAudio() && rtmpCameral.prepareVideo(1280, 720, 30, 2500 * 1024, false, rotation)) {
```
If you can't use cameraHelper because you are using an old version of the library you can copy this method in the class to replace it:
```java
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/CameraHelper.java#L25
```

**Comment by Mate20x** [comment]
@pedroSG94 

I am a super newbie

Cordova In RTMPActivity.java
Line 59 Code : private final String[] _orient = new String[]{"90", "180", "270", "0"};
![2020-08-29_073911](https://user-images.githubusercontent.com/46883314/91622665-d7b74800-e9ca-11ea-997d-c2426d8854a9.jpg)

Don't know how to use
cameraHelper

Request assistance

**Comment by pedroSG94** [comment]
Copy CameraHelper file from my project:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/master/encoder/src/main/java/com/pedro/encoder/input/video
To Cordova project in this folder:
https://github.com/disono/cordova-rtmp-rtsp-stream/tree/master/src/android/com/webmons/disono/rtmpandrtspstreamer

Replace package name of CameraHelper class. This line:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/CameraHelper.java#L1
To:
``` java
package com.webmons.disono.rtmpandrtspstreamer;
```

Add CameraHelper to the method:

```java
if (rtmpCameral.prepareAudio() && rtmpCameral.prepareVideo(1280, 720, 30, 2500 * 1024, false, CameraHelper.getCameraOrientation(this))) {
```

**Comment by Mate20x** [comment]
@pedroSG94 

Your CameraHelper.java teaching is very helpful to me

Can be used like magic

I will help more people in need

Thanks again for your enthusiasm

One thing to add is that you need to detect the user's hand-held direction in RTMPActivity.java

code:
setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED);

![333](https://user-images.githubusercontent.com/46883314/91632291-76b36280-ea12-11ea-8a77-b566159aaaa3.jpg)

![4](https://user-images.githubusercontent.com/46883314/91632298-7c10ad00-ea12-11ea-9df8-fc4131666e8c.jpg)
