### ISSUE TITLE
Probmlem rtsp Display and Permission

### ISSUE THREAD

**Issue by adelhoss** [pedroSG94/rtmp-rtsp-stream-client-java#65]
hi pedro
i three week ago u help me and use rtspdisplay library and send stream to rtsp server
but now only i added two edittext to one activity user can enter ip address for server
but app crash ..
I send log and my Project in next post (Uploading ...)

**Comment by adelhoss** [comment]
this is my log cat : 
https://www.mediafire.com/file/775f000lznbd75j/logcat1.txt
this is my project : 
https://www.mediafire.com/file/jr8u7l1lksa0mq2/MyApplication.zip
I use try catch in all my part of code but system crashed ....
i use try catch and Toast can see error message but do not show error and app crash

**Comment by adelhoss** [comment]
I Do not change anything code in your library
only added another activity ...

**Comment by adelhoss** [comment]
I connected my phone to android studio 
and this my log only Error 
https://www.mediafire.com/file/5crd7hrs6vr4dju/logcat2.txt
only only one time app run without problem after install
second run app VideoEncoder Exceotion and crashed app

**Comment by adelhoss** [comment]
only one time app Work good .
after run app for two time or re run app crashed .
VideoEncoder throw Exception Show in Logcat send to you .

**Comment by adelhoss** [comment]
**`10-11 14:33:18.559 2977-3103/? E/InputMethodManagerService: Perflock object null
10-11 14:33:18.757 2512-16347/? E/OMXNodeInstance: getConfig(9d002f7:Exynos.AVC.Encoder, ConfigAndroidIntraRefresh(0x6f60000a)) ERROR: UnsupportedIndex(0x8000101a)
10-11 14:33:18.809 31373-31373/com.example.alihp.myapplication E/Pedro: size: 640X480
10-11 14:33:18.809 31373-31373/com.example.alihp.myapplication E/Pedro: valid surface?? true
10-11 14:33:18.882 31373-31627/com.example.alihp.myapplication E/AndroidRuntime: FATAL EXCEPTION: Thread-7
                                                                                 Process: com.example.alihp.myapplication, PID: 31373
                                                                                 java.lang.IllegalStateException
                                                                                     at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
                                                                                     at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2568)
                                                                                     at com.pedro.encoder.video.VideoEncoder$2.run(VideoEncoder.java:312)
                                                                                     at java.lang.Thread.run(Thread.java:762)**
10-11 14:33:18.887 2512-2710/? E/OMXNodeInstance: getConfig(9d002f9:Exynos.AVC.Encoder, ConfigAndroidIntraRefresh(0x6f60000a)) ERROR: UnsupportedIndex(0x8000101a)
10-11 14:33:18.928 2503-2999/? E/APM_AudioPolicyManager: startInput(550) failed: other input 542 already started
10-11 14:33:18.928 31373-31373/com.example.alihp.myapplication E/AudioRecord: start() status -38
10-11 14:33:18.929 31373-31373/com.example.alihp.myapplication E/Pedro: size: 640X480
10-11 14:33:18.929 31373-31373/com.example.alihp.myapplication E/Pedro: valid surface?? true
10-11 14:33:18.949 2432-2432/? E/VirtualDisplaySurface: VirtualDisplaySurface is deleted,WFDMode 0
10-11 14:33:18.954 8555-8555/? E/InputMethodService: Unexpected null in startExtractingText : mExtractedText = null, input connection = InputConnectionWrapper{idHash=#4385f5f mMissingMethods=}
10-11 14:33:18.965 2503-31615/? E/audio_hw_primary: select_devices: adev->outputs[1] - device 2 / adev->out_device 2
10-11 14:33:19.031 31373-31373/com.example.alihp.myapplication E/ViewRootImpl@58b1e12[Main2Activity]: ViewRootImpl #2 Surface is not valid.
10-11 14:33:19.063 2503-27973/? E/echo_reference_processing: remove_echoReference_effect: error - reset preproc_list
10-11 14:33:19.063 2503-27973/? E/echo_reference_processing: remove_echoReference_effect: error - reset preproc_list
10-11 14:33:19.063 2503-27973/? E/echo_reference_processing: remove_echoReference_effect: error - reset preproc_list
10-11 14:33:19.067 2503-27973/? E/audio_hw_primary: adev_close_input_stream, set jack_in to null
10-11 14:33:19.098 2512-8598/? E/BufferQueueProducer: [GraphicBufferSource] dequeueBuffer: BufferQueue has been abandoned
                                                      
                                                      [ 10-11 14:33:19.099  2432: 2432 D/         ]
                                                      NULL == surf->write_back_color_buffer
10-11 14:33:19.100 2512-16347/? E/BufferQueueProducer: [GraphicBufferSource] dequeueBuffer: BufferQueue has been abandoned
10-11 14:33:19.100 2432-2432/? E/DisplayDevice: eglSwapBuffers(0x1, 0xea62ca20) failed with 0x0000300d
10-11 14:33:19.112 8555-8555/? E/KeyboardInfoUtils: getInstance start
10-11 14:33:19.112 8555-8555/? E/KeyboardInfoUtils: sendSIPInformation state:6  isAbstractKeyboardView : true
10-11 14:33:19.112 8555-31668/? E/KeyboardInfoUtils: sending null keyboardInfo as SIP is closed
10-11 14:33:19.117 2512-12444/? E/BufferQueueProducer: [GraphicBufferSource] dequeueBuffer: BufferQueue has been abandoned`

**Comment by adelhoss** [comment]
When App Crashed But Toast is Show Define in RtspChecker show
but app stoped and crashed .

**Comment by adelhoss** [comment]
I removed first activity ....
and run only your activity ....
one time run ok ...
but two time and other time : TWO START NOW (Permission For Display Record) SHOW
(I unchecked Display For next Time )
and i check always app crashed ....
but when no checeked always app good work but two display Permission show ...
Why after close app and exit from app no stop thread ?
How Stop before Thread and then new thread ....

**Comment by pedroSG94** [comment]
This is your problem implementation no library error (Your project crash for me too). Activity that I shared with you work fine, your code is not my Activity you have more changes.
**Remember get permissions in runtime.** You have a example on MainActivity in my project.
This is a little adaptation if you want use FirstActivity and send ip server:
```java
package com.example.alihp.myapplication;

import android.app.Activity;
import android.content.Intent;
import android.media.projection.MediaProjection;
import android.media.projection.MediaProjectionManager;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.util.Log;
import android.view.Surface;
import android.view.SurfaceView;
import android.widget.Toast;
import com.pedro.rtplibrary.rtsp.RtspDisplay;
import com.pedro.rtsp.rtsp.Protocol;
import com.pedro.rtsp.utils.ConnectCheckerRtsp;

public class Main2Activity extends AppCompatActivity implements ConnectCheckerRtsp {

  private MediaProjectionManager mediaProjectionManager;
  private SurfaceView surfaceView;
  private RtspDisplay rtspDisplay;
  private String ipcam;
  private String ipserver;
  
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main2);
    rtspDisplay = new RtspDisplay(this, Protocol.TCP, this);
    mediaProjectionManager = (MediaProjectionManager) getSystemService(MEDIA_PROJECTION_SERVICE);
    ipcam = getIntent().getStringExtra("ipcamera").toString();
    ipserver = getIntent().getStringExtra("ipserver").toString();
    startActivityForResult(mediaProjectionManager.createScreenCaptureIntent(), 179);
  }

  @Override
  public void onActivityResult(int requestCode, int resultCode, Intent data) {
    if (requestCode == 179 && resultCode == Activity.RESULT_OK) {
      if (rtspDisplay.prepareAudio() && rtspDisplay.prepareVideo()){
        rtspDisplay.setAuthorization("adel", "eng123456");
        rtspDisplay.startStream("rtsp://" + ipserver + ":1414/live/android_test");
        int width = rtspDisplay.getStreamWidth();
        int height = rtspDisplay.getStreamHeight();
        Log.e("Pedro", "size: " + width + "X" + height);
        Surface surface = rtspDisplay.getStreamSurface();
        Log.e("Pedro", "valid surface?? " + (surface != null));
        MediaProjection mediaProjection =
            mediaProjectionManager.getMediaProjection(resultCode, data);
        mediaProjection.createVirtualDisplay("Stream Display", width,
            height, 320, 0, surface, null, null);
      }
    } else {
      Toast.makeText(this, "Permissions no available", Toast.LENGTH_SHORT).show();
    }
  }

  @Override
  public void onConnectionSuccessRtsp() {
    runOnUiThread(new Runnable() {
      @Override
      public void run() {
        Toast.makeText(Main2Activity.this, "Connection success", Toast.LENGTH_SHORT).show();
      }
    });
  }

  @Override
  public void onConnectionFailedRtsp() {
    runOnUiThread(new Runnable() {
      @Override
      public void run() {
        Toast.makeText(Main2Activity.this, "Connection failed", Toast.LENGTH_SHORT).show();
        rtspDisplay.stopStream();
      }
    });
  }

  @Override
  public void onDisconnectRtsp() {
    runOnUiThread(new Runnable() {
      @Override
      public void run() {
        Toast.makeText(Main2Activity.this, "Disconnected", Toast.LENGTH_SHORT).show();
      }
    });
  }

  @Override
  public void onAuthErrorRtsp() {
    runOnUiThread(new Runnable() {
      @Override
      public void run() {
        Toast.makeText(Main2Activity.this, "Auth error", Toast.LENGTH_SHORT).show();
      }
    });
  }

  @Override
  public void onAuthSuccessRtsp() {
    runOnUiThread(new Runnable() {
      @Override
      public void run() {
        Toast.makeText(Main2Activity.this, "Auth success", Toast.LENGTH_SHORT).show();
      }
    });
  }
}
```

**Comment by adelhoss** [comment]
I only send data from edittext with intent to second activity...
i use your activity only one time ok ....
after install one time ok ....
please est for two time three time after install

**Comment by pedroSG94** [comment]
Activity in my last post work all time for me.

**Comment by adelhoss** [comment]
ok i test now and result .....

**Comment by adelhoss** [comment]
you removed permission parted ?
how i can request permission from user ?

**Comment by adelhoss** [comment]
rtsp display no need to permission ?
you set permission Manually ?

**Comment by pedroSG94** [comment]
I tested setting permisison manually but I recomend you set permission on FirstActivity.

**Comment by adelhoss** [comment]
ok thanks . i get permission in FirstActivity and send result for you .

**Comment by adelhoss** [comment]
I use Last Activity and Set Permission Manually ....
but Two Time Show Start Record screen and app crash

**Comment by adelhoss** [comment]
Why Two Time Show Permission For Screen Record Show 
then touch on Start NOW APP SCREEN .
AND SAME LAST LOGCAT SEND TO YOU .
Video ENCODER throw Exception

**Comment by adelhoss** [comment]
I Used DisplayBase Class Alter You For Me ...
you remember alter DisplayClass Base For ME ?
I do not touch your Last Activity send For me : but Show Two Time Screen Record Request and APP CRASH

**Comment by adelhoss** [comment]
Solved Problem ....
I Moved All Extra Code : Request Permission - Rotate Screen - kepp screen on TO FIRST ACTIVITY 
PROBLEM SOLVED 
THANK YOU
