### ISSUE TITLE
Endpoint malformed, should be: rtmp://ip:port/appname/streamname

### ISSUE THREAD

**Issue by e9ab98e991ab** [pedroSG94/rtmp-rtsp-stream-client-java#650]
总是校验不通过
![微信截图_20200824154903](https://user-images.githubusercontent.com/30852521/91017906-6de11c00-e621-11ea-9e1c-eca89919aa8f.png)

**Comment by e9ab98e991ab** [comment]
![image](https://user-images.githubusercontent.com/30852521/91018020-9832d980-e621-11ea-8f7c-a0d946205b71.png)
请问这个是什么问题呢？

**Comment by pedroSG94** [comment]
You endpoint is malformed.
Your endpoint is :
rtmp:192.168.34.219:8888/aa/aa
And should be (you forgot //):
rtmp://192.168.34.219:8888/aa/aa

**Comment by e9ab98e991ab** [comment]
Are all the clients in the demo? I want to convert from rtsp to rtmp to push streaming. What should I do?

**Comment by pedroSG94** [comment]
I answered you in the other issue. This seems solved closing.. 
Reopen it if you have a problem related or open other issue.
