### ISSUE TITLE
Crash on Dailymotion stream 

### ISSUE THREAD

**Issue by Goule** [pedroSG94/rtmp-rtsp-stream-client-java#653]
Hello,

I'm trying to stream on Dailymotion but I got a crash in production and an error in debug : `RtmpConnection: Caught SocketException while reading/decoding packet, shutting down: Unknown AMF data type`

Here is an exemple URL : 
```
rtmp://publish.dailymotion.com/publish-dm/
x7vtc7q?auth=4WB1CMAYO6sOSDCiP7w3PHeln4l5w6ubsPN7lUnpl0
```
This RTMP URL work with restream for exemple. 

Have you any idea how to fix it ? 

Thanks

**Comment by pedroSG94** [comment]
Can you reproduce it always or it only crash sometimes?

**Comment by Goule** [comment]
It’s crashing always

**Comment by pedroSG94** [comment]
I did an account in dailymotion but I can't found live stream section in my panel. Is necessary any requeriments to stream?

**Comment by Goule** [comment]
Unfortunately yes it is necessary that the channel is verified by Dailymotion. You can test with the RTMP link I put above, it must be valid to reproduce the error each time

**Comment by pedroSG94** [comment]
Ok. I will test it and let you know when problem is fixed.

**Comment by Goule** [comment]
Ok thanks 🙏🏻
Tell me if you need another URL, I don’t know how many time the URL will be valid

**Comment by pedroSG94** [comment]
Now I got connection success. Try with last commit and let me know if all is working fine (I only can confirm you that connection is success, you need tell me if you can see stream).
Fixed here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/98bb3c0bfecb6f4370e4beac3a8bdcb254330804

**Comment by Goule** [comment]
Hello,
It's working now, many thanks ! 

What was the cause ? Is that Dailymotion was doing something wrong ?

**Comment by pedroSG94** [comment]
It was because in my connect packet tcUrl ended with "/" and dailymotion doesn't like it (it was fine for other servers). As you can see in the commit I only did a method to delete that "/" if exists.
After that, dailymotion send me a reject connection and a close command. After close command dailymotion close connection producing an error reading packet, because inputstream is closed and you can't read it (Anyway it was already catched so it didn't produce any crash).

**Comment by Goule** [comment]
Ok thanks ! 
I close the issue :)

**Comment by Goule** [comment]
Hello @pedroSG94,

I got this crash since some day : 

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
       at java.lang.String.contains(String.java:2196)
       at com.github.faucamp.simplertmp.io.RtmpConnection.handleRxInvoke(RtmpConnection.java:666)
       at com.github.faucamp.simplertmp.io.RtmpConnection.handleRxPacketLoop(RtmpConnection.java:563)
       at com.github.faucamp.simplertmp.io.RtmpConnection.access$000(RtmpConnection.java:44)
       at com.github.faucamp.simplertmp.io.RtmpConnection$1.run(RtmpConnection.java:189)
       at java.lang.Thread.run(Thread.java:764)
```

Do you think this is related to your fix ? Or maybe when use typing an empty url ?

**Comment by pedroSG94** [comment]
Fixed:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/9bca5f3d7cd69f0bbf4b9204861c7ab9a5b334a3

**Comment by Goule** [comment]
Thanks !
