### ISSUE TITLE
Video encoder signal error problem

### ISSUE THREAD

**Issue by korcanergun** [pedroSG94/rtmp-rtsp-stream-client-java#654]
Hi,

Thanks for library.

When i tried to run your rtsp display example, i am having encoder problem only on Samsung phones. Logcat and available encoders are on [https://pastebin.ubuntu.com/p/HmBx9KtRnD/](url)

Also i runned CodecUtils.showAllCodecsInfo and result are on [https://pastebin.ubuntu.com/p/rfwpQxGtNp/](url)

Do you have any idea why is this happening ?

Best,

**Comment by pedroSG94** [comment]
Only in display mode or also with camera?
Did you try using OpenGL enabled? (In constructor set Boolean to true)

**Comment by pedroSG94** [comment]
I can see in logcat that your resolution is 311x640 resolution must be divisible by 2. Try with 312 or 310 instead of 311.

**Comment by korcanergun** [comment]
@pedroSG94 you are best :) it started working after resolution update. thanks again
