### ISSUE TITLE
Certain devices stream with audio frequency of 32000 

### ISSUE THREAD

**Issue by mkrn** [pedroSG94/rtmp-rtsp-stream-client-java#655]
Some devices (Samsung Galaxy S10 Lite on Android 10, Google Pixel 4 XL) 
stream with AAC LC | Bitrate 70 Kb/s | Frequency 32000

This results in some very poor sound quality.

Is there a way to configure frequency?

Code:
```
return rtmpCamera2.prepareVideo(1280, 720, VIDEO_FPS, DEFAULT_BITRATE, false, 2, CameraHelper.getCameraOrientation(this), 8, 0x800)
            && rtmpCamera2.prepareAudio();
```

Thanks in advance

**Comment by pedroSG94** [comment]
Hi,

You can use prepareAudio method with params:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera2Base.java#L268
Where sampleRate is frequency that you mentioned. I recommend you this params:
```java
prepareAudio(128 * 1000, 44100, true);
```

**Comment by mkrn** [comment]
Thank you. Sample rate it is.
