### ISSUE TITLE
Switch between rtmpCamera and rtspCamera

### ISSUE THREAD

**Issue by fpcxsun** [pedroSG94/rtmp-rtsp-stream-client-java#656]
How to switch between rtmpCamera and rtspCamera without stopPreview?
It will cause the preview screen to interrupt.
Any better way?
Thanks.

**Comment by pedroSG94** [comment]
No without create a new class. You can mix both (RtmpCamera and RtspCamera) in a new class for this purpose. You only need add rtspClient and srsFlvMuxer and select one with a new method:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtmp/RtmpCamera1.java
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtsp/RtspCamera1.java

**Comment by fpcxsun** [comment]
Thank you, I'll try it
