### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by Mate20x** [pedroSG94/rtmp-rtsp-stream-client-java#657]
Hello @pedroSG94 

I moved from Cordova to Java

No Java development experience, super novice

use pedroSG94 (rtmp-rtsp-stream-client-java)

I refer to the example on GIT RTMP

The code still has an error

Can you solve it for me?

My English expression is not very good.. Please forgive me

build.gradle(:app)

![123](https://user-images.githubusercontent.com/46883314/91644934-6ed7da80-ea73-11ea-9baa-ff515c8ac634.jpg)

Error:
![2020-08-30_032137](https://user-images.githubusercontent.com/46883314/91644585-04716b00-ea70-11ea-81ed-6554b2eb7f56.jpg)

**Comment by pedroSG94** [comment]
I can't help you more. This isn't an issue or question related with the library. You need learn about java and Android SDK first.
Anyway you have an example here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/defaultexample/ExampleRtmpActivity.java

**Comment by Mate20x** [comment]
Your message is very helpful

After exploring Java

Using the URL example you provided, the program can run

Surprised and successful

Are there other files (activity_main.xml)

Demo xml **SurfaceView** template?

![2020-08-31_135521](https://user-images.githubusercontent.com/46883314/91687197-bce30000-eb91-11ea-84ad-d192ef313700.jpg)

**Comment by pedroSG94** [comment]
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/master/app/src/main/res/layout
