### ISSUE TITLE
Occasionally there will be a black border on the left or right

### ISSUE THREAD

**Issue by icewst** [pedroSG94/rtmp-rtsp-stream-client-java#658]
![1](https://user-images.githubusercontent.com/7521027/91813326-26800e80-ec65-11ea-8a99-14fcb0afa05f.png)
![3](https://user-images.githubusercontent.com/7521027/91814347-9216ab80-ec66-11ea-979c-0a8cf355b738.png)

Normally, there is no black border on the left and right.
Occasionally there will be a black border on the left or right.Error

**Comment by pedroSG94** [comment]
Can you tell me device screen resolution and stream/record resolution?
If you use multiple resolutions let me know it, because maybe only 1 fail.

**Comment by icewst** [comment]
> 您能告诉我设备屏幕分辨率和流/记录分辨率吗？
> 如果您使用多种分辨率，请告诉我，因为也许只有1种失败。

device 2400x1080
use 1920x1080

**Comment by icewst** [comment]
> device screen resolution and stream/record resolution?

device screen resolution   2400x1080
stream/record resolution  1920x1080

**Comment by pedroSG94** [comment]
I was testing with a device with same screen resolution and this error seems that is your notch, not a black border. 
You should have this problem always if you use an app without notch support in landscape or portrait and depend if you rotate it left or right, you have the notch in different position.

Try disable notch in device settings before start stream and check if this solve the problem for you.

**Comment by icewst** [comment]
> notch

Thinks

**Comment by icewst** [comment]
> I was testing with a device with same screen resolution and this problem seems that is your notch, not a black border.
> You should have this problem always if you use an app without notch support in landscape or portrait and depend if you rotate it left or right, you have the notch in different position.
> 
> Try disable notch in device settings before start stream and check if this solve the problem for you.

Thinks!

**Comment by pedroSG94** [comment]
I think this issue is closed, reopen it if you need it or create another one.
