### ISSUE TITLE
Can we capture both internal and microphone audio above Android 10?

### ISSUE THREAD

**Issue by parthivmistri** [pedroSG94/rtmp-rtsp-stream-client-java#661]
I'm Using Display Service and streaming games via RTMP.

Issues I'm facing are if the user enables an in-game microphone, the stream doesn’t capture Audio at all.

I have tried both the way.

```
prepareInternalAudio(196 * 1024, 44100, true);
prepareAudio(196 * 1024, 44100, true, false, false);
```

For the above Android 10 internal Audio captures in-game sound but I want to capture the user's microphone also.

@pedroSG94 Can you help me with this?

**Comment by parthivmistri** [comment]
I'm Using Display Service and streaming games via RTMP.

Issues I'm facing are if the user enables an in-game microphone, the stream doesn’t capture Audio at all.

I have tried both the way.

```
prepareInternalAudio(196 * 1024, 44100, true);
prepareAudio(196 * 1024, 44100, true, false, false);
```

For the above Android 10 internal Audio captures in-game sound but I want to capture the user's microphone also.

@pedroSG94 Can you help me with this?

**Comment by pedroSG94** [comment]
For now, only one audio source is supported.

You can try create your own class and mix both audio sources with this method, but I can't confirm you that it is working (not tested):
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/utils/PCMUtil.java

**Comment by parthivmistri** [comment]
Thanks for the Reply. I'll check on the above solution.

Also, one question is it even possible that 2 Apps simultaneously record audio with a microphone?

Let’s take an example of PUBG if the user switches on the camera through PUBG then what happens to our microphone Audio capture? Currently, It's not recording anything in this case.

**Comment by pedroSG94** [comment]
No, microphone is blocked by the first app that enable it. Same with camera.
If you have 2 microphones this is possible (somes devices got it) but you can't know which is used by others apps.

I recommend you test it yourself because maybe this is supported in somes devices marks or maybe not (This is Android). 
A way to test could be enable background stream and call to that devices to know if both apps is working or record audio with an external app, etc.

**Comment by parthivmistri** [comment]
Sure, I'll test it. 
I think this is it, if I need more help, I'll re-open the issue closing it for now. 
Thanks

**Comment by ulohani90** [comment]
@pedroSG94 : Can you please share a  little insight on which class are you talking to creat and how the mixing of two audio sources will be done?
Thanks

**Comment by pedroSG94** [comment]
You can try with something like this:
```java
rtmpCamera1.setCustomAudioEffect(new CustomAudioEffect() {
      @Override
      public byte[] process(byte[] pcmBuffer) {
        //Mix 2 audio buffer and return result. The result must have same size that original buffer.
        return pcmBuffer;
      }
    });
```
You only need send your second audio source in this method and mix both buffers. You can try use PCMUtil to mix both buffers.
