### ISSUE TITLE
We are facing Play back issue with iOS while streaming using nginx server on RTMPS protocol but works with Android 

### ISSUE THREAD

**Issue by yodesh87** [pedroSG94/rtmp-rtsp-stream-client-java#663]
We are using below parameter for publishing video on RTMPS url 

bitrate = 1200 * 1024;
width = 640;
height = 480;
fps =: 30,
iFrameInterval = 2
formatVideoEncoder = FormatVideoEncoder.SURFACE

We are try to play it using HLS and nginx server it works well for both Android as well as iOS.
When we try to play it using RTMPS low latency protocol using nginx server it works only for  Android but fails for iOS.

Our RTMPS setup works perfectly fine for iOS and Android if we try to publish video using FFMPEG utility for publishing on RTMPS server.

Could  you please guide us to resolve it .

**Comment by pedroSG94** [comment]
I think that video profile could be related:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/375

**Comment by mkrn** [comment]
Yes, I would suggest explicitly setting 1) Profile 2) Level 3) Audio sampling rate 4)Audio bitrate 
Otherwise some android phones choose some very strange settings like High 1.0  32000 kHz, 71 kbps, which sometimes can not play on iOS
