### ISSUE TITLE
Flag MediaCodec.BUFFER_FLAG_KEY_FRAME is never seted

### ISSUE THREAD

**Issue by IgorGiroti** [pedroSG94/rtmp-rtsp-stream-client-java#664]
Hi, 
I'm using the lib in a custom camera, witch have a Android 5.1 Lollipop instaled. 
I have compiled and installed the full project for test, and the stream works perfectly in Wowza Cloud, but i can't record the video when i click in "Record" button. I have noticied that the video file just "start" but not send any data, creating a mp4 file with 0 bytes of size.

After futher investigations, i have noticied that the condition "videoInfo.flags == MediaCodec.BUFFER_FLAG_KEY_FRAME" in the class recordVideo(RecordController.java) is always false (with logcat i noticied that videoInfo.flags returns a 264 value).

In the first time i suspected that the issue is in Android 5.1, but I have tried in other Android device( Samsung galaxy J1, with Android 5.1 Lollipop too), but works perfectly (stream and record at same time, wich is my goal).

I'm using the CustomRTSP example, but this happens with other examples too.

Someone has a ideia what is going on?

Thanks in advance!

UPDATE: If i comment the line "videoInfo.flags == MediaCodec.BUFFER_FLAG_KEY_FRAME", i'm able to record a video, but if I try stream at the same time, the app crashs

UPDATE 2: I did a logcat to see the flags in recordVideo class, here is the result

D/RecordTest(30328): Actual Flag 258
D/RecordTest(30328): Actual Flag 265
D/RecordTest(30328): Actual Flag 264
D/RecordTest(30328): Actual Flag 264
D/RecordTest(30328): Actual Flag 264
D/RecordTest(30328): Actual Flag 264
D/RecordTest(30328): Actual Flag 264
D/RecordTest(30328): Actual Flag 264
D/RecordTest(30328): Actual Flag 264
D/RecordTest(30328): Actual Flag 264
D/RecordTest(30328): Actual Flag 264
D/RecordTest(30328): Actual Flag 264
D/RecordTest(30328): Actual Flag 264
D/RecordTest(30328): Actual Flag 264
D/RecordTest(30328): Actual Flag 264
D/RecordTest(30328): Actual Flag 264
D/RecordTest(30328): Actual Flag 264
D/RecordTest(30328): Actual Flag 264
D/RecordTest(30328): Actual Flag 264
D/RecordTest(30328): Actual Flag 264
D/RecordTest(30328): Actual Flag 264
D/RecordTest(30328): Actual Flag 264

We can see that the flag is never 1 (MediaCodec.BUFFER_FLAG_KEY_FRAME)

**Comment by IgorGiroti** [comment]
I forgot to say, i'm using the CustomRTSP example, but this happens in other examples too.

**Comment by pedroSG94** [comment]
For now, we can try fix record flag reading h264 header. In [RecordController](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/util/RecordController.java) class:
```java
@RequiresApi(api = Build.VERSION_CODES.JELLY_BEAN_MR2)
  public void recordVideo(ByteBuffer videoBuffer, MediaCodec.BufferInfo videoInfo) {
    if (status == Status.STARTED && videoFormat != null && audioFormat != null) {
      int type = videoBuffer.array()[4] & 0x1F;  //check h264 key frame
      if (videoInfo.flags == MediaCodec.BUFFER_FLAG_KEY_FRAME || type == 5) {
        videoTrack = mediaMuxer.addTrack(videoFormat);
        audioTrack = mediaMuxer.addTrack(audioFormat);
        mediaMuxer.start();
        status = Status.RECORDING;
        if (listener != null) listener.onStatusChange(status);
      }
    } else if (status == Status.RESUMED && videoInfo.flags == MediaCodec.BUFFER_FLAG_KEY_FRAME) {
      status = Status.RECORDING;
      if (listener != null) listener.onStatusChange(status);
    }
    if (status == Status.RECORDING) {
      updateFormat(this.videoInfo, videoInfo);
      mediaMuxer.writeSampleData(videoTrack, videoBuffer, this.videoInfo);
    }
  }
```

Can you tell me device model and print your encoders?
```java
for (String s: CodecUtil.showAllCodecsInfo()) {
      Log.i("Pedro", s);
}
```
Let me know if this is working for you without crash to upload a commit.

**Comment by IgorGiroti** [comment]
Thanks for the fast answer.

The app crashs when I start the record with this fix.

Here is the log of the encoders:
[logs.txt](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/5170525/logs.txt)

the device is a custom device android  based on MediaTek 6580.

**Comment by pedroSG94** [comment]
Can you share logcat error?

**Comment by pedroSG94** [comment]
Ok. Try this:
```java
 private boolean isKeyFrame(ByteBuffer videoBuffer) {
    byte[] header = new byte[5];
    videoBuffer.get(header, 0, header.length);
    if ((header[4] & 0x1F) == 5) {  //h264
      return true;
    } else {
      return false;
    }
  }
  
  @RequiresApi(api = Build.VERSION_CODES.JELLY_BEAN_MR2)
  public void recordVideo(ByteBuffer videoBuffer, MediaCodec.BufferInfo videoInfo) {
    if (status == Status.STARTED && videoFormat != null && audioFormat != null) {
      if (videoInfo.flags == MediaCodec.BUFFER_FLAG_KEY_FRAME || isKeyFrame(videoBuffer)) {
        videoTrack = mediaMuxer.addTrack(videoFormat);
        audioTrack = mediaMuxer.addTrack(audioFormat);
        mediaMuxer.start();
        status = Status.RECORDING;
        if (listener != null) listener.onStatusChange(status);
      }
    } else if (status == Status.RESUMED && videoInfo.flags == MediaCodec.BUFFER_FLAG_KEY_FRAME) {
      status = Status.RECORDING;
      if (listener != null) listener.onStatusChange(status);
    }
    if (status == Status.RECORDING) {
      updateFormat(this.videoInfo, videoInfo);
      mediaMuxer.writeSampleData(videoTrack, videoBuffer, this.videoInfo);
    }
  }
```

**Comment by IgorGiroti** [comment]
I'm answer for the first fix problem, here is the logcat that i have get:
[logs.txt](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/5170823/logs.txt)
Now I will try this second option and let you know if still crashing

**Comment by IgorGiroti** [comment]
Now it's working! I was able to record and stream at the same time! Thank you very much!

**Comment by pedroSG94** [comment]
Great!

I will push a commit with this changes soon.

**Comment by pedroSG94** [comment]
Fixed here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/04c76192c9e58daa7bb80afc885add45edd7051d
