### ISSUE TITLE
Turn On/Off Audio while display streaming

### ISSUE THREAD

**Issue by vuleanh** [pedroSG94/rtmp-rtsp-stream-client-java#669]
Hi Pedro, this is a great library. Thank you!!!
I got a question:
Is there any option to turn on/off audio while streaming?

**Comment by pedroSG94** [comment]
Hello,

Try this:

```java
if (!rtmpCamera1.isAudioMuted()) { 
  rtmpCamera1.disableAudio();
} else {
  rtmpCamera1.enableAudio();
}
```

**Comment by vuleanh** [comment]
@pedroSG94  Found it. Many thanks for your awesome work!
