### ISSUE TITLE
RtmpCamera2 cannot zoom to `maxZoom`

### ISSUE THREAD

**Issue by CubitSpeed** [pedroSG94/rtmp-rtsp-stream-client-java#671]
`RtmpCamera2` when attempting to zoom to the bounds of `maxZoom`, the preview will freeze and sometimes crash. It would appear the value returned by `getMaxZoom()` is incorrect.

`RtmpCamera1` does not have this issue and works as expected. (I know the API is a bit different)

This can most easily be tested by changing `app/src/main/java/com/pedro/rtpstreamer/customexample/RtmpActivity.java` to use `RtmpCamera2`

(tested on multiple android devices)

**Comment by pedroSG94** [comment]
Fixed: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/ac8ddd61502c19a5571246b55e91c3c118295faa

**Comment by CubitSpeed** [comment]
Thanks, works perfectly now. Thank you for the blazing fast response
