### ISSUE TITLE
MetaTag

### ISSUE THREAD

**Issue by mylaimani** [pedroSG94/rtmp-rtsp-stream-client-java#672]
I am trying pass meta data for my live streaming, the meta data will contain batsman and bowlers details. Later after the live streaming is completed, I want to edit the MP4 format video based on meta data. 

Is there any way to do that

**Comment by pedroSG94** [comment]
You have 2 ways.
- Change packets header if you want change metadata in real time.
- Add info in connection packets:
RTMP:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/github/faucamp/simplertmp/io/RtmpConnection.java#L348
RTSP:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtsp/src/main/java/com/pedro/rtsp/rtsp/CommandsManager.java

After that, you need modify server to extract it.
