### ISSUE TITLE
Audio issue with streaming while doing a video call.

### ISSUE THREAD

**Issue by ulohani90** [pedroSG94/rtmp-rtsp-stream-client-java#673]
Hi. First of all Thank you for this awesome library. I am using it for the streaming feature in my app.

 Now I have to build a feature where a person can get over a video call with another person and stream the screen as well as the video call at the same time. 
For video calling I am using Agora's video calling service. After integration the issue that I faced was with the Audio i.e I could here my sound in the stream but my sound was not going in the video call and also the other person's sound from video call was not received at my end and also did not go in the stream.

Can you please suggest something over here that could solve the problem?

Thanks in advance!!

**Comment by pedroSG94** [comment]
You can't open microphone two times. Same with camera.
The first library that handle microphone will block it until it is released.
One solution could be use same microphone instance for both libraries, but I don't know if you can extract audio buffers from Agora or send buffers to Agora
