### ISSUE TITLE
Stream filter quality 

### ISSUE THREAD

**Issue by Goule** [pedroSG94/rtmp-rtsp-stream-client-java#675]
Hello,

I'm trying to add image filter into the stream but I'm facing to some quality issue. 

I'v tested two kind of filters : 
- Android native filter with view like `AndroidViewFilterRender` : resulting a bad filter quality and unreadable text on the image.
- Taking a bitmap image from a native view and use ImageObjectFilterRender to add it on filter : working with better quality than the native filters

The second solution work well, but the bitmap generation marking lag the interface, so this is not a really good solution. 

Here is the code  :

```kotlin
private fun loadBitmapFromView(v: View): Bitmap? {
    val b: Bitmap = Bitmap.createBitmap(v.width, v.height, Bitmap.Config.ARGB_8888)
    val c = Canvas(b)
    v.layout(v.left, v.top, v.right, v.bottom)
    v.draw(c)
    return b
}
```

And here is how I put the filter when I got the bitmap 

```kotlin
rtmpCamera2?.let {
    val imageObjectFilterRender = ImageObjectFilterRender()
     it.glInterface.setFilter(2, imageObjectFilterRender)
     imageObjectFilterRender.apply {
     setImage(bitmap.copy(bitmap.config, true))
     setPosition(TranslateTo.CENTER)
}
```

Have you any idea how to improve the bitmap capture or how to improve the quality of the native filter ? 

Thanks

**Comment by pedroSG94** [comment]
I recommend you use a thread or coroutine to do it:
```java
private fun loadBitmapFromView(v: View): Deferred<Bitmap> = GlobalScope.async(Dispatchers.IO) {
                val b: Bitmap = Bitmap.createBitmap(v.width, v.height, Bitmap.Config.ARGB_8888)
                val c = Canvas(b)
                v.layout(v.left, v.top, v.right, v.bottom)
                v.draw(c)
                b
    }

    private fun test() {
        lifecycleScope.launch {
            val bitmap = loadBitmapFromView(view).await()
            rtmpCamera2?.let {
                val imageObjectFilterRender = ImageObjectFilterRender()
                it.glInterface.setFilter(2, imageObjectFilterRender)
                imageObjectFilterRender.apply {
                    setImage(bitmap.copy(bitmap.config, true))
                    setPosition(TranslateTo.CENTER)
                }
            }
        }
    }
```
You can replace it with a thread with a callback if you don't know about coroutines.

**Comment by Goule** [comment]
Thanks for the help !
