### ISSUE TITLE
Is tap to focus supported by this library

### ISSUE THREAD

**Issue by animaonline** [pedroSG94/rtmp-rtsp-stream-client-java#679]
Hi, I need to implement manual focus, is it supported by this library?

**Comment by pedroSG94** [comment]
No for now. But you can try implement it yourself. You only need modify this class.
Camera1:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java
Camera2:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java

**Comment by animaonline** [comment]
Thanks! I will try that
