### ISSUE TITLE
I want to add a two second delay to the stream, is there any way

### ISSUE THREAD

**Issue by icewst** [pedroSG94/rtmp-rtsp-stream-client-java#680]
I want to add a two second delay to the stream, is there any way

**Comment by pedroSG94** [comment]
Delay is not supported in this library. Maybe you can implement it doing a modify in cache.
RTMP:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/net/ossrs/rtmp/SrsFlvMuxer.java#L66
RTSP:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtsp/src/main/java/com/pedro/rtsp/rtsp/RtspSender.java#L34
