### ISSUE TITLE
Use SurfaceFilterRender to render frames from some other source

### ISSUE THREAD

**Issue by ulohani90** [pedroSG94/rtmp-rtsp-stream-client-java#681]
Hi
I am using SurfaceFilterRenderer to render camera during streaming. Now I have included video calling feature using Agora. For that Agora's sdk requires a Surfaceview to render the video calling frames. 
How can I achieve this that I can pass a surfaceview to agora sdk that has the same surface as my SurfaceFilterRender object?

Any help here would be appreciated.

**Comment by pedroSG94** [comment]
I think that, you can't do it.
I don't know about Agora SDK but the normal way to send frames to 2 surfaces is:
- Create a surface with opengl
- Render that surface with camera API.
- Copy frames from that opengl surface to multiple surfaces using opengl.

The question is. How is working Agora SDK to extract frames? Can you modify Agora code?

If you can set a TextureView to Agora SDK you can try set SurfaceTexture from SurfaceFilterRenderer to TextureView but I think this will not work. Example:
```java
 SurfaceFilterRender surfaceFilterRender =
            new SurfaceFilterRender(new SurfaceFilterRender.SurfaceReadyCallback() {
              @Override
              public void surfaceReady(SurfaceTexture surfaceTexture) {
                textureView.setSurfaceTexture(surfaceTexture);
              }
            });
```
