### ISSUE TITLE
Camera and Display in one stream

### ISSUE THREAD

**Issue by vuleanh** [pedroSG94/rtmp-rtsp-stream-client-java#682]
Hi Pedro, how are you? Thanks for the awesome library

I got a question. Is the any way we can combine camera and display in one stream?

Something like this:
![Untitled](https://user-images.githubusercontent.com/7000252/93656736-ba6c1b80-fa56-11ea-9397-d6a5af01d348.png)

Thank you very much

**Comment by pedroSG94** [comment]
Yes, you can do it using SurfaceFilter. Similar to this but replace MediaPayer with Camera1Manager:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L260

**Comment by vuleanh** [comment]
@pedroSG94 Great. Thank you!
