### ISSUE TITLE
Retrying breaks if the stream is stopped and and then resumed

### ISSUE THREAD

**Issue by CubitSpeed** [pedroSG94/rtmp-rtsp-stream-client-java#683]
For some reason, retrying breaks if the stream is stopped and and then resumed.

**Reproduction Steps**
  1. Start example android app
  2. Choose `Default RTMP`
  3. Disconnect all network connections (disable WiFi/mobile networks)
  4. Press "Start stream"
  5. Notice that the stream will retry (until it hits the value set in `rtmpCamera1.setReTries()` -- 10 in the default case)
  6. Before you run out of retries, press "Stop Stream"
  7. Press "Start stream"
  8. Notice that now all retries fail. Your `numRetries` has become 0 (regardless of previous value)!

**Comment by pedroSG94** [comment]
fixed: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/61a8586ca7bfc0ced94d379bff879ae3d63fbb3b

**Comment by CubitSpeed** [comment]
Thanks for the quick fix here, @pedroSG94 ! I've opened a new (possibly related) issue: 684
