### ISSUE TITLE
Crashlytics

### ISSUE THREAD

**Issue by abadoliverco** [pedroSG94/rtmp-rtsp-stream-client-java#685]
Hi @pedroSG94,

I just want to share with you the crashes from crashlytics.

Thank you!
<img width="805" alt="Screen Shot 2020-09-21 at 12 49 33 PM" src="https://user-images.githubusercontent.com/13760154/93733866-9a308e00-fc09-11ea-803c-f69bdb936b3b.png">
<img width="727" alt="Screen Shot 2020-09-21 at 12 49 14 PM" src="https://user-images.githubusercontent.com/13760154/93733877-a1f03280-fc09-11ea-9d21-917814f4f8af.png">
<img width="619" alt="Screen Shot 2020-09-21 at 12 48 59 PM" src="https://user-images.githubusercontent.com/13760154/93733878-a288c900-fc09-11ea-81c2-f0d6c65af9e0.png">
<img width="596" alt="Screen Shot 2020-09-21 at 12 48 44 PM" src="https://user-images.githubusercontent.com/13760154/93733880-a3215f80-fc09-11ea-9d5f-c5366c456096.png">
<img width="708" alt="Screen Shot 2020-09-21 at 12 48 25 PM" src="https://user-images.githubusercontent.com/13760154/93733881-a3b9f600-fc09-11ea-856c-4617ae722c0e.png">

**Comment by pedroSG94** [comment]
I can't do anything this week.
I will check it next week.

**Comment by pedroSG94** [comment]
All this errors should be solved now:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/71f372e773606d06d568d0a8c41f33a5fc297925
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/fcb68b83f7e052cd101448615f2ebc06ac6fbdd2
