### ISSUE TITLE
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:1.9.1. Show Details Affected Modules: app

### ISSUE THREAD

**Issue by 11xiaochou** [pedroSG94/rtmp-rtsp-stream-client-java#687]
add  implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:1.9.1'

Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:1.9.1.
Show Details
Affected Modules: app

**Comment by pedroSG94** [comment]
Did you add maven repository?
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java#compile

**Comment by 11xiaochou** [comment]
yes. I've already added it

**Comment by pedroSG94** [comment]
Can you share screenshot of both gradle files?

**Comment by 11xiaochou** [comment]
![image](https://user-images.githubusercontent.com/11965898/93999590-9303ae80-fdc8-11ea-82f7-9ceab1f2c836.png)
![image](https://user-images.githubusercontent.com/11965898/93999638-a4e55180-fdc8-11ea-8cd0-eaf53af55ed1.png)

**Comment by pedroSG94** [comment]
Try this:

- In first image delete:
repositories {
mavenCentral()
}
- In second image add to repositories in line 4:
maven { url 'https://jitpack.io' }

**Comment by 11xiaochou** [comment]
Or an error

**Comment by pedroSG94** [comment]
What do you means?
The second image should be like this:
https://github.com/pedroSG94/RTSP-Server/blob/master/build.gradle

**Comment by 11xiaochou** [comment]
![Uploading image.png…]()

**Comment by 11xiaochou** [comment]
![image](https://user-images.githubusercontent.com/11965898/94005793-6011e880-fdd1-11ea-8751-c51480afcef8.png)

**Comment by 11xiaochou** [comment]
![image](https://user-images.githubusercontent.com/11965898/94006283-33aa9c00-fdd2-11ea-9a6d-a2af12994535.png)

**Comment by 11xiaochou** [comment]
![image](https://user-images.githubusercontent.com/11965898/94006793-f09cf880-fdd2-11ea-8f5d-22e3896a9167.png)

**Comment by pedroSG94** [comment]
Try replace:
maven { url 'https://jitpack.io' }
With:
maven { url 'https://www.jitpack.io' }

**Comment by 11xiaochou** [comment]
Thank you very very very much！

**Comment by pedroSG94** [comment]
Great!
If all is working. Close the issue :)

**Comment by 11xiaochou** [comment]
Is this software paid for

**Comment by pedroSG94** [comment]
No. 
You can read license to know more about it:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/LICENSE.txt

**Comment by 11xiaochou** [comment]
Do you have a pull stream player? Support network

**Comment by pedroSG94** [comment]
No I haven't.
I only have a wrapper example of VLC but I recomend you compile VLC in last version yourself if you want use it:
https://github.com/pedroSG94/vlc-example-streamplayer
