### ISSUE TITLE
Streaming with the internal device audio

### ISSUE THREAD

**Issue by svprdga** [pedroSG94/rtmp-rtsp-stream-client-java#688]
I am trying to enable internal audio capture for my app, but for some reason the broadcasted sound is choppy and it doesn't sound the same as the source at all.

I'm using the following configuration:

```
private const val AUDIO_BITRATE = 1200 * 1024
private const val SAMPLE_RATE = 44100
private const val IS_STEREO = true
```

And I call the method normally:

```
displayBase.prepareInternalAudio(
                AUDIO_BITRATE, SAMPLE_RATE, IS_STEREO
            )
```

I am missing something to make this thing work? Thanks.

**Comment by pedroSG94** [comment]
I can't check it now.
I will test it next week.

**Comment by pedroSG94** [comment]
fixed: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/a3c0a0232fcb68cee76c5148937047a854a7d740

**Comment by svprdga** [comment]
I have tried the new version, got a new error:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/703
