### ISSUE TITLE
It is possible to capture series of photos using OpenGL RTSP?

### ISSUE THREAD

**Issue by cyprianG96** [pedroSG94/rtmp-rtsp-stream-client-java#690]
As in title it is possible?

Or have any ideas how I can do it? I need to capture 16 photos before stream will starting.

**Comment by pedroSG94** [comment]
I haven't a specific mode to do it but you can try call takePhoto method multiple times.

**Comment by cyprianG96** [comment]
Yeah, it is some solution, but capture 16 photos takes too long, anyway thanks for fast answer. :)
