### ISSUE TITLE
Broken video stream on iOS

### ISSUE THREAD

**Issue by insidefun** [pedroSG94/rtmp-rtsp-stream-client-java#692]
When decoding video chunks meta info about stream, encoded using your lib, im having problem with calculating NALUnitLength. It is should be in bytes, but you encoding it as int. I mean your encoder providing it like just "3", but according to the standart it should be something like "255", so when calculating length, it should be calculated somehow like (255 >> 6) + 1 on the viewer client.

Audio stream at this case works fine

Reference: https://www.iso.org/obp/ui/#iso:std:iso-iec:14496:-15:ed-2:v1:cor:2:v1:en

**Comment by pedroSG94** [comment]
Are you using RTMP or RTSP?

**Comment by insidefun** [comment]
RTMP

**Comment by pedroSG94** [comment]
I will check it tomorrow. For now, you can try change it here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/net/ossrs/rtmp/SrsFlvMuxer.java#L537
I can’t find it in your link but I used this(page 16):
https://github.com/wlanjie/AndroidFFmpeg/blob/master/doc/H.264-AVC-ISO_IEC_14496-15.pdf
If you find a solution before me. A PR is welcome :)
