### ISSUE TITLE
Broken bitmap on take photo

### ISSUE THREAD

**Issue by insidefun** [pedroSG94/rtmp-rtsp-stream-client-java#694]
Taking photo on active stream returning broken bitmap.

`rtmpCamera2.glInterface.takePhoto { bitmap -> }`

Stack to reproduce:

- RtmpCamera2
- OpenGlView (keepAspectRatio=true, aspectRatioMode=fill)
- Frontal camera
- RTMP stream
- No filters
- Video settings: 1280x720, 30fps, 3000*1024 bitrate, frame interval 1, rotation 90
- Audio settings: bit 64 * 1024, sr 44100, stereo = true

![last_frame](https://user-images.githubusercontent.com/9580252/94802442-60713b80-03f0-11eb-9822-24ec73e3c2dc.jpg)

**Comment by pedroSG94** [comment]
fixed: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/a6a705cae313372606b5bfed473f9f2ebf92f481
