### ISSUE TITLE
All future stream data is discarded data if TCP write hangs

### ISSUE THREAD

**Issue by CubitSpeed** [pedroSG94/rtmp-rtsp-stream-client-java#696]
**Reproduction steps:**

1. Setup a network a network limiter (in my case [Apple's Network LinkConditioner](https://nshipster.com/network-link-conditioner/))
2. Open the example app & start a stream (I used Facebook as server, but others appears to produce the same result)
3. Increase the upload bandwidth (in my case, 9mb/s to 90mb/s -- but this number shouldn't matter)
4. Notice the stream 'continues', but all future frames are now discarded

**Analysis**
I looked into this issue a bit. The issue boils down to this being a forever blocked TCP write/flush. In Java's TCP Socket, writes block indefinitely and no timeout is possible (without using NIO selectors). In this case, it seems like the connection is kept intact, but during the bandwidth change, the remote will never process one of the writes. This leaves the stream in a state where it is forever blocked while also discarding future frames.

I'll admit, I'm not sure when this same behavior might occur in the real world, but the fact that it it can occur even in a simulated one feels a bit troubling to me. So I bring up the issue.

**Comment by pedroSG94** [comment]
This is working as expected. To avoid this problem you can implement adaptative bitrate for this case (this feature increase or reduce bitrate according to if you discard frames) :
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Adaptative-video-bitrate

If you have other idea to implement in this cases we can comment and implement it.

**Comment by CubitSpeed** [comment]
Sorry for my very late reply to this thread.

But using adaptive bitrate here doesn't solve the issue. The TCP connection will never expire regardless of the connection quality. I can confirm this behavior using the network limiter.

**Comment by pedroSG94** [comment]
Actually I don't have any way to check it because my router can't make a network limiter and actually I haven't a macbook. I will mark if as bug and work on it in the future.

**Comment by animaonline** [comment]
This should be reopened, there are multiple ways to reproduce this:

- Run the sample app in the emulator, start streaming, turn off the wifi on your computer, the app does not detect that there is no network.
- Run the app on a device connected to a wifi, pull the nework cable from your router, the app does not detect that there is no network.
