### ISSUE TITLE
Stream from OpenGlView

### ISSUE THREAD

**Issue by FunnyDevs** [pedroSG94/rtmp-rtsp-stream-client-java#697]
Hi! I'm using this client for playing a remote rtsp video -> https://github.com/alexeyvasilyev/rtsp-client-android
I have changed the implementation and now i'm able to play the video with OpenGlView.
Now i would like to stream what the surface plays to a remote streaming server but i have no idea what i should do. 
Is there a sort of example of this situation?  I have tried to edit your Restreamer project with no luck.

Thank you

**Comment by pedroSG94** [comment]
Did you tried replace mediaextractor with your rtsp client library?
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/decoder/VideoDecoder.java#L68

**Comment by FunnyDevs** [comment]
mmm, using that client i have a decodeVideoThread like this

`class VideoDecodeThread (
        private val surface: Surface,
        private val mimeType: String,
        private val width: Int,
        private val height: Int,
        private val videoFrameQueue: FrameQueue
) : Thread() {

    private val TAG: String = VideoDecodeThread::class.java.simpleName
    private val DEBUG = true

    override fun run() {
        try {
            if (DEBUG) Log.d(TAG, "VideoDecodeThread started")

            val decoder = MediaCodec.createDecoderByType(mimeType)
            val format = MediaFormat.createVideoFormat(mimeType, width, height)

            decoder.configure(format, surface, null, 0)
            decoder.start()

            val bufferInfo = MediaCodec.BufferInfo()
            while (!interrupted()) {
                val inIndex: Int = decoder.dequeueInputBuffer(10000L)
                if (inIndex >= 0) {
                    // fill inputBuffers[inputBufferIndex] with valid data
                    val byteBuffer: ByteBuffer? = decoder.getInputBuffer(inIndex)
                    byteBuffer?.rewind()

                    // Preventing BufferOverflowException
//              if (length > byteBuffer.limit()) throw DecoderFatalException("Error")

                    val frame: FrameQueue.Frame?
                    try {
                        frame = videoFrameQueue.pop()
                        if (frame == null) {
                            Log.d(TAG, "Empty frame")
                        } else {
                            byteBuffer!!.put(frame.data, frame.offset, frame.length)
                            decoder.queueInputBuffer(inIndex, frame.offset, frame.length, frame.timestamp, 0)
                        }
                    } catch (e: Exception) {
                        e.printStackTrace()
                    }
                }

                try {
                    val outIndex = decoder.dequeueOutputBuffer(bufferInfo, 10000)
                    when (outIndex) {
                        MediaCodec.INFO_OUTPUT_FORMAT_CHANGED -> Log.d(TAG, "Decoder format changed: " + decoder.outputFormat)
                        MediaCodec.INFO_TRY_AGAIN_LATER -> if (DEBUG) Log.d(TAG, "No output from decoder available")
                        else -> {
                            if (outIndex >= 0) {
                                decoder.releaseOutputBuffer(outIndex, bufferInfo.size != 0)
                            }
                        }
                    }
                } catch (e: java.lang.Exception) {
                    e.printStackTrace()
                }

                // All decoded frames have been rendered, we can stop playing now
                if (bufferInfo.flags and MediaCodec.BUFFER_FLAG_END_OF_STREAM != 0) {
                    Log.d(TAG, "OutputBuffer BUFFER_FLAG_END_OF_STREAM")
                    break
                }
            }

            decoder.stop()
            decoder.release()
            videoFrameQueue.clear()

            if (DEBUG) Log.d(TAG, "VideoDecodeThread stopped")
        } catch (e: Throwable) {
            e.printStackTrace()
        }
    }
}
`

To decode video and play it. 
Now do you advise me to move this thread inside your videodecoder class? Because i have no idea what i should do . In other threads you said that is possibile to restream directly from surface/opengl view but you use vlcplayer.

**Comment by pedroSG94** [comment]
I mean go to my decoders classes and delete mediaextractor to replace that input buffer with buffer from your library or directly replace my decoders with your decoders in this class:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/FromFileBase.java
Anyway, I have other idea.
You can try use flvmuxer (RTMP) or rtspclient (RTSP) like here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtmp/RtmpCamera1.java
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtsp/RtspCamera1.java

Convert bytes to bytebuffer:
https://stackoverflow.com/questions/31062973/java-byte-array-to-bytebuffer-or-bytebuffer-to-byte-array-convertion-without-co

To create a MediaCodec.BufferInfo you can do something similar to this:
Instance one:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/util/RecordController.java#L36
Update it:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/util/RecordController.java#L198
You can update flag for key frames using this method:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/util/RecordController.java#L125
Possible values (anyway you can create a [logcat here](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtmp/RtmpCamera1.java#L177) using my library to check flag values):
https://developer.android.com/reference/android/media/MediaCodec#BUFFER_FLAG_KEY_FRAME

Of course, if you use this way you can't stream filters.

Conclusion:
Option 1:
- Set video and audio info to flvmuxer or rtspclient using onRtspConnected
- Connect flvmuxer or rtspclient after set info.
- Send audio and video frames creating a BufferInfo as indicated above.

Option 2:
Replace MediaMuxer in my Decoder with your library.

**Comment by pedroSG94** [comment]
Yes, you can stream from openglview directly if you add a mediacodec surface to copy buffer and encode it.
Basically I'm doing it here.
I'm rendering my openglview with my decoder:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/FromFileBase.java#L345
After that, I'm creating an encoder and I add surface from that encoder to openglview:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/FromFileBase.java#L374
The buffer result is received here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/FromFileBase.java#L649

**Comment by FunnyDevs** [comment]
I've tried to stream from openglview but you start the glinterface with the start method, but i have the openglview with already decoded video.
So i 've tried to remove mediaextractor: the rtsp player i use decodes the rtsp remote video so is useless another videodecoder if i have the bytebuffers. But how can i "push" the decoded byte buffers to the videoencoder?
