### ISSUE TITLE
when usb camera is high resolution it cant work

### ISSUE THREAD

**Issue by heaveninfosoft** [pedroSG94/rtmp-rtsp-stream-client-java#698]
hello
i use 480p ,720p and 1080 usb external camera to live stream o youtube ,fb.

480p and 720p working fine but 1080p cant seen any thing in live stream

**Comment by pedroSG94** [comment]
How are you using usb external camera?
This project doesn’t support it by default.
Are you using this?
https://github.com/pedroSG94/Stream-USB-test

**Comment by heaveninfosoft** [comment]
i make take some file from your project and runusb camera live stream  it work great i havent take from your given  link .

but 1080p not work it become too too slow even not showing anything on live stream

**Comment by heaveninfosoft** [comment]
> How are you using usb external camera?
> This project doesn’t support it by default.
> Are you using this?
> https://github.com/pedroSG94/Stream-USB-test

yuor project not working for usb so i made my self

**Comment by heaveninfosoft** [comment]
can you tell me what issue with 1080p camera?

**Comment by heaveninfosoft** [comment]
@pedroSG94 please reply sir

**Comment by pedroSG94** [comment]
This is difficult to know.
I have no way to test because I haven’t usb camera right now and I don’t know anything about your code implementation.
Can you show preview in a surfaceview to normal speed in 1080p to discard usb library problems?
If you can do it show me a video in both cases, 1080p with openglview (Your problem case) and working with surfaceview, to know what do you mean with slow

**Comment by heaveninfosoft** [comment]
too slow problem may i solve but main problem why high resolution video i mean video from (1080p) camera not live stream.
even i used just 640*480 from that camera even not work.

it is need to change bitrate, or any YouTube setting for that?

**Comment by pedroSG94** [comment]
I know that 480p and 720p works. I told you that you should test without my stream library to know if you camera open properly in 1080p using **only** your usb library.
After that, send me a video in 1080p and other in 720p on Youtube to compare and know what do you mean with problems.

About bitrate. You can change bitrate using this document to know correct bitrate in all resolutions:
https://support.google.com/youtube/answer/2853702?hl=en

**Comment by heaveninfosoft** [comment]
@pedroSG94 as far i know in usb 1080p camera some time slow but most time open and work like 720p , 480p
but as far live streaming concerned 1080p not even stream for 1 sec in other 480p,720p work well in live stream too .

you said that send video in 1080p - let me now you that it even doesn't start

**Comment by heaveninfosoft** [comment]
all above solved when app in foreground
@pedroSG94 only problem is that i made one service so usb camera work in background now when app goes to background i get debug data  but only video data get not audio data in Samsung 9 plus (Android 10) when app in background
