### ISSUE TITLE
Error:Conflict with dependency 'com.android.support:support-annotations' in project ':app'. Resolved versions for app (25.3.1) and test app (25.3.0) differ. See http://g.co/androidstudio/app-test-app-conflict for details.

### ISSUE THREAD

**Issue by rakshitsoni02** [pedroSG94/rtmp-rtsp-stream-client-java#7]
please help to solve this.

**Comment by pedroSG94** [comment]
You have 2 ways:
Upgrade your project dependencies to 25.3.1 or exclude libraries dependencies like: 
compile ('com.github.pedroSG94.rtmp-rtsp-stream-client-java:builder:v1.0.2'){
    exclude group: 'com.android.support', module: 'support-annotations'
}
