### ISSUE TITLE
work in facebook 5 sec then stop , in YouTube not work even sec

### ISSUE THREAD

**Issue by heaveninfosoft** [pedroSG94/rtmp-rtsp-stream-client-java#701]
in some device work fully good with fb and youtube in some device it give error like below
as far as i know issue with audio related please help me

E/AndroidRuntime: FATAL EXCEPTION: BaseEncoder
    Process: com.pedro.rtpstreamer, PID: 20745
    java.nio.BufferOverflowException
        at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:298)
        at com.pedro.encoder.BaseEncoder.processInput(BaseEncoder.java:130)
        at com.pedro.encoder.BaseEncoder.inputAvailable(BaseEncoder.java:170)
        at com.pedro.encoder.BaseEncoder$2.onInputBufferAvailable(BaseEncoder.java:192)
        at android.media.MediaCodec$EventHandler.handleCallback(MediaCodec.java:1738)
        at android.media.MediaCodec$EventHandler.handleMessage(MediaCodec.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by pedroSG94** [comment]
Which mode are you using? (Camera1, Display...)
Device model and Api?

**Comment by heaveninfosoft** [comment]
in fact i am doing USB camera and its working fine two type camera dont know why not work in other camera i think is audio type related issue

**Comment by pedroSG94** [comment]
I can't give you support because I haven't anyway to test it.
I only can tell you that you can change buffer size here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L257

**Comment by heaveninfosoft** [comment]
you sure above error is audio type error only??

**Comment by pedroSG94** [comment]
Check frame size here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/BaseEncoder.java#L136

**Comment by heaveninfosoft** [comment]
yes that point error occur let me clearly tell what to do?? is i because of high resolution camera that's why size need to increase??

clearly tell me where to change code so that in future my app will not crash

E/AndroidRuntime: FATAL EXCEPTION: BaseEncoder
Process: com.pedro.rtpstreamer, PID: 20745
java.nio.BufferOverflowException
at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:298)
at com.pedro.encoder.BaseEncoder.processInput(BaseEncoder.java:130)
at com.pedro.encoder.BaseEncoder.inputAvailable(BaseEncoder.java:170)
at com.pedro.encoder.BaseEncoder$2.onInputBufferAvailable(BaseEncoder.java:192)
at android.media.MediaCodec$EventHandler.handleCallback(MediaCodec.java:1738)
at android.media.MediaCodec$EventHandler.handleMessage(MediaCodec.java:1696)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:237)
at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by pedroSG94** [comment]
I told you.
Set [frame.getSize](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/BaseEncoder.java#L136) that you get before crash in this line:
https://github.com/pedroSG94/Stream-USB-test/blob/master/app/src/main/java/com/pedro/usbtest/streamlib/USBBase.java#L160
Maybe, you need update library version:
https://github.com/pedroSG94/Stream-USB-test/blob/master/app/build.gradle#L31

**Comment by heaveninfosoft** [comment]
but for audio there is null frame

**Comment by pedroSG94** [comment]
That is not possible:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/BaseEncoder.java#L134
And video can’t crash in that line because usb example only use surface to buffer encoding so that line is never called

**Comment by heaveninfosoft** [comment]
i forget max value to pass now that solved

new crash here
ava.io.IOException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
        at java.net.PlainSocketImpl.socketShutdown(PlainSocketImpl.java:283)

**Comment by pedroSG94** [comment]
I can’t see any line in that logcat.
Anyway, socket problem should be related with internet. Check that you have access to server.

**Comment by heaveninfosoft** [comment]
two final question
1. any reason for getting audio in some device and and not getting for other device??/
2. can i only stream video not  audio (i am not talking about disable audio -i am talking  if you face problem in getting audio)

**Comment by pedroSG94** [comment]
1- I always get audio from phone microphone. I never use usb camera audio or disable audio in some devices.
Sometimes usb camera could contain microphone and this can block phone microphone. Try plug camera and record a video with default camera app to know if phone microphone is working.

2-I haven’t problems with audio but I’m not using usb camera so this should be related with usb camera.

Actually usb camera support is without maintenance because I haven’t usb camera and usb library is developed by other people so I can’t help in that part.

**Comment by heaveninfosoft** [comment]
actually i developed custom project using most of your project for usb , i havent use your usb camera project because it never connect usb camera to phone.

**now i describe you properly:-**
usb camera(640*480 and 720*1280)working fine in youtube and facebook in two device (Google nexus 5 and MI Poco F1).both camera and phone work fine  no error at all.  { i am taking only video frame from usb camera and for audio i using MicrophoneManager to get audio ) that work very well in above situation.--work in facebook YouTube fine no time limit

**Now problem is when** i try to use (1920*1080) camera in Samsung 9plus and when i see code log cat then i get info that here only video data  frame getting correctly but not getting any frame for audio and thats why in fb it work for just4-5 sec and stop and in youtube not work for any second. problem is i ssure you audio not getting this time

**Comment by pedroSG94** [comment]
Yes, Audio is mandatory to stream in fb and yt.
If you can’t get buffer from microphone I recommend you test with default example in this project to discard problems with my library.
After that, share me a full logcat using usb 1080p

**Comment by heaveninfosoft** [comment]
default example i test first  with phone camera then test with usb 1080p camera???

**Comment by pedroSG94** [comment]
Yes, to discard usb problems.
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/defaultexample/ExampleRtmpActivity.java

**Comment by heaveninfosoft** [comment]
i just do,
 i can heard audio but video is black when i try use your  default example with my phone camera
https://www.youtube.com/watch?v=JqMFTZ2M0fw&feature=youtu.be

**Comment by pedroSG94** [comment]
Microphone is working properly so you have problems with usb camera.
Share me full logcat using usb camera but if I can’t see anything in that I can’t help you

**Comment by heaveninfosoft** [comment]
i will soon send you

**Comment by heaveninfosoft** [comment]
thanks bro i finally got my silly mistake 
below method not used that why audio frame max size always got 0 and that reason it not streaming
now i use at above audio encoder start and it work super cool

public void prepareAudioRtp(boolean isStereo, int sampleRate) {
        flvMuxer.setIsStereo(isStereo);
        flvMuxer.setSampleRate(sampleRate);
    }
