### ISSUE TITLE
Out of order frames

### ISSUE THREAD

**Issue by GGPENG** [pedroSG94/rtmp-rtsp-stream-client-java#702]
Hi,

I'm using this library to record and stream videos from foreground service on Android 10. 

It works with my Samsung Note 8, but when I try to run the application on a Samsung A10S device got the following error 1 or 2 minutes after blocking my screen.

```
E/MPEG4Writer: do not support out of order frames (timestamp: 19144185 < last: 19144248 for Audio track
E/MPEG4Writer: Dumping Audio track's last 10 frames timestamp and frame type 
E/MediaAdapter: pushBuffer called before start
E/MediaAdapter: pushBuffer called before start
E/MediaAdapter: pushBuffer called before start
E/MediaAdapter: pushBuffer called before start
```

I believe it is something related to my system/battery optimization. It doesn't happen if the device remain active. 
Could you help me to figure out the solution or confirm the problem?
Thank you!

**Comment by pedroSG94** [comment]
You can try disable battery optimization in your app:
http://nine-faq.9folders.com/articles/8698-how-to-turn-off-battery-optimization-on-the-samsung-galaxy-android-6-7-and-8-devices
Also you should check that your service is alive. Android 10 kill background services for battery optimization but you have a few tricks to avoid it on internet. Example:
https://stackoverflow.com/questions/38474290/how-to-keep-a-service-alive

**Comment by GGPENG** [comment]
Thank you Pedro!
This issue "frame out of order" is generally related to battery optimization? Is there any code solution to prevent that desincronization?

**Comment by pedroSG94** [comment]
If my link worked you can open that window by code:
https://stackoverflow.com/questions/39256501/check-if-battery-optimization-is-enabled-or-not-for-an-app

**Comment by GGPENG** [comment]
Just tried every solution, but the problem persists. The process is not being killed, but something make audio (and just audio) track frames desynchronized.
When I set my camera object to .disableAudio() the problem is solved. Why audio track is out of order but the video frames remains in the order?
Is there any software solution to prevent that issue @pedroSG94?

**Comment by GGPENG** [comment]
@pedroSG94 
News about this issue, just tested at same environment using Android Media Recorder instead of our library. It works. Do you know how to fix this error so I can continue using this library?

**Comment by pedroSG94** [comment]
Sorry, I had no time this days.
What do you mean with frames desynchronized?. Is it working but video and audio out of sync?
I need more info about this problem.
- Mode used and configuration (Display, Camera1, Camera2, prepare video and audio params).
- Device model and Api version.
- Steps to reproduce

**Comment by GGPENG** [comment]
Hi @pedroSG94, no problem!

I did a lot of tests using Android MediaRecorder Api and our library. 
I believe that frames are missing or desynced when I receive the following error message (please check complete error log in my last message):
`E/MPEG4Writer: do not support out of order frames (timestamp: 55785969 < last: 55786000 for Audio track`
When this error happens I can't playback .mp4 media file anymore, it's corrupted. 

I'm using camera = RtmpCamera2(context, true, connectCheckerRtp) in my foreground service. 
Device model ATM R5 that uses pure android version Android 9 API 28.

If I use MediaRecorder instead of MediaMuxer, everything works fine.

**Comment by pedroSG94** [comment]
I did a commit that could fix your problem:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/034571a3083312cb186356b4ca36f7c20b73d75a
Test with this commit. If your problem with frame discarded persist use this new method:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera2Base.java#L137
Like this:
```java
rtmpCamera2 = new RtmpCamera2(surfaceView, this);
//Use same thread for microphone and encoder to avoid discard audio frames. Should be called before prepareAudio
rtmpCamera2.setMicrophoneMode(MicrophoneMode.SYNC);
```

**Comment by GGPENG** [comment]
Hi @pedroSG94, 

Got the same error using that commit. 
Testing using `rtmpCamera2.setMicrophoneMode(MicrophoneMode.SYNC);` I got the following error:

`E/AudioRecord-JNI: Error -38 during AudioRecord native read
E/AudioRecord-JNI: Error -38 during AudioRecord native read`

That error occurs as soon as startRecord method is triggered, and I can't playback that media.

**Comment by pedroSG94** [comment]
This is weird, MicrophoneMode.SYNC is basically reproducing version 1.8.5 that worked with only one thread for microphone and audio encoder. Also, I can't find what mean error -38 in android source code...

I will try find the reason comparing 1.8.6 and 1.8.5.

Meanwhile, can you try find -38 error reason? 
Also I'm not sure if this apply to audio but, in Android 9 you can block permissions if the app is in background (at least with location this is possible). Can you check if you have this permission enabled in background?

**Comment by GGPENG** [comment]
I'll try to find -38 error. 
About audio permission, it's enabled. To confirm that, the app is working on Samsung devices running Android 9 and 10. 

Tested again today, version 1.8.5 is working.
