### ISSUE TITLE
Microphone Manager not working in background in api 29 android

### ISSUE THREAD

**Issue by heaveninfosoft** [pedroSG94/rtmp-rtsp-stream-client-java#705]
hello @pedroSG94 
i know you help me great help last time too
now i have problem of background app recording

i am using usb camera to live stream , it also work in background but after api 29
i can see debugging that in background only video data getting but not audio data so that mean Microphone Manager not working help me.

**Comment by pedroSG94** [comment]
I can't help you like this.
Try create multiple breakpoints or logs to know audio flush. In microphone and audioencoder start/stop, in [microphone read](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/audio/MicrophoneManager.java#L176) and in [audioencoder encode](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/BaseEncoder.java#L61).

**Comment by heaveninfosoft** [comment]
i am talking about is it possible Microphone Manager work in background in android 10

**Comment by pedroSG94** [comment]
It should work. It is working with Display example in my Oneplus 7T

**Comment by heaveninfosoft** [comment]
i am talking about in background , it work in foreground there is no issue.
again i telling you i am doing one custom usb project which need to streaming in live usb video to server that work in all phone except Android 10 in background. issue with Audio . video i get data but audio cant thats  issue

**Comment by pedroSG94** [comment]
Display example is for background screen stream...

**Comment by heaveninfosoft** [comment]
yes i can see result in background , you really very very very helpful men. Thanks you much.

but only little suggestion that your usb 
https://github.com/pedroSG94/Stream-USB-test not working when will allow usb camera permission it redirect to other same screen

by the way i have other usb project i just take your stream code from this project not from usb stream project. if you solve your stream project then its good.

**Comment by pedroSG94** [comment]
I have no plan to solve usb project problems because I haven't anyway to test.

**Comment by wujianwei121** [comment]
Thank you. Later I found that 1.6.0 controls the delay and supports USB camera
