### ISSUE TITLE
how to get url for youtube

### ISSUE THREAD

**Issue by heaveninfosoft** [pedroSG94/rtmp-rtsp-stream-client-java#706]
how i can give url to other person??
how get url from key???

**Comment by pedroSG94** [comment]
I don't understand what do you mean, but you should find in youtube documentation or internet. This is only for issues related with the library.

**Comment by heaveninfosoft** [comment]
@pedroSG94 
ok no problem 
please ans in this please
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/705
