### ISSUE TITLE
Is it possible to change the orientation of the video stream from within the library while not using preview?

### ISSUE THREAD

**Issue by Abhilash--** [pedroSG94/rtmp-rtsp-stream-client-java#707]
I want to invert the video stream based on the device orientation. Only MediaCodec surface is used and activity to show preview is no created.

**Comment by pedroSG94** [comment]
I suggest you use your device sensor to calculate it:
https://stackoverflow.com/questions/32826227/how-to-determine-device-orientation-from-the-sensors

**Comment by Abhilash--** [comment]
I am able to get the device orientation. Based on the orientation received I want to rotate the video stream at some particular angle which I am not able to do.

**Comment by pedroSG94** [comment]
In prepareVideo only this values are allowed: 0, 90, 180, 270.
Also you can try with rotation filter that allow any values: 
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L240

**Comment by Abhilash--** [comment]
There is no camera preview used in my case. The library is working as a service. Will the above changes work even in this case? I want to change the rotation of only the streamed video.

**Comment by pedroSG94** [comment]
You can use both without preview.
But this will change rotation of all (preview if you have it, video record and streamed video). Only change rotation of streamed video is not supported.
