### ISSUE TITLE
rtsp or rtmp address

### ISSUE THREAD

**Issue by reo-min** [pedroSG94/rtmp-rtsp-stream-client-java#709]
I don't know what to enter the addresses of rtsp and rtmp.

Is the IP address of the Android phone or the server on the desktop? And what should be set as “live” and “app” on the back of the port and the port...?

There is an error message
"Connection failed. Connect error, failed to connect to /192.168.31.221(port5554) from /192.168.31.221(port 39700) after 5000ms: isConnected failed: ECONNREFUSED(Connection refused)

Thx

**Comment by pedroSG94** [comment]
Hi,

You should write something similar to this:
RTMP:
rtmp://192.168.1.130:1935/live/testing
RTSP:
rtsp://192.168.1.130:554/live/testing

Where:
192.168.1.130 -> IP of your mediaserver.
1935 or 554 (it is default port in each protocol but you can set anyone if you configure it in your server) -> Port used for your server.
live -> Application name used by your server. By default usually is live or app
testing -> Stream name. Normally this could be any string.

**Comment by reo-min** [comment]
Thank you so much

But, 

I already did that, but it doesn't work. I am trying to link with a laptop, can I use the laptop Ip address as the Ip address? Where can I set the port?

As a beginner, I am still inexperienced.

**Comment by pedroSG94** [comment]
First of all. You need get both devices (phone and laptop) in the same network.
Also if you are using firewall or something similar disable it to avoid problems with that.

After that you should use laptop IP (local IP if you are in a local net) like I told you.
About the port this depend of mediaserver installed in your laptop (not all server use same ports) so I recommend you go to your server documentation and check it. If you can tell me server used. Maybe I can help you.

**Comment by reo-min** [comment]
Hmm.. okay!!

Actually, I am trying to connect with Python, using the OS.

I have disabled using firewall

**Comment by pedroSG94** [comment]
I think you don't understand this library porpouse.
It seems that you don't have a mediaserver installed in your laptop.

This library is for stream video and audio to a media server.
Here is a list of mediaserver tested if you want install one:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Media-servers-tested

**Comment by Moyout** [comment]
> rtmp://192.168.1.130:1935/live/testing
I had the same problem. My rtmp service is fine, pushing the stream normally using OBS software, but showing a connection error on Android

**Comment by pedroSG94** [comment]
Hello,

Please, if possible open a new issue instead of write in a closed one. You can link this issue if it is relevant for the case.
About the error, which one? can you share error connection?
Are you sure that your device has connection with your server? (if OBS works it is not relevant if you are using different devices) You can download a ping app and do a ping to your server
Are you sure that your device is in the same network? check your IP in settings > device info > IP address (this could change depend of device model, you can download an app if necessary)
