### ISSUE TITLE
the type of rtsp or rtmp

### ISSUE THREAD

**Issue by reo-min** [pedroSG94/rtmp-rtsp-stream-client-java#711]
there is custom default..etc

can u explain what the difference is among them?

**Comment by pedroSG94** [comment]
Custom and default is basically the same but in custom you can modify stream parameters as you want (rtmCamera1 using SurfaceView).
The others one is an example in each stream modes supported by the library (display, camera2, from file, onlyaudio) and one example to use filters (opengl).
