### ISSUE TITLE
Reduce video quality and video getting stuck in between while doing streaming

### ISSUE THREAD

**Issue by bharat-supekar** [pedroSG94/rtmp-rtsp-stream-client-java#712]
We are publishing our video using RTMPs URL, while streaming video sometimes its works but suddenly it getting stucked and it reduced video quality.
Can you please help me here to do video streaming using RTMPS?

**Comment by pedroSG94** [comment]
Are you using adaptative video bitrate?
We have a few problems to work with this in some cases with the actual algorithm:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/545
