### ISSUE TITLE
In front camera is too dark

### ISSUE THREAD

**Issue by Pisey-Nguon** [pedroSG94/rtmp-rtsp-stream-client-java#713]
My camera is too dark when I use function in camera1apimanager and if I use it with camera2apimanager is show better but it's stuck (No crash) camera when I start stream.

**Comment by pedroSG94** [comment]
First of all I need to know device model and API version.

This could be related with your problem with camera1:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/184

About camera2 use this method to know camera error:
```java
rtmpCamera2.setCameraCallbacks(this);
```
And show me the error to know what happens.
Also if you are using SurfaceView or TextureView with camera2, try with LightOpenGlView or OpenGlView.

**Comment by Pisey-Nguon** [comment]
Thank you brother now it's work
