### ISSUE TITLE
reConnect vs retry when there is a disconnection?

### ISSUE THREAD

**Issue by denebchorny** [pedroSG94/rtmp-rtsp-stream-client-java#714]
I am trying to reconnect the streamer when there is a fail o disconnection. I need to understand what and when to use retry or reconnect.

For example: if I change from wifi to 4g, what is going to happen? Does a disconnection or connection fail?

I am making a kind of video call. When there is a problem, I need to reconnect the streamer, but I saw two methods. One is retry, and the other is reConnect. What's the difference, and when I need to use one or another?

RESUME: I need to reconnect a streamer. Then:
1. where do I have to use the reconnect method? On disconnect method or connection fail?
2. What do I have to use? reConnect or retry?

NOT: I found this https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/530, but it doesn't answer my questions at all.

And I didn't find anything on the wiki.

**Comment by pedroSG94** [comment]
Hello,

OnDisconnect method is called after you call stopStream, if you have a connection problem OnConnectionFailed is called and you can decide if you want reconnect (retry method) or finish connection using stopStream method.
reconnect should be an internal method used to call reconnect method of rtmp or rtsp modules  depend of reason and delay selected in reTry method.

You basically need use retry method like here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/defaultexample/ExampleRtmpActivity.java#L75
Remember set number of retries:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/defaultexample/ExampleRtmpActivity.java#L56
