### ISSUE TITLE
Audio Recording Issue

### ISSUE THREAD

**Issue by MingLoan** [pedroSG94/rtmp-rtsp-stream-client-java#72]
E/AudioRecord-JNI: Error -4 during AudioRecord native read

I cannot stream with example project with this error

**Comment by pedroSG94** [comment]
Can you provide me more logcat?
I need too device model and API used.
If you are using custom room or emulator I can't help you so much because could be a system error (in custom room) or no support hardware encoding (emulator).

**Comment by MingLoan** [comment]
finally I found my URL incorrect, I can now stream, thanks
