### ISSUE TITLE
problem with switch camera during live stream with the RTMP

### ISSUE THREAD

**Issue by Pisey-Nguon** [pedroSG94/rtmp-rtsp-stream-client-java#720]
when I live stream with the RTMP link it's successful but when I switch the camera to front it also has a disconnected stream.

**Comment by pedroSG94** [comment]
This is working fine for me.

I need know more to find the error.
- Device model and Android API used.
- Did you tested with my app in my last commit? If not, share me a code example to reproduce the problem
- Which mode are you using? (camera1, camera2, fromfile or display)
- Which view are you using (openglview, lightopenglview, surfaceview, textureview, only context)
- Can you share me a full logcat when you have the problem?

**Comment by Pisey-Nguon** [comment]
Thank brother for your reply but now it's work that mistake by me has a modifier some code on camera1 that effect to function switch camera.
