### ISSUE TITLE
 Broadcast screen flickers

### ISSUE THREAD

**Issue by reon69or** [pedroSG94/rtmp-rtsp-stream-client-java#722]
Broadcasting screen flickers when AndroidViewfilterRender is applied in OpenGl view.
androidViewFilterRender = new AndroidViewFilterRender();
                    androidViewFilterRender.setAndroidViewtype(0);
                    androidViewFilterRender.setView(mPresetViewList.get(i));
                    androidViewFilterRender.setScale(mPresetViewList.get(i).getScaleX(), mPresetViewList.get(i).getScaleY());
                    androidViewFilterRender.setPosition(rect.left, rect.top);
                    if (mPresetViewList.get(i).getId() == 0) {
                        rtmpCamera1.getGlInterface().setFilter(presetAlert, androidViewFilterRender);

**Comment by pedroSG94** [comment]
I need more info to reproduce the problem:
- Device model and Android API.
- Stream resolution used.
- XML example to reproduce the problem.
- Do you have this problem in preview, stream result or both?

**Comment by reon69or** [comment]
Device model and Android API. --> android 9 and 10,, 
Stream resolution used. -> 1280x720, 960x 540 ,Occurs in all resolutions
Do you have this problem in preview, stream/record result or both? -> applied android view filter during live stream.

the screen layout is as below
<RelativeLayout
                android:id="@+id/camera_layout"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:gravity="center_horizontal">
                <com.pedro.rtplibrary.view.OpenGlView
                    android:id="@+id/rtmp_camera_view"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:layout_gravity="top"
                    app:aspectRatioMode="adjust"
                    app:keepAspectRatio="false"
                    app:AAEnabled="true"
                    />
            </RelativeLayout>

**Comment by pedroSG94** [comment]
Ah ok, I understand now and I can reproduce it.
I will check if I can delete that flicker

**Comment by pedroSG94** [comment]
Fixed: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/9ea2978a2fd919bb033b24e3a4afbc22a92078dd

If you are using gradle you can compile this commit with:
```gradle
implementation 'com.github.pedroSG94:rtmp-rtsp-stream-client-java:9ea2978a2f'
```

**Comment by reon69or** [comment]
Dear. prero.

thank for your advice..
It is processed successfully.

thank you.


2020년 11월 6일 (금) 오전 8:17, Pedro Sánchez <notifications@github.com>님이 작성:
