### ISSUE TITLE
Device: Wiko Fever, Android: 6.0. Audio distorted while recording or streaming using OpenGlSurface and Camera1Api

### ISSUE THREAD

**Issue by a-nacollari** [pedroSG94/rtmp-rtsp-stream-client-java#723]
Hi and let me thank you for the amazing job that you and the other contributors have made.

A tester that has this mobile device has been reporting this problem while streaming or while recoding a video, using the OpenGlView and RtmpCamera1.

On the other devices that I've tested everything seems to work fine, android 8, 9, 10. 

Currently I'm not able to get the logs from the user.
We're are trying to get another device with android 6 to see if the problem is related to the device manufacture or the android version. So we can have other hints

**Comment by pedroSG94** [comment]
I can't reproduce this problem, but maybe this is related with microphone configuration.

You can try with this:
- Record a video with default camera app to discard hardware problems. Share this video could be helpful to know audio configuration used and try configure library with that params.
- Change samplerate
- Test with mono and stereo.
- Disable filters if you are using someone (noise suppressor and echo canceler)
- If you think that the distortion is noise or echo, you can try enable that filter.

Also, try combine all possibilities.

**Comment by naco95** [comment]
Thank you for your help, definitely I'm going to try it.
