### ISSUE TITLE
PedroSG94 RTMP-STSP-Stream-Client SDK with ARCore SDK for Live Streaming in Android

### ISSUE THREAD

**Issue by mandanai** [pedroSG94/rtmp-rtsp-stream-client-java#724]
Hello, I am using PedroSG94 RTMP-STSP-Stream-Client SDK for live streaming. Here you have provided OpenGlView which supports live streaming, but what if I have to use it with ARCore SDK. ARCore provides ARScene view. Can you please help me to stream my ARScene view by using PedroSG94 RTMP-STSP-Stream-Client sdk for live streaming.

**Comment by pedroSG94** [comment]
Hello,

If you want stream with external library you should replace CameraApiManager with your own library (ARCore SDK in this case).
Basically you need render surface of OpenGlView.getGlInterface.getsurface(); using that SDK. 

I dont know how is working ARCore SDK so you need investigate it by yourself.
I recommend you try with a stupid example like this (XML layout is basically an OpenGlView full screen):
```java
public class TestActivity extends AppCompatActivity implements SurfaceHolder.Callback{

    private OpenGlView openGlView;
    
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
        setContentView(R.layout.activity_open_gl);
        openGlView = findViewById(R.id.surfaceView);
        openGlView.getHolder().addCallback(this);
    }
    
    @Override
    public void surfaceCreated(SurfaceHolder surfaceHolder) {

    }

    @Override
    public void surfaceChanged(SurfaceHolder surfaceHolder, int i, int i1, int i2) {
        openGlView.init();
        openGlView.start();
        //You are ready to render
        //Render one of this (Surface or SurfaceTexture). 
        // If you can see the result in the preview you are doing it correctly.
        openGlView.getSurface();
        openGlView.getSurfaceTexture();
    }

    @Override
    public void surfaceDestroyed(SurfaceHolder surfaceHolder) {
        openGlView.stop();
    }
}
```
If you can do it work. The next step is go to Camera1Base or Camera2Base and replace CameraApiManager with your ARCore code.

**Comment by pedroSG94** [comment]
Also You can follow this oficial example of ARCore to integrate it inside [Camera2ApiManager](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java):
https://github.com/google-ar/arcore-android-sdk/blob/master/samples/shared_camera_java/app/src/main/java/com/google/ar/core/examples/java/sharedcamera/SharedCameraActivity.java

**Comment by mandanai** [comment]
Thank you for your advice. I'll try the method you suggest

**Comment by ntqp97** [comment]
> Thank you for your advice. I'll try the method you suggest

Are you tried to integrate ARCore inside Camera2ApiManager ?? You can share your solution or code?
