### ISSUE TITLE
the lib version 1.9.4 can't stream 720x480

### ISSUE THREAD

**Issue by ngoluuduythai** [pedroSG94/rtmp-rtsp-stream-client-java#725]
I run the master code it works fine. But with lib version 1.9.4. I can't stream the 720x480 resolution video.
I found the code change is:
mater VideoEncoder line 404 is:
```
  @Override
  protected Frame getInputFrame() throws InterruptedException {
    Frame frame = queue.take();
```
in version 1.9.4:
```
 @Override
  protected Frame getInputFrame() throws InterruptedException {
    Frame frame = queue.poll(100, TimeUnit.MILLISECONDS);
```
I think this is causing this issue

**Comment by pedroSG94** [comment]
I just updated library version. Try with version 1.9.5

**Comment by ngoluuduythai** [comment]
Yeah, Thanks so much ❤️
