### ISSUE TITLE
Camera auto switch from Facing front to back after onPause

### ISSUE THREAD

**Issue by cryinrain69** [pedroSG94/rtmp-rtsp-stream-client-java#727]
First, i switch camera from Facing Back to Front.
After fragment/activity fall on onPause and onResume state, camera auto switch Facing Back without holding the state before.
Is this a bug ?

**Comment by pedroSG94** [comment]
No, this isn't a bug.
When you go to onPause, preview is stopped producing a camera release and the state is reset too.

If you want use same face you should save it in a variable and use it when you call startPreview.
For example:
```java
  private CameraHelper.Facing facing = CameraHelper.Facing.BACK;

private void switchCamera() {
    try {
      rtmpCamera1.switchCamera();
      facing = rtmpCamera1.isFrontCamera() ? CameraHelper.Facing.FRONT : CameraHelper.Facing.BACK;
    } catch (CameraOpenException e) {
      Toast.makeText(this, e.getMessage(), Toast.LENGTH_SHORT).show();
    }
  }

@Override
  public void surfaceChanged(SurfaceHolder surfaceHolder, int i, int i1, int i2) {
    rtmpCamera1.startPreview(facing);
  }
```

**Comment by cryinrain69** [comment]
It's works well.
Thank you so much :100:
