### ISSUE TITLE
Stream loses settings on Restart

### ISSUE THREAD

**Issue by ElectronHerder** [pedroSG94/rtmp-rtsp-stream-client-java#728]
I am trying to create an app that can reliably reconnect to send an RTMP stream after loss of network signal. I am testing by starting a video stream, briefly interrupting network service ( about 20 sec or more ) then letting the app reconnect.

The problem seems to be that the RTMP stream to server no longer contains the settings established in prepareEncoders(). My NGINX server records multiple files. The first one is for the original stream. After stop and restart, it creates a new file. The new file lacks information about the audio stream, the frame rate and other critical pieces. The only thing that remains constant is the pixel resolution.

You can look at two files that were created this way at:

Original Stream

https://rescueresponder.com/pedro/stream_181-1605297863.flv

Restarted Stream

https://rescueresponder.com/pedro/stream_181-1605297956.flv

The Original stream contains the audio encoding information and other necessary parameters. The Restarted stream ( created after network drop then reconnect ) does not. So, no audio plays. Also, the ffmpeg program can not convert it to .mp4 format. And, the NGINX server can not stream it to viewers, because it lacks information needed by the hls players.

**Comment by pedroSG94** [comment]
How are you doing restart?

**Comment by ElectronHerder** [comment]
Our goal has been to make our app reliably reconnect at the sender and receiver ends after a network loss ( roaming around with poor cell service ). It has been a problem. We would be happy to hire you for a few hours to make this work reliably.

We need it to be as reliable as Apple Facetime or something, where it can simply reconnect and resume streaming after network interruption.


DEMO FILES - we are also testing this from the iOS version of the app. It restarts a stream successfully, with encoding information, so the NGINX server conversion is working properly. Here is a stream that is started, stopped, then resumed when network becomes available again. It is basically starting a fresh stream with full encoding information, so the files are good. Here are both the .flv and .mp4 versions ( after ffmpeg conversion ). So, the server seems okay.

https://rescueresponder.com/pedro/stream_189-1605635558.flv
https://rescueresponder.com/pedro/stream_189-1605635558.mp4  ( converted by ffmpeg )
https://rescueresponder.com/pedro/stream_189-1605635659.flv
https://rescueresponder.com/pedro/stream_189-1605635659.mp4  ( converted by ffmpeg )


ANDROID

Establishing Video Settings:

```
	private boolean prepareEncoders() {
		int width = 720;                    // Default 1920 x 1080
		int height = 480;
		int etFps = 6;                    // up to 30
		int etVideoBitrate = 256 * 1024;    // range 256 to 2500
		Boolean cbHardwareRotation = false;
		int etAudioBitrate = 48 * 1024;        // default 128
		int etSampleRate = 16000;            // default 44100
		Boolean isStereo = false;
		Boolean cbEchoCanceler = false;
		Boolean cbNoiseSuppressor = false;

		try {
			return rtmpCamera1.prepareVideo(width, height, etFps, etVideoBitrate,
					0, CameraHelper.getCameraOrientation(mContext))
					&& rtmpCamera1.prepareAudio(etAudioBitrate,
					etSampleRate,
					isStereo, cbEchoCanceler,
					cbNoiseSuppressor);
		} catch (Exception e) {
			e.printStackTrace();
			Log.e(TAG, "prepareEncoders() failed");
			return false;
		}
	}
```

Restart after connection fail:

```
	@Override
	public void onConnectionFailedRtmp(final String reason) {
		runOnUiThread(new Runnable() {
			@Override
			public void run() {

				if (rtmpCamera1.isStreaming()) {
					if(rtmpCamera1.shouldRetry(reason)){
						rtmpCamera1.reTry(1000, reason);
						streaming_status.setText("Reconnecting");
					}else  {
						rtmpCamera1.stopStream();
						streaming_status.setText("Streaming Disconnected .Please start again");
						Toast.makeText(mContext, "Video Connection failed. " + reason, Toast.LENGTH_SHORT)
								.show();
					}
				}
			}
		});
	}
```

NGINX

( Sending by Email to your published email address )

**Comment by pedroSG94** [comment]
Ok, I detected that audio error is only with 16000 sample rate. For now, try with 44100. I'm investigating it.

**Comment by pedroSG94** [comment]
Audio config is fixed now:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/346bbcefb31d1393e46f395e8100a9a3e4888ed0
Try with this gradle and let me know if all is working fine:
```gradle
	        implementation 'com.github.pedroSG94:rtmp-rtsp-stream-client-java:346bbcefb3'
```

**Comment by ElectronHerder** [comment]
> Ok, I detected that audio error is only with 16000 sample rate. For now, try with 44100. I'm investigating it.

I wonder if there is a specific multiplier value that the audio rate must match. Like, 44003 would not be a good value. So, maybe 16000 is not good but 16384 ( a power of 2 ) would be?

**Comment by pedroSG94** [comment]
> > Ok, I detected that audio error is only with 16000 sample rate. For now, try with 44100. I'm investigating it.
> 
> I wonder if there is a specific multiplier value that the audio rate must match. Like, 44003 would not be a good value. So, maybe 16000 is not good but 16384 ( a power of 2 ) would be?

No, this is fixed in the last commit as I told you in my last post. You can use 16000 of you update library.
16384 is not a valid sample rate.

**Comment by ElectronHerder** [comment]
UPDATE: On network reconnect, there is black video but the audio is good.

First video before network loss:

https://rescueresponder.com/pedro/stream_360-1606245380.flv

Second video after network reconnect

https://rescueresponder.com/pedro/stream_360-1606245461.flv

**Comment by pedroSG94** [comment]
This is weird. That commit is working for me.
Try test with this gradle:
```gradle
	        implementation 'com.github.pedroSG94:rtmp-rtsp-stream-client-rtmpresettest-SNAPSHOT'
```

**Comment by ElectronHerder** [comment]
Woops. Not found.

`Could not find com.github.pedroSG94:rtmp-rtsp-stream-client-rtmpresettest-SNAPSHOT`

**Comment by pedroSG94** [comment]
My bad. This is the correct gradle:
```gradle
    implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:rtmpresettest-SNAPSHOT'
```

**Comment by ElectronHerder** [comment]
The first test worked! I manually ran ffmpeg to convert the .flv files to .mp4 and they turned out good. Whatever you changed, it seems to have improved the situation.

I need to restore the automatic .mp4 conversion on the server and do some more testing. I will report again in two days.

**Comment by ElectronHerder** [comment]
Here are latest test results:

I added back the automatic ffmpeg conversion to .mp4 and that works properly.

Whatever change you made has apparently hard-coded the video settings. In my source, it is set to 720x480 at 6fps, with 16000 audio rate and isStereo set to false. Running ffmpeg -i against the saved video file gives 

```
Input #0, flv, from 'stream_405-1607039097.flv':
  Duration: 00:00:26.87, start: 0.223000, bitrate: 1198 kb/s
    Stream #0:0: Video: h264 (Baseline), yuv420p(tv, bt470bg/bt470bg/smpte170m), 480x640, 1k tbr, 1k tbn, 2k tbc
    Stream #0:1: Audio: aac (LC), 32000 Hz, stereo, fltp
```

I don't mind the 480x640 resolution. I would like to reduce the frame rate, a lot, as well as the audio encoding, to reduce data usage and resulting file size.

So, what is the next step?

**Comment by pedroSG94** [comment]
Sorry for late response. I was in holydays.
I did a commit in that branch. Try clear project and rebuilt it to download last commit or compile project example using that branch:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/rtmpresettest

**Comment by ElectronHerder** [comment]
Okay I have returned from travel, am looking into this again. My goal is to be able to reduce frame rate and to set the audio encoding to mono with lower bitrate to save data. Will start testing again.

**Comment by ElectronHerder** [comment]
I'm sorry, I'm not sure which you mean for me to use. Is it:

implementation 'com.github.pedroSG94:rtmp-rtsp-stream-client-java:346bbcefb3'

**Comment by pedroSG94** [comment]
Try this:
```gradle
implementation 'com.github.pedroSG94:rtmp-rtsp-stream-client-java:313480fbb4'
```

**Comment by romio95** [comment]
If i try retry method retry() i have error:

error: shouldRetry(String) has protected access in RtmpCamera1
					if(rtmpCameral.shouldRetry(reason)){
					              ^
------------------------------------------------------------------------------------------------------------------------------------------------------

My code:

    @Override
    public void onConnectionFailedRtmp(String reason) {

	runOnUiThread(new Runnable() {
			@Override
			public void run() {

				if (rtmpCamera1.isStreaming()) {
					if(rtmpCamera1.shouldRetry(reason)){
						rtmpCamera1.reTry(1000, reason);
					} else  {
                      Toast.makeText(CapacitorRtmpActivity.this,
                      "Connection failed, " + reason,
                      Toast.LENGTH_SHORT).show();
                      stopStreaming();
					}
				}
			}
		});
    }


------------------------------------------------------------------------------------------------------------------------------------------
