### ISSUE TITLE
1.9.5 with USB camera streaming, there is no sound

### ISSUE THREAD

**Issue by wujianwei121** [pedroSG94/rtmp-rtsp-stream-client-java#729]
1.9.5 with USB camera streaming, there is no sound, 1.5.0 has no problem, but the delay will increase with time or even more than 10 seconds

**Comment by pedroSG94** [comment]
This is duplicated
Unfortunately, USB camera is not currently under support cause I haven't any way to test it and I'm not owner of the USB library so I can't help in that part:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/705

**Comment by wujianwei121** [comment]
Thank you. Later I found that 1.6.0 controls the delay and supports USB camera
