### ISSUE TITLE
Problem rotate preview in landscape

### ISSUE THREAD

**Issue by cryinrain69** [pedroSG94/rtmp-rtsp-stream-client-java#730]
Hi.
In Manifest,  i set screenOrientation = Portrait
In my app, when want livestream in portait or landscape, i set rotation = 0 or 90 in **rtmpCamera2.prepareVideo**.
When watch livestream, everything work. But in preview with landscape, camera rotate incorrect.
How can the camera rotate correct in my case ?
I see in class Camera2Base -> 
```java
startPreview(CameraHelper.Facing cameraFacing, int width, int height, int rotation) {
...
boolean isPortrait = CameraHelper.isPortrait(context);
if (isPortrait) {
    glInterface.setEncoderSize(height, width);
} else {
   glInterface.setEncoderSize(width, height);
}
glInterface.setRotation(rotation == 0 ? 270 : rotation - 90);
glInterface.start();
```
Do not know if this is the problem ?
Please help me.

**Comment by pedroSG94** [comment]
Hello,

Camera (preview and stream) is rotated according with current UI state (portrait, landscape, reverse portrait, reverse landscape).
To handle the correct rotation and let user select if stream is portrait or landscape. I recommend unlock activity rotation and lock it when you configure video settings and press start stream. For example:
```java
startStreamButton.setOnClickListener {
     lockCurrentUIState()
     if (prepareAudioVideoConfiguration()) {
       startStream(endpoint)
     }
}

stopStreamButton.setOnClickListener {
     stopStream()
     unlockUIState()
}
```
In startPreview and prepareVideo methods. You should use rotation provided by CameraHelper.getCameraOrientation(context)

**Comment by cryinrain69** [comment]
That is a great suggestion.
Thank you so much.
