### ISSUE TITLE
Do not reconnect if network switch between WiFi and Mobile data

### ISSUE THREAD

**Issue by anupdey99** [pedroSG94/rtmp-rtsp-stream-client-java#731]
When user switch between WiFi and Mobile data, stream retry and disconnected.
Retry not working

**Comment by pedroSG94** [comment]
This is working for me. Which server are you using?

**Comment by anupdey99** [comment]
AWS

**Comment by ILoveLin** [comment]
I also encountered no data in the push stream when I switched the network
This is the link to the question
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/1200
