### ISSUE TITLE
Orientation change for streaming

### ISSUE THREAD

**Issue by psddas** [pedroSG94/rtmp-rtsp-stream-client-java#732]
Hello,

Which API needs to be used to change orientation of the stream to endpoints. I am not using the Activities/UI components.  
Could you please give a little brief.

**Comment by psddas** [comment]
For the orientation rotation to work, should we add the OffScreenGlThread surface also to the camera list of surface while creating the builder?
Currently we are adding only the mediacodec surface, with which the orientation rotation is not working. 

Code ref: private void prepareGlView() of Camera2Base class.

**Comment by pedroSG94** [comment]
Are you using a custom code?
In this case, OffScreenGlThread should render mediacodec surface so, you only need add OffScreenGlThread surface to camera2 list of surfaces after start and setRotation to OffScreenGlThread before call start.
If you are using my code without modification. Rotation should work if you set 90, 180, 270 or 0 in prepareVideo.

**Comment by psddas** [comment]
Thanks a lot for the suggestion. Yes, I am using a custom code and using your app as a library to stream.
