### ISSUE TITLE
Take input from external RTSP source / transmux to pusher

### ISSUE THREAD

**Issue by t3therdev** [pedroSG94/rtmp-rtsp-stream-client-java#734]
Hi, we are looking to see how we can expand on this library to include support for rtsp sources. Currently we want to allow the user to select between android cameras and external RTSP sources (h264 video and aac audio), we need to be able to preview/display them as well as transmux to push to rtsp the same way the android camera is. For example we want to take the rtsp in and take the h264 nals or rtsp payload and insert it where the normal encoder would go in your library, so that we could push it the same way as android cameras.

**Comment by pedroSG94** [comment]
You have multiples ways to get RTSP video/audio from external RTSP sources.
I did an example using VLC but only support video:
https://github.com/pedroSG94/AndroidReStreamer
You need find a way to get audio and video and send it to RtspClient class.
