### ISSUE TITLE
Prerecorded video is not streaming properly, showing blurred lines only

### ISSUE THREAD

**Issue by bharat-supekar** [pedroSG94/rtmp-rtsp-stream-client-java#736]
I'm using camera stream for one streaming url  and pre recorded video/stored video stream for another streaming url.

Camera streaming is working fine but From file RTMP  i.e. pre recorded video stream for another URL is not working,

Below is code snippet for same -->

if (!rtmpCamera1.isStreaming()) {
          if (rtmpCamera1.isRecording()
              || rtmpCamera1.prepareAudio() && rtmpCamera1.prepareVideo()) {
            button.setText(R.string.stop_button);
            rtmpCamera1.startStream(etUrl.getText().toString());
          } else {
            Toast.makeText(this, "Error preparing stream, This device cant do it",
                Toast.LENGTH_SHORT).show();
          }
        } else {
          button.setText(R.string.start_button);
          rtmpCamera1.stopStream();
        }

        if (!rtmpFromFile.isStreaming()) {
          try {
            if (!rtmpFromFile.isRecording()) {
              if (prepare()) {
                button.setText(R.string.stop_button);
                rtmpFromFile.startStream(etUrlPreRecorded.getText().toString());
              } else {
                button.setText(R.string.start_button);
                rtmpFromFile.stopStream();
                Toast.makeText(this, "Error: unsupported file", Toast.LENGTH_SHORT).show();
              }
            } else {
              button.setText(R.string.stop_button);
              rtmpFromFile.startStream(etUrlPreRecorded.getText().toString());
            }
          } catch (IOException e) {
            Toast.makeText(this, "Error: file not found", Toast.LENGTH_SHORT).show();
          }
        } else {
          button.setText(R.string.start_button);
          rtmpFromFile.stopStream();
        }

Getting below error --> 
![testing_prerecorded_view](https://user-images.githubusercontent.com/73534690/100416159-c5b97400-30a3-11eb-8106-cd8e0ac8bab9.PNG)

**Comment by bharat-supekar** [comment]
getting something corrupted video rendering  as like above screenshot.
We are using .mp4 pre recorded video with size 1.36 MB

**Comment by pedroSG94** [comment]
If you reproduce that video in a player is working fine or video is corrupted?
If you can reproduce that video, can you share me that video to test?

**Comment by bharat-supekar** [comment]
Thanks for your reply, Appreciates your input.

video is fine, we tried in sample code but there also same thing we observed.
For all videos this is happening.
