### ISSUE TITLE
[Question]control draw of the AndroidViewFilter.

### ISSUE THREAD

**Issue by reon69or** [pedroSG94/rtmp-rtsp-stream-client-java#737]
Android View Filter is applied to the stream broadcasting service.
I want to limit the filter drawing to 30 sheets per second.
How to limit filter drawing?
How can control draw() function?

**Comment by pedroSG94** [comment]
In this conditional, the filter is drawing:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/gl/render/filters/AndroidViewFilterRender.java#L92

**Comment by reon69or** [comment]
I know the draw conditions.
Can I adjust the draw filter counter?
I want to limit it to 20 frames per second,
