### ISSUE TITLE
[question] Screen distorted

### ISSUE THREAD

**Issue by reon69or** [pedroSG94/rtmp-rtsp-stream-client-java#740]
Dear.pedro.
Applied web view to Android view filter in streaming broadcasting.
When there is motion in the Android view filter area, the screen is distorted.
rtmpSurfaceView =  (OpenGlView) findViewById(R.id.rtmp_camera_view);
        rtmpSurfaceView.getHolder().addCallback(this);
        rtmpCamera1 =  new RtmpCamera2(rtmpSurfaceView,this);

private boolean prepareEncoder(int resolution){
        int width = 0;
        int height = 0;
        int videoBitRate = 0;
        int videoFramelate = 30;
        try{
            if( resolution == 0 ){
                width = 640;
                height = 360;
                videoBitRate = 1000;
            } else if( resolution == 1 ) {
                width = 960;
                height = 540;
                videoBitRate = 2000;
            } else {
                width = 1280;
                height = 720;
                videoBitRate = 3000;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        return rtmpCamera1.prepareVideo(width,height,videoFramelate,videoBitRate*1024,false,CameraHelper.getCameraOrientation(this))
                && rtmpCamera1.prepareAudio();
    }

[screen_distorted.zip](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/5650159/screen_distorted.zip)

**Comment by pedroSG94** [comment]
can you share xml ui and webview url to reproduce the problem?

**Comment by reon69or** [comment]
Hi. pedro
stream activity is as below
<androidx.drawerlayout.widget.DrawerLayout

    tools:context="com.theenm.live.LiveStreamingActivity"
    android:id="@+id/drawer_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="horizontal"
    >

    <RelativeLayout
        android:layout_width="match_parent"

        android:layout_height="match_parent"
        android:id="@+id/main_layout"
        android:background="@color/color_000000">
        

        <FrameLayout
            android:id="@+id/surface_layout"
            android:layout_width="match_parent"




            android:layout_height="match_parent">

                
            <RelativeLayout
                android:id="@+id/camera_layout"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:gravity="center_horizontal">
                <com.pedro.rtplibrary.view.OpenGlView
                    android:id="@+id/rtmp_camera_view"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:layout_gravity="top"
                    app:aspectRatioMode="adjust"
                    app:keepAspectRatio="false"
                    app:AAEnabled="true"  />
            </RelativeLayout>

            <FrameLayout
                android:id="@+id/layout_full"
                android:layout_width="match_parent"
                android:layout_height="match_parent">
            </FrameLayout>

for web view setting as below
private void initPresetWebView(){
        WebSettings webSettings = presetWebView.getSettings();
        if(webSettings != null){
            webSettings.setJavaScriptEnabled(true);
            webSettings.setLoadsImagesAutomatically(true);
            webSettings.setUseWideViewPort(true);
            webSettings.setSupportZoom(true);
            webSettings.setBuiltInZoomControls(true);
            webSettings.setDisplayZoomControls(true);
            webSettings.setAppCacheEnabled(false);
            webSettings.setLoadWithOverviewMode(true);
            webSettings.setCacheMode(WebSettings.LOAD_NO_CACHE);
            webSettings.setAllowContentAccess(false);
            webSettings.setMediaPlaybackRequiresUserGesture(true);
            if( Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP )
            {
                // HTTPS HTTP 의 연동, 서로 호출 가능하도록
                webSettings.setMixedContentMode(WebSettings.MIXED_CONTENT_ALWAYS_ALLOW);
            }
            presetWebView.setHorizontalScrollBarEnabled(false);
            presetWebView.setVerticalScrollBarEnabled(false);
            // 웹뷰 클라이언트 등록
            presetWebView.setWebChromeClient(new LiveStreamingActivity.MyWebChromeClient());
            // 웹 크롬 클라이언트 등록
            presetWebView.setWebViewClient(new LiveStreamingActivity.MyWebViewClient());
        }
    }


create webview
private void creatPresetEffectScreen(int type){

        if(mPreseEffectLayout.getVisibility() != View.VISIBLE){
            mPreseEffectLayout.setVisibility(View.VISIBLE);
        }
        if(findViewById(R.id.layout_full).getVisibility() ==View.VISIBLE){
            findViewById(R.id.layout_full).setVisibility(View.INVISIBLE);
        }
        mPresetApply =false;
        mPresetType = type;
        setPresetScreen(mPresetApply);
        FrameLayout.LayoutParams frame= new FrameLayout.LayoutParams(rtmpSurfaceView.getWidth(),rtmpSurfaceView.getHeight());
        if(getRequestedOrientation() == ActivityInfo.SCREEN_ORIENTATION_PORTRAIT){
            frame.gravity = Gravity.TOP|Gravity.LEFT;
        }else{
            frame.gravity = Gravity.CENTER_HORIZONTAL;
        }
        mPreseEffectLayout.setLayoutParams(frame);
        if(!bModifyPreserView){
            mContainWebView = new FrameLayout(this);
            mContainWebView.setLayoutParams(new FrameLayout.LayoutParams(500,500));
            presetWebView.setLayoutParams(mContainWebView.getLayoutParams());
            presetWebView.setFocusable(false);
            presetWebView.setFocusableInTouchMode(false);
            presetWebView.setBackgroundColor(0);
            presetWebView.setY((float)mPreseEffectLayout.getTop() + presetViewCap);
            presetWebView.setTag(presetAddViewId);
            presetWebView.setId(type);
            if(mPresetViewList.size() >0) {
                for (int i = 0; i < mPresetViewList.size(); i++) {
                    if(i == mPresetViewList.size()-1){
                        mPresetViewList.get(i).setBackground(getResources().getDrawable(R.drawable.shape_broadcasting_preset_edit));
                    }
                    else{
                        mPresetViewList.get(i).setBackground(null);
                    }
                }
            }
            mPresetViewList.add(presetWebView);
            presetViewCap = (mPresetViewList.size()+1)* 100;
            presetAddViewId++;
        }
        if(misReadyBroadCast){
            // 방송 중 프리셋 편집시 필터 제거 후 재 적용
            rtmpCamera1.getGlInterface().setFilter(presetAlert, new NoFilterRender());
            rtmpCamera1.getGlInterface().setFilter(presetGoal, new NoFilterRender());
            rtmpCamera1.getGlInterface().setFilter(presetSubtitle, new NoFilterRender());
            rtmpCamera1.getGlInterface().setFilter(presetBanner, new NoFilterRender());
        }
        mPreseEffectLayout.removeAllViews();
        mPreseEffectLayout.addView(mPresetEditCancel);
        mPreseEffectLayout.addView(mPresetEditSave);

        if(mPresetViewList.size() >0) {
            for (int i = 0; i < mPresetViewList.size(); i++) {
                if(i == mPresetViewList.size()-1){
                    if(bModifyPreserView)
                        mPresetViewList.get(i).setBackground(null);
                    else
                        mPresetViewList.get(i).setBackground(getResources().getDrawable(R.drawable.shape_broadcasting_preset_edit));
                }
                else{
                    mPresetViewList.get(i).setBackground(null);
                }
                mPreseEffectLayout.addView(mPresetViewList.get(i));
                setPresetEffectEvent(mPresetViewList.get(i));
            }
        }
        mPreseEffectLayout.bringToFront();
        mPreseEffectLayout.requestLayout();
   }

You can reference this url.  :  https://widget.popkontv.com/page/rdnc1d2e3p-ooKjg0NHMoA/0

**Comment by pedroSG94** [comment]
Your code is working fine for me:

https://user-images.githubusercontent.com/17556876/103083112-e362f600-45db-11eb-97d8-7d5f6fc169db.mp4
