### ISSUE TITLE
network bandwidth usage for streaming 

### ISSUE THREAD

**Issue by psddas** [pedroSG94/rtmp-rtsp-stream-client-java#741]
Hello pedro,

Could you please let me know how much minimum internet bandwidth is needed/expected for each stream in different resolutions, like, 480p,720p, and 1080p?

Also, could you please give some idea about at what interval each packet is sent and how many frames each packet contains? 

Thanks.

**Comment by pedroSG94** [comment]
Hello you can use youtube stream specification as guide.
https://support.google.com/youtube/answer/2853702?hl=en
