### ISSUE TITLE
Streamusb in background service

### ISSUE THREAD

**Issue by t3therdev** [pedroSG94/rtmp-rtsp-stream-client-java#742]
Hi, we are reviewing your project to stream a uvc usb camera using your library. Is it possible to do this as a background service?

**Comment by pedroSG94** [comment]
I think that you need a accept a window each time you connect a USB camera so I think this is not possible but I'm not sure about it since USB library is not my project. You can ask it to library owner:
https://github.com/saki4510t/UVCCamera
