### ISSUE TITLE
Video Encoder callback are only being received while phone is in use

### ISSUE THREAD

**Issue by parthivmistri** [pedroSG94/rtmp-rtsp-stream-client-java#745]
@pedroSG94 Need your help here,

I'm using Display Service and what I observed is we are getting callback **onOutputBufferAvailable** only if the device is being used (scrolling, surfing, etc) so what if someone is just streaming his display without doing anything in that case we are not able to write any video packets. and the video goes blank on the client-side.

Can you please look into it and let me know If you need help on testing the scenarios.

Also, one more question on microphone audio I have enabled **noiseSuppressor** and **echoCanceler** but I'm getting a lot more noise. 

Thanks in advance.

**Comment by pedroSG94** [comment]
The first case is not a bug. This is related with MediaProjection API:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/63
Try force render using this method but I 
The second case is a software filter provided by Android and in some cases this is not working fine.
https://developer.android.com/reference/android/media/audiofx/NoiseSuppressor

**Comment by parthivmistri** [comment]
@pedroSG94 Thanks for that trick to make the screen fore-fully refresh using notification. 

You have any alternative options to make the audio quality better?

**Comment by pedroSG94** [comment]
I only can tell you create your own audio filter:
```java
rtmpCamera1.setCustomAudioEffect(new CustomAudioEffect() {
      @Override
      public byte[] process(byte[] pcmBuffer) {
        //return pcmBuffer modified. This buffer must have same size that the original buffer.
        return pcmBuffer;
      }
    });
```
Unfortunatelly. This is really difficult to implement because you need know so much about it.

**Comment by parthivmistri** [comment]
Yeah, I figured out this method but I thought maybe you have some idea to process buffer, anyway thanks for the assistance I'll try by myself and will keep you posted if I figured out anything. 

Thanks again.
