### ISSUE TITLE
Error when switch camera

### ISSUE THREAD

**Issue by cryinrain69** [pedroSG94/rtmp-rtsp-stream-client-java#746]
**Device running android 10 (API 29), Kotlin, lib v1.9.5**
Sometimes, i had error:

I'm using RtmpCamera2, when i call rtmpCamera?.switchCamera(), camera preview not switch and print log:
````java
Camera2ApiManager: Open failed
````
Please help me.
Thanks

**Comment by pedroSG94** [comment]
Did you check that your device support that resolution in front camera?
```java
rtmpCamera1.getResolutionsFront();
rtmpCamera1.getResolutionsBack();
```

**Comment by cryinrain69** [comment]
> Did you check that your device support that resolution in front and back camera?
> 
> ```java
> rtmpCamera1.getResolutionsFront();
> rtmpCamera1.getResolutionsBack();
> ```

Yes I have checked.
The problem is that it is sometimes, not continuously :-(

**Comment by pedroSG94** [comment]
Sorry for late reponse. I was in holydays.
Can you provide me errors of cameraerror callback?
```java
rtmpCamera1.setCameraCallbacks(new CameraCallbacks() {
      @Override
      public void onCameraChanged(boolean isFrontCamera) {

      }

      @Override
      public void onCameraError(String error) {
        Log.e("Camera error", error);
      }
    });
```

**Comment by JulianKowalczuk** [comment]
I'm using 1.9.5 version in Flutter app.
On Samsung Note 8 I got same message, but rest devices works fine.
I'm not Java guy, so I can't tell You more about that, I came here just to bump issue, since switching camera is key in our app.
Both cameras work fine when choosing it first time in app, but to switch it app restart is required.

**Comment by pedroSG94** [comment]
I need any info about it to debug.
Are you using camera1 or camera2?
Can you provide me any logcat or error?

**Comment by JulianKowalczuk** [comment]
Camera2.
The error comes from Camera2ApiManager.java onError func in 790 line.
Some errors are logged with primary error description and native exception, like in 145 line.
The only error information I get is the one mentioned by issue's author.

**Comment by pedroSG94** [comment]
Can you print this int i value?
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java#L790
