### ISSUE TITLE
Giphy

### ISSUE THREAD

**Issue by MohammadRezaei92** [pedroSG94/rtmp-rtsp-stream-client-java#748]
How can I convert gifs from Giphy sdk to inputStream for `GifObjectFilterRender `
https://github.com/Giphy/giphy-android-sdk-ui-example/blob/master/Docs.md

**Comment by pedroSG94** [comment]
Sorry for late reponse. I was in holydays.
You can try add it as AndroidViewFilterRender using a view provided by that library:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L145
