### ISSUE TITLE
ECONNRESET (Connection reset by peer)

### ISSUE THREAD

**Issue by ozankonur** [pedroSG94/rtmp-rtsp-stream-client-java#75]
Sometimes I am getting this error:

Caught SocketException while reading/decoding packet, shutting down: recvfrom failed: ECONNRESET (Connection reset by peer)
10-24 15:19:39.600 13137-16383/com.app E/ACodec: [OMX.qcom.video.encoder.avc] calling emptyBuffer 0xb8e04518 w/ time 2383965 us
10-24 15:19:39.600 13137-16402/com.app E/RtmpConnection: Caught SocketException during write loop, shutting down: sendto failed: EPIPE (Broken pipe)
10-24 15:19:39.620 13137-16371/com.app E/ACodec: [OMX.google.aac.encoder] calling emptyBuffer 0x65205d30 w/ time 2392293 us
10-24 15:19:39.630 13137-16383/com.app E/ACodec: [OMX.qcom.video.encoder.avc] calling emptyBuffer 0xb8e04478 w/ time 2413659 us

I dont know if this is because of server side..

**Comment by pedroSG94** [comment]
Normally yes. Server side:
https://stackoverflow.com/questions/11207394/getting-socketexception-connection-reset-by-peer-in-android

**Comment by ozankonur** [comment]
Hi Pedro,

Is it possible to solve this issue on client side ? As I saw from the stackoverflow there is a solution like that;

"Try to set this property for your HttpURLConnection before connecting:   conn.setRequestProperty("connection", "close"); 
This will disable "keep-alive" property which is on by default "
