### ISSUE TITLE
share screen bug

### ISSUE THREAD

**Issue by 555chy** [pedroSG94/rtmp-rtsp-stream-client-java#751]
The 1.8.4 version use to share screen is normal ok, but when i update this version to 1.9.5, the delay of rtmp was too long, some times more then one minute. I build a nginx+rtmp server in my local area network for test, then i found use ffplay to pull the stream is very difficult at 1.8.6 to 1.9.5, the tip of ffplay is nan. but when i change the version to 1.8.4, everything become normal

**Comment by pedroSG94** [comment]
Sorry for late reponse. I was in holydays.

I'm investigating it.
The only problem that you have is delay, right?
What do you means with?:
```
the tip of ffplay is nan
```
