### ISSUE TITLE
QUESTION: is it possible to remove the background from the camera1 with the help of green background?

### ISSUE THREAD

**Issue by abadoliverco** [pedroSG94/rtmp-rtsp-stream-client-java#752]
I want to know if we can achieve the green background effect using camera 1 or camera 2 using your library?
I want to remove the background and crop only the person

Thank you!

**Comment by pedroSG94** [comment]
Yes, you can do it.
You need create you own filter:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Real-time-filters
The idea is detect green pixels with a reasonable sensitive and replace it with other thing like an image or video.
To load image, video or gif you can read this:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/master/encoder/src/main/java/com/pedro/encoder/input/gl/render/filters/object
About detect green pixel you can use something similar to this to know pixel color and create your own function to get a sensitive range:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/res/raw/object_fragment.glsl
Where samplerPixel is camera color and objectPixel is image, video or gif color.

**Comment by pedroSG94** [comment]
I did a chroma filter for it. download project in last commit and test it:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/6e365869fa8531536fb61b050f6df75db5a31c99
