### ISSUE TITLE
How to set resolution and bitrate for screen broadcast?

### ISSUE THREAD

**Issue by noho501** [pedroSG94/rtmp-rtsp-stream-client-java#755]
I used this function prepareVideo(width, height, frameRate, bitRate, 0, densityDpi) but it won't work. 

Could you please give me an advice?

**Comment by pedroSG94** [comment]
That is working for me.
Did you check example?
Can you share your example code?

**Comment by hoangnn-htv** [comment]
> That is working for me.
> Did you check example?
> Can you share your example code?

Oh, so sorry, I mistake in my code. It works now. Thank you for the great library
