### ISSUE TITLE
QUESTION: Is it possible to get the sound from internal audio and at the same time with MIC via RTMPdisplay class?

### ISSUE THREAD

**Issue by abadoliverco** [pedroSG94/rtmp-rtsp-stream-client-java#756]
Hi @pedroSG94,

is it possible to get the internal audio and at the same time get the sound on the MIC I'm using RtmpDisplay.

thank you!

**Comment by pedroSG94** [comment]
I'm not sure about this. I never test it but you can create an stream with one of this, create a class with the other one and mix it using a CustomAudioEffect
