### ISSUE TITLE
Problem with broadcasting at 540x960

### ISSUE THREAD

**Issue by insidefun** [pedroSG94/rtmp-rtsp-stream-client-java#758]
![IMAGE 2021-01-18 14:42:51](https://user-images.githubusercontent.com/9580252/104911139-7143be00-599b-11eb-8ac2-6b4a82b687d6.jpg)

RTMP
front camera
OpenGlViewI(
app:keepAspectRatio="true"
app:aspectRatioMode="fill"
)

startPreview(CameraHelper.Facing.FRONT, 960, 540, 90)

rtmpCamera1.prepareVideo(
            960,
            540,
            30,
            2000 * 1024,
            2,
            90
        )

**Comment by pedroSG94** [comment]
Can you share an image with a good reference to see distortion? (a circle for example)
If you record a video. Do you have this problem in the video?
