### ISSUE TITLE
Can't find the correct aspect ratio for the list of previewsizes

### ISSUE THREAD

**Issue by prudhvicoder** [pedroSG94/rtmp-rtsp-stream-client-java#76]
Dear Pedro..!!
I can't find the correct aspect ratio for the list of all the previewsizes that are coming from cameramanager.getResolutions() method. The adaptive resolution 720 x 480 only works correct aspect ratio, don't know why..!! My camera is stretched and the preview is looking so weird that all the images are stretched. But the video in the stream is working fine. How can I achieve correct aspect ratio for the preview size which is supportable by my camera?

**Comment by prudhvicoder** [comment]
Yes, my camera preview is stretched. How can I find the correct aspect ratio? Btw, if I use texture mode the app is only compatible with above the lollipop versions. I need my app to work on below lollipop versions also.

**Comment by pedroSG94** [comment]
Go to the example and replace object rtmpcamera2 to rtmcamera1 and it should work

**Comment by prudhvicoder** [comment]
Thanks pedro, It's working but I want full-screen camera preview, the autofittextureview is reducing the height of preview by keeping aspect ratio with 640 x 480 dimension. Is there any way to achieve full-screen preview by keeping aspect ratio?

**Comment by pedroSG94** [comment]
You need select a stream resolution with same aspect ratio than your device screen.
For example:
If you have a screen with 1280px x 720px you can use a stream resolution with the same aspect ratio. Like 1280x720, 1920x1080, 852*480, etc.
If 720x480 is working fine for you then you should found a resolution with a width = height * 1.5. My library show you all resolutions that your device can open the camera select one of that. If anyone work for you maybe you can found other resolution doing a modify in Camera1ApiManager class and use setPictureSize instance of setPreviewSize that some times give you other resolutions.

**Comment by pedroSG94** [comment]
@rkoshti https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/167
