### ISSUE TITLE
RTSP broadcasting not working 

### ISSUE THREAD

**Issue by StewardH** [pedroSG94/rtmp-rtsp-stream-client-java#761]
Hi ,

Your lib is great on RTMP, thank you. We have also tried the other half of it, specifically the RTSP client that comes with it  (implemented in the default example as well as the custom example). Unfortunately it does not work. To narrow down the issue we have tested several media servers with it: red5 (ant media variant), ffmpeg server as well as the rtsp-simple-server(https://github.com/aler9/rtsp-simple-server). This library does connect via TCP to its server but it fails on UDP. However, once connected on TCP it does not stream anything: the streamed packets look empty on VLC. To make sure we don't deal with a network issue I have tried streaming with a different streaming app (the Larix Broadcaster https://play.google.com/store/apps/details?id=com.wmspanel.larix_broadcaster&hl=en_US&gl=US). It looks like larix does manage to stream to both ffmpeg as well as the other server on both RTSP as well as RTMP. So unfortunately it seems like the issues is with the rtmp-rtsp-stream-client-java library.
Let me know if you need further details in order to replicate and address this issue.

Regards,
Steward

**Comment by StewardH** [comment]
Update: I just tested the 1.9.7 release and I can confirm that the RTSP over TCP is fixed. On the other hand on UDP I can connect to the server however no data is transmitted over. VLC first tries to read over UDP and after 10s of radio silience it switches to TCP. Here is the VLC output log:  

main debug: `rtsp://localhost/phone/conn' successfully opened
qt debug: IM: Setting an input
live555 warning: no data received in 10s. Switching to TCP
main debug: killing decoder fourcc `h264'
main debug: removing module "avcodec"
main debug: removing module "h264"
main debug: killing decoder fourcc `mp4a'
main debug: removing module "faad"
main debug: Program doesn't contain anymore ES
live555 debug: RTP subsession 'video/H264'
main debug: looking for packetizer module matching "any": 25 candidates
h264 debug: found NAL_SPS (sps_id=0)
h264 debug: found NAL_PPS (pps_id=0 sps_id=0)
main debug: using packetizer module "h264"
main debug: looking for video decoder module matching "any": 19 candidates
avcodec debug: using ffmpeg Lavc58.6.103
avcodec debug: CPU flags: 0x000fd3db
avcodec debug: allowing 6 thread(s) for decoding
avcodec debug: codec (h264) started
avcodec debug: using frame thread mode with 6 threads
main debug: using video decoder module "avcodec"
live555 debug: RTP subsession 'audio/MPEG4-GENERIC'
main debug: looking for audio decoder module matching "any": 23 candidates
main debug: using audio decoder module "faad"
live555 debug: setup start: 0.000000 stop:0.000000
live555 debug: We have a timeout of 60 seconds
live555 debug: play start: 0.000000 stop:0.000000
live555 error: no data received in 10s, aborting
main debug: EOF reached
main debug: killing decoder fourcc `h264'
main debug: removing module "avcodec"
main debug: removing module "h264"
main debug: killing decoder fourcc `mp4a'
main debug: removing module "faad"
main debug: removing module "live555"
main debug: Program doesn't contain anymore ES
main debug: dead input
main debug: changing item without a request (current 3/4)
main debug: nothing to play
qt debug: IM: Deleting the input

**Comment by pedroSG94** [comment]
fixed:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/c2678c87d8f97c9960500d5262c84c65a6c7ac75
I will update version after resolve others issues. For now you can use this gradle:
```gradle
	        implementation 'com.github.pedroSG94:rtmp-rtsp-stream-client-java:c2678c87d8'
```

**Comment by StewardH** [comment]
Thank you, I will take a look
