### ISSUE TITLE
Replacing a openglview

### ISSUE THREAD

**Issue by mdmuneerhasan** [pedroSG94/rtmp-rtsp-stream-client-java#763]
Hello everyone!!
How can I change OffScreenGlThread to openglview and vice-versa in RtmpCamera1 class.
I can do same thing in RtmpFromFile class as their is already method available for this.

I have created this method but it is giving error.

  public void replaceGlInterface(GlInterface glInterface) {
    if (this.glInterface != null && Build.VERSION.SDK_INT >= 18) {
      if (isStreaming()||isRecording()) {
        try {
          this.glInterface.removeMediaCodecSurface();
          this.glInterface.stop();

          this.glInterface = glInterface;
          videoEncoder.reset();

          if (!(glInterface instanceof OffScreenGlThread)) {
            glInterface.init();
          }

          prepareGlView();

        } catch (Exception e) {
          Log.e(TAG, "Error", e);
        }

      } else {
        this.glInterface = glInterface;
        this.glInterface.init();
        camera1ApiMuneer = new Camera1ApiMuneer(glInterface.getSurfaceTexture(), context);
        init();
      }
    }

  }

**Comment by pedroSG94** [comment]
You already can do it:
```java
rtmpCamera1.replaceView(context);
```

**Comment by mdmuneerhasan** [comment]
Thanks I got that.
