### ISSUE TITLE
getStreamFrameTopicture

### ISSUE THREAD

**Issue by hbbdzry** [pedroSG94/rtmp-rtsp-stream-client-java#767]
I want to get real-time streaming frames into pictures, how to get it

**Comment by pedroSG94** [comment]
You need use OpenGlView and use this method:
```java
rtmpCamera1.getGlInterface().takePhoto(new TakePhotoCallback() {
      @Override
      public void onTakePhoto(Bitmap bitmap) {
        
      }
    });
```

**Comment by hbbdzry** [comment]
thank you very much,how to use OpenGlView，Replace SurfaceView with  OpenGlView？

**Comment by hbbdzry** [comment]
thank you very much
