### ISSUE TITLE
Authorisation doesn't work with retry

### ISSUE THREAD

**Issue by marcin-adamczewski** [pedroSG94/rtmp-rtsp-stream-client-java#769]
Hi @pedroSG94 

After calling Camera2Base.retry() the user and password set with `setAuthorization(user, pass)` method are cleared.
They are cleared because on retry the SrsFlvMuxer.reConnect() is being called and then RtmpConnection.shutdown() and RtmpConnection.reset() which clears user and password.
So the effect is that reconnection doesn't work as the credentials are cleared and auth error is returned.

To reproduce:

```
rtmpCamera1.setAuthorization("user", "pass");
rtmpCamera1.startStream(url);

...

  @Override
  public void onConnectionFailedRtmp(final String reason) {
    runOnUiThread(new Runnable() {
      @Override
      public void run() {
        if (rtmpCamera1.reTry(5000, reason)) {
          rtmpCamera1.setAuthorization("user", "pass"); // doesn't help
        } else {
          rtmpCamera1.stopStream();
        }
      }
    });
  }
```

Calling `setAuthorization("user", "pass");` again before or after rtmpCamera1.reTry() doesn't help.

**Comment by pedroSG94** [comment]
I will fix it in the next commit(today or maybe tomorrow). Thanks for report

**Comment by pedroSG94** [comment]
Fixed:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/9d22352b79b8ebf3d13da05c8106b26a8dbc20aa

**Comment by marcin-adamczewski** [comment]
Thanks @pedroSG94 
So if you don't clear the user and pass anymore, then it won't be problematic to connect to a different stream with a different user and password using the same RtmpCamera object, right? Because before `RtmpCamera.start()` I would have to call `setAuthenticate(user, pass)` either way so it will be set to new credentials.

**Comment by pedroSG94** [comment]
If you want change Auth you can call it before startStream or retry and all should work fine.

Also, if you don't need Auth, you don't need call anything because library try to connect without Auth before and then set Auth when server response that you need it.
Anyway, you can clear Auth if you set user and password to null.
