### ISSUE TITLE
How to keep this app showing when executing the display activity example?

### ISSUE THREAD

**Issue by addriumruss** [pedroSG94/rtmp-rtsp-stream-client-java#773]
Environment: android10.
It's needed to keep current app showing where push video stream from phone screen. Is it possible?

**Comment by pedroSG94** [comment]
I don't fully understand your question but maybe you can show info about it using a notification or an opengl filter. You have all opengl filter with example here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java

**Comment by addriumruss** [comment]
Got it, Thks! 
Yestoday I just tried the custom push, and just minute ago i found the opengl example is OK to my question. 
Sorry for the bother!
