### ISSUE TITLE
Is it possible to push stream from a texturesurface instead of camera?

### ISSUE THREAD

**Issue by addriumruss** [pedroSG94/rtmp-rtsp-stream-client-java#774]
Is it possible to push stream from a texturesurface instead of camera?

**Comment by addriumruss** [comment]
The surfacemodeexample and texturemodeexample both failed the test in an android 10 phone.

**Comment by pedroSG94** [comment]
It is possible but no by default. You need modify the library to do it.
Can you provide any logcat or info about your error? It is working for me in oneplus 7T with android 10.

**Comment by addriumruss** [comment]
Thks! 
I changed the "RtspCamera2" to "RtspCamera1", and "RtmpCamera2" to "RtmpCamera1", then they both succeed. 
Sometimes there is need to push stream from one texturesurface, otherwise I could only use the fullscreen stream-push. About modifying the library, I'll find some time and give it a try.
