### ISSUE TITLE
I want To increase Frame Rate from on VLC media player by using this app can you please tell me about this thanks !!

### ISSUE THREAD

**Issue by DanishNaveed1228** [pedroSG94/rtmp-rtsp-stream-client-java#777]

**Comment by pedroSG94** [comment]
I'm not sure about your problem but this library is not related with VLC frame rate.
ABout frame rate in this library. You can stream to 60 fps is your device support it with camera1 or camera2 api or 30 fps that is supported by all device genarally (of course depend of resolution, bitrate, device hardware, etc).

To handle this. You can set fps in prepareVideo method and library will adapt frame rate to closest frame rate supported by your device.
