### ISSUE TITLE
Audio not working when using USB camera

### ISSUE THREAD

**Issue by ashikxcel** [pedroSG94/rtmp-rtsp-stream-client-java#778]
Thanks for this library. Im using this library for mobile streaming to youtube, works perfect. Using [https://github.com/pedroSG94/Stream-USB-test](url) I can use external camera to stream, but issue is only video is streaming and audio is not capturing. Also I need to use mobile microphone to stream audio and external camera to stream video, is it possible or not?

**Comment by pedroSG94** [comment]
That sample should work with mobile microphone and usb camera.
The problem is that I can't test it now because I haven't USB camera to test. For that reason that sample is abandoned.

**Comment by ToysoftInc** [comment]
@ashikxcel How did you the USB app to stream? When I tried it on my phone all I got was the blank screen. thx

**Comment by ashikxcel** [comment]
Audio is capturing when I use headphone.

**Comment by ashikxcel** [comment]
> @ashikxcel How did you the USB app to stream? When I tried it on my phone all I got was the blank screen. thx

Did you add this line in manifest file

<uses-feature android:name="android.hardware.usb.host"/>
