### ISSUE TITLE
Streaming in a device with RAM constraint

### ISSUE THREAD

**Issue by psddas** [pedroSG94/rtmp-rtsp-stream-client-java#780]
Hi, 
I am using your app as a library (with a bit of customization) to do streaming.
Using this app as a library just to do the streaming as the camera is used for other purpose as well. The surface of this library is  added to the camera along with other surfaces that I am using for other purposes. 

Now the RAM usage is going high as soon as I initialize the library and I have a very limited RAM in my target device.
So, could you suggest something that I could remove/optimize as I am using this app as a lib just to do the streaming. 

Thanks.

**Comment by pedroSG94** [comment]
This is really difficult to say.
Reduce bitrate, resolution and framerate will reduce CPU.
Also, maybe you can reduce the num of surfaces set to camera doing a copy with opengl delegating that responsability to GPU.

**Comment by psddas** [comment]
Thanks Pedro for the reply.
