### ISSUE TITLE
Unable to get the voice from mic using earphones

### ISSUE THREAD

**Issue by abadoliverco** [pedroSG94/rtmp-rtsp-stream-client-java#782]
Hi @pedroSG94,

I used the `prepareInternalAudio()` to get the internal audio from earphones but unfortunately, my voice from the mic is not captured, can you help me? thank you so much!

**Comment by pedroSG94** [comment]
prepareInternalAudio() is to capture audio from device (audio that should be reproduced by speakers) for example if you reproduce a video in youtube or sound of a game. Not to use earphone microphone.
This feature isn't developed. It seems that each phone provider do it different so it is difficult to implement, anyway you can try change audio source that could work in somes devices:
https://stackoverflow.com/questions/11077161/android-audiorecord-headphones-with-mic
Line to change:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/audio/MicrophoneManager.java#L59
