### ISSUE TITLE
Question: How to handle multiplie back cameras

### ISSUE THREAD

**Issue by Stewioie** [pedroSG94/rtmp-rtsp-stream-client-java#783]
I have a question about camera switching. Many devices has multiplie cameras at back but I can only use one of them.
How can I switch from all back cameras?

Thanks

**Comment by pedroSG94** [comment]
Normally this is not possible. Devices provider usually don't get access to all camera features using Camera1 or Camera2 of Android. They have her own api to do it and it is private.
To know if you can get all cameras. You can try like here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java#L712
With this method you can get all cameras id and open it. Actually this is developed to find back and front camera but you can modify it as you want.
That method is used in switch camera method:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java#L535
