### ISSUE TITLE
Question:: app not sending packets

### ISSUE THREAD

**Issue by natxopedreira** [pedroSG94/rtmp-rtsp-stream-client-java#787]
Hello

Im able to set bitrate now, thanks.

I want to create a basic sample recording screen and publishing to local server... example works perfect but not when i move code to a new app.

It compiles and run ok, i get asked for permission to record screen etc etc and i saw on server that i'm connected.

However it doesn't seem to write video packets.

On logcat i see at the begining some packets like
```
D/RtmpConnection: wrote packet: RTMP Video, size: 2998
D/RtmpConnection: wrote packet: RTMP Video, size: 24
```
But after a pair of seconds... nothing only
```
D/RtmpConnection: wrote packet: RTMP Audio, size: 33
D/RtmpConnection: wrote packet: RTMP Audio, size: 33
D/RtmpConnection: wrote packet: RTMP Audio, size: 33
```

Do you have any clue on whats happening? Example works perfect and im not able to see differences...

Thank you!

**Comment by pedroSG94** [comment]
I think that your problem is this:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/63
You can try create an animation to discard it.

**Comment by natxopedreira** [comment]
Yes!!! thank you a lot.... that was driving me nuts :)
