### ISSUE TITLE
Error EGL_BAD_MATCH on SurfaceManager

### ISSUE THREAD

**Issue by mandanai** [pedroSG94/rtmp-rtsp-stream-client-java#789]
Error **EGL_BAD_MATCH** on SurfaceManager.java from code like this below

`if (surface == null) {
      int[] surfaceAttribs = {
          EGL14.EGL_WIDTH, width, EGL14.EGL_HEIGHT, height, EGL14.EGL_NONE
      };
      eglSurface = EGL14.eglCreatePbufferSurface(eglDisplay, configs[0], surfaceAttribs, 0);
    }`

Error on some devices such as Oppo A83, Android 7.1.1

How to resolve this problem?

**Comment by pedroSG94** [comment]
Try this. In this line:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/gl/SurfaceManager.java#L125
Replace:
```java
int[] surfaceAttribs = {
          EGL14.EGL_WIDTH, width, EGL14.EGL_HEIGHT, height, EGL14.EGL_NONE
      };
```
To:
```java
int[] surfaceAttribs = {
          EGL14.EGL_WIDTH, width,
          EGL14.EGL_HEIGHT, height,
          EGL14.EGL_SURFACE_TYPE, EGL14.EGL_PBUFFER_BIT,
          EGL14.EGL_NONE

      };
```

**Comment by pedroSG94** [comment]
Also, share me your video configuration. Resolution must be power of 2.

**Comment by mandanai** [comment]
I replace the code that you answer to me but doesn't work for me.

This my video configuration (Kotlin)

>
> rtmpCamera = RtmpCamera1(openGlView, this)
> rtmpCamera.setReTries(500)
> 
> if (rtmpCamera.prepareAudio() && rtmpCamera.prepareVideo()) {
>     rtmpCamera.startStream(live?.rtmpLiveUrl)
> }
>

> 
>   override fun surfaceChanged(p0: SurfaceHolder?, p1: Int, p2: Int, p3: Int) {
>
>         rtmpCamera.startPreview(CameraHelper.Facing.FRONT, 640, 480, 90)
> 
>         if (!rtmpCamera.isStreaming) {
>             if (rtmpCamera.prepareAudio() && rtmpCamera.prepareVideo()) {
>                 rtmpCamera.startStream(live?.rtmpLiveUrl)
>             }
>         }
>   }
>

**Comment by pedroSG94** [comment]
According with opengl documentation this should be surface config:
https://www.khronos.org/registry/EGL/sdk/docs/man/html/eglCreatePbufferSurface.xhtml
Try this and show me Log.i() included:
```java
Log.i("debug", width + "x" + height);
      int[] surfaceAttribs = {
          EGL14.EGL_WIDTH, width,
          EGL14.EGL_HEIGHT, height,
          EGL14.EGL_SURFACE_TYPE, EGL14.EGL_PBUFFER_BIT,
          EGL14.EGL_TEXTURE_FORMAT, EGL14.EGL_NO_TEXTURE,
          EGL14.EGL_TEXTURE_TARGET, EGL14.EGL_NO_TEXTURE,
          EGL14.EGL_TEXTURE_FORMAT, EGL14.EGL_NO_TEXTURE,
          EGL14.EGL_NONE
      };
```

**Comment by mandanai** [comment]
@pedroSG94 
**Log:**

I/debug: **480x640**
E/AndroidRuntime: FATAL EXCEPTION: glThread
    java.lang.RuntimeException: eglCreateWindowSurface. EGL error: 12297
        at com.pedro.encoder.utils.gl.GlUtil.checkEglError(GlUtil.java:133)
        at com.pedro.encoder.input.gl.SurfaceManager.eglSetup(SurfaceManager.java:141)
        at com.pedro.encoder.input.gl.SurfaceManager.<init>(SurfaceManager.java:36)
        at com.pedro.rtplibrary.view.OpenGlView.run(OpenGlView.java:123)
        at java.lang.Thread.run(Thread.java:761)
I/Process: Sending signal. PID: 18339 SIG: 9

**Comment by mandanai** [comment]
@pedroSG94 
when add attribute below

EGL14.EGL_SURFACE_TYPE, EGL14.EGL_PBUFFER_BIT,
EGL14.EGL_TEXTURE_FORMAT, EGL14.EGL_NO_TEXTURE,
EGL14.EGL_TEXTURE_TARGET, EGL14.EGL_NO_TEXTURE

then error EGL_BAD_MATCH in all devices 😨

**Comment by pedroSG94** [comment]
Try this:
```java
      int[] surfaceAttribs = {
          EGL14.EGL_WIDTH, width,
          EGL14.EGL_HEIGHT, height,
          EGL14.EGL_SURFACE_TYPE, EGL14.EGL_PBUFFER_BIT,
          EGL14.EGL_TEXTURE_FORMAT, EGL14.EGL_NO_TEXTURE,
          EGL14.EGL_NONE
      };
```
Or:
```java
    int[] surfaceAttribs = {
          EGL14.EGL_WIDTH, width,
          EGL14.EGL_HEIGHT, height,
          EGL14.EGL_VG_ALPHA_FORMAT, EGL14.EGL_VG_ALPHA_FORMAT_PRE,
          EGL14.EGL_SURFACE_TYPE, EGL14.EGL_VG_ALPHA_FORMAT_PRE_BIT,
          EGL14.EGL_NONE
      };
```
Or:
```java
    int[] surfaceAttribs = {
          EGL14.EGL_WIDTH, width,
          EGL14.EGL_HEIGHT, height,
          EGL14.EGL_VG_ALPHA_FORMAT, EGL14.EGL_VG_ALPHA_FORMAT_PRE,
          EGL14.EGL_SURFACE_TYPE, EGL14.EGL_VG_ALPHA_FORMAT_PRE_BIT,
          EGL14.EGL_NONE
      };
```

**Comment by mandanai** [comment]
Thanks for helping me, I really appreciate it, @pedroSG94 
I have tried changing the code you provided to me, but it doesn't work 😭

**Comment by mandanai** [comment]
Oh @pedroSG94 , I can resolve it by add `EGL14.EGL_SURFACE_TYPE, EGL14.EGL_PBUFFER_BIT`

on in this line 
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/gl/SurfaceManager.java#L89

to replace with

>     int[] attribList;
>     if (eglSharedContext == null) {
>       attribList = new int[] {
>           EGL14.EGL_RED_SIZE, 8, EGL14.EGL_GREEN_SIZE, 8, EGL14.EGL_BLUE_SIZE, 8, 
>           **EGL14.EGL_SURFACE_TYPE, EGL14.EGL_PBUFFER_BIT,**
>           EGL14.EGL_RENDERABLE_TYPE, EGL14.EGL_OPENGL_ES2_BIT,
>           EGL14.EGL_NONE
>       };
>     } else {
>       attribList = new int[] {
>           EGL14.EGL_RED_SIZE, 8, EGL14.EGL_GREEN_SIZE, 8, EGL14.EGL_BLUE_SIZE, 8,
>           **EGL14.EGL_SURFACE_TYPE, EGL14.EGL_PBUFFER_BIT,**
>           EGL14.EGL_RENDERABLE_TYPE, EGL14.EGL_OPENGL_ES2_BIT, EGL_RECORDABLE_ANDROID, 1,
>           EGL14.EGL_NONE
>       };
>     }
