### ISSUE TITLE
Background Audio/Video RSTP Stream

### ISSUE THREAD

**Issue by DaviGia** [pedroSG94/rtmp-rtsp-stream-client-java#79]
Hi, that's a very good library! You saved me! Keep it running!

I have a question, can you provide an example on how to use your library to stream audio and video via RTSP without a surfaceView? I need to use it on a Service and I do not want to show the playback to the user. I think I'm looking for an example for the Camera2Base builder and I cannot see it in the examples.

**Comment by pedroSG94** [comment]
Simple use surface mode example and set in constructor a context instance of surfaceview. This use camera2 API so you need API >= 21

**Comment by DaviGia** [comment]
Ok, got it. I have one more question, is it possible to use the library as a produder of a rtsp stream without actually rely on an external server? What I really need is to use it as RTSP Server (like libstreaming's RtspServer). What I need is to be able to process the rtsp stream from the android device with ffmpeg, or directly play it with ffplay.
Is it possible? if no, can you provide some informations on how to do it? A RTSP server implementation is available [here](https://github.com/fyhertz/libstreaming/blob/master/src/net/majorkernelpanic/streaming/rtsp/RtspServer.java)

**Comment by pedroSG94** [comment]
No this library can't do it. 
I think you can create your own RtspServer class, teorically my packets and encoder should work for you so you only need add this.

**Comment by DaviGia** [comment]
Hi, I discovered that ffmpeg can even serve as rtsp server just adding "-rtsp_flags listen". The problem is that ffmpeg fails to recognize the profile-level-id field of the video track. The error is:

[rtsp @ 0000025e53a824a0] sdp: m='video 5002 RTP/AVP 96'
[rtsp @ 0000025e53a824a0] sdp: a='rtpmap:96 H264/90000'
[rtsp @ 0000025e53a824a0] video codec set to: h264
[rtsp @ 0000025e53a824a0] sdp: a='fmtp:96 packetization-mode=1;profile-level-id=42c029;sprop-parameter-sets=Z0KAHtoCgPaAbQoTUA==,aM4G4g==;'
**[rtsp @ 0000025e53a824a0] The profile-level-id field size is invalid (42)**
[rtsp @ 0000025e53a824a0] RTP Packetization Mode: 1
[rtsp @ 0000025e53a824a0] RTP Profile IDC: 42 Profile IOP: c0 Level: 29
[rtsp @ 0000025e53a824a0] Extradata set to 0000025e522cc800 (size: 25)
[rtsp @ 0000025e53a824a0] sdp: a='control:trackID=1'

have you ever tried to use ffmpeg as server and make it working? I'm basically using your default example project, selecting "surface mode rtsp" mode and typing the the ip when ffmpeg is running.

Thanks in advance

**Comment by pedroSG94** [comment]
No, I never try that. Can you give me the command to test? (on desktop if you can)
I only need install ffmpeg, right?
This is possible with rtmp too? (maybe work)

**Comment by pedroSG94** [comment]
according with: https://tools.ietf.org/html/rfc6184 (8.1)
profile-level-id is optional.
Try delete the string in the connection and test. I don't know if this work but...
delete: profile-level-id=" + "42c029" + ";
from:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtsp/src/main/java/com/pedro/rtsp/rtsp/Body.java#L57

**Comment by DaviGia** [comment]
Hi, yes I was watching the SDP specification and find out that it's optional. I don't know why you hardcoded that string in the code, but I think you must either remove it or generate it dynamically because that base16 string actually force a constrained profile, in that case Constrained Baseline 4.1 but each device has a different default profile.

**Comment by pedroSG94** [comment]
I deleted profile-level-id and work. 
Library updated, get last commit or compile version 1.2.1
My test that worked:
ffmpeg command
`sudo ffmpeg -loglevel 99 -rtsp_flags listen -i rtsp://192.168.1.110:1935/live/pedro -c:v copy -c:a copy -sn output.mp4`

And I open endpoint:  
`rtsp://192.168.1.110:1935/live/pedro`

**Comment by DaviGia** [comment]
Great! That should now work on any device.

I have one remaining problem, I'm trying to set encoding resolution at 1920x1080 but in the logcat I see:

E/CameraDevice-0-LE: Surface with size (w=1920, h=1080) and format 0x1 is not valid, size not in valid set: [1280x960, 1280x720, 960x720, 960x540, 720x720, 864x480, 720x540, 800x480, 720x480, 768x432, 640x480, 576x432, 480x320, 384x288, 352x288, 320x240, 240x160, 208x144, 176x144, 144x176, 160x120]
W/CameraDevice-JV-0: Stream configuration failed
E/CameraCaptureSession: Session 0: Failed to create capture session; configuration failed
I/Camera2ApiManager: camera opened

and then the stream does not start. Have you a workaround or fix for that error?

**Comment by pedroSG94** [comment]
If you open custom example and see resolutions in options, can you see 1920x1080? If not, You cna get more resolutions supported for your camera if you go to:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java
And replace preview to picture in:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java#L112
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java#L291
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java#L295

If you do it maybe you can see more resolution in options. If you cant see 1920x1080 then your camera can't open that resolution.
Your device could encode 1080 but your camera maybe can't open to that resolution (for example my samsung S7 can record to 3k but can encode to 4k resolution).

**Comment by DaviGia** [comment]
Yes, I think you're right. Thank you.
