### ISSUE TITLE
Question: variable bitrate

### ISSUE THREAD

**Issue by natxopedreira** [pedroSG94/rtmp-rtsp-stream-client-java#790]
Hello

Maybe i say something dumb but exist something like variable bitrate¿?

Thank you

**Comment by pedroSG94** [comment]
Yes:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Adaptative-video-bitrate

**Comment by natxopedreira** [comment]
Super!!!

Even if i set a bitrate on prepareVideo method using prepareVideo method BitrateAdapter will overwrite this on the fly to adapt to bandwidth?

**Comment by pedroSG94** [comment]
Yes. Or you can change it on fly as you want.

**Comment by natxopedreira** [comment]
im curious, can i ask how it calculate what value is the best one?

**Comment by pedroSG94** [comment]
It is increasing of decreasing bitrate depend of frame queue state (depend of congestion in the queue).

**Comment by natxopedreira** [comment]
thank you!
