### ISSUE TITLE
BaseEncoder throw java.nio.BufferUnderflowException when using multiple srsFlvMuxer to stream

### ISSUE THREAD

**Issue by chauvansang1997** [pedroSG94/rtmp-rtsp-stream-client-java#796]
Hear is my code in RtmpCamera1.java:
` package com.pedro.rtplibrary.rtmp;

import android.content.Context;
import android.media.MediaCodec;
import android.os.Build;

import androidx.annotation.RequiresApi;

import android.view.SurfaceView;
import android.view.TextureView;

import com.pedro.rtplibrary.base.Camera1Base;
import com.pedro.rtplibrary.view.LightOpenGlView;
import com.pedro.rtplibrary.view.OpenGlView;

import java.nio.ByteBuffer;

import net.ossrs.rtmp.ConnectCheckerRtmp;
import net.ossrs.rtmp.SrsFlvMuxer;

/**
 * More documentation see:
 * {@link com.pedro.rtplibrary.base.Camera1Base}
 * <p>
 * Created by pedro on 25/01/17.
 */

public class RtmpCamera1 extends Camera1Base {

    private SrsFlvMuxer srsFlvMuxer;
    private SrsFlvMuxer srsFlvMuxer1;

    public RtmpCamera1(SurfaceView surfaceView, ConnectCheckerRtmp connectChecker) {
        super(surfaceView);
        srsFlvMuxer = new SrsFlvMuxer(connectChecker);
    }

    public RtmpCamera1(TextureView textureView, ConnectCheckerRtmp connectChecker) {
        super(textureView);
        srsFlvMuxer = new SrsFlvMuxer(connectChecker);
    }

    @RequiresApi(api = Build.VERSION_CODES.JELLY_BEAN_MR2)
    public RtmpCamera1(OpenGlView openGlView, ConnectCheckerRtmp connectChecker1,
                       ConnectCheckerRtmp connectChecker2) {
        super(openGlView);
        srsFlvMuxer = new SrsFlvMuxer(connectChecker1);
      srsFlvMuxer1 = new SrsFlvMuxer(connectChecker2);
    }

    @RequiresApi(api = Build.VERSION_CODES.JELLY_BEAN_MR2)
    public RtmpCamera1(OpenGlView openGlView, ConnectCheckerRtmp connectChecker) {
        super(openGlView);
        srsFlvMuxer = new SrsFlvMuxer(connectChecker);
    }

    @RequiresApi(api = Build.VERSION_CODES.JELLY_BEAN_MR2)
    public RtmpCamera1(LightOpenGlView lightOpenGlView, ConnectCheckerRtmp connectChecker) {
        super(lightOpenGlView);
        srsFlvMuxer = new SrsFlvMuxer(connectChecker);
    }

    @RequiresApi(api = Build.VERSION_CODES.JELLY_BEAN_MR2)
    public RtmpCamera1(Context context, ConnectCheckerRtmp connectChecker) {
        super(context);
        srsFlvMuxer = new SrsFlvMuxer(connectChecker);
    }

    /**
     * H264 profile.
     *
     * @param profileIop Could be ProfileIop.BASELINE or ProfileIop.CONSTRAINED
     */
    public void setProfileIop(byte profileIop) {
        srsFlvMuxer.setProfileIop(profileIop);
    }

    @Override
    public void resizeCache(int newSize) throws RuntimeException {
        srsFlvMuxer.resizeFlvTagCache(newSize);
        srsFlvMuxer1.resizeFlvTagCache(newSize);
    }

    @Override
    public int getCacheSize() {
        return srsFlvMuxer.getFlvTagCacheSize();
    }

    @Override
    public long getSentAudioFrames() {
        return srsFlvMuxer.getSentAudioFrames();
    }

    @Override
    public long getSentVideoFrames() {
        return srsFlvMuxer.getSentVideoFrames();
    }

    @Override
    public long getDroppedAudioFrames() {
        return srsFlvMuxer.getDroppedAudioFrames();
    }

    @Override
    public long getDroppedVideoFrames() {
        return srsFlvMuxer.getDroppedVideoFrames();
    }

    @Override
    public void resetSentAudioFrames() {
        srsFlvMuxer.resetSentAudioFrames();
    }

    @Override
    public void resetSentVideoFrames() {
        srsFlvMuxer.resetSentVideoFrames();
    }

    @Override
    public void resetDroppedAudioFrames() {
        srsFlvMuxer.resetDroppedAudioFrames();
    }

    @Override
    public void resetDroppedVideoFrames() {
        srsFlvMuxer.resetDroppedVideoFrames();
    }

    @Override
    public void setAuthorization(String user, String password) {
        srsFlvMuxer.setAuthorization(user, password);
    }

    /**
     * Some Livestream hosts use Akamai auth that requires RTMP packets to be sent with increasing
     * timestamp order regardless of packet type.
     * Necessary with Servers like Dacast.
     * More info here:
     * https://learn.akamai.com/en-us/webhelp/media-services-live/media-services-live-encoder-compatibility-testing-and-qualification-guide-v4.0/GUID-F941C88B-9128-4BF4-A81B-C2E5CFD35BBF.html
     */
    public void forceAkamaiTs(boolean enabled) {
        srsFlvMuxer.forceAkamaiTs(enabled);
    }

    @Override
    protected void prepareAudioRtp(boolean isStereo, int sampleRate) {
        srsFlvMuxer.setIsStereo(isStereo);
        srsFlvMuxer1.setIsStereo(isStereo);
        srsFlvMuxer.setSampleRate(sampleRate);
        srsFlvMuxer1.setSampleRate(sampleRate);
    }

  @Override
    protected void startStreamRtp(String url) {
      if(!isStreaming()){
        if (videoEncoder.getRotation() == 90 || videoEncoder.getRotation() == 270) {
          srsFlvMuxer.setVideoResolution(videoEncoder.getHeight(), videoEncoder.getWidth());
        } else {
          srsFlvMuxer.setVideoResolution(videoEncoder.getWidth(), videoEncoder.getHeight());
        }
        srsFlvMuxer.start(url);
      }else{
        if (videoEncoder.getRotation() == 90 || videoEncoder.getRotation() == 270) {
          srsFlvMuxer1.setVideoResolution(videoEncoder.getHeight(), videoEncoder.getWidth());
        } else {
          srsFlvMuxer1.setVideoResolution(videoEncoder.getWidth(), videoEncoder.getHeight());
        }
        srsFlvMuxer1.start(url);
      }

    }

    @Override
    protected void stopStreamRtp() {
        srsFlvMuxer.stop();
    }

    @Override
    public void setReTries(int reTries) {
        srsFlvMuxer.setReTries(reTries);
    }

    @Override
    public boolean shouldRetry(String reason) {
        return srsFlvMuxer.shouldRetry(reason);
    }

    @Override
    public void reConnect(long delay) {
        srsFlvMuxer.reConnect(delay);
    }

    @Override
    public boolean hasCongestion() {
        return srsFlvMuxer.hasCongestion();
    }

    @Override
    protected void getAacDataRtp(ByteBuffer aacBuffer, MediaCodec.BufferInfo info) {
        srsFlvMuxer.sendAudio(aacBuffer, info);
        srsFlvMuxer1.sendAudio(aacBuffer, info);
    }

    @Override
    protected void onSpsPpsVpsRtp(ByteBuffer sps, ByteBuffer pps, ByteBuffer vps) {
        srsFlvMuxer.setSpsPPs(sps, pps);
        srsFlvMuxer1.setSpsPPs(sps, pps);
    }

    @Override
    protected void getH264DataRtp(ByteBuffer h264Buffer, MediaCodec.BufferInfo info) {
        srsFlvMuxer.sendVideo(h264Buffer, info);
        srsFlvMuxer1.sendVideo(h264Buffer, info);
    }

    @Override
    public void setLogs(boolean enable) {
        srsFlvMuxer.setLogs(enable);
        srsFlvMuxer1.setLogs(enable);
    }
}`
How can I stream with multiple urls?

**Comment by pedroSG94** [comment]
All seems fine but you need duplicate buffer before send it to srsflvmuxer to avoid fails. Example:
```java
    srsFlvMuxer.sendVideo(h264Buffer.duplicate(), info);
```
This is necessary in getAacDataRtp, onSpsPpsVpsRtp and getH264DataRtp

**Comment by chauvansang1997** [comment]
When start two srsFlvMuxer the same time, it's ok. But when I start srsFlvMuxer1 after srsFlvMuxer has been started for a while. A broken pipe exception throws. Can you explain it for me?
