### ISSUE TITLE
aspectRatioMode and keepAspectRatio attributes are not available 

### ISSUE THREAD

**Issue by vitalmon** [pedroSG94/rtmp-rtsp-stream-client-java#797]
Hi @pedroSG94 
I try to make the video preview not stretched. I use OpenGlView. But now the video after starting preview is stretched. I've found your suggestion to use aspectRatioMode and keepAspectRatio attributes to fix that. But as I understood they aren't available if minSdkVersion > 18. Mine is 23.
So here is the question how to make my video haven't been stretched on the preview?
Thanks

**Comment by pedroSG94** [comment]
You need sdk 18+ so you can use it (OpenGlView need 18+). Sample:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/res/layout/activity_open_gl.xml#L8

**Comment by vitalmon** [comment]
Thanks. I used the old version. Now it's fine
