### ISSUE TITLE
Image is distorted when live stream on facebook or youtube

### ISSUE THREAD

**Issue by chauvansang1997** [pedroSG94/rtmp-rtsp-stream-client-java#798]
I find out [youtube resolution recommend](https://support.google.com/youtube/answer/2853702#zippy=%2Cvariable-bitrate-with-custom-stream-keys-in-live-control-room%2Ck-p-fps). But phone resolution is reversed. How can I fix it?. Thank you.

**Comment by pedroSG94** [comment]
You should stream in landscape instead of portrait mode to use recommended resolution of youtube
