### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by KunNiu** [pedroSG94/rtmp-rtsp-stream-client-java#799]
I'm using your library to push RTMPS stream to [AWS IVS service](https://aws.amazon.com/cn/blogs/media/setting-up-for-streaming-with-amazon-ivs/),  most time it works well, thank you very much!
But sometimes, I got a NullPointerException. This is not a must happen issue, details please see the crash log:
`    java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes(java.lang.String)' on a null object reference
        at com.github.faucamp.simplertmp.amf.AmfString.writeTo(AmfString.java:59)
        at com.github.faucamp.simplertmp.amf.AmfObject.writeTo(AmfObject.java:58)
        at com.github.faucamp.simplertmp.packets.VariableBodyRtmpPacket.writeVariableData(VariableBodyRtmpPacket.java:71)
        at com.github.faucamp.simplertmp.packets.Command.writeBody(Command.java:83)
        at com.github.faucamp.simplertmp.packets.RtmpPacket.writeTo(RtmpPacket.java:36)
        at com.github.faucamp.simplertmp.io.RtmpConnection.sendRtmpPacket(RtmpConnection.java:511)
        at com.github.faucamp.simplertmp.io.RtmpConnection.sendConnect(RtmpConnection.java:235)
        at com.github.faucamp.simplertmp.io.RtmpConnection.rtmpConnect(RtmpConnection.java:200)
        at com.github.faucamp.simplertmp.io.RtmpConnection.connect(RtmpConnection.java:168)
        at com.github.faucamp.simplertmp.DefaultRtmpPublisher.connect(DefaultRtmpPublisher.java:21)
        at net.ossrs.rtmp.SrsFlvMuxer.connect(SrsFlvMuxer.java:243)
        at net.ossrs.rtmp.SrsFlvMuxer.access$100(SrsFlvMuxer.java:53)
        at net.ossrs.rtmp.SrsFlvMuxer$2.run(SrsFlvMuxer.java:285)
        at java.lang.Thread.run(Thread.java:923)
`
Thanks again!

**Comment by pedroSG94** [comment]
Can you share a full logcat to know when this error is produced?

**Comment by KunNiu** [comment]
@pedroSG94 , this issue always happened when **onConnectionFailedRtmp** invoked, and need to retry.
`
9103-07 23:38:05.110 25556  7636 I SrsFlvMuxer: frame discarded
--
9203-07 23:38:05.111 25556  7636 I SrsFlvMuxer: frame discarded
9303-07 23:38:05.130 25556  7632 I SrsFlvMuxer: frame discarded
9403-07 23:38:05.153 25556  6698 D RtmpConnection: connect(): socket connection established, doing handhake...
9503-07 23:38:05.153 25556  6698 D Handshake: writeC0
9603-07 23:38:05.153 25556  6698 D Handshake: writeC1
9703-07 23:38:05.153 25556  6698 D Handshake: writeC1(): Calculating digest offset
9803-07 23:38:05.154 25556  6698 D Handshake: writeC1(): (real value of) digestOffset: 559
9903-07 23:38:05.154 25556  6698 D Handshake: writeC1(): recalculated digestOffset: 1335
10003-07 23:38:05.154 25556  6698 D Handshake: writeC1(): digestOffsetBytes: 0031FFFF
10103-07 23:38:05.154 25556  6698 D Handshake: partBeforeDigest(): size: 1335
10203-07 23:38:05.154 25556  6698 D Handshake: writeC1(): Writing timestamp and Flash Player version
10303-07 23:38:05.154 25556  6698 D Handshake: partAfterDigest(): size: 169
10403-07 23:38:05.154 25556  6698 D Handshake: copying digest offset bytes in partBeforeDigest
10503-07 23:38:05.154 25556  6698 D Handshake: writeC1(): Calculating digest
10603-07 23:38:05.155 25556  6698 D Handshake: writeC1(): writing C1 packet
10703-07 23:38:05.155 25556  6698 D Handshake: readS0
10803-07 23:38:05.163 25556  7632 I SrsFlvMuxer: frame discarded
10903-07 23:38:05.190 25556  7636 I SrsFlvMuxer: frame discarded
14303-07 23:38:05.728 25556  7632 I SrsFlvMuxer: frame discarded
14403-07 23:38:05.751 25556  7636 I SrsFlvMuxer: frame discarded
14503-07 23:38:05.752 25556  7636 I SrsFlvMuxer: frame discarded
14603-07 23:38:05.761 25556  7632 I SrsFlvMuxer: frame discarded
14703-07 23:38:05.765 25556  6698 D Handshake: readS1
14803-07 23:38:05.791 25556  7632 I SrsFlvMuxer: frame discarded
21403-07 23:38:06.871 25556  7636 I SrsFlvMuxer: frame discarded
21503-07 23:38:06.872 25556  7636 I SrsFlvMuxer: frame discarded
21603-07 23:38:06.890 25556  6698 D Handshake: readS1(): S1 total bytes read OK
21703-07 23:38:06.890 25556  6698 D Handshake: writeC2
21803-07 23:38:06.891 25556  6698 D Handshake: readS2
21903-07 23:38:06.891 25556  6698 D Handshake: readS2(): S2 total bytes read OK
22003-07 23:38:06.891 25556  6698 D RtmpConnection: connect(): handshake done
22103-07 23:38:06.892 25556  6698 D RtmpConnection: rtmpConnect(): Building 'connect' invoke packet
22203-07 23:38:06.893 25556  7931 D RtmpConnection: starting main rx handler loop
22303-07 23:38:06.894 25556  7632 I SrsFlvMuxer: frame discarded
224--------- beginning of crash
22503-07 23:38:06.895 25556  6698 E AndroidRuntime: FATAL EXCEPTION: Thread-54
22603-07 23:38:06.895 25556  6698 E AndroidRuntime: Process: com.sktlab.android.veeko, PID: 25556
22703-07  23:38:06.895 25556  6698 E AndroidRuntime:  java.lang.NullPointerException: Attempt to invoke virtual method 'byte[]  java.lang.String.getBytes(java.lang.String)' on a null object reference
22803-07 23:38:06.895 25556  6698 E AndroidRuntime: 	at com.github.faucamp.simplertmp.amf.AmfString.writeTo(AmfString.java:59)
22903-07 23:38:06.895 25556  6698 E AndroidRuntime: 	at com.github.faucamp.simplertmp.amf.AmfObject.writeTo(AmfObject.java:58)
23003-07  23:38:06.895 25556  6698 E AndroidRuntime: 	at  com.github.faucamp.simplertmp.packets.VariableBodyRtmpPacket.writeVariableData(VariableBodyRtmpPacket.java:71)
23103-07 23:38:06.895 25556  6698 E AndroidRuntime: 	at com.github.faucamp.simplertmp.packets.Command.writeBody(Command.java:83)
23203-07  23:38:06.895 25556  6698 E AndroidRuntime: 	at  com.github.faucamp.simplertmp.packets.RtmpPacket.writeTo(RtmpPacket.java:36)
23303-07  23:38:06.895 25556  6698 E AndroidRuntime: 	at  com.github.faucamp.simplertmp.io.RtmpConnection.sendRtmpPacket(RtmpConnection.java:511)
23403-07  23:38:06.895 25556  6698 E AndroidRuntime: 	at  com.github.faucamp.simplertmp.io.RtmpConnection.sendConnect(RtmpConnection.java:235)
23503-07  23:38:06.895 25556  6698 E AndroidRuntime: 	at  com.github.faucamp.simplertmp.io.RtmpConnection.rtmpConnect(RtmpConnection.java:200)
23603-07  23:38:06.895 25556  6698 E AndroidRuntime: 	at  com.github.faucamp.simplertmp.io.RtmpConnection.connect(RtmpConnection.java:168)
23703-07  23:38:06.895 25556  6698 E AndroidRuntime: 	at  com.github.faucamp.simplertmp.DefaultRtmpPublisher.connect(DefaultRtmpPublisher.java:21)
23803-07 23:38:06.895 25556  6698 E AndroidRuntime: 	at net.ossrs.rtmp.SrsFlvMuxer.connect(SrsFlvMuxer.java:243)
23903-07 23:38:06.895 25556  6698 E AndroidRuntime: 	at net.ossrs.rtmp.SrsFlvMuxer.access$100(SrsFlvMuxer.java:53)
24003-07 23:38:06.895 25556  6698 E AndroidRuntime: 	at net.ossrs.rtmp.SrsFlvMuxer$2.run(SrsFlvMuxer.java:285)
24103-07 23:38:06.895 25556  6698 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
24203-07 23:38:06.896 25556  6698 E CrashReport: Java Crash Happen cause by Thread-54(79031)
24303-07 23:38:06.930 25556  7632 I SrsFlvMuxer: frame discarded
24403-07 23:38:06.949 25556  7636 I SrsFlvMuxer: frame discarded
26603-07 23:38:07.269 25556  7636 I SrsFlvMuxer: frame discarded
26703-07 23:38:07.291 25556  7632 I SrsFlvMuxer: frame discarded
26803-07 23:38:07.324 25556  7632 I SrsFlvMuxer: frame discarded
26903-07 23:38:07.349 25556  7636 I SrsFlvMuxer: frame discarded
27003-07 23:38:07.349 25556  7636 I SrsFlvMuxer: frame discarded
27103-07 23:38:07.359 25556  7632 I SrsFlvMuxer: frame discarded
27203-07 23:38:07.389 25556  7632 I SrsFlvMuxer: frame discarded
27303-07 23:38:07.425 25556  7632 I SrsFlvMuxer: frame discarded
27403-07 23:38:07.428 25556  7636 I SrsFlvMuxer: frame discarded
27503-07 23:38:07.429 25556  7636 I SrsFlvMuxer: frame discarded
27603-07 23:38:07.430 25556  7636 I SrsFlvMuxer: frame discarded
27703-07 23:38:07.460 25556  7632 I SrsFlvMuxer: frame discarded
27803-07 23:38:07.491 25556  7632 I SrsFlvMuxer: frame discarded
27903-07 23:38:07.505 25556  7640 D RtmpConnection: connect(): socket connection established, doing handhake...
28003-07 23:38:07.505 25556  7640 D Handshake: writeC0
28103-07 23:38:07.505 25556  7640 D Handshake: writeC1
28203-07 23:38:07.506 25556  7640 D Handshake: writeC1(): Calculating digest offset
28303-07 23:38:07.506 25556  7640 D Handshake: writeC1(): (real value of) digestOffset: 144
28403-07 23:38:07.506 25556  7640 D Handshake: writeC1(): recalculated digestOffset: 920
28503-07 23:38:07.506 25556  7640 D Handshake: writeC1(): digestOffsetBytes: 00000090
28603-07 23:38:07.506 25556  7640 D Handshake: partBeforeDigest(): size: 920
28703-07 23:38:07.506 25556  7640 D Handshake: writeC1(): Writing timestamp and Flash Player version
28803-07 23:38:07.506 25556  7640 D Handshake: partAfterDigest(): size: 584
28903-07 23:38:07.506 25556  7640 D Handshake: copying digest offset bytes in partBeforeDigest
29003-07 23:38:07.506 25556  7640 D Handshake: writeC1(): Calculating digest
29103-07 23:38:07.506 25556  7640 D Handshake: writeC1(): writing C1 packet
29203-07 23:38:07.506 25556  7640 D Handshake: readS0
29303-07 23:38:07.509 25556  7636 I SrsFlvMuxer: frame discarded
29403-07 23:38:07.510 25556  7636 I SrsFlvMuxer: frame discarded
29503-07 23:38:07.522 25556  7632 I SrsFlvMuxer: frame discarded
29603-07 23:38:07.561 25556  7632 I SrsFlvMuxer: frame discarded
29703-07 23:38:07.588 25556  7636 I SrsFlvMuxer: frame discarded
29803-07 23:38:07.589 25556  7636 I SrsFlvMuxer: frame discarded
29903-07 23:38:07.589 25556  7636 I SrsFlvMuxer: frame discarded
30003-07 23:38:07.590 25556  7632 I SrsFlvMuxer: frame discarded

`

**Comment by pedroSG94** [comment]
I see. Aparently when you do a retry AWS server send response to connect packet with an unexpected body.
Is possible to provide me an endpoint to AWS server to test it? You can send me info by email to keep it private:
pedrossgg1994@gmail.com
If you can't. A full connection packet info using wireshark could be useful to detect the different beetween normal connection and retry connection.

**Comment by KunNiu** [comment]
@pedroSG94 , sent the endpoint to you via email, thanks!

**Comment by pedroSG94** [comment]
Thank you, I'm trying to reproduce it.

**Comment by pedroSG94** [comment]
I did around 100 test but I can't reproduce it. Basically I'm opening default example, connect to endpoint, disable wifi and enable wifi to simulate a retry by internet lost.
Do you have any tips to reproduce it?
Is it a rare error and this is difficult to reproduce?

**Comment by KunNiu** [comment]
@pedroSG94 , from my side, it's a low rate error, but not rare. I think it may caused by the special network environment in China. And this issue always happens during connecting with multi-times retry. For example, connecting -> retry -> retry -> retry -> occur.

**Comment by KunNiu** [comment]
@pedroSG94 , I tested by disable wifi and enable wifi, crashed again, but not NullPointerException this time, I attach the log here, could you please take a look? Thanks!
[crash.log](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/6172348/crash.log)

**Comment by KunNiu** [comment]
And I found every time, if appear connect failed reason **Error configure stream, publish permitted failed**, after several times re-connect, crash will happen.

**Comment by pedroSG94** [comment]
This error right?:
```
java.lang.IllegalArgumentException: Unknown message type byte: A5
        at com.github.faucamp.simplertmp.packets.RtmpHeader$MessageType.valueOf(RtmpHeader.java:149)
        at com.github.faucamp.simplertmp.packets.RtmpHeader.readHeaderImpl(RtmpHeader.java:234)
```
I can't reproduce it. I don't know how are you doing to produce this crash. Are you using the same endpoint that you shared me?
Also before this crash you receive this multiple times:
```
E/RtmpConnection: Error
    java.io.IOException: Invalid RTMP protocol version; expected 3, got 2
```
This error is produced in handshake because you received a bad response for S0. This could cause the problem reading packets in the future and produce that crash.
Also handshake is called multiple times without wait for the rest of connection packets before that error with handshake is produced.
I'm not sure how to reproduce it. Can you show me your retry code?
Are you able to reproduce this error in my app example?

**Comment by KunNiu** [comment]
@pedroSG94 , this issue is not a must happen issue, and I think it's may related to network environment. I also cannot reproduce it recent days. I will try to capture more logs in the future, if it happen again.

**Comment by pedroSG94** [comment]
Hello,

I think that I found the reason about this error and I fixed it here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/a049b6f167cd3008a7e059dbecc1ba160b5405da#diff-bf2708a3b0cf12a3553fe9bea6287e7a2717379f051b139b9d8f66c5087169abL225
swfUrl or pageUrl could be null but the value is always "" so I replaced variable by value in order to avoid npe.
Please, update library and report me if you have any problem in the future with this error.

**Comment by KunNiu** [comment]
@pedroSG94 it's very appreciate!
