### ISSUE TITLE
Unable to stop stream

### ISSUE THREAD

**Issue by avinash7074** [pedroSG94/rtmp-rtsp-stream-client-java#8]
Hi,

Thanks for such a great library.

When I am trying to stop the stream its not able to stop the stream when I have integrated the project through gradle.
But when I have try with downloaded code it working great.

Thank you.

**Comment by pedroSG94** [comment]
Can you give me more info?
Log crash, rtmp or rtsp, code used.

**Comment by avinash7074** [comment]
Thanks for the reply, its not giving any error I am just not able to stop the stream.
I think the stopStream() function is not updated in gradle build ?

So can you help me out in that.

Thank you.

**Comment by avinash7074** [comment]
I have download the project and integrated the library into my project then I am able to stop the Stream but when I have integrated through dependencies then its not able to stop the stream.

And I am also not able to change the orientation of video i have  tried will all orientation also.

Thank you

![image](https://cloud.githubusercontent.com/assets/28567882/25857947/24ee8dd0-34f8-11e7-810f-25a18315403e.png)

**Comment by pedroSG94** [comment]
I will check gradle build. Rotation in somes devices dont work because mediacodec rotation is not enable or is bugged. In that case you can rotate image manually with YUVUtil class in CameraApi1Manager class. You can see a example in this issue (last response):
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/2

**Comment by pedroSG94** [comment]
Stop in gradle checked and working. Rotation by software added (should work in all devices). 
If you need more help open other issue, thank for report.
