### ISSUE TITLE
RTMPS (RTMP over TLS)

### ISSUE THREAD

**Issue by giusboi** [pedroSG94/rtmp-rtsp-stream-client-java#80]
Hi Pedro! Thanks a lot for your awesome work, I'm using your library and it works like a charm.

Now I need to move the RTMP protocol over TLS. I found that you've the CreateSSLSocket class inside the net.ossrs.rtmp package, but it seems that you never use the createSSlSocket method to create an ssl socket. Have you ever tested it? Do you think it could be difficult to include SSL Socket support?

Best regards,
Giuseppe

**Comment by pedroSG94** [comment]
No, I never tested because I haven't a server configured with ssl connection.
If you know some server and a tutorial to configure secure connection I can try test and implement it.
I think, I only need change my default socket to a ssl socket but I never use ssl socket with the java api and I don't want add socketio dependency.

**Comment by giusboi** [comment]
Hi Pedro, we are using a normal RTMP server with a ssl tcp proxy (https://www.stunnel.org/index.html). In this way we can have TLS over non-secure RTMP server.
Here the guide we use: https://www.digitalocean.com/community/tutorials/how-to-set-up-an-ssl-tunnel-using-stunnel-on-ubuntu
You will need a public ip address with a valid SSL certificate from a certification authority.

I think that it could be simple to replace the java Socket with a SSL Socket. I'm trying to do it, and I will tell you if it works and what I've done.

Thanks a lot,
Giuseppe

**Comment by giusboi** [comment]
Ok, I did add TLS. It seems stable. I just changed a few lines of code. If you want I can share the code.

**Comment by pedroSG94** [comment]
Yes please. It will be a good feature

**Comment by giusboi** [comment]
I created a pull request. Thanks for all your work Pedro.

**Comment by pedroSG94** [comment]
Thank you. I will add this to rtsp too.

**Comment by pedroSG94** [comment]
Added to rtsp: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/994830bd54dc08c63d85fd52147e3591ccaaa5e0
I tested rtmps on facebook and work fine :). Thanks for the feature. 
Issue closed.
