### ISSUE TITLE
sps or pps is null

### ISSUE THREAD

**Issue by mlph-sreyes** [pedroSG94/rtmp-rtsp-stream-client-java#800]
Hi, 

I am new in RTSP/RTMP streaming development, apologies if the question is a bit stupid. I have set up a basic streaming server using [this code]( https://github.com/aler9/rtsp-simple-server#standard). I am able to run the server, however when I try to connect via CustomRTPS or DefaultRTSP it always shows the error `sps or pps is null`. But when I traced the code I tried to add a breakpoint on every piece of code that is the entry point on writing data in `sps `and `pps `but the code does not pass through.

May I know what is the SPS and PPS and if I am doing something wrong?

**Comment by pedroSG94** [comment]
Your encoder is not generating an sps and pps necessary to stream.
Can you confirm me that rtmp is working to discard device problems?
Did you check with other device?
