### ISSUE TITLE
RtpService.kt and setting protocol

### ISSUE THREAD

**Issue by moster67** [pedroSG94/rtmp-rtsp-stream-client-java#802]
Sorry, another question.
In the Background example, I am wondering how to set the Protocol for Tcp or Udp?
I noted that Camera2Base does not seem to expose the setProtocol method. It seems to be present in RtspCamera2 but I cannot access it.
Probably my lack of OOP skills shining through and my poor knowledge of Kotlin although I learned what a Companion Object is :-)
Thanks.

**Comment by pedroSG94** [comment]
This is for inheritance reasons. You can use this:
```java
if (camera2Base is RtspCamera2) { 
          (camera2Base as RtspCamera2).setProtocol(Protocol.TCP)
}
```

**Comment by moster67** [comment]
Thank you - now I learned something new in Kotlin. 
I really need to start working with Kotlin more...
