### ISSUE TITLE
Background (Service) and streaming filters

### ISSUE THREAD

**Issue by moster67** [pedroSG94/rtmp-rtsp-stream-client-java#803]
I adapted your background Rtsp example so I can use also filters while streaming.

While the cameraview is visible on the screen, the filters (in this case text) can be seen also on the rtsp-server (using VLC).
However, if I go to home screen on the phone or turn off the screen, the stream continues just fine but the filter disappears. However, as soon as I open the app/activity again, the filter re-appears in the stream.

Is it possible to continue streaming the filters even if the activity is no longer in focus/visible?

Thank you.

**Comment by pedroSG94** [comment]
The filters are released when you change glinterface because all opengl resources are linked to openglview or offscreenglthread. For now, I recommend you save all filters in a list with all configurations and set all after change glinterface

**Comment by moster67** [comment]
Thank you for your hints. 
I will try this out.
