### ISSUE TITLE
(Question) Take Photo | OpenGL RTMP

### ISSUE THREAD

**Issue by rashid56156** [pedroSG94/rtmp-rtsp-stream-client-java#805]
Hello Pedro,

I am Streaming to youtube using OpenGl RTMP and setting dynamic location data to stream as text. This is working fine.

Now I have to take still images of the stream so I am using onPreviewFrame(byte[] data, Camera camera) from Camera1ApiManager to get frames and convert them to Bitmap as you suggested to someone.

I want the location text to be visible on the frame that I convert to bitmap but currently, the text is visible on preview as well as on stream but not on images.

I was wondering maybe you can guide me on how to solve this problem.

Thanks in advance, appreciate your efforts.

**Comment by pedroSG94** [comment]
Hello,

If you are using onPreviewFrame to take photo you can't capture filter because you get frames before apply filters. If you are using OpenGlView I recommend you use takePhoto from glInterface instead of use onPreviewFrame.
```java
rtmpCamera1.getGlInterface().takePhoto(new TakePhotoCallback() {
          @Override
          public void onTakePhoto(Bitmap bitmap) {
            
          }
        });
```

**Comment by rashid56156** [comment]
Hello,

Thanks for the quick response.

That was the first thing i tried but the method you mentioned simply returns a black/blank bitmap. 

Tried it on Emulator as well as my physical device but no luck.

Though i got another idea, i can get the bitmap from onPreviewFrame and then write text on it using Paint and Canvas combo.

**Comment by pedroSG94** [comment]
It that case it is a bug. I will check it
