### ISSUE TITLE
Hide and show image filters

### ISSUE THREAD

**Issue by abadoliverco** [pedroSG94/rtmp-rtsp-stream-client-java#807]
Hi,

I just want to ask if there's a way to toggle the image filter like hiding and showing? my plan is to create a privacy mode while streaming.

Thank you!

**Comment by pedroSG94** [comment]
You can use alpha to hide and show image filters:
```java
imageObjectFilterRender.setAlpha(0.0f); // hide
imageObjectFilterRender.setAlpha(1.0f); // show
```
You can do it after set filter in any moment.

**Comment by abadoliverco** [comment]
Hi,

i tried these

glInterface?.muteVideo()
glInterface?.unmuteVideo()

and its working

thank you!
