### ISSUE TITLE
Test with two pcs

### ISSUE THREAD

**Issue by mariohectem** [pedroSG94/rtmp-rtsp-stream-client-java#809]
Thanks so much for your atention, I realized a test as follows:
1 Phone and two pcs: A and B.
Pc A with nginx and rtmp module. Pc A and Pc B with ffmpeg (for test with ffplay).
Streaming from phone to Pc A, all right can see video with ffplay (in the same pc).
But Pc B not get the video of PC A (while streaming from phone to Pc A) with ffplay (or browser) only audio.

ffplay log:
 non-existing PPS 0 referenced
[h264 @ 0xac2f14c0] decode_slice_header error
[h264 @ 0xac2f14c0] no frame!
[h264 @ 0x8710bc80] non-existing PPS 0 referenced
[h264 @ 0x8710bc80] decode_slice_header error

**Comment by pedroSG94** [comment]
This is really weird. I think that this is a server configuration error.
Can you see stream if you use other way to stream to PC? (for example, use ffmpeg to stream from PC B to PC A and reproduce stream in phone).
Also, we can discard a keyframe problem: 
In prepareVideo set iFrameInterval to 0

**Comment by mariohectem** [comment]
Ok, thank so much.
I test with ffmpeg and another pc and its ok.
Maybe set iFrameInterval to 0 as you say.
Thanks.
