### ISSUE TITLE
Processing Frames While streaming

### ISSUE THREAD

**Issue by TareqAlbeeshFMS** [pedroSG94/rtmp-rtsp-stream-client-java#810]
is it possible to process frames in real time while streaming them using camera2?

**Comment by pedroSG94** [comment]
What do you mean with proccess?
If you want get bitmap you can use:
```java
rtmpCamera1.getGlInterface().takePhoto(new TakePhotoCallback() {
      @Override
      public void onTakePhoto(Bitmap bitmap) {
        
      }
    });
```
If you want capture continously frames from camera2 you can set a surface of an ImageReader in Camera2ApiManager class.

**Comment by TareqAlbeeshFMS** [comment]
I want to get each frame in real time, in Camera2 API I used to that using ImageReader with onImageAvailableListener, I want to get the frames from the camera while streaming them

**Comment by TareqAlbeeshFMS** [comment]
What I meant is to get each frame from the camera, process it or manipulate it, then send it to the server(stream it), 
but currently adding ImageReader to Camera2ApiManager  would work for me.

**Comment by pedroSG94** [comment]
If you want sent it to server. I recommend you create your own filter:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Real-time-filters

**Comment by TareqAlbeeshFMS** [comment]
Can I do Machine learning processing using filters?
I wan for example to detect faces in the images and mark them while streaming.

**Comment by pedroSG94** [comment]
Machine learning on fly normally is not possible because all api need generate a bitmap and proccess it on each frame with 30fps is impossible in a phone.
Face detection is developed and working with camera1. Example:
```java
final ImageObjectFilterRender imageObjectFilterRender = new ImageObjectFilterRender();
    rtmpCamera1.getGlInterface().setFilter(imageObjectFilterRender);
    imageObjectFilterRender.setImage(BitmapFactory.decodeResource(getResources(), R.mipmap.ic_launcher));
    imageObjectFilterRender.setDefaultScale(rtmpCamera1.getStreamWidth(),
        rtmpCamera1.getStreamHeight());
    final FaceDetectorUtil parser = new FaceDetectorUtil();
    rtmpCamera1.enableFaceDetection(new Camera1ApiManager.FaceDetectorCallback() {
      @Override
      public void onGetFaces(Camera.Face[] faces) {
        if (faces.length > 0) {
          FaceDetectorUtil.FaceParsed faceParsed = parser.camera1Parse(faces[0], openGlView, imageObjectFilterRender.getScale(),
              CameraHelper.getCameraOrientation(getApplicationContext()), rtmpCamera1.isFrontCamera());
          imageObjectFilterRender.setScale(faceParsed.getScale().x, faceParsed.getScale().y);
          imageObjectFilterRender.setPosition(faceParsed.getPosition().x, faceParsed.getPosition().y);
        }
      }
    });
```
