### ISSUE TITLE
(Question) How to get current bytes sent in one second and totalBytesOut send so far?

### ISSUE THREAD

**Issue by alicja99** [pedroSG94/rtmp-rtsp-stream-client-java#814]

**Comment by pedroSG94** [comment]
You can get bits in one second using this callback:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/defaultexample/ExampleRtmpActivity.java#L89
To get total use a variable to sum all values provided in that callback.
Remeber that if you want the value in bytes you can symple divide by 8
