### ISSUE TITLE
Real time filters Thread Limit

### ISSUE THREAD

**Issue by mustafaboleken** [pedroSG94/rtmp-rtsp-stream-client-java#818]
Hi, I wanted to add last 5 messages on stream. 
I add "ManagerRender.numFilters = 8" before creating rtmpCamera1

When I add more then 3 filters, I get Fatal exception in GLThread: IndexOutOfBoundsException

Is there any way to increse OpenGL thread more than 3?

**Comment by pedroSG94** [comment]
It is working for me. It has no limit
Are you using a openglview? In that case, did you test using xml param?
Can you share a code example that produce that crash?

**Comment by mustafaboleken** [comment]
> It is working for me. It has no limit
> Are you using a openglview? In that case, did you test using xml param?
> Can you share a code example that produce that crash?

Today I test it on the real device and everything is fine. I think the problem is in the emulator. Thanks for the reply.
