### ISSUE TITLE
Reconnect / restart stream problems

### ISSUE THREAD

**Issue by chauvansang1997** [pedroSG94/rtmp-rtsp-stream-client-java#820]
When connect to server I turn wifi and it auto reconnect but package send only Audio. This is my rtmp code:
`public class MultipleRtmpCamera1 extends Camera1Base {
    private Map<String, SrsFlvMuxer> mapStream;
    private List<SrsFlvMuxer> srsFlvMuxers;
    private Activity activity;
    private long disconnectTime;

    public MultipleRtmpCamera1(SurfaceView surfaceView, ConnectCheckerRtmp connectChecker, Activity activity) {
        super(surfaceView);
        srsFlvMuxers = new ArrayList();
        mapStream = new HashMap<String, SrsFlvMuxer>();
        this.activity = activity;
    }

    public MultipleRtmpCamera1(TextureView textureView, ConnectCheckerRtmp connectChecker, Activity activity) {
        super(textureView);
        srsFlvMuxers = new ArrayList();
        mapStream = new HashMap<String, SrsFlvMuxer>();
        this.activity = activity;
    }

    @RequiresApi(api = Build.VERSION_CODES.JELLY_BEAN_MR2)
    public MultipleRtmpCamera1(OpenGlView openGlView, ConnectCheckerRtmp connectChecker, Activity activity) {
        super(openGlView);
        srsFlvMuxers = new ArrayList();
        mapStream = new HashMap<String, SrsFlvMuxer>();
        this.activity = activity;
    }

    @RequiresApi(api = Build.VERSION_CODES.JELLY_BEAN_MR2)
    public MultipleRtmpCamera1(LightOpenGlView lightOpenGlView, ConnectCheckerRtmp connectChecker, Activity activity) {
        super(lightOpenGlView);
        srsFlvMuxers = new ArrayList();
        mapStream = new HashMap<String, SrsFlvMuxer>();
        this.activity = activity;
    }

    @RequiresApi(api = Build.VERSION_CODES.JELLY_BEAN_MR2)
    public MultipleRtmpCamera1(Context context, ConnectCheckerRtmp connectChecker, Activity activity) {
        super(context);
        srsFlvMuxers = new ArrayList();
        mapStream = new HashMap<String, SrsFlvMuxer>();
        this.activity = activity;
    }

    private Boolean start = false;

    public void addUrl(final String url) {
        final SrsFlvMuxer srsFlvMuxer = new SrsFlvMuxer(
                new ConnectCheckerRtmp() {
                    @Override
                    public void onConnectionSuccessRtmp() {
                        if (!start) {
                            boolean check = false;
                            for (int i = 0; i < srsFlvMuxers.size(); i++) {
                                if (!srsFlvMuxers.get(i).isConnected()) {
                                    check = true;
                                    break;
                                }
                            }

                            if (!check) {
                                start = true;
                                startStream("");
                            }
                        }
                    }

                    @Override
                    public void onConnectionFailedRtmp(@NonNull String reason) {
                        activity.runOnUiThread(new Runnable() {

                            @Override
                            public void run() {

                                SrsFlvMuxer srsFlvMuxer = mapStream.get(url);
                                if (srsFlvMuxer != null) {
                                    srsFlvMuxer.reConnect(15000);
                                }

                            }
                        });
                    }

                    @Override
                    public void onNewBitrateRtmp(long bitrate) {

                    }

                    @Override
                    public void onDisconnectRtmp() {

                    }

                    @Override
                    public void onAuthErrorRtmp() {

                    }

                    @Override
                    public void onAuthSuccessRtmp() {

                    }
                }
        );
        if (videoEncoder.getRotation() == 90 || videoEncoder.getRotation() == 270) {
            srsFlvMuxer.setVideoResolution(videoEncoder.getHeight(), videoEncoder.getWidth());
        } else {
            srsFlvMuxer.setVideoResolution(videoEncoder.getWidth(), videoEncoder.getHeight());
        }
        mapStream.put(url, srsFlvMuxer);
        srsFlvMuxers.add(srsFlvMuxer);
    }

    /**
     * H264 profile.
     *
     * @param profileIop Could be ProfileIop.BASELINE or ProfileIop.CONSTRAINED
     */
    public void setProfileIop(byte profileIop) {

    }

    @Override
    public void resizeCache(int newSize) throws RuntimeException {

    }

    @Override
    public int getCacheSize() {
        return 0;
    }

    @Override
    public long getSentAudioFrames() {
        return 0;
    }

    @Override
    public long getSentVideoFrames() {
        return 0;
    }

    @Override
    public long getDroppedAudioFrames() {
        return 0;
    }

    @Override
    public long getDroppedVideoFrames() {
        return 0;
    }

    @Override
    public void resetSentAudioFrames() {

    }

    @Override
    public void resetSentVideoFrames() {

    }

    @Override
    public void resetDroppedAudioFrames() {

    }

    @Override
    public void resetDroppedVideoFrames() {

    }

    @Override
    public void setAuthorization(String user, String password) {

    }

    /**
     * Some Livestream hosts use Akamai auth that requires RTMP packets to be sent with increasing
     * timestamp order regardless of packet type.
     * Necessary with Servers like Dacast.
     * More info here:
     * https://learn.akamai.com/en-us/webhelp/media-services-live/media-services-live-encoder-compatibility-testing-and-qualification-guide-v4.0/GUID-F941C88B-9128-4BF4-A81B-C2E5CFD35BBF.html
     */
    public void forceAkamaiTs(boolean enabled) {

    }

    @Override
    protected void prepareAudioRtp(boolean isStereo, int sampleRate) {

    }

    @Override
    protected void startStreamRtp(String url) {

    }

    public void startStreamRtp() throws InterruptedException {
        for (Map.Entry<String, SrsFlvMuxer> set : mapStream.entrySet()) {
            set.getValue().start(set.getKey());
        }

    }

    @Override
    protected void stopStreamRtp() {

    }

    @Override
    public void setReTries(int reTries) {

    }

    @Override
    public boolean shouldRetry(String reason) {
        return true;
    }

    @Override
    public void reConnect(long delay) {

    }

    @Override
    public boolean hasCongestion() {
        return false;
    }

    @Override
    protected void getAacDataRtp(ByteBuffer aacBuffer, MediaCodec.BufferInfo info) {
        for (int i = 0; i < srsFlvMuxers.size(); i++) {
            srsFlvMuxers.get(i).sendAudio(aacBuffer.duplicate(), info);

        }
    }

    @Override
    protected void onSpsPpsVpsRtp(ByteBuffer sps, ByteBuffer pps, ByteBuffer vps) {
        for (int i = 0; i < srsFlvMuxers.size(); i++) {
            srsFlvMuxers.get(i).setSpsPPs(sps.duplicate(), pps.duplicate());
        }
    }

    @Override
    protected void getH264DataRtp(ByteBuffer h264Buffer, MediaCodec.BufferInfo info) {
        for (int i = 0; i < srsFlvMuxers.size(); i++) {
            srsFlvMuxers.get(i).sendVideo(h264Buffer.duplicate(), info);
        }
    }

    @Override
    public void setLogs(boolean enable) {
        for (int i = 0; i < srsFlvMuxers.size(); i++) {
            srsFlvMuxers.get(i).setLogs(enable);
        }
    }
}`

`D/RtmpConnection: wrote packet: RTMP Audio, size: 33
  D/RtmpConnection: wrote packet: RTMP Audio, size: 33
  D/RtmpConnection: wrote packet: RTMP Audio, size: 33`
Do you think video queue is blocked?

**Comment by pedroSG94** [comment]
Did you check if getH264DataRtp is called?
If that method is called maybe you never produce a keyframe and video stream can't start for that reason.
Maybe you need reset videoEncoder to fix it. I'm doing it when on my retry:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L639

**Comment by chauvansang1997** [comment]
I need to stream multiple stream at same video encoder and each srsFlvMuxer will receive data from encoder. How can I do that?

**Comment by pedroSG94** [comment]
Try send sps and pps produced the first time that you init videoEncoded.
- Copy bytebuffers of onSpsPpsVpsRtp callback in a variable.
- After succes reconnection send that buffer to srsFlvMuxer using setSpsPPs.

If this is not working you will need wait to next keyframe to produce video packets.
The only way to do it is reduce iFrameInterval. Try with value to 1 or 0 (1 keyframe each 1 second or all frame are keyframes)

**Comment by chauvansang1997** [comment]
Thank you. It has already sent video. But do we facebook server not receive reset. Do we need change        info.presentationTimeUs to last disconnect time?

**Comment by pedroSG94** [comment]
I'm not sure if Facebook require start stream from timestamp 0 to work.
For now, I recommend you set iframeinterval in preparevideo method to 0 (this mean that all frames are keyframes) and you can discard keyframe problems with Facebook.
If it is not working try change info.presentationTimeUs (remember that you need change both audio and video)

**Comment by chauvansang1997** [comment]
Thank you for your help. I have already resolved problem.
