### ISSUE TITLE
switchCamera while a js webview callback

### ISSUE THREAD

**Issue by Nodalailama** [pedroSG94/rtmp-rtsp-stream-client-java#823]
Hi,

When using a native button, the camera is switching, but when I receive a js callback from a webview, it's enter in the method but it's not switching ...

```
    // Switch camera from a native button
    fun changeCameraClicked(view: View?) {
        rtmpCamera!!.switchCamera()
    }
```

```
    // Switch camera from a button clicked in the webview
    @JavascriptInterface
    fun changeCamera() {
        rtmpCamera!!.switchCamera()
    }
```

I have tested that the js android interface is working fine.

If someone have any idea ... thanks in advance.

**Comment by pedroSG94** [comment]
I don't know about js. 
This seems a problem related with js like it is working using native code. Remember that switchcamera fail if you change to an invalid resolution for the other camera:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/defaultexample/ExampleRtmpActivity.java#L144
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L748

**Comment by Nodalailama** [comment]
Hi,

Yes, that's right, everything works now :) thanks for your work.

Cordialement,
