### ISSUE TITLE
Pausing The Stream

### ISSUE THREAD

**Issue by tareqalbeesh** [pedroSG94/rtmp-rtsp-stream-client-java#826]
How Can I stop the stream and re start it without recreating capture session in Camera2 ?

**Comment by pedroSG94** [comment]
Some servers don't support stop send video or audio so you try this alternative:
```java
//mute video (send only back images)
rtmpCamera2.getGlInterface().muteVideo();
//mute audio (send only silence)
rtmpCamera1.disableAudio();
```
