### ISSUE TITLE
Green Frames with file video sent to RTMPServer

### ISSUE THREAD

**Issue by francescogatto** [pedroSG94/rtmp-rtsp-stream-client-java#827]
Hi,
I'm trying to send a video file via the rtmp channel. 
I'm using your RTMPFile class. It works good with a Samsung Galaxy s8 and Android 9, but with the same video and different device  (Smartglasses) with Android 8 a green screen is sent
What can I change to tune the encoding?

**Comment by pedroSG94** [comment]
Did you tried with opengl and without it to discard opengl problems?
With opengl:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/e7c07474235be1356b49a3544eb938f791f97b8d/rtplibrary/src/main/java/com/pedro/rtplibrary/rtmp/RtmpFromFile.java#L36
Without it:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/e7c07474235be1356b49a3544eb938f791f97b8d/rtplibrary/src/main/java/com/pedro/rtplibrary/rtmp/RtmpFromFile.java#L30

**Comment by francescogatto** [comment]
Hi @pedroSG94 
Thanks for the fast reply! With opengl it works!
