### ISSUE TITLE
Android Api 16 Compatibility

### ISSUE THREAD

**Issue by martinbe1io** [pedroSG94/rtmp-rtsp-stream-client-java#828]
Hi, 

Pedro mentions api16 compatibility but when I try to build it for android 9 (level 28) the following library is missing

```
import android.media.AudioPlaybackCaptureConfiguration;
```

above library seems to be level 29, some other minor issues occur as well - any hint for me? 

thx Martin

**Comment by pedroSG94** [comment]
I just test library with an emulator with api 16 and it is working of course only camera1 with surfaceview as marked in the library by annotations. I don't understand you.
Can you explain it more?

**Comment by martinbe1io** [comment]
It don’t even compiles as the imported library I mentioned is api level 29.

**Comment by pedroSG94** [comment]
Can you compile my app example or you have this problem only in your project?
