### ISSUE TITLE
How to get device resolution?

### ISSUE THREAD

**Issue by AlexUrrutia** [pedroSG94/rtmp-rtsp-stream-client-java#829]
Hello! I am setting the resolution to **1280x720** via RTMP on OpenGL, but **if the device don`t support it**, how can it fallback to the closest resolution? for example: **640x480**, is there a way to achieve this?
Thanks

**Comment by pedroSG94** [comment]
You can get a list of supported resolutions with this methods:
```java
rtmpCamera1.getResolutionsBack();
rtmpCamera1.getResolutionsFront();
```
