### ISSUE TITLE
Recording Videos

### ISSUE THREAD

**Issue by tareqalbeesh** [pedroSG94/rtmp-rtsp-stream-client-java#830]
How to record video while streaming?, I did the camera2Base.startRecord(), but it didn't record IDK why
the mp4 file is being created with size 0 but it's not recording

**Comment by pedroSG94** [comment]
Did you tried with my app example?
Also you can use listener to know record state:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera1Base.java#L343

**Comment by tareqalbeesh** [comment]
I saw the samples but what I am trying to do is recording video in the background from service, is it achievable ?
and I wonder would it be achievable without recreating the camera2 capture session ?

**Comment by pedroSG94** [comment]
Record in background is exactly the same that foreground examples. For that reason I ask you it to confirm that all is working fine.
You only need call startrecord and stoprecord when you want finish (if you don't call stoprecord the result file is unredeable)

**Comment by tareqalbeesh** [comment]
I did the following:
I made a new Activity that binds on the service that does the streaming
when the stream starts in the service I go to the Activity that I created and I call the "StartRecording" method, which is the same as in your samples
when I click the startRecording method the streaming stops and from checking the Device File Explorer I get an empty .mp4 file

**Comment by pedroSG94** [comment]
Use this method to startRecord and show me logcat:
```java
rtmpCamera2.startRecord("path", new RecordController.Listener() {
      @Override
      public void onStatusChange(RecordController.Status status) {
        Log.e("Record log", "record stare: " + status.name());
      }
    });
```

**Comment by tareqalbeesh** [comment]
Sorry, the problem was was related to edits I made to the library.
