### ISSUE TITLE
Streaming on demand

### ISSUE THREAD

**Issue by tareqalbeesh** [pedroSG94/rtmp-rtsp-stream-client-java#833]
I want to do the following:
- I want to have an `ImageReader` working all the time, and at some point I want to start streaming and/or recording video according to some processing I am doing to the frames that I am getting from `ImageReader`'s surface,
is there a way to do this using this library without creating `CaptureSession` multiple times ?

**Comment by pedroSG94** [comment]
I'm not sure what do you mean with "creating capture session multiple times" but you can simple add an imagereader surface to camera2apimagaer in this list:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/1873bae5b7a1744bd4a8b0e93e0f3557a922a343/encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java#L180
With that your surface will be renderer while camera is open (on preview, streaming or recording)

**Comment by tareqalbeesh** [comment]
what I want is to render this surface (the imageReader Surface) all the time. start the stream and close it on demand

**Comment by pedroSG94** [comment]
Yes, that surface is renderer on preview, you don't need start stream to work and you only stop render after call stop preview

**Comment by tareqalbeesh** [comment]
Thanks it worked perfectly fine but I had to make couple of changes,
because on `stopStream`  the camera gets closed in case the recording wasn't working

```
    if (!recordController.isRecording()) {
      onPreview = !isBackground;
      if (audioInitialized) microphoneManager.stop();
      if (glInterface != null) {
        glInterface.removeMediaCodecSurface();
        if (glInterface instanceof OffScreenGlThread) {
          glInterface.stop();
          cameraManager.closeCamera();
        }
      } else {
        if (isBackground) {
          cameraManager.closeCamera();
        } else {
          cameraManager.stopRepeatingEncoder();
        }
      }
```

**Comment by pedroSG94** [comment]
Perfect, Closing issue because it is solved
