### ISSUE TITLE
RTSP Url Pattern

### ISSUE THREAD

**Issue by 1-CharlieShin** [pedroSG94/rtmp-rtsp-stream-client-java#834]
Hello!

I am using this library. But my rtsp url address is like below.
- rtsp://id:@192.168.0.1:554/
(Even password is blank. And there is nothing after port number..)

But **because of url pattern**, I cannot stream..
I tried to find other rtsp url, but I cannot find it.

And I tried to check your pattern with my url.
`Pattern.compile("^rtsps?://([^/:]+)(?::(\\d+))*/([^/]+)/?([^*]*)$").matcher("rtsp://id:@192.168.0.1:554/").matches()`

This statement will return "false".

That's why I cannot stream with this library.

I am using IP Camera that is selling in here.
[https://homecamerakit.com/shop/wifi-security-camera-1080p-ptz-day-night-hip291-ycc365-plus/](https://homecamerakit.com/shop/wifi-security-camera-1080p-ptz-day-night-hip291-ycc365-plus/)

According to their FAQ and my test, there is nothing after port.
(And there is no password, too..)
see [https://www.ycc365plus.com/en/ycc365-plus-camera-rtsp-url-address-and-port-number](https://www.ycc365plus.com/en/ycc365-plus-camera-rtsp-url-address-and-port-number)

**So, can you change the url pattern?**
Or any other solutions..?

I'm sorry for short English.

Thank you.

**Comment by pedroSG94** [comment]
Hello,

First of all, this library is a pusher not a player, so you can't get stream from ip camera using this library.
Also about auth you need use this method instead of set it in url:
```java
//call it any time before startStream
    rtspCamera1.setAuthorization("user", "password");
```

**Comment by 1-CharlieShin** [comment]
> Hello,
> 
> First of all, this library is a pusher not a player, so you can't get stream from ip camera using this library.
> Also about auth you need use this method instead of set it in url:
> 
> ```java
> //call it any time before startStream
>     rtspCamera1.setAuthorization("user", "password");
> ```

**Comment by 1-CharlieShin** [comment]
I will try it. If it works, I will close this thread. Thanks
