### ISSUE TITLE
Question: How to mix the two audio source?

### ISSUE THREAD

**Issue by abadoliverco** [pedroSG94/rtmp-rtsp-stream-client-java#840]
hi @pedroSG94,

im trying to find a way to get the audio from the mic and from internal audio and I want them to combine and pass it to RTMP display, is there any way i can do this or any idea will do. The idea is to capture both mic and internal audio.

Thank you!

**Comment by pedroSG94** [comment]
Hi,

Try this:

Start stream as usually with microphone or internal audio no matter what and mix pcm buffer like this
```java
    //create a manual instance to get frame in a sync way
    final MicrophoneManagerManual microphoneManager = new MicrophoneManagerManual();
    //select one depend of you have in stream instance and configure if with the same parameters that stream
    microphoneManager.createMicrophone(); //configure audio format here
    microphoneManager.createInternalMicrophone(); //configure audio format here
    //start it
    microphoneManager.start();
    rtmpCamera1.setCustomAudioEffect(new CustomAudioEffect() {
      @Override
      public byte[] process(byte[] pcmBuffer) {
        Frame f = microphoneManager.getInputFrame();
        byte[] secondPcmBuffer = f.getBuffer();
        //create a method to mix both frames.
        //You can try use PCMUtil.mixPCM() but it is not guaranteed to work.
        byte[] result = mixPcmBuffers(pcmBuffer, secondPcmBuffer);
        //Keep in mind that result buffer MUST be with the same size that original buffer.
        // fill it with 0 if you have a smaller one, if you have larger one, bytes will be discarded resulting in a weird result.
        return result;
      }
    });
    //stop it after stop stream
    rtmpCamera1.setCustomAudioEffect(new NoAudioEffect());
    microphoneManager.stop();
```

**Comment by abadoliverco** [comment]
Hi @pedroSG94,

Thank you for the quick response.

I followed your idea but my stream has no sound, just a video and I got this on my log

`I/SrsFlvMuxer: frame discarded`

I tried using PCMUtil.mixPCM()

by the way, when to call `rtmpCamera1.setCustomAudioEffect()` because right now this method is not calling when the stream is started.

Thank you!

**Comment by abadoliverco** [comment]
hi @pedroSG94,

I tried to implement this `rtmpCamera1.setCustomAudioEffect()` but I think the audio data is not passing to the `SrsFlvMuxer`, there's a video but no sounds

Thank you!

**Comment by abadoliverco** [comment]
i will close this issue, i think i already figure it out. thank you so much
