### ISSUE TITLE
No Video frames after reconnecting

### ISSUE THREAD

**Issue by marcin-adamczewski** [pedroSG94/rtmp-rtsp-stream-client-java#841]
Hi @pedroSG94 
Since 2.0.1 version, after reconnecting via retry, the video packets are not sent. Only audio packets are sent.

Steps to reproduce:
1. Start streaming (make sure retrying mechanism is used before)
2. Switch from WiFi to LTE so the retry mechanism triggers
3. After successful connecting again, there is no video on the web player

**Comment by marcin-adamczewski** [comment]
I narrowed the issue to this commit https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/479f72b2f3fdfd4eb4b6fd5ab021d30981afe629

**Comment by marcin-adamczewski** [comment]
Digging a little bit more in the latest version's code, I can see that in the Came1Base, Camera2Base, etc.
there is a method like `resetVideoEncoder()`. This method is being called on `reTry()`. 
But in fact, this method doesn't reset the video encoder anymore. It calls `forceKeyFrame()`  instead of `reset()`. If I change it to call the `reset()` method then it works fine. 
I'm not sure if this is safe to do it like this because you've changed it for some reason.

**Comment by pedroSG94** [comment]
I was reseting videoEncoder becasue that force to produce a keyframe (encoding always start with a keyframe)
Theoretically forceKeyFrame is used to force produce a keyframe in the encoder. With this, you don't need reset video encoder anymore.
I tested this on oneplus 7T and this is working totally fine. Maybe this method is ignored in somes devices/encoders :(

Can you tell me device model and api? I will try find a solution without reset encoder. If I can't do anything, I will roll back to old implementation using reset

**Comment by marcin-adamczewski** [comment]
I tested it on his younger brother OnePlus 6T. I've just tested on Android emulator Pixel 2 and getting the same results.
How do you test it?

**Comment by pedroSG94** [comment]
I tested it using start record instead of retry and check that encoder produce a keyframe.
Can you tell me full emulator configuration to reproduce the case?

**Comment by marcin-adamczewski** [comment]
Sure, It's Pixel 2, API 30, x86, Android 11 (Google Play), front camera emulated, back camera as a webcam.
Could you try to test it with the steps I described? If you test on a local server then you can just turn off and on wifi to trigger retry.

**Comment by pedroSG94** [comment]
Gradle of this fix:
```gradle
implementation 'com.github.pedroSG94:rtmp-rtsp-stream-client-java:b3ee94978f'
```

**Comment by marcin-adamczewski** [comment]
@pedroSG94 Seems to work fine now. Thank you :)
