### ISSUE TITLE
Starting Preview in the background

### ISSUE THREAD

**Issue by tareqalbeesh** [pedroSG94/rtmp-rtsp-stream-client-java#847]
is there a way to start the preview using context without `surfaceView `in a background Service?

**Comment by pedroSG94** [comment]
You can set a preview any time using replaceView method like in background example:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/backgroundexample/BackgroundActivity.kt

**Comment by tareqalbeesh** [comment]
I have added a Surface Using ImageReader,
and when this code runs (in case of having a surfaceView) :
```
  RtpService.setView(surfaceView)
  RtpService.startPreview()
```
 the surface starts and I start getting frames,  
but in case I called the:
```
 RtpService.setView(context)
  RtpService.startPreview()
```
the ImageReader Surface don't start getting frames.

**Comment by pedroSG94** [comment]
Closed because it is duplicated now:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/848
