### ISSUE TITLE
Stream freeze for a second in the start

### ISSUE THREAD

**Issue by DipanshKhandelwal** [pedroSG94/rtmp-rtsp-stream-client-java#849]
When I start streaming for the client, if freezes for a couple of seconds then continues perfectly.
I looks fine on the mobile screen, just the stream is disturbed.

Any idea how can I tackle this ?

Please take a look at this video

https://user-images.githubusercontent.com/24923974/116132562-547dfb80-a6eb-11eb-90f0-68799ff2e945.mp4

**Comment by pedroSG94** [comment]
This is weird.
Record and stream use same buffer. If you record a video using my app, can you reproduce the problem?
Did you try with multiple players?

**Comment by DipanshKhandelwal** [comment]
Yes I have tried with multiple apps.

apps with your library:

- your example
- [mux-android-example](https://github.com/muxinc/examples/tree/master/android-live-streaming)
- the app I am working on

all show a similar behaviour

but
this library which is not related do not have this issue.
[Ant media - LiveVideoBroadcaster](https://github.com/ant-media/LiveVideoBroadcaster)

**Comment by pedroSG94** [comment]
I mean if you can record a video (local video) using my app example.
This is only to discard rtmp module problems and try find the possible reason.
Also try with this (don't mix try it one by one):
- In prepareVideo method set IFrame parameter to 0.
```java
    rtmpCamera1.prepareVideo(640, 480, 30, 1200 * 1024, 0, CameraHelper.getCameraOrientation(context));
```
- Force use software video encoder:
```java
// call it before preapre video and audio
rtmpCamera1.setForce(CodecUtil.Force.SOFTWARE, CodecUtil.Force.FIRST_COMPATIBLE_FOUND);
```

**Comment by DipanshKhandelwal** [comment]
I tried the above methods.

- setting `IFrame` parameter to 0:
It did not help, the behaviour was same as before

- Force use software video encoder:
Though this helped, I could see a huge decrease in the stream quality

I recorded a stream using the example app. Attaching the stream video and the recorded video.

Stream video:

https://user-images.githubusercontent.com/24923974/116280184-0d087580-a7a6-11eb-852e-163687b2c021.mp4

Recorded video:

https://user-images.githubusercontent.com/24923974/116280251-1e518200-a7a6-11eb-865a-4d1cd6f3cee8.mp4

If you observe in the recorded video, just after the start there is a small freeze, which I am expecting is the same but a longer freeze in the stream.

Thanks

**Comment by pedroSG94** [comment]
Did you record both videos using software encoder?

Ok, we can discard keyframe problems. So the problem could be encoder or rtmp module (I think that maybe the encoder)
Now, lets try check encoders in your device and use another one. Use this code to show me encoders available in your device and device info:
```java
    Log.e("Pedro", "model: " + Build.MODEL + ", product: " + Build.PRODUCT + ", manufacturer: " + Build.MANUFACTURER);
    for (String s: CodecUtil.showAllCodecsInfo()) Log.e("Pedro", s);
```
Show me logcat result

**Comment by DipanshKhandelwal** [comment]
- No. Both the above video are from the hardware encoder [ Its from your default app ]

Here is the logcat:

[log.txt](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/6386757/log.txt)

**Comment by pedroSG94** [comment]
Did you try using OpenGlExample? default example is only recomend for api < 18.
Ok, I can see in your log that you only have 1 hardware encoder and I have a device with an encoder with the same name
I will try erproduce the error using that encoder (Im not sure if it is possible because my device is a different model but I will try)

**Comment by DipanshKhandelwal** [comment]
> Did you try using OpenGlExample? default example is only recomend for api < 18.

Yes the behaviour is exactly same.

**Comment by g7i** [comment]
Hey @pedroSG94, I think I might have found the problem.  You can refer to the commit https://github.com/g7i/rtmp-rtsp-stream-client-java/commit/436f5742efb79ab10ea693c2e42e2ec35c8167d5.
If I understand the flow correctly, the RTMP connection and publish is being done by another thread.
The encoders are started and begin capturing frames before the connection established. When the connection is successful we see this distortion.
Please look into the issue and let me know for a better way to handle the issue.

**Comment by pedroSG94** [comment]
That commit solve the problem? It is not applicable for rtsp because I need get sps and pps to negotiate connection but I will try find a way to do this.

**Comment by g7i** [comment]
Yes, that commit solves the problem.

> It is not applicable for rtsp because I need get sps and pps to negotiate connection but I will try find a way to do this.

Yeah make sense but I haven't tried it with rtsp yet.

Thanks

**Comment by pedroSG94** [comment]
Hello,

I was working few weeks re creating totally a new rtmp module and with plan to scale with more feature that the currently one. I migrated it to kotlin and it handle a bit different with videoframes. 
This solution could solve the problem without change the VideoEncoder but in case it is not working, I can use a solution for it easier with this version because the logic is similar to rtsp module and this patch could be applied in both modules at same time.
If you can, use this branch and test it to let me know if the problem is solved:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/rtmpkotlin
Also, if you experiment any issue with it and you can open a issue to report me it will be helpful. Any idea of new feature support (actually working in Amf3) or suggest is really welcome.

**Comment by g7i** [comment]
Hey, I tried to run the example app from https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/rtmpkotlin. 
Got this error [error-log.txt](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/6477193/error-log.txt) while streaming to the RTMP URL after the connection has been established successfully.

**Comment by pedroSG94** [comment]
This seems that server close connection. Can you tell me server used?
Also, if you can share me a full log of connection to see packets

**Comment by g7i** [comment]
We're using [mux](https://mux.com/) as backend service.
Here is full logcat after pressing start stream till getting the toast for broken pipe.
[error-log.txt](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/6477328/error-log.txt)

**Comment by pedroSG94** [comment]
I fixed the problem and now work with mux. Try know and let me know if freeze is fixed also.

**Comment by g7i** [comment]
It works and the freeze issue is also gone.
Thank you.

**Comment by pedroSG94** [comment]
It is good to know. 
This kotlin version is still under test because I only tested it on wowza. I will test it on servers of my wiki and YT, FB, Twitch.
After that I will merge it to master and delete/mark as deprecated old one.

If you are insteresting in test it with your server compile my library with this gradle and let me know if work in your server:
```gradle
	        implementation 'com.github.pedroSG94:rtmp-rtsp-stream-client-java:rtmpkotlin-SNAPSHOT'
```

Any help or suggestion is welcome.

**Comment by mustafaboleken** [comment]
> It is good to know.
> This kotlin version is still under test because I only tested it on wowza. I will test it on servers of my wiki and YT, FB, Twitch.
> After that I will merge it to master and delete/mark as deprecated old one.
> 
> If anyone is interested in test it with your server compile my library with this gradle and let me know if work in your server:
> 
> ```groovy-gradle
> 	        implementation 'com.github.pedroSG94:rtmp-rtsp-stream-client-java:rtmpkotlin-SNAPSHOT'
> ```
> 
> Any help or suggestion is welcome.

I tested it on ant media server ee and I use OpenGL but I got broken pipe error after 20-25 seconds.

**Comment by pedroSG94** [comment]
Fixed:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/2043905314f09f80cf66eefdaac542f6789bca7e
Please try using master branch now

**Comment by mustafaboleken** [comment]
It works.
