### ISSUE TITLE
Changing transparency on watermark?

### ISSUE THREAD

**Issue by havalito** [pedroSG94/rtmp-rtsp-stream-client-java#85]
Hi,

First off thanks for this project, it's really appreciated but how would one go about changing transpareny on watermark? I am interested in creating a "HUD" like feel. 

Kind regards

**Comment by pedroSG94** [comment]
Actually transparency is a mix of pixels of camera and watermark (I will change it in the future to set with parameters) but you can do your own transparency if you go to:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/res/raw/watermark_fragment.glsl
Replace:
```glsl
gl_FragColor = cameraPixel + watermarkPixel;
```
To:
```glsl
    if (watermarkPixel.rgb == vec3(0.0, 0.0, 0.0)) {
      gl_FragColor = cameraPixel;
    } else {
      float transparency = 1.0;
      gl_FragColor = (cameraPixel * (1.0 - transparency)) + (watermarkPixel * transparency);
    }
```
Where transparency 1.0 is totally opaque and 0.0 is totally transparent.

**Comment by pedroSG94** [comment]
I added a method to do it on fly:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/9162ae8ea7427ee0c185a53a444c471971ad7981
