### ISSUE TITLE
can I start streaming parallelly in 2 or more URL using this library in Android?

### ISSUE THREAD

**Issue by jyotir1994** [pedroSG94/rtmp-rtsp-stream-client-java#850]
I require to go live on multiple environments simultaneously, but whenever I'm calling mRtmpCamera1.startStream(URL) 2 times with both the URL's streaming is not started.

how can I start streaming parallelly in 2 or more URL using this library in Android?

**Comment by pedroSG94** [comment]
Hello, You can do it but you need modify the library a little. You have an issue that will help you here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/549
