### ISSUE TITLE
Streaming stops when the application came from a background

### ISSUE THREAD

**Issue by jyotir1994** [pedroSG94/rtmp-rtsp-stream-client-java#855]
When the application goes to background and came back to foreground then streaming gets stop

**Comment by pedroSG94** [comment]
Did you try background example?

**Comment by jyotir1994** [comment]
No

**Comment by pedroSG94** [comment]
When you are doing a stream with preview you need handle with view lifecycle because when your view die you can't render it and render should be replaced or stopped. That is the example porpouse.
You should use a code like that to switch background mode and preview as you need without stop stream.

**Comment by jyotir1994** [comment]
I tried this example but still getting the same issue.
When the application came to the foreground screen turns black

**Comment by pedroSG94** [comment]
This is working for me. Screen turn black for ever or only 1 second (1 second is normal).
Did you check with other device?
Are you using my app directly without modify code?
Can you explain your steps to reproduce the error or record a video?
Device model and api?

**Comment by jyotir1994** [comment]
The issue is fixed by using RtmpCamera2 class

**Comment by nguyentu97** [comment]
I've used RtmpCamera2 and it doesn't work! Is there any other solution? Thanks.

**Comment by pedroSG94** [comment]
Did you try using a service as in Background example?
