### ISSUE TITLE
Stream preview

### ISSUE THREAD

**Issue by FunnyDevs** [pedroSG94/rtmp-rtsp-stream-client-java#857]
Hello Pedro,
i use this library to take photo and video (https://github.com/natario1/CameraView) and it has two functions: takephoto (takevideo) and takephotosnapshot (takevideosnapshot); the snapshot functions are used to save what it is shown on the opengl preview with a center crop proportion (so what i see on the preview is equal to what i see on the picture/video saved file).
Can i find a similar function inside your library to stream what i see in the preview?

**Comment by FunnyDevs** [comment]
ok, thank you. I think i should study how to use opengl to crop.
When i use the options `aspectRatioMode `and `keepAspectRatio `i am able (before `startstream`) to have a centercrop (cropped) preview, so my question is: if i have already a cropped surface, applying a filter does it cause a double clipping?

**Comment by pedroSG94** [comment]
Yes, so I recommend you disable keepAspectRatio.
To apply a similar filter you can check keepAspectRatio and emulate that effect.
In this case you can check it here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/gl/render/ScreenRender.java#L86
Now you can copy NoFilter class and change viewport like in calculateViewPort to take that effect:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/gl/render/filters/NoFilterRender.java

**Comment by pedroSG94** [comment]
Remember that when you call prepareVideo method resolution could change depend of rotation, width or height.
You have 2 ways to solve it:
- Set same rotation and resolution to startPreview
- Update rotation, width and height of your filter after call that method (you can do it by setters and you will get changes on fly.

**Comment by FunnyDevs** [comment]
ok, i have set same parameters for startpreview and preparevideo. The only problem is the quality, not so good ( i have chosen the preview resolution next to opengl width and height). Is there anything i can do to improve it?

**Comment by pedroSG94** [comment]
If the problem is quality in preview the only way is increase resolution. If you only have problems in stream/record result try increase video bitrate

**Comment by FunnyDevs** [comment]
Ok, with a higher video bitrate the quality is ok; but it's strange that with 720p and default bitrate i record with a decent quality without filter, instead with the filter i have a bad quality.

**Comment by pedroSG94** [comment]
This is normal.
The quality is the same in both cases but by default stream result isn't scaled. In your case you are doing a scale so you need increase quality to get same quality.

**Comment by FunnyDevs** [comment]
ok, thank you again

**Comment by zhouhuirun2015** [comment]
> ok, thank you again

Hi, can you give some tips(about how to set glViewport) or show some code(crop filter) about keeping image same in preview and streaming/recording file?

Thanks.
