### ISSUE TITLE
[RtmpOnlyAudio] stopStream method don't work

### ISSUE THREAD

**Issue by lqmminh** [pedroSG94/rtmp-rtsp-stream-client-java#860]
This is log:
I/SrsFlvMuxer(18829): SrsFlvMuxer closed
I/MicrophoneManager(18829): Microphone stopped
I/AudioEncoder(18829): stopped
D/AudioStream(18829): onDisconnectRtmp
I/SrsFlvMuxer(18829): worker: disconnect ok.
D/RtmpConnection(18829): wrote packet: RTMP Audio, size: 256
W/System  (18829): A resource failed to call release. 
I/flutter (18829): Event {eventType: rtmp_stopped, errorDescription: Disconnected}
I/BpBinder(18829): onLastStrongRef automatically unlinking death recipients: <uncached descriptor>
D/RtmpConnection(18829): wrote packet: RTMP Audio, size: 291
D/RtmpConnection(18829): wrote packet: RTMP Audio, size: 255
After i call this method all still running :( 
Any help me. Please!

**Comment by pedroSG94** [comment]
This is working perfectly for me. Are you sure that you are not doing any retry?
Can you share me a code example? In my case I go to default example and replace RtmpCamera1 to RtmpOnlyAudio and delete all method not available

**Comment by lqmminh** [comment]
Tks for response!
I writing it in plugin in flutter and when user press to button stop i call "rtmpAudio.stopStream()"
And this is log:
I/SrsFlvMuxer(18829): SrsFlvMuxer closed
I/MicrophoneManager(18829): Microphone stopped
I/AudioEncoder(18829): stopped
D/AudioStream(18829): onDisconnectRtmp
I/SrsFlvMuxer(18829): worker: disconnect ok.
D/RtmpConnection(18829): wrote packet: RTMP Audio, size: 256
W/System (18829): A resource failed to call release.
I/flutter (18829): Event {eventType: rtmp_stopped, errorDescription: Disconnected}
I/BpBinder(18829): onLastStrongRef automatically unlinking death recipients:
D/RtmpConnection(18829): wrote packet: RTMP Audio, size: 291
D/RtmpConnection(18829): wrote packet: RTMP Audio, size: 255

**Comment by lqmminh** [comment]
SrsFlvMuxer log closed and disconnect but stream still running :(

**Comment by pedroSG94** [comment]
Since it is working on my side. I need a code example to reproduce the problem.
Also, to confirm that it is not a library issue try using my case test (go to default example, replace RtmpCamera1 to RtmpOnlyAudio and delete all methods not available)

**Comment by lqmminh** [comment]
yeah haha. This work fine!
But when we start and stop adjacent it will get this problem and after about 1 - 2 minute it will stop 👍

**Comment by lqmminh** [comment]
Tks @pedroSG94. I will close this issue but hope you will do better in the future
