### ISSUE TITLE
New future! 

### ISSUE THREAD

**Issue by lqmminh** [pedroSG94/rtmp-rtsp-stream-client-java#861]
I need record only audio to path and record with stream only audio for my application. Can you help me!

**Comment by pedroSG94** [comment]
Hello,

You can record using only audio mode like in the other modes:
```java
RtmpOnlyAudio rtmpOnlyAudio = new RtmpOnlyAudio(this);
    if (rtmpOnlyAudio.prepareAudio()) {
      try {
        rtmpOnlyAudio.startRecord("path");
      } catch (IOException e) {
        Log.e("Pedro", "record failed", e);
      }
    }
```

**Comment by lqmminh** [comment]
hi @pedroSG94 
Tks for answer. but when use RtmpOnlyAudio object, this will reaction every time connect changed. :(

**Comment by pedroSG94** [comment]
I don't understand.
Can you exaplain it a bit?. Explain steps to reproduce the current problem and expected behavior
