### ISSUE TITLE
Change the bit depth of audio

### ISSUE THREAD

**Issue by FirstSpectr** [pedroSG94/rtmp-rtsp-stream-client-java#865]
I am using rtmp streaming, on the server side I get audio with MPEG AAC Audio codec and 32 bit depth. Is it possible to change this value to 16 or 8 bits?

I tried using this but nothing changed

```
val rtmpCamera: RtmpCamera2 = RtmpCamera2(openGlView, this)
val mediaFormat = MediaFormat()
mediaFormat.setInteger(MediaFormat.KEY_PCM_ENCODING, AudioFormat.ENCODING_PCM_8BIT)
rtmpCamera.onAudioFormat(mediaFormat)
```

**Comment by pedroSG94** [comment]
Hello,

Audio is already 16bit:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/audio/MicrophoneManager.java#L31
If you are using rtmp. Remember change it too here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/pedro/rtmp/flv/audio/AacPacket.kt#L21
and here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/pedro/rtmp/rtmp/CommandsManager.kt#L143

**Comment by FirstSpectr** [comment]
Many Thanks!
