### ISSUE TITLE
Preview deformed while rotating 

### ISSUE THREAD

**Issue by ButtersHub** [pedroSG94/rtmp-rtsp-stream-client-java#87]
In case I'm enabling landscape in the demo project, the image is stretched while I'm rotating.
surfaceChanged is called only when rotation completed, so i can't use this method.

Any idea? 

BTW, great work on the Lib, I want to use wrap it and use it as ReactNative library.

**Comment by pedroSG94** [comment]
The preview is stretched because you use an aspect ratio in surfaceview different of the stream.
For example:
If you select stream resolution of 1920x1080 aspect ratio = 16:9. So you need create a surfaceview with 16 pixels of width each 9 of height.

**Comment by ButtersHub** [comment]
Thx, this fixed the problem, I had to call `prepareVideo(.....)` before `startPreview()`:

   ```
     getHolder().addCallback(new SurfaceHolder.Callback() {
            @Override
            public void surfaceCreated(SurfaceHolder surfaceHolder) {
                String resolution = rtmpCamera1.getResolutions().get(0);
                int width = Integer.parseInt(resolution.split("X")[0]);
                int height  = Integer.parseInt(resolution.split("X")[1]);
                rtmpCamera1.prepareVideo(width, height, fps, videoBitrate * 1024, isHardwareRotatation, orientations[1]);
                rtmpCamera1.startPreview();
            }

            @Override
            public void surfaceChanged(SurfaceHolder holder, int format, int width, int height){
            }
            @Override
            public void surfaceDestroyed(SurfaceHolder surfaceHolder) {
                rtmpCamera1.stopPreview();
            }
        });
    }

```
Now I have a problem changing orientation on rotating from portrait to landscape (and vice versa), the orientation is set only in Camera1ApiManager constructor, can I change it while previewing? or I'm doing something wrong

**Comment by pedroSG94** [comment]
I'm not sure if I understand the question.
Do you want change preview orientation on startPreview but with the same stream orientation?
Orientation only change stream result. The preview orientation is setted to the camera automatically to 0 if you are in landscape or reverse landscape activity or 90 if you are in portrait or reverse portrait activity.
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java#L59

Want do you want exactly? Maybe I can do a little change in the library if the requeriment is usefull
If you explain me it with a picture, it will be more easy for me.

**Comment by ButtersHub** [comment]
I want to be able to change the orientation on the fly while previewing.
For example, I started with portrait (90), and while previewing I rotated the device to landscape.

and there is no place where i can call `camera.setDisplayOrientation(orientation);` with the new orientation.

maybe  `camera.setDisplayOrientation` method should be exposed from RtmpCamera1/Camera1Base
This method can be called while previewing: 

> Starting from API level 14, this method can be called when preview is active.

https://developer.android.com/reference/android/hardware/Camera.html#setDisplayOrientation(int)

**Comment by pedroSG94** [comment]
I did a commit in the library to implement it: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/51cb8dd7b19760d0d358024fd0d85f7035cb9b0d
Now:
```java
rtmpCamera1.prepareVideo(width, height, fps, videoBitrate * 1024, isHardwareRotatation, rotation);
rtmpCamera1.startPreview();
```
This is incorrect. You have startPreview method with a resolution. Remember that preparevideo will override resolution of startPreview when call to startStream.
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/51cb8dd7b19760d0d358024fd0d85f7035cb9b0d#diff-cfc8e034d6d6419c1a64088e9cb13dcbR193

setPreviewOrientation() method change the orientation of your preview camera on fly. This can be called when you want (before, after or while the stream). If you never call this method library will select the orientation for you in the rtmpCamera1 constructor. Remember this change only preview no result stream so if you change it while you are stream the result will not rotate only preview rotate.
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/51cb8dd7b19760d0d358024fd0d85f7035cb9b0d#diff-cfc8e034d6d6419c1a64088e9cb13dcbR213

**Comment by ButtersHub** [comment]
Thanks a lot, ill try and update
