### ISSUE TITLE
Why do I use rtsponlyaudio to record audio in MPEG, mp4a format. The recorded audio file cannot be used normally when it is put on the web page.

### ISSUE THREAD

**Issue by iqiluwxy** [pedroSG94/rtmp-rtsp-stream-client-java#872]

**Comment by pedroSG94** [comment]
I use mp4 because I'm using MediaMuxer and only that format is supported:
https://developer.android.com/reference/android/media/MediaMuxer#MediaMuxer(java.lang.String,%20int)
