### ISSUE TITLE
[Question] Manual Focus

### ISSUE THREAD

**Issue by welcome2c** [pedroSG94/rtmp-rtsp-stream-client-java#876]
Hi @pedroSG94  is available set focus distance manually? not use autofocus

**Comment by pedroSG94** [comment]
tap to focus?
You can try this:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/customexample/RtmpActivity.java#L429

**Comment by welcome2c** [comment]
@pedroSG94 
No I want to set and fix the focus value before the start of the broadcast 
like CaptureRequest.LENS_FOCUS_DISTANCE, 5f

**Comment by pedroSG94** [comment]
No, it is not implemented.
You can try implement it yourself here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java
If you can't do it let me know and I will try do it but It will take time. (Actually I'm working in others things)

**Comment by welcome2c** [comment]
ok thanks i will try

**Comment by welcome2c** [comment]
@pedroSG94 Hi I developed that feature, can you review and add this code?

Camera2ApiManager.java

 public void setFocusDistance(float distance) {
    CameraCharacteristics characteristics = getCameraCharacteristics();
    if (characteristics == null) return;
    if (builderInputSurface != null) {
      try {
        builderInputSurface.set(CaptureRequest.LENS_FOCUS_DISTANCE, distance);
        cameraCaptureSession.setRepeatingRequest(builderInputSurface.build(), null, null);
      } catch (Exception e) {
        Log.e(TAG, "Error", e);
      }
    }
  }

--------------------------------------------------------------------------------
Camera2Base.java

public void setFocusDistance(float distance) {
    cameraManager.setFocusDistance(distance);
  }

thanks bro

**Comment by pedroSG94** [comment]
I added it to proyect:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/bd58cb06688b50a37927ff31ba80efe8b979f8b4
According this documentation negatives values are invalid so I fixed it replacing negatives values to 0:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/bd58cb06688b50a37927ff31ba80efe8b979f8b4

**Comment by welcome2c** [comment]
@pedroSG94 Thank you so much bro
