### ISSUE TITLE
Instruction on how to live stream to media server

### ISSUE THREAD

**Issue by noexcuse0414** [pedroSG94/rtmp-rtsp-stream-client-java#88]
I am very new in this field and do not know a lot of streaming stuff. Could you please post some instruction on how to live stream video to wowza server or https://github.com/iizukanao/node-rtsp-rtmp-server ? What should I put in the "rtsp://yourendpoint" text field?

really appreciated.

**Comment by pedroSG94** [comment]
In this post you have a little guide to install wowza:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/34
The readme of  https://github.com/iizukanao/node-rtsp-rtmp-server is really explicative. 
Use it and tell me if you have any dude.
If you have server working then the endpoint should be like:

rtsp
```
rtsp://ip:port/appname/streamname
```
rtmp
```
rtmp://ip:port/appname/streamname
```
Where ip is the ip of pc where you installed the media server, Port is the port that you configured to stream (on wowza 1935 by default for rtsp and rtmp, on node-rtsp-rtmp-server 1935 for rtmp and 80 for rtsp by default). Appname is the application that you configured in your server (live by default on both servers). Streamname is the name that you use for stream (this is a random name, you can write anything for example noexcuse0414).
So a example endpoint for rtmp is:
```
rtmp://192.168.1.5/live/noexcuse0414
```

**Comment by noexcuse0414** [comment]
Thank you very much for your reply. It is working now with Wowza. However, the live streaming does not seem to be "real time". The Video display on Wowza server is 10-20s behind the video feed on the mobile phone. Is that the expected behavior? Or did I make a mistake? 

Thank you again for your help.

**Comment by madmate** [comment]
Is it also possible to stream directly to vlc or omxplayer?

**Comment by pedroSG94** [comment]
No, if you want stream to vlc directly you should emulate a server side protocol to work. This library only has client side implementation.
