### ISSUE TITLE
For this project, can we do the secondary development of multi-player video conferencing

### ISSUE THREAD

**Issue by ILoveLin** [pedroSG94/rtmp-rtsp-stream-client-java#880]
在这个项目上,可以做多人视频会议二次开发吗?
For this project, can we do the secondary development of multi-player video conferencing

**Comment by ILoveLin** [comment]
Thank you. I see what you mean. The video conferency is "many to many, bidirecctional" and this is "one to many, unidirecctional".So, the second development on this project is not going to be able to implement video conferencing, right

**Comment by pedroSG94** [comment]
webrtc tecnology can be used in China for sure but you need create your own servers and download library in an unofficial website (because you can't access to google servers to test).
Maybe you can ask to other chinise developer how to start:
https://github.com/ddssingsong/webrtc_android

**Comment by ILoveLin** [comment]
Thank you, brother, for helping me out all the time. Thanks again

**Comment by pedroSG94** [comment]
This seems finished. Closing issue, open other one if you have any question
