### ISSUE TITLE
[Question] H264Packet is using Annex B or AVCC?

### ISSUE THREAD

**Issue by ngoluuduythai** [pedroSG94/rtmp-rtsp-stream-client-java#887]
I stream RTMP from android using rtmp-rtsp-stream-client-java, but in ios HaishinKit.swift lib to view this stream. I hear only the audio can't render the video.
I guest two libs can have different h264 format. So I want to ask, Does H264Packet using AVCC format?.

**Comment by pedroSG94** [comment]
It is using annexb

**Comment by pedroSG94** [comment]
VideoEncoder produce annexb frames and then rtmp remove that header and include avc header to it

**Comment by ngoluuduythai** [comment]
Thanks, @pedroSG94 , That meaning the current libary already in RTMP with AVCC format.
