### ISSUE TITLE
Unknown/unhandled server invoke

### ISSUE THREAD

**Issue by anhvo312** [pedroSG94/rtmp-rtsp-stream-client-java#89]
Please help me !!!. when i use url (rtmp://52.69.165.220:1935/live_portrait/stream_id) it's working, but i use url (rtmp://52.69.165.220:1935/live1/stream_id) it got error >_<. this is me Logcat

> 
11-28 17:17:20.545 16355-16355/jp.stagegroup.livestream I/VideoEncoder: videoEncoder OMX.qcom.video.encoder.avc type supported: video/avc
11-28 17:17:20.545 16355-16355/jp.stagegroup.livestream W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
11-28 17:17:20.547 16355-16355/jp.stagegroup.livestream I/VideoEncoder: Color supported: 2141391876
11-28 17:17:20.547 16355-16355/jp.stagegroup.livestream I/VideoEncoder: Color supported: 2130708361
11-28 17:17:20.548 16355-16355/jp.stagegroup.livestream I/VideoEncoder: Color supported: 2135033992
11-28 17:17:20.548 16355-16355/jp.stagegroup.livestream I/VideoEncoder: Color supported: 21
11-28 17:17:20.627 16355-16355/jp.stagegroup.livestream W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
11-28 17:17:20.632 16355-25371/jp.stagegroup.livestream W/OMXUtils: do not know color format 0x7fa30c04 = 2141391876
11-28 17:17:20.633 16355-25371/jp.stagegroup.livestream W/OMXUtils: do not know color format 0x7f000789 = 2130708361
11-28 17:17:20.639 16355-25371/jp.stagegroup.livestream I/ACodec: setupAVCEncoderParameters with [profile: Baseline] [level: Level3]
11-28 17:17:20.640 16355-25371/jp.stagegroup.livestream I/ACodec: [OMX.qcom.video.encoder.avc] cannot encode color aspects. Ignoring.
11-28 17:17:20.641 16355-25371/jp.stagegroup.livestream I/ACodec: [OMX.qcom.video.encoder.avc] cannot encode HDR static metadata. Ignoring.
11-28 17:17:20.641 16355-25371/jp.stagegroup.livestream I/ACodec: setupVideoEncoder succeeded
11-28 17:17:20.679 16355-16355/jp.stagegroup.livestream I/MicrophoneManager: Microphone created, 44100hz, Stereo
11-28 17:17:20.693 16355-25387/jp.stagegroup.livestream I/SrsFlvMuxer: worker: connecting to RTMP server by url=rtmp://52.69.165.220:1935/live1/6457a7a4009ce3ea
11-28 17:17:20.694 16355-25387/jp.stagegroup.livestream D/RtmpConnection: connect() called. Host: 52.69.165.220, port: 1935, appName: live1, publishPath: 6457a7a4009ce3ea
11-28 17:17:20.721 16355-16355/jp.stagegroup.livestream I/AudioEncoder: AudioEncoder started
11-28 17:17:20.816 16355-25387/jp.stagegroup.livestream D/RtmpConnection: connect(): socket connection established, doing handhake...
11-28 17:17:20.816 16355-25387/jp.stagegroup.livestream D/Handshake: writeC0
11-28 17:17:20.816 16355-25387/jp.stagegroup.livestream D/Handshake: writeC1
11-28 17:17:20.816 16355-25387/jp.stagegroup.livestream D/Handshake: writeC1(): Calculating digest offset
11-28 17:17:20.817 16355-25387/jp.stagegroup.livestream D/Handshake: writeC1(): (real value of) digestOffset: 421
11-28 17:17:20.817 16355-25387/jp.stagegroup.livestream D/Handshake: writeC1(): recalculated digestOffset: 1197
11-28 17:17:20.817 16355-25387/jp.stagegroup.livestream D/Handshake: writeC1(): digestOffsetBytes: 0000A6FF
11-28 17:17:20.817 16355-25387/jp.stagegroup.livestream D/Handshake: partBeforeDigest(): size: 1197
11-28 17:17:20.819 16355-25387/jp.stagegroup.livestream D/Handshake: writeC1(): Writing timestamp and Flash Player version
11-28 17:17:20.819 16355-25387/jp.stagegroup.livestream D/Handshake: partAfterDigest(): size: 307
11-28 17:17:20.819 16355-25387/jp.stagegroup.livestream D/Handshake: copying digest offset bytes in partBeforeDigest
11-28 17:17:20.820 16355-25387/jp.stagegroup.livestream D/Handshake: writeC1(): Calculating digest
11-28 17:17:20.820 16355-25387/jp.stagegroup.livestream D/Handshake: writeC1(): writing C1 packet
11-28 17:17:20.822 16355-25387/jp.stagegroup.livestream D/Handshake: readS0
11-28 17:17:20.854 16355-16355/jp.stagegroup.livestream I/Camera1ApiManager: 640X480
11-28 17:17:20.859 16355-16355/jp.stagegroup.livestream I/MicrophoneManager: Microphone started
11-28 17:17:20.861 16355-16355/jp.stagegroup.livestream I/Choreographer: Skipped 45 frames!  The application may be doing too much work on its main thread.
11-28 17:17:20.890 16355-25387/jp.stagegroup.livestream D/Handshake: readS1
11-28 17:17:20.890 16355-25387/jp.stagegroup.livestream D/Handshake: readS1(): S1 total bytes read OK
11-28 17:17:20.890 16355-25387/jp.stagegroup.livestream D/Handshake: readC2
11-28 17:17:20.890 16355-25387/jp.stagegroup.livestream D/Handshake: readS2
11-28 17:17:20.890 16355-25387/jp.stagegroup.livestream D/Handshake: readS2(): S2 total bytes read OK
11-28 17:17:20.890 16355-25387/jp.stagegroup.livestream D/RtmpConnection: connect(): handshake done
11-28 17:17:20.894 16355-25387/jp.stagegroup.livestream D/RtmpConnection: rtmpConnect(): Building 'connect' invoke packet
11-28 17:17:20.896 16355-25387/jp.stagegroup.livestream D/RtmpConnection: wrote packet: RTMP Command (command: connect, transaction ID: 1), size: 273
11-28 17:17:20.898 16355-25443/jp.stagegroup.livestream D/RtmpConnection: starting main rx handler loop
11-28 17:17:20.904 16355-16361/jp.stagegroup.livestream I/zygote64: Do partial code cache collection, code=247KB, data=189KB
11-28 17:17:20.904 16355-16361/jp.stagegroup.livestream I/zygote64: After code cache collection, code=246KB, data=189KB
11-28 17:17:20.904 16355-16361/jp.stagegroup.livestream I/zygote64: Increasing code cache capacity to 1024KB
11-28 17:17:20.982 16355-25443/jp.stagegroup.livestream D/RtmpConnection: handleRxPacketLoop(): Setting acknowledgement window size: 2500000
11-28 17:17:20.982 16355-25443/jp.stagegroup.livestream D/RtmpConnection: handleRxPacketLoop(): Send acknowledgement window size: 2500000
11-28 17:17:20.982 16355-25443/jp.stagegroup.livestream D/RtmpConnection: wrote packet: RTMP Window Acknowledgment Size, size: 4
11-28 17:17:20.983 16355-25443/jp.stagegroup.livestream D/RtmpDecoder: readPacket(): Setting chunk size to: 4096
11-28 17:17:20.985 16355-25443/jp.stagegroup.livestream I/RtmpConnection: Connection failed: Application rejected connection.
**11-28 17:17:20.986 16355-25443/jp.stagegroup.livestream E/RtmpConnection: handleRxInvoke(): Unknown/unhandled server invoke: RTMP Command (command: close, transaction ID: 0)**
11-28 17:17:20.988 16355-25387/jp.stagegroup.livestream D/RtmpConnection: socket closed
11-28 17:17:21.061 16355-16355/jp.stagegroup.livestream I/MicrophoneManager: Microphone stopped
11-28 17:17:21.062 16355-16355/jp.stagegroup.livestream I/SrsFlvMuxer: SrsFlvMuxer closed
11-28 17:17:21.063 16355-25459/jp.stagegroup.livestream I/SrsFlvMuxer: worker: disconnect ok.
11-28 17:17:21.092 16355-16355/jp.stagegroup.livestream I/AudioEncoder: AudioEncoder stopped
> 

live1: landscape
live_portrait: portrait

Thanks you so much !!!

**Comment by anhvo312** [comment]
![screen shot 2017-11-28 at 5 22 16 pm](https://user-images.githubusercontent.com/25069423/33314603-ba9efe66-d460-11e7-9c7a-77d2c2f23b20.png)

**Comment by pedroSG94** [comment]
This look a bad configuration in live1 application on server side.
```
11-28 17:17:20.985 16355-25443/jp.stagegroup.livestream I/RtmpConnection: Connection failed: Application rejected connection.
```
Did you tried with ffmpeg commands?

**Comment by anhvo312** [comment]
sorry, i just learn android on 2 week. i will try with ffmpeg (research by google) as you tell. i too think server side got bad configuration in live1 application. Thanks for your help !!!

**Comment by anhvo312** [comment]
![screen shot 2017-11-29 at 12 52 10 pm](https://user-images.githubusercontent.com/25069423/33359979-261c4754-d504-11e7-8d28-87427c0d86ba.png)

**Comment by pedroSG94** [comment]
ffmpeg on desktop not on android.
https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/Installing-ffmpeg-on-Mac-OS-X
With ffmpeg installed use this command in console:
```
ffmpeg -i pathtomp4file -f flv rtmp://ip:port/appname/streamname
```
Where pathtomp4file is a path to a mp4 file in your disk that will be streamed and rtmp://ip:port/appname/streamname is the endpoint used in this library.
Ffmpeg should give you more info about the connection fail. 
What media server are you using? can you post your live1 configuration?

**Comment by anhvo312** [comment]
`What media server are you using? can you post your live1 configuration?`
(rtmp://52.69.165.220:1935/) this server of customer i can't touch it

`Where pathtomp4file is a path to a mp4 file`
i stream by live camera, not mp4 file

  On IOS my friend use (https://github.com/shogo4405/HaishinKit.swift) and it work, i use same library (https://github.com/shogo4405/HaishinKit.kt) but it not work and got error like when i use your lirary. I asked admin of server, he talk "i can't see any error in log of server, I see the log of Wowza (distribution) server". ^^ i don't know what happen.

**Comment by pedroSG94** [comment]
If i do stream to:
```
rtmp://52.69.165.220:1935/live1/pedro
```
Server response me with auth error. I think, you need user and password to do stream, ask to the admin for it and use the method rtmpCamera1.setAuthorization(); before rtmpCamera1.startStream() method. Other option is disable auth requeriments like in live_portrait application.

**Comment by anhvo312** [comment]
you are correct, finaly i found solution. Thank you so much
