### ISSUE TITLE
Camera Preview is Stretched

### ISSUE THREAD

**Issue by vijayjangid2000** [pedroSG94/rtmp-rtsp-stream-client-java#893]
Thanks for this amazing library. I successfully implemented this in my project. But the preview is vertically stretched. I really need your help.

I am using Vivo 1814 for testing and it happens in all devices.

**Comment by pedroSG94** [comment]
Did you try OpenGL example with keepaspectratio enabled?
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/res/layout/activity_open_gl.xml#L12

**Comment by vijayjangid2000** [comment]
You are awesome, Thanks for the reply. I thank you from my whole complete heart. Now it's working, by mistake, I replaced the OpenGL view with SurfaceView of my Own.
