### ISSUE TITLE
onNewBitrateRtmp(long bitrate) will show total bitrate and audio bitrate alternately

### ISSUE THREAD

**Issue by felixyangtw** [pedroSG94/rtmp-rtsp-stream-client-java#894]
Hi:
   I use RTMP to stream to server. I found a problem. Normally, onNewBitrateRtmp will always show total bitrates. However, I turn off the Wi-FI on the cell phone and use rtmpCamera1.stopStream() to stop stream and then use rtmpCamera1.startStream(StreamURL) to start streaming. I found onNewBitrateRtmp will show otal bitrate and audio bitrate alternately. The log is as the following, how should I do to disable showing audio bitrate?(version:2.0.5)

Normally:
Video:3.5Mbps  Audio:128kbs
6-15 15:17:02.381 14906 15024 E Felix   : RTMP bitrate:3405712
06-15 15:17:03.386 14906 15024 E Felix   : RTMP bitrate:3169300
06-15 15:17:04.399 14906 15024 E Felix   : RTMP bitrate:3215715
06-15 15:17:05.399 14906 15024 E Felix   : RTMP bitrate:3250864
06-15 15:17:06.407 14906 15024 E Felix   : RTMP bitrate:3236634
06-15 15:17:07.419 14906 15024 E Felix   : RTMP bitrate:3380395
06-15 15:17:08.420 14906 15024 E Felix   : RTMP bitrate:3214176
06-15 15:17:09.429 14906 15024 E Felix   : RTMP bitrate:3449673
06-15 15:17:10.439 14906 15024 E Felix   : RTMP bitrate:3225505
06-15 15:17:11.455 14906 15024 E Felix   : RTMP bitrate:3158440
06-15 15:17:12.484 14906 15024 E Felix   : RTMP bitrate:3195910
06-15 15:17:13.499 14906 15024 E Felix   : RTMP bitrate:3344859
06-15 15:17:14.500 14906 15024 E Felix   : RTMP bitrate:3112399
06-15 15:17:15.505 14906 15024 E Felix   : RTMP bitrate:3662049
06-15 15:17:16.521 14906 15024 E Felix   : RTMP bitrate:3414582
......

Strange:
Video:3.5Mbps  Audio:128kbs
06-15 15:01:27.290 13664 14286 E Felix   : RTMP bitrate:133597
06-15 15:01:27.829 13664 14285 E Felix   : RTMP bitrate:3428287
06-15 15:01:28.330 13664 14286 E Felix   : RTMP bitrate:137332
06-15 15:01:29.864 13664 14285 E Felix   : RTMP bitrate:3181686
06-15 15:01:30.469 13664 14286 E Felix   : RTMP bitrate:134392
06-15 15:01:30.890 13664 14285 E Felix   : RTMP bitrate:3100288
06-15 15:01:31.511 13664 14286 E Felix   : RTMP bitrate:135623
06-15 15:01:31.890 13664 14285 E Felix   : RTMP bitrate:3478600
06-15 15:01:32.589 13664 14286 E Felix   : RTMP bitrate:138087
06-15 15:01:32.920 13664 14285 E Felix   : RTMP bitrate:3154151
06-15 15:01:33.650 13664 14286 E Felix   : RTMP bitrate:134001
....

Video:3.5Mbps  Audio:256kbs
06-15 15:03:52.358 14607 14825 E Felix   : RTMP bitrate:3709624
06-15 15:03:52.445 14607 14824 E Felix   : RTMP bitrate:267973
06-15 15:03:53.383 14607 14825 E Felix   : RTMP bitrate:3457998
06-15 15:03:53.544 14607 14824 E Felix   : RTMP bitrate:265106
06-15 15:03:54.412 14607 14825 E Felix   : RTMP bitrate:3502561
06-15 15:03:54.584 14607 14824 E Felix   : RTMP bitrate:268481
06-15 15:03:55.416 14607 14825 E Felix   : RTMP bitrate:3620629
06-15 15:03:55.625 14607 14824 E Felix   : RTMP bitrate:267965
06-15 15:03:56.437 14607 14825 E Felix   : RTMP bitrate:3339659
06-15 15:03:56.725 14607 14824 E Felix   : RTMP bitrate:265106
06-15 15:03:57.466 14607 14825 E Felix   : RTMP bitrate:3691133
06-15 15:03:57.764 14607 14824 E Felix   : RTMP bitrate:268481
....

**Comment by pedroSG94** [comment]
I will check it. Can you reproduce this problem with all devices?

**Comment by pedroSG94** [comment]
I can see in your logs that the callback is called 2 times in a second but this only should be called a time each second. 
This means that maybe the library is using 2 instances of BitrateManager but I only have one instance declared.

- Did you modify the library?
- Can you try add a log in [BitrateManager class](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/pedro/rtmp/utils/BitrateManager.kt) to know if it is called 2 times?
```kotlin
init {
    Log.e("Pedro", "BitrateManager initialized")
  }
```
This log should be called only a time when you create RtmpCamera1 class.

**Comment by felixyangtw** [comment]
Yes. I rewrite RtmpCamera1 for external camera. I checked my program and I found I set rtmpCamera1=null, when WI-FI is error and new RTMPCamera1 again to restart connect when WI-FI is ready again. It will show total bitrate and audio bitrate. If I don't renew RTMPCamera1 it is ok. However, if I don't set rtmpCamera1=null and new RTMPCamera1 again(I startStream directly), the video will become strange (poor image (Mosaic...)). How should I do?( I stream to youtube.)

**Comment by felixyangtw** [comment]
I do an experiment agagin. I found if I  stop stream and set rtmpCamera1=null and new rtmpCamera1 in the same activity. This situation will happen even I finish this activity,  enter the activity, start a new stream agagin. If I stop stream and set rtmpCamera1=null, quit the activity, enter the activity, and start a new stream, this situation will not happen.

**Comment by pedroSG94** [comment]
First of all, I recommend you use examples provided in this proyect to know if you have any fail using it to discard custom implementations problems.
If all is working fine doing your test in my project. We can do the following:
- Share a code example and I can help you find the problem.
- Set rtmpCamera1=null is not necessary in most of cases. I recommend let java collector delete the instance and use rtmpCamera as singleton.

**Comment by felixyangtw** [comment]
I found I made a mistake. I new rtmpCamera1 twice when I restart to stream so there are two instance to do encoder. I fixed it. Thanks for your kindly help.

**Comment by pedroSG94** [comment]
This seems solved. Closing issue
