### ISSUE TITLE
Video stabilization

### ISSUE THREAD

**Issue by Nodalailama** [pedroSG94/rtmp-rtsp-stream-client-java#896]
Hi, 

Is there a way to have video stabilization ?

Thanks.

**Comment by pedroSG94** [comment]
I did a commit for it:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/15be5effc70b91b489a9ba73970230a215838d24

Let me know if it is working for you.

**Comment by Nodalailama** [comment]
Ok, super duper quick. Ave Cesar. 
I will try and then I tell you.

**Comment by Nodalailama** [comment]
Hi,

Thanks, 
how can I specify this commit using gradle ?

**Comment by pedroSG94** [comment]
Try this:
```gradle
implementation 'com.github.pedroSG94:rtmp-rtsp-stream-client-java:15be5effc7'
```

**Comment by Nodalailama** [comment]
Hi,

So its working fine but I implement the same on iphone and on android, the stabilization is not top notch.
Maybe using the camera 2 lib should be better when using stabilization.

Thank you very much to replied me quickly.
