### ISSUE TITLE
Crashes on start

### ISSUE THREAD

**Issue by mattghall** [pedroSG94/rtmp-rtsp-stream-client-java#9]
I'm passing in a valid rtmp url to the `rtmpBuilder.startStream(rtmp_url);` but the app is crashing on RtmpBuilder.class line 87 `this.cameraManager.start();`.

Error reading `com.pedro.encoder.input.video.CameraOpenException: This camera resolution cant be opened`

Any ideas on how to get around this?

**Comment by pedroSG94** [comment]
Are you doing default preparevideo? if you do it and crash that is because your device cant open to 1280x720 (default resolution setted in the library). Go to Camera1ApiManager class and do a log in checkCanOpen method and try with that resolution like this:
```
private boolean checkCanOpen() {
    for (Camera.Size size : getPreviewSize()) {
      Log.e(TAG, size.width + "x" + size.height);
      if (size.width == width && size.height == height) {
        return true;
      }
    }
    return false;
  }
```

You can use my app example and open menu in custom rtsp or custom rtmp for see resolutions supported for your device.

**Comment by mattghall** [comment]
I'm following the example at https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/c926da855f5cef09a8a71bf873b8dec315a6716d/app/src/main/java/com/pedro/rtmpstreamer/defaultexample/ExampleRtmpActivity.java

I threw `rtmpBuilder.startStream(sStreamUrl);` in a try catch so the app won't crash, but what's strange is `onConnectionSuccessRtmp()` is still being fired, after the resolution error.

Android.hardware.Camera is deprecated with API 21 so I'm needing to use Camera2. Have you gotten the stream to work with Camera2?

**Comment by pedroSG94** [comment]
You don't need a catch, you need select a correct resolution. Obviously if you do a catch app continue and you will get a connect success but you never will send video because camera crashed.
Use method prepareVideo with params like:
`prepareVideo(int width, int height, int fps, int bitrate, boolean hardwareRotation, int rotation);`
Example:
```
//this is for resolution 640x480, 20 fps, 1200kb video bitrate, rotation with software and 0 rotation
if (rtmpBuilder.prepareAudio() && rtmpBuilder.prepareVideo(640, 480, 20, 1200 * 1024, false, 0)) {
        button.setText(getResources().getString(R.string.stop_button));
        rtmpBuilder.startStream(etUrl.getText().toString());
      } else {
        Toast.makeText(this, "Error preparing stream, This device cant do it", Toast.LENGTH_SHORT)
            .show();
}
```
With no params you are doing:
`prepareVideo(1280, 720, 1200 * 1024, false, 0);`
Camera2 can be use at the moment in rtsp stream but no in rtmp and dont work well. Anyway you need change builder for that.

**Comment by mattghall** [comment]
You are the most helpful person I've ever contacted on GitHub issues!

I was missing the parameters on prepareVideo(...) so that fixed the video issue. It might be helpful to add those parameters to your readme so future developers don't get stuck. For some reason the parameters for the function don't involve that boolean you have, so I'm calling  
```Java
rtmpBuilder.prepareAudio() && rtmpBuilder.prepareVideo(640,480,20,1200*1024,0)
```
in my if and that makes the video work.

Video works now, but I'm getting 
>java.lang.IllegalStateException: startRecording() called on an uninitialized AudioRecord

with detail message reading

>startRecording() called on an uninitialized AudioRecord.

I'm including 
```xml
   <uses-permission android:name="android.permission.RECORD_AUDIO" />
   <uses-permission android:name="android.permission.CAMERA" />
```
in my Manifest. Are there parameters I need to pass into prepareAudio as well or is there another step I'm missing?

Thanks again!

**Comment by mattghall** [comment]
Here's the full code
```Java
if (!rtmpBuilder.isStreaming()) {
            if(sStreamUrl == null || sStreamUrl == ""){
                Log.d(TAG,"Waiting to load stream from Facebook");
            }
            else if (rtmpBuilder.prepareAudio() && rtmpBuilder.prepareVideo(640,480,20,1200*1024,0)) {
                startStreamButton.setText(getResources().getString(R.string.stop_button));
                try {
                    rtmpBuilder.startStream(sStreamUrl);
                }
                catch (CameraOpenException coe){
                    Log.d(TAG,"RTMP ERROR: " + coe.getLocalizedMessage());
                    coe.printStackTrace();
                }
                catch (Exception e){
                    Log.d(TAG,"RTMP Exception");
                    Log.d(TAG, e.toString());
                    e.printStackTrace();
                }
            } else {
                Toast.makeText(this, "Error preparing stream, This device cant do it", Toast.LENGTH_SHORT)
                        .show();
            }
        } else {
            startStreamButton.setText(getResources().getString(R.string.start_button));
            rtmpBuilder.stopStream();
        }
```

**Comment by pedroSG94** [comment]
Readme updated. 
Issue closed, if you need more help open other issue.
