### ISSUE TITLE
how to replace gif or add .mov file with base scale

### ISSUE THREAD

**Issue by nikhilmzp** [pedroSG94/rtmp-rtsp-stream-client-java#901]
hello
i m fresher in android development  may i know how to replace gif with gif or .mov file 
with base scale like if resolution is set to 1280x720 then gif or mov is 1280x720

**Comment by pedroSG94** [comment]
I don't understand. What do you want exactly? Rescale a gif or surface filter?
You can set scale of filter with method setScale(x, y).
This method use percent of stream/preview resolution.
For example. If you stream with 1280x720 and you want set gif to 200x100:
```java
1280 -> 100%
200 -> x
x = 200 * 100 / 1280 = 15.625f

720 -> 100%
100 -> y
y = 100 * 100 / 720 = 13.888888889f
```

**Comment by nikhilmzp** [comment]
ok thnks 
can u tell where .gif file located and can we use .mov file insted of gif

**Comment by pedroSG94** [comment]
I located .gif and video files (.mov in your case .mp4 in my case) in raw folder:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/master/app/src/main/res/raw
If you want use a gif you can use this example:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/aed6232682c00bb511bad0f7e13c1425575d88e4/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L320
If you want use a video file use this one:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/aed6232682c00bb511bad0f7e13c1425575d88e4/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L268
Surface filter can handle any API that can render a surface so you can replace MediaPlayer with any player that you want, for example VLC

**Comment by nikhilmzp** [comment]
can i get your mail id rither

**Comment by pedroSG94** [comment]
You have email in my profile

**Comment by nikhilmzp** [comment]
that was wrong brother nikhilmzp.maac@gmail.com
