### ISSUE TITLE
orientation eroor in RTMP OpenGI

### ISSUE THREAD

**Issue by nikhilmzp** [pedroSG94/rtmp-rtsp-stream-client-java#904]
hey m trying to go live using rtmpopengl and got eroor of oriataion 
is there any way to fix it in landscape mode like 1280X720
720X480

**Comment by pedroSG94** [comment]
What do you mean with "error of orientation"?
can you share me an image with the fail and explain what do you want?

**Comment by nikhilmzp** [comment]
https://youtu.be/GnQsXy1lYMQ
please cheack this 
audio packet is also having some issue brother

**Comment by pedroSG94** [comment]
private video

**Comment by nikhilmzp** [comment]
sorry 
now see

**Comment by pedroSG94** [comment]
Did you set activity to landscape?
This feel that you are in portrait and then rotate device.
Change this to landscape and try again:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/AndroidManifest.xml#L94

**Comment by nikhilmzp** [comment]
thnks brother
