### ISSUE TITLE
Some devices only have a FPS of 30.

### ISSUE THREAD

**Issue by baehongjun0212** [pedroSG94/rtmp-rtsp-stream-client-java#905]
It's a camera that supports FPS 60, but the FPS is only printed up to 30.
![스크린샷 2021-07-07 오전 9 50 01](https://user-images.githubusercontent.com/55692618/124683872-06fee580-df09-11eb-96f0-cb2f510713b7.png)

input: 60
camera support fps: [120, 120], [240, 240], [60, 120], [30, 120], [60, 240], [30, 240]
output: 30

How can I print input fps 60 as it is?

code: 
`public class ViewLive extends Camera2Base {
    static String VIEW_LIVE_LIB = "VIEW_LIVE_VER_00.00.08";
    static String TAG = "say_ViewLive";
    static int MAX_FPS = 60; 

    protected CLRSCallback mCallback = null;
    private Sender mSender = null;
    private Context mContext;`

`@RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)
public class Camera2ApiManager extends CameraDevice.StateCallback {

    private final String TAG = "say_Camera2ApiManager";

    private CameraDevice cameraDevice;
    private SurfaceView surfaceView;
    private TextureView textureView;
    private Surface surfaceEncoder; //input surfaceEncoder from videoEncoder
    private CameraManager cameraManager;
    private Handler cameraHandler;
    private CameraCaptureSession cameraCaptureSession;
    private boolean prepared = false;
    private int cameraId = -1;
    private boolean isFrontCamera = false;
    private CaptureRequest.Builder builderInputSurface;
    private float fingerSpacing = 0;
    private float zoomLevel = 0f;
    private boolean lanternEnable = false;
    private boolean autoFocusEnabled = true;
    private boolean running = false;
    private int fps = 60;
    private final Semaphore semaphore = new Semaphore(0);

    public Camera2ApiManager(Context context) {
        cameraManager = (CameraManager) context.getSystemService(Context.CAMERA_SERVICE);
    }

    public void prepareCamera(SurfaceView surfaceView, Surface surface, int fps) {
        this.surfaceView = surfaceView;
        this.surfaceEncoder = surface;
        this.fps = fps;
        Log.d(TAG, "---- test input fps 0000 [ " + fps + " ]");
        prepared = true;
    }

    public void prepareCamera(TextureView textureView, Surface surface, int fps) {
        this.textureView = textureView;
        this.surfaceEncoder = surface;
        this.fps = fps;
        Log.d(TAG, "---- test input fps 1111 [ " + fps + " ]");
        prepared = true;
    }

    public void prepareCamera(Surface surface, int fps) {
        this.surfaceEncoder = surface;
        this.fps = fps;
        Log.d(TAG, "---- test input fps 2222 [ " + fps + " ]");
        prepared = true;
    }

    public void prepareCamera(SurfaceTexture surfaceTexture, int width, int height, int fps) {
        // 여기로 탈듯
        surfaceTexture.setDefaultBufferSize(width, height);
        this.surfaceEncoder = new Surface(surfaceTexture);
        this.fps = fps;
        Log.d(TAG, "---- test input fps 3333 [ " + fps + " ]");
        prepared = true;
    }

    public boolean isPrepared() {
        return prepared;
    }

    private void startPreview(CameraDevice cameraDevice) {
        try {

            final List<Surface> listSurfaces = new ArrayList<>();
            Surface preview = addPreviewSurface();
            if (preview != null) listSurfaces.add(preview);
            if (surfaceEncoder != preview && surfaceEncoder != null) listSurfaces.add(surfaceEncoder);

            cameraDevice.createCaptureSession(listSurfaces, new CameraCaptureSession.StateCallback() {
                @Override
                public void onConfigured(@NonNull CameraCaptureSession cameraCaptureSession) {
                    Camera2ApiManager.this.cameraCaptureSession = cameraCaptureSession;
                    try {
                        CaptureRequest captureRequest = drawSurface(listSurfaces);
                        if (captureRequest != null) {
                            cameraCaptureSession.setRepeatingRequest(captureRequest,null, cameraHandler);
                            ESayLog.Logi(TAG, () -> "Camera configured");
                        } else {
                            ESayLog.Logi(TAG, () ->"Error, captureRequest is null");
                            CLRSEventHandler.getInstance().sendEventMsg(CLRSErrors.CLRS_ERROR_CAPTURE_REQUEST,0);

                        }
                    } catch (CameraAccessException | NullPointerException e) {
                        ESayLog.Logi(TAG, () -> "Error :"  + e.toString() );
                        CLRSEventHandler.getInstance().sendEventMsg(CLRSErrors.CLRS_ERROR_CAPTURE_REQUEST,0);

                    } catch (IllegalStateException e) {
                        reOpenCamera(cameraId != -1 ? cameraId : 0);
                    }
                }

                @Override
                public void onConfigureFailed(@NonNull CameraCaptureSession cameraCaptureSession) {
                    cameraCaptureSession.close();
                    ESayLog.Logi(TAG, () -> "Configuration failed");
                    CLRSEventHandler.getInstance().sendEventMsg(CLRSErrors.CLRS_ERROR_CAPTURE_CONFIGURE_FAILD,0);
                }
            }, cameraHandler);
        } catch (CameraAccessException | IllegalArgumentException e) {
            CLRSEventHandler.getInstance().sendEventMsg(CLRSErrors.CLRS_ERROR_CAPTURE_BASE,0);
            ESayLog.Logi(TAG, () ->  "Error :"  + e.toString() );
        } catch (IllegalStateException e) {
            reOpenCamera(cameraId != -1 ? cameraId : 0);
        }
    }

    private Surface addPreviewSurface() {
        Surface surface = null;
        if (surfaceView != null) {
            surface = surfaceView.getHolder().getSurface();
        } else if (textureView != null) {
            final SurfaceTexture texture = textureView.getSurfaceTexture();
            surface = new Surface(texture);
        }
        return surface;
    }

    private CaptureRequest drawSurface(List<Surface> surfaces) {
        try {
            builderInputSurface = cameraDevice.createCaptureRequest(CameraDevice.TEMPLATE_PREVIEW);

            Range<Integer>[] fps2 = new Range[1];
            fps2[0] = Range.create(120,120);
            builderInputSurface.set(CaptureRequest.CONTROL_AE_TARGET_FPS_RANGE,fps2[0]);
            for (Surface surface : surfaces) if (surface != null) builderInputSurface.addTarget(surface);
//            adaptFpsRange(fps, builderInputSurface);
            return builderInputSurface.build();
        } catch (CameraAccessException | IllegalStateException e) {
            ESayLog.Logi(TAG, () -> "Error :"  + e.toString() );
            return null;
        }
    }

    private void adaptFpsRange(int expectedFps, CaptureRequest.Builder builderInputSurface) {
        Range<Integer>[] fpsRanges = getSupportedFps();

        if (fpsRanges != null && fpsRanges.length > 0) {
            Range<Integer> closestRange = fpsRanges[0];
            int measure = Math.abs(closestRange.getLower() - expectedFps) + Math.abs(
                    closestRange.getUpper() - expectedFps);
            for (Range<Integer> range : fpsRanges) {
                ESayLog.Logi(TAG, () -> "=======aaaa" + range.getLower() + "    " + range.getUpper() );
                if (range.getLower() <= expectedFps && range.getUpper() >= expectedFps) {
                    int curMeasure =
                            Math.abs(range.getLower() - expectedFps) + Math.abs(range.getUpper() - expectedFps);
                    if (curMeasure < measure) {
                        closestRange = range;
                        measure = curMeasure;
                    }
                }
                // ESayLog.Logi(TAG, () -> "=======aaaa" + (int)closestRange.getLower() + "    " + closestRange.getUpper() );
                Log.d(TAG,  "=======aaaaa2222222" + closestRange.getLower() + "    " + closestRange.getUpper() );
            }

            builderInputSurface.set(CaptureRequest.CONTROL_AE_TARGET_FPS_RANGE, closestRange);

        }

    }

    public Range<Integer>[] getSupportedFps() {
        try {
            CameraCharacteristics characteristics = getCameraCharacteristics();
            if (characteristics == null) return null;
            return characteristics.get(CameraCharacteristics.CONTROL_AE_AVAILABLE_TARGET_FPS_RANGES);
        } catch (IllegalStateException e) {
            ESayLog.Logi(TAG, () -> "Error :"  + e.toString() );
            return null;
        }
    }

    public int getLevelSupported() {
        try {
            CameraCharacteristics characteristics = getCameraCharacteristics();
            if (characteristics == null) return -1;
            Integer level = characteristics.get(CameraCharacteristics.INFO_SUPPORTED_HARDWARE_LEVEL);
            if (level == null) return -1;
            return level;
        } catch (IllegalStateException e) {
            ESayLog.Logi(TAG, () -> "Error :"  + e.toString() );
            return -1;
        }
    }

    public void openCamera() {
        openCameraBack();
    }

    public void openCameraBack() {
        openCameraFacing(Facing.BACK);
    }

    public void openCameraFront() {
        openCameraFacing(Facing.FRONT);
    }

    public void openLastCamera() {
        if (cameraId == -1) {
            openCameraBack();
        } else {
            openCameraId(cameraId);
        }
    }

    public Size[] getCameraResolutionsBack() {
        return getCameraResolutions(Facing.BACK);
    }

    public Size[] getCameraResolutionsFront() {
        return getCameraResolutions(Facing.FRONT);
    }

    public Size[] getCameraResolutions(Facing facing) {
        try {
            CameraCharacteristics characteristics = getCharacteristicsForFacing(cameraManager, facing);
            if (characteristics == null) {
                return new Size[0];
            }

            StreamConfigurationMap streamConfigurationMap =
                    characteristics.get(CameraCharacteristics.SCALER_STREAM_CONFIGURATION_MAP);
            if (streamConfigurationMap == null) return new Size[0];
            Size[] outputSizes = streamConfigurationMap.getOutputSizes(SurfaceTexture.class);
            return outputSizes != null ? outputSizes : new Size[0];
        } catch (CameraAccessException | NullPointerException e) {
            ESayLog.Logi(TAG, () -> "Error :"  + e.toString() );
            return new Size[0];
        }
    }

    public void _test_camera_fps()
    {
        Log.d(TAG, "-------- _test_camera_fps");
        try {
            CameraCharacteristics characteristics = getCameraCharacteristics();

            StreamConfigurationMap map = characteristics
                    .get(CameraCharacteristics.SCALER_STREAM_CONFIGURATION_MAP);

            for (Range<Integer> fpsRange : map.getHighSpeedVideoFpsRanges()) {
                Log.d(TAG, "-------- test openCamera: [width, height] = "+ fpsRange.toString());
            }
        } catch ( NullPointerException e) {
            ESayLog.Logi(TAG, () -> "Error :"  + e.toString() );
            return ;
        }
    }

    @Nullable
    public CameraCharacteristics getCameraCharacteristics() {
        try {
            return cameraId != -1 ? cameraManager.getCameraCharacteristics(String.valueOf(cameraId))
                    : null;
        } catch (CameraAccessException e) {
            ESayLog.Logi(TAG, () ->  "Error :"  + e.toString() );
            return null;
        }
    }

    /**
     * Select camera facing
     *
     * @param selectedCameraFacing - CameraCharacteristics.LENS_FACING_FRONT,
     * CameraCharacteristics.LENS_FACING_BACK,
     * CameraCharacteristics.LENS_FACING_EXTERNAL
     */
    public void openCameraFacing(Facing selectedCameraFacing) {
        try {
            String cameraId = getCameraIdForFacing(cameraManager, selectedCameraFacing);
            if (cameraId != null) {
                openCameraId(Integer.valueOf(cameraId));
            } else {
                ESayLog.Logi(TAG, () -> "Camera not supported"); // TODO maybe we want to throw some exception here?
                CLRSEventHandler.getInstance().sendEventMsg(CLRSErrors.CLRS_ERROR_CAMERA,0);

            }
        } catch (CameraAccessException e) {
            ESayLog.Logi(TAG, () ->  "Error :"  + e.toString() );
            CLRSEventHandler.getInstance().sendEventMsg(CLRSErrors.CLRS_ERROR_CAMERA, 0);
        }
    }

    public boolean isLanternSupported() {
        CameraCharacteristics characteristics = getCameraCharacteristics();
        if (characteristics == null) return false;
        Boolean available = characteristics.get(CameraCharacteristics.FLASH_INFO_AVAILABLE);
        if (available == null) return false;
        return available;
    }

    public boolean isLanternEnabled() {
        return lanternEnable;
    }

    /**
     * @required: <uses-permission android:name="android.permission.FLASHLIGHT"/>
     */
    public void enableLantern() throws Exception {
        CameraCharacteristics characteristics = getCameraCharacteristics();
        if (characteristics == null) return;
        Boolean available = characteristics.get(CameraCharacteristics.FLASH_INFO_AVAILABLE);
        if (available == null) return;
        if (available) {
            if (builderInputSurface != null) {
                try {
                    builderInputSurface.set(CaptureRequest.FLASH_MODE, CameraMetadata.FLASH_MODE_TORCH);
                    cameraCaptureSession.setRepeatingRequest(builderInputSurface.build(), null, null);
                    lanternEnable = true;
                } catch (Exception e) {
                    ESayLog.Logi(TAG, () -> "Error :"  + e.toString() );
                }
            }
        } else {
            ESayLog.Logi(TAG, () -> "Lantern unsupported");
            throw new Exception("Lantern unsupported");
        }
    }

    /**
     * @required: <uses-permission android:name="android.permission.FLASHLIGHT"/>
     */
    public void disableLantern() {
        CameraCharacteristics characteristics = getCameraCharacteristics();
        if (characteristics == null) return;
        Boolean available = characteristics.get(CameraCharacteristics.FLASH_INFO_AVAILABLE);
        if (available == null) return;
        if (available) {
            if (builderInputSurface != null) {
                try {
                    builderInputSurface.set(CaptureRequest.FLASH_MODE, CameraMetadata.FLASH_MODE_OFF);
                    cameraCaptureSession.setRepeatingRequest(builderInputSurface.build(), null, null);
                    lanternEnable = false;
                } catch (Exception e) {
                    ESayLog.Logi(TAG, () -> "Error :"  + e.toString() );
                }
            }
        }
    }

    public void enableAutoFocus() {
        CameraCharacteristics characteristics = getCameraCharacteristics();
        if (characteristics == null) return;
        int[] supportedFocusModes =
                characteristics.get(CameraCharacteristics.CONTROL_AF_AVAILABLE_MODES);
        if (supportedFocusModes != null) {
            List<Integer> focusModesList = new ArrayList<>();
            for (int i : supportedFocusModes) focusModesList.add(i);
            if (builderInputSurface != null) {
                try {
                    if (focusModesList.contains(CaptureRequest.CONTROL_AF_MODE_CONTINUOUS_PICTURE)) {
                        builderInputSurface.set(CaptureRequest.CONTROL_AF_MODE,
                                CaptureRequest.CONTROL_AF_MODE_CONTINUOUS_PICTURE);
                        cameraCaptureSession.setRepeatingRequest(builderInputSurface.build(), null, null);
                        autoFocusEnabled = true;
                    } else if (focusModesList.contains(CaptureRequest.CONTROL_AF_MODE_AUTO)) {
                        builderInputSurface.set(CaptureRequest.CONTROL_AF_MODE,
                                CaptureRequest.CONTROL_AF_MODE_AUTO);
                        cameraCaptureSession.setRepeatingRequest(builderInputSurface.build(), null, null);
                        autoFocusEnabled = true;
                    }
                } catch (Exception e) {
                    ESayLog.Logi(TAG, () -> "Error :"  + e.toString() );
                }
            }
        }
    }

    public void disableAutoFocus() {
        CameraCharacteristics characteristics = getCameraCharacteristics();
        if (characteristics == null) return;
        int[] supportedFocusModes =
                characteristics.get(CameraCharacteristics.CONTROL_AF_AVAILABLE_MODES);
        if (supportedFocusModes != null) {
            if (builderInputSurface != null) {
                for (int mode : supportedFocusModes) {
                    try {
                        if (mode == CaptureRequest.CONTROL_AF_MODE_OFF) {
                            builderInputSurface.set(CaptureRequest.CONTROL_AF_MODE,
                                    CaptureRequest.CONTROL_AF_MODE_OFF);
                            cameraCaptureSession.setRepeatingRequest(builderInputSurface.build(), null, null);
                            autoFocusEnabled = false;
                            return;
                        }
                    } catch (Exception e) {
                        ESayLog.Logi(TAG, () -> "Error :"  + e.toString() );
                    }
                }
            }
        }
    }

    public boolean isAutoFocusEnabled() {
        return autoFocusEnabled;
    }

    private void prepareFaceDetectionCallback() {
        try {
            cameraCaptureSession.stopRepeating();
            cameraCaptureSession.setRepeatingRequest(builderInputSurface.build(), null, null);
        } catch (CameraAccessException e) {
            ESayLog.Logi(TAG, () -> "Error :"  + e.toString() );
        }
    }

    @SuppressLint("MissingPermission")
    public void openCameraId(Integer cameraId) {
        this.cameraId = cameraId;
        _test_camera_fps();
        if (prepared) {
            HandlerThread cameraHandlerThread = new HandlerThread(TAG + " Id = " + cameraId);
            cameraHandlerThread.start();
            cameraHandler = new Handler(cameraHandlerThread.getLooper());
            try {
                cameraManager.openCamera(cameraId.toString(), this, cameraHandler);

                semaphore.acquireUninterruptibly();
                CameraCharacteristics cameraCharacteristics =
                        cameraManager.getCameraCharacteristics(Integer.toString(cameraId));
                running = true;
                Integer facing = cameraCharacteristics.get(CameraCharacteristics.LENS_FACING);
                if (facing == null) return;
                isFrontCamera = LENS_FACING_FRONT == facing;
            } catch (CameraAccessException | SecurityException e) {
                ESayLog.Logi(TAG, () -> "Error :"  + e.toString() );
                CLRSEventHandler.getInstance().sendEventMsg(CLRSErrors.CLRS_ERROR_CAMERA,0);
            }
        } else {
            ESayLog.Logi(TAG, () -> "Camera2ApiManager need be prepared, Camera2ApiManager not enabled");
        }
    }

    public boolean isRunning() {
        return running;
    }

    public void switchCamera() {
        try {
            String cameraId;
            if (cameraDevice == null || isFrontCamera) {
                cameraId = getCameraIdForFacing(cameraManager, Facing.BACK);
            } else {
                cameraId = getCameraIdForFacing(cameraManager, Facing.FRONT);
            }
            if (cameraId == null) cameraId = "0";
            reOpenCamera(Integer.parseInt(cameraId));
        } catch (CameraAccessException e) {
            ESayLog.Logi(TAG, () -> "Error :"  + e.toString() );
            CLRSEventHandler.getInstance().sendEventMsg(CLRSErrors.CLRS_ERROR_CAMERA,0);
        }
    }

    private void reOpenCamera(int cameraId) {
        if (cameraDevice != null) {
            closeCamera(false);
            if (textureView != null) {
                prepareCamera(textureView, surfaceEncoder, fps);
            } else if (surfaceView != null) {
                prepareCamera(surfaceView, surfaceEncoder, fps);
            } else {
                prepareCamera(surfaceEncoder, fps);
            }
            openCameraId(cameraId);

            _test_camera_fps();
        }
    }

    public float getMaxZoom() {
        CameraCharacteristics characteristics = getCameraCharacteristics();
        if (characteristics == null) return 1;
        Float maxZoom = characteristics.get(CameraCharacteristics.SCALER_AVAILABLE_MAX_DIGITAL_ZOOM);
        if (maxZoom == null) return 1;
        return maxZoom;
    }

    public Float getZoom() {
        return zoomLevel;
    }

    public void setZoom(float level) {
        try {
            float maxZoom = getMaxZoom();
            //Avoid out range level
            if (level <= 0f) {
                level = 0.01f;
            } else if (level > maxZoom) level = maxZoom;

            CameraCharacteristics characteristics = getCameraCharacteristics();
            if (characteristics == null) return;
            Rect rect = characteristics.get(CameraCharacteristics.SENSOR_INFO_ACTIVE_ARRAY_SIZE);
            if (rect == null) return;
            //This ratio is the ratio of cropped Rect to Camera's original(Maximum) Rect
            float ratio = 1f / level;
            //croppedWidth and croppedHeight are the pixels cropped away, not pixels after cropped
            int croppedWidth = rect.width() - Math.round((float) rect.width() * ratio);
            int croppedHeight = rect.height() - Math.round((float) rect.height() * ratio);
            //Finally, zoom represents the zoomed visible area
            Rect zoom = new Rect(croppedWidth / 2, croppedHeight / 2, rect.width() - croppedWidth / 2,
                    rect.height() - croppedHeight / 2);
            builderInputSurface.set(CaptureRequest.SCALER_CROP_REGION, zoom);
            cameraCaptureSession.setRepeatingRequest(builderInputSurface.build(), null, null);
            zoomLevel = level;
        } catch (CameraAccessException e) {
            ESayLog.Logi(TAG, () -> "Error :"  + e.toString() );
        }
    }

    public void setZoom(MotionEvent event) {
        float currentFingerSpacing;
        if (event.getPointerCount() > 1) {
            currentFingerSpacing = getFingerSpacing(event);
            float delta = 0.1f;
            float maxZoom = getMaxZoom();
            if (fingerSpacing != 0) {
                float newLevel = zoomLevel;
                if (currentFingerSpacing > fingerSpacing) { //Don't over zoom-in
                    if ((maxZoom - zoomLevel) <= delta) {
                        delta = maxZoom - zoomLevel;
                    }
                    newLevel += delta;
                } else if (currentFingerSpacing < fingerSpacing) { //Don't over zoom-out
                    if ((zoomLevel - delta) < 1f) {
                        delta = zoomLevel - 1f;
                    }
                    newLevel -= delta;
                }
                setZoom(newLevel);
            }
            fingerSpacing = currentFingerSpacing;
        }
    }

    public boolean isFrontCamera() {
        return isFrontCamera;
    }

    private void resetCameraValues() {
        lanternEnable = false;
        zoomLevel = 1.0f;
    }

    public void stopRepeatingEncoder() {
        if (cameraCaptureSession != null) {
            try {
                cameraCaptureSession.stopRepeating();
                surfaceEncoder = null;
                Surface preview = addPreviewSurface();
                if (preview != null) {
                    CaptureRequest captureRequest = drawSurface(Collections.singletonList(preview));
                    if (captureRequest != null) {
                        cameraCaptureSession.setRepeatingRequest(captureRequest, null, cameraHandler);
                    }
                } else {
                    ESayLog.Logi(TAG, () -> "preview surface is null");
                }
            } catch (CameraAccessException | IllegalStateException e) {
                ESayLog.Logi(TAG, () ->  "Error :"  + e.toString() );
            }
        }
    }

    public void closeCamera() {
        closeCamera(true);
    }

    public void closeCamera(boolean resetSurface) {
        resetCameraValues();
        if (cameraCaptureSession != null) {
            cameraCaptureSession.close();
            cameraCaptureSession = null;
        }
        if (cameraDevice != null) {
            cameraDevice.close();
            cameraDevice = null;
        }
        if (cameraHandler != null) {
            cameraHandler.getLooper().quitSafely();
            cameraHandler = null;
        }
        if (resetSurface) {
            surfaceEncoder = null;
            builderInputSurface = null;
        }
        prepared = false;
        running = false;
        ESayLog.Logi(TAG, () ->"Camera closed");
    }

    @Override
    public void onOpened(@NonNull CameraDevice cameraDevice) {
        this.cameraDevice = cameraDevice;
        startPreview(cameraDevice);
        semaphore.release();
        ESayLog.Logi(TAG, () -> "Camera opened");
    }

    @Override
    public void onDisconnected(@NonNull CameraDevice cameraDevice) {
        cameraDevice.close();
        semaphore.release();
        ESayLog.Logi(TAG, () -> "Camera disconnected");
    }

    @Override
    public void onError(@NonNull CameraDevice cameraDevice, int i) {
        cameraDevice.close();
        semaphore.release();
        CLRSEventHandler.getInstance().sendEventMsg(CLRSErrors.CLRS_ERROR_CAPTURE_BASE,0);
        ESayLog.Logi(TAG, () -> "Open failed : " + i);
    }

    @Nullable
    private String getCameraIdForFacing(CameraManager cameraManager, CameraHelper.Facing facing)
            throws CameraAccessException {
        int selectedFacing = getFacing(facing);
        for (String cameraId : cameraManager.getCameraIdList()) {
            Integer cameraFacing =
                    cameraManager.getCameraCharacteristics(cameraId).get(CameraCharacteristics.LENS_FACING);
            if (cameraFacing != null && cameraFacing == selectedFacing) {
                return cameraId;
            }
        }
        return null;
    }

    @Nullable
    private CameraCharacteristics getCharacteristicsForFacing(CameraManager cameraManager,
                                                              CameraHelper.Facing facing) throws CameraAccessException {
        String cameraId = getCameraIdForFacing(cameraManager, facing);
        return cameraId != null ? cameraManager.getCameraCharacteristics(cameraId) : null;
    }

    private static int getFacing(CameraHelper.Facing facing) {
        return facing == CameraHelper.Facing.BACK ? CameraMetadata.LENS_FACING_BACK
                : CameraMetadata.LENS_FACING_FRONT;
    }
}`

**Comment by pedroSG94** [comment]
Your fps support are in slow motion mode.
I'm not able to render in slow motion so it is not a valid fps support for this library. You must get 60fps from this method:
```java
//must be called after startPreview
for (Range<Integer> r: rtmpCamera2.getSupportedFps()) {
      Log.e("Pedro", r.getLower() + "-" + r.getUpper());
}
```

**Comment by baehongjun0212** [comment]
![스크린샷 2021-07-08 오후 2 27 11](https://user-images.githubusercontent.com/55692618/124867229-a6e76c80-dff8-11eb-9622-b18851ee45fe.png)

The device's camera clearly supports 60 frames, and the log comes out like this.

How do I fix this?

**Comment by baehongjun0212** [comment]
<img width="978" alt="S21 60 지원하는데 이상하게뜸 Fps" src="https://user-images.githubusercontent.com/55692618/124872355-20cf2400-e000-11eb-956e-1448b75616e9.png">


It is a device that outputs the FPS 60.
However, the supported fps range is [15, 15] [15, 20] [20, 20] [24, 24] [8, 30] [10, 30] [15, 30] [30, 30].

What's going on?

**Comment by pedroSG94** [comment]
I don't understand your logs.
Which device is the first log and which one the second log? (specify device model of each log)
Are you using my Camera2ApiManager without modifications?

Try call getSupportedFps after start getting frames in OpenGlViewBase because this could be related with resolution/camera selected
