### ISSUE TITLE
Queue Full

### ISSUE THREAD

**Issue by mateidediu93** [pedroSG94/rtmp-rtsp-stream-client-java#91]
Hello,

When streaming from low-end phones, no matter the resolution, bitrate or fps given, an IllegalStateException is thrown due to the queue being full:
 **(I/VideoEncoder: Queue full frame discarded**)

The video skips frames resulting in a faulty and on some devices, an unwatchable stream. Also, ocasionally, this occurs even on better devices like Samsung Galaxy J5 after a long period of time streaming.
The tests were done on Samsung Note 2 (frames skipped, around 10 FPS while streaming), Samsung Galaxy J1 2017 (constant 4 FPS, unwatchable stream), Motorola Nexus 6 (frames skipped, around 12-14 FPS while streaming). I'm using RTMPCamera1 with 640x480 or 1280x720 resolution, 25 FPS and 2mbps bitrate.
Do you have any solution or idea of a fix to solve this? Is it an expected behaviour?  

By the way, you have developed a great library!
Thank you,
Matei

**Comment by pedroSG94** [comment]
Yes, I know this problem but I only see that on a xiaomi redmi and If I use 1920x1080 but work fine on 1280x720.
For now you can set a video bitrate more low. This will reduce buffer size and do the stream more fluid.
You can use openglview that draw in a surface or camera2 object that will reduce buffers used and could be more efficient.

**Comment by mateidediu93** [comment]
Yes, only in the VideoEncoder class. I tried now with openGlView and lowering the bitrate to 0.9 mbps and still happens on Samsung Galaxy J5. I will try also with Camera2 and let you know how it goes.

Thank you,
Matei

**Comment by pedroSG94** [comment]
I create a branch with a change in the VideoEncoder and Camera1ApiManager classes to optimizate it.
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/optimizationtest
Can you do a test to know if you get more fps?
Maybe you will see now frame discarted on SrsFlvMuxer class.

**Comment by mateidediu93** [comment]
Sorry for the late response. I have tested your change and the queue full (frame discarded) problem hasn't appeared anymore which is good, but the average FPS on most of the devices have dropped:
Samsung J5: 14-16 FPS - before was 22-25
Samsung Note5: 22-30 FPS - before was 25-30
Samsung S7: 22-26 FPS - before was 30
Samsung J1: constant 1 FPS - before was 1-4 
Motorola Nexus 6: 10-14 FPS - before was approximately the same.

Thank you,
Matei

**Comment by pedroSG94** [comment]
I did a little change that got 4 fps more on my S7.
I will try optimize it more this week. For now if you select rotation to 0 you will get more fps than with other rotation. Note: If you use frontal camera you are rotating 180

**Comment by mateidediu93** [comment]
I have replaced surfaceview with openglview and on S7 i have 26-30 FPS, on J5 26-30, on Motorola Nexus 6 13-15 but on J1 I have 1-2 FPS and frames are still discarded. The J1 is the only device I have that behaves like this, I will analyse more on some old tablets and see if they behave the same. (I'm starting to think that the phone is just too weak for this kind of processing).

**Comment by pedroSG94** [comment]
If I set prepareVideo(1920, 1080, 30, 5000 * 1024, false, 90) with Samsung S7 30 fps and Nexus7 (tablet) 29fps. I'm using a local server.
If you see frames discarded on SrsFlvMuxer normally this is because you generate packets more fast than you can send. I start believe that the problem is network card.
J1 2017 case is so rare. With that device you should have more fps in 640x480 resolution.

**Comment by mateidediu93** [comment]
Ran the new android profiler and found out that the bottleneck is at the frame rotation functions. On old or low-end phones it's too heavy to process, so frames are filling in the other queues. I'm working on implementing the libyuv library and the first results seem promising. You can mark this issue as closed since it's device specific. Thank you again for you support
