### ISSUE TITLE
Is there any problem including the rtsp server library with this library?

### ISSUE THREAD

**Issue by ToysoftInc** [pedroSG94/rtmp-rtsp-stream-client-java#913]
In my project I have this lib and included the rtsp server project.
Now I **can no**t stream to Youtube.  I went back to my previous branch before including the rtsp server lib and streaming works.

Just wondering.

Thanks

**Comment by pedroSG94** [comment]
I did an update for rtsp server, try with last update and report me if the error persist

**Comment by ToysoftInc** [comment]
sorry still not getting any data from Youtube.  In my app it is sending all the packets.

**Comment by ToysoftInc** [comment]
Update: I was able to get it work using library version 2.0.2.
Anything newer will not work. 
FYI, I have subclass some of the classes in the library which I can not update to latest version.
I'm just happy that I can have both rtmp and rtsp server in the same app.
