### ISSUE TITLE
How to rotate video 90 degrees in Portrait mode?

### ISSUE THREAD

**Issue by ToysoftInc** [pedroSG94/rtmp-rtsp-stream-client-java#914]
Problem:  My app is set to portrait mode (A MUST) and I want to rotate the video 90 degrees or any degrees.

Tried:  I have set RotationFilterRender() which rotates the video but it does not keep the aspect ratio.

Basically I need to fit portrait in landscape.

**Comment by pedroSG94** [comment]
I don't fully understand you but you have 3 ways of rotate stream:
- Set rotation in startPreview and/or prepareVideo
- Using RotationFilterRender
- Flip horizontally and vertically in openglview with setCameraFlip
Can you share me an orientative image to understand your actual case and desired case?

**Comment by ToysoftInc** [comment]
Here is an example 

https://drive.google.com/file/d/1OnczhwgiUhFAd1-W7jh9b9LI2VdaduNh/view?usp=sharing

The camera preview is showing in "landscape" in Portrait mode. 

How can I rotate the preview to show in correct orientation? Will flipping just "mirroring" correct? I need to physically rotate 90 degrees in the test pic.

**Comment by ToysoftInc** [comment]
I tested the rotate filter in the sample app.  It works but the output is stretched to fit the entire view.  Is there any way to keep the aspect ratio when rotated?

**Comment by pedroSG94** [comment]
Sorry for late response. I'm on holydays so It could take a bit to response but I will check it

**Comment by pedroSG94** [comment]
I'm working on it. After check it the aspect ratio issue with rotation filter is normal because you are rotating a 16:9 image to 9:16.

We should fix the problem using:
- Set rotation in startPreview and/or prepareVideo
- Flip horizontally and vertically in openglview with setCameraFlip

Which device are you using? Can you reproduce this problem in my app example?

**Comment by ToysoftInc** [comment]
HI

I have a unique custom hardware base on the Samsung S20.
The camera is rotated landscape so when in Portrait mode it is oriented to the right. (shown in landscape) The preview looks like this

       camera facing (must be in portrait)
           ||
           V
|==============|
|                                   |
|                                   |
|                                   |
|                                   | ===> orientated
|                                   |
|                                   |
|                                   |
|==============|

I need to rotate the preview so it will display properly in Portrait.  I can not set the orientation to landscape.

In sample all when I use the rotate filter it does rotate to 90 degrees but the image stretches and takes up the entire screen.  It does not keep the aspect ratio.  I'm ok if there are black bars on the top and bottom to maintain the aspect ratio.

Hope this helps.   thanks

**Comment by ToysoftInc** [comment]
Here is what i'm doing.

1.  The phone that I have  I need to rotate the preview 270 degrees.
2.  The preview is stretch taking up the entire view which does not retain the aspect ratio
3.  When viewing on Youtube the video is also stretched

Can you give me some suggestions or are you able to update the rotate filter?

I have tried making the camera preview and layout 1:1 square but then I get an error when opening the camera with unsupported resolution. I'm happy if I can just get the 1:1 working.

**Comment by pedroSG94** [comment]
I will check it again.
Currently it is really confuse to implement because it is a hardware problem than send image rotated without any way to check the correct orientation to fix it.

Since RotationFilter is working as exptected I will try create a new filter

**Comment by ToysoftInc** [comment]
You are correct the Rotate filter works correctly but it would be nice if there is an option to maintain the aspect ratio.
Is there a possible option to stream a 1:1 resolution like 720x720 or 1080x1080?

**Comment by pedroSG94** [comment]
Try with camera2 in few devices you can open any resolution.
Also you can check all resolution supported using:
```java
rtmpCamera1.getResolutionsBack();
rtmpCamera1.getResolutionsFront();
```

**Comment by pedroSG94** [comment]
Set keepAspectRatio disabled in OpenGlView and try use this filter:

```java
@RequiresApi(api = Build.VERSION_CODES.JELLY_BEAN_MR2)
public class RotationFixedFilterRender extends BaseFilterRender {

  //rotation matrix
  private final float[] squareVertexDataFilter = {
      // X, Y, Z, U, V
      -1f, -1f, 0f, 0f, 0f, //bottom left
      1f, -1f, 0f, 1f, 0f, //bottom right
      -1f, 1f, 0f, 0f, 1f, //top left
      1f, 1f, 0f, 1f, 1f, //top right
  };

  private int program = -1;
  private int aPositionHandle = -1;
  private int aTextureHandle = -1;
  private int uMVPMatrixHandle = -1;
  private int uSTMatrixHandle = -1;
  private int uSamplerHandle = -1;

  private int rotation = 0;
  private float[] rotationMatrix = new float[16];

  public RotationFixedFilterRender() {
    squareVertex = ByteBuffer.allocateDirect(squareVertexDataFilter.length * FLOAT_SIZE_BYTES)
        .order(ByteOrder.nativeOrder())
        .asFloatBuffer();
    squareVertex.put(squareVertexDataFilter).position(0);
    Matrix.setIdentityM(MVPMatrix, 0);
    Matrix.setIdentityM(STMatrix, 0);
    Matrix.setIdentityM(rotationMatrix, 0);
  }

  @Override
  protected void initGlFilter(Context context) {
    String vertexShader = GlUtil.getStringFromRaw(context, R.raw.simple_vertex);
    String fragmentShader = GlUtil.getStringFromRaw(context, R.raw.simple_fragment);

    program = GlUtil.createProgram(vertexShader, fragmentShader);
    aPositionHandle = GLES20.glGetAttribLocation(program, "aPosition");
    aTextureHandle = GLES20.glGetAttribLocation(program, "aTextureCoord");
    uMVPMatrixHandle = GLES20.glGetUniformLocation(program, "uMVPMatrix");
    uSTMatrixHandle = GLES20.glGetUniformLocation(program, "uSTMatrix");
    uSamplerHandle = GLES20.glGetUniformLocation(program, "uSampler");
  }

  @Override
  protected void drawFilter() {
    GLES20.glClearColor(0.0f, 0.0f, 0.0f, 1.0f);
    GLES20.glClear(GLES20.GL_DEPTH_BUFFER_BIT | GLES20.GL_COLOR_BUFFER_BIT);

    SizeCalculator.calculateViewPort(true, 0, getHeight(), getWidth(), getPreviewHeight(),
        getPreviewWidth());

    GLES20.glUseProgram(program);

    squareVertex.position(SQUARE_VERTEX_DATA_POS_OFFSET);
    GLES20.glVertexAttribPointer(aPositionHandle, 3, GLES20.GL_FLOAT, false,
        SQUARE_VERTEX_DATA_STRIDE_BYTES, squareVertex);
    GLES20.glEnableVertexAttribArray(aPositionHandle);

    squareVertex.position(SQUARE_VERTEX_DATA_UV_OFFSET);
    GLES20.glVertexAttribPointer(aTextureHandle, 2, GLES20.GL_FLOAT, false,
        SQUARE_VERTEX_DATA_STRIDE_BYTES, squareVertex);
    GLES20.glEnableVertexAttribArray(aTextureHandle);

    GLES20.glUniformMatrix4fv(uMVPMatrixHandle, 1, false, MVPMatrix, 0);
    GLES20.glUniformMatrix4fv(uSTMatrixHandle, 1, false, STMatrix, 0);

    GLES20.glUniform1i(uSamplerHandle, 4);
    GLES20.glActiveTexture(GLES20.GL_TEXTURE4);
    GLES20.glBindTexture(GLES20.GL_TEXTURE_2D, previousTexId);
  }

  @Override
  public void release() {
    GLES20.glDeleteProgram(program);
  }

  public int getRotation() {
    return rotation;
  }

  public void setRotation(int rotation) {
    this.rotation = rotation;
    //Set rotation
    Matrix.setRotateM(rotationMatrix, 0, rotation, 0, 0, 1.0f);
    //Translation
    Matrix.translateM(rotationMatrix, 0, 0f, 0.25f, 0f);
    // Combine the rotation matrix with the projection and camera view
    Matrix.multiplyMM(MVPMatrix, 0, rotationMatrix, 0, MVPMatrix, 0);
  }
}

```

**Comment by ToysoftInc** [comment]
thank you. I will try this weekend.

**Comment by ToysoftInc** [comment]
Rotation now keeps the aspect ratio with the new filter.  The video is now half of the screen and it shows at the bottom half.  Is there any way to center the video or make it on the top? thanks

**Comment by ToysoftInc** [comment]
Thanks. I have tried your suggestions and the new fix.  The video is now centered but the aspect ratio is still not 100%.  The video still appears stretched.  The filter RotationFixedFilterRender code above the aspect ratio is correct.

I did set the aspectRatio in the xml.

**Comment by pedroSG94** [comment]
Hello,

It is working fine for me with 640x480 and 1280x720
Which resolution are you using?
Did you set resolution as explained in my last post?

Anyway you can adjust it using only this value:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/gl/render/filters/RotationFilterRender.java#L119

Value range is 0f to 1f. You can modify it to produce exactly the aspect ratio as you want.
