### ISSUE TITLE
Wrong message length when read multiple chunk

### ISSUE THREAD

**Issue by XuanTung95** [pedroSG94/rtmp-rtsp-stream-client-java#921]
I tested this library with OvenMediaEngine and see that it parse the wrong RTMP command input in case of multiple chunk.

- The data sent from server (total 259 + 2 bytes):
 `128 bytes + (1 byte (-61)) + 128 bytes + (1 byte (-61)) + 3 bytes`
- 128 is the chunk length, (-61) is the byte between 2 chunk.
- Length of data only: 259
- The messageLength in the header: 259 (2 chunk bytes is not included)
 
But the current implementation of this method treats 259 as data length + chunk bytes.
```
    private fun getInputWithoutChunks(input: InputStream, header: RtmpHeader, chunkSize: Int,
      commandSessionHistory: CommandSessionHistory): InputStream {
      val packetStore = ByteArrayOutputStream()
      var bytesRead = 0
      while (bytesRead < header.messageLength) {
        var chunk: ByteArray
        if (header.messageLength - bytesRead < chunkSize) {
          //last chunk
          chunk = ByteArray(header.messageLength - (bytesRead - 1))  // <-- here
          input.readUntil(chunk)
        } else {
          chunk = ByteArray(chunkSize)
          input.readUntil(chunk)
          //skip chunk header to discard it, set packet ts to indicate if you need read extended ts
          RtmpHeader.readHeader(input, commandSessionHistory, header.timeStamp)
          bytesRead++
        }
        bytesRead += chunk.size // <-- and here
        packetStore.write(chunk)
      }
      return ByteArrayInputStream(packetStore.toByteArray())
    }
```

So 1 byte at the end is missing.

Should header.messageLength include chunk bytes or it's bug of the client library?

**Comment by pedroSG94** [comment]
Which command is wrong?
Can you share me a logcat?

Can you tell me how to configure server to reproduce your case?

**Comment by XuanTung95** [comment]
Command "_result" is wrong.
To set up the server, you can use docker as https://airensoft.gitbook.io/ovenmediaengine/getting-started
There is nothing much in the logcat.
Because 1 byte is missing, it cannot find the AmfObjectEnd so it jump to an infinite loop.

**Comment by pedroSG94** [comment]
I did a commit for it:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/d11357e62ebd8d2bf28d0992ec4f8c055caadbb8
I tested using OvenMediaEngine docker and it is working for me. Let me know if this commit resolve your problema dn I will update library version

**Comment by XuanTung95** [comment]
The chunk problem is resolved.
But can you stream successfully?
Because I face other problem related to encoder/h264 profile... (I'm not sure) not supported by server.

**Comment by pedroSG94** [comment]
The server output (reproduce stream in a player) is not working for me with ffmpeg, OBS or my library. So I think this is server error. 

So much coincidence that OBS and ffmpeg is not working well.

**Comment by XuanTung95** [comment]
For me OBS and ffmpeg work.

- ffmpeg:

`ffmpeg -re -i ./input.mp4  -loglevel verbose -b:v 6M -maxrate 8M -bufsize 8M -g 24 -pix_fmt yuv420p -c:a aac -pes_payload_size 0 -vcodec libx264 -forced-idr 1 -g 24 -profile:v main -f flv rtmp:127.0.0.1/app/stream`

- OBS: you can follow the setting here https://airensoft.gitbook.io/ovenmediaengine/getting-started

I think oven support h264 aac and not high profile.
There is a issue here https://github.com/AirenSoft/OvenMediaEngine/issues/467

**Comment by pedroSG94** [comment]
After few tests with your recommended command. I could find that the problem is not related with video profile.
I'm using a video with high profile and it is working with this command:
```
ffmpeg -re -i ./BigBuckBunny.mp4 -c:a aac -vcodec libx264 -f flv rtmp://127.0.0.1/app/stream
```
Also, I tried set main profile in my library without luck.
I need investigate more about it

**Comment by XuanTung95** [comment]
Oven is open source so I can check the source code but I don't have knowledge about video codec so I'm not sure what's wrong.
And It's true that BigBuckBunny.mp4 don't need to change profile but other movie files need.

**Comment by pedroSG94** [comment]
I don't know the reason so I think we should open an issue in github server and wait for a response to know where is the fail.
If it is a fail in my library I can fix it after know the possible reason.

meanwhile I can continue with test to try find the reason

**Comment by pedroSG94** [comment]
I tested with 2 streaming android apps: Larix Broadcaster and OvenStreamEncoder (You can download both apps in the play store totally free if you want test it).
The first one is maybe one of the most knowned streaming platform

Neither works. This is really suspecious for me that the app provided by OvenMediaEngine is not working. I will do my last try to find the error tomorrow and write an issue.

This really seem a server error that fail in few configuration because ffmpeg and OBS is not working if you don't configure stream in a special way.

**Comment by pedroSG94** [comment]
I opened an issue in OvenMediaEngine github:
https://github.com/AirenSoft/OvenMediaEngine/issues/476

I will wait for feedback.

**Comment by pedroSG94** [comment]
Finally solved:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/cf24d534a87f50f9dc37dd9e59c272f339fddc3b

Test it and let me know if works for you

**Comment by XuanTung95** [comment]
Thank for the fix.
It worked ❤️
I close this ticket.
