### ISSUE TITLE
The noise of audio is amplified during the stream to IVS AWS server.

### ISSUE THREAD

**Issue by ntqp97** [pedroSG94/rtmp-rtsp-stream-client-java#930]
When I broadcast to the IVS AWS server. The noise of audio is amplified. Below is the audio for this problem during the live stream.
Link: https://drive.google.com/file/d/19D6YcB8Q2w3rx9hfhM2OjG-iT7wL8HAr/view?usp=sharing

Please help me!

**Comment by pedroSG94** [comment]
Hello,

I did an account in IVS AWS and all is working totally fine in my 2 devices (Samsung S7 and Oneplus 7T).
This feel like you are capturing audio from player with your device producing audio coupling.

**Comment by JDBae** [comment]
please explain what it meaning ?
This feel like you are capturing audio from player with your device producing audio coupling.

**Comment by pedroSG94** [comment]
This is like a normal audio call, when you have both devices (device that reproduce audio and device that send audio) close, this produce a noise because the audio is in loop between both devices.
In this case, your player (reproduce audio) and your phone that stream (send audio).

**Comment by ntqp97** [comment]
thank you for your supports. I'll close this issue.
