### ISSUE TITLE
RTMP to Streaming Server/CDN

### ISSUE THREAD

**Issue by Challengo** [pedroSG94/rtmp-rtsp-stream-client-java#931]
Hello,

I set up my RTMP Camera and am ready to stream to a server.
I also got a CDN and a domain.
I was now wondering how I can get that RTMP stream to the CDN (probably over a streaming server).
There are some easy solutions like Wowza but for my project this is no option because of the price (it will be a social media platform like twitch where everyone can stream).
Does anyone have a solution where I can maybe stream directly to the CDN (it's BelugaCDN/BunnyCDN) or an affordable solution that would work for receiving the RTMP streams and sending them as HLS (not necessarily HLS and RTMP) to the CDN?

Best Regards,
Philipp

**Comment by pedroSG94** [comment]
If you are looking a server you can check this:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/wiki/Media-servers-tested
The better choice for a scalable free server could be Nginx or Srs but you need know how to implement it because you need install all manually.

**Comment by Challengo** [comment]
Thank you for the quick response, I will look through the list and close the issue when I find something! :)

**Comment by Challengo** [comment]
To run and implement the server I need a VPS right?
Or is there any other solution?

**Comment by pedroSG94** [comment]
Yes, you need a VPS or buy a IP and create your own server in local
