### ISSUE TITLE
License and Use

### ISSUE THREAD

**Issue by Challengo** [pedroSG94/rtmp-rtsp-stream-client-java#933]
Hello, 

what about the license to use this library? 
What License(s) do I need to mention when using the library?
Am I allowed to use this library and the services of it for free and unlimited for my application?

Best Regards

**Comment by pedroSG94** [comment]
Yes, you can use this for free. Read this for more info:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/LICENSE.txt

**Comment by Challengo** [comment]
This means I only attribute to the Apache License 2.0, but not you and your project, right?

**Comment by pedroSG94** [comment]
Maybe this link is easier to understand:
https://en.wikipedia.org/wiki/Apache_License
Basically:
- You can't change author, patent, trademark and attribution notices to the code. 
- You can't change license of unmodified files

**Comment by Challengo** [comment]
Okay, my question wasn't a bit confusing xD

I have understood how you need to implement the Apache 2.0 License, but haven't found any information to attribute you and your project, like: https://github.com/hdodenhof/CircleImageView (README -> License)

The attribution would look like: "This software uses CircleImageView - Apache 2.0 License - Copyright 2014 - 2020 Henning Dodenhof"

(The question is just about attribution to your project in addition to the standard Apache attribution.)

**Comment by pedroSG94** [comment]
That is not necessary, but if you want to do it. It is always apreciated
