### ISSUE TITLE
The issue with example

### ISSUE THREAD

**Issue by hoangcongtuan** [pedroSG94/rtmp-rtsp-stream-client-java#938]
I have try implement retry feature, I look at your example but look like it not run propertly
https://drive.google.com/file/d/1UqzZKj2LuTTHK1SIDcnEBwXn51ZWLUcV/view?usp=sharing

**Comment by pedroSG94** [comment]
Can I assume that you tested all in an emulator (previous post included)?
Can you share me emulator specifications?

**Comment by pedroSG94** [comment]
Also, please compile last commit because I can see that you are working with 2.0.5 and that method (disconnect) was changed recently.

**Comment by hoangcongtuan** [comment]
Ah, I see, I clone your repository on June, now I update the latest and the issue is disappear, thanks a lot

**Comment by pedroSG94** [comment]
> Ah, I see, I clone your repository on June, now I update the latest and the issue is disappear, thanks a lot

Both issues?

**Comment by hoangcongtuan** [comment]
Yes, the latest commit fix both issue 👍

**Comment by pedroSG94** [comment]
Nice, closing both issues
