### ISSUE TITLE
Can I stream just audio only via RTMP with this library?

### ISSUE THREAD

**Issue by jpage4500** [pedroSG94/rtmp-rtsp-stream-client-java#942]
Hi, I'm researching a project that needs to send audio only to a RTMP server.

Is that possible with this library? I see audio and video setup options but nothing excluding video completely

```
if (rtspCamera1.prepareAudio(int bitrate, int sampleRate, boolean isStereo, boolean echoCanceler,
      boolean noiseSuppressor) && rtspCamera1.prepareVideo(int width, int height, int fps, int bitrate, int rotation)) {
```

**Comment by pedroSG94** [comment]
You can use RtmpOnlyAudio class for it.

**Comment by jpage4500** [comment]
thanks for the quick reply - I'll try that!
