### ISSUE TITLE
How to rotate output RTSP stream by 90 degrees? How to remove audio stream completely?

### ISSUE THREAD

**Issue by lchy12345** [pedroSG94/rtmp-rtsp-stream-client-java#944]
I am using RTSPServerDisplay to stream screen capture with mediaprojection. Is there any way to rotate the stream by 90 degrees so that when I watch the stream on computer is will be landscape (my app is portrait).

Also, I would only like to stream video only and completely remove the audio stream. I have tried to comment on the MicrophoneManager and AudioEncoder in the DisplayBase.java. When I play the video in computer, there is no sound. However, when I check the Codec Info, there is still two stream: stream 0 is video and stream 1 is audio. I want to remove stream 1.

Thank you very much.

**Comment by pedroSG94** [comment]
To rotate, try change rotation parameter in prepareVideo method.

About audio track if you want remove it from player (Anyway it is declared but no used) you need remove it in connect and metadata packets:
- This line:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/pedro/rtmp/rtmp/CommandsManager.kt#L113
- Lines 184 to 187:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/pedro/rtmp/rtmp/CommandsManager.kt#L184
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/pedro/rtmp/rtmp/CommandsManager.kt#L187

**Comment by lchy12345** [comment]
Thanks for your quick response. However, both solution seems not working.

**Comment by pedroSG94** [comment]
Oh my fail, you are using this project:
https://github.com/pedroSG94/RTSP-Server

I will check it.
About orientation, what do you want? landscape resolution with black borders?
This is normally automatically handled by all players when you rescale player to adjust to your pc screen.
For example, open with VLC and maximize VLC window

**Comment by pedroSG94** [comment]
I did a commit to add setOnlyVideo. Please, update library to last commit.

To discard audio track you need call:
```java 
rtspServer.setOnlyVideo(true)
```

**Comment by lchy12345** [comment]
Thank you, I will have a try on the new function.

Regarding the orientation, my app is in portrait. However, I would like it to stream out as landscape so that I do not need to do anything on the player to make it landscape (now when I make it full screen on pc, the video is portrait with black border on the side) (I want it to be full screen landscape).

Thanks again.

**Comment by lchy12345** [comment]
BTW, may I know how to set fixed frame rate and bit rate? I have set the frame rate and bit rate in preparevideo function. However, when I check the bit rate and fps of the output stream, they are not constant.

**Comment by lchy12345** [comment]
The new function works well for me. Thank you so much.

Regarding the orientation, I still have no idea how can I rotate it.

Regarding the bitrate and frame rate, I saw "set bitrate mode CBR" in the log. But the bitrate and fps are still varying in the output RTSP stream. Is there any way to make them constant?

Thanks in advance.

**Comment by lchy12345** [comment]
Also, I got this error when my client disconnected. Any suggestion on how to solve? Thanks.

E/Command: cSeq not found
    cSeq not found
E/Command: cSeq not found
E/Command: cSeq not found
    cSeq not found
E/Client: Client disconnected
    java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:117)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:161)
        at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
        at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at java.io.BufferedWriter.flush(BufferedWriter.java:254)
        at com.pedro.rtspserver.ServerClient.run(ServerClient.kt:53)

**Comment by pedroSG94** [comment]
> Regarding the bitrate and frame rate, I saw "set bitrate mode CBR" in the log. But the bitrate and fps are still varying in the output RTSP stream. Is there any way to make them constant?

The fps will be the closest value to your fps value set in preparevideo depend of your internet bandwidth (if you have a poor connection the library could discard frames) and your device performance (if you can't handle more fps for hardware reasons). If you have a constant fps using 30fps but the fps is not working fine with lowest value, this could be a library bug. In this case let me know:
Mode used (camera1, display, etc), view used (openglview, surfaceview) and preparevideo configuration.

CBR means that you will have a packets with a more constant size. Remember that keyframe is an exception to this rule. Also, it  depends of codec implementation, it isn't related with this code because it is normally a device provider responsability to develop the codec implementation.

About the "cSeq not found" it is normal, you don't need to worry about it. It is because when you disconnect a client, the server still try to read response from that client and get this error because the response is null and server still don't know that this socket is closed. It is not a mandatory bug and I will solve it in the future.

**Comment by pedroSG94** [comment]
> Regarding the orientation, I still have no idea how can I rotate it.

If prepareVideo method is not working for you. Try using rotate filter:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L264
Also, you can rotate and flip using this methods of openglview:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/view/OpenGlViewBase.java#L87

If it is not working as expected share me a photo with current state and desired result to know how to handle it.

**Comment by lchy12345** [comment]
Thank you. I will have a try on that.

**Comment by lchy12345** [comment]
Thanks so much. I solved the problem.
