### ISSUE TITLE
version 2.0.9 filter has a major bug

### ISSUE THREAD

**Issue by Rethen** [pedroSG94/rtmp-rtsp-stream-client-java#945]
![image](https://user-images.githubusercontent.com/7802673/134607872-4c1b8349-dd56-461f-a718-09db2eaa875d.png)
If  I  not set  “numFilter” in  xml ，numFilter is  0  and  when i  set  filter  in  java  code，it's  must  crash

**Comment by pedroSG94** [comment]
Fixed in 2.1.0.

Now, this is working as expected and wiki was updated too.

- 0 or less -> Infinite filters.
- 1 or more -> limited filters, app will crash if you exceed this value.

0 value to disable filters (limit to 0) has no sense because it is the same that use any value and never set a filter. Also, if you want disable filters, LightOpenGlView is a better option beacause the render is faster than OpenGlView without filters. For this reason 0 is infinity

**Comment by Rethen** [comment]
> Fixed in 2.1.0.
> 
> Now, this is working as expected and wiki was updated too.
> 
> * 0 or less -> Infinite filters.
> * 1 or more -> limited filters, app will crash if you exceed this value.
> 
> 0 value to disable filters (limit to 0) has no sense because it is the same that use any value and never set a filter. Also, if you want disable filters, LightOpenGlView is a better option beacause the render is faster than OpenGlView without filters. For this reason 0 is infinity

Ok，I will try thanks

**Comment by Rethen** [comment]
> > Fixed in 2.1.0.
> > Now, this is working as expected and wiki was updated too.
> > 
> > * 0 or less -> Infinite filters.
> > * 1 or more -> limited filters, app will crash if you exceed this value.
> > 
> > 0 value to disable filters (limit to 0) has no sense because it is the same that use any value and never set a filter. Also, if you want disable filters, LightOpenGlView is a better option beacause the render is faster than OpenGlView without filters. For this reason 0 is infinity
> 
> Ok，I will try thanks

Now，Have other bug
![image](https://user-images.githubusercontent.com/7802673/134644041-6dc61c0d-9e64-4eb7-a2fe-697e7e4ad4ca.png)

**Comment by Rethen** [comment]
I  add  a  imagefilter  and then clear filter  ，and then  add  new imagefilter，and  it's  crash

**Comment by pedroSG94** [comment]
This is working for me.

What are you doing exactly?

numFilters to 0 in xml, addFilter, clearFilters and addFilters?

**Comment by Rethen** [comment]
> This is working for me.
> 
> What are you doing exactly?
> 
> numFilters to 0 in xml, addFilter, clearFilters and addFilters?

Yes，i not to  set  xml  numFilters
![image](https://user-images.githubusercontent.com/7802673/134646954-9d32dff4-7cc9-4a7e-bc0e-1b2f7679b4fb.png)

**Comment by Rethen** [comment]
> > This is working for me.
> > What are you doing exactly?
> > numFilters to 0 in xml, addFilter, clearFilters and addFilters?
> 
> Yes，i not to set xml numFilters
> ![image](https://user-images.githubusercontent.com/7802673/134646954-9d32dff4-7cc9-4a7e-bc0e-1b2f7679b4fb.png)

My business needs need to switch between a filter and no filter gas

**Comment by pedroSG94** [comment]
Are you using addfilter(0, filter)?

**Comment by Rethen** [comment]
> Are you using addfilter(0, filter)? or addfilter(filter)?

![image](https://user-images.githubusercontent.com/7802673/134648280-4c8103f1-2908-4c5b-92bd-9480785f1cbb.png)

**Comment by pedroSG94** [comment]
Try this gradle:
```gradle
	        implementation 'com.github.pedroSG94:rtmp-rtsp-stream-client-java:e8c29fb570'
```

**Comment by Rethen** [comment]
> Try this gradle:
> 
> ```groovy-gradle
> implementation 'com.github.pedroSG94:rtmp-rtsp-stream-client-java:rtsplibrary:e8c29fb570'
> ```

Dependency failure

**Comment by Rethen** [comment]
> Try this gradle:
> 
> ```groovy-gradle
> implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:e8c29fb570'
> ```

you can try with your  demo app，no use  addFilter(NoFileterRender())，just  use clearFilter()

**Comment by pedroSG94** [comment]
I checked it with last commit and it is working fine.

Did you update app example to get last commit?

Updated gradle:
```gradle
implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:e8c29fb570'
```

**Comment by Rethen** [comment]
> I checked it with last commit and it is working fine.
> 
> Did you update app example to get last commit?
> 
> Updated gradle:
> 
> ```groovy-gradle
> implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:e8c29fb570'
> ```

implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:e8c29fb570'
Depend on success now ，and  i  trying now

**Comment by Rethen** [comment]
> I checked it with last commit and it is working fine.
> 
> Did you update app example to get last commit?
> 
> Updated gradle:
> 
> ```groovy-gradle
> implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:e8c29fb570'
> ```

![image](https://user-images.githubusercontent.com/7802673/134654320-0f534d20-4c17-4437-af03-82866d1b6c5f.png)

this bug is fixed now ，but  there is a new  bug now，I think it may be related to bitmaps, but in the 2.0.8 version, bitmaps are transmitted normally。

![image](https://user-images.githubusercontent.com/7802673/134654670-d6454aee-3e3d-4ff9-a93a-8750d280a89d.png)

**Comment by pedroSG94** [comment]
I think that all problems should be solved now:
```gradle
implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:38cefae298'
```

Please, confirm me that all is working fine to create a new release

**Comment by Rethen** [comment]
> I think that all problems should be solved now:
> 
> ```groovy-gradle
> implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:38cefae298'
> ```
> 
> Please, confirm me that all is working fine to create a new release

**Comment by Rethen** [comment]
> > I think that all problems should be solved now:
> > ```
> > implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:38cefae298'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please, confirm me that all is working fine to create a new release

Sorry, I took a vacation two days ago，I will try this today

**Comment by Rethen** [comment]
I updated the 2.1.2 version. Fortunately, all the exceptions that caused the program to exit were resolved, but when I added an image filter and then deleted the image filter, the streaming failed

![image](https://user-images.githubusercontent.com/7802673/134831561-5cea7ba4-4c3b-4a9d-a092-4861811f1702.png)

**Comment by pedroSG94** [comment]
I can't reproduce your problem.
Do you have bitrate adapter?
Can you reproduce this error in opengl example? (I tried it with clearfilters in [no filter button](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L158))

**Comment by Rethen** [comment]
> I can't reproduce your problem.
> Do you have bitrate adapter?
> Can you reproduce this error in opengl example? (I tried it with clearfilters in [no filter button](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L158))

I think this should be caused by the creation of bitmap

![image](https://user-images.githubusercontent.com/7802673/134876243-dad2b4c0-21bd-4ac1-a2fe-0a87ffc26b30.png)

**Comment by pedroSG94** [comment]
It should be fine. Any way try set filter size to full stream size:
```java
val bitmap = createBitmap(
      ...
    )
    imageObjectFilterRender.setImage(bitmap)
    //100% width, 100% height (full preview size and full stream size)
    imageObjectFilterRender.setScale(100f, 100f)
    imageObjectFilterRender.setPosition(TranslateTo.CENTER)
    rtmpCamera2.glInterface.setFilter(imageObjectFilterRender)
```

Also, since you are using an Android view you can use this filter:
```
//This filter update automatically if you change layout externally. 
// For example: if you change a button color, you can see that change on fly.
AndroidViewFilterRender androidViewFilterRender = new AndroidViewFilterRender();
androidViewFilterRender.setView(view);
androidViewFilterRender.setScale(100f, 100f);
androidViewFilterRender.setPosition(TranslateTo.CENTER);
```

Anyway, if possible share me layout content (with necessary resources) to emulate your case.

**Comment by Rethen** [comment]
> It should be fine. Anyway try set filter size to full stream size instead of setdefaultscale:
> 
> ```java
> val bitmap = createBitmap(
>       ...
>     )
>     imageObjectFilterRender.setImage(bitmap)
>     //100% width, 100% height (full preview size and full stream size)
>     imageObjectFilterRender.setScale(100f, 100f)
>     imageObjectFilterRender.setPosition(TranslateTo.CENTER)
>     rtmpCamera2.glInterface.setFilter(imageObjectFilterRender)
> ```
> 
> Also, since you are using an Android view you can use this filter:
> 
> ```
> //This filter update automatically if you change layout externally. 
> // For example: if you change a button color, you can see that change on fly.
> AndroidViewFilterRender androidViewFilterRender = new AndroidViewFilterRender();
> androidViewFilterRender.setView(view);
> androidViewFilterRender.setScale(100f, 100f);
> androidViewFilterRender.setPosition(TranslateTo.CENTER);
> ```
> 
> Anyway, if possible share me layout content (with necessary resources) to emulate your case.

<FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/fl_empty"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/colorBg">


    <LinearLayout
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
        android:orientation="vertical">


        <androidx.appcompat.widget.AppCompatImageView
            android:id="@+id/iv_pause_empty"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center_horizontal"
            android:src="@drawable/ic_live_pause" />


        <androidx.appcompat.widget.AppCompatTextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center_horizontal"
            android:layout_marginTop="16dp"
            android:text="@string/live_pause_desc"
            android:textColor="@color/colorTextSecondary"
            android:textSize="12sp" />


    </LinearLayout>


</FrameLayout>



this  is  my  layout content

**Comment by Rethen** [comment]
private fun setImageToStream() {
        val imageObjectFilterRender = ImageObjectFilterRender()

        val view = layoutInflater.inflate(R.layout.layout_stop_live, null, false)
        val bitmap = createBitmap(
            view,
            ScreenUtils.getScreenWidth(this),
            ScreenUtils.getScreenHeight(this)
        )
        imageObjectFilterRender.setImage(
            bitmap
        )
         imageObjectFilterRender.setDefaultScale(
             ScreenUtils.getScreenWidth(this),
             ScreenUtils.getScreenHeight(this)
         )
        imageObjectFilterRender.setPosition(TranslateTo.CENTER)
        rtmpCamera2?.glInterface!!.setFilter(imageObjectFilterRender)

    }


    private fun createBitmap(v: View, width: Int, height: Int): Bitmap? {
        val measuredWidth = View.MeasureSpec.makeMeasureSpec(width, View.MeasureSpec.EXACTLY)
        val measuredHeight = View.MeasureSpec.makeMeasureSpec(height, View.MeasureSpec.EXACTLY)
        v.measure(measuredWidth, measuredHeight)
        v.layout(
            0,
            0,
            v.measuredWidth,
            v.measuredHeight
        )
        val bmp = Bitmap.createBitmap(
            v.width,
            v.height,
            Bitmap.Config.ARGB_8888
        )
        val c = Canvas(bmp)
        c.drawColor(Color.WHITE)
        v.draw(c)
        return bmp
    }


And  this  is  my  kotlin  code  。just  createBitmap  and  setFilter

**Comment by pedroSG94** [comment]
I can' reproduce it.
I did my own filters based in your files:
- A class to create image filter (I replaced ScreenUtil with other way to get screen size  because I haven't dependencie):
```kotlin
class Test {


  fun setFilter(stream: RtmpCamera2, activity: Activity) {
   val imageObjectFilterRender = ImageObjectFilterRender()
    val view = activity.layoutInflater.inflate(R.layout.layout_stop_live, null, false)
    val displayMetrics = DisplayMetrics()
    activity.windowManager.defaultDisplay.getMetrics(displayMetrics)
    val height = displayMetrics.heightPixels
    val width = displayMetrics.widthPixels

    val bitmap = createBitmap(view, width, height)
    imageObjectFilterRender.setImage(bitmap)
    imageObjectFilterRender.setDefaultScale(width, height)
    imageObjectFilterRender.setPosition(TranslateTo.CENTER)
    stream.glInterface!!.setFilter(imageObjectFilterRender)
  }

  private fun createBitmap(v: View, width: Int, height: Int): Bitmap? {
    val measuredWidth = View.MeasureSpec.makeMeasureSpec(width, View.MeasureSpec.EXACTLY)
    val measuredHeight = View.MeasureSpec.makeMeasureSpec(height, View.MeasureSpec.EXACTLY)
    v.measure(measuredWidth, measuredHeight)
    v.layout(
      0,
      0,
      v.measuredWidth,
      v.measuredHeight
    )
    val bmp = Bitmap.createBitmap(
      v.width,
      v.height,
      Bitmap.Config.ARGB_8888
    )
    val c = Canvas(bmp)
    c.drawColor(Color.WHITE)
    v.draw(c)
    return bmp
  }
}
```

- Layout (I changed image icon and textview text and text color):
```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_gravity="center"
    android:orientation="vertical">


    <androidx.appcompat.widget.AppCompatImageView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center_horizontal"
        android:src="@drawable/icon_camera" />


    <androidx.appcompat.widget.AppCompatTextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center_horizontal"
        android:layout_marginTop="16dp"
        android:text="Live"
        android:textSize="12sp" />


</LinearLayout>
```

In OpenGlRtmpActivity:
- Replace setImageToStream method to:
```java
    new Test().setFilter(rtmpCamera2, this);
```
- Use clearFilter to remove image in noFilter menu button.
- Replace RtmpCamera1 to RtmpCamera2

Can you compile my app example and check it?
A PR, fork project and share me a link or something where I can compile an apk with the issue could be really helpfull

**Comment by Rethen** [comment]
> > I can' reproduce it.
> > I did my own filters based in your files:
> > 
> > * A class to create image filter (I replaced ScreenUtil with other way to get screen size  because I haven't dependencie):
> > 
> > ```kotlin
> > class Test {
> > 
> > 
> >   fun setFilter(stream: RtmpCamera2, activity: Activity) {
> >    val imageObjectFilterRender = ImageObjectFilterRender()
> >     val view = activity.layoutInflater.inflate(R.layout.layout_stop_live, null, false)
> >     val displayMetrics = DisplayMetrics()
> >     activity.windowManager.defaultDisplay.getMetrics(displayMetrics)
> >     val height = displayMetrics.heightPixels
> >     val width = displayMetrics.widthPixels
> > 
> >     val bitmap = createBitmap(view, width, height)
> >     imageObjectFilterRender.setImage(bitmap)
> >     imageObjectFilterRender.setDefaultScale(width, height)
> >     imageObjectFilterRender.setPosition(TranslateTo.CENTER)
> >     stream.glInterface!!.setFilter(imageObjectFilterRender)
> >   }
> > 
> >   private fun createBitmap(v: View, width: Int, height: Int): Bitmap? {
> >     val measuredWidth = View.MeasureSpec.makeMeasureSpec(width, View.MeasureSpec.EXACTLY)
> >     val measuredHeight = View.MeasureSpec.makeMeasureSpec(height, View.MeasureSpec.EXACTLY)
> >     v.measure(measuredWidth, measuredHeight)
> >     v.layout(
> >       0,
> >       0,
> >       v.measuredWidth,
> >       v.measuredHeight
> >     )
> >     val bmp = Bitmap.createBitmap(
> >       v.width,
> >       v.height,
> >       Bitmap.Config.ARGB_8888
> >     )
> >     val c = Canvas(bmp)
> >     c.drawColor(Color.WHITE)
> >     v.draw(c)
> >     return bmp
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * Layout (I changed image icon and textview text and text color):
> > 
> > ```
> > <?xml version="1.0" encoding="utf-8"?>
> > <LinearLayout
> >     xmlns:android="http://schemas.android.com/apk/res/android"
> >     android:layout_width="wrap_content"
> >     android:layout_height="wrap_content"
> >     android:layout_gravity="center"
> >     android:orientation="vertical">
> > 
> > 
> >     <androidx.appcompat.widget.AppCompatImageView
> >         android:layout_width="wrap_content"
> >         android:layout_height="wrap_content"
> >         android:layout_gravity="center_horizontal"
> >         android:src="@drawable/icon_camera" />
> > 
> > 
> >     <androidx.appcompat.widget.AppCompatTextView
> >         android:layout_width="wrap_content"
> >         android:layout_height="wrap_content"
> >         android:layout_gravity="center_horizontal"
> >         android:layout_marginTop="16dp"
> >         android:text="Live"
> >         android:textSize="12sp" />
> > 
> > 
> > </LinearLayout>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In OpenGlRtmpActivity:
> > 
> > * Replace setImageToStream method to:
> > 
> > ```java
> >     new Test().setFilter(rtmpCamera2, this);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * Use clearFilter to remove image in noFilter menu button.
> > * Replace RtmpCamera1 to RtmpCamera2
> > 
> > Can you compile my app example and check it?
> > A PR, fork project and share me a link or something where I can compile an apk with the issue could be really helpfull

OK，I  will try

**Comment by Rethen** [comment]
> > > I can' reproduce it.
> > > I did my own filters based in your files:
> > > 
> > > * A class to create image filter (I replaced ScreenUtil with other way to get screen size  because I haven't dependencie):
> > > 
> > > ```kotlin
> > > class Test {
> > > 
> > > 
> > >   fun setFilter(stream: RtmpCamera2, activity: Activity) {
> > >    val imageObjectFilterRender = ImageObjectFilterRender()
> > >     val view = activity.layoutInflater.inflate(R.layout.layout_stop_live, null, false)
> > >     val displayMetrics = DisplayMetrics()
> > >     activity.windowManager.defaultDisplay.getMetrics(displayMetrics)
> > >     val height = displayMetrics.heightPixels
> > >     val width = displayMetrics.widthPixels
> > > 
> > >     val bitmap = createBitmap(view, width, height)
> > >     imageObjectFilterRender.setImage(bitmap)
> > >     imageObjectFilterRender.setDefaultScale(width, height)
> > >     imageObjectFilterRender.setPosition(TranslateTo.CENTER)
> > >     stream.glInterface!!.setFilter(imageObjectFilterRender)
> > >   }
> > > 
> > >   private fun createBitmap(v: View, width: Int, height: Int): Bitmap? {
> > >     val measuredWidth = View.MeasureSpec.makeMeasureSpec(width, View.MeasureSpec.EXACTLY)
> > >     val measuredHeight = View.MeasureSpec.makeMeasureSpec(height, View.MeasureSpec.EXACTLY)
> > >     v.measure(measuredWidth, measuredHeight)
> > >     v.layout(
> > >       0,
> > >       0,
> > >       v.measuredWidth,
> > >       v.measuredHeight
> > >     )
> > >     val bmp = Bitmap.createBitmap(
> > >       v.width,
> > >       v.height,
> > >       Bitmap.Config.ARGB_8888
> > >     )
> > >     val c = Canvas(bmp)
> > >     c.drawColor(Color.WHITE)
> > >     v.draw(c)
> > >     return bmp
> > >   }
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > * Layout (I changed image icon and textview text and text color):
> > > 
> > > ```
> > > <?xml version="1.0" encoding="utf-8"?>
> > > <LinearLayout
> > >     xmlns:android="http://schemas.android.com/apk/res/android"
> > >     android:layout_width="wrap_content"
> > >     android:layout_height="wrap_content"
> > >     android:layout_gravity="center"
> > >     android:orientation="vertical">
> > > 
> > > 
> > >     <androidx.appcompat.widget.AppCompatImageView
> > >         android:layout_width="wrap_content"
> > >         android:layout_height="wrap_content"
> > >         android:layout_gravity="center_horizontal"
> > >         android:src="@drawable/icon_camera" />
> > > 
> > > 
> > >     <androidx.appcompat.widget.AppCompatTextView
> > >         android:layout_width="wrap_content"
> > >         android:layout_height="wrap_content"
> > >         android:layout_gravity="center_horizontal"
> > >         android:layout_marginTop="16dp"
> > >         android:text="Live"
> > >         android:textSize="12sp" />
> > > 
> > > 
> > > </LinearLayout>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > In OpenGlRtmpActivity:
> > > 
> > > * Replace setImageToStream method to:
> > > 
> > > ```java
> > >     new Test().setFilter(rtmpCamera2, this);
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > * Use clearFilter to remove image in noFilter menu button.
> > > * Replace RtmpCamera1 to RtmpCamera2
> > > 
> > > Can you compile my app example and check it?
> > > A PR, fork project and share me a link or something where I can compile an apk with the issue could be really helpfull
> 
> OK，I will try

If I need a fixed resolution, and the screen is full screen, and the picture preview does not produce distortion, how should I set it in xml

**Comment by pedroSG94** [comment]
What do you mean? I don't understand.

Can you reproduce error using that code? I can create a branch with my code and we can work in that branch to reproduce the error.

**Comment by Rethen** [comment]
> What do you mean? I don't understand.
> 
> Can you reproduce error using that code? I can create a branch with my code and we can work in that branch to reproduce the error.

I am not describing the previous problem, I just want to set a fixed resolution (such as 1920*1080) when streaming, but not all mobile phones have a resolution of 1920*1080. What can I do to make all phones preview in full screen

**Comment by pedroSG94** [comment]
Full screen image filter no matter screen resolution because it is wokring in percent:
```java
imageObjectFilterRender.setScale(100f, 100f);
```

**Comment by Rethen** [comment]
> Full screen image filter no matter screen resolution because it is wokring in percent:
> 
> ```java
> imageObjectFilterRender.setScale(100f, 100f);
> ```


 I mean  when I don’t add any filters and the resolution of the stream transmission is less than the screen resolution, how do I set it to distort the picture in the full screen state?

![image](https://user-images.githubusercontent.com/7802673/135067305-58f4a5d6-4d16-49a8-b017-9076d2be3e3f.png)

Obviously, the picture is distorted

**Comment by Rethen** [comment]
> Ah ok.
> If you want full screen without distortion in preview you can use aspect ratio mode fill:
> 
> ```
> <com.pedro.rtplibrary.view.OpenGlView
>       android:layout_width="match_parent"
>       android:layout_height="match_parent"
>       android:id="@+id/surfaceView"
>       app:keepAspectRatio="true"
>       app:aspectRatioMode="fill"
>       app:AAEnabled="false"
>       app:numFilters="1"
>       app:isFlipHorizontal="false"
>       app:isFlipVertical="false"
>       />
> ```
> 
> * adjust: Adapt to preview size doing black borders to avoid distortion.
> * fill: Full preview size cropping borders to adapt screen resolution and avoid distortion.
> 
> This have no effect to stream result, this is only for preview

Ok, all problems are solved, thank you very much
