### ISSUE TITLE
Can't restart stream while recording

### ISSUE THREAD

**Issue by ggpaeg** [pedroSG94/rtmp-rtsp-stream-client-java#946]
Hi,

My application uses a background service to record all time. During the recording, the user needs to start a stream and stop sometimes. 
The problem occurs when a stream is stopped and started again, in that situation I got the following error:
`E/H264Packet: waiting for a valid sps and pps`

I figured that I need to call prepareVideo and prepareAudio methods, but I can't do that while recording. It's not viable to stop recording to restart stream.
Is there any solution to restart the stream several times while recording?

**Comment by pedroSG94** [comment]
Fixed in 2.1.2:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/6e1dfb6a5617c316a5c1e1f423519592186f96c1

**Comment by ggpaeg** [comment]
Working perfectly! Thanks @pedroSG94!
