### ISSUE TITLE
ExampleRtspActivity does not connect

### ISSUE THREAD

**Issue by duilio82** [pedroSG94/rtmp-rtsp-stream-client-java#947]
I want to test the Default RTSP example with the url "rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov" but it does not connect. It enter in `ExampleRtspActivity.onConnectionFailedRtsp` and show Retry message
I checked the url "rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov" with VLC and it works.

Thanks in advanced!

**Comment by pedroSG94** [comment]
Hello,

It is working as expected because this is not a player, this is a pusher library.
If you want a player you can check it (it is only a vlc example I recommend you compile library yourself if you want last version):
https://github.com/pedroSG94/vlc-example-streamplayer
