### ISSUE TITLE
Can not streaming rtmp with camera1

### ISSUE THREAD

**Issue by devhuyhq** [pedroSG94/rtmp-rtsp-stream-client-java#95]
I try to live stream video with camera1 android but the video can not publish to server

wrote packet: RTMP Video, size: 16
wrote packet: RTMP Video, size: 16
wrote packet: RTMP Video, size: 16

Logcat show some logs I think could help you

**Comment by pedroSG94** [comment]
For some reason you send only packet header. For now I will need some info to know where is the problem. 

Can you tell me gradle version or commit used?
This is only on a specific device? 
Did you tried with camera2 or openglview in camera1?
Can you write a log of buffer in this lines?:

Log.e("Debug h264", "data=" + byteBuffer.remaining());
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/net/ossrs/rtmp/SrsFlvMuxer.java#L211

Log.e("Debug frame", "data=" + frame.data.remaining() + ", size=" + frame.size);
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/net/ossrs/rtmp/SrsFlvMuxer.java#L766

Log.e("Debug pps", "data=" + frame_pps.data.remaining() + ", size=" + frame_pps.size);
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/net/ossrs/rtmp/SrsFlvMuxer.java#L771

Log.e("Debug pps", "data=" + frame_sei.data.remaining() + ", size=" + frame_sei.size);
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/net/ossrs/rtmp/SrsFlvMuxer.java#L780

This to know where is the fail.
