### ISSUE TITLE
Low bitrate even when network upload speed is strong

### ISSUE THREAD

**Issue by MichHighlander** [pedroSG94/rtmp-rtsp-stream-client-java#958]
Hello, i am using SrsFlvMuxer and VideoEncoder to send video to a Red5 server,
and for some reason even after i set the bitrate of the VideoEncoder to 5 * 1024 * 1024 i still get bitrates of 200KB/s - 1.2MB/s.
I am not using adaptive bitrate and even if use the bitrate adapter it doesn't have any effect, also tried to different devices.
This is my code:

### Init Function:
 if (videoEncoder == null) videoEncoder = new VideoEncoder(this);
 if (srsFlvMuxer == null) srsFlvMuxer = new SrsFlvMuxer(this);
 videoEncoder.setForce(CodecUtil.Force.FIRST_COMPATIBLE_FOUND);
 videoEncoder.prepareVideoEncoder(vidWidth, vidHeight, 24, 5 * 1024 * 1024, 0, 2, FormatVideoEncoder.YUV420PLANAR);
 srsFlvMuxer.setIsStereo(true);
 srsFlvMuxer.setSampleRate(44100);
 srsFlvMuxer.setVideoResolution(videoEncoder.getWidth(), videoEncoder.getHeight());
 videoEncoder.start();
 srsFlvMuxer.start(broadcastUrl);

### Sending YuvData to encoder
if (videoEncoder != null && videoEncoder.isRunning()) videoEncoder.inputYUVData(frame);

## Sending encoded data to Muxer
 @Override
    public void getVideoData(ByteBuffer h264Buffer, MediaCodec.BufferInfo info) {
        srsFlvMuxer.sendVideo(h264Buffer, info);
    }

**Comment by pedroSG94** [comment]
You have a callback to know bitrate send to server:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/defaultexample/ExampleRtmpActivity.java#L110
It seems that you are using an old library version. I don't know if you need update it or not but I recommend you update it and check that callback.
Also, remember that:
- That callback include audio bitrate.
- Bitrate could change depend of encoding mode (VBR or CBR) and image renderer.
- Bitrate could change if you send less fps that the indicated in prepareVideo.
- MB is not the same that Mb.
