### ISSUE TITLE
App is hanging when rtmpcamera1.stopStream() is called

### ISSUE THREAD

**Issue by prudhvicoder** [pedroSG94/rtmp-rtsp-stream-client-java#96]
When I called rtmpcamera1.stopStream() my app is hanging and the log is going on like this.

**LOG**
`12-05 20:35:04.818 25071-25170/com.tube.codegama.tubenow I/SrsFlvMuxer: frame discarded
12-05 20:35:04.821 25071-25163/com.tube.codegama.tubenow D/ACodec: [OMX.MTK.VIDEO.ENCODER.AVC] onOutputBufferDrained ID 14
12-05 20:35:04.838 25071-25071/com.tube.codegama.tubenow I/CameraFramework: handleMessage: 16
12-05 20:35:04.841 25071-25121/com.tube.codegama.tubenow I/BufferQueueProducer: [SurfaceTexture-0-25071-0](this:0x999af800,id:0,api:4,p:265,c:25071) queueBuffer: fps=29.89 dur=1037.12 max=67.55 min=9.77
12-05 20:35:04.864 25071-25163/com.tube.codegama.tubenow D/ACodec: give LatencyToken 247, 5510
12-05 20:35:04.886 25071-25071/com.tube.codegama.tubenow I/CameraFramework: handleMessage: 16
12-05 20:35:04.896 25071-25188/com.tube.codegama.tubenow I/SrsFlvMuxer: frame discarded
12-05 20:35:04.899 25071-25188/com.tube.codegama.tubenow I/SrsFlvMuxer: frame discarded
12-05 20:35:04.917 25071-25163/com.tube.codegama.tubenow D/ACodec: [OMX.MTK.VIDEO.ENCODER.AVC] onInputBufferFilled ID 9 w/ time 26877646 eos 0 mode 1 err 0
12-05 20:35:04.919 25071-25170/com.tube.codegama.tubenow I/SrsFlvMuxer: frame discarded
12-05 20:35:04.919 25071-25163/com.tube.codegama.tubenow D/ACodec: [OMX.MTK.VIDEO.ENCODER.AVC] onOutputBufferDrained ID d
12-05 20:35:04.947 25071-25121/com.tube.codegama.tubenow I/BufferQueueProducer: [SurfaceTexture-0-25071-0](this:0x999af800,id:0,api:4,p:265,c:25071) queueBuffer: slot 0 is dropped, handle=0x9dd48c80
12-05 20:35:04.961 25071-25163/com.tube.codegama.tubenow D/ACodec: give LatencyToken 248, 5995
12-05 20:35:04.962 25071-25071/com.tube.codegama.tubenow I/CameraFramework: handleMessage: 16
12-05 20:35:04.965 25071-25071/com.tube.codegama.tubenow D/SettingsInterface:  from settings cache , name = sound_effects_enabled , value = 0
12-05 20:35:04.965 25071-25071/com.tube.codegama.tubenow D/AudioRecord: stop
12-05 20:35:04.965 25071-25071/com.tube.codegama.tubenow D/AudioTrackShared: front(422080), mIsOut 0, interrupt() FUTEX_WAKE
12-05 20:35:04.965 25071-25188/com.tube.codegama.tubenow D/AudioTrackShared: obtainBuffer() interrupted by client
12-05 20:35:04.966 25071-25188/com.tube.codegama.tubenow I/SrsFlvMuxer: frame discarded
12-05 20:35:04.968 25071-25086/com.tube.codegama.tubenow I/BufferQueueProducer: [SurfaceTexture-0-25071-0](this:0x999af800,id:0,api:4,p:265,c:25071) queueBuffer: slot 2 is dropped, handle=0xb37f89a0
12-05 20:35:05.018 25071-25071/com.tube.codegama.tubenow D/AudioRecord: -stop
12-05 20:35:05.018 25071-25071/com.tube.codegama.tubenow D/AudioRecord: stop
12-05 20:35:05.018 25071-25071/com.tube.codegama.tubenow D/AudioRecord: stop
12-05 20:35:05.018 25071-25071/com.tube.codegama.tubenow D/AudioRecord: stop
12-05 20:35:05.018 25071-25071/com.tube.codegama.tubenow D/AudioTrackShared: front(422080), mIsOut 0, interrupt() FUTEX_WAKE
12-05 20:35:05.019 25071-25071/com.tube.codegama.tubenow I/MicrophoneManager: Microphone stopped
12-05 20:35:05.021 25071-25121/com.tube.codegama.tubenow D/AudioSystem: getIoDescriptor: ioHandle = 899, index = 2, mIoDescriptors = 0xab3e2f68
12-05 20:35:05.028 25071-25163/com.tube.codegama.tubenow D/ACodec: [OMX.MTK.VIDEO.ENCODER.AVC] onInputBufferFilled ID 10 w/ time 26989416 eos 0 mode 1 err 0
12-05 20:35:05.029 25071-25219/com.tube.codegama.tubenow I/BufferQueueProducer: [SurfaceTexture-0-25071-0](this:0x999af800,id:0,api:4,p:265,c:25071) queueBuffer: slot 4 is dropped, handle=0x9dd4b200
12-05 20:35:05.031 25071-25170/com.tube.codegama.tubenow I/SrsFlvMuxer: frame discarded
12-05 20:35:05.031 25071-25163/com.tube.codegama.tubenow D/ACodec: [OMX.MTK.VIDEO.ENCODER.AVC] onOutputBufferDrained ID e
12-05 20:35:05.056 25071-25121/com.tube.codegama.tubenow I/BufferQueueProducer: [SurfaceTexture-0-25071-0](this:0x999af800,id:0,api:4,p:265,c:25071) queueBuffer: slot 1 is dropped, handle=0x9dd4b0c0
12-05 20:35:05.068 25071-25163/com.tube.codegama.tubenow D/ACodec: give LatencyToken 249, 5470
12-05 20:35:05.072 25071-25086/com.tube.codegama.tubenow I/BufferQueueProducer: [SurfaceTexture-0-25071-0](this:0x999af800,id:0,api:4,p:265,c:25071) queueBuffer: slot 0 is dropped, handle=0x9dd48c80
12-05 20:35:05.098 25071-25085/com.tube.codegama.tubenow I/BufferQueueProducer: [SurfaceTexture-0-25071-0](this:0x999af800,id:0,api:4,p:265,c:25071) queueBuffer: slot 2 is dropped, handle=0xb37f89a0
12-05 20:35:05.131 25071-25086/com.tube.codegama.tubenow I/BufferQueueProducer: [SurfaceTexture-0-25071-0](this:0x999af800,id:0,api:4,p:265,c:25071) queueBuffer: slot 4 is dropped, handle=0x9dd4b200
12-05 20:35:05.169 25071-25085/com.tube.codegama.tubenow I/BufferQueueProducer: [SurfaceTexture-0-25071-0](this:0x999af800,id:0,api:4,p:265,c:25071) queueBuffer: slot 1 is dropped, handle=0x9dd4b0c0
12-05 20:35:05.201 25071-25086/com.tube.codegama.tubenow I/BufferQueueProducer: [SurfaceTexture-0-25071-0](this:0x999af800,id:0,api:4,p:265,c:25071) queueBuffer: slot 0 is dropped, handle=0x9dd48c80
12-05 20:35:05.231 25071-25085/com.tube.codegama.tubenow I/BufferQueueProducer: [SurfaceTexture-0-25071-0](this:0x999af800,id:0,api:4,p:265,c:25071) queueBuffer: slot 2 is dropped, handle=0xb37f89a0
12-05 20:35:05.270 25071-25086/com.tube.codegama.tubenow I/BufferQueueProducer: [SurfaceTexture-0-25071-0](this:0x999af800,id:0,api:4,p:265,c:25071) queueBuffer: slot 4 is dropped, handle=0x9dd4b200
12-05 20:35:05.321 25071-25085/com.tube.codegama.tubenow I/BufferQueueProducer: [SurfaceTexture-0-25071-0](this:0x999af800,id:0,api:4,p:265,c:25071) queueBuffer: slot 1 is dropped, handle=0x9dd4b0c0
12-05 20:35:05.345 25071-25086/com.tube.codegama.tubenow I/BufferQueueProducer: [SurfaceTexture-0-25071-0](this:0x999af800,id:0,api:4,p:265,c:25071) queueBuffer: slot 0 is dropped, handle=0x9dd48c80
12-05 20:35:05.366 25071-25085/com.tube.codegama.tubenow I/BufferQueueProducer: [SurfaceTexture-0-25071-0](this:0x999af800,id:0,api:4,p:265,c:25071) queueBuffer: slot 2 is dropped, handle=0xb37f89a0
12-05 20:35:05.400 25071-25086/com.tube.codegama.tubenow I/BufferQueueProducer: [SurfaceTexture-0-25071-0](this:0x999af800,id:0,api:4,p:265,c:25071) queueBuffer: slot 4 is dropped, handle=0x9dd4b200
12-05 20:35:05.441 25071-25085/com.tube.codegama.tubenow I/BufferQueueProducer: [SurfaceTexture-0-25071-0](this:0x999af800,id:0,api:4,p:265,c:25071) queueBuffer: slot 1 is dropped, handle=0x9dd4b0c0
12-05 20:35:05.469 25071-25086/com.tube.codegama.tubenow I/BufferQueueProducer: [SurfaceTexture-0-25071-0](this:0x999af800,id:0,api:4,p:265,c:25071) queueBuffer: slot 0 is dropped, handle=0x9dd48c80
12-05 20:35:05.500 25071-25085/com.tube.codegama.tubenow I/BufferQueueProducer: [SurfaceTexture-0-25071-0](this:0x999af800,id:0,api:4,p:265,c:25071) queueBuffer: slot 2 is dropped, handle=0xb37f89a0
12-05 20:35:05.534 25071-25086/com.tube.codegama.tubenow I/BufferQueueProducer: [SurfaceTexture-0-25071-0](this:0x999af800,id:0,api:4,p:265,c:25071) queueBuffer: slot 4 is dropped, handle=0x9dd4b200
12-05 20:35:05.591 25071-25085/com.tube.codegama.tubenow I/BufferQueueProducer: [SurfaceTexture-0-25071-0](this:0x999af800,id:0,api:4,p:265,c:25071) queueBuffer: slot 1 is dropped, handle=0x9dd4b0c0
12-05 20:35:05.610 25071-25086/com.tube.codegama.tubenow I/BufferQueueProducer: [SurfaceTexture-0-25071-0](this:0x999af800,id:0,api:4,p:265,c:25071) queueBuffer: slot 0 is dropped, handle=0x9dd48c80
12-05 20:35:05.633 25071-25085/com.tube.codegama.tubenow I/BufferQueueProducer: [SurfaceTexture-0-25071-0](this:0x999af800,id:0,api:4,p:265,c:25071) queueBuffer: slot 2 is dropped, handle=0xb37f89a0
12-05 20:35:05.667 25071-25086/com.tube.codegama.tubenow I/BufferQueueProducer: [SurfaceTexture-0-25071-0](this:0x999af800,id:0,api:4,p:265,c:25071) queueBuffer: slot 4 is dropped, handle=0x9dd4b200
12-05 20:35:05.710 25071-25085/com.tube.codegama.tubenow I/BufferQueueProducer: [SurfaceTexture-0-25071-0](this:0x999af800,id:0,api:4,p:265,c:25071) queueBuffer: slot 1 is dropped, handle=0x9dd4b0c0
12-05 20:35:05.733 25071-25086/com.tube.codegama.tubenow I/BufferQueueProducer: [SurfaceTexture-0-25071-0](this:0x999af800,id:0,api:4,p:265,c:25071) queueBuffer: slot 0 is dropped, handle=0x9dd48c80`

I'm using rtmpcamera1 with AutofitTextureView, could you please help me out?

**Comment by pedroSG94** [comment]
Can you try with my app example and show me log from you press stop?
