### ISSUE TITLE
Streaming and recording with different quality, using OpenGl views

### ISSUE THREAD

**Issue by LucaBL** [pedroSG94/rtmp-rtsp-stream-client-java#967]
Hi, I was following the answer to this issue (#284), although it seems OpenGl is not used in this case (videoEncoder2 is used only when glInterface is null).
I need to use OpenGl views to add filters, so it seems it's not what I need.
Would it be possible to see a working example of having two different encoders receiving video data when glInterface is not null? I tried all day but I'm stumped.
Thank you very much!

**Comment by pedroSG94** [comment]
Hello,

The case with glinterface should be similar in your case but you need create another constructor in Camera2ApiManager using SurfaceTexture with resolution (in this case 2 SurfaceTexture with 2 resolutions):
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java#L131

Also, as the second glinterface to provide the second SurfaceTexture I recommend you an OffScreenGlThread.

**Comment by LucaBL** [comment]
Thank you for the quick response! I'll try and let you know.

**Comment by LucaBL** [comment]
Is it ok to create a second glInterface with the same context?

      glInterface = new OffScreenGlThread(context);
      glInterface.init();
      glInterface2 = new OffScreenGlThread(context);
      glInterface2.init();
      
It seems I can't shake off this error:
checkAndUpdateEglState: invalid current EGLContext


Should I have 2 different OpenGlViews on screen?

**Comment by pedroSG94** [comment]
You don't need create a second glInterface, You should create a second ManagerRender inside of the glInterface

**Comment by LucaBL** [comment]
It seems I managed to get it working that way, thank you very much.

For future readers, what gave me errors during that approach was that I was trying to apply the same filter (BaseFilterRender) to both ManagerRenders, but doubling both the filters and the filter queues, so that each ManagerRender gets different filters from its own queue, did the trick.
Also for the ManagerRender handling the streaming, I made it do basically everything the main one does, except the 'drawScreen' done for the preview on screen (with 'isPreview' as true).

**Comment by florianmlr** [comment]
Hello, I'm trying to reproduce it. How do you specify an OffScreenGlThread as the second SurfaceTexture without creating a new glInterface ?
Did you create a new managerRender in the `OpenGlViewBase` as well ?

**Comment by florianmlr** [comment]
Can you help me for this @LucaBL @pedroSG94  ?

**Comment by LucaBL** [comment]
Hi, yes, in both `OffScreenGlThread` and `OpenGlView`+`OpenGlViewBase` I added a second SurfaceManager (the one named surfaceManagerEncoder), a second ManagerRender, a second BlockingQueue<Filter>, and a second set of encoder width and height, right where the first ones were.

Then initialize and configure them like the first ones, and add methods to `GlInterface` to set or get both of them. Reflect these methods also on the other classes implementing this interface.

**Comment by florianmlr** [comment]
Thank you @LucaBL I have an other question, where did you call prepareCamera( with the second surfaceTexture ?

**Comment by LucaBL** [comment]
> Thank you @LucaBL I have an other question, where did you call prepareCamera( with the second surfaceTexture ?

In Camera2ApiManager I added this method:
`public void prepareCamera(SurfaceTexture[] surfaceTextures,
                            int width, int height, int width2, int height2, int fps) {
    surfaceTextures[0].setDefaultBufferSize(width, height);
    this.surfaceEncoder = new Surface(surfaceTextures[0]);
    surfaceTextures[1].setDefaultBufferSize(width2, height2);
    this.surfaceEncoder2 = new Surface(surfaceTextures[1]);
    this.fps = fps;
    prepared = true;
  }`
  
This method is called in several points in Camera2Base more or less like this:
`cameraManager.prepareCamera(this.glInterface.getSurfaceTextures(),
              videoEncoder.getWidth(), videoEncoder.getHeight(),
              videoEncoder2.getWidth(), videoEncoder2.getHeight(),
              videoEncoder.getFps());`

GlInterface has a method like this:
`SurfaceTexture[] getSurfaceTextures();`

Which is implemented like this in its implementations:
`@Override
  public SurfaceTexture[] getSurfaceTextures() {
    return new SurfaceTexture[] {
            managerRender.getSurfaceTexture(),
            managerRender2.getSurfaceTexture(),
    };
  }`
  
  Hope it helps.

**Comment by user97116** [comment]
There is no 'ManagerRender' `surfaceEncoder', 'OffScreenGlThread', can you provide updated code @pedroSG94 @LucaBL

**Comment by pedroSG94** [comment]
Hello,

OffScreenGlThread was replaced with GlStreamInterface
ManagerRender was replaced to MainRender
surfaceEncoder is still present inside Camera2ApiManager
