### ISSUE TITLE
Rtmp stats

### ISSUE THREAD

**Issue by TepesLucian** [pedroSG94/rtmp-rtsp-stream-client-java#976]
I've briefly looked over the sdk and wanted to ask if there are any stats that we can collect and inspect over time like fps, bitrate, jitter etc. similar to webRTC stats?

**Comment by pedroSG94** [comment]
Jitter is the delay  right?. It is not possible but you can get fps and bps.
fps. Use this code:
```java
rtmpCamera1.setFpsListener(new FpsListener.Callback() {
      @Override
      public void onFps(int fps) {
        
      }
    });
```
bps. You have a callback:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/openglexample/OpenGlRtmpActivity.java#L378

**Comment by TepesLucian** [comment]
Fps and bitrate look like a good start, thanks!
